### ISSUE TITLE
Validation error: mandatory parameters missing

### ISSUE THREAD

**Issue by amitm02** [drakkan/sftpgo#100]
I've run sftpgo with a "memory" driver.
In the admin dashboard, I've tried to add a new user but I'm keep getting:
"Validation error: mandatory parameters missing banner" even though I've selected Storage to be "S3". 
The only way I got this message to go away, was to add a value to "Home Dir" field. 
But if I do that, it seems to try to download from that folder instead from S3 and fails (list files seems to work fine).

`sftpgo_1                     | {"level":"warn","time":"2020-03-22T19:15:19.777","sender":"sftpd","connection_id":"c5839bda8eee4bb1a5471a46237630ef3dfc376fede9f86464af7203c0804315","message":"could not open file \"/Screen Shot 2020-03-22 at 10.08.25.png\" for reading: open /app/amit/pipefile010203927: no such file or directory"}`

<img width="1439" alt="Screen Shot 2020-03-22 at 21 17 42" src="https://user-images.githubusercontent.com/1888927/77258339-b1a2b480-6c82-11ea-8c84-791a312c8f5e.png">

**Comment by drakkan** [comment]
A local home directory is required to store temporary files.

Can you please attach the full logs?

**Comment by amitm02** [comment]
yes, your solution worked

**Comment by drakkan** [comment]
> yes, your solution worked.

thanks for confirming

> I would add to the logs that "A local home directory is required to store temporary files." even for s3/google storage. :)

this is documented already :) please take a look at the last sentence here:

https://github.com/drakkan/sftpgo/blob/master/docs/s3.md

**Comment by amitm02** [comment]
what I meant was that It would be beneficial to know in https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md what properties are optional and what are required.

**Comment by drakkan** [comment]
> what I meant was that It would be beneficial to know in https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md what properties are optional and what are required.

Ok, I'll try to improve the docs later today, anyway if you want you can simply clone the repo modify the doc and send a pull request. I think that docs written from a user perspective could be better, additionally english is not my native language.
