### ISSUE TITLE
HTTP redirect to HTTPS

### ISSUE THREAD

**Issue by tanvp112** [drakkan/sftpgo#1003]
Hi,

I have setup and run sftpgo v2.3.5 with TLS support with no issue.

But when I tried to redirect HTTP to HTTPS follow the guide mentioned [here](https://github.com/drakkan/sftpgo/issues/777#issuecomment-1089911273) and browse to http://domain:8080, the request didn't get redirect but a plain text response saying "**Client sent an HTTP request to an HTTPS server.**"

Same response if I also set _httpd.bindings[0].security.enabled_ to **true** and set a host name for _httpd.bindings[0].security.https_host_.

Is there any other setting needed for the redirect?

**Comment by drakkan** [comment]
Hi,

you need an HTTP binding that redirect to your HTTPS enabled binding

**Comment by tanvp112** [comment]
Ok, thanks!

**Comment by huiyang-work** [comment]
> Hi,
> 
> you need an HTTP binding that redirect to your HTTPS enabled binding

how to do it?

**Comment by huiyang-work** [comment]
> > Hi,
> > you need an HTTP binding that redirect to your HTTPS enabled binding
> 
> how to do it?

![image](https://user-images.githubusercontent.com/24961929/213715204-58e08825-bb34-4694-a29a-0873105ee731.png)
don't work ...

**Comment by drakkan** [comment]
> > > Hi,
> > > you need an HTTP binding that redirect to your HTTPS enabled binding
> > 
> > 
> > how to do it?
> 
> ![image](https://user-images.githubusercontent.com/24961929/213715204-58e08825-bb34-4694-a29a-0873105ee731.png) don't work ... sftpgo on windows 11.

sure, there is no redirect rule here.

**Comment by huiyang-work** [comment]
> > > > 嗨，您需要一个重定向到启用 HTTPS 的绑定的 HTTP 绑定
> > > 
> > > 
> > > 怎么办？
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/24961929/213715204-58e08825-bb34-4694-a29a-0873105ee731.png)不工作...Windows 11 上的 SFTPGO。
> 
> 当然，这里没有重定向规则。

need nginx for redirect ，or others configuration in sftpgo？

**Comment by drakkan** [comment]
> > > > > 嗨，您需要一个重定向到启用 HTTPS 的绑定的 HTTP 绑定
> > > > 
> > > > 
> > > > 怎么办？
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/24961929/213715204-58e08825-bb34-4694-a29a-0873105ee731.png)不工作...Windows 11 上的 SFTPGO。
> > 
> > 
> > 当然，这里没有重定向规则。
> 
> need nginx for redirect ，or others configuration in sftpgo？

other sftpgo configurations, read the first post in this thread. nginx will also work. 
I no longer provide free support sorry, please read the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by huiyang-work** [comment]
Thank you for your hard work. I hope your donation can support the Alipay channel. Thank you very much! There is no PayPal service in China. Your project is great and deserves more support!

**Comment by drakkan** [comment]
> Thank you for your hard work. I hope your donation can support the Alipay channel. Thank you very much! There is no PayPal service in China. Your project is great and deserves more support!

I'm trying to get Alipay approved, but it seems really difficult. I'll keep you updated. Thank you

**Comment by drakkan** [comment]
> Thank you for your hard work. I hope your donation can support the Alipay channel. Thank you very much! There is no PayPal service in China. Your project is great and deserves more support!

You can now purchase one time support plans from the website using Alipay
