### ISSUE TITLE
WebDAV multiple HTTPS binding

### ISSUE THREAD

**Issue by drakkan** [drakkan/sftpgo#1006]
I am wanting to achieve my all users can get access on a web client by their hostname which should be domains, instead of using IPs. I am trying to add certficates for each domain in webdav server under the configuration file of sftpgo. I created multiple bindings with domain cerfticates in webdav server, but the problem is that each binding containing unique id which is port. It suppose to be on a same port and it should be add multilple certificates of domain. So my users can access on a web client with TLS/SSL connections (HTTPS). Please guide how to implement each domain certificates on same port of webdav server with enable https mode into the configuration file of sftpgo.

_Originally posted by @jatinvishwa12 in https://github.com/drakkan/sftpgo/issues/452#issuecomment-1262298874_

**Comment by drakkan** [comment]
@jatinvishwa12 please post the relevant SFTPGo config, thanks

**Comment by jatinvishwa12** [comment]
"webdavd": {
  "bindings": [	  
	  {	
		"port": 2006,
		"address": "domain1.com",
		"enable_https": true,
		"certificate_file": "domain1.com.crt",
		"certificate_key_file": "domain1.com.key",
        "min_tls_version": 12,
        "client_auth_type": 0,
        "tls_cipher_suites": [],
        "prefix": "",
        "proxy_allowed": [],
        "client_ip_proxy_header": "",
        "client_ip_header_depth": 0
      },
	  {	
		"port": 2006,
		"address": "domain2.com",
		"enable_https": true,
		"certificate_file": "domain2.com.crt",
		"certificate_key_file": "domain2.com.key",
        "min_tls_version": 12,
        "client_auth_type": 0,
        "tls_cipher_suites": [],
        "prefix": "",
        "proxy_allowed": [],
        "client_ip_proxy_header": "",
        "client_ip_header_depth": 0
      }
    ],

**Comment by drakkan** [comment]
This way SFTPGo will resolve `domain1.com` and `domain2.com` and it will try to bind on the resolved IP addresses. If both the domains resolve to the same IP address then SFTPGo will fail to start.
If you want to setup name-based virtual hosting do this in Apache/NGINX and then configure a proxy to your SFTPGo instance

**Comment by jatinvishwa12** [comment]
Ok i will try these things and if there is any issue I will let you know. Thanks

**Comment by drakkan** [comment]
> Ok i will try these things and if there is any issue I will let you know. Thanks

as expected, you disappeared ...
