### ISSUE TITLE
signing_passphrase and bolt provider with externalauth does not work for multi nodes

### ISSUE THREAD

**Issue by tooptoop4** [drakkan/sftpgo#1008]
on a brand new installation with 2 nodes and same SFTPGO_HTTPD__SIGNING_PASSPHRASE set on both, login to webui works but then shows pages like:

`The server is unable to fulfill your request. not found: username "iredacted" does not exist`

OR

`Failed to get directory listing: Unable to retrieve your user`

but then if i use sftp commandline a few times, then the UI starts to work

i guess because the .bolt file on one of the nodes would be empty until it received traffic

**Comment by drakkan** [comment]
bolt provider cannot be shared. It is documented
