### ISSUE TITLE
Question about Virtual Folders

### ISSUE THREAD

**Issue by bryantsmith24450** [drakkan/sftpgo#1012]
Hello,

I'm looking for some clarification on the Statement under Virtual Folders for users:

"Quota -1 means included within user quota, 0 unlimited. Don't set -1 for shared folders"

For the users i have been setting the Quota bytes to -1 for the Virtual Folders, under the assumption that this will give the user the same quota to the virtual directory as their user quota.  Is this correct or am i understanding this statement wrong?  

Thanks in advance!

**Comment by drakkan** [comment]
closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
