### ISSUE TITLE
[BUG] Combination of haproxy protocol, ftp, passive and data connections don't work

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#1013]
I'm unsure if this has been reported before - couldn't find any issue relating.

I have sftpgo containers configured behind a Network balancer, configured with sftp & ftp (both plain & ssl); basically ports 22, 21 & 990. I also have configured passive port range and a force passive IP address.

This worked, until I wanted to upgrade. There were no issues on v2.0.4, I upgraded to v2.1.0 and I believe the problem started with v2.2.0. I proceeded to upgrade to v2.3.5, with the same problem persisting.

With the haproxy configuration, the network balancer prefixes any tcp connection with client information. This is a way to provide the backend (sftpgo) with information about the actual client (eg. to write in the logs).

This works for the connection ports, but from v2.2.0 onward it seems to fail for de data ports (used only with the FTP protocol).

I see the following error:

```json
{"level":"warn","time":"2022-10-06T10:42:57.187","sender":"ftpserverlib","server_id":"FTP_0","clientId":"5","error":"data connection security requirements not met","message":"Unable to open transfer"}
{"level":"warn","time":"2022-10-06T10:42:57.187","sender":"ftpserverlib","server_id":"FTP_0","clientId":"5","err":"data connection ip address [loadbalancer address] does not match control connection ip address [actual client address]","message":"Could not validate passive data connection requirement"}
```

This is returned in [this code](https://github.com/fclairamb/ftpserverlib/blob/main/client_handler.go#L682-L712)

I expect we either need a way to set `IPMatchDisabled`, or (prefereably) set the `dataConnIP` to the correct IP address?

**Comment by drakkan** [comment]
Hi,

this is a security feature, not a bug. The SFTPGo version that works for you is vulnerable to data connection stealing attacks. 
I no longer have time for free step-by-step support I'm sorry. You have to update your haproxy configuration. You can find some useful details here:

https://github.com/fclairamb/ftpserverlib/commit/c387884850161def55593d829c9c12925a0288fb

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
