### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by maxiride** [drakkan/sftpgo#1014]
I browsed a bit the docs without finding info about it.

Is it possible to graceful shutdown the server as in:

- stop accepting new connection
- let ongoing transfers complete
- shutdown when all transfers are complete\client disconnects\timeout\idle etc

**Comment by maxiride** [comment]
Thanks for the reply,

> could potentially take an indefinite time (think about a client uploading a large file over a slow connection)

Indeed, more often than not in applications that offer this functionality there is a grace period after that the processes/whatever gets killed.


If it's a feature that is not of interest for the project, the ticket can be closed I suppose.

**Comment by drakkan** [comment]
Hi,

it might be useful but before working on this I want to better understand how similar programs handle graceful shutdown. I see that ProFTPD has an [ftpshut](http://www.proftpd.org/docs/howto/Stopping.html) program which looks a bit different. Can you please provide links to other SFTPGo-like applications that implement this feature? Thanks
