### ISSUE TITLE
Preserving file modification time when uploading via WebDAV into local storage

### ISSUE THREAD

**Issue by Kirrrr** [drakkan/sftpgo#1018]
I'm fresh new here so maybe I just didn't get something. Searching through closed issues gave me nothing.

I run sftpgo under Windows 10. I have exposed local folder for some user. It works fine. Web access and FTP access are all ok. The product is really great.
WebDAV is working ok too in general. I tested it with native Windows Explorer client and with Total Commander plugin. 
But if I upload a file via WebDAV (using any client) then the modification time of the uploaded file are changing to the current time. It is pretty frustrating when one are trying to use WebDAV share as an alternative to SMB or FTP shares.

I know that the preserving of the file modification time in WebDAV is a long complicated story. But, anyway, is that an intended behaviour or not in case of using WebDAV with a local folder?

Regards.

(sorry for clumsy English)

**Comment by drakkan** [comment]
Hi,

please explain how your client is setting the modification time. Thanks

**Comment by Kirrrr** [comment]
Well... good question. :)
I have not much ideas on how to provide it for now.

Just uploaded a test file. In `sftpgo.log` I see a request record with `"method":"PROPPATCH"` for my test file just before a record with `"method":"UNLOCK"`. It seems to be a some properties setting after transfer. But `sftpgo.log` doesn't contain details of the requests. How can I get this details? (without setting up a debug proxy I hope :) )

**Comment by drakkan** [comment]
> Well... good question. :) I have not much ideas on how to provide it for now.
> 
> Just uploaded a test file. In `sftpgo.log` I see a request record with `"method":"PROPPATCH"` for my test file just before a record with `"method":"UNLOCK"`. It seems to be a some properties setting after transfer. But `sftpgo.log` doesn't contain details of the requests. How can I get this details? (without setting up a debug proxy I hope :) )

wireshark or something similar

**Comment by drakkan** [comment]
Maybe I have a limited PROPPATCH support as described [here](https://github.com/mar10/wsgidav/issues/112#issuecomment-398863104). Either way, wireshark's dumps will help you better understand what the clients you're testing are doing. 

A sponsorship could help, are you interested to [support SFTPGo](https://github.com/drakkan/sftpgo#sponsors)?

**Comment by Kirrrr** [comment]
> a limited PROPPATCH support as described here
Oops. I didn't find that disqussion. 
Yeah, I will try to dig it with Wireshark. I'll write about results a bit later.

>A sponsorship could help, are you interested to support SFTPGo?
I'll think about it.

**Comment by Kirrrr** [comment]
Here is it.
PROPPATCH XML request body generated by Windows Explorer WebDAV client (aka WebDAV-MiniRedir):
```
<?xml version="1.0" encoding="utf-8"?>
<D:propertyupdate xmlns:D="DAV:" xmlns:Z="urn:schemas-microsoft-com:">
  <D:set>
    <D:prop>
      <Z:Win32LastModifiedTime>Wed, 02 Feb 2011 14:03:31 GMT</Z:Win32LastModifiedTime>
      <Z:Win32FileAttributes>00000020</Z:Win32FileAttributes>
    </D:prop>
  </D:set>
</D:propertyupdate>
```
PROPPATCH XML request body generated by Total Commander WebDAV client plugin:
```
<?xml version="1.0" encoding="utf-8"?>
<D:propertyupdate xmlns:D="DAV:" xmlns:Z="urn:schemas-microsoft-com:">
  <D:set>
    <D:prop>
      <D:getlastmodified>Wed, 2 Feb 2011 14:03:31 GMT</D:getlastmodified>
      <Z:Win32LastModifiedTime>Wed, 2 Feb 2011 14:03:31 GMT</Z:Win32LastModifiedTime>
    </D:prop>
  </D:set>
</D:propertyupdate>
```
They are almost identical and both are using `Win32LastModifiedTime` property.
Additionally TC plugin is trying to do the best sending `getlastmodified` property too as a backup.
And Explorer also sending a standard WinAPI file attributes double-word `Win32FileAttributes`.
