### ISSUE TITLE
Provided web interface is unusable

### ISSUE THREAD

**Issue by mikroskeem** [drakkan/sftpgo#102]
Current web interface set up by sftpgo is unusable because the built in web server does not provide Content-Type header.

![image](https://user-images.githubusercontent.com/3490861/77456777-64e6e700-6e04-11ea-92d9-38c61e683e50.png)

Any solutions to that besides setting up a reverse proxy and serving assets myself?

Bonus: _The article what Firefox wants me (or you) to read: [link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options)_

**Comment by drakkan** [comment]
Hi,

thank you for reporting this issue. Please help me to reproduce it locally. The web interface seems to work fine for me using both Firefox 74 and Chormium 80. 

Additionally if I try something like this:

```
curl --verbose "http://127.0.0.1:8080/static/vendor/jquery/jquery.min.js"
```

I get a proper content type header:

```
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /static/vendor/jquery/jquery.min.js HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 88145
< Content-Type: application/javascript
< Last-Modified: Mon, 07 Oct 2019 13:47:04 GMT
< Date: Tue, 24 Mar 2020 17:29:05 GMT
< 
```

as you can see the Content-Type is `application/javascript`. I get the same from chromium

![Schermata del 2020-03-24 18-46-52](https://user-images.githubusercontent.com/553263/77459534-28b18780-6e00-11ea-8fc9-86ce239d8abe.png)

do you have some non standard firefox plugin? Are you able to reproduce the issue with another browser?

I will be glad to fix this issue once I'm able to reproduce locally, thanks

**Comment by mikroskeem** [comment]
Holy shit what a PEBKAC situation, I managed to mess up and not copy over `static` folder 🤦‍♂ 

Pinging the sftpgo instance was showing suspicious 404 and that ringed a bell for me.

This issue is invalid, sorry.

**Comment by drakkan** [comment]
OK thanks!
