### ISSUE TITLE
sftpgo does not honor $SFTPGO_LOG_LEVEL

### ISSUE THREAD

**Issue by volkerwestphal** [drakkan/sftpgo#1022]
From full-configuration.md:

> The serve command supports the following flags:
>
> `--log-level` string. Set the log level. ...
>  Default debug or the value of SFTPGO_LOG_LEVEL 
> environment variable.

So I understand that setting the environment variable SFTPGO_LOG_LEVEL=info  will omit all debug-level log messages from the logs.

However, the variable is not changing the behavior of sftpgo, at least under Linux x64.

How to reproduce:

```
$ SFTPGO_LOG_FILE_PATH= SFTPGO_LOG_LEVEL=info  sftpgo serve
{"level":"info","time":"2022-10-13T11:11:14.379","sender":"service","message":"starting SFTPGo 2.3.6-66c14beb-2022-10-12T17:03:16Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: , log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, log utc time: false, load data from: \"\""}
{"level":"debug","time":"2022-10-13T11:11:14.379","sender":"config","message":"no configuration file found"}
```
... lots of `"level":"debug"` messages to follow ...

The same behavior has already been seen in v2.3.5. 

Additionally, sftpgo does not accept the `--log-level` option

```
$ sftpgo serve --log-level
Error: unknown flag: --log-level
Usage:
  sftpgo serve [flags]
```

**Comment by drakkan** [comment]
duplicated of #1004
