### ISSUE TITLE
unable to execute python code for dynamic user creation 

### ISSUE THREAD

**Issue by navnitkum** [drakkan/sftpgo#1025]
i am trying to create dynamic user via OIDC login if the user doesnt exsist 

below is my python code
```
import os
import json

name = "SFTPGO_LOGIND_USER"
ipAddress = "SFTPGO_LOGIND_IP"
protocol = "SFTPGO_LOGIND_PROTOCOL"

status = 1

x = {
    "username" : os.environ.get(name)
}

y = json.dumps(x)

print(y)
```

when i am trying to run this python code via dockerfile it is not able to run python , with error   **### exec format error**
may i know how can i install python inside this docker container , or if anyone can help me with a hint for , how to create dynamic user when login happen via OIDC

**Comment by drakkan** [comment]
closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by tooptoop4** [comment]
@navnitkum u need a shebang line at top of the .py
