### ISSUE TITLE
Login Failed: Unsupported cipher

### ISSUE THREAD

**Issue by harryhahn** [drakkan/sftpgo#1028]
How ca we solved this problem?

{"level":"debug","time":"2022-10-18T13:07:20.032","sender":"sftpd","message":"failed to accept an incoming connection: ssh: disconnect, reason 11: Unsupported cipher"}

Thanks Harry

**Comment by drakkan** [comment]
closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
