### ISSUE TITLE
Feature request: firewall based on allow lists

### ISSUE THREAD

**Issue by wokalski** [drakkan/sftpgo#1030]
Hey, first of all, my company is willing to pay for this feature.

Secondly, we would like the sftp endpoint to reject all connections but for the ones made from clients that belong to the allow lists. We would like the rules to be different for sftp and for the web GUI. So basically for the sftp port if `requesting ip = ANY(all allow list ips)` then we establish connection, otherwise reject.

**Comment by drakkan** [comment]
Hello,

thanks for your interest in SFTPGo.

If you use SFTPGo at your company then it would make business sense to sponsor SFTPGo, even if you don't need any new features, to ensure that the project you rely on stays healthy and well maintained.
If I lose interest you could end up using unmaintained software.

As for your request, it is already possible by using a [post-connect hook](https://github.com/drakkan/sftpgo/blob/main/docs/post-connect-hook.md).
Do you want I write this hook for you? If so, you can contact me at the email address you see in each commit to discuss further details.

**Comment by drakkan** [comment]
One way to do this directly within SFTPGo and thus avoid the overhead of an additional HTTP request/command to execute the external hook is to add a `whitelist_file` configuration option also in `sftpd`, `ftpd`, `httpd`, `webdavd` sections. 
If you define a `whitelist_file` in the `common` section is applied for all protocols like now. 
If you leave the `whitelist_file` blank in the `common` section and define it in the `sftpd` section, it will only apply for SSH/SFTP connections and so on

**Comment by drakkan** [comment]
It seems you are no more interested :pensive:

**Comment by wokalski** [comment]
sorry, I am, I am just a bit busy with other stuff. It's ok to close this one, but I will make sure to sponsor you/contact you once I can come back to this.

**Comment by drakkan** [comment]
Ok no problem, what do you think about https://github.com/drakkan/sftpgo/issues/1030#issuecomment-1295905214? Will this work for your use case? You don't have to answer right away, take your time to think about it, thank you

**Comment by drakkan** [comment]
This is now supported https://github.com/drakkan/sftpgo/commit/409fca43c826c285f2a92d793846ea79115a43c2
