### ISSUE TITLE
system-level permissions

### ISSUE THREAD

**Issue by jsjcjsjc** [drakkan/sftpgo#1031]
Hi
I installed sftpgo by https://github.com/drakkan/sftpgo/blob/main/docs/repo.md
and try to use directories outside the `/srv/sftpgo`, as mentioned in https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md#creating-users.

but it looks like `sudo chown sftpgo:sftpgo /home/username/test` does not work in debian 10.

could you please help me with it ?
Thanks

**Comment by drakkan** [comment]
make sure that the `sftpgo` system user has at least the read permission to any parent directory, so in the example above `/home/username` and `/home` must not have `0700` permissions.

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
