### ISSUE TITLE
Feature request: Whitelist/Safelist/Blacklist editing via UI

### ISSUE THREAD

**Issue by isaacharrisholt** [drakkan/sftpgo#1033]
The whitelist feature of SFTPGo is really great, but we have SFTPGo deployed in a Docker container, so it's difficult for non-technical users to update the whitelist etc.

It would be fantastic if this could be updated via the UI somehow rather than a file, and if it was also stored in the data backend that would also be great.

I'm imagining an extra tab in the admin UI that just allows whitelisting of addresses and networks fairly easily. Will look into opening an MR, but not 100% familiar with all the technologies used in the project.

**Comment by drakkan** [comment]
I think this should initially be developed as a plug-in/hook and eventually merged into the main repository in the future. Querying the database after each connection may not be appropriate for all use cases.

A such plugin could also fixes #1030 but I haven't heard from that request anymore.

Feel free to send a PR  if you want but please note that a PR imposes a cost on the project both immediately (for code review) and on an ongoing basis (for maintenance/evolution), I'm not sure I have enough time/motivation to review large PRs. Thanks
