### ISSUE TITLE
Log lines do not include the user id that issued the command?

### ISSUE THREAD

**Issue by ScubaDrew** [drakkan/sftpgo#1038]
Would it be possible to include the user id of the user that issued commands?

IE: `message: "new cmd, method: Rename, sourcePath: "/product/PRODUCT DATA.xlsx", targetPath: "/product/processed/PRODUCT DATA.xlsx""`

Does not tell me what user renamed this file. If I have dozens of users connected, I have no way to track.

Thanks,
Drew

**Comment by ScubaDrew** [comment]
Does not seem to match what I am seeing in https://github.com/drakkan/sftpgo/blob/main/docs/logs.md

**Comment by drakkan** [comment]
Hi,

you should have a log line like this one:

```
{"level":"info","time":"2022-10-31T18:43:48.182","sender":"Rename","local_addr":"127.0.0.1:2022","remote_addr":"127.0.0.1:35790","username":"b","file_path":"/tmp/test_home/start/dir/ros.txt","target_path":"/tmp/test_home/start/dir/ros1.txt","filemode":"","uid":-1,"gid":-1,"access_time":"","modification_time":"","size":-1,"ssh_command":"","connection_id":"SFTP_51c5f21483f087e7aac1a6afeabb9ebce8737903cd12104fa5b23c04742dddeb_1","protocol":"SFTP"}
```
the log above is emitted [here](https://github.com/drakkan/sftpgo/blob/main/internal/sftpd/handler.go#L185) and it is only a debug log. 

Transfers and commands logs are emitted at info level and are documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/logs.md).

You can also stores events in a supported database using this [plugin](https://github.com/sftpgo/sftpgo-plugin-eventstore). 
Please let me know if the above info are enough. Thanks

**Comment by ScubaDrew** [comment]
Confirmed, this was a debug log and that full log as described by @drakkan exists.
