### ISSUE TITLE
proxy_protocol causing 400 bad request on web client

### ISSUE THREAD

**Issue by Cjaiceman** [drakkan/sftpgo#1044]
When I enable 'send-proxy' in HAproxy on my pfsense machine I get a 400 Bad Request response in my browser from sftpgo when accessing it through HAproxy. If I remove 'send-proxy' I am able to reach the web interface as expected. I am also able to reach it without issue when going directly to the host instead of through HAproxy, but that is not the desired connection method. 

I have sftpgo setup in a docker container on UnRaid. I believe I followed the documentation correctly when enabling the proxy protocol, but the 400 error suggests that something is still amiss, so I have included a screen shot for review. HAproxy is at 10.10.1.1, sftpgo is hosted at 10.10.1.5. 

![proxy_protocol](https://user-images.githubusercontent.com/26099769/200213278-77ca7a95-8e01-469b-b133-4d7d938ac2b8.JPG)

**Comment by drakkan** [comment]
Check the updated [docs](https://github.com/drakkan/sftpgo/commit/4e10275fd16e9d47f62128c9f8ea83721c770f38#diff-70e627f2f0733fe85104c4dad76acd0ce373fbd9c213efd8cccfa54387e07e4c)
