### ISSUE TITLE
Failed to get directory listing: Unable to get directory contents

### ISSUE THREAD

**Issue by NeverVane** [drakkan/sftpgo#1046]
Hi, I installed SFTPGo on a fresh installation of Ubuntu 20.04 (tried also on 22.04) with docker ( tried also with daemon installation ) but when creating a new user that needs to connect to a S3 compatible storage, I get errors.

In detail, when I sftp to the newly created user I get the errors that tells me that files can't be listed and from terminal if I try to ssh into the user I get 
`PTY allocation request failed on channel 0
shell request failed on channel 0`

I tried to install SFTPGo on my own VMs and also on some Digital Ocean droplets and I get the same result ... anyone got same issue?

**Comment by drakkan** [comment]
SFTPGo does not support shell access only SFTP. Check your logs to understand the issue.
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
