### ISSUE TITLE
sftpgo 2.4.0 initprovider hashes passwords from loaddata 

### ISSUE THREAD

**Issue by mmetz-isa** [drakkan/sftpgo#1051]
Hi,

sftpgo version: SFTPGo 2.4.0-63bf8eb1-2022-10-23T04:58:19Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
uname -a: Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
os release: Debian GNU/Linux 11 (bullseye)

when bulk importing users to a sqlite backed data provider with the following command line:

```
sudo -u sftpgo sftpgo initprovider --config-dir /etc/sftpgo --loaddata-from /tmp/vsftpd-users --loaddata-clean --loaddata-mode 0
```

The password of user objects are hashed, even when the password attribute already is a password hash in crypt format.  This deviates from the previous behavior of initprovider version <= 2.3.6, where the password was passed through untouched.  Admin objects seems to use a different import routine and are only affected when the password is not a password hash in crypt format.

This change breaks in an unrecoverable manner:
  * backups obtained via REST API /dumpdata cannot be imported via initprovider (and possibly via REST API /loaddata ), as the password would be hashed twice.
  * Bulk user imports or third party imports via initprovider for the same reason when the source third party system only provides crypt formatted passhashes.
  * Using special tokens like '!', '!!' or '*' to disable password logins entirely for certain users.

As a workaround I currently inject the password hashes directly into the sqlite database.

**Comment by drakkan** [comment]
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by mmetz-isa** [comment]
May I ask why a bug report is closed?

The behaviour change is not listed in the list of incompatible changes for Release v2.4.0 and it breaks your only provided backup mechanism for data providers.

**Comment by drakkan** [comment]
Your report is invalid, your tests are inaccurate, I think I know what problem you are having and it is not related to the SFTPGo version, this is not a free help center.
If you want support you have to also support the project, this is the only way to keep SFTPGo alive in the long run. If you use SFTPGo for free you have no support. Thanks for understanding

**Comment by mmetz-isa** [comment]
> Your report is invalid, your tests are inaccurate
Will you reconsider reopening the bug report with repeatable test cases?
