### ISSUE TITLE
SeaweedFS & Empty directories

### ISSUE THREAD

**Issue by yeganemehr** [drakkan/sftpgo#1052]
Hi @drakkan 
First of all, thank you for wonderful work that you done here :heart: 

# Problem
I started an s3 service using [Seaweedfs](https://github.com/seaweedfs/seaweedfs) and a sftpgo instance with ftp enabled.
When I connect to ftp i can list/get/... my files but when I create a new directory using mkdir command I cannot change directory to it.
```
# ftp sftpgo
Connected to sftpgo.
Name (sftpgo:root): my-user
331 OK
Password:
230 Password ok, continue
Remote system type is UNIX.
Using binary mode to transfer files.

ftp> mkdir test
257 Created dir "/test"

ftp> cd test
550 Can't change directory to /test: Not a Directory
```

# Reproduce
You can follow these steps to reproduce the problem:

install seaweedfs
```
cd /tmp
wget https://github.com/seaweedfs/seaweedfs/releases/download/3.34/linux_amd64.tar.gz
tar -xvf linux_amd64.tar.gz
./weed server -filer -s3
```

In Another shell terminal:
```
./weed shell
> s3.configure -user admin -access_key admin -secret_key 123456 -actions Read,Write,List,Tagging,Admin  -apply
> s3.bucket.create -name my-bucket
```

Now spin up a portable sftpgo instance with ftp access:
```
sftpgo portable --fs-provider s3fs  --s3-access-key admin --s3-access-secret 123456 --s3-bucket my-bucket --s3-endpoint http://localhost:8333 --s3-force-path-style --ftpd-port 21 --sftpd-port -1
```

Now you connect with ftp client:
```
ftp localhost
220 SFTPGo portable 2.4.0 ready
Name (localhost:root): admin
331 OK
Password:
230 Password ok, continue
Remote system type is UNIX.
Using binary mode to transfer files.
> mkdir test
257 Created dir "/test"

ftp> cd test
550 Can't change directory to /test: Not a Directory
```

# Cuase
Because Seaweedfs actually have & support directories unlike S3, objects cannot have '/' in their name.
As far as I know sftpgo rely on '/' in object name to detect whether an object is empty directory or not.

# Suggested Solution
in [internal/vfs/s3fs.go:162](https://github.com/drakkan/sftpgo/blob/a9207857cf53d379a1b73a8dfd60ac8e16faecab/internal/vfs/s3fs.go#L162) we can check for  `application/x-directory` mimetype.
```diff
obj, err := fs.headObject(name)
if err == nil {
-	// a "dir" has a trailing "/" so we cannot have a directory here
+	isDir := *obj.ContentType == s3DirMimeType
-	return updateFileInfoModTime(fs.getStorageID(), name, NewFileInfo(name, false, obj.ContentLength,
+	return updateFileInfoModTime(fs.getStorageID(), name, NewFileInfo(name, isDir, obj.ContentLength,
		util.GetTimeFromPointer(obj.LastModified), false))
}
```

**Comment by drakkan** [comment]
Hi @yeganemehr 

thanks for the reproducer and for the tentative patch. I did a quick test and it looks good. I'll take a closed look as soon as I'm done with ongoing development (probably next weekend).

**Comment by drakkan** [comment]
Fixed https://github.com/drakkan/sftpgo/commit/6591769a07b0f48007cfa1c39b8ae1a47578d220, thanks
