### ISSUE TITLE
bandwith limit not working properly ?

### ISSUE THREAD

**Issue by matuopm** [drakkan/sftpgo#1054]
A friend of mine is regularly copying files from my sftp server but when I set no upload bandwith limit, he uses all my upload bandwith and slows down my whole network,

I use the SFTPgo as a docker container on my unraid server and in the webadmin interface I set a bandwith limit of 30000KB/s for both upload and download for his user.
![image](https://user-images.githubusercontent.com/95039636/201529261-59e1a997-1537-4481-9ed9-c7295dddbb59.png)
I saved the settings of the user, rebooted the container but my friend is still using my complete upload speed and when I look in the Dreammachine Interface it shows that I'm constantly uploading data with like 50MB/s but no other devices are uploading anything.

![image](https://user-images.githubusercontent.com/95039636/201529239-1b5cdf71-ee67-40d6-964d-ce81bd48c192.png)

Also just a question about the configuration settings:
 upload bandwith means in this case: data that is copied on to the server (using my download speed) 
 and
 download bandwith means data that is copied from my server (using my upload speed)
 right ?
 
 Anyone got a suggestion how to fix this or a hint what I'm doin wrong ?

**Comment by drakkan** [comment]
Hi,

in SFTPGo you set the limit in KB/s (Kilobytes/s) not Kilobits/s (kb/s). 
Anyway take a look at the "Connections" page in the SFTPGo Web Admin to understand what's going on.

**Comment by matuopm** [comment]
Ah greeat. I solved it now. Thanks for the hint.
