### ISSUE TITLE
Failed to delete not empty folders using the web client

### ISSUE THREAD

**Issue by dr460nf1r3** [drakkan/sftpgo#1057]
Hello! :) 

I stumbled upon an issue with deleting folders that aren't empty via the web interface using a Docker deployment. The web client errors out with:

`Unable to delete directory "/test/test1": failure`

While investigating the logfiles, I found the following error message:

`{"level":"error","time":"2022-11-14T11:11:29.375","sender":"HTTP","connection_id":"HTTP_cdp18kdc9g2i8fokftl0","message":"failed to remove directory \"/wordpress/test/test1\": remove /wordpress/test/test1: directory not empty"`

Deleting the folder via SFTP works, the content and subfolders are recursively deleted as expected.

**Comment by drakkan** [comment]
SFTP clients handle recursive deletion themselves. This isn't a server side feature.

The feature you request was added in v2.4.1. I think you are using an older version

**Comment by drakkan** [comment]
The changelog is now up to date, thanks for noticing
