### ISSUE TITLE
 Failed to get directory listing on windows via SMB in service mode

### ISSUE THREAD

**Issue by rorschach-py** [drakkan/sftpgo#1062]
Tested in windows 10 x64 and windows server 2019
 
Mount Z: via smb, set user local storage to Z:\
when sftpgo runs in user mode, everything goes well

when sftpgo runs in service mode, it reports  "Failed to get directory listing: Unable to get directory contents"

logfile:
`{"level":"error","time":"2022-11-18T19:31:17.585","sender":"osfs","connection_id":"HTTP_cdrmq1c929bjsq278fmg","message":"error creating root directory \"Z:\\\\\" for user \"aaa\": mkdir Z:\\: The system cannot find the path specified."}`

**Comment by drakkan** [comment]
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by drakkan** [comment]
This is not related to SFTPGo, this is a Windows specific question

https://www.ibm.com/support/pages/how-map-network-shares-drives-windows-service-permanently
https://superuser.com/questions/753400/map-network-drive-for-the-system-user-in-windows

**Comment by rorschach-py** [comment]
Fixed it, thank you!
