### ISSUE TITLE
http: request body too large

### ISSUE THREAD

**Issue by brunodomenici** [drakkan/sftpgo#1069]
Hello,

I have a very particular case which I have an user with 5k+ public keys and I'm using `PUT /api/v2/users/<user>` to keep the list of pub keys updated but I  got the error `{"error":"http: request body too large","message":""}` due to the request size limit (`Content-Length: 2116209`):

```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> PUT /api/v2/users/< redacted > HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.79.1
> Accept: */*
> Authorization: Bearer < redacted >
> Content-Type: application/json
> Content-Length: 2116209
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: application/json; charset=utf-8
< Date: Wed, 23 Nov 2022 17:13:39 GMT
< Content-Length: 54
< Connection: close
< 
{"error":"http: request body too large","message":""}
* Closing connection 0
```

I see the limit is 1MB: 

https://github.com/drakkan/sftpgo/blob/5a222807b72a0c1c794528241117598a028920b1/internal/httpd/httpd.go#L170

I've changed to 3MB locally and it works.

I'm happy to send a PR with this change of even include this in the configuration.

Thank you

**Comment by drakkan** [comment]
Hi,

I'm not sure, you are probably abusing the API, keep your changes locally for now, thanks
