### ISSUE TITLE
OIDC Roles

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#1076]
Currently, i do not see any way of specifying roles when setting up OIDC 

I believe we can already today specify where the roles can be found, i.e.:

`SFTPGO_HTTPD__BINDINGS__0__OIDC__ROLE_FIELD`

but they are hardcoded as admin? 

A feature request, to have the ability to override which roles that should be assigned to user/admin would be great. The only other way i can probably achieve this is do some mapping on OIDC itself, but i have managed to accomplish this in almost every other application i use with OIDC auth. Seems like i couldn't find this in SFTPGO. 

Thanks for all the great work!

**Comment by drakkan** [comment]
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by drakkan** [comment]
Hi,

thanks for supporting the project.

You can set an OIDC field with a configurable name to `admin` or if you cannot or don't want to explicitly define SFTPGo roles in your identity provider, you can set `implicit_roles` to `true`

**Comment by ryjogo** [comment]
OK Thank you - i will give it a go.
