### ISSUE TITLE
Using S3 virtual folder with external auth exposes S3 credentials

### ISSUE THREAD

**Issue by simonjenny** [drakkan/sftpgo#1077]
We are currently using SFTPGO as a SFTP to S3 Proxy for our customers successfully. We authenticate all users via Webhook with our custom backend. Doing so we need to pass along the S3 credentials in the Webhook JSON answer for the virtual directory. Is there a possibility to pass the S3 credentials another way to SFTPGO than in this JSON Response?

**Comment by drakkan** [comment]
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
