### ISSUE TITLE
Aggregate Events

### ISSUE THREAD

**Issue by tsmgeek** [drakkan/sftpgo#1078]
I am looking at the docs https://github.com/drakkan/sftpgo/blob/main/docs/eventmanager.md for filesystem events sending on repeating schedule to notify via of uploaded files.
What is not clear is if the system will aggregate all upload events on email or just send one email for each file that was uploaded.

If this is not supported I may have to instead write a service that can do this instead.

Any help would be appreciated.

**Comment by drakkan** [comment]
Aggregation is not supported in event manager. Please check the [support policy](https://github.com/drakkan/sftpgo#support-policy)
