### ISSUE TITLE
option to delete partially uploaded file (from 'max_upload_file_size' limit)

### ISSUE THREAD

**Issue by tooptoop4** [drakkan/sftpgo#1079]
currently if i upload a file bigger than max_upload_file_size size, a partial/corrupt file is saved onto s3. i would like option for sftpgo to automatically remove/cleanup that partial file

**Comment by drakkan** [comment]
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by tooptoop4** [comment]
I saw https://github.com/drakkan/sftpgo/commit/c1effdf70102992fe5990baf6e989435b7f17b29#diff-b09c54f19cb310e0f0194b9af5fa223f24e5baecf6b5d439865f1dc5de41ace8 but it has os.Remove not covering s3 delete which has atomic mode limitations

**Comment by drakkan** [comment]
Please stop this nonsense. It looks like you are not using SFTPGo but you are reading its code without understanding it.
Remember that SFTPGo is AGPLv3 licensed software, you cannot copy its code into proprietary products
