### ISSUE TITLE
Usage with MySql/Vitess database ( PlanetScale )

### ISSUE THREAD

**Issue by aKardasz** [drakkan/sftpgo#1085]
Hello,

I attempted to utilize PlanetScale as the DB, however due to the usage of foreign keys, it's not working out. I have begun looking through the code to see if I can make the changes myself, however I am having a hard time getting this to compile from my fork of the project. 

I am just seeing if there may be a possibility of getting support for dbs like planetscale put on the todo list, or maybe even some documentation for how to fork and compile the binaries (this may just be a Windows Struggle) to be able to make contributions easier. I don't really work with Go all too often but would love to support and possibly contribute code one day, however I am having one heck of a time just getting the default going. 

For example, I forked, and ran "go build -tags nogcs,nos3,nosqlite -ldflags "-s -w -X github.com/dakkan/sftpgo/v2/internal/version.commit=`git describe --always --abbrev=8 --dirty` -X github.com/aKardasz/sftpgo/v2/internal/version.date=`date -u +%FT%TZ`" -o sftpgo" after setting up the windows mingw requirement, and get stuck with the following output:
`internal\vfs\vfs.go:757:34: undefined: s3fsName 
internal\vfs\vfs.go:760:34: undefined: gcsfsName`

If I just do Go Build

**Comment by drakkan** [comment]
Hi,

the build mode with s3 and gcs disabled is now [fixed](https://github.com/drakkan/sftpgo/commit/91e4a543851e27c1f9527ee3ddc544e398bd9321). 

As for supporting a mysql dialect without foreign keys, we would have to handle foreign key constraints within the application. This is an ongoing effort and can only happen with a recurring sponsorship. Even reviewing a PR will take time and once merged I will have to maintain the feature and fix bugs forever.

**Comment by aKardasz** [comment]
Hello Drakkan,

Thank you for the fix! I have begun working on the changes to support no foreign keys, ( maybe this might be a good route to also think about using something like firebase etc ). With the sponorship peace, as much as I would love to support in a more monetary form, I just don't have the capability at this time, however I did choose your project as the first one I want to make contributions too. I do believe that even with the extra effort with the merge, this might allow for more usage of your tool. I have definitely thought of some saas type projects where utilizing this project would be beneficial, just need to do more research in what the licensing allows and does not allow for, as I am still a bit confused, but either way I do intend to contribute in the meantime however I can.

**Comment by drakkan** [comment]
Hi,

I'm sorry but without a recurring sponsorship I don't think I'll merge a such contribution. Feel free to experiment in your branch (it must be public as for AGPL V3 license, you cannot include SFTPGo code in proprietary/commercial products). 

As explained above, please understand that this is an ongoing effort. I have to think about this feature and test without foreign keys after every schema change. A database without foreign keys allows for inconsistent data, the application needs to handle these cases gracefully and so needs to be modified accordingly and we probably also need some sort of script to check and clean up orphaned data. If I'll merge a such feature I have to maintain it and fix bug reports, I don't have time/motivation sorry.

Just FYI CockroachDB is already supported and appears to have a similar pricing model and features to PlanetScale, I don't see any real benefit in supporting PlanetScale.

**Comment by aKardasz** [comment]
May you explain the license more then. If I make a public fork, and wanted to set up a data pipeline, and for example do one day want to make a service where the code and all the updates stay public, but I compile the binary myself, and use it in a docker image as just a piece of the bigger puzzle. (Just the sftp for uploading the file and retrieving it via my other code and services running), but then decide to make a service with this (hosting doesn't pay for itself) I would not be able to use this public compiled binary as a piece of the service as a whole or does this more so impact utilizing sftpGo code directly, as in adding to it and integrating it code to code directly? 

Also out of curiosity, how does this work with all the code you utilized from os project with different licensing, do you do merge requests back into their code with fixes you made? 
For example:
The service being sold is data transformation platform in the cloud. We would provide the tools to upload data ( SftpGo for sftp,  any other tools for any other upload methods like AS2, Van, rest etc ), what would be sold is the hosting, and transformation pieces, the being able to deploy a sftp server would be a feature, but someone still has to pay for the actual server, how does this work in the grand scheme of things.

**Comment by aKardasz** [comment]
https://vitess.io/blog/2021-06-15-online-ddl-why-no-fk/

Also, some extra info regarding foreign keys.

**Comment by drakkan** [comment]
> May you explain the license more then. If I make a public fork, and wanted to set up a data pipeline, and for example do one day want to make a service where the code and all the updates stay public, but I compile the binary myself, and use it in a docker image as just a piece of the bigger puzzle. (Just the sftp for uploading the file and retrieving it via my other code and services running), but then decide to make a service with this (hosting doesn't pay for itself) I would not be able to use this public compiled binary as a piece of the service as a whole or does this more so impact utilizing sftpGo code directly, as in adding to it and integrating it code to code directly?
> 

The AGPL license is quite controversial. You can easily find my interpretation in other issues, in any case I advise you to consult your lawyer (I'm not a lawyer)

> Also out of curiosity, how does this work with all the code you utilized from os project with different licensing, do you do merge requests back into their code with fixes you made? 

Sure, I became a contributor to "pkg/sftp" and "ftpserverlib" for example

> For example: The service being sold is data transformation platform in the cloud. We would provide the tools to upload data ( SftpGo for sftp, any other tools for any other upload methods like AS2, Van, rest etc ), what would be sold is the hosting, and transformation pieces, the being able to deploy a sftp server would be a feature, but someone still has to pay for the actual server, how does this work in the grand scheme of things.
