### ISSUE TITLE
md5sum / sha1sum leaks the real storage path

### ISSUE THREAD

**Issue by matrey** [drakkan/sftpgo#109]
I'm using the latest release 0.9.6
If you try to apply the `md5sum` or `sha1sum` command to a file that doesn't exist:
```
$ ssh test@my-sftpgo-host "md5sum does-not-exist"
md5sum: /does-not-exist open /sftpdata/test/subtest/does-not-exist: no such file or directory
```
It leaks the real storage path (`/sftpdata/test/subtest/` in my example above)
Not really a big issue, but not really desirable either.

**Comment by drakkan** [comment]
Thanks for reporting this issue, it affects SFTP too and it should be fixed now:

```
ssh -p 2022 nicola@127.0.0.1 md5sum a.txt
nicola@127.0.0.1's password: 
md5sum: /a.txt no such file or directory
```

```
scp -P 2022 -r nicola@127.0.0.1:/a /tmp/
nicola@127.0.0.1's password: 
no such file or directory
```
