### ISSUE TITLE
pre-upload action for s3 files show 0 byte filesize

### ISSUE THREAD

**Issue by tooptoop4** [drakkan/sftpgo#1092]
it always shows:
SFTPGO_ACTION_FILE_SIZE=0

other things like SFTPGO_ACTION_PATH are showing correctly

i tried with files of 1302 bytes or 19 bytes, via http or sftp cli. same issue

**Comment by tooptoop4** [comment]
https://github.com/drakkan/sftpgo/blob/v2.4.2/internal/sftpd/handler.go#L404 here I see 0 is passed

https://github.com/drakkan/sftpgo/blob/a7f9581d99b5c5fc64896ed0cc72301e8d84d469/internal/common/actions.go#L94

**Comment by drakkan** [comment]
SFTPGo only knows the size of the upload when the upload finishes, not before
