### ISSUE TITLE
Brother scanner supports only  ssh-rsa for SFTP

### ISSUE THREAD

**Issue by DocN0** [drakkan/sftpgo#1093]
It seems that my new Brother scanner only supports ssh-rsa, which is why I always get the following error in the log: 

`sender":"connection_failed","client_ip":"XXXXX","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"ssh: no common algorithm for host key; client offered: [ssh-rsa], server offered: [rsa-sha2-256 rsa-sha2-512 ecdsa-sha2-nistp256 ssh-ed25519]"}`

is there a way to enable ssh-rsa on the server side? I have unfortunately found nothing about this.
 
Thanks a lot!

**Comment by drakkan** [comment]
Hi, ssh-rsa is disabled by default because it is no longer considered secure but still supported. Customize [host_key_algorithms](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md) to enable it
