### ISSUE TITLE
创建用户时，没有自动创建home_dir

### ISSUE THREAD

**Issue by peng223** [drakkan/sftpgo#1098]
看接口文档：path to the user home directory. The user cannot upload or download files outside this directory. SFTPGo tries to automatically create this folder if missing. Must be an absolute path

但是创建用户时，并没有创建home_dir

**Comment by drakkan** [comment]
Please write in English, I used google translator to understand what you mean. The home dir is created when the user logins not when you create the account. Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by peng223** [comment]
ok,thank you
