### ISSUE TITLE
Automatic credentials for GCP buckets

### ISSUE THREAD

**Issue by ajaykumar-gbi** [drakkan/sftpgo#1099]
How does automatic credentials work. We are going to use SFTPgo for multiple users and its not possible to upload json key each time as we are going to automate it. 
Also, is GCP bucket uses federated authentication ? https://cloud.google.com/iam/docs/workload-identity-federation 
![image](https://user-images.githubusercontent.com/90805529/207599672-bd24b79d-ee0d-4052-bf3a-54788d390ea3.png)

**Comment by drakkan** [comment]
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
