### ISSUE TITLE
Add "excluded in quota limit"option

### ISSUE THREAD

**Issue by HiFiPhile** [drakkan/sftpgo#110]
Hi,

I've a simple idea to add an option to let some folders excluded in quota limit.

For example in our company we have public shared files and personal storage. Using SFTPGo  we can use home folder for personal storage and virtual folder for shared files, it would be good to exclude shared files from personal quota.

**Comment by drakkan** [comment]
Hi,

thanks for suggesting this feature. I think this make sense for virtual folders only (so folders outside the user home dir), we don't want exclude quota for folders inside the user home directory. Do you agree?

I think that automatically adding this option for overlapping mapped path will solve the issue pointed in #95 too.

I'm a bit busy in these days, I'll see if I can find some time this or the next weekend

**Comment by HiFiPhile** [comment]
> I think this make sense for virtual folders only
Yes I think it covers most of the user cases.

> I'm a bit busy in these days, I'll see if I can find some time this or the next weekend
Take your time 🙂

**Comment by drakkan** [comment]
I did minimal testing, please let me know if it works as expected, thanks!

**Comment by drakkan** [comment]
Hi, I refactored virtual folders. 

You can find update docs [here](https://github.com/drakkan/sftpgo/blob/master/docs/virtual-folders.md)

Testing is very appreciated, thanks!
