### ISSUE TITLE
how to set sftpgo configuration restrict login behavior ？

### ISSUE THREAD

**Issue by sxj1991** [drakkan/sftpgo#1100]
I look sftpgo configuration 'full-configuration' and want to find restricted user login behavior, but can‘t find similar information.
for example ：
     There is a user who has failed to log in multiple times. Forbid him to log in or not allowed to log in for a period of time.
If a relevant configuration please tell me, thanks!

**Comment by drakkan** [comment]
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
