### ISSUE TITLE
openapi generated python gets: Unexpected keyword argument ‘access_token’

### ISSUE THREAD

**Issue by JonBendtsen** [drakkan/sftpgo#1101]
openapi.yaml from SFTPGO 2.4.2

openapi-generator-cli with hash 1169ad9ea4e2 modified with added yapf3

build python

resulting file out/python/README.md 

trying to use example from line 148 to 193.

had to add line that imported APIKeyScope right after import of ApiResponse

(inconsistent API/Api usage?)

line 167 has access_token = ‘your_bearer_token’

but it fails with unexpected keyword argument ‘access_token’

access_token not defined as a :param in out/python/openapi_client/configuration.py

**Comment by JonBendtsen** [comment]
I edited out/python/openapi_client/configuration.py


```
--- original_configuration.py	2022-12-19 09:40:26.328683842 +0000
+++ configuration.py	2022-12-19 09:13:27.356712489 +0000
@@ -116,7 +116,7 @@
 
     _default = None
 
-    def __init__(self, host=None,
+    def __init__(self, host=None, access_token=None,
                  api_key=None, api_key_prefix=None,
                  username=None, password=None,
                  discard_unknown_keys=False,
@@ -151,6 +151,11 @@
             self.api_key_prefix = api_key_prefix
         """dict to store API prefix (e.g. Bearer)
         """
+        self.access_token = ""
+        if access_token:
+            self.access_token = access_token
+        """dict to store access_token (e.g. Bearer)
+        """
         self.refresh_api_key_hook = None
         """function hook to refresh API key if expired
         """
```

but that only gave a new error which I'll post in the next comment

**Comment by JonBendtsen** [comment]
After running python install I get

```
adm_jobe@jontest:~/new_podman_stuff/openapi/out$ python3 jon_proever.py 
/home/adm_jobe/.local/lib/python3.10/site-packages/urllib3-1.26.13-py3.10.egg/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jontest.dmi.dk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/home/adm_jobe/new_podman_stuff/openapi/out/jon_proever.py", line 45, in <module>
    api_response = api_instance.add_api_key(api_key)
  File "/home/adm_jobe/.local/lib/python3.10/site-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/paths/apikeys/post.py", line 443, in add_api_key
  File "/home/adm_jobe/.local/lib/python3.10/site-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/paths/apikeys/post.py", line 362, in _add_api_key_oapg
  File "/home/adm_jobe/.local/lib/python3.10/site-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/api_client.py", line 929, in deserialize
openapi_client.exceptions.ApiValueError: Invalid content_type returned. Content_type='application/json; charset=utf-8' was returned when only {'application/json'} are defined for status_code=201
```

So I edited the post.py file
```
--- out-v6.2.1/python/build/lib/openapi_client/paths/apikeys/post.py	2022-12-15 14:43:03.000000000 +0000
+++ out/python/openapi_client/paths/apikeys/post.py	2022-12-19 09:29:35.616695356 +0000
@@ -137,7 +137,7 @@
 _response_for_201 = api_client.OpenApiResponse(
     response_cls=ApiResponseFor201,
     content={
-        'application/json': api_client.MediaType(
+        'application/json; charset=utf-8': api_client.MediaType(
             schema=SchemaFor201ResponseBodyApplicationJson),
     },
     headers=[
@@ -160,7 +160,7 @@
 _response_for_400 = api_client.OpenApiResponse(
     response_cls=ApiResponseFor400,
     content={
-        'application/json': api_client.MediaType(
+        'application/json; charset=utf-8': api_client.MediaType(
             schema=SchemaFor400ResponseBodyApplicationJson),
     },
 )
@@ -179,7 +179,7 @@
 _response_for_401 = api_client.OpenApiResponse(
     response_cls=ApiResponseFor401,
     content={
-        'application/json': api_client.MediaType(
+        'application/json; charset=utf-8': api_client.MediaType(
             schema=SchemaFor401ResponseBodyApplicationJson),
     },
 )

```
python install again and now I finally got an API key.

Is this an issue in the openapi.yaml file I used? or is this an issue in the openapi-generator-cli docker image I use?

**Comment by drakkan** [comment]
Hello,

I have no time/motivation to test this myself sorry. Please report here if you find something wrong in the openapi definition.
The generated (java) code worked fine for another user, see #875, so try using the yaml from SFTPGo v2.3.x and see if you have the same issue, the login method is unchanged. Thanks

**Comment by JonBendtsen** [comment]
trying with [https://raw.githubusercontent.com/drakkan/sftpgo/2.3.x/openapi/openapi.yaml](https://raw.githubusercontent.com/drakkan/sftpgo/2.3.x/openapi/openapi.yaml)

Tried both with and without yapf3 in the python generator, and it did not make any difference in the generated python files.

after reinstalling 
`adm_jobe@jontest:~/new_podman_stuff/openapi/out_from_2.3.x_v6.2.1$ python3 setup.py install --user
`
I once again try to get an API key

```
adm_jobe@jontest:~/new_podman_stuff/openapi/out_from_2.3.x_v6.2.1$ python3 jon_proever.py 
Traceback (most recent call last):
  File "/home/adm_jobe/new_podman_stuff/openapi/out_from_2.3.x_v6.2.1/jon_proever.py", line 20, in <module>
    configuration = openapi_client.Configuration(
TypeError: Configuration.__init__() got an unexpected keyword argument 'access_token'

```

Editing python/openapi_client/configuration.py  to add the access_token definition from last time such that the only differences between 2.3x and 2.4.2 are:
```--- out_from_2.3.x_v6.2.1/python/openapi_client/configuration.py	2022-12-19 10:30:40.624630506 +0000
+++ out_from_openapi_2.4.2/python/openapi_client/configuration.py	2022-12-19 09:13:27.356712489 +0000
@@ -5,7 +5,7 @@
 
     SFTPGo allows you to securely share your files over SFTP and optionally over HTTP/S, FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per-user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, an S3 user that exposes a Google Cloud Storage bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo supports groups to simplify the administration of multiple accounts by letting you assign settings once to a group, instead of multiple times to each individual user. The SFTPGo WebClient allows end users to change their credentials, browse and manage their files in the browser and setup two-factor authentication which works with Authy, Google Authenticator and other compatible apps. From the WebClient each authorized user can also create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date.   # noqa: E501
 
-    The version of the OpenAPI document: 2.3.6
+    The version of the OpenAPI document: 2.4.2
     Generated by: https://openapi-generator.tech
 """
 
@@ -438,7 +438,7 @@
         return "Python SDK Debug Report:\n"\
                "OS: {env}\n"\
                "Python Version: {pyversion}\n"\
-               "Version of the API: 2.3.6\n"\
+               "Version of the API: 2.4.2\n"\
                "SDK Package Version: 1.0.0".\
                format(env=sys.platform, pyversion=sys.version)
 
 ```

Reinstalling with `python3 setup.py install --user`

I get the same kind of content_type error
```adm_jobe@jontest:~/new_podman_stuff/openapi/out_from_2.3.x_v6.2.1$ python3 jon_proever.py 
/home/adm_jobe/.local/lib/python3.10/site-packages/urllib3-1.26.13-py3.10.egg/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jontest.dmi.dk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/home/adm_jobe/new_podman_stuff/openapi/out_from_2.3.x_v6.2.1/jon_proever.py", line 45, in <module>
    api_response = api_instance.add_api_key(api_key)
  File "/home/adm_jobe/.local/lib/python3.10/site-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/paths/apikeys/post.py", line 443, in add_api_key
  File "/home/adm_jobe/.local/lib/python3.10/site-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/paths/apikeys/post.py", line 362, in _add_api_key_oapg
  File "/home/adm_jobe/.local/lib/python3.10/site-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/api_client.py", line 929, in deserialize
openapi_client.exceptions.ApiValueError: Invalid content_type returned. Content_type='application/json; charset=utf-8' was returned when only {'application/json'} are defined for status_code=401
```

so I diff my post.py and end up just copying the one I made from 2.4.2
```--- out_from_2.3.x_v6.2.1/python/openapi_client/paths/apikeys/post.py	2022-12-19 10:15:29.996646619 +0000
+++ out_from_openapi_2.4.2/python/openapi_client/paths/apikeys/post.py	2022-12-19 09:29:35.616695356 +0000
@@ -137,7 +137,7 @@
 _response_for_201 = api_client.OpenApiResponse(
     response_cls=ApiResponseFor201,
     content={
-        'application/json': api_client.MediaType(
+        'application/json; charset=utf-8': api_client.MediaType(
             schema=SchemaFor201ResponseBodyApplicationJson),
     },
     headers=[
@@ -160,7 +160,7 @@
 _response_for_400 = api_client.OpenApiResponse(
     response_cls=ApiResponseFor400,
     content={
-        'application/json': api_client.MediaType(
+        'application/json; charset=utf-8': api_client.MediaType(
             schema=SchemaFor400ResponseBodyApplicationJson),
     },
 )
@@ -179,7 +179,7 @@
 _response_for_401 = api_client.OpenApiResponse(
     response_cls=ApiResponseFor401,
     content={
-        'application/json': api_client.MediaType(
+        'application/json; charset=utf-8': api_client.MediaType(
             schema=SchemaFor401ResponseBodyApplicationJson),
     },
 )
```

Reinstalling with `python3 setup.py install --user` in the 2.3.x directory

Running 2.3.x again with all my necessary changes to configuration.py and post.py I once again get an API key.

@drakkan I am inclined to conclude that openapi-generator-cli v6.2.1 from Docker hub and either of openapi.yaml from 2.4.2 and 2.3.x generates the same "broken" Python code.

**Comment by drakkan** [comment]
according to your test, it seems an openapi-generator-cli issue. The v2.3.x specs were confirmed to generate correct (java) code for at least another user (using a different generator)

**Comment by JonBendtsen** [comment]
@drakkan  maybe. I made this change to openapi.yaml and it no longer complains about the charset, meaning I do not have to make changes to post.py
```--- 2.4.2_openapi.yaml  2022-12-19 09:08:22.580717882 +0000
+++ jons_2.4.2_openapi.yaml     2022-12-19 11:26:12.760571545 +0000
@@ -125,7 +125,7 @@
         '201':
           description: successful operation
           content:
-            application/json:
+            application/json; charset=utf-8:
               schema:
                 type: array
                 items:
```
... many more lines like that, see the attached diff.

[jons_2.4.2_openapi_yaml_diff.txt](https://github.com/drakkan/sftpgo/files/10258926/jons_2.4.2_openapi_yaml_diff.txt)

I've also re-generated the bash client using openapi-generator-cli v6.2.1 and my version of openapi.yaml with contains the charset=utf-8 in the application/json and openapi-generator-cli seems to only make changes on lines with the application/json text. I can also still use the bash version to get a new access token.

Therefore I would like to make a Pull Request with the charset=utf-8 change.

Which other generator did that other user use?

**Comment by drakkan** [comment]
> @drakkan maybe. I made this change to openapi.yaml and it no longer complains about the charset, meaning I do not have to make changes to post.py
> 
> ```
> +++ jons_2.4.2_openapi.yaml     2022-12-19 11:26:12.760571545 +0000
> @@ -125,7 +125,7 @@
>          '201':
>            description: successful operation
>            content:
> -            application/json:
> +            application/json; charset=utf-8:
>                schema:
>                  type: array
>                  items:
> ```
> 
> ... many more lines like that, see the attached diff.
> 
> [jons_2.4.2_openapi_yaml_diff.txt](https://github.com/drakkan/sftpgo/files/10258926/jons_2.4.2_openapi_yaml_diff.txt)
> 
> I've also re-generated the bash client using openapi-generator-cli v6.2.1 and my version of openapi.yaml with contains the charset=utf-8 in the application/json and openapi-generator-cli seems to only make changes on lines with the application/json text. I can also still use the bash version to get a new access token.
> 
> Therefore I would like to make a Pull Request with the charset=utf-8 change.
> 

I am not against such a change, please prepare a PR against the main branch

> Which other generator did that other user use?

He used openapi-generator like you, in my testing for that problem I used swagger-codegen

**Comment by JonBendtsen** [comment]
FYI: I am talking with openapi about this and even tried their new python-nextgen, but it kind of has the same issue.

**Comment by drakkan** [comment]
does this [python client](https://github.com/ramnes/sftpgo-client) have the same issue? I think it uses [this library](https://github.com/openapi-generators/openapi-python-client) under the hood.

If you find something to change in the SFTPGo OpenAPI definition I'm glad to merge the PR

**Comment by JonBendtsen** [comment]
I did pip install sftpgo-client and then it does seem to work. I have not tried using the library you also link to. Looking at that library seems like it needs a openapi.json file and not an openapi.yaml file so I won't be pursuing using that library.

Thanks, if I find something to change in the openapi.yaml I'll send a PR.

I have thought about sending some python based API use case examples, but that won't be until I've developed them.

**Comment by drakkan** [comment]
As for the access token, I suggest opening an upstream issue if you're sure you're using the generated python code correctly.

If you plan to submit python based API examples please use the main branch. I just pushed a backard incompatible change for [REST API](https://github.com/drakkan/sftpgo/commit/0841c7d7bd692a9af9cad307d02c1313647ffe1e)

**Comment by JonBendtsen** [comment]
@drakkan FYI: I do not expect a any need to change SFTPGO/openapi.yaml when it comes to access_token because it seems like it was indeed an upstream issue that'll probably eventually get fixed.

[https://github.com/OpenAPITools/openapi-generator/pull/14308](https://github.com/OpenAPITools/openapi-generator/pull/14308)

**Comment by drakkan** [comment]
> @drakkan FYI: I do not expect a any need to change SFTPGO/openapi.yaml when it comes to access_token because it seems like it was indeed an upstream issue that'll probably eventually get fixed.
> 
> [OpenAPITools/openapi-generator#14308](https://github.com/OpenAPITools/openapi-generator/pull/14308)

Thanks
