### ISSUE TITLE
new feature: custom action for pre-mkdir that can prevent the folders being created

### ISSUE THREAD

**Issue by tooptoop4** [drakkan/sftpgo#1102]
currently the custom action 'mkdir' can't block the directory from being created

**Comment by drakkan** [comment]
Hello, this can be done but I'm accepting feature requests from bronze or higher sponsors. Thank you

**Comment by drakkan** [comment]
Improved in the new UI

**Comment by drakkan** [comment]
Cloud storage providers don't have real folders, they have a flat structure and folders are just part of the object name so it is hard to make this work in every case, sorry
