### ISSUE TITLE
Placeholder for Virtual Folders

### ISSUE THREAD

**Issue by patrickap** [drakkan/sftpgo#1105]
First of all: SFTPGo is great!

I have a requirement to map external user data `/data/<username>/...` from another application to each individual SFTPGo user. The documentation mentions that there are virtual folders for this purpose but I did not found anything generic. What do you think about the possibility to define placeholders like `%username%` in the path for virtual folders? In my case, this would make it possible to automatically map the right content to the right user. Provided that the usernames match.

**Comment by drakkan** [comment]
Hi,

this should already work. Please make sure to read the (entire) docs or consider sponsoring the project if you want SFTPGo to stay alive and to get answers to questions like this. Thank you.

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
