### ISSUE TITLE
Is SCP possible?

### ISSUE THREAD

**Issue by lonnietc** [drakkan/sftpgo#1116]
Hello,

I am researching SSH on Windows and have read that SCP is significantly faster than SFTP for file transfers, but that SCP does not actually provide all of the file management functionality.

Being a bit confused on how to go about this, I have been in search of an SCP server that would allow multiple connections and serve a directory to those users.

I came across sftpgo and wanted to get some input on this question as well as to ask if it is possible to have an SCP module for this sever to reduce latency in transferring files to/from the server?

Any help would be greatly appreciated.
Thanks

**Comment by drakkan** [comment]
Hello,

SCP is supported. Take a look at the [docs here](https://github.com/drakkan/sftpgo/blob/main/docs/ssh-commands.md)
