### ISSUE TITLE
Disallow usernames with trailing and/or leading space-like chars

### ISSUE THREAD

**Issue by zlodes** [drakkan/sftpgo#1119]
Hi!

I just created a user using username copied from Slack. 
Then I couldn't edit/delete this user from SFTPGo admin panel — had 404. 

I think it would be better to trim string by RegEx `\s`.

**Comment by drakkan** [comment]
Hello,

this is already supported but not enabled by default. I'll consider changing the default in the v2.5.
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
