### ISSUE TITLE
Seems to be no way to get windows network shares working

### ISSUE THREAD

**Issue by jenny787** [drakkan/sftpgo#1123]
I installed sftpgo using the instructions, and using the windows binary in the releases.
I created a user, with a home directory on the local drive.  Everything works fine on this folder.
I also added virtual folders, which are network drives with default * permissions.
The virtual folders show up in the root as expected.
But no files can be uploaded or modified.  It's almost read only, and one folder won't even show contents, it just hangs trying to open.
This is likely a windows problem, but I see no way to modify this on sftpgo's end.  I also did not find any documentation of anyone who got network windows shares working.

**Comment by jenny787** [comment]
I am going to close this.  The solution was to give the sftpgo service in windows a logon with a domain user that has network access.

**Comment by drakkan** [comment]
Hello, this is a way, also take a look [here](https://github.com/drakkan/sftpgo/issues/1062)
