### ISSUE TITLE
only use xftp connect ftp passive can not list file

### ISSUE THREAD

**Issue by shuinoo** [drakkan/sftpgo#1134]
I use xftp connect to ftp passive can not list file,
![image](https://user-images.githubusercontent.com/38451598/211019997-7c85f638-1b1a-4a54-b699-aae47accf1e4.png)
log:
{"level":"debug","time":"2023-01-06T21:08:10.234","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","clientIp":"163.125.196.0:33639","message":"Client connected"}
{"level":"debug","time":"2023-01-06T21:08:10.234","sender":"FTP","connection_id":"FTP_0_2143","message":"connection added, local address \"192.168.99.103:21\", remote address \"163.125.196.0:33639\", num open connections: 2"}
{"level":"debug","time":"2023-01-06T21:08:10.235","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"220 ftp is ready","message":"Sendinganswer"}
{"level":"debug","time":"2023-01-06T21:08:10.256","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"USER yict","message":"Received line"}
{"level":"debug","time":"2023-01-06T21:08:10.256","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"331 OK","message":"Sending answer"}
{"level":"debug","time":"2023-01-06T21:08:10.276","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"PASS yict@2016!","message":"Receivedline"}
{"level":"debug","time":"2023-01-06T21:08:10.276","sender":"common","connection_id":"FTP_0_2143","message":"connection swapped, close fs error: <nil>"}
{"level":"info","time":"2023-01-06T21:08:10.276","sender":"FTP","connection_id":"FTP_0_2143","message":"User \"yict\" logged in with \"password\" from ip \"163.125.196.0\""}
{"level":"debug","time":"2023-01-06T21:08:10.276","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"230 Password ok, continue","message":"Sending answer"}
{"level":"debug","time":"2023-01-06T21:08:10.301","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"PWD","message":"Received line"}
{"level":"debug","time":"2023-01-06T21:08:10.301","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"257 \"/\" is the current directory","message":"Sending answer"}
{"level":"debug","time":"2023-01-06T21:08:10.323","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"CWD /","message":"Received line"}
{"level":"debug","time":"2023-01-06T21:08:10.323","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"250 CD worked on /","message":"Sending answer"}
{"level":"debug","time":"2023-01-06T21:08:10.340","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"PWD","message":"Received line"}
{"level":"debug","time":"2023-01-06T21:08:10.340","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"257 \"/\" is the current directory","message":"Sending answer"}
{"level":"debug","time":"2023-01-06T21:08:10.356","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"TYPE A","message":"Received line"}
{"level":"debug","time":"2023-01-06T21:08:10.356","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"200 Type set to ASCII","message":"Sending answer"}
{"level":"debug","time":"2023-01-06T21:08:10.373","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"PASV","message":"Received line"}
{"level":"debug","time":"2023-01-06T21:08:10.373","sender":"ftpserverlib","server_id":"FTP_0","clientId":"2143","line":"227 Entering Passive Mode (192,168,99,103,236,38)","message":"Sending answer"}
log only to passive, can not continue

**Comment by drakkan** [comment]
Try setting the proper passive IP. Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
