### ISSUE TITLE
Disconnect old connections after changing the password

### ISSUE THREAD

**Issue by peng223** [drakkan/sftpgo#1137]
I logged into the sftp service, and I stayed connected
Then I changed the password
At this time, I hope that the previous login will be automatically disconnected
Waht can i do.thank you

**Comment by JonBendtsen** [comment]
how did you change the password?

At the bottom of the GUI you can select 
```
[ ] Disconnect the user after the update
This way you force the user to login again, if connected, and so to use the new configuration
```
If you use SFTP, then have in mind that the user might use a key to login in with.

**Comment by peng223** [comment]
ok,thanks
