### ISSUE TITLE
sftpgo.service failed

### ISSUE THREAD

**Issue by levilhorrb** [drakkan/sftpgo#1144]
![image](https://user-images.githubusercontent.com/119741219/211957999-6f2e84f1-7b1f-42e9-a635-f55f3207d5a2.png)

如果你和我遇到同样得问题，可以试试

sed -i '/Capabili/d' /lib/systemd/system/sftpgo.service
systemctl daemon-reload
systemctl restart sftpgo

**Comment by drakkan** [comment]
Hello,

can you share the kernel version/Linux distro you are using? I suppose you are on very old version. Having `CAP_NET_BIND_SERVICE` is important to many users and is unlikely to be removed by default. Uses affected by this can override the systemd unit
