### ISSUE TITLE
pre_login_hook not being called

### ISSUE THREAD

**Issue by alivesay** [drakkan/sftpgo#115]
Hi,

I have `pre_login_hook` set to a url, and `external_auth_scope` is 0, yet sftpgo never sends a request.

From the logs, I'm guessing this is because it tries to first find a user in the data provider.  I'm confused if this is the case... isn't the point of the pre_login_hook to be able to dynamically create users as they log in?

Ideally I'd like to keep all user data and authentication external via web hooks.

Thanks.

**Comment by drakkan** [comment]
Hi, 

are you using 0.9.6? Pre-login hook can create new users since [this](https://github.com/drakkan/sftpgo/commit/0a9c4914aa7f4b534003db789b56b622b62f0dc6) commit.

If you are using 0.9.6 pre-login hook can only modify existing users. 
If you are using current git please paste the relevant logs, 
thanks.

**Comment by alivesay** [comment]
I've tried both the 0.9.6 release and latest git.

````
{"level":"warn","time":"2020-05-01T16:25:23.911","sender":"sqlite","connection_id":"","message":"error authenticating user: test00, error: Not found: sql: no rows in result set"}
{"level":"debug","time":"2020-05-01T16:25:23.911","sender":"connection_failed","client_ip":"x.x.x.x","username":"test00","login_type":"publickey","error":"Not found: sql: no rows in result set"}
{"level":"warn","time":"2020-05-01T16:25:25.654","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: [ssh: no auth passed yet, Authentication error: could not validate public key credentials: Not found: sql: no rows in result set]"}
```

```

**Comment by alivesay** [comment]
"external_auth_hook": "http://localhost:1337/sftpgo/auth",
    "pre_login_hook": "http://127.0.0.1:1337/sftpgo/prelogin"

**Comment by drakkan** [comment]
> I've tried both the 0.9.6 release and latest git.
> 
> ```
> {"level":"warn","time":"2020-05-01T16:25:23.911","sender":"sqlite","connection_id":"","message":"error authenticating user: test00, error: Not found: sql: no rows in result set"}
> {"level":"debug","time":"2020-05-01T16:25:23.911","sender":"connection_failed","client_ip":"x.x.x.x","username":"test00","login_type":"publickey","error":"Not found: sql: no rows in result set"}
> {"level":"warn","time":"2020-05-01T16:25:25.654","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: [ssh: no auth passed yet, Authentication error: could not validate public key credentials: Not found: sql: no rows in result set]"}
> ```
> 

please post some more logs to help me to understand what is happening

> ```
>     "external_auth_hook": "http://localhost:1337/sftpgo/auth",
>     "pre_login_hook": "http://127.0.0.1:1337/sftpgo/prelogin"
> ```
> ```

external auth and pre login hook cannot be used together. If you define both of them external auth should be called, anyway if you post some more logs I can better understand the issue, thanks

**Comment by alivesay** [comment]
I think these are max verbosity logs (`sftpgo serve -v`):

```
{"level":"info","time":"2020-05-01T21:39:40.146","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.6-4fe51f7-dirty-2020-05-01T16:19:56Z, config dir: ., config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false"}
{"level":"debug","time":"2020-05-01T21:39:40.147","sender":"config","connection_id":"","message":"config file used: '\"/opt/sftpgo/sftpgo.json\"', config loaded: {SFTPD:{Banner:SFTPGo_0.9.6 BindPort:2564 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0117 UploadMode:0 Actions:{ExecuteOn:[upload] Command: HTTPNotificationURL:http://localhost:1337/sftpgo/upload} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile:./banner.txt SetstatMode:1 EnabledSSHCommands:[md5sum sha1sum cd pwd] KeyboardInteractiveProgram: ProxyProtocol:0 ProxyAllowed:[]} ProviderConf:{Driver:memory Name: Host: Port:5432 Username: Password:[redacted] SSLMode:0 ConnectionString: UsersTable:users ManageUsers:0 TrackQuota:0 PoolSize:0 UsersBaseDir:/srv/sftpgohome Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} ExternalAuthProgram: ExternalAuthScope:0 CredentialsPath:credentials PreLoginProgram:} HTTPDConfig:{BindPort:8080 BindAddress:127.0.0.1 TemplatesPath:templates StaticFilesPath:static BackupsPath:backups AuthUserFile: CertificateFile: CertificateKeyFile:}}"}
{"level":"debug","time":"2020-05-01T21:39:40.147","sender":"dataProvider","connection_id":"","message":"no users configuration file defined"}
{"level":"debug","time":"2020-05-01T21:39:40.147","sender":"service","connection_id":"","message":"initializing SFTP server with config {Banner:SFTPGo_0.9.6 BindPort:2564 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0117 UploadMode:0 Actions:{ExecuteOn:[upload] Command: HTTPNotificationURL:http://localhost:1337/sftpgo/upload} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile:./banner.txt SetstatMode:1 EnabledSSHCommands:[md5sum sha1sum cd pwd] KeyboardInteractiveProgram: ProxyProtocol:0 ProxyAllowed:[]}"}
{"level":"debug","time":"2020-05-01T21:39:40.147","sender":"utils","connection_id":"","message":"set umask to 0117 (79)"}
{"level":"info","time":"2020-05-01T21:39:40.147","sender":"sftpd","connection_id":"","message":"Loading private key: id_rsa"}
{"level":"info","time":"2020-05-01T21:39:40.148","sender":"sftpd","connection_id":"","message":"Loading private key: id_ecdsa"}
{"level":"debug","time":"2020-05-01T21:39:40.148","sender":"httpd","connection_id":"","message":"initializing HTTP server with config {BindPort:8080 BindAddress:127.0.0.1 TemplatesPath:templates StaticFilesPath:static BackupsPath:backups AuthUserFile: CertificateFile: CertificateKeyFile:}"}
{"level":"info","time":"2020-05-01T21:39:40.159","sender":"sftpd","connection_id":"","message":"server listener registered address: [::]:2564"}
{"level":"warn","time":"2020-05-01T21:40:40.805","sender":"dataProvider","connection_id":"","message":"error authenticating user: pps00, error: Not found: username pps00 does not exist"}
{"level":"debug","time":"2020-05-01T21:40:40.805","sender":"connection_failed","client_ip":"X.X.X.X","username":"pps00","login_type":"publickey","error":"Not found: username pps00 does not exist"}
{"level":"warn","time":"2020-05-01T21:40:42.075","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: [ssh: no auth passed yet, Authentication error: could not validate public key credentials: Not found: username pps00 does not exist]"}
```

```
{
  "sftpd": {
    "bind_port": 2564,
    "bind_address": "",
    "idle_timeout": 15,
    "max_auth_tries": 0,
    "umask": "0117",
    "banner": "",
    "upload_mode": 0,
    "actions": {
      "execute_on": ["upload"],
      "command": "",
      "http_notification_url": "http://localhost:1337/sftpgo/upload"
    },
    "keys": [],
    "enable_scp": false,
    "kex_algorithms": [],
    "ciphers": [],
    "macs": [],
    "login_banner_file": "./banner.txt",
    "setstat_mode": 1,
    "enabled_ssh_commands": [
      "md5sum",
      "sha1sum",
      "cd",
      "pwd"
    ],
    "keyboard_interactive_auth_program": "",
    "proxy_protocol": 0,
    "proxy_allowed": []
  },
  "data_provider": {
    "driver": "memory",
    "name": "",
    "manage_users": 0,
    "track_quota": 0,
    "pool_size": 0,
    "actions": {
      "execute_on": [],
      "command": "",
      "http_notification_url": ""
    },
    "external_auth_scope": 0,
    "users_base_dir": "/srv/sftpgohome",
    "external_auth_hook": "http://localhost:1337/sftpgo/auth"
  },
  "httpd": {
    "bind_port": 8080,
    "bind_address": "127.0.0.1",
    "templates_path": "templates",
    "static_files_path": "static",
    "backups_path": "backups",
    "auth_user_file": "",
    "certificate_file": "",
    "certificate_key_file": ""
  }
```

The purpose of `manage_users` isn't clear to me, but changing that setting has no effect either way.

It's also not clear to me if I should use external_auth_hook or pre_login_hook when I want to externalize all user authentication.  Does the use of either of these approaches remove the need to store local sftpgo user accounts in the data provider?

Ideally I guess I'd like:

1. User connects with SFTP client to sftpgo
2. sftpgo calls webhook to authenticate user
3. user is now logged into sftp in their specific "home" directory
4. user uploads file
5. webhook is called for upload action

Thanks.

**Comment by drakkan** [comment]
> I think these are max verbosity logs (`sftpgo serve -v`):
> 
> ```
> {"level":"info","time":"2020-05-01T21:39:40.146","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.6-4fe51f7-dirty-2020-05-01T16:19:56Z, config dir: ., config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false"}

version `0.9.6-4fe51f7-dirty-2020-05-01T16:19:56Z` means that you are using 0.9.6 version with some uncommitted changes (maybe the configuration file)

> {"level":"debug","time":"2020-05-01T21:39:40.147","sender":"config","connection_id":"","message":"config file used: '\"/opt/sftpgo/sftpgo.json\"', config loaded: {SFTPD:{Banner:SFTPGo_0.9.6 BindPort:2564 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0117 UploadMode:0 Actions:{ExecuteOn:[upload] Command: HTTPNotificationURL:http://localhost:1337/sftpgo/upload} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile:./banner.txt SetstatMode:1 EnabledSSHCommands:[md5sum sha1sum cd pwd] KeyboardInteractiveProgram: ProxyProtocol:0 ProxyAllowed:[]} ProviderConf:{Driver:memory Name: Host: Port:5432 Username: Password:[redacted] SSLMode:0 ConnectionString: UsersTable:users ManageUsers:0 TrackQuota:0 PoolSize:0 UsersBaseDir:/srv/sftpgohome Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} ExternalAuthProgram: ExternalAuthScope:0 CredentialsPath:credentials PreLoginProgram:} HTTPDConfig:{BindPort:8080 BindAddress:127.0.0.1 TemplatesPath:templates StaticFilesPath:static BackupsPath:backups AuthUserFile: CertificateFile: CertificateKeyFile:}}"}

as you can see here both `ExternalAuthProgram` and `PreLoginProgram` are not defined, see below to understand the reason

> {"level":"debug","time":"2020-05-01T21:39:40.147","sender":"dataProvider","connection_id":"","message":"no users configuration file defined"}
> {"level":"debug","time":"2020-05-01T21:39:40.147","sender":"service","connection_id":"","message":"initializing SFTP server with config {Banner:SFTPGo_0.9.6 BindPort:2564 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0117 UploadMode:0 Actions:{ExecuteOn:[upload] Command: HTTPNotificationURL:http://localhost:1337/sftpgo/upload} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile:./banner.txt SetstatMode:1 EnabledSSHCommands:[md5sum sha1sum cd pwd] KeyboardInteractiveProgram: ProxyProtocol:0 ProxyAllowed:[]}"}
> {"level":"debug","time":"2020-05-01T21:39:40.147","sender":"utils","connection_id":"","message":"set umask to 0117 (79)"}
> {"level":"info","time":"2020-05-01T21:39:40.147","sender":"sftpd","connection_id":"","message":"Loading private key: id_rsa"}
> {"level":"info","time":"2020-05-01T21:39:40.148","sender":"sftpd","connection_id":"","message":"Loading private key: id_ecdsa"}
> {"level":"debug","time":"2020-05-01T21:39:40.148","sender":"httpd","connection_id":"","message":"initializing HTTP server with config {BindPort:8080 BindAddress:127.0.0.1 TemplatesPath:templates StaticFilesPath:static BackupsPath:backups AuthUserFile: CertificateFile: CertificateKeyFile:}"}
> {"level":"info","time":"2020-05-01T21:39:40.159","sender":"sftpd","connection_id":"","message":"server listener registered address: [::]:2564"}
> {"level":"warn","time":"2020-05-01T21:40:40.805","sender":"dataProvider","connection_id":"","message":"error authenticating user: pps00, error: Not found: username pps00 does not exist"}
> {"level":"debug","time":"2020-05-01T21:40:40.805","sender":"connection_failed","client_ip":"X.X.X.X","username":"pps00","login_type":"publickey","error":"Not found: username pps00 does not exist"}
> {"level":"warn","time":"2020-05-01T21:40:42.075","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: [ssh: no auth passed yet, Authentication error: could not validate public key credentials: Not found: username pps00 does not exist]"}
> ```
> 
> ```
> {
>   "sftpd": {
>     "bind_port": 2564,
>     "bind_address": "",
>     "idle_timeout": 15,
>     "max_auth_tries": 0,
>     "umask": "0117",
>     "banner": "",
>     "upload_mode": 0,
>     "actions": {
>       "execute_on": ["upload"],
>       "command": "",
>       "http_notification_url": "http://localhost:1337/sftpgo/upload"
>     },
>     "keys": [],
>     "enable_scp": false,
>     "kex_algorithms": [],
>     "ciphers": [],
>     "macs": [],
>     "login_banner_file": "./banner.txt",
>     "setstat_mode": 1,
>     "enabled_ssh_commands": [
>       "md5sum",
>       "sha1sum",
>       "cd",
>       "pwd"
>     ],
>     "keyboard_interactive_auth_program": "",
>     "proxy_protocol": 0,
>     "proxy_allowed": []
>   },
>   "data_provider": {
>     "driver": "memory",
>     "name": "",
>     "manage_users": 0,
>     "track_quota": 0,
>     "pool_size": 0,
>     "actions": {
>       "execute_on": [],
>       "command": "",
>       "http_notification_url": ""
>     },
>     "external_auth_scope": 0,
>     "users_base_dir": "/srv/sftpgohome",
>     "external_auth_hook": "http://localhost:1337/sftpgo/auth"

`external_auth_hook` was not present in 0.9.6. In 0.9.6 you can only call an external auth program and not an http hook. You need to build the current master to use an HTTP hook, so please really update to the current master to be able to use an http hook.

If you want to use 0.9.6 please refer to the matching documentation:

https://github.com/drakkan/sftpgo/blob/0.9.6/docs/external-auth.md

>   },
>   "httpd": {
>     "bind_port": 8080,
>     "bind_address": "127.0.0.1",
>     "templates_path": "templates",
>     "static_files_path": "static",
>     "backups_path": "backups",
>     "auth_user_file": "",
>     "certificate_file": "",
>     "certificate_key_file": ""
>   }
> ```
> 
> The purpose of `manage_users` isn't clear to me, but changing that setting has no effect either way.
> 
> It's also not clear to me if I should use external_auth_hook or pre_login_hook when I want to externalize all user authentication. Does the use of either of these approaches remove the need to store local sftpgo user accounts in the data provider?

please read the doc here to understand the difference:

https://github.com/drakkan/sftpgo/blob/master/docs/dynamic-user-mod.md

> 
> Ideally I guess I'd like:
> 
> 1. User connects with SFTP client to sftpgo
> 2. sftpgo calls webhook to authenticate user
> 3. user is now logged into sftp in their specific "home" directory
> 4. user uploads file
> 5. webhook is called for upload action
> 
> Thanks.

**Comment by drakkan** [comment]
Please reopen providing more info if you still have issues, thanks
