### ISSUE TITLE
database schema version 15 is too old, please see the upgrading docs

### ISSUE THREAD

**Issue by errogaht** [drakkan/sftpgo#1155]
Hi. We are using your app it is great and it is deployed to kubernetes.
It is too hard to upgrade schema that way. k8s deployment auto restarts container and i have no way to run initprovider.
do i need to install sftpgo locally and set remote db, open remote db ports to internet just to run initprovider? it is too complicated.
Please provide web ui to run any requiremens actions if no automatic migration can be done(like it done in TeamCity, web ui show maintenance and enter token generated in container, you enters it and UI said bla bla bla press the button). the only way i see to downgrade sftpgo and use old version forever.

**Comment by errogaht** [comment]
`sftpgo initprovider` returns Unable to initialize/update the data provider: database schema version 15 is too old, please see the upgrading docs. please provide docs how to upgrade DB schema

**Comment by drakkan** [comment]
It is documented and please stop complaining, you are not helping the project in any way

**Comment by alanmiller** [comment]
Hmmm, I too am facing this issue but like @errogaht **I can't find any documentation in the repo regarding how to upgrade.**

I have tried upgrading from subsequent major releases (v2.2.x to v2.3.x) but when doing so (2.2.3 to 2.3.x) I get error:

`2024-10-02T14:15:48.040 INF updating database version: 15 -> 19
panic: page 6 already freed

goroutine 1 [running]:
go.etcd.io/bbolt.(*freelist).free(0xc000303500, 0xe065, 0x7fa7ecee0000)
	go.etcd.io/bbolt@v1.3.6/freelist.go:175 +0x2c8` 

I too appreciate your contribution an like using your app but you're not helping your cause either by telling you users  by saying "it's documented, stop complaining".  

A simple link to the mentioned documentation would suffice and help everybody.
