### ISSUE TITLE
sftpgo fail2ban in global loadbalancer/clusters

### ISSUE THREAD

**Issue by archer29m** [drakkan/sftpgo#116]
Hello,

I was wondering if anyone knows how to config sftpgo fail2ban for a global load balancer/cluster? e.g., GCP global LB doesn't transfer IPs for non-HTTP requests (e.g., SFTP). So how can one see the actual source IPs in LB?

Thanks,
Arash

**Comment by drakkan** [comment]
Hi,

SFTPGo supports proxy protocol, please take a look at the documentation [here](https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md). GCP seems to support proxy protocol [v1](https://cloud.google.com/load-balancing/docs/tcp/setting-up-tcp#proxy-protocol), so please configure appropriately both GCP and SFTPGo, please let me know if it works as expected, thanks!

**Comment by drakkan** [comment]
Hi,

proxy protocol is the standard way to load balance the SFTP/SCP service without losing the information about the client's address. Please reopen if you have configuration issues and/or other suggestions, thanks!
