### ISSUE TITLE
Web Client: Password protected share without username

### ISSUE THREAD

**Issue by martin31821** [drakkan/sftpgo#1166]
Hi :wave: 

First of all, thanks for this awesome project. I'm using it to securely share files with external people, usually password protected.
I would love to be able to create a password protected share where the person shared with can download it with *only* entering the password and not the username. 

Is that an option you consider adding? If so, maybe I'd even try to implement and create a PR for it.

**Comment by drakkan** [comment]
Hi,

from a technical point of view this is probably a 1 line change, but please share more about the rationale and point out the docs of similar software that work this way. Thanks

**Comment by martin31821** [comment]
Hi,

my usecase is that I want to send a link and a password to someone else to allow them to access the file.
Currently, the UI doesn't say anything about requiring a username when setting up a password protected share, which then confuses the users when they're getting prompted for username & password.

Another software that does password-only would be owncloud/nextcloud (doc link: https://docs.nextcloud.com/server/stable/user_manual/en/files/sharing.html#public-link-shares).  There I can set a password for a shared file/folder and then the user is redirected to a nice password prompt when they try to access the share.

**Comment by drakkan** [comment]
Ok, I'll evaluate this feature request before v2.5. Thanks

**Comment by Jasper-Ben** [comment]
Thanks for looking into this!
