### ISSUE TITLE
Where is web_root folder?

### ISSUE THREAD

**Issue by onanana** [drakkan/sftpgo#1168]
I wanna use my index.html file at the http root folder.
like this
http://mydomain.com/index.html

but idk where is the root folder.

Im using Windows 10.

plz answer me.

thx.

**Comment by drakkan** [comment]
Hello,

I'm not sure I understand your question, SFTPGo is not a web server like NGINX, Apache, Caddy. It is not meant for rendering HTML files/websites

**Comment by onanana** [comment]
ok i got it.

thx for your responding

thank you

sftp and webdav is working easily

i think sftpgo is very good program.

thank you.
