### ISSUE TITLE
[Feature Request] SSH certificate authentication

### ISSUE THREAD

**Issue by WhileLoop** [drakkan/sftpgo#117]
What would it take to make this server support SSH certificate authentication? Is it possible?

**Comment by drakkan** [comment]
Hi,

I'm not sure to understand your question. If you mean public key authentication it is supported since the first version. You can add one or more public keys to each users using the REST API and/or the built-in web interface.

**Comment by WhileLoop** [comment]
I mean the process described here https://engineering.fb.com/security/scalable-and-secure-access-with-ssh/ and here https://smallstep.com/blog/use-ssh-certificates/. 

Unless I am completely misunderstanding the flow, the SFTP server would need to reproduce the functionality of the `TrustedUserCAKeys` directive.

**Comment by drakkan** [comment]
OK, I understand now. This feature isn't currently supported. I'll try to understand if I can add support for it, thanks for your suggestion and explanation.

**Comment by WhileLoop** [comment]
This might be a good place to start looking https://github.com/golang/crypto/blob/master/ssh/certs_test.go

**Comment by drakkan** [comment]
> This might be a good place to start looking https://github.com/golang/crypto/blob/master/ssh/certs_test.go

Yes, thanks,  I think this can be done using `CertChecker`. It looks like I have something to do the next weekend :)

**Comment by drakkan** [comment]
Hi,

certificate auth should be supported now, please let me know if it works as expected.
Please report any problem here and/or open separate issues.

I didn't added support for revocation checking: this require a file with the revoked certificates and/or a database table, you can achive the same result removing a certificate for a given user using the REST API/CLI/Web UI.

Optionally if you want improve the docs adding a dedicated section with detailed steps to configure cert auth a pull request is really appreciated.

Thanks!

**Comment by jovandeginste** [comment]
The weekend hadn't started yet! I find this a very interesting feature (we use it in other scenarios), I will check it out!

**Comment by drakkan** [comment]
> The weekend hadn't started yet! I find this a very interesting feature (we use it in other scenarios), I will check it out!

Well this time was quite easy, no need to hack inside external libraries. Optionally I could fix crypto/ssh to avoid to validate [source-address critical option inside sftpgo](https://github.com/drakkan/sftpgo/blob/master/sftpd/server.go#L614)

If you/others have suggestions please open issues to let me know. I don't use SFTPGo in production. This is basically a hobby. I started this project to make an SFTP server with the same features as Pure-FTPd and to learn Go at the same time. I could have only one potential commercial customer in future, so currently I receive only community feedbacks, I don't have use cases myself. 

There are some features that I could implement but I don't think are essential, for example:

- host certificate authentication
- GSSAPI with mic authentication

I would like to hear of use cases about these features if you need them.

Regarding the state of the project I think we are very close to 1.0 milestone, there are some know minor issues that I'm monitoring for example [this one](https://github.com/drakkan/sftpgo/blob/master/vfs/s3fs.go#L239) and I would like to see my performance improvements merged in upstream pkg/sftp too, but we already use them in SFTPGo git master so this is not a blocking issue.

Regarding performance we could still improve uploads performance avoiding [this allocation](https://github.com/golang/crypto/blob/master/ssh/transport.go#L162) in crypto/ssh  but this isn't easy to fix and you need a very fast storage or a ramdisk to notice a small difference from OpenSSH, so I think this isn't a real issue too.
