### ISSUE TITLE
Web interface error messages quickly disappear

### ISSUE THREAD

**Issue by mombooks** [drakkan/sftpgo#1171]
We often upload very large files, over 1GB. When the upload via web interface is interrupted, the web interface keeps the progress wheel spinning for a minute or two and then displays an error message in red text which quickly disappears. The result is that users think the file has been fully uploaded, when in fact the file was only partially uploaded. This problem could be solved by an error message that doesn't disappear until the user acknowledges it.

We're using an FTP client in house which is always going to be a better idea than a WUI, but it would be great to have a reliable web upload for when files are requested from external users.

**Comment by drakkan** [comment]
Hello,

http uploads are limited to 1GB by default, you can change the limit in your configuration file or using env vars

https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L343

please check the docs [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md).

I'll consider changing how notifications work but the user should see that the uploaded file is not in the file list

**Comment by mombooks** [comment]
Yes I've changed the config, but the issue is uploads being interrupted for whatever reason and users not noticing - for instance we often work over VPN which can be a little unstable. 

The large uploaded files are .zip files, so for instance if someone is uploading a 1.5GB file and the upload is interrupted the file will show up in the upload list but only with a size of say 700MB or whatever it got to before the upload was interrupted.

**Comment by drakkan** [comment]
> Yes I've changed the config, but the issue is uploads being interrupted for whatever reason and users not noticing - for instance we often work over VPN which can be a little unstable.
> 
> The large uploaded files are .zip files, so for instance if someone is uploading a 1.5GB file and the upload is interrupted the file will show up in the file list but only with a size of say 700MB or whatever it got to before the upload was interrupted. Because they didn't notice they then shared the file to customers who complained that the .zip file wouldn't open.

OK, got it
