### ISSUE TITLE
use local users to auth

### ISSUE THREAD

**Issue by rogeriojlle** [drakkan/sftpgo#1172]
how to parameterize the program to use users from passwords of local users, in the case of Linux?

**Comment by drakkan** [comment]
you can import your local users (yescrypt passwords are not supported yet), write an authentication plugin/hook or use SFTPGo as OpenSSH subsystem (not recommended). Check the docs.

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
