### ISSUE TITLE
[OIDC] Create the user when it does not exist

### ISSUE THREAD

**Issue by matthieu-calasin** [drakkan/sftpgo#1179]
Hi,
I have an OIDC configuration which has been tested with these Identity Providers : 
- Keycloak
- Google Auth
- DEX

My requirement is to create an "admin" and authenticate him. WIth the default configuration, it doesn't work. So, i have created the following `pre_login_hook` who create the user when it doesn't exists : 
```bash
#!/bin/bash

username=$(echo $SFTPGO_LOGIND_USER | jq '.username')

if [[ "${SFTPGO_LOGIND_PROTOCOL}" == "OIDC" ]] ; then
  echo '{
      "status": 1,
      "username": '${username}',
      "password": "test",
      "permissions": {
          "/": [
              "*"
          ]
      }
  }'
fi
```
This `pre_login_hook` works only for creating a user, but not for an admin.

I tried to create a custom claim with the key `sftpgo_role` which has value `admin` and it doesn't work too.

I have the following configuration 
```json
"oidc": {
  "client_id": "sftpgo",
  "client_secret": "<the client_secret>",
  "config_url": "<config_url>",
  "redirect_base_url": "<root url of SFTPGo>",
  "scopes": [
    "openid",
    "profile",
    "email"
  ],
  "username_field": "email",
  "role_field": "sftpgo_role",
  "implicit_roles": false,
  "custom_fields": [],
  "insecure_skip_signature_check": false,
  "debug": true
}
```
I have tried without the custom claim and with `"implicit_roles": true,` and it doesn't work too.
It works when i create the user with the same email fetched from OIDC.
The log : 
```json
{"level":"debug","time":"2023-02-06T09:22:25.245","sender":"httpd","message":"unable to get the sftpgo user associated with oidc token: not found: sql: no rows in result set"}
```
The problem seems to come from the fact that to create an "admin" with the OIDC protocol, if the user does not exist in SFTPGo, it will not be created.

STPGo version : `2.4.2`

Do you think the issue can be fixed ?
Thanks in advice.
Best regards

**Comment by drakkan** [comment]
Pre-login hook only works for users, not admins. You have to pre-create your admins.
Supporting pre-login hook/external auth also for admins is a discrete amount of work.
I no longer provide free support or implement features like these for free, sorry.

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
