### ISSUE TITLE
Upload unlimited files simultaneously (You can upload a maximum of 30 files)

### ISSUE THREAD

**Issue by ajaykumar-gbi** [drakkan/sftpgo#1182]
I was testing some concurrent uploads on SFTPGO. I tried to upload 1000+ files simultaneously to mimic the customer issues recently increasing sftp server usage and saw the sftpgo instance does not let me upload more than 30 files at a time. I am using "Google Cloud Storage" as backend storage.

**Comment by drakkan** [comment]
Check the logs, there is no such limitation, some project sponsors use SFTPGo this way without issues.

I no longer provide step-by-step support, sorry

**Comment by ajaykumar-gbi** [comment]
Thanks. I will try to figure this out.

![image](https://user-images.githubusercontent.com/90805529/217486549-ed5bd23e-1ed4-4347-ac97-0297f4b1d387.png)

**Comment by drakkan** [comment]
Ah do you mean from the WebUI. Browsers became slow if you upload many files at the same time

**Comment by ajaykumar-gbi** [comment]
That makes more sense. I tried with all non-webUI methods and it works.

**Comment by tooptoop4** [comment]
https://github.com/drakkan/sftpgo/blob/0190d0b849a8c24faa841d7600e8ab18f7d59590/templates/webclient/files.html#L733
