### ISSUE TITLE
TLS connection problems on port 21, without NAT

### ISSUE THREAD

**Issue by StefanSa** [drakkan/sftpgo#1185]
Hi there,
first of all thanks for the good tool sftpgo.
i have a strange problem here which i do not understand. 
```
SFTPGO_FTPD__BINDINGS__0__PORT=21
SFTPGO_FTPD__BINDINGS__0__TLS_MODE=0
SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_FILE="/etc/sftpgo/certs/ftp1.xxx.com.cer"
SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_KEY_FILE="/etc/sftpgo/certs/ftp1.xxx.com.key"
SFTPGO_FTPD__PASSIVE_PORT_RANGE__START=60000
SFTPGO_FTPD__PASSIVE_PORT_RANGE__END=65535
```
External access on port 21 (NAT) works with and without TLS.
Internal access, only FTP works unencrypted, connection establishing fails and time out.
The internal firewall rule already has ANY to FTP for testing.
But if i change the port from 21 to 2121, for example, TLS works both internally and externally.
Question, why are there problems with internal access (without NAT) with TLS and port 21 ?

OS `opensuse Leap 15.4`
Thanks for any Help

**Comment by drakkan** [comment]
Try enabling debug logs to understand the issue. I no longer provide free step by step support sorry.

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by StefanSa** [comment]
È un peccato, ma lo capisco.
Saluti all'Italia

**Comment by drakkan** [comment]
> È un peccato, ma lo capisco. Saluti all'Italia

il vero peccato è se il progetto muore perchè tutti gli utenti vogliono usarlo gratuitamente. Non c'è nessuna azienda dietro SFTPGo se non ricevo abbastanza sponsorizzazioni il progetto non avrà futuro. Buona fortuna per i tuoi progetti

**Comment by StefanSa** [comment]
Nicola, capisco bene il tuo punto di vista.
Tuttavia, vi auguro un grande successo con sftpgo.
Tanti saluti dalla Germania all'Italia.
