### ISSUE TITLE
WebClient - could not create root filesystem: secrets

### ISSUE THREAD

**Issue by nControl88** [drakkan/sftpgo#1189]
I've setup SFTPGo using this tutorial on [Medium](https://medium.com/google-cloud/sftpgo-access-to-gcs-via-sftp-e203e0783f6f) (basically installed it via `sudo apt install sftpgo`). All is running well and as it should.

When adding a user via the admin panel, I can access the WebClient via the assigned credentials.
After adding a user via the API, the WebClient is giving the following error: `could not create root filesystem: secrets (code=Unknown): localsecrets: Decrypt failed`.

An example of the API JSON used to add the user:
```
{
    "status": 1,
    "username": "info@email.com",
    "password": "$2a$10$...",
    "permissions": {
        "/": [
            "list",
            "download"
        ]
    },
    "filesystem": {
        "provider": 2,
        "s3config": {
            "access_secret": {}
        },
        "gcsconfig": {
            "bucket": "bucket...",
            "key_prefix": "internal",
            "credentials": {
                "status": "Secretbox",
                "payload": "...",
                "key": "...",
                "additional_data": "info@email.com"
            }
        }
    }
}
```

One thing I noticed is that no folder is created in `/srv/sftpgo/data/` after adding the user via the API, whereas a folder is created after a user is added via the admin panel. However, the response from the API is saying `"home_dir": "/srv/sftpgo/data/info@email.com"`.

From the logs:
```
Feb 12 14:27:57 ftp-server sftpgo[1981]: {"level":"warn","time":"2023-02-12T14:27:57.034","sender":"dataprovider_sqlite","connection_id":"HTTP_cfkfercd8q8s8cb8fnng","message":"could not create main filesystem for user \"info@email.com\" err: secrets (code=Unknown): localsecrets: Decrypt failed"}
Feb 12 14:27:57 ftp-server sftpgo[1981]: {"level":"warn","time":"2023-02-12T14:27:57.035","sender":"httpd","connection_id":"HTTP_cfkfercd8q8s8cb8fnng","message":"unable to check fs root: could not create root filesystem: secrets (code=Unknown): localsecrets: Decrypt failed"}
```

**Comment by drakkan** [comment]
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
