### ISSUE TITLE
rsync + chroot jail

### ISSUE THREAD

**Issue by mattlaue** [drakkan/sftpgo#1190]
Is there a way get rsync working inside a chroot jail?

The problem is that sftpgo can't access the rsync executable to exec/fork it.   Could we make it a 'built-in' command to sftpgo - even if all its doing is executing rsync from the not-chrooted filesystem?

I understand that rclone is an alternative but `rsync -avz` is just so much faster for syncing a big directory.

**Comment by drakkan** [comment]
try writing a wrapper bash script. Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by mattlaue** [comment]
It makes complete sense that if there is a workaround to go with that.  Could you elaborate on how to make that work?  It's not clear how the bash script would work.

Maybe we can reopen this ticket and make it a documentation request instead.  I'll be happy to submit a PR with a how-to once I've gotten rsync working in the chroot jail.
