### ISSUE TITLE
[support] armv6/7 in dockerhub

### ISSUE THREAD

**Issue by MushiTheMoshi** [drakkan/sftpgo#1193]

**Comment by drakkan** [comment]
See here

https://github.com/drakkan/sftpgo/commit/200b1d08c781b4197909a2b5268224ffe79ef088
https://github.com/drakkan/sftpgo/commit/46157ebbb63fc5c14bb88a77894ea8c916e8ed16

CI is unreliable if I add arm images. I have to retry many times before it succeeds.
Now that RPI supports arm64 is support for arm still relevant?

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
