### ISSUE TITLE
Web UI gets timed out after couple of seconds

### ISSUE THREAD

**Issue by ajaykumar-gbi** [drakkan/sftpgo#1194]
I have hosted SFTPGO on kubernetes and was trying to add users. Each time I try to provide all information for user to add the user, SFTPGO gets timed out and I again land to same login page. 

I tried to use below but didnt help:

```
    - name: SFTPGO_COMMON__IDLE_TIMEOUT
      value: "0"
```

**Comment by drakkan** [comment]
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by larssb** [comment]
@drakkan is it allowed for other users of the open-source version of sftpgo to chime in with a solution on an issue like this one?
