### ISSUE TITLE
Using the SFTPgo webinterface behind a load balancer not working

### ISSUE THREAD

**Issue by AOE-Review-Backend** [drakkan/sftpgo#1198]
Your CSRF implementation is relying on the remote address (which is only for logging purposes)
https://brightsec.com/blog/6-csrf-protection-best-practices-you-must-know/#csrf-tokens

_Originally posted by @AOE-Review-Backend in https://github.com/drakkan/sftpgo/issues/333#issuecomment-1436634170_

A setup on AWS is only working when you use a load balancer in one subnet. (remote address is not changing)

When the load balancer has more than one subnet it is not working anymore. (switching remote address)

**Comment by drakkan** [comment]
I no longer provide step-by-step support, sorry. Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
