### ISSUE TITLE
Quota per virtual folder

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#120]
Hello.

I see its possible to exclude virtual folder from user quota (https://github.com/drakkan/sftpgo/commit/3f75d46a16d75aa8e43c151b25a0ae7c68375e37), but would it be also possible to set quota per virtual folder? I guess that is currently not possible, but would be a nice addition. That way we can make user access multiple virtual folders from one account and enforcing their quotas.

For example, we have a "shared" folder for all our users, but do not want it to get out of control. We would disable user quota on that virutal folder and at the same time set that virtual folder quota to a chosen size.

**Comment by drakkan** [comment]
Hi,

this is currently not possible, the quota is per user and not per folder. I agree that this could be a nice addition.

I have to think about it a bit more, if we can avoid a new structure inside the provider this can be included in the upcoming 1.0.0 release otherwise it will be postponed

**Comment by drakkan** [comment]
Hi all,

I propose the following solution:

- add a new database structure "folders" with the fields `path`, `quota_size`, `quota_files`. This way we can define folders with associated quota limits
- add a mapping database structure "folders_mapping" that contains a reference to a user and to a folder and a `virtual_path` field to define the sftp path for the specified folder and user. This is basically a many-to-many relationship, with an additional field on the relation table, in the SQL world. I'll think later on how to represent this structure for the bolt (NoSQL) provider ...  and what is the better embedding there.

Sample, untested, SQL migration for PostgreSQL:

```
--
-- Create model Folder
--
CREATE TABLE "folders" ("id" serial NOT NULL PRIMARY KEY, "path" varchar(512) NOT NULL UNIQUE, "quota_size" bigint NOT NULL, "quota_files" integer NOT NULL);
--
-- Create model FolderMapping
--
CREATE TABLE "folders_mapping" ("id" serial NOT NULL PRIMARY KEY, "virtual_path" varchar(512) NOT NULL, "folder_id" integer NOT NULL, "user_id" integer NOT NULL);
--
-- Create constraints 
--
ALTER TABLE "folders_mapping" ADD CONSTRAINT "unique mapping" UNIQUE ("user_id", "folder_id");
ALTER TABLE "folders_mapping" ADD CONSTRAINT "folders_mapping_folder_id_fk_folders_id" FOREIGN KEY ("folder_id") REFERENCES "folders" ("id") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "folders_mapping" ADD CONSTRAINT "folders_mapping_user_id_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "folders_mapping_folder_id_idx" ON "folders_mapping" ("folder_id");
CREATE INDEX "folders_mapping_user_id_dx" ON "folders_mapping" ("user_id");
```

I want to keep the `virtual_folders` field that is already defined for users: this field will be used for "private" virtual folders, while the new many-to-many relationship will be used for "public" virtual folders. 

Public virtual folders can be shared among several users and they will have their own quota limits.

For private virtual folders the quota limits are included in the ones defined for the user, alternately the folder can be excluded from the quota calculation, basically the current behaviour.

Use cases:

1) you want to map a folder outside the home directory for a single user: you will use a private virtual folder. The files inside this virtual folder will be added to the user quota limits or they can be excluded using the existing setting
2) you want to map a folder outside the home directory for multiple users: you will use a public virtual folder. The public virtual folder has its own quota limits unrelated to the users ones

I think it make no sense to have public virtual folders whose content increases user quota and technically this would mean that we have to do a database/dataprovider updates for many users each time a new file is uploaded to such folders. If someone shares the same folder among several users this would generate a lot of queries. So I would avoid this use case for both technical and logical reasons.

Do you have suggestions and/or other use cases to consider? thanks

**Comment by sergiz** [comment]
How will these public virual folser be created and managed?

My use case is the following:
I have many models, let's called them "boxes" which have their own quota limit. I also have many users, that can have access to one or more of these boxes. I use external authentication, and users' access to different boxes and boxes' quotas can change anytime.

My proposal for management is the following (ensuring maximum flexibility). I'm talking from the external auth perspective.
When you return serialized user data, it also includes public virtual folders details (virtual path, real path, quota size and quota files). Sftpgo then checks "folders" table, if these real paths already exist. If they don't they are created, but if they do, their limits are updated with the new values. "folders_mapping" for the user is then also synhronized with the new data. After this, sftpgo should check, if we have any "folders" left that have no users, and in that case remove them.

This way we can simply redefine these relations on every user login and we do not have to handle any logic about it externally. It keeps the same level of flexibility as with current virtual folders.

**Comment by drakkan** [comment]
> How will these public virual folser be created and managed?
> 

in general via new REST API

> My use case is the following:
> I have many models, let's called them "boxes" which have their own quota limit. I also have many users, that can have access to one or more of these boxes. I use external authentication, and users' access to different boxes and boxes' quotas can change anytime.
> 
> My proposal for management is the following (ensuring maximum flexibility). I'm talking from the external auth perspective.
> When you return serialized user data, it also includes public virtual folders details (virtual path, real path, quota size and quota files). Sftpgo then checks "folders" table, if these real paths already exist. If they don't they are created, but if they do, their limits are updated with the new values. "folders_mapping" for the user is then also synhronized with the new data. After this, sftpgo should check, if we have any "folders" left that have no users, and in that case remove them.
> 

these are implementation details that I'll evaluate while developing this new feature. Probably I'll give a way to add/update also the external folders based on the external auth JSON response.

> This way we can simply redefine these relations on every user login and we do not have to handle any logic about it externally. It keeps the same level of flexibility as with current virtual folders.

the relations will  be likely redefined on every user update (and so on every external auth login) but probably you have to think yourself to the unused folders cleanup. The login must be as fast as possibile I want to avoid uneeded queries. Eventually I can provide an external script to run periodically for this job (or it could be user contributed). It is the same for the users: once a user login via external auth it will remain inside the dataprovider forever if you don't remove it using the REST API.

In general, running a periodic script to update quotas is recommended too, the quota usage is indicative, it could be wrong for several reasons that are very hard or near impossibile to handle in all use cases.

**Comment by sergiz** [comment]
> the relations will be likely redefined on every user update (and so on every external auth login) but probably you have to think yourself to the unused folders cleanup. The login must be as fast as possibile I want to avoid uneeded queries.

But the difference is, that there is no way to tell, if user should be deleted and when, while for these virtual folders there's a clear way, if there is no user left that is linked to it.
Considering the usage of external auth, which will probably take hundreds of milliseconds or even seconds, a query which will execute in around 1ms, shouldn't be a concern in my opinion.

**Comment by sergiz** [comment]
But the difference is, that there is no way to tell, if user should be deleted and when, while for these virtual folders there's a clear way, if there is no user left that is linked to it.
Considering the usage of external auth, which will probably take hundreds of milliseconds or even seconds, a query which will execute in a few milliseconds shouldn't really be a concern in my opinion.

**Comment by sergiz** [comment]
> the relations will be likely redefined on every user update (and so on every external auth login) but probably you have to think yourself to the unused folders cleanup. The login must be as fast as possibile I want to avoid uneeded queries. 

But the difference is, that there is no way to tell, if user should be deleted and when, while for these virtual folders there's a clear way, if there is no user left that is linked to it.
Considering the usage of external auth, which will probably take hundreds of milliseconds or even seconds, a query which will execute in 1ms shouldn't really be a concern in my opinion.

**Comment by drakkan** [comment]
Hi, this is a feature with a discrete impact on the existing code, let's first ship it and after that we can discuss about its implementation details and eventually improve it, thanks

**Comment by sergiz** [comment]
Considering that there hasn't been any input from other users that might find this useful, I think it would make sense to pospone it to some later point, and focus on other areas now and get v1 out first.

**Comment by drakkan** [comment]
I'm working on it in my free time. I think it could be a useful addition but it requires a lot of changes. I'm trying to convert the old virtual folders to the new structure too. I hope to have something testable before the end of this week and complete the patch before the end of the next week. 

I would like to include this feature in 1.0. This means pospone the release to have enough time for feedbacks, anyway I'll decide after I have a working patch.

This is the diff for current WIP  just to give you the idea of the required effort:

```
git diff --numstat 
1       1       README.md
1       1       config/config.go
467     17      dataprovider/bolt.go
138     14      dataprovider/dataprovider.go
274     19      dataprovider/memory.go
64      30      dataprovider/mysql.go
65      30      dataprovider/pgsql.go
540     78      dataprovider/sqlcommon.go
97      24      dataprovider/sqlite.go
117     22      dataprovider/sqlqueries.go
14      11      dataprovider/user.go
40      7       httpd/api_folder.go
50      3       httpd/api_quota.go
2       2       httpd/api_user.go
2       0       httpd/httpd.go
75      29      httpd/httpd_test.go
6       2       httpd/internal_test.go
5       0       httpd/router.go
15      5       httpd/web.go
116     88      sftpd/handler.go
16      10      sftpd/internal_test.go
32      27      sftpd/scp.go
71      14      sftpd/sftpd.go
32      44      sftpd/sftpd_test.go
30      24      sftpd/transfer.go
2       2       sftpgo.json
2       2       templates/user.html
6       4       vfs/osfs.go
23      3       vfs/vfs.go
```

**Comment by sergiz** [comment]
Nice work! I see it's a lot of changes, that's why it might be better to hold it off for v1.1 and focus on getting the stable version out first.
