### ISSUE TITLE
Problems with Webdav and different ports

### ISSUE THREAD

**Issue by StefanSa** [drakkan/sftpgo#1200]
Hi Nicola.
We currently use the webdav service with https on port 10443.
It works for some Windows 10 clients but not for others, same local GPO policy.
For those it does not work, the error message appears that the server is not found, but the name resolution works without any problem.
After a longer search we understand that the "file explorer" sometimes has problems with a port on the FQDN ":10443".
This may be a bug in Windows depending on the version and patch level.

Now to my actual question.
Is there a possibility that WEBDav uses only port 443 like httpd ? I know that this is currently not possible, but would have the advantage that you would not have to attach a port to the FQDN. Nextcloud, Owencloud derivate do it exactly this way.

Grazie per il vostro tempo e il vostro impegno.
Saluti all'Italia

**Comment by StefanSa** [comment]
Postscript:
on the clients that show these problems, these URL / FQDN do not work.
`\\Servername@SSL@10443\dav` and `https://Servername:10443/dav `

**Comment by StefanSa** [comment]
false alarm.
Webdav on Windows client need service "WebClient".
After start this service, problem solved.

**Comment by StefanSa** [comment]
had to reopen the ticket after all.
It turns out that a running "WebClient" service is only half the solution.
There are still quite a few Windows Cleinst that have problems with a FQDN / URL that has an attached port. -> `:10443`
Currently we have solved that the WebDAV service works on port `443` and the httpd service on `10443`. 

So it would be of great advantage if httpd and webdav can `share port 443`.

**Comment by drakkan** [comment]
This could be done, but it will increase the complexity of the code and thus the maintenance burden. You can easily setup a reverse proxy using nginx or something similar (or ask Microsoft to fix their bug).
I'll leave the issue open to think about it some more

**Comment by StefanSa** [comment]
Hi Nicola,
On the RProxy i should have also thought of, thanks for the tip Nicola.
I know that these are complex changes and need time.

Come sempre.
Grazie per il vostro tempo e il vostro impegno.
Benvenuti in Italia

**Comment by StefanSa** [comment]
Hi Nicola,
here is a working configuration for an apache2 reverse proxy. With this configuration it passes the SSL Labs test with A+. 
This may also help others who have encountered the same problem as me.
`vhost-ssl-sftpgo.conf`
```
<IfDefine SSL>
<IfDefine !NOSSL>

<VirtualHost *:443>
        ServerName ftp1.test.com

        LimitRequestBody 1048600000
        # SSLRenegBufferSize 1048600000

        SSLProxyEngine On
        ProxyPreserveHost On
        RewriteEngine On

        RewriteRule ^/dav(.*) https://127.0.0.1:20443/dav/$1 [P,L]
        ProxyPassReverse /dav/ https://127.0.0.1:20443/dav
        RewriteRule ^/(.*) https://127.0.0.1:10443/$1 [P,L]
        ProxyPassReverse / https://127.0.0.1:10443

        <Directory />
        SSLRenegBufferSize 1048600000
        </Directory>

        <Directory /dav>
        SSLRenegBufferSize 1048600000
        </Directory>

        Header add Strict-Transport-Security: "max-age=15552000;includeSubdomains"
        SSLEngine               on
        SSLCompression          off
        SSLProtocol             -all +TLSv1.2 +TLSv1.3
        SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHA>

        SSLHonorCipherOrder     off
        SSLSessionTickets       off
        ServerSignature         off
        LogLevel warn
        ErrorLog /var/log/apache2/error_log
        TransferLog /var/log/apache2/access_log
        CustomLog /var/log/apache2/ssl_request_log   ssl_combined

        SSLCertificateFile /etc/sftpgo/certs/ftp1.test.com.cer
        SSLCertificateKeyFile /etc/sftpgo/certs/ftp1.test.com.key
        SSLCertificateChainFile /etc/sftpgo/certs/fullchain.cer
</VirtualHost>

</IfDefine>
</IfDefine>


```

**Comment by drakkan** [comment]
Thanks for sharing. I suggest to configure SFTPGo over http to avoid double encryption/decryption

**Comment by StefanSa** [comment]
Nicola question,
i am currently successfully testing the reverse proxy with http2, is this useful ev. also for the future.
WebDav and Httpd currently work with it without problem.

**Comment by drakkan** [comment]
Yes, I think this is the best approach, you can also easily configure http to https redirects etc.

**Comment by Gunni** [comment]
While the above workaround would work, I'd like to suggest supporting this as a feature in sftpgo.
