### ISSUE TITLE
user setting overwrite with external authentication

### ISSUE THREAD

**Issue by assices** [drakkan/sftpgo#1203]
Dear all,

I configured external authentication using ldap.
The only user setting that authentication program returns to SFTPgo is the home directory parameter (derivated from ladap attributes), that is mandatory.
Authentication process works fine but I get an issue.

I would like to modify other user settings from Web GUI, but at each subsequent login for an user, all settings are overwritten to default (except home dir).
I would have expected only the returned parameters (home dir) is updated from external auth process if the user exists.

Is this expected behavior? 
If, yes, is there a workaround to solve my issue?

Thanks a lot,
Andrea

**Comment by drakkan** [comment]
Hello, this is how it works, you have to return a complete user from your external auth program
