### ISSUE TITLE
user was removed and deleted but still upload

### ISSUE THREAD

**Issue by anhttfintech** [drakkan/sftpgo#1204]
anyone facing this issue?

**Comment by drakkan** [comment]
I can't reproduce

**Comment by anhttfintech** [comment]
@drakkan if u want, i can give you a demo test sftp server

**Comment by drakkan** [comment]
> @drakkan if u want, i can give you a demo test sftp server

No thanks, read the support policy

**Comment by anhttfintech** [comment]
lol bad repo

**Comment by drakkan** [comment]
Just for reference, if I delete a user with an upload in progress from the WebAdmin UI, the connection is forcibly closed like this

```
sftp> put android-studio-ide-181.5056338-linux.zip 
Uploading android-studio-ide-181.5056338-linux.zip to /android-studio-ide-181.5056338-linux.zip
Connection closed.  81.5056338-linux.zip        0% 1792KB 242.1KB/s 1:10:49 ETA
Connection closed
```
