### ISSUE TITLE
Release with upstream Crypto updates?

### ISSUE THREAD

**Issue by jasonwc** [drakkan/sftpgo#1205]
Hey there @drakkan! Thanks for all the work on this project. 

We recently had an issue where a vendor attempted to connect using the `diffie-hellman-group-exchange-sha256` Kex Algorithm and connections were failing.

We found this [issue](https://github.com/drakkan/sftpgo/issues/858) explaining what we were seeing. Since then it looks like you've added support in [this commit](https://github.com/drakkan/crypto/commit/dd87049cc9df4e5a1d8f266009e175e05c9c8271) in drakkan/crypto and also pulled it into the project on `main` [here](https://github.com/drakkan/sftpgo/blob/main/go.sum#L852)

Assuming our assumption is correct, we were wondering if that was scheduled to be released anytime soon so that we could upgrade via `apt` or if we're better off building from source for now. Thanks!

**Comment by drakkan** [comment]
Hello, `diffie-hellman-group-exchange-sha256` is already included in recent releases but disabled by default. Please refer to the docs to understand how to enable it

**Comment by jasonwc** [comment]
Awesome. Thank you!

**Comment by jasonwc** [comment]
For folks getting to this in the future, here is a commit with a diff that shows how to configure different Kex algorithms: https://github.com/drakkan/sftpgo/commit/ec1d20f46f2242690b80902fd78be96812caa597
