### ISSUE TITLE
Action hooks

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#121]
Add possibility to define pre and post hooks for various actions, for example commands.

Here are two examples that would utilize this:

a) Recycle bin
When "delete" command is received, run a pre_delete hook. The script that is registered to the hook receives a payload, so you can move a file that was supposed to get deleted to your desired location Then you echo a specific phrase and the real delete command doesn't get executed. The key point is, that you can control whether the real command gets executed.

b) Adding data to response
I would like to add mimetype to the response of "list" command. So I register my script to post_list hook which receives a response that is about to be sent to the client. I can then modify the response (adding mimetype in this case) and output the modified response that is then sent to the client.

I think this shouldn't be too hard to add since the hooks system is already in place (https://github.com/drakkan/sftpgo/blob/master/docs/custom-actions.md), but it seems to be geared more towards notifications after execution. With my proposal we would have external control over execution and its response.

I would propose the following config structure:
```
{
    "hooks": {
        "commands": {
            "list": {
                "post": [
                    "/home/usr/something.sh",
                    "/home/usr/something_else.sh"
                ]
            },
            "delete": {
                "pre": [
                    "/home/usr/move_to_bin.sh"
                ]
            }
        }
    }
}
```

**Comment by drakkan** [comment]
> Add possibility to define pre and post hooks for various actions, for example commands.
> 
> Here are two examples that would utilize this:
> 
> a) Recycle bin
> When "delete" command is received, run a pre_delete hook. The script that is registered to the hook receives a payload, so you can move a file that was supposed to get deleted to your desired location Then you echo a specific phrase and the real delete command doesn't get executed. The key point is, that you can control whether the real command gets executed.
> 

I like this idea

> b) Adding data to response
> I would like to add mimetype to the response of "list" command. So I register my script to post_list hook which receives a response that is about to be sent to the client. I can then modify the response (adding mimetype in this case) and output the modified response that is then sent to the client.
> 

I don't understand what you mean here, can you please clarify with a full example?

> I think this shouldn't be too hard to add since the hooks system is already in place (https://github.com/drakkan/sftpgo/blob/master/docs/custom-actions.md), but it seems to be geared more towards notifications after execution. With my proposal we would have external control over execution and its response.
> 
> I would propose the following config structure:
> 
> ```
> {
>     "hooks": {
>         "commands": {
>             "list": {
>                 "post": [
>                     "/home/usr/something.sh",
>                     "/home/usr/something_else.sh"
>                 ]

I don't think we need a list of hooks, a single command/http notification should be enough the receiver can do multiple action if needed

>             },
>             "delete": {
>                 "pre": [
>                     "/home/usr/move_to_bin.sh"
>                 ]
>             }
>         }
>     }
> }
> ```

**Comment by sergiz** [comment]
> I don't understand what you mean here, can you please clarify with a full example?

When I request a "list" from SFTP server, I would like that each file entry has mime-type added to it as well. Using a post hook, I would loop through files that "list" command made and add its mime-type to it. Then this modified response would be sent to the client.

> I don't think we need a list of hooks, a single command/http notification should be enough the receiver can do multiple action if needed

Ah yes, simple is better. Just make it a string instead of array.
```
        "delete": {
            "pre": "/home/usr/move_to_bin.sh"
        }
```

**Comment by drakkan** [comment]
> > I don't understand what you mean here, can you please clarify with a full example?
> 
> When I request a "list" from SFTP server, I would like that each file entry has mime-type added to it as well. Using a post hook, I would loop through files that "list" command made and add its mime-type to it. Then this modified response would be sent to the client.
> 

I don't think that this is possible, the response for the SFTP clients must be conformant to the SFTP specs, we cannot add fields as we wish, the SFTP clients will not understand them

> > I don't think we need a list of hooks, a single command/http notification should be enough the receiver can do multiple action if needed
> 
> Ah yes, simple is better. Just make it a string instead of array.
> 
> ```
>         "delete": {
>             "pre": "/home/usr/move_to_bin.sh"
>         }
> ```

we could probably reuse the existing configuration something like this:

```
"actions": {
      "execute_on": ["upload","predelete","delete"],
      "command": "....",
      "http_notification_url": "http://127.0.0.1:8081/sftp"
    },
```

we should also replace `command` and `http_notification_url` with a single hook as I already did for external auth/pre login hooks

**Comment by sergiz** [comment]
> I don't think that this is possible, the response for the SFTP clients must be conformant to the SFTP specs, we cannot add fields as we wish, the SFTP clients will not understand them

But you can use them in your custom SFTP client ;) However, SFTP version 6 supports multiple of addiitonal attributes, including mime (https://www.greenend.org.uk/rjk/sftp/sftpversions.html).

**Comment by drakkan** [comment]
> > I don't think that this is possible, the response for the SFTP clients must be conformant to the SFTP specs, we cannot add fields as we wish, the SFTP clients will not understand them
> 
> But you can use them in your custom SFTP client ;) However, SFTP version 6 supports multiple of addiitonal attributes, including mime (https://www.greenend.org.uk/rjk/sftp/sftpversions.html).

we (pkg/sftp) implements version 3 of the specs (the same as OpenSSH) the client checks the version returned from the server in `SSH_FXP_INIT`. 

So to add mime type we cannot simply add it in our custom way. The server should declare version 6 in init packet and must set the appropriate bit in `supported-attribute-mask`, after this the clients that support version 6 of the specs can read mime type. All of this is almost transparent for sftpgo, the work must be done in pkg/sftp. 

I don't want to support custom clients, anyway the support for custom clients must be added to pkg/sftp and not here

**Comment by sergiz** [comment]
Ah understandabe, then please disregard my suggestion about modifying response.

**Comment by drakkan** [comment]
> Ah understandabe, then please disregard my suggestion about modifying response.

Yes, I'll first remove the double notification from actions (command+http) in favor of a single hook that can be a command or an HTTP url and then I'll add the pre-delete action

**Comment by vb8448** [comment]
Hi @drakkan,
sorry for posting on this old issues but i'm interested in a specific use case and think a 'pre-upload' hook could be a good option.

USE CASE: if a user upload an existing file i want to keep the existing file(renaming it with a random prefix or suffix). This could be easyly done with a pre-upload hook.

What do you think?
Thanks.

**Comment by drakkan** [comment]
Hi,

please stop posting here, when this issue was opened SFTPGo was basically a different program, many things have changed in the last year.

pre-upload hook is already supported if you use the development version, take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/custom-actions.md).

I think you are very optimistic, if you rename a file in your pre-upload hook resuming an upload will not work anymore. It is not very common but SFTP protocol allows opening a big file and writing only xxx bytes at xxx offset and some clients use this feature. You should copy the file instead of renaming it but copy could take a lot of time if the file is big ...

If you want to keep track of quotas in SFTPGo, after renaming/copying the old file you must inform SFTPGo that you have added a file (there are specific REST APIs for this) otherwise you will break quota calculation
