### ISSUE TITLE
Env variable Docker image K8s deployment not working

### ISSUE THREAD

**Issue by fontexD** [drakkan/sftpgo#1214]
ive tried to set env variable but nothing is defined in the .json config nor applied. followed toe documentration but without any luck, using :latest

        - name: SFTPGO_FTPD__0__CERTIFICATE_FILE
          value: "/cert/cert.pem"
        - name: SFTPGO_FTPD__CERTIFICATE_KEY_FILE
          value: "/cert/key.pem"
          
          both of this is not working, am i missing something out ?

**Comment by drakkan** [comment]
Please read the docs more carefully. There is also this exact example in the howto section
