### ISSUE TITLE
Issue when upload files more than 1GB web mode | file corrupted or truncated (v2.4.4)

### ISSUE THREAD

**Issue by daniel8800** [drakkan/sftpgo#1216]
Hello Team.

I'm having an issue when I try to upload a 1.5gb file in web mode; after the file is uploaded it gets truncated. We are using the version 2.4.4

Example:

I created a 1.5gb file with the following command

Command: head --bytes=1610612736  /dev/urandom > prueba.ova

After that, I tried to upload it using the drag and drop feature and while it's getting upload, I was doing a simple "ls" to see the file grows, but... when it reachs the 1gb, it starts from 0kb size 

990M

-rw-r--r-- 1 sftpgo sftpgo 990M Feb 28 09:25 prueba.ova

999M
user@sftp-debian:/srv/sftpgo/data/test$ ls -lh
total 999M
-rw-r--r-- 1 sftpgo sftpgo 999M Feb 28 09:25 prueba.ova

and then starts again from Kb

user@sftp-debian:/srv/sftpgo/data/test$ ls -lh
total 960K
-rw-r--r-- 1 sftpgo sftpgo 960K Feb 28 09:25 prueba.ova

user@sftp-debian:/srv/sftpgo/data/test$ ls -lh
total 8.6M
-rw-r--r-- 1 sftpgo sftpgo 8.6M Feb 28 09:25 prueba.ova

I tried with chrome and firefox and without drag and drop (using the upload button) but all with the same result.
The workaround to this issue was to upload the file using the client sftp (that works perfect)

Hope you can help me with this problem.

Thanks!

**Comment by daniel8800** [comment]
Something I just forget to say, after the file get uploaded from the web interface to the folder, I get truncated (example, the 1.5gb file is now 1gb size) but if I upload the same file from sftp, using for example, filezilla client, I get upload correctly.

**Comment by drakkan** [comment]
Hello,

1GB is the default limit. Please refer to the docs to understand how to change or remove this limit. This question was asked many time in the past, search the old issue if you need more detailed help

**Comment by daniel8800** [comment]
Thanks! you where right!
