### ISSUE TITLE
Feature: Minimum password strength?

### ISSUE THREAD

**Issue by havedill** [drakkan/sftpgo#1219]
Maybe I'm missing something from the configurations but I feel like i've looked everywhere.

I noticed a Web client user has the ability to set their password to something as simple as a single character.

Is there a way to set minimum password lengths or strength requirements?

**Comment by drakkan** [comment]
Set a min_entropy for the password. It is documented

**Comment by havedill** [comment]
Thank you sir, I was def not expecting that to be in the provider section!
