### ISSUE TITLE
cp and rm commands

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#122]
I think adding "cp" and "rm" SSH commands would be a very nice addition, especially their "-r" options. That way we can avoid making tons of requests for removing a folder with files and downloading and uploading every single file in case of copy.

**Comment by drakkan** [comment]
Hi, 

merging directories is doable but it requires some effort, we should, at least, check file by file if we are overwriting an existing file in the destination directory or if it is a new file and then we need to calculate the diff (as number of files and size) to check quota limits before copying any file (using `cp` does not change nothing here).

Depending on your use case `rsync` could help.

I don't plan to work on this feature, at least in the near future, a pull request is appreciated. If you prefer please open a new issue, I'll mark it as "help wanted", thanks

**Comment by sergiz** [comment]
Ah understandable. Thanks for the idea with rsync.
