### ISSUE TITLE
Public/private key authentication not working

### ISSUE THREAD

**Issue by Zahuczky** [drakkan/sftpgo#1221]
Hi!

When I try to add a public key to a user, I get this error message at the top of the page:
```Validation error: could not parse key nr. 1: ssh: no key found```

I tried including/excluding the header and comments from the key, but still no dice. 

The format I initially tried is
```
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "3072-bit RSA, converted by {redacted}@{redacted}"
AAAA........
---- END SSH2 PUBLIC KEY ----
```

I also tried 
```
---- BEGIN SSH2 PUBLIC KEY ----
AAAA........
---- END SSH2 PUBLIC KEY ----
```
and
```
AAAA........
```

**Version: 2.4.3**

**Comment by drakkan** [comment]
The public key must be in OpenSSH format

```
ssh-rsa AAAA...
```
