### ISSUE TITLE
FYI volumes have to be writeable to all (or uid 100999) not just uid 1000 to start container

### ISSUE THREAD

**Issue by tonydiep** [drakkan/sftpgo#1223]
Thanks for making sftpgo. Love it!

# ISSUE
When starting docker image with --mount option container cannot start

* Documentation says volumes need to be read and writeable to uid 1000 because that's the user in the container
* I confirmed volumes were writeable to uid 1000
* Confirmed sftpgo user in container cannot write to volumes

# WORKAROUND

* allowing everyone to write solved problem

chmod -R a+w <the_volumes>

# DISCUSSION

* I noticed the files belong to uid 100999, not uid 1000

**starting podman / docker with --userns=keep-id solves issues of using uid 1000 to match the rest of the documentation.**

**Comment by drakkan** [comment]
Hello,

if it works with `--userns=keep-id` it means that the id specified in the Dockerfile is not respected. The docs should work fine with vanilla docker
