### ISSUE TITLE
scp command not supported

### ISSUE THREAD

**Issue by 0sorkon** [drakkan/sftpgo#1224]
We have Virtualizor which must backs up its database to sftpgo server via ssh , but its doesnt work correctly now. When trying to create a backup, sftpgo logs show the following:
> "message":"unsupported scp command, args: [-pt ./DB/database.sql.gz]"}

As a result, the backup is not created and ends up with an error.
Unfortunately, the way and arguments with which virtualizor backups are hardcoded and cannot be changed. How can the situation be fixed?

**Comment by drakkan** [comment]
Hello, I might take a look, but I only accept requests like this from people who support the project. You are paying for Virtualizor and asking for free support/bug fix/change request here
