### ISSUE TITLE
/api/v2/folders - Your token audience is not valid

### ISSUE THREAD

**Issue by oNdsen** [drakkan/sftpgo#1229]
SFTPGo Version: SFTPGo 2.4.4-b9255047-2023-02-04T16:00:25Z

We have a special Transfer case which is build up like following:
```
"Transfer"
    "Subfolder 1"
        "Read"
        "Write"
    "Subfolder 2"
        "Read"
        "Write"
...
```

There is an Admin, which has recursive Access to "Transfer" to put and get Files for all Subfolders.
There are Users for every "Subfolder *", which has only access to his specific "Subfolder X".
User Permissions are set to:
```
"permissions" = @{
	"/" = @(
		"list"
	)
	"/Read" = @(
		"list",
		"download"
	)
	"/Write" = @(
		"list",
		"download",
		"upload",
		"delete"
	)
}
```

It seems that the User creation process via API works, also the Folder "/Transfer/Subfolder X" and the User itself is created successfully with the correct Permissions.
But the Subfolders "/Transfer/Subfolder X/_Read_" and "/Transfer/Subfolder X/_Write_" are not being created.

When im trying to check if the Folder exists, it fails with "Message: Your token audience is not valid"
Using the Bearer from an Administrator via /api/v2/folders (GET)

How can i check for specific Folders and create them if not existent?

Thanks,
oNdsen

**Comment by drakkan** [comment]
closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
