### ISSUE TITLE
Can't get FEATURES env var to work

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#123]
Hello.

So I build a docker image using
```
docker build \
    --build-arg FEATURES=nogcs,nos3,nobolt,nomysql,nopgsql,nosqlite,noportable \
    -t sftpgo:build \
    https://github.com/drakkan/sftpgo.git#master:docker/sftpgo/alpine
```
but I can still use the features, that were supposed to be disabled. What am I doing wrong?

And a side question. Is it normal that the image that it's used to build from source is around 2.5GB big?

**Comment by drakkan** [comment]
Hi,

can you post the version number for your build? You can get it using `sftpgo -v` or from the startup logs:

```
{"level":"info","time":"2020-05-28T07:49:30.748","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.6-dev-ad53429-2020-05-23T10:28:46Z -gcs +s3 -bolt -mysql -pgsql +sqlite -portable, config dir: /srv/sftpgo/config, config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, profile: false"}
```

it contains the git commit and the available features. thanks

**Comment by sergiz** [comment]
Aha, the problem was that it was checking out commit 15298b0. I had a builder image from before, but when I changed my build command, it created a new builder image, but was still stuck with the old git pull.

I deleted all images and now it recreated everyrthing and it works. Builder image is now down to 2.12GB.

**Comment by drakkan** [comment]
ok, thanks for reporting back.

I have similar size for the build image, the runtime image is much smaller

**Comment by sergiz** [comment]
No problem. Do you plan to push official docker images on tags? It would be very useful, so we can simply build from them and don't have to download these 2GB+ builders ourselves.

I would recommend a normal and a slim version (with all optional features disabled), for example:
sftpgo:0.9.6-alpine
sftpgo:0.9.6-alpine-slim

**Comment by drakkan** [comment]
> No problem. Do you plan to push official docker images on tags? It would be very useful, so we can simply build from them and don't have to download these 2GB+ builders ourselves.
> 

not for now, I don't like docker so much and so I don't know it very well

> I would recommend a normal and a slim version (with all optional features disabled), for example:
> sftpgo:0.9.6-alpine
> sftpgo:0.9.6-alpine-slim
