### ISSUE TITLE
custom backup filename 

### ISSUE THREAD

**Issue by huobazi** [drakkan/sftpgo#1231]
I used SFTPGo version  2.4.4-b9255047, and set the backup by event action and rules, so I got the files like below:

![image](https://user-images.githubusercontent.com/341526/224936213-bfe4dbd1-c7ca-468e-8d45-52bc8a5b942b.png)

When I  review the code, I found the filename is like ```backup_Monday_12.json```,  I'm not familiar with Golang, but I wonder is the files will be **overwritten** in the next week?
https://github.com/drakkan/sftpgo/blob/b719d03ebe18a70cbe7874f92216ef3f582fe5f7/internal/dataprovider/dataprovider.go#L535

Temporary, I use the backup scripts by https://github.com/drakkan/sftpgo/blob/main/examples/backup/backup and change the filename format with ``` %Y-%m-%d %H:%M:%S.%f ``` then I got the files like below:

![image](https://user-images.githubusercontent.com/341526/224936819-a5bc810c-fa68-4bf5-b2d2-58d885acd8d7.png)

I hoped I can set the filename with any custom format, and **automatically delete** the old files by date settings.

**Comment by drakkan** [comment]
the filename is overwritten, automatically delete old files by date settings is not supported

**Comment by drakkan** [comment]
You can add another action to the backup rule and execute (for example a script) and execute your custom logic there
