### ISSUE TITLE
sftp services stop after more than 18 sessions

### ISSUE THREAD

**Issue by maniasso** [drakkan/sftpgo#1238]
I have been running the sftpgo under openshift, however I noticed the sftpgo servers stops to work if more than 18th simultaneous session

{"level":"debug","time":"2023-03-16T15:50:00.275","sender":"common","connection_id":"01e1202cbb024b8fdab2695031478c4b64ca2395268b0b55ed5e9f8b1f5c8e19","message":"ssh connection added, num open connections: 19"}
{"level":"debug","time":"2023-03-16T15:50:00.277","sender":"SFTP","connection_id":"SFTP_01e1202cbb024b8fdab2695031478c4b64ca2395268b0b55ed5e9f8b1f5c8e19_1","message":"connection added, local address \"10.128.5.44:2022\", remote address \"10.128.4.1:49258\", num open connections: 19"}
{"level":"info","time":"2023-03-16T15:50:00.289","sender":"SFTP","connection_id":"SFTP_ea6c02db64f52dabd8d0be6f981b39065dc4d50cffd31244618f99c0b13528bc_1","message":"connection closed, sent exit status {Status:0} error: EOF"}
{"level":"debug","time":"2023-03-16T15:50:00.289","sender":"SFTP","connection_id":"SFTP_ea6c02db64f52dabd8d0be6f981b39065dc4d50cffd31244618f99c0b13528bc_1","message":"connection removed, local address \"10.128.5.44:2022\", remote address \"10.128.4.1:36334\" close fs error: <nil>, num open connections: 18"}
{"level":"debug","time":"2023-03-16T15:50:00.290","sender":"common","connection_id":"ea6c02db64f52dabd8d0be6f981b39065dc4d50cffd31244618f99c0b13528bc","message":"ssh connection removed, num open ssh connections: 18"}
{"level":"info","time":"2023-03-16T15:50:01.077","sender":"common","message":"active connections from 10.128.4.1 21/20"}
{"level":"debug","time":"2023-03-16T15:50:01.077","sender":"SSH","message":"connection not allowed from ip \"10.128.4.1\": you are not allowed to connect"}
{"level":"info","time":"2023-03-16T15:50:01.081","sender":"common","message":"active connections from 10.128.4.1 21/20"}
{"level":"debug","time":"2023-03-16T15:50:01.081","sender":"SSH","message":"connection not allowed from ip \"10.128.4.1\": you are not allowed to connect"}
{"level":"info","time":"2023-03-16T15:50:01.119","sender":"SSH","connection_id":"ec947899010f0221c54aa321403d46b1d20be18b240843993a5cd04cc27d8aed","message":"User \"admin\" logged in with \"password\", from ip \"10.128.4.1\", client version \"SSH-2.0-JSCH_0.1.54\""}
**{"level":"debug","time":"2023-03-16T15:50:01.120","sender":"common","connection_id":"ec947899010f0221c54aa321403d46b1d20be18b240843993a5cd04cc27d8aed","message":"ssh connection added, num open connections: 19"}**
{"level":"debug","time":"2023-03-16T15:50:01.125","sender":"SFTP","connection_id":"SFTP_ec947899010f0221c54aa321403d46b1d20b**e18b240843993a5cd04cc27d8aed_1","message":"connection added, local address \"10.128.5.44:2022\", remote address \"10.128.4.1:43562\", num open connections: 19"}**
{"level":"info","time":"2023-03-16T15:50:02.099","sender":"common","message":"active connections from 10.128.4.1 21/20"}
{"level":"debug","time":"2023-03-16T15:50:02.099","sender":"SSH","message":"connection not allowed from ip \"10.128.4.1\": you are not allowed to connect"}
{"level":"info","time":"2023-03-16T15:50:02.103","sender":"common","message":"active connections from 10.128.4.1 21/20"}
{"level":"debug","time":"2023-03-16T15:50:02.103","sender":"SSH","message":"connection not allowed from ip \"10.128.4.1\": you are not allowed to connect"}
{"level":"info","time":"2023-03-16T15:50:03.122","sender":"common","message":"active connections from 10.128.4.1 21/20"}
{"level":"debug","time":"2023-03-16T15:50:03.122","sender":"SSH","message":"connection not allowed from ip \"10.128.4.1\": you are not allowed to connect"}
{"level":"info","time":"2023-03-16T15:50:03.127","sender":"common","message":"active connections from 10.128.4.1 21/20"}
{"level":"debug","time":"2023-03-16T15:50:03.127","sender":"SSH","message":"connection not allowed from ip \"10.128.4.1\": you are not allowed to connect"}
{"level":"debug","time":"2023-03-16T15:50:04.958","sender":"sftpd","message":"failed to accept an incoming connection: read tcp 10.128.5.44:2022->10.128.4.1:53811: read: connection reset by peer"}
{"level":"debug","time":"2023-03-16T15:50:04.958","sender":"connection_failed","client_ip":"10.128.4.1","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"read tcp 10.128.5.44:2022->10.128.4.1:53811: read: connection reset by peer"}
{"level":"debug","time":"2023-03-16T15:50:05.334","sender":"SFTP","connection_id":"SFTP_2fc4a2221825a498581504b129ebc82c337827a7da77a8dd6c397d8d504d3913_1","message":"transfer added, id: 6, active transfers: 1"}
{"level":"debug","time":"2023-03-16T15:50:05.371","sender":"SFTP","connection_id":"SFTP_429eb084919e0918f1c5d9874c0a2ef00042f24c06430001fc30fafb84d1962a_1","message":"transfer added, id: 7, active transfers: 1"}
{"level":"info","time":"2023-03-16T15:50:05.373","sender":"Download","local_addr":"10.128.5.44:2022","remote_addr":"10.128.4.

When I manually try to connect I receive the following

kex_exchange_identification: Connection closed by remote host
Connection closed by 10.78.25.10 port 30222
Connection closed

is there a way to overcome this situation?
Thank you

**Comment by drakkan** [comment]
closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
