### ISSUE TITLE
Cannot add new users or edit existing following upgrade to v2.4.4

### ISSUE THREAD

**Issue by stuartluscombe** [drakkan/sftpgo#1242]
About a year ago our HA instance of SFTPGo on a K8s cluster upgraded to 2.2.3 after a pod failure. This was fine, and wasn't a problem for our users, apart from a financial institution which required we have SHA1-based KEX enabled.

To quickly resolve the issue, I downgraded at that time to 2.1.2 while I worked on using the environment variables to enable those KEX algorithms that were needed. The plan was then to upgrade back to 2.2.3 and onwards from there.

That short-term plan ended up getting pushed back until now, where we found that we couldn't add new accounts on account of the upgraded DB schema, so I set up a test K8s cluster and set up a replica of our setup (installed 2.1.2, upgraded to 2.2.3, then downgraded to 2.1.2).

I was able to run a 2-step upgrade from 2.1.2 to 2.3 and 2.3 to 2.4.4 without any problems and have also pushed this to our production cluster. Connections to the server are working fine, but when logging into the WebUI as an admin I'm unable to add or edit any accounts. I get a table of the accounts, but no buttons to add/update anything.

**Comment by drakkan** [comment]
I'm sorry but I no longer provide step-by-step support (as you received in the past) for free. Please check the [support policy](https://github.com/drakkan/sftpgo#support-policy).

I think this question has been asked at least 2-3 times in the past, you can find the answer in the closed issues.

**Comment by stuartluscombe** [comment]
No problem. For info, I tried it from another machine and the issue wasn't present, so I tried a couple of things and found it was just a browser caching issue.
