### ISSUE TITLE
Unable to find curl in latest and plugins docker images

### ISSUE THREAD

**Issue by MarsWarrior** [drakkan/sftpgo#1245]
I did test both the latest and plugins labels (the last one does contain the plugins), but I can't seem to use the "curl" command in actions because it is not included.

If I look at the dockerfile, curl should be there if plugins are enabled.

Either I do something wrong, or the docker image is missing something!

I can install curl as a new package, but this one is gone of course after recreation of the container.

```shell
root@bc8d64ee8c48:/var/lib/sftpgo# apt install curl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcurl4
The following NEW packages will be installed:
  curl libcurl4
0 upgraded, 2 newly installed, 0 to remove and 6 not upgraded.
Need to get 617 kB of archives.
After this operation, 1198 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://deb.debian.org/debian-security bullseye-security/main amd64 libcurl4 amd64 7.74.0-1.3+deb11u7 [346 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security/main amd64 curl amd64 7.74.0-1.3+deb11u7 [270 kB]
Fetched 617 kB in 0s (12.0 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libcurl4:amd64.
(Reading database ... 10124 files and directories currently installed.)
Preparing to unpack .../libcurl4_7.74.0-1.3+deb11u7_amd64.deb ...
Unpacking libcurl4:amd64 (7.74.0-1.3+deb11u7) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_7.74.0-1.3+deb11u7_amd64.deb ...
Unpacking curl (7.74.0-1.3+deb11u7) ...
Setting up libcurl4:amd64 (7.74.0-1.3+deb11u7) ...
Setting up curl (7.74.0-1.3+deb11u7) ...
Processing triggers for libc-bin (2.31-13+deb11u5) ...
root@bc8d64ee8c48:/var/lib/sftpgo# 

```

**Comment by drakkan** [comment]
Hello, curl is not installed in any docker image sorry. Consider building your own image using the official one as base. Thank you

**Comment by MarsWarrior** [comment]
> Hello, curl is not installed in any docker image sorry. Consider building your own image using the official one as base. Thank you

Ok. As I need curl to notify Gotify, I will use your Dockerfile to build my own image!

Thanx for the fast reply.

**Comment by drakkan** [comment]
I think you can use an HTTP action instead of starting an external command. However, use the method that you think is most appropriate for your use case

**Comment by MarsWarrior** [comment]
Ah. Good idea. I will check that option too!
