### ISSUE TITLE
External Auth - user settings

### ISSUE THREAD

**Issue by chrgraefe** [drakkan/sftpgo#1246]
We implemented an external authentication service. The service respondes with an empty HTTP 200 status code.
The login via web interface fails with invalid credential.

excerpt from the sftogo.log
`{"level":"debug","time":"2023-03-24T15:12:20.386","sender":"dataprovider_sqlite","message":"external auth hook executed, response code: 200"}
{"level":"debug","time":"2023-03-24T15:12:20.387","sender":"dataprovider_sqlite","message":"external auth completed for user \"Username\", elapsed: 49.1774ms"}
{"level":"debug","time":"2023-03-24T15:12:20.387","sender":"dataprovider_sqlite","message":"empty response from external hook, no modification requested for user \"Username\" id: 4"}
{"level":"debug","time":"2023-03-24T15:12:20.387","sender":"connection_failed","client_ip":"10.x.x.x","username":"Username","login_type":"password","protocol":"HTTP","error":"credentials cannot be null or empty"}
{"level":"info","time":"2023-03-24T15:12:20.387","sender":"httpd","local_addr":"10.x.x.x:80","method":"POST","proto":"HTTP/1.1","remote_addr":"10.x.x.x:64129","request_id":"SERVER/rzKfgjJ74S-000054","uri":"http://server01.com/web/client/login","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","resp_status":200,"resp_size":5932,"elapsed_ms":51}
{"level":"debug","time":"2023-03-24T15:12:21.749","sender":"service","message":"Received service interrogate request, current status: {4 141 0 0 0 0 0}"}
{"level":"debug","time":"2023-03-24T15:12:21.749","sender":"service","message":"Received service interrogate request, current status: {4 141 0 0 0 0 0}"}`

**Comment by drakkan** [comment]
Hello, 

the logs seem clear enough but I would probably need a little more context to help.
However I no longer provide free support, sorry. Please check the [support policy](https://github.com/drakkan/sftpgo#support-policy). Thank you
