### ISSUE TITLE
[Feature Request] s3 home directory config over API

### ISSUE THREAD

**Issue by 12nick12** [drakkan/sftpgo#1247]
Hey, thanks for the awesome program, but I would love the ability to be able to configure S3 based home directories over the API (I'm using external auth and would like to use S3 for the users home dir).

**Comment by 12nick12** [comment]
It is not supported over the external auth/API. According to the docs and testing a string is required, but when providing the config that should work for S3 it doesn't work. I just started sponsoring you. 

```
"home_dir":
  {
    "provider": 1,
    "s3config": {
      "bucket": "bucket_name",
      "key_prefix": "home/username/",
      "region": "us-east-2"
    }
   },
```


The error it returns is `json: cannot unmarshal object into Go struct field User.home_dir of type string`

**Comment by drakkan** [comment]
> It is not supported over the external auth/API. According to the docs and testing a string is required, but when providing the config that should work for S3 it doesn't work. I just started sponsoring you.
> 
> ```
> "home_dir":
>   {
>     "provider": 1,
>     "s3config": {
>       "bucket": "bucket_name",
>       "key_prefix": "home/username/",
>       "region": "us-east-2"
>     }
>    },
> ```
> 
> The error it returns is `json: cannot unmarshal object into Go struct field User.home_dir of type string`

That's wrong check the [OpenAPI specs](https://sftpgo.stoplight.io/docs/sftpgo/d9755a1cfd67c-add-user)

```
....
"filesystem": {
   "provider": 1,
    "s3config": {
      "bucket": "bucket_name",
      "key_prefix": "home/username/",
      "region": "us-east-2"
    }
   },
....
```

**Comment by 12nick12** [comment]
OK, thank you. So this should work correct? I'm still getting the same error. 

```
  "home_dir": {
    "filesystem": {
      "provider": 1,
        "s3config": {
          "bucket": "bucket_name",
          "key_prefix": "home/username/",
          "region": "us-east-2"
      }
    }
  },
```

**Comment by drakkan** [comment]
home_dir is a string, filesystem is a struct. If you open the link in the previous comment there is an example

```
"home_dir":"....",
"filesystem": {
      "provider": 1,
        "s3config": {
          "bucket": "bucket_name",
          "key_prefix": "home/username/",
          "region": "us-east-2"
      }
    }
```

**Comment by 12nick12** [comment]
OK, so how would I use a struct for the home directory since it's looking for a string?

**Comment by 12nick12** [comment]
I got it. Thanks. I just don't need to provide the home_dir. 

Sorry for the confusion. Thank you for the awesome software
