### ISSUE TITLE
Setting up diffie-hellman-group-exchange-sha256 support

### ISSUE THREAD

**Issue by gabriel-envoi** [drakkan/sftpgo#1248]
Hello! I need to support this Key Exchange Algorithm and in the documentation it says that I need to populate the "moduli" property in `sftpgo.json`. So I tried to generate the .pem file using several different approaches, one of which would be `openssl dhparam -out dhparam.pem 2048`. Then I added the path to the moduli and expected it to work, however in the logs I get:  `"{ message":"could not start SFTP server: ssh: invalid contents for module file \"/etc/sftpgo/dhparam.pem\", unexpeted number of parts: 4"}`. Any suggestions on how to solve this?

**Comment by gabriel-envoi** [comment]
I could have just used the default moduli file.

**Comment by JarnoRFB** [comment]
What is the path to the default moduli file? Is it included in the Docker container? I am trying to activate `diffie-hellman-group1-sha1` but just adding it in SFTPGO_SFTPD__KEX_ALGORITHMS does not seem to work.
