### ISSUE TITLE
Username in response from external auth

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#125]
https://github.com/drakkan/sftpgo/blob/e3761afe0cdbdb68fba06003cb8203a6d6ad2a71/dataprovider/dataprovider.go#L1473-L1515

I was wondering ,what's the actualy purpose of having "username" field in response from external auth? It absolutely must be the same as the username that the user provided during the login, otherwise we will get to "xxx does not exist".
As we can see from the snippet, the script will check, if user exists by using the user provided username, but then act further by using the username provided by the external auth response. If they don't match, we will run in problems.

So it should be either that
a) script uses username from the external auth response, that way we can actually have multiple login names that all refer to the same user account; or
b) remove "username" from the response, and use the username provided by the user during login

Or best of the both worlds:
c) If "username" is in external auth response AND is not empty, do a), if "username" is missing from the response, do b), and if "username" is in response AND is empty, that means that credentials are invalid (as it works currently, so it's completely backwards compatible).

**Comment by drakkan** [comment]
Hi,

the username in the ext auth response is used to check if the auth is OK or not, omitting the username is the same as setting an empty username and so the auth will fail. I probably have to check that the username in the response is the same as the username used to login and fail the auth in this case too

**Comment by sergiz** [comment]
Yeah, but why is it simply not a true/false check? Like `'{"success":true,"status":1,...}'` / `'{"success":false}'`

**Comment by drakkan** [comment]
> Yeah, but why is it simply not a true/false check? Like `'{"success":true,"status":1,...}'` / `'{"success":false}'`

because the response is used to create an `User` instance for the connection, so we need a serialized user struct in the response. For example in the response you can set a denied ip and it will be checked in the same way as for built-in users.

**Comment by sergiz** [comment]
But you already have the username from login form? And returned username from external auth MUST be the same as that one since the code is inconsistent:
```
u, err := provider.userExists(username)
...
err = provider.updateUser(user) OR err = provider.addUser(user) // user.Username
...
return provider.userExists(username) 
```

As I wrote in the OP, it's redundant to send username back and forth since it must match anyway. If it doesn't match it won't work as you will be creating/updating one user, while wanting to return another, so it is eventually a boolean (does it match or not?).

> a) script uses username from the external auth response, that way we can actually have multiple login names that all refer to the same user account; or
```
u, err := provider.userExists(user.Username)
...
err = provider.updateUser(user) OR err = provider.addUser(user)
...
return provider.userExists(user.Username) 
```

> b) remove "username" from the response, and use the username provided by the user during login
```
u, err := provider.userExists(username)
...
// set user.Username to username
err = provider.updateUser(user) OR err = provider.addUser(user)
...
return provider.userExists(username) 
```

> c) If "username" is in external auth response AND is not empty, do a), if "username" is missing from the response, do b), and if "username" is in response AND is empty, that means that credentials are invalid (as it works currently, so it's completely backwards compatible).

**Comment by drakkan** [comment]
The code implictly assumes that the returned username is the same as the one used for the login but don't check it, I think I have to change this line:

https://github.com/drakkan/sftpgo/blob/master/dataprovider/dataprovider.go#L1491 

to something like this:

```
if len(user.Username) == 0 || user.Username != username {
    return user, errors.New("Invalid credentials")
}
```

We could also add an explicit boolean check, as you suggest, instead of the username but in this case we need:

1) write several test cases to ensure to not break backward compatibility
2) we cannot directly deserialize the response to a `User` [struct](https://github.com/drakkan/sftpgo/blob/master/dataprovider/dataprovider.go#L1487) but we need to extend the `User` struct to add the check field

**Comment by sergiz** [comment]
> to something like this:
> 
> if len(user.Username) == 0 || user.Username != username {
>     return user, errors.New("Invalid credentials")
> }
> 
> or:
> 
> if user.Username != username {
>     return user, errors.New("Invalid credentials")
> }

Hmm, but this doesn't really change anything, you would still need to return username on every response manually. The only change would be that it wouldn't error out, if there was no match.

Thanks to your replies, I understand the situation better now. I think that the cleanest solution with minimal changes would actually be a)
https://github.com/drakkan/sftpgo/blob/dc011af90d5e2614b039daabff4e97dd16656ce6/dataprovider/dataprovider.go#L1500
https://github.com/drakkan/sftpgo/blob/dc011af90d5e2614b039daabff4e97dd16656ce6/dataprovider/dataprovider.go#L1514
Change "username" var to "user.Username" on these two lines and this issue is solved.

This also offers us maximum flexibility, and follows the original idea that you had (that we return complete serialized user).

Additional bonus is also, that we can have multiple login usernames per one SFTPGo account):
User can login with "account1" or "account2" as username, and if our external auth returns "account" as "username", the same user account will be used both times.

**Comment by sergiz** [comment]
Thanks to your replies, I understand the situation better now. I think that the cleanest solution with minimal changes would actually be a)
https://github.com/drakkan/sftpgo/blob/dc011af90d5e2614b039daabff4e97dd16656ce6/dataprovider/dataprovider.go#L1500
https://github.com/drakkan/sftpgo/blob/dc011af90d5e2614b039daabff4e97dd16656ce6/dataprovider/dataprovider.go#L1514
Change "username" var to "user.Username" on these two lines and this issue is solved.

This also offers us maximum flexibility, and follows the original idea that you had (that we return complete serialized user).

Additional bonus is also, that we can have multiple login usernames per one SFTPGo account):
User can login with "account1" or "account2" as username, and if our external auth returns "account" as "username", the same user account will be used both times.

**Comment by drakkan** [comment]
well, if this is useful for your use case it could be accepted since it should not break backward compatibility and it still allows the more standard use case where the username is the same. 

Do you want to send a pull request? I could check it the next weekend or as soon as I find some free time to do some more tests. Thanks!

**Comment by sergiz** [comment]
Alright, will do tomorrow probably.
