### ISSUE TITLE
Defender problem

### ISSUE THREAD

**Issue by SC0TT0Ne** [drakkan/sftpgo#1250]
Hi, what should the blocklist look like, is there an example for this

ERR defender initialization error: unexpected end of JSON input

**Comment by drakkan** [comment]
You edited sftpgo.json and made it non-json compliant, this is one of the reasons why editing sftpgo.json directly is not recommened.

I no longer provide step-by-step support, sorry. Please check the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by SC0TT0Ne** [comment]
It's a pity that there is no documentation. 
Bad!

**Comment by drakkan** [comment]
Please be polite. It is all documented. There is also an example
