### ISSUE TITLE
unknown pflags error creating file

### ISSUE THREAD

**Issue by ajaykumar-gbi** [drakkan/sftpgo#1251]
We are using kubernetes containers and time to time we get a weird error. I tried to search but did not find anything related to it:

```
error creating file "customer/files/filename.json", os flags 577, pflags {Read:false Write:true Append:false Creat:true Trunc:true Excl:false}: open /srv/sftpgo/data/customer/pipefile1805439284: no such file or directory
```

We are not sure why this is looking for `pipefile1805439284`. We are neither uploading this file not downloading it. This does not even exists.

**Comment by drakkan** [comment]
It looks like an old bug, however, as you know, I no longer provide free step-by-step support and troubleshooting, sorry. Good luck
