### ISSUE TITLE
Debian initprovider connection refused on Postgres

### ISSUE THREAD

**Issue by babdulkarim** [drakkan/sftpgo#126]
I'm using sftpgo via Docker on Debian. I have created a database called db on my server, which I reference in sftpgo.json under the name field. After running the initprovider command, it results in the following message:

```
2020-05-31T23:17:18.000 DBG Initializing provider: "postgresql" config file: "/app/config/sftpgo.json"
2020-05-31T23:17:18.000 WRN Unable to initialize data provider: dial tcp :5432: connect: connection refused
```

**Comment by drakkan** [comment]
Hi,

please check the `host` configuration directive inside your configuration file, the posted error means that there is no running postgresql instance on the configured `host` (or it is not accessibile from your Docker)

**Comment by babdulkarim** [comment]
I do have a postgresql instance running. Furthermore, I configured the fields for driver ("postgresql"), name ("db" the database I manually created), host (tried both "localhost" and "127.0.0.1"), port ("5432"), and the username/password that I created for db on /srv//sftpgo/config/sftpgo.json . I still receive that error.

**Comment by drakkan** [comment]
Hi,

I just did a quick test myself.

I have postgres running on host 192.168.1.50 and Docker on different machine (192.168.1.12). 
I created the database `sftpgo_test` inside postgres and configured sftpgo appropriately, here is the relevant configuration inside `sftpgo.json`:

```
"data_provider": {
    "driver": "postgresql",
    "name": "sftpgo_test",
    "host": "192.168.1.50",
    "port": 5432,
    "username": "postgres",
    "password": "postgres",
    "sslmode": 0,
....
```

then the provider initialization worked fine:

```
docker run --name sftpgo_debian -p 8080:8080 -p 2022:2022 --mount type=bind,source=/home/nicola/sftpgo/data,target=/app/data --mount type=bind,source=/home/nicola/sftpgo/config,target=/app/config --mount type=bind,source=/home/nicola/sftpgo/backups,target=/app/backups drakkan/sftpgo initprovider -c /app/config
2020-06-05T09:06:19.000 DBG Initializing provider: "postgresql" config file: "/app/config/sftpgo.json"
2020-06-05T09:06:19.000 DBG Data provider successfully initialized
```

and the Docker instance started with no issue, here are some relevant logs:

```
{"level":"info","time":"2020-06-05T09:10:15.279","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.6-dev-ad53429-2020-05-23T10:15:36Z -gcs +s3 +bolt +mysql +pgsql +sqlite -portable, config dir: /app/config, config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, profile: false"}
{"level":"debug","time":"2020-06-05T09:10:15.306","sender":"config","connection_id":"","message":"config file used: '\"/app/config/sftpgo.json\"', config loaded: {SFTPD:{Banner:SFTPGo_0.9.6-dev BindPort:2022 BindAddress: IdleTimeout:15 MaxAuthTries:10 Umask:0022 UploadMode:0 Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} Keys:[] HostKeys:[] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd git-receive-pack git-upload-pack git-upload-archive scp] KeyboardInteractiveProgram: KeyboardInteractiveHook: ProxyProtocol:0 ProxyAllowed:[] certChecker:<nil> parsedUserCAKeys:[]} ProviderConf:{Driver:postgresql Name:sftpgo_test Host:192.168.1.50 Port:5432 Username:postgres Password:[redacted] SSLMode:0 ConnectionString: UsersTable:users ManageUsers:1 TrackQuota:2 PoolSize:0 UsersBaseDir:/app/data Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} ExternalAuthProgram: ExternalAuthHook: ExternalAuthScope:0 CredentialsPath:credentials PreLoginProgram: PreLoginHook:} HTTPDConfig:{BindPort:8080 BindAddress: TemplatesPath:/app/web/templates StaticFilesPath:/app/web/static BackupsPath:/app/backups AuthUserFile: CertificateFile: CertificateKeyFile:} HTTPConfig:{Timeout:20 CACertificates:[] SkipTLSVerify:false customTransport:<nil>}}"}
{"level":"debug","time":"2020-06-05T09:10:15.306","sender":"dataprovider_postgresql","connection_id":"","message":"postgres database handle created, connection string: \"host='192.168.1.50' port=5432 dbname='sftpgo_test' user='postgres' password='[redacted]' sslmode=disable connect_timeout=10\", pool size: 0"}
{"level":"info","time":"2020-06-05T09:10:15.321","sender":"dataprovider_postgresql","connection_id":"","message":"updating database version: 1 -> 2"}
{"level":"info","time":"2020-06-05T09:10:15.346","sender":"dataprovider_postgresql","connection_id":"","message":"updating database version: 2 -> 3"}
....
```

so this seems an issue on your side. 

The error you posted clearly means that sftpgo is unable to connect to postgres instance on localhost, I'll try to indagate this issue. Please open a shell inside your Docker instance and manually verify the connection. Thanks

**Comment by babdulkarim** [comment]
Yes, you're right. I had to configure pg_hba.conf via this gist:

https://gist.github.com/MauricioMoraes/87d76577babd4e084cba70f63c04b07d

Apologies for wasting your time. 

May I ask how I can connect with my user? I created a user 'boogs' via the 8080 web server, but it didn't create the home dir for that user. So the docker logs says:

```
{"level":"debug","time":"2020-06-09T17:59:41.814","sender":"sftpd","connection_id":"","message":"idle connections check ticker 2020-06-09 17:59:41.814719594 +0000 UTC m=+5700.008796347"}
{"level":"debug","time":"2020-06-09T17:59:41.814","sender":"sftpd","connection_id":"","message":"check idle connections ended"}
{"level":"debug","time":"2020-06-09T18:01:39.119","sender":"osfs","connection_id":"35dd4cefcdf8986f8f1c4b2d2b43f3080764acf3e6d8319433ceea5195720b07","message":"root directory \"/app/data/boogs\" for user \"boogs\" does not exist, try to create, mkdir error: <nil>"}
{"level":"info","time":"2020-06-09T18:01:39.119","sender":"sftpd","connection_id":"35dd4cefcdf8986f8f1c4b2d2b43f3080764acf3e6d8319433ceea5195720b07","message":"User id: 1, logged in with: \"password\", username: \"boogs\", home_dir: \"/app/data/boogs\" remote addr: \"54.205.84.174:58166\""}
{"level":"debug","time":"2020-06-09T18:01:39.121","sender":"postgresql","connection_id":"","message":"last login updated for user \"boogs\""}
```

**Comment by drakkan** [comment]
> Yes, you're right. I had to configure pg_hba.conf via this gist:
> 
> https://gist.github.com/MauricioMoraes/87d76577babd4e084cba70f63c04b07d
> 
> Apologies for wasting your time.

no problem

> 
> May I ask how I can connect with my user? 

You can connect with any SFTP client

> I created a user 'boogs' via the 8080 web server, but it didn't create the home dir for that user. So the docker logs says:
> 
> ```
> {"level":"debug","time":"2020-06-09T17:59:41.814","sender":"sftpd","connection_id":"","message":"idle connections check ticker 2020-06-09 17:59:41.814719594 +0000 UTC m=+5700.008796347"}
> {"level":"debug","time":"2020-06-09T17:59:41.814","sender":"sftpd","connection_id":"","message":"check idle connections ended"}
> {"level":"debug","time":"2020-06-09T18:01:39.119","sender":"osfs","connection_id":"35dd4cefcdf8986f8f1c4b2d2b43f3080764acf3e6d8319433ceea5195720b07","message":"root directory \"/app/data/boogs\" for user \"boogs\" does not exist, try to create, mkdir error: <nil>"}
> {"level":"info","time":"2020-06-09T18:01:39.119","sender":"sftpd","connection_id":"35dd4cefcdf8986f8f1c4b2d2b43f3080764acf3e6d8319433ceea5195720b07","message":"User id: 1, logged in with: \"password\", username: \"boogs\", home_dir: \"/app/data/boogs\" remote addr: \"54.205.84.174:58166\""}
> {"level":"debug","time":"2020-06-09T18:01:39.121","sender":"postgresql","connection_id":"","message":"last login updated for user \"boogs\""}
> ```
> 

these logs refers to a successful login

```
mkdir error: <nil>
```

means that the home dir was created with no error and this log:

```
"User id: 1, logged in with: \"password\", username: \"boogs\", home_dir: \"/app/data/boogs\" remote addr: \"54.205.84.174:58166\"
```

means that the user `boogs` logged in with the `password` login method from the remote address `54.205.84.174`

You have configured SFTPGo successfully, congrats!

> Checking my container though, the home dir for that user does exist. By the way, i'm running this on aws ec2.
