### ISSUE TITLE
Telemetry by folder

### ISSUE THREAD

**Issue by alexsanderp** [drakkan/sftpgo#1261]
Any possibility to implement telemetry by folder?

I think it would be more interesting than by provider (s3, gcp...)

**Comment by drakkan** [comment]
Not sure to understand what you mean. If two or more users have a folder named `/folder` do you want to see number of uploads, downloads etc for this folder?

**Comment by coendaar** [comment]
Yes. Would be great to see amount of files per folder. Or available quota per folder/client.
For instance: we expect a 'client' to upload 100 files per day to a folder. Using prometheus we could monitor if the client is still working.

**Comment by drakkan** [comment]
I don't think it's possible, we should declare a prometheus counter for each folder and we don't know the folder names beforehand, do you know any other sw using prometheus like this?

**Comment by viniciusdsmello** [comment]
Hi @drakkan! I'm not a Go Developer, but looking into the code, I saw that perhaps we could use [sshDestPath](https://github.com/drakkan/sftpgo/blob/b524d178dd45d015ffb8bcee2a2a15a1c2b6a7e1/internal/sftpd/ssh_cmd.go#LL252C2-L252C13). The idea is to get the counts of uploaded files, quotas and other metrics by folder so we can track the different use cases we might have.

**Comment by viniciusdsmello** [comment]
I've found a thread on this https://groups.google.com/g/prometheus-users/c/yzJjrLGVeCw?pli=1

**Comment by coendaar** [comment]
I understand this is complicated. And due to the poor security for prometheus (the /metrics page has no authentication by default) it might be a security risk as well.
