### ISSUE TITLE
What does no_auth_tryed mean?

### ISSUE THREAD

**Issue by aleks-m** [drakkan/sftpgo#1265]
Hi.

With Defender enabled some of our (legitimate) clients are being banned periodically with the following error present in logs: 
```
{"client_ip":"XXX.XXX.XXX.XXX", "error":"EOF", "level":"debug", "login_type":"no_auth_tryed", "protocol":"SSH", "sender":"connection_failed", "username":""}
```
What does this "no_auth_tryed" message mean exactly? Is there a way to get more details on such connection failures?

We are trying to understand what is happening, they are using valid credentials, so should not be banned in theory...

Could please help?
Thanks.

**Comment by drakkan** [comment]
I'm sorry, I no longer provide free support, please check the [support policy](https://github.com/drakkan/sftpgo#support-policy). Hope you understand. Thank you

**Comment by aleks-m** [comment]
@drakkan we (https://github.com/nuorder)  are now a bronze sponsor, could you please reopen this issue?

**Comment by drakkan** [comment]
> @drakkan we (https://github.com/nuorder) are now a bronze sponsor, could you please reopen this issue?

@aleks-m thank you for supporting the project, much appreciated.
This log is generated if a client connects and the connection is closed without any authentication attempt.

As a bronze sponsor you also can write me directly to support at sftpgo dot com and, if you want, your company logo can be added [here](https://github.com/drakkan/sftpgo#thank-you-to-our-sponsors).
