### ISSUE TITLE
Publish `python` client to `pip` using `OpenAPI`

### ISSUE THREAD

**Issue by vnghia** [drakkan/sftpgo#1268]
Hello,

I would like to ask if you have thought about publish a `python` client to `pip`. That should be done quite easily since we already have https://github.com/OpenAPITools/openapi-generator. I can help you:
- Add a github action to publish the generated client to pip.
- Rewrite various scripts in this repo using the new client (for example: https://github.com/drakkan/sftpgo/blob/main/examples/backup/backup)

**Comment by drakkan** [comment]
Hello,

this generators seems to have some issues (probably fixed), see #1101. Have you tested the generator and can you confirm that it is now working?

Some python clients are already available (I haven't tested them):

https://pypi.org/project/sftpgo-client/
https://pypi.org/project/ant-sftpgo-client/

Please note that most of the python examples are obsolete, for example backup, data retention, quotascan can now be done using the EventManager. Probably the only useful python script is the one that import users from other stores.

I'm trying to minimize the maintenance burden, as you can read in other issues the project is currently not financially viable, as soon as I gain a new sponsor an old one stop sponsoring :cry: and I cannot continue to do all this work for free forever.

I would like to avoid having issues/questions for the auto-created python client as well, maybe it's better to publish it from an external repository and possibly merge it here when the future of the project is clearer/defined.

Not strictly related, I'm working on a [Terraform provider](https://github.com/drakkan/terraform-provider-sftpgo)

**Comment by vnghia** [comment]
I see. I think I will use an already working client. Thank you very much !

**Comment by ramnes** [comment]
Hey there, sftpgo-client author here, thanks for mentioning it Nicola! I'm not actively using sftpgo currently but I'm still always happy to help if you need anything related to the client @vnghia, e.g. bumping the client to the latest OpenAPI spec or answering questions.
