### ISSUE TITLE
sftpgo portable Model support multi disk?

### ISSUE THREAD

**Issue by djerrystyle** [drakkan/sftpgo#127]
`sftpgo.exe portable  --directory C:\  --directory D:\`
just run for D:\ , but if need to run for C and D disk , how to set command option, thanks

**Comment by drakkan** [comment]
Hi,

portable mode allows to serve a single directory on demand.

If you need to serve both `C` and `D` disk you can:

1) run sftpgo in portable mode multiple times, for example `sftpgo.exe portable --directory C:\` and `sftpgo.exe portable --directory D:\` in a separate shell
2) switch to the standard (non portable) mode and run sftpgo as service
3) switch to the standard mode and run sftpgo on demand using `sftpgo.exe serve`

Using the standard mode you can define a user for the `C` drive and another one for the `D` drive or you can create a single user and set `C:\` as home dir and map `D:\` as virtual path

**Comment by djerrystyle** [comment]
thank you!
