### ISSUE TITLE
Unable to update via PPA

### ISSUE THREAD

**Issue by Lungshot** [drakkan/sftpgo#1270]
I have version 2.2.2 installed via the PPA and would like to update to the latest, 2.4.5.
When I update directly to 2.4.5 from 2.2.2 (the default for "apt update sftpgo") it obviously does not follow the upgrade path outlined in the docs, and the sqlite database schema version 15 is too old. I am unable to specify package version numbers manually and update from 2.2.2 to 2.2.3 and so on, because the older version numbers are not available on the PPA.
Is there a repo out there besides the launchpad repo that has the older builds so I can update?
Thanks!

**Comment by drakkan** [comment]
Hello, download and manually install a deb from the release page
