### ISSUE TITLE
Feature request: Authentication Banner

### ISSUE THREAD

**Issue by d-j-a** [drakkan/sftpgo#1278]
Could we have the option to add an authentication banner? This would be super helpful—an example is attached from WinSCP and another sFTP server.   Maybe it could even be set per user?  Apologies if this exists and I missed it! :)

![image](https://user-images.githubusercontent.com/10190674/235721726-fd07bd4a-5fbe-41ec-9156-3b639a601809.png)

**Comment by drakkan** [comment]
Hello, this is already supported check `login_banner_file` and `banner_file` in the [docs](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md). The banner is sent before the user authenticate  so it cannot be customized per-user

**Comment by d-j-a** [comment]
Awesome, thanks! Sorry to waste your time; I clearly missed that.

**Comment by d-j-a** [comment]
Is there a guide on how to set this? It looks like I need to adjust full-configuration.md, but I can't seem to find that in the console for my docker?

**Comment by d-j-a** [comment]
@drakkan , I found the sftpgo.json file in etc/sftpgo but I cannot edit it (no vi or vim) and I can copy an edited file into the location because I'm not root and su or sudu su doesn't work. (I don't know su password, and the one I set doesn't for for admin) 

How exactly do I edit the file and/or get root?
