### ISSUE TITLE
Unspecific error using S3 compatible file system

### ISSUE THREAD

**Issue by antoinebourayne** [drakkan/sftpgo#1280]
I am trying to make a connection to a S3 compatible bucket (Scaleway). When i try to make a command logged as a user via sftp, i get this error :

{"level":"error","time":"2023-05-03T14:46:59.333","sender":"SFTP","connection_id":"SFTP_XXXXXX","message":"generic error: operation error S3: ListObjectsV2, https response error StatusCode: 400, RequestID: txXXXXXXX, HostID: txXXXXXXX, api error BadRequest: Invalid token."}

This is my configuration :

-bucket name : mybucket
-region : fr-par
-access key : XXXX
-access secret : XXXX
-storage class : STANDARD 
-endpoint : https://s3.fr-par.scw.cloud/
-home dir : /

Is there a way to have further information on how the s3 api is used ? The logs are not detailed enough to debug this unfortunately...

**Comment by drakkan** [comment]
Hello,

this is the error returned from Scaleway. If you want to use SFTPGo for free you have no support, so you have to debug/fix errors like this yourself. I no longer provide free support, sorry. Thanks for understanding

**Comment by MaximBalaganskiy** [comment]
@antoinebourayne try removing STANDARD, I had 'unsupported protocol scheme' until I removed it

**Comment by antoinebourayne** [comment]
Hi guys thanks for your answers, my problem came from a specificity of my cloud provider

**Comment by drakkan** [comment]
I think this is solved now
