### ISSUE TITLE
Support less-featureful deployments

### ISSUE THREAD

**Issue by solacelost** [drakkan/sftpgo#1287]
## Description

SFTPGo is pretty cool. There are some features of it that I'm _really_ interested in, but because it's designed pretty expressly to host SFTP instances with some alternative access protocols and  full user management backed by arbitrary storage, I'm having some struggles applying it to my use case. I'm going to try to work around them myself with some automation, but what I'd really like is a strange blend of what's configurable today and what's available from portable mode, along with some other stuff. My use case is kind of strange and not really considered by your project, but your project is the best I've found for it yet.

## My infrastructure

I have a Kubernetes cluster on which I have deployed [Rook](https://rook.io/) and configured an Object Pool that uses [Ceph](https://ceph.io/) [RGW](https://docs.ceph.com/en/quincy/radosgw/index.html) to expose an S3-compatible API in response to the [ObjectBucketClaim object](https://rook.io/docs/rook/v1.11/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-notifications/?h=objectbucketclaim#obc-custom-resource). This lets me use [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) to declaratively define intent for an S3 bucket in Git, and have it created with credentials and connection information delivered into a Kubernetes Namespace for consumption by some workload - and clean the bucket up through the same kinds of interactions (remove the OBC in Git, the bucket is deleted and data is removed).

I have some users of ephemeral applications on my cluster than use buckets stood up for a short period of time, have the application work with that bucket, then my users retrieve the data from S3 for use locally, or with some other application. I currently provide the users with S3 credentials and let them pull it down via something like [s3cmd](https://s3tools.org/s3cmd) or integrate with whatever other application is expecting the data.

I have an OIDC provider and I've got the capability to deploy OAuth proxies alongside my web-based applications to enforce authn/authz when accessing those applications, with RBAC defined via the Kubernetes cluster itself.

## My ask

I'd like to use my existing RBAC/OAuth configurations to provide sign-in-less access to a web UI that provides easy exploration and download of resources backed by an S3 bucket without any additional auth or configuration beyond CLI parameters, a configuration file, or environment variables. That is, if SFTPGo supported this, it would completely address my use case:

- No sign in at all - client or admin. Anonymous FTP/SFTP/WebDAV are not a concern, but the web UI (which is very good!) supporting landing _directly_ at a web client for browsing a preconfigured storage backend
- S3 storage backend configurable via CLI, environment, or config file as a default for unauthenticated users as above

Note that if portable mode supported hosting the web UI without auth, it would meet my expectations right now since I _can_ provide an S3 backend for it.

## Things I considered instead of asking for this

Using portable mode, which wasn't designed for this but rather for SFTP hosting arbitrary directories on the fly. It's pretty close to what I want, I would just like a simplified version of the client web UI instead of SFTP. I couldn't find a way to force portable mode to accept any configuration overrides beyond the CLI parameters provided.

Doing some configuration via the API or CLI to get the initial users set up and then configure my Ingress to provide the necessary headers to just drop someone at the web client. I gave up due to the complexity of digging into some poorly documented parts of SFTPGo. I'm probably going to have to dig more into the Swagger docs and try to get something working here.

Setting up a full instance, dumping the data provider, loading ephemeral SFTPGo instances with this pre-built configuration and Ingress set up to bypass auth using that data. Will have to figure out a way to dynamically change the bucket configuration and authn as I load the pre-built configuration per instance. I'm considering this a bail-out from the above.

Just using something that's purpose-built to host a thin web UI for browsing S3 buckets. First off, the pickings are slim. Second, SFTPGo's web UI is much nicer and more responsive at the same time.

**Comment by drakkan** [comment]
Hello,

I think you can already do most of all you need if you use the [OpenID connect support](https://github.com/drakkan/sftpgo/blob/main/docs/oidc.md) integrated in SFTPGo and the EventManager to create/update users after login. 
To have the same using an external OpenID provider we should support something like a `REMOTE_USER` header the main difference is that OpenID connect provides a way to get additional fields useful for creating/updating user a `REMOTE_USER` header can only send the username for the authenticated user. 
Using the portable mode means you have to start (and then terminate) a new process each time.

However, this is not a development that can happen for free. Even reviewing a PR takes work and once a PR is merged, I have to maintain the new feature, fix bugs, etc.

If you're really interested, please consider sponsoring or purchasing a support plan. Thank you
