### ISSUE TITLE
Cant apply ACL on home dir

### ISSUE THREAD

**Issue by Izanatos** [drakkan/sftpgo#1289]
Hi,

I have a hierarchy for each user with an upload and download folder.

I've setup ACLs so that the download folder is read only and the upload is write and list.

Now I've tried to apply an ACL to limit access to the home directory  to read and list only but it doesn't seems to work.

I guess this could be done using filesystwm access rights but could we had the option to add / to the home dir ?

**Comment by drakkan** [comment]
Hello,

not sure to understand your question. SFTPGo uses virtual permissions, no need for filesystem level ACL, just set the required permission from the WebAdmin UI. Please also check the [support policy](https://github.com/drakkan/sftpgo#support-policy). Thank you

**Comment by Izanatos** [comment]
I think that was my point I am able to apply acl on the download and upload folder but ACL on root(home dir) doesn't  work.  I am trying to remove any write rights in the root.

**Comment by drakkan** [comment]
I'm sorry but I no longer provide step-by-step support, please check the [support policy](https://github.com/drakkan/sftpgo#support-policy). I hope that you understand my reasons. Thank you
