### ISSUE TITLE
Tag versions more frequently

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#129]
I suggest that you tag versions frequently. Every new feature should be minor version increase (0.y.0) and every fix should be patch version increase (0.y.z) (if you follow semver).

Current version is months old already and I guess it's in everyone's interest to get as many users as possible to newer versions, so they are real-life tested. It's also not really user friendly to force users to compile from source to be able to use the latest features.

**Comment by drakkan** [comment]
Hi,

making a new release requires some effort on my side, currently I don't have enough free time to increase the release frequency.

I think a continuous delivery system could help here, something integrated with Travis or a GitHub action or similar that builds the new version after each commit and allows to download the build artifact.

This is a low priority task for me a pull request is appreciated, thanks!

**Comment by drakkan** [comment]
with this [commit](https://github.com/drakkan/sftpgo/commit/403b9a831078682b2e6f67225580208f1457e54f) we now build binaries for Linux,macOS and Windows after each commit, build artifact can be downloaded here:

https://github.com/drakkan/sftpgo/actions/runs/142056806

**Comment by sergiz** [comment]
Perfect. Now that this is automated, I hope you will also tag releases.
