### ISSUE TITLE
Phasing out Docker Distroless variant

### ISSUE THREAD

**Issue by drakkan** [drakkan/sftpgo#1295]
Hello,

since Docker Distroless variant is useful to a limit group of users, we decided to phase it out. 
This step aims to streamline maintenance and expedite the development of new features. Consequently, the Distroless variant will be removed from our public repo in the near future and therefore will no longer receive updates on Docker Hub and GitHub Container Registry. 

If you still require the Distroless variant, please inform us at support at sftpgo dot com. We can consider offering this variant under our new support plans, details of which can be found at https://www.sftpgo.com#pricing. Thank you

**Comment by dlehammer** [comment]
Hi @drakkan,

Which image is the recommended substitue, perhaps [alpine-slim](https://hub.docker.com/layers/drakkan/sftpgo/alpine-slim/images/sha256-c8871561f0f0a22c957cfa990d7ccd2bcf642d855d5ae9e124f6dcc8455a540d?context=explore), when migrating from [distroless-slim](https://hub.docker.com/layers/drakkan/sftpgo/distroless-slim/images/sha256-2ecc9255d5dc25de3057e2f4aad5c0f2ca2f6e2440803bebde77974a883df3cc?context=explore) **?**

( I was utilizing that image privately on a Pi, chosen based on the assumed limited attack surface and small size 🤓 )

**Comment by drakkan** [comment]
> Hi @drakkan,
> 
> Which image is the recommended substitute, perhaps [alpine-slim](https://hub.docker.com/layers/drakkan/sftpgo/alpine-slim/images/sha256-c8871561f0f0a22c957cfa990d7ccd2bcf642d855d5ae9e124f6dcc8455a540d?context=explore), when migrating from [distroless-slim](https://hub.docker.com/layers/drakkan/sftpgo/distroless-slim/images/sha256-2ecc9255d5dc25de3057e2f4aad5c0f2ca2f6e2440803bebde77974a883df3cc?context=explore) **?**
> 
> EDIT: The reason I'm asking; is when I attempted to migrate from: [v2.5.1-distroless-slim](https://hub.docker.com/layers/drakkan/sftpgo/v2.5.1-distroless-slim/images/sha256-2ecc9255d5dc25de3057e2f4aad5c0f2ca2f6e2440803bebde77974a883df3cc?context=explore) to: [v2.5.2-alpine-slim](https://hub.docker.com/layers/drakkan/sftpgo/v2.5.2-alpine-slim/images/sha256-c8871561f0f0a22c957cfa990d7ccd2bcf642d855d5ae9e124f6dcc8455a540d?context=explore) the result was an endless restart loop:
> 
> ```
> 2023-06-18T21:19:35.981 WRN Unable to initialize data provider: file is not a database
> 2023-06-18T21:19:35.981 ERR error initializing data provider: file is not a database
> 2023-06-18T21:19:49.622 INF creating initial database schema, version 23
> 2023-06-18T21:19:49.625 WRN Unable to initialize data provider: file is not a database
> 2023-06-18T21:19:49.625 ERR error initializing data provider: file is not a database
> ```
> 
> My docker-compose is unchanged, besides the `image` reference, in the above scenario. I've rolled back until I have time to analyse why the alpine-slim image isn't compatible with the distroless-slim.
> 
> ( I was utilizing that image privately on a Pi, chosen based on the assumed limited attack surface and small size nerd_face )

alpine-slim is the closer alternative. The distroless image used bolt as data provider (because sftpgo was compiled statically), other variants use sqlite by default. You have to set the data provider to bolt to reuse the existing database

**Comment by dlehammer** [comment]
Hi @drakkan,

Thanks for taking the time to reply.

I've done a bit of digging, my changes are inspired by [this](https://github.com/drakkan/sftpgo/issues/229#issuecomment-733004052) suggestion pointing towards the bolt [test-setup](https://github.com/drakkan/sftpgo/blob/66f360e66cf40d5ce142e9b37a63eb25d378c5f1/.github/workflows/development.yml#L103).

The below changes to my docker-compose allowed me to migrate successfully:
```
     environment:
+      SFTPGO_DATA_PROVIDER__DRIVER: 'bolt'
+      SFTPGO_DATA_PROVIDER__NAME: 'sftpgo.db'
```

```
-    image: 'drakkan/sftpgo:v2.5.1-distroless-slim'
+    image: 'drakkan/sftpgo:v2.5.2-alpine-slim'
```
:nerd_face:
