### ISSUE TITLE
proxyproto: proxy protocol signature not present

### ISSUE THREAD

**Issue by Syer10** [drakkan/sftpgo#1296]
Ever since I updated to 2.5.0 I have not been able to connect using FTP.

My setup uses SFTPGO behind Traefik, and while it worked fine previously, it doesnt seem to work now. Here is the relavent configuration
```
      # Proxy Protocol
      - "SFTPGO_COMMON__PROXY_PROTOCOL=2"
      - "SFTPGO_COMMON__PROXY_ALLOWED=192.168.90.0/24"

```

And here are some logs
```json
{"level":"info","time":"2023-05-20T03:14:18.746","sender":"httpd","local_addr":"192.168.90.16:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.90.254:47020","request_id":"sftp/xxxxxxxxx-000005","uri":"http://sftpgo.xxxxxxxx.xxx/favicon.ico","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0","resp_status":404,"resp_size":24,"elapsed_ms":0}
{"level":"debug","time":"2023-05-20T03:14:34.134","sender":"sftpd","message":"failed to accept an incoming connection from ip \"xx.xxx.xxx.xxx\": proxyproto: proxy protocol signature not present"}
{"level":"debug","time":"2023-05-20T03:14:34.134","sender":"connection_failed","client_ip":"xx.xxx.xxx.xxx","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"proxyproto: proxy protocol signature not present"}
```

**Comment by drakkan** [comment]
Hello,

Your write

> I have not been able to connect using FTP

but in the logs I see an SFTP connection.  They are different protocols and require different configurations on the Traefik side. 
You masked the client IP that is required to understand if this is a real bug report or a misconfiguration on your side.
I just tested the proxy protocol for SFTP using both nginx and haproxy and it works fine.
This looks like a support request and I don't provide free support any longer, sorry

**Comment by Syer10** [comment]
It was a misconfiguration on my side. It seems I had opened the port directly to sftpgo instead of routing it through Traefik. I'm not sure why it worked previously, but its working again after I was able to get it through traefik.
