### ISSUE TITLE
"Operation not permitted" in Openshift

### ISSUE THREAD

**Issue by karatekaneen** [drakkan/sftpgo#1301]
Thank you for an amazing project!

When upgrading our Openshift cluster we ran into an issue where we got "Operation not permitted" when trying to execute the binary. This is due to that all applications in Openshift are run with a random user ID and a random group by default. Unfortunately I was not allowed to set the user ID to 1000 because of some rule in Openshift but I was allowed to set the group to 1000.

Looking at the file in the docker image it currently looks like this:
```
-rwxr-xr-x 1 root root 40956616 May 20 17:20 sftpgo
```

Is this something that might be possible to add to the dockerfiles? I don't know it it's a best practice or not but the following workaround worked for us:

```docker
FROM drakkan/sftpgo:v2
USER root
RUN chgrp 1000 /usr/local/bin/sftpgo
USER 1000:1000
```

And after that the file now looks like this and works in Openshift:
```
-rwxr-xr-x 1 root sftpgo 40956616 May 20 17:20 sftpgo
```

**Comment by drakkan** [comment]
Hello, the binary is already executable by everyone. I guess the issue is related to #1263

**Comment by karatekaneen** [comment]
Looks like it could be the same issue, yes. Then I definitely don't understand why our workaround worked but that's a separate issue.

Thank you anyways!

**Comment by drakkan** [comment]
> Looks like it could be the same issue, yes. Then I definitely don't understand why our workaround worked but that's a separate issue.
> 
> Thank you anyways!

your workaround works because chgrp removed the capabilities
