### ISSUE TITLE
Running httpd without frontend

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#131]
You cannot run httpd without frontend stuff since sftpgo cannot start, if templates are missing. That eventually makes sftpgo less portable, since if you want to use API, you cannot only have binary somewhere, but also need to take all frontend stuff with you.

Would it be possible to instead of erroring out, if templates_path/static_files_path does not exist, to simply start sftpgo with frontend disabled (but leaving API operational)?

**Comment by jovandeginste** [comment]
@42wim
