### ISSUE TITLE
[Bug] [webui]: sorting by size only considers number, not the actual size

### ISSUE THREAD

**Issue by kzshantonu** [drakkan/sftpgo#1313]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

<img width="81" alt="image" src="https://github.com/drakkan/sftpgo/assets/7745374/969e93ff-92d0-41e9-aebd-c0cac3f25e12">

### Steps to reproduce

sort list by size 

### Expected behavior

smaller files to larger files, or larger files to smaller files

### SFTPGo version

2.5.1-5b4a1bda-2023-05-20T17:10:04Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite -unixcrypt +portable

### Data provider

sqlite

### Installation method

Community Deb package

### Configuration

UI bug, irrelevant

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by kzshantonu** [comment]
@drakkan thanks

**Comment by drakkan** [comment]
No problem, thanks for noticing
