### ISSUE TITLE
Alicloud oss storage anonymous support

### ISSUE THREAD

**Issue by zwmyxzs** [drakkan/sftpgo#1314]
### Is your feature request related to a problem? Please describe.

Dear Team,

I selected Storage is AWS S3, and input Bucket, AccessKey, AccessSecret and Endpoint, try access Alicloud oss, it is fine.

Now I have set up a bucket policy for this bucket. This allows anonymous access bucket. for example:

curl https://{bucketname}.oss-cn-hangzhou-internal.aliyuncs.com/xxx.zip it is fine.

I tried to modify S3 without AccessKey and AccessSecret, but sftpgo UI result: Failed to get directory listing: Unable to get directory contents.

Sftogo app log result: 
{"level":"debug","time":"2023-06-06T16:38:40.627","sender":"OIDC","connection_id":"OIDC_chvf12tt7obr8um14hgg","message":"error listing directory: operation error S3: ListObjectsV2, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded"}
{"level":"error","time":"2023-06-06T16:38:40.627","sender":"OIDC","connection_id":"OIDC_chvf12tt7obr8um14hgg","message":"generic error: operation error S3: ListObjectsV2, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded"}

Is it possible for us to support this anonymous access feature in the future?

Thank you.

### Describe the solution you'd like

Alicloud oss anonymous support

**Comment by drakkan** [comment]
Hello,

Not sure if that's possible. Please provide a snippet of code using the AWS SDK that demonstrates it can work. Thank you

**Comment by zwmyxzs** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies-vpc-endpoint.html

https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html

AK is not required for VPC or public network policies.

**Comment by lue30499** [comment]
@drakkan The link you provided has details on how to make an unsigned request for "Anonymous" connections.
Under the natively-supported-authschemes
