### ISSUE TITLE
Issues uploading a file On S3 Filesystem

### ISSUE THREAD

**Issue by botzill** [drakkan/sftpgo#1319]
- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I setup sftpgo on kubernetes using helm chart. I setup a user with a S3 filesystem, like this:

<img width="457" alt="Screenshot 2023-06-10 at 08 56 50" src="https://github.com/drakkan/sftpgo/assets/4686040/6192474e-9391-4332-b122-d60f14f2d764">

S3 Filesystem setup:

<img width="708" alt="Screenshot 2023-06-10 at 09 01 41" src="https://github.com/drakkan/sftpgo/assets/4686040/602982cf-3e4d-404c-8dca-4b54ac539006">

I did upload some files on S3 directly and this user see the files:

<img width="1489" alt="Screenshot 2023-06-10 at 08 59 33" src="https://github.com/drakkan/sftpgo/assets/4686040/f898b425-f4f7-404b-8502-3cc077494888">

But when I try to upload a new a new file it say:
<img width="1491" alt="Screenshot 2023-06-10 at 08 59 49" src="https://github.com/drakkan/sftpgo/assets/4686040/0672253e-8588-4159-bfec-144ad95cfdcb">

### Steps to reproduce

1. Install sftpgo on kubernetes from helm chart
2. Create a user with S3 Filesystem
3. Upload a new files on the new user

### Expected behavior

It should upload the file and listed on the user files list

### SFTPGo version

2.5.1

### Data provider

postgresql

### Installation method

Community Docker image

### Configuration

Config has only dataprovider defined

### Relevant log output

```shell
{"level":"debug","time":"2023-06-10T05:59:42.775","sender":"HTTP","connection_id":"HTTP_ci212jjec0rc73c2jg20","message":"connection added, local address \"10.244.3.187:8080\", remote address \"10.244.3.89:35208\", num open connections: 1"}
{"level":"error","time":"2023-06-10T05:59:42.912","sender":"HTTP","connection_id":"HTTP_ci212jjec0rc73c2jg20","message":"error opening existing file, source: \"test/home.png\", err: open /test/pipefile1387135604: no such file or directory"}
{"level":"error","time":"2023-06-10T05:59:42.912","sender":"HTTP","connection_id":"HTTP_ci212jjec0rc73c2jg20","message":"generic error: open /test/pipefile1387135604: no such file or directory"}
{"level":"debug","time":"2023-06-10T05:59:42.912","sender":"HTTP","connection_id":"HTTP_ci212jjec0rc73c2jg20","message":"connection removed, local address \"10.244.3.187:8080\", remote address \"10.244.3.89:35208\" close fs error: <nil>, num open connections: 0"}
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
wow a home user running SFTPGo on Kubernetes. However the reported issue is invalid and I don't provide step by step support for free, sorry

**Comment by botzill** [comment]
Hi @drakkan, thanks for response. Why is invalid? How do we get paid support?

**Comment by drakkan** [comment]
> Hi @drakkan, thanks for response. Why is invalid? How do we get paid support?

a GitHub [sponsorship](https://github.com/sponsors/drakkan) or a support plan from the sftpgo [website](https://sftpgo.com/#pricing). Thank you

**Comment by botzill** [comment]
Hi @drakkan, I did contribute to the project with a donation, I appreciate your work.

Let me if that is ok, for the future i'm sure I can contribute more when we start using it more often.

Can you let me know about the issues I am facing?

**Comment by drakkan** [comment]
Thanks for supporting the project. When creating your users, leave the home directory blank for an appropriate default. This should fix your problem (or at least the error should change). As a supporter of the project you can also contact me at the dedicated email address support at sftpgo dot com.

**Comment by botzill** [comment]
and if another user want to access his own sub folder on the same bucket, how do I specify that?

**Comment by drakkan** [comment]
> and if another user want to access his own sub folder on the same bucket, how do I specify that?

by setting a key prefix like this


![Schermata del 2023-06-12 08-36-38](https://github.com/drakkan/sftpgo/assets/553263/978cdc6a-f0e2-411e-87da-c19683476ae4)

**Comment by botzill** [comment]
I did set that Key prefix, folders are created OK in S3, but I get 413 status code when I upload a file, anything else to check?

Thanks.

**Comment by drakkan** [comment]
413 means request too large. What is the size of the file you are trying to upload? Can you please also share the full sftpgo logs? here or privately to the dedicate email address?

**Comment by botzill** [comment]
1.2M png image

**Comment by drakkan** [comment]
> 1.2 MB png image, will check the logs

Wasabi s3 is unlikely to have such a limitation and neither is SFTPGo. I guess you are uploading from the WebClient UI and have an NGINX based reverse proxy. In NGINX the default client_max_body_size is 1MB, please check

**Comment by botzill** [comment]
you are right, I did fix that by increasing the nginx. 

Thanks !

**Comment by drakkan** [comment]
> you are right, I did fix that by increasing the nginx.
> 
> Thanks !

no problem, but next time please include the sftpgo logs as well, otherwise I have to guess. 

Your architecture is quite complex, that's why there is no fixed price for multi-node installations. You will soon have other issues :smile:

**Comment by botzill** [comment]
ok, I did write you on email, let's continue there/
