### ISSUE TITLE
[Bug]: K8S: Connections from node

### ISSUE THREAD

**Issue by flaupretre** [drakkan/sftpgo#1322]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hello,

I am using sftpgo in a AWS (EKS) Kubernetes cluster. Deployed version 2.4.3 via the 'sagikazarmark' chart.

Every 10 seconds, these 2 messages go to my log : 
 
     {"level":"debug","time":"2023-06-13T08:34:21.500","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
     {"level":"debug","time":"2023-06-13T08:34:21.500","sender":"connection_failed","client_ip":"11.0.3.143","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}

11.0.3.143 is the IP address of the node host SFTPGO is running on. So, it looks like a connection done by the K8S kubelet to the sftp port. But I use the default liveness/readiness probes, configured as a bare http connection to the 'telemetry' port. These probes run OK so the messages above are caused by something else. I don't understand why the kubelet would connect to my sftp port without such a behavior being configured anywhere. Actually, this is not strictly an SFTPGO issue but I hope someone has met it already.

Actually, this makes using the defender impossible as it immediately bans the node address and subsequent requests are blocked. The bonus (unrelated) question being : why do every request go through the node despite the "service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip" service annotation ?

Every suggestion to explain this is welcome. Thanks.

### Steps to reproduce

Install SFTPGO on a K8S cluster using "https://charts.sagikazarmark.dev"

### Expected behavior

No scheduled request on sftp port (every 10 sec).

### SFTPGo version

2.4.3

### Data provider

postgres

### Installation method

Community Docker image

### Configuration

config:
  common:
    upload_mode: 1
    setstat_mode: 1
    defender:
      enabled: false
      driver: provider
  sftpd:
    host_keys: [ "${local.host_key_path}" ]
    keyboard_interactive_authentication: false
    password_authentication: false
  data_provider:
    driver: postgresql
    create_default_admin: true
    update_mode: 0
    backups_path: /tmp

### Relevant log output

```shell
{"level":"debug","time":"2023-06-13T08:34:31.499","sender":"connection_failed","client_ip":"11.0.3.143","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}
{"level":"debug","time":"2023-06-13T08:34:41.500","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
```

### What are you using SFTPGo for?

Enterprise

**Comment by drakkan** [comment]
Hello,

You are using an old/unmaintained SFTPGo version and your question is not strictly related to SFTPGo (and this is a configuration issue, not a bug). It should also be quite clear that no support is provided for people/companies using SFTPGo for free.
Perhaps you can try to raise an issue in the chart [repo](https://github.com/sagikazarmark/helm-charts). Good luck!
