### ISSUE TITLE
Log SFTP algo used

### ISSUE THREAD

**Issue by sebPomme** [drakkan/sftpgo#1324]
### Is your feature request related to a problem? Please describe.

I want to monitor witch of my sftp clients use weak `host_key_algorithms` `kex_algorithms` `ciphers` or `macs`.

### Describe the solution you'd like

I wonder if this is possible to log thees informations on debug log stream. 

### Describe alternatives you've considered

I don't find any that didn't consist of put only one of each and wait to have this kind of logs.  
```
 client offered: [diffie-hellman-group-exchange-sha1], server offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha256]"}
```
Not very usable method.  
Maybe someone else known a better solution ?

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment]
https://go-review.googlesource.com/c/crypto/+/538235
