### ISSUE TITLE
Log rotation period

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#133]
Hello.

Would it be possible to also have config option for setting log rotation period (for example 1d)? Currently, we can only rotate logs per size, but that can vary massively (on a busy day it can rotate multiple days, while sometimes it can go days without rotation). Having an option to specify period would enable us to have for example 1 log per day.

It should rotate by period or max-size (what comes earlier).

**Comment by drakkan** [comment]
Hi, we use [lumberjack](https://github.com/natefinch/lumberjack) for log file rotation, this feature was requested several times for lumberjack but it wasn't accepted, see for example the following issues:

https://github.com/natefinch/lumberjack/issues/17
https://github.com/natefinch/lumberjack/issues/54

I'll evaluate to use a cron like timer inside SFTPGo and I'll try to add options to rotate logs daily, weekly and monthly but please don't expect that this will be perfect, read the above issues for details, and probaly the time based rotation will not take place if SFTPGo isn't running at midnight. 

If you want something better please try to convince lumberjack maintainers that this is a good idea or help me to find a mature Go log files rotation library that supports this feature and all the features supported by lumberjack too. For example this [library](https://github.com/lestrrat-go/file-rotatelogs) (not tested) seems to support time based log files rotation but log files compression (and probably size based rotation) seems not supported.

**Comment by jovandeginste** [comment]
I didn't read the issues above, so maybe my question is answered there. Would it be possible to write to a template like filename? The template can be a string understood by `time.Parse`, which means the admin has some control over the timeframe for each log.

**Comment by sergiz** [comment]
Thanks for the explanation.

The relatively simple solution I was thinking of. When sftpgo is started get the time of the first line in existing log. Then every time before a log message is written, check if "(current time - first time) > period" and if it passes, rotate the file. That way there is no need for any complications with timers or/and cron jobs.

**Comment by sergiz** [comment]
Thanks for the explanation.

The relatively simple solution I was thinking of. When sftpgo is started get the time of the first line in existing log. Then every time before a log message is written do a following check (I will just put some examples and you will get the idea):

Period in config: 1d
First log line: 2020-06-20T09:05:00.031
Check if current time is equal or higher than 2020-06-21T00:00:00.000

Period in config: 1h
First log line: 2020-06-20T09:05:00.031
Check if current time is equal or higher than 2020-06-20T10:00:00.000

Period in config: 2h
First log line: 2020-06-20T09:05:00.031
Check if current time is equal or higher than 2020-06-20T11:00:00.000

Period in config: 1m
First log line: 2020-06-20T09:05:00.031
Check if current time is equal or higher than 2020-06-20T09:06:00.000

This way there don't need to be any complications with timers, and logs will be rotated regardless of when sftpgo is running.

**Comment by sergiz** [comment]
Thanks for the explanation.

I think that a better alternative is to simply use some external program for more advanced log rotation (like logrotate). In that case, sftpgo should support listening to SIGUSR1 signal, so after we rotate the log, it would re-open the log file at the specified path. That's how all popular programs do it basically.

**Comment by jovandeginste** [comment]
Yup, totally agree

**Comment by DeRuina** [comment]
For anyone still looking for time-based log rotation, I created a fork of Lumberjack called [Timberjack](https://github.com/DeRuina/timberjack).

It adds support for time-based rotation through a `RotationInterval` setting, while keeping everything else the same.

Just wanted to share in case it’s useful. Feedback, issues, or PRs are welcome! 

https://github.com/DeRuina/timberjack
