### ISSUE TITLE
Allow using environment variables in event action HTTP headers

### ISSUE THREAD

**Issue by bigbasti** [drakkan/sftpgo#1335]
### Describe the solution you'd like

I would like to call an API whenever a user is creating a directory. This is working fine with event actions, however, the target API is secured and required an Authorization HTTP header containing an API key (JWT).

Easiest way for me would be if i could read the API key fron an environment variable which is set when the container is created.
So i could create http Header in the event action like "Authorization" and value "Bearer ${MY_API_KEY}"

Is there a reason this is not supported? Or is there a better way of achieving my desired solution?

**Comment by drakkan** [comment]
I don't plan to work on a feature like this myself sorry. I will be glad to review a PR. Thank you
