### ISSUE TITLE
[Bug]: Backblaze B2 - Upload fails when Object Lock is enabled  

### ISSUE THREAD

**Issue by luissantos** [drakkan/sftpgo#1336]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

The upload fails when B2 Object Lock is enable. 

```
2023-06-23T13:16:12.897 DBG upload completed, path: "doorbell/2023/", acl: "", readed bytes: 0, err: operation error S3: PutObject, https response error StatusCode: 400, RequestID: 54e445b4417bb4e2, HostID: aMLg1mDV0YtpjbWKpM9o1CTIjOOZhDTRi, api error InvalidRequest: Missing required header for this request: Content-MD5 | sender=S3Fs bucket "camera-events" connection_id=FTP_0_35
```

### Steps to reproduce

1. Setup an B2 Bucket (S3 compatible) 
1.1 Endpoint: https://s3.eu-central-003.backblazeb2.com/
1. Enable Object Lock Retention and set retention policy to 1 day or more
1. Upload file 

### Expected behavior

File is uploaded successfully

### SFTPGo version

2.5.2-a503feaa-2023-06-17T16:50:53Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +unixcrypt +portable

### Data provider

s3

### Installation method

Community Docker image

### Configuration

`{
  "common": {
    "idle_timeout": 15,
    "upload_mode": 0,
    "actions": {
      "execute_on": [],
      "execute_sync": [],
      "hook": ""
    },
    "setstat_mode": 0,
    "temp_path": "",
    "proxy_protocol": 0,
    "proxy_allowed": [],
    "startup_hook": "",
    "post_connect_hook": "",
    "post_disconnect_hook": "",
    "data_retention_hook": "",
    "max_total_connections": 0,
    "max_per_host_connections": 20,
    "whitelist_file": "",
    "allow_self_connections": 0,
    "defender": {
      "enabled": false,
      "driver": "memory",
      "ban_time": 30,
      "ban_time_increment": 50,
      "threshold": 15,
      "score_invalid": 2,
      "score_valid": 1,
      "score_limit_exceeded": 3,
      "score_no_auth": 2,
      "observation_time": 30,
      "entries_soft_limit": 100,
      "entries_hard_limit": 150,
      "safelist_file": "",
      "blocklist_file": "",
      "safelist": [],
      "blocklist": []
    },
    "rate_limiters": [
      {
        "average": 0,
        "period": 1000,
        "burst": 1,
        "type": 2,
        "protocols": [
          "SSH",
          "FTP",
          "DAV",
          "HTTP"
        ],
        "allow_list": [],
        "generate_defender_events": false,
        "entries_soft_limit": 100,
        "entries_hard_limit": 150
      }
    ]
  },
  "acme": {
    "domains": [],
    "email": "",
    "key_type": "4096",
    "certs_path": "certs",
    "ca_endpoint": "https://acme-v02.api.letsencrypt.org/directory",
    "renew_days": 30,
    "http01_challenge": {
      "port": 80,
      "proxy_header": "",
      "webroot": ""
    },
    "tls_alpn01_challenge": {
      "port": 0
    }
  },
  "sftpd": {
    "bindings": [
      {
        "port": 0,
        "address": "",
        "apply_proxy_config": true
      }
    ],
    "max_auth_tries": 0,
    "banner": "",
    "host_keys": [],
    "host_certificates": [],
    "host_key_algorithms": [],
    "moduli": [],
    "kex_algorithms": [],
    "ciphers": [],
    "macs": [],
    "trusted_user_ca_keys": [],
    "revoked_user_certs_file": "",
    "login_banner_file": "",
    "enabled_ssh_commands": [
      "md5sum",
      "sha1sum",
      "sha256sum",
      "cd",
      "pwd",
      "scp"
    ],
    "keyboard_interactive_authentication": false,
    "keyboard_interactive_auth_hook": "",
    "password_authentication": true,
    "folder_prefix": ""
  },
  "ftpd": {
    "bindings": [
      {
        "port": 2021,
        "address": "0.0.0.0",
        "apply_proxy_config": true,
        "tls_mode": 0,
        "certificate_file": "",
        "certificate_key_file": "",
        "min_tls_version": 12,
        "force_passive_ip": "192.168.1.100",
        "passive_ip_overrides": [],
        "client_auth_type": 0,
        "tls_cipher_suites": [],
        "passive_connections_security": 0,
        "active_connections_security": 0,
        "debug": false
      }
    ],
    "banner": "",
    "banner_file": "",
    "active_transfers_port_non_20": true,
    "passive_port_range": {
      "start": 50000,
      "end": 50100
    },
    "disable_active_mode": false,
    "enable_site": false,
    "hash_support": 0,
    "combine_support": 0,
    "certificate_file": "",
    "certificate_key_file": "",
    "ca_certificates": [],
    "ca_revocation_lists": []
  },
  "webdavd": {
    "bindings": [
      {
        "port": 0,
        "address": "",
        "enable_https": false,
        "certificate_file": "",
        "certificate_key_file": "",
        "min_tls_version": 12,
        "client_auth_type": 0,
        "tls_cipher_suites": [],
        "prefix": "",
        "proxy_allowed": [],
        "client_ip_proxy_header": "",
        "client_ip_header_depth": 0,
        "disable_www_auth_header": false
      }
    ],
    "certificate_file": "",
    "certificate_key_file": "",
    "ca_certificates": [],
    "ca_revocation_lists": [],
    "cors": {
      "enabled": false,
      "allowed_origins": [],
      "allowed_methods": [],
      "allowed_headers": [],
      "exposed_headers": [],
      "allow_credentials": false,
      "max_age": 0,
      "options_passthrough": false,
      "options_success_status": 0,
      "allow_private_network": false
    },
    "cache": {
      "users": {
        "expiration_time": 0,
        "max_size": 50
      },
      "mime_types": {
        "enabled": true,
        "max_size": 1000
      }
    }
  },
  "data_provider": {
    "driver": "sqlite",
    "name": "sftpgo.db",
    "host": "",
    "port": 0,
    "username": "",
    "password": "",
    "sslmode": 0,
    "disable_sni": false,
    "target_session_attrs": "",
    "root_cert": "",
    "client_cert": "",
    "client_key": "",
    "connection_string": "",
    "sql_tables_prefix": "",
    "track_quota": 2,
    "delayed_quota_update": 0,
    "pool_size": 0,
    "users_base_dir": "/srv/sftpgo/data",
    "actions": {
      "execute_on": [],
      "execute_for": [],
      "hook": ""
    },
    "external_auth_hook": "",
    "external_auth_scope": 0,
    "pre_login_hook": "",
    "post_login_hook": "",
    "post_login_scope": 0,
    "check_password_hook": "",
    "check_password_scope": 0,
    "password_hashing": {
      "bcrypt_options": {
        "cost": 10
      },
      "argon2_options": {
        "memory": 65536,
        "iterations": 1,
        "parallelism": 2
      },
      "algo": "bcrypt"
    },
    "password_validation": {
      "admins": {
        "min_entropy": 0
      },
      "users": {
        "min_entropy": 0
      }
    },
    "password_caching": true,
    "update_mode": 0,
    "create_default_admin": false,
    "naming_rules": 1,
    "is_shared": 0,
    "node": {
      "host": "",
      "port": 0,
      "proto": "http"
    },
    "backups_path": "/srv/sftpgo/backups"
  },
  "httpd": {
    "bindings": [
      {
        "port": 8080,
        "address": "",
        "enable_web_admin": true,
        "enable_web_client": true,
        "enable_rest_api": true,
        "enabled_login_methods": 0,
        "enable_https": false,
        "certificate_file": "",
        "certificate_key_file": "",
        "min_tls_version": 12,
        "client_auth_type": 0,
        "tls_cipher_suites": [],
        "proxy_allowed": [],
        "client_ip_proxy_header": "",
        "client_ip_header_depth": 0,
        "hide_login_url": 0,
        "render_openapi": true,
        "web_client_integrations": [],
        "oidc": {
          "client_id": "",
          "client_secret": "",
          "config_url": "",
          "redirect_base_url": "",
          "scopes": [
            "openid",
            "profile",
            "email"
          ],
          "username_field": "",
          "role_field": "",
          "implicit_roles": false,
          "custom_fields": [],
          "insecure_skip_signature_check": false,
          "debug": false
        },
        "security": {
          "enabled": false,
          "allowed_hosts": [],
          "allowed_hosts_are_regex": false,
          "hosts_proxy_headers": [],
          "https_redirect": false,
          "https_host": "",
          "https_proxy_headers": [],
          "sts_seconds": 0,
          "sts_include_subdomains": false,
          "sts_preload": false,
          "content_type_nosniff": false,
          "content_security_policy": "",
          "permissions_policy": "",
          "cross_origin_opener_policy": "",
          "expect_ct_header": ""
        },
        "branding": {
          "web_admin": {
            "name": "",
            "short_name": "",
            "favicon_path": "",
            "logo_path": "",
            "login_image_path": "",
            "disclaimer_name": "",
            "disclaimer_path": "",
            "default_css": "",
            "extra_css": []
          },
          "web_client": {
            "name": "",
            "short_name": "",
            "favicon_path": "",
            "logo_path": "",
            "login_image_path": "",
            "disclaimer_name": "",
            "disclaimer_path": "",
            "default_css": "",
            "extra_css": []
          }
        }
      }
    ],
    "templates_path": "templates",
    "static_files_path": "static",
    "openapi_path": "openapi",
    "web_root": "",
    "certificate_file": "",
    "certificate_key_file": "",
    "ca_certificates": [],
    "ca_revocation_lists": [],
    "signing_passphrase": "",
    "token_validation": 0,
    "max_upload_file_size": 1048576000,
    "cors": {
      "enabled": false,
      "allowed_origins": [],
      "allowed_methods": [],
      "allowed_headers": [],
      "exposed_headers": [],
      "allow_credentials": false,
      "max_age": 0,
      "options_passthrough": false,
      "options_success_status": 0,
      "allow_private_network": false
    },
    "setup": {
      "installation_code": "",
      "installation_code_hint": "Installation code"
    },
    "hide_support_link": false
  },
  "telemetry": {
    "bind_port": 0,
    "bind_address": "127.0.0.1",
    "enable_profiler": false,
    "auth_user_file": "",
    "certificate_file": "",
    "certificate_key_file": "",
    "min_tls_version": 12,
    "tls_cipher_suites": []
  },
  "http": {
    "timeout": 20,
    "retry_wait_min": 2,
    "retry_wait_max": 30,
    "retry_max": 3,
    "ca_certificates": [],
    "certificates": [],
    "skip_tls_verify": false,
    "headers": []
  },
  "command": {
    "timeout": 30,
    "env": [],
    "commands": []
  },
  "kms": {
    "secrets": {
      "url": "",
      "master_key": "",
      "master_key_path": ""
    }
  },
  "mfa": {
    "totp": [
      {
        "name": "Default",
        "issuer": "SFTPGo",
        "algo": "sha1"
      }
    ]
  },
  "smtp": {
    "host": "",
    "port": 25,
    "from": "",
    "user": "",
    "password": "",
    "auth_type": 0,
    "encryption": 0,
    "domain": "",
    "templates_path": "templates"
  },
  "plugins": []
}`

### Relevant log output

```shell
2023-06-23T13:25:17.558 ERR transfer error: operation error S3: PutObject, https response error StatusCode: 400, RequestID: 215e00bb5ea13076, HostID: aMFI1ITVZYlBjcWKmMxM1jjL3ON9hKDRV, api error InvalidRequest: Missing required header for this request: Content-MD5, path: "atomic-blast.png" | sender=HTTP connection_id=HTTP_ciapqf5dlgc000dn8ee0

2023-06-23T13:25:17.558 DBG transfer removed, id: 1 active transfers: 0 | sender=HTTP connection_id=HTTP_ciapqf5dlgc000dn8ee0

2023-06-23T13:25:17.558 ERR generic error: operation error S3: PutObject, https response error StatusCode: 400, RequestID: 215e00bb5ea13076, HostID: aMFI1ITVZYlBjcWKmMxM1jjL3ON9hKDRV, api error InvalidRequest: Missing required header for this request: Content-MD5 | sender=HTTP connection_id=HTTP_ciapqf5dlgc000dn8ee0
```

**Comment by drakkan** [comment]
Hello,

thank you for reporting this issue. I don't plan to work on this edge case (currently I don't even have a B2 test account), I will be glad to review a PR.

**Comment by portswigger-tim** [comment]
Seems related to: https://github.com/aws/aws-sdk-go/issues/1553

which may help somebody with a PR.

**Comment by drakkan** [comment]
> Seems related to: [aws/aws-sdk-go#1553](https://github.com/aws/aws-sdk-go/issues/1553)
> 
> which may help somebody with a PR.

please don't post random and unrelated stuff. This just creates confusion.

This is an S3 bug, I don't think there's anything SFTPGo can do

https://github.com/aws/aws-sdk-go-v2/issues/1040

Please follow up there.

**Comment by metadaddy** [comment]
@drakkan One clarification, according to https://github.com/aws/aws-sdk-go/issues/1553, this bug is not related to Backblaze B2. An S3 bucket with object lock enabled will behave in the same way.

From https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-managing.html#object-lock-put-object

> The Content-MD5 header is required for any request to upload an object with a retention period configured using Object Lock. The MD5 digest is a way to verify the integrity of your object after uploading it to a bucket. After uploading the object, Amazon S3 calculates the MD5 digest of the object and compares it to the value that you provided. The request succeeds only if the two digests match. The S3 console automatically adds this header, however you must specify this header when using the [PutObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) API.

For more information, see [Using Content-MD5 when uploading objects](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#checking-object-integrity-md5).

**Comment by drakkan** [comment]
@metadaddy yes, that's clear. I don't understand what you want to add here though. 

As a Backblaze employee are you making it clear that this is not a problem related to your company? Great! But maybe it would be better to contribute a fix for the s3 manager instead since it is also used to interact with Backblaze B2. 

SFTPGo code is also public if you think this can be fixed in SFTPGo :smile: Thank you

**Comment by marsteel** [comment]
This is expected according to AWS support. "You can place a retention period explicitly on an individual object version or on a bucket's properties so that it applies to all objects in the bucket automatically. "

Possible workaround is:

- lambda to move files from EFS to S3
- AWS DataSync to move files from EFS to S3
- Use s3fs (if s3fs supports Object Lock) and mount S3 to SFTPGo

**Comment by marziaelia** [comment]
Just for information, this feature is included in SFTPGo Enterprise:

https://docs.sftpgo.com/enterprise/s3/#configuration
