### ISSUE TITLE
Cannot deny `list` permission from a subdirectory of the user's home dir

### ISSUE THREAD

**Issue by piaste** [drakkan/sftpgo#134]
Hello,

I'm running the latest build from source (commit b30614e9d8db3b5fdfa7156e5e67dcfcf155470b) and I'm setting up a shared SFTP where users can upload and download files of various categories. 

Inside each user's folder, we would like to also store some pre- or post-processed versions of the data that the user shouldn't have access to. Example:

```
/user1
/user1/category1/upload
/user1/category1/upload_results
/user1/category1/download
/user1/category1/download_results
// same for category2, user2, etc.
```

User1 should be able to:

 - list /user1
 - list /user1/category1
 - list or upload in /user1/category1/upload
 - list or download in /user1/category1/download
 - NOT list the contents of /user1/category1/upload_results
 - NOT list the contents of /user1/category1/download_results

According to this pull request: https://github.com/drakkan/sftpgo/commit/8eff2df39c12f663f1dcd4d18903ef44d81e6b1a it seems this should be possible by setting the permissions to an empty string, or (according to the linked issue) by setting a useless `chtimes` permissions.

I've tried the following configurations but without getting the right result:

```
Home dir : /user1
Home permission: list

/user1::list
/user1/category1/upload::list,upload
/user1/category1/upload_results::
/user1/category1/download::list,download,delete
/user1/category1/download_results::chtimes
```

Outcome: user can still list the contents of both `upload_results` and `download_results`.

```
Home dir : /user1
Home permission: chtimes

/user1::list
/user1/category1/upload::list,upload
/user1/category1/download::list,download,delete
```

Outcome: user cannot use the SFTP connection at all (using FileZilla).

The only set up I have found that works is giving the user a dummy home dir outside of the actual hierarchy, and then using virtual folders to only show him the uploads and downloads for each category. But that seems like a hack.

Am I misunderstanding how empty / denied permissions are supposed to work?

**Comment by drakkan** [comment]
Hi,

what you describe should work. Please note that permissions should be configured for SFTP paths and not filesystem paths, so if the home dir is `/user1` and so `/user1/category1` filesystem path is accessible as `/category1` SFTP path you have to set permissions for `/category1` and not for `/user1/category1`. Please let me know if it works as expected after setting the permissions this way, thanks

**Comment by piaste** [comment]
Ahhh, that was it. Works perfectly now - should have figured it from the way vfolders were configured similarly.

Thanks a lot for the quick response! 👍
