### ISSUE TITLE
[Bug]: Validation error: home_dir is mandatory

### ISSUE THREAD

**Issue by kbdavis07** [drakkan/sftpgo#1341]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

When SFTPGo is installed as a "Service" on a Windows 2019 VM, when creating a new user with a Primary group that has a home directory, the newly created user is not inheriting the home directory that is used in the Primary group and this giving the error

" Validation error: home_dir is mandatory"

When put in a directory for the home directory of the user the error goes away, but that then do away with the point of a Primary group where you can set settings there and have users get those settings without having to repeat the process with each new user created.

### Steps to reproduce

1. Download and install : [sftpgo_v2.5.2_windows_x86_64.exe](https://github.com/drakkan/sftpgo/releases/download/v2.5.2/sftpgo_v2.5.2_windows_x86_64.exe)
On a Windows Device, like a VM server and etc.
2. Create a Group with a home directory
3. Create a New User
4. Select the new Group as "Primary"
5. Click Submit
6. Notice the Error: "Validation error: home_dir is mandatory"

### Expected behavior

User to be created with settings from the Primary Group the user was assigned to.

### SFTPGo version

2.5.2 Windows X86_64

### Data provider

sqlite

### Installation method

Other

### Configuration

Using the default configuration settings after install.

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional info

When using Docker version, not having this issue, only when using SFTPGo as a Window Server is when having this issue.

**Comment by drakkan** [comment]
This is a support question and we don't provide free support, sorry

**Comment by drakkan** [comment]
> So this is not a bug then?
> 
> I am doing something wrong on my end then is why it is not working?

Please don't ask for free support. Thanks for understanding

**Comment by Macleykun** [comment]
> So this is not a bug then?
> 
> I am doing something wrong on my end then is why it is not working?

heya @kbdavis07 have you been able to find a solution why this error is thrown?
Sadly have the same problem.

**Comment by Macleykun** [comment]
Found the issue related to this.
If you create a user through the UI, and would only give the username, it will throw the same error.
Based on that, i found out i had to add this:
```json
  "data_provider": {
    "users_base_dir": "/srv/sftpgo/sftpgo/data"
  },
```
If you login, it will create a subfolder with the username's name.

https://github.com/drakkan/sftpgo/issues/1373#issuecomment-1658757337
