### ISSUE TITLE
Support Podman healthcheck for OCI image

### ISSUE THREAD

**Issue by EndzeitBegins** [drakkan/sftpgo#1343]
### Is your feature request related to a problem? Please describe.

We're evaluating the use of `sftpgo`, especially the OCI image, right now to provide controlled SFTP access to a shared file system. 

In our environment we're using Podman to run OCI containers. Podman [allows to define a healthcheck](https://docs.podman.io/en/latest/markdown/podman-run.1.html#health-cmd-command-command-arg1) when running containers. The command provided is executed inside the container. 

sftpgo provides a HTTP API endpoint suitable for the healthcheck functionality under `/healthz`.

Oftentimes common Linux tools such as `curl` or `wget` are used to execute healthchecks against HTTP API endpoints. However, these are not available in the default OCI image variant of sftpgo available on Docker Hub. 

---

I would love to contribute this minor addition, if that's desired and welcomed. However, my knowledge of Go is quite limited.

### Describe the solution you'd like

I'd prefer a script / Go program bundled into the OCI container, e.g. under `/healthcheck`, that makes a HTTP call to the existing `/healthz` endpoint introduced as part of #212.

This way, the healthcheck configured in Podman or alternatives would simply need to delegate to the existing script / program.

### Describe alternatives you've considered

One alternative would be to install `curl`, `wget` or a similar third party tool into the container image in order to be able to execute a custom healthcheck, such as `curl localhost:8080/healthz`.
Personally I do not like this approach, as it bloats the image.
This is also an eligible workaround when creating ones own image based on `drakkan/sftpgo`.

Another feasible workaround could be to mount a self-contained script / program into the running container that provides the functionality.

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment]
Hello,

this feature is already supported. 
Please read the documents more carefully or support the project if you want answers to questions like this and if you want SFTPGo to be sustainable in the long run (it is also your interest if you use SFTPGo). Thank you

**Comment by EndzeitBegins** [comment]
I'm sorry, I must've overlooked it while reading the documentation.
Thank you (and the other contributors) for the great work you've done with sftpgo! I'll advocate to support the project financially in case we decide to move forward with sftpgo. 

---

For anyone stumbling upon this issue in the future:

The functionality is provided by command `ping` of the `sftpgo` executable, as [outlined in the documentation](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#configuring-sftpgo).

Thus a suitable healthcheck command may look as simple as 
```sh
sftpgo ping
```
