### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by niele84-dot** [drakkan/sftpgo#1344]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hi,
I m experiencing a reoccurring issue when I try to upload files via passive ftp to sftpgo.
At some point the server is unable to serve other requests because all ports are occupied. In Sftpgo connections tab I see that one connection is still open since long time, although the client issued a QUIT command.
If I look at the log files, the QUIT command is never followed by "221" acknowledge message, as it happens for all other connections. 
When that occurs the sftpgo instance, every new FTP port opened for communication (Passive FTP) is not closed and also the event manager doesn't trigger any action for new uploads.

Attached a log, removed from sensible informations and a screenshot of the open connection.

![Screenshot 2023-06-28 224545](https://github.com/drakkan/sftpgo/assets/56230147/53c457f8-d038-4eb7-a767-b8338f8a41ce)

### Steps to reproduce

1. Set up the ftp server to accept passive FTP connections
2. Run uploads from multiple users (I have 3 hw uploading files to the server)

### Expected behavior

The ftp passive connection is closed.

### SFTPGo version

2.5.2-a503feaa-2023-06-17T16:51:59Z 

### Data provider

sqlite

### Installation method

Community Deb package

### Configuration

tested with both `idle_timeout=0` and `idle_timeout=15`

### Relevant log output

```shell
{"level":"debug","time":"2023-06-28T16:30:49.446","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","clientIp":"XX.XX.XX.XX:57882","message":"Client connected"}
{"level":"debug","time":"2023-06-28T16:30:49.447","sender":"FTP","connection_id":"FTP_0_273","message":"connection added, local address \"<destination_server>:2121\", remote address \"XX.XX.XX.XX:57882\", num open connections: 2"}
{"level":"debug","time":"2023-06-28T16:30:49.448","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"220 Welcome in sftpgo server","message":"Sending answer"}
{"level":"debug","time":"2023-06-28T16:30:49.498","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"USER user1","message":"Received line"}
{"level":"debug","time":"2023-06-28T16:30:49.498","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"331 OK","message":"Sending answer"}
{"level":"debug","time":"2023-06-28T16:30:49.545","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"PASS XXXXX","message":"Received line"}
{"level":"debug","time":"2023-06-28T16:30:49.552","sender":"common","connection_id":"FTP_0_273","message":"connection swapped, close fs error: <nil>"}
{"level":"info","time":"2023-06-28T16:30:49.552","sender":"FTP","connection_id":"FTP_0_273","message":"User \"user1\" logged in with \"password\" from ip \"XX.XX.XX.XX\""}
{"level":"debug","time":"2023-06-28T16:30:49.552","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"230 Password ok, continue","message":"Sending answer"}
{"level":"debug","time":"2023-06-28T16:30:49.596","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"TYPE I","message":"Received line"}
{"level":"debug","time":"2023-06-28T16:30:49.597","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"200 Type set to binary","message":"Sending answer"}
{"level":"debug","time":"2023-06-28T16:30:49.643","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"CWD .//remote_folder/images/","message":"Received line"}
{"level":"debug","time":"2023-06-28T16:30:49.644","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"250 CD worked on /remote_folder/images","message":"Sending answer"}
{"level":"debug","time":"2023-06-28T16:30:49.692","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"PASV","message":"Received line"}
{"level":"debug","time":"2023-06-28T16:30:49.692","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"227 Entering Passive Mode (XX,XX,XX,X,XXX,XXX)","message":"Sending answer"}
{"level":"debug","time":"2023-06-28T16:30:49.737","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"STOR file_304110.jpg","message":"Received line"}
{"level":"debug","time":"2023-06-28T16:30:49.839","sender":"FTP","connection_id":"FTP_0_273","message":"transfer added, id: 1, active transfers: 1"}
{"level":"debug","time":"2023-06-28T16:30:49.840","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"150 Using transfer connection","message":"Sending answer"}
{"level":"debug","time":"2023-06-28T16:30:49.840","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","remoteAddr":"XX.XX.XX.XX:37718","localAddr":"<destination_server>:50063","message":"Transfer connection opened"}

........

{"level":"debug","time":"2023-06-28T16:31:52.392","sender":"ftpserverlib","server_id":"FTP_0","clientId":"273","line":"QUIT ","message":"Received line"}
{"level":"debug","time":"2023-06-28T16:31:52.894","sender":"ftpserverlib","server_id":"FTP_0","clientId":"279","clientIp":"XX.XX.XX.XX:27727","message":"Client connected"}
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Hello,

please share the full logs and/or a full network dump or a standalone reproducer. It is unlikely we can do anything with the above info. 

There are production installations with thousands of concurrent connections and no issues, this looks like a client specific problem, can you share the client version? Is this client something I can test myself? FTP is an old protocol with many edge cases.

If you don't want/can share the full logs and a network dump you can also try debugging and fixing it yourself, this is probably something in [ftpserverlib](https://github.com/fclairamb/ftpserverlib), probably a one line of code fix. Thank you

**Comment by niele84-dot** [comment]
Hi,
thank you for the prompt reply. 
If I click disconnect I get only the following message in the log:
`{"level":"debug","time":"2023-07-03T21:01:39.225","sender":"FTP","connection_id":"FTP_0_134","message":"close connection requested, close err: close tcp <server_ip>:2121->XX.11.XX.210:38484: use of closed network connection"}
`
Unfortunately I can't share any standalone software as the client is a security camera and I don't have access to its source code. 
I tried to have a look at the ftpserverlib source code and I suspect that the `Wait` function within the  [HandleQuit](https://github.com/fclairamb/ftpserverlib/blob/47908399cd245697297ad9f75447817ae595a1ba/handle_misc.go#L275) function might be stuck for some reason waiting for some task to finish and the server nevers ends the connection properly.

**Comment by drakkan** [comment]
The QUIT command waits for the transfer to complete as requested in RFC 959.
I did several tests (simulating hangs both server and client side), after I click the "Disconnect" button the connection is always closed and disappear from the list of active connections.

```
{"level":"error","time":"2023-07-04T19:56:50.594","sender":"FTP","connection_id":"FTP_0_7","message":"Unexpected error for transfer, path: \"/tmp/nicola/android-studio-ide-181.5056338-linux.zip\", error: \"read tcp 127.0.0.1:50075->127.0.0.1:40796: use of closed network connection\" bytes sent: 0, bytes received: 0 transfer running since 26703 ms"}
{"level":"debug","time":"2023-07-04T19:56:50.594","sender":"FTP","connection_id":"FTP_0_7","message":"upload file size 0, num files 0, deleted files 0, fs path \"/tmp/nicola/android-studio-ide-181.5056338-linux.zip\""}
{"level":"info","time":"2023-07-04T19:56:50.594","sender":"Upload","local_addr":"127.0.0.1:2121","remote_addr":"127.0.0.1:52676","elapsed_ms":26703,"size_bytes":0,"username":"nicola","file_path":"/tmp/nicola/android-studio-ide-181.5056338-linux.zip","connection_id":"FTP_0_7","protocol":"FTP","ftp_mode":"passive"}
{"level":"error","time":"2023-07-04T19:56:50.594","sender":"FTP","connection_id":"FTP_0_7","message":"transfer error: read tcp 127.0.0.1:50075->127.0.0.1:40796: use of closed network connection, path: \"/tmp/nicola/android-studio-ide-181.5056338-linux.zip\""}
{"level":"debug","time":"2023-07-04T19:56:50.594","sender":"FTP","connection_id":"FTP_0_7","message":"transfer removed, id: 1 active transfers: 0"}
{"level":"error","time":"2023-07-04T19:56:50.594","sender":"FTP","connection_id":"FTP_0_7","message":"generic error: read tcp 127.0.0.1:50075->127.0.0.1:40796: use of closed network connection"}
{"level":"debug","time":"2023-07-04T19:56:50.594","sender":"FTP","connection_id":"FTP_0_7","message":"close connection requested, close err: <nil>"}
{"level":"warn","time":"2023-07-04T19:56:50.594","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","err":"write tcp 127.0.0.1:2121->127.0.0.1:52676: use of closed network connection","message":"Couldn't flush line"}
```

Sorry I can't help you if you are really using SFTPGo at home (do a home user need to show quota in the WebClient?) but with partial logs/info it's not possible even if I want to, and this kind of support (in-depth troubleshooting) it is part of the enterprise support plan. You have to debug/fix yourself, sorry.

**Comment by niele84-dot** [comment]
I understand your point and appreciate the testing and help you already provided.
To answer your question, yes the connection is not removed from the UI.
I will try to have a look at the source code and understand what is happenening.
Most likely, after few tries I will reach out to you to see if there is a way to purchase the bugfix only, as I can't buy the enterprise plan for my home server.

**Comment by drakkan** [comment]
In any case the full logs, with ftp debug enabled, are required to understand what happen and try to write a reproducer/test case.

Can you please share the camera manufacturer, model and firmware version? I have several security cameras. Thank you

**Comment by niele84-dot** [comment]
Hi Drakkan,

It seems that the issue was not due to FTP itself, but rather to the filesystem I was using, that for some reasons was interfering with SFTPGO and leading to exhaustion of FTP port. I was using curlftp for one folder, as filesystem, and that seem to have been the root cause. Once I switched back to the local filesystem, the issue did not occur anymore.

I will close the issue, and Thank you for your help!!!
