### ISSUE TITLE
Portable DNS Multicast

### ISSUE THREAD

**Issue by ohdearaugustin** [drakkan/sftpgo#135]
The command line argument  -S, --advertise-service of the portable command is set per default to true. As it is a BoolVarP it is now impossible to turn off the multicast DNS.

`	portableCmd.Flags().BoolVarP(&portableAdvertiseService, "advertise-service", "S", true, `"Advertise` SFTP service using multicast DNS")
`

My suggestion would be to set the default to false.

**Comment by drakkan** [comment]
Hi,

please try:

```
./sftpgo portable --advertise-service=false
```

**Comment by ohdearaugustin** [comment]
Thank you. Somehow it just didn't work with the the shortflag.

**Comment by drakkan** [comment]
> Thank you. Somehow it just didn't work with the the shortflag.

Hi, this one work too

```
./sftpgo portable -S=0
```

anyway I agree that the flag should be false by default

**Comment by ohdearaugustin** [comment]
I tried it with 
```
./sftpgo portable -Sfalse
```
which lead to this error.
```
Error: invalid argument "alse" for "-f, --fs-provider" flag: strconv.ParseInt: parsing "alse": invalid syntax
```
That caused all of my confusion.
