### ISSUE TITLE
Portable Password

### ISSUE THREAD

**Issue by ohdearaugustin** [drakkan/sftpgo#136]
It would be a nice feature to disable the password output from the portable command when the password is set per command line argument. This would make the portable command more useful for simple shares, as you won't leak your password in the logs.

Reproduce:

```sftpgo portable -p test123```

Output:
```
INF Portable mode ready, SFTP port: 63046, user: "user", password: "test", public keys: [], directory: "/srv/sftpgo", permissions: map[/:[list download]], enabled ssh commands: [md5sum sha1sum cd pwd scp] file extensions filters: []
```

Expected Output:
```
INF Portable mode ready, SFTP port: 63046, user: "user", public keys: [], directory: "/srv/sftpgo", permissions: map[/:[list download]], enabled ssh commands: [md5sum sha1sum cd pwd scp] file extensions filters: []
```

Edit: Better readability.

**Comment by ohdearaugustin** [comment]
Thank you a lot @drakkan (=

**Comment by drakkan** [comment]
> Thank you a lot @drakkan (=

You can test the changes using the build artificats here:

https://github.com/drakkan/sftpgo/actions/runs/146096034

if you don't want to rebuild yourself

**Comment by ohdearaugustin** [comment]
It works perfectly. (=

Tested:
* sftpgo-ubuntu-latest-go1.13
* sftpgo-ubuntu-latest-go1.14
