### ISSUE TITLE
[Bug]: Changing SFTP default port to 22 causes service to fail

### ISSUE THREAD

**Issue by jheran007** [drakkan/sftpgo#1362]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Following the docs, I've done the cap_net_bind_service commands but this doesn't seem to work. Once I change the port in the sftpgo.json file and attempt to restart the service I get the following errors.

```
sftpgo.service - SFTPGo Server
     Loaded: loaded (/lib/systemd/system/sftpgo.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2023-07-20 19:18:44 UTC; 889ms ago
    Process: 6088 ExecStart=/usr/bin/sftpgo serve (code=exited, status=1/FAILURE)
   Main PID: 6088 (code=exited, status=1/FAILURE)
```
+

### Steps to reproduce

1. Install via apt
2. Change default SFTP port in sftpgo.json
3. Restart sftpgo service

### Expected behavior

I would expect the service to start normally.

### SFTPGo version

Latest

### Data provider

?

### Installation method

Other

### Configuration

config

**Comment by drakkan** [comment]
Hello, I'm sorry this is not a bug, just a support question and we don't provide free support
