### ISSUE TITLE
[Bug]: sftpgo user does not have delete permissions on s3 bucket

### ISSUE THREAD

**Issue by piyu200594** [drakkan/sftpgo#1367]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I have setup sftpgo on a AWS Linux EC2 server. Everything is working fine except the sftpgo user is not able to delete files on the server. I tried with full S3 access role too but still a no go. Is this a bug or limitation in sftpgo? Or I am missing something.

### Steps to reproduce

1. Setup SFTPGO with S3 backend on a AWS S3 Linux box
2. Assign full S3 access role to the EC2 server.
3. SFTP to the server thru command line.
4. Run rm <name of file> 
5. I get error permission denied.
6. Read Write all working good

### Expected behavior

rm <filename>

Should be able to delete the file from S3 bucket

### SFTPGo version

v2.5.4

### Data provider

AWS S3

### Installation method

Community RPM package

### Configuration

NA

### What are you using SFTPGo for?

Professional user, 1 person business

### Additional info

NA

**Comment by drakkan** [comment]
This looks like a problem from your side. Delete works fine. Try checking your logs to figure out what's going on. I'm sorry but I no longer provide free support.

**Comment by piyu200594** [comment]
The Logs are just coming back saying permission denied even after having full S3 access policy attached. That is the reason I opened this bug. I tested on a GCS bucket and same issue rm command is not able to delete the file.

**Comment by piyu200594** [comment]
How do I get paid support for this?

**Comment by drakkan** [comment]
https://github.com/drakkan/sftpgo#sponsors

Please note that I am not interested in a one time sponsorship, if so please avoid. I want to make SFTPGo a long-term sustainable project. Thank you
