### ISSUE TITLE
Pre-calculated checksums for SFTP

### ISSUE THREAD

**Issue by ScuttleSE** [drakkan/sftpgo#1374]
### Is your feature request related to a problem? Please describe.

I am using rclone to sync data between a few different remote locations that are all running sftpgo. To calculate checksums on the files, to compare a file on site A with a file on site B, [rclone uses shell-commands that runs on the remote host.](https://rclone.org/sftp/#checksum)

When transfering large files, this can take up a substantial amount of time

### Describe the solution you'd like

It would be nice if there was an option to cache these checksum-requests, or even have sftpgo run the checksums on the files beforehand, so when rclone asks for them, it can instantly return the checksum

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
we don't plan support storing file metadata in a database sorry. Maybe this can be done using a plugin, in this case we should also define some new plugin API
