### ISSUE TITLE
Error on initializing data provider: no such table: schema_version

### ISSUE THREAD

**Issue by CompuRoot** [drakkan/sftpgo#138]
sftpgo: SFTPGo 1.0.0-1ac4baa-2020-07-06T20:46:08Z +metrics +gcs +s3 +bolt +mysql +pgsql +sqlite +portable

Prerequisites: 
    - mkdir CFG
    - copy default sftpgo.json to CFG
    - copy default template directory to CFG
    - create id_rsa, id_ecdsa in CFG

Run: sftpgo serve -c ./CFG

ERROR result: ERR error initializing data provider: no such table: schema_version

**Comment by drakkan** [comment]
Hi,

you need to initialize the configured dataprovider before starting SFTPGo, for example:

```
sftpgo initprovider -c ./CFG/
```

**Comment by CompuRoot** [comment]
Thank you for quick reply and thank you for the great idea as sftpgo !

Just curious, wouldn't be it better to throw more meaningful error message in such case instead absents of sql table it won't involve a lot of changes in the code?

**Comment by drakkan** [comment]
You should now get an error like this:

```
2020-07-09T19:58:33.759 WRN database query error, did you forgot to run the "initprovider" command?
2020-07-09T19:58:33.760 ERR error initializing data provider: no such table: schema_version
```
