### ISSUE TITLE
Hide the full absolute path

### ISSUE THREAD

**Issue by Joshua2504** [drakkan/sftpgo#1380]
### Describe the solution you'd like

When creating a new user, the full local storage path can be defined.

I have set the path to /mnt/storage/data in the sftpgo config file.

On user creation page, this should be the default storage path when defining a custom folder name.

Right now I can put anything there. For example path /user will also be /path on the server, while it should be /mnt/storage/data/path.

### What are you using SFTPGo for?

Enterprise

**Comment by Chouille** [comment]
+1

**Comment by drakkan** [comment]
This would be a backward incompatible change and hiding the path is already possible
