### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Knkkyl** [drakkan/sftpgo#1386]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

SFTPgo with external authentication and response code 200 with empty response body giving invalid credentials. I am using version 2.5.4

### Steps to reproduce

Successful authentication but with empty response body giving invalid credentials error in sftpgo logs

### Expected behavior

It should not show invalid credentials as per sftpgo external_auth.md

### SFTPGo version

2.5.4

### Data provider

Mariadb and sqlite

### Installation method

Community Deb package

### Configuration

Changed external_hook field in sftpgo.json to point to LDAP authentication http url

**Comment by drakkan** [comment]
Hello, this looks like a support request like the others. Please post the relevant logs

**Comment by Knkkyl** [comment]
Hi,
This is not support request. Because as per sftpgo
documentation(sftpgo/docs/external-auth.md)

If authentication succeeds the HTTP response code must be 200 and the
response body can be:

1)a valid SFTPGo user serialized as JSON. The user will be added/updated
within the defined data provider
2) empty, the existing SFTPGo user does not need to be updated. Please note
that in versions 2.0.x and earlier an empty response was interpreted as an
authentication error.

I am using 2.5.3 version of sftpgo and wanted to test 2nd option because I
don't want to update sftpgo user in database. But I am getting " invalid
credentials" error message.


Kindly help me in this regard.
Thank you

**Comment by drakkan** [comment]
Still no logs.

Please understand that I have no time/motivation to provide free support.
There's unlikely to be a bug here, many users use the auth hook like this.
If you post your logs and I see a bug, I may or may not fix it. If, as I think, you're just asking for free support (this is your third request on the auth hook), I'll just close the issue and continue ignoring you just like you ignore the support policy. Thanks for understanding.
