### ISSUE TITLE
[Bug]: SFTP cannot delete this file after editing and saving it.

### ISSUE THREAD

**Issue by yanliangchao** [drakkan/sftpgo#1394]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

SFTP cannot delete this file after editing and saving it.

### Steps to reproduce

1. Edit and save a file in the SFTP client
2. Then delete it and you will find that it cannot be deleted

### Expected behavior

I hope to delete the file

### SFTPGo version

SFTPGo - 2.1.2

### Data provider

mysql

### Installation method

Other

### Configuration

config

### Relevant log output

```shell
{"level":"info","time":"2023-08-18T10:12:23.780","sender":"Upload","remote_addr":"127.0.0.1:56528","elapsed_ms":4,"size_bytes":4,"username":"test","file_path":"C:\\YLC\\Temp\\home\\test\\aaa.txt","connection_id":"SFTP_b4c82839fd83e107a87938542f2b2a6b9c830371_1","protocol":"SFTP"}
{"level":"debug","time":"2023-08-18T10:12:23.780","sender":"SFTP","connection_id":"SFTP_b4c82839fd83e107a87938542f2b2a6b9c830371_1","message":"transfer removed, id: 3 active transfers: 2"}
{"level":"debug","time":"2023-08-18T10:12:28.292","sender":"SFTP","connection_id":"SFTP_b4c82839fd83e107a87938542f2b2a6b9c830371_1","message":"new cmd, method: Remove, sourcePath: \"/aaa.txt\", targetPath: \"\""}
{"level":"warn","time":"2023-08-18T10:12:28.294","sender":"SFTP","connection_id":"SFTP_b4c82839fd83e107a87938542f2b2a6b9c830371_1","message":"failed to remove a file/symlink \"C:\\\\YLC\\\\Temp\\\\home\\\\test\\\\aaa.txt\": remove C:\\YLC\\Temp\\home\\test\\aaa.txt: The process cannot access the file because it is being used by another process."}
```

**Comment by drakkan** [comment]
Please check that no other user (from your logs I see there are other 2 transfers) or process (e.g. antivirus) is accessing the file. However you are using a very old and unsupported SFTPGo version
