### ISSUE TITLE
[Bug]: WebAdmin Users page loads slowly for large amount of users

### ISSUE THREAD

**Issue by rafasc** [drakkan/sftpgo#1396]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

If the number of users in SFTPGo is sufficiently large, the WebAdmin Users page struggles to load.

This happens because SFTPGo loads all users regardless of pagination count.

**https://github.com/drakkan/sftpgo/blob/163662a65af76e76eff8e8459201b7327db82207/internal/httpd/webadmin.go#L2944-L2978**

Pagination client side:
https://github.com/drakkan/sftpgo/blob/main/templates/webadmin/users.html

### Steps to reproduce

1. Create 20K+ users.
2. Login in the Web Admin Interface.
3. Wait several seconds, sometimes more than a minute to load.
4. See the page mis-rendered while users are loading.
5. See this loading issue repeat every time we go back to the Users page.

### Expected behavior

Clicking the Users page should be responsive even with large amount of users present.

### SFTPGo version

2.5.4

### Data provider

tested with sqlite/mysql

### Installation method

Community Docker image

### Configuration

reproducible with no overrides.
users loaded with `SFTPGO_LOADDATA_FROM` but method of user creation should be irrelevant for this issue.

### Relevant log output

```shell
{
  "level": "info",
  "time": "2023-08-19T18:56:02.038",
  "sender": "httpd",
  "local_addr": "[::1]:8080",
  "method": "GET",
  "proto": "HTTP/1.1",
  "remote_addr": "[::1]:45416",
  "request_id": "ftp/ImjNlDyge6-000077",
  "uri": "http://localhost:8080/web/admin/users",
  "resp_status": 200,
  "resp_size": 18465247,
  "elapsed_ms": 38063
}
```

**Comment by drakkan** [comment]
This is planned as part of the UI refactoring for v2.6.x, no plans to improve the users page in v2.5.x (unless the request is from an Enterprise subscriber) sorry

**Comment by drakkan** [comment]
It should be fixed/improved in the new WebAdmin
