### ISSUE TITLE
Integrate ICAP client functionality for malware scanning

### ISSUE THREAD

**Issue by schindlerd** [drakkan/sftpgo#1397]
### Describe the solution you'd like

It would be great if you could implement an [ICAP](https://en.wikipedia.org/wiki/Internet_Content_Adaptation_Protocol) client functionality to enable malware scanning upon file upload.

I would imagine this to be a user based setting. Option for the ICAP server I would see under "Server Manager" - "Configurations" - "ICAP".

Looking forward to your thoughts about this! :blush

### Describe alternatives you've considered

An alternative might be using event manager and pre_upload functionality to trigger a python script (e.g. https://github.com/fim/icapclient3) that forwards file to ICAP scanning server.

### What are you using SFTPGo for?

Enterprise

**Comment by drakkan** [comment]
We can implement what you suggest or directly integrate antivirus protocols (for example the ClamAV protocol is quite simple).
Unfortunately there is not enough interest. In other words, even if many companies would use it if they could get the feature for free, no company wants to pay for this development (many design decisions are required to properly integrate something like this).  
We currently only accept feature requests from long-term project sponsors/support plan subscribers, sorry

**Comment by schindlerd** [comment]
I totally understand your feature request policy! It was worth a try 😅
