### ISSUE TITLE
[Bug]: Error when uploading large files with the Webinterface

### ISSUE THREAD

**Issue by andiarbeit12** [drakkan/sftpgo#1398]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

If I want to upload a large file (7.83gb) via the web interface, this breaks after some time with the error: "Error uploading files: NetworkError when attempting to fetch resource."
In the logs you can see that the jwt token has expired. Just before the post request is answered with 302 Found.

### Steps to reproduce

1.  Mount S3 Bucket for user on "/".
2. Set the UL Part Size for this user to 100MB.
3. Upload a file larger than 5GB.

### Expected behavior

The upload also works for larger files via the web interface.

### SFTPGo version

2.5.4

### Data provider

sqlite

### Installation method

Community Docker image

### Configuration
```
{
  "httpd": {
    "bindings": {
      "client_ip_header_depth": 0,
      "client_ip_proxy_header": "X-Forwarded-For"
    },
    "token_validation": 1
  }
}
```
### Relevant log output

```shell
{"level":"debug","time":"2023-08-21T12:34:34.792","sender":"httpd","message":"error getting jwt token: token is expired"}
{"level":"info","time":"2023-08-21T12:34:34.792","sender":"httpd","local_addr":"10.1.63.109:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"10.1.79.0:47280","request_id":"76870ecee8be7ce0a2d6ae3cd5488afa","uri":"http://sftpgo.validation.artcodix.cloud/web/client/file?path=%2Fmediastore%2Ftestfolder%2Ftest-file-7.83gb.wpress","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0","resp_status":302,"resp_size":0,"elapsed_ms":0}
```

### Additional info

To me it looks like the upload takes longer than the validity of the jwt token (20min) and during the refresh process the upload is aborted.

**Comment by drakkan** [comment]
```
{"level":"debug","time":"2023-08-22T20:24:23.813","sender":"httpd","local_addr":"[::1]:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"[::1]:59584","request_id":"p1/eEAQi2lkiW-000076","uri":"http://localhost:8080/web/client/file?path=%2F%2Fandroid-studio-ide-181.5056338-linux.zip","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36","resp_status":201,"resp_size":31,"elapsed_ms":2013368}
```

**Comment by lijogrg444** [comment]
sorry is this bug still on latest version?

**Comment by gabrielcossette** [comment]
I had this error using the latest version (2.6.2).

**Comment by ShyneTurtle** [comment]
Issue still present

**Comment by leopoldhub** [comment]
Issue still present, even with webdav protocol
