### ISSUE TITLE
Suffix to accounts created by role admin

### ISSUE THREAD

**Issue by glasserre** [drakkan/sftpgo#1401]
### Is your feature request related to a problem? Please describe.

Not linked to an issue

### Describe the solution you'd like

Feature to add autmatically a suffix to account created by a role admin.

In our case we delegate accounts creation by department/business. Sometimes, it happend 2 departments need to create an account for the same customer.

So the idea is to allow creation of 2 accounts : 
- customer@business1
- customer@business2

Suffix can be the Role name associated to the role admin or an extra field.

![image](https://github.com/drakkan/sftpgo/assets/2472365/06fda924-e4e0-4477-8100-24778f7898e5)

### What are you using SFTPGo for?

Enterprise

**Comment by drakkan** [comment]
We currently only accept feature requests from Enterprise Support Plan subscribers or equivalent, and we consider feature requests from Pro Support Plan subscribers, sorry

https://sftpgo.com/#pricing

In your case you already got the role feature for free, please stop asking, do you work for your company for free? If all users/companies behave like you, SFTPGo will die
