### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by Knkkyl** [drakkan/sftpgo#1403]
Hello,

we're using SFTPGo for transfer of (very) large files. It would be really useful if there was some kin of progress indicator during upload, ideally with a list of files currently being uploaded and how far they got. Could you implement something like this?

Thanks

_Originally posted by @blindmikesghost in https://github.com/drakkan/sftpgo/discussions/1352_

**Comment by drakkan** [comment]
Duplicate of #1352

**Comment by drakkan** [comment]
Please check our support policy, we prioritize requests from project sponsors/support plan subscribers sorry
