### ISSUE TITLE
filesystem storage - ftp/ftps

### ISSUE THREAD

**Issue by zvekan** [drakkan/sftpgo#1407]
### Is your feature request related to a problem? Please describe.

some old apps can use only ftp and don't know about ftps.

### Describe the solution you'd like

option to add ftps as storage option and this way old apps can still use just ftp option without encryption.

### Describe alternatives you've considered

I was searching maybe for some proxy or similar for windows but couldn't find solution.

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
This is unlikely to happen, sorry
