### ISSUE TITLE
Keep default configuration file on disk as a reference

### ISSUE THREAD

**Issue by djmattyg007** [drakkan/sftpgo#141]
It would be great if there was a default configuration file kept in `/usr/share/doc/sftpgo` as a reference. This can be useful as a quick way to cross-reference against the defaults, and also as a convenient way to get back to a default working state in case something goes wrong.

**Comment by sergiz** [comment]
What do you mean? You can organize files any way you want. There is no automatic installer that would put files somewhere for you.

**Comment by djmattyg007** [comment]
I'm using the AUR package that is put together by the developer:

https://aur.archlinux.org/packages/sftpgo/

**Comment by sergiz** [comment]
Ah, I didn't know it was put to package managers.

**Comment by drakkan** [comment]
OK, I'll update AUR package once #142 is fixed too, thanks

**Comment by drakkan** [comment]
fixed in the latest PKGBUILD
