### ISSUE TITLE
GCP load balancer and sftpgo

### ISSUE THREAD

**Issue by prakash-mh** [drakkan/sftpgo#1410]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

The application exhibits inconsistent behavior when utilizing the GCP load balancer, with attempts made using both Application Load Balancing (ALB) and SSL Load Balancing (SSL LB).

Configuration:

Provisioned a virtual machine (VM) and installed SFTPGO.
Set up a firewall rule to allow ingress traffic.
Established an instance group for high availability (HA).
Observed Behavior:
Clicking on any function within the application (e.g., using the '+' sign to add a new user) redirects users to the login screen. Occasionally, the login screen displays a "the form token is not valid" error before returning to the login screen.

Notably, when accessing the application's user interface directly through port forwarding or by assigning a public IP address to the VM, this issue does not manifest.

### Steps to reproduce

1. Create a new instance and install sftpgo
2. Create an image from the disk
3. Create and new template and an instance group
4. Reserve a static IP and google managed certificate
5. Deploy an application or SSL load balancer using the reserved static IP and cert
6. Setup admin password, create additional users [ you might want to use port forwarding using gcloud command]
7. Access the UI using the LB and right from login you can encounter the issue.

### Expected behavior

Anticipating the user interface to function in a manner consistent with direct access to the virtual machine.

### SFTPGo version

2.5.4

### Data provider

PostgreSQL

### Installation method

Community Deb package

### Configuration

{
    "common": {
      "idle_timeout": 15,
      "upload_mode": 0,
      "actions": {
        "execute_on": [],
        "execute_sync": [],
        "hook": ""
      },
      "setstat_mode": 0,
      "rename_mode": 0,
      "temp_path": "",
      "proxy_protocol": 0,
      "proxy_allowed": [],
      "proxy_skipped": [],
      "startup_hook": "",
      "post_connect_hook": "",
      "post_disconnect_hook": "",
      "data_retention_hook": "",
      "max_total_connections": 0,
      "max_per_host_connections": 20,
      "allowlist_status": 0,
      "allow_self_connections": 0,
      "defender": {
        "enabled": false,
        "driver": "memory",
        "ban_time": 30,
        "ban_time_increment": 50,
        "threshold": 15,
        "score_invalid": 2,
        "score_valid": 1,
        "score_limit_exceeded": 3,
        "score_no_auth": 0,
        "observation_time": 30,
        "entries_soft_limit": 100,
        "entries_hard_limit": 150
      },
      "rate_limiters": [
        {
          "average": 0,
          "period": 1000,
          "burst": 1,
          "type": 2,
          "protocols": [
            "SSH",
            "FTP",
            "DAV",
            "HTTP"
          ],
          "generate_defender_events": false,
          "entries_soft_limit": 100,
          "entries_hard_limit": 150
        }
      ]
    },
    "acme": {
      "domains": [],
      "email": "",
      "key_type": "4096",
      "certs_path": "certs",
      "ca_endpoint": "https://acme-v02.api.letsencrypt.org/directory",
      "renew_days": 30,
      "http01_challenge": {
        "port": 80,
        "proxy_header": "",
        "webroot": ""
      },
      "tls_alpn01_challenge": {
        "port": 0
      }
    },
    "sftpd": {
      "bindings": [
        {
          "port": 2022,
          "address": "",
          "apply_proxy_config": true
        }
      ],
      "max_auth_tries": 0,
      "banner": "",
      "host_keys": [],
      "host_certificates": [],
      "host_key_algorithms": [],
      "moduli": [],
      "kex_algorithms": ["curve25519-sha256", "curve25519-sha256@libssh.org", "ecdh-sha2-nistp256", "ecdh-sha2-nistp384", "ecdh-sha2-nistp521", "diffie-hellman-group14-sha1"]
,
      "ciphers": [],
      "macs": ["hmac-sha2-256-etm@openssh.com", "hmac-sha2-256","hmac-sha1","hmac-sha1-96"],
      "trusted_user_ca_keys": [],
      "revoked_user_certs_file": "",
      "login_banner_file": "",
      "enabled_ssh_commands": [
        "md5sum",
        "sha1sum",
        "sha256sum",
        "cd",
        "pwd",
        "scp"
      ],
      "keyboard_interactive_authentication": true,
      "keyboard_interactive_auth_hook": "",
      "password_authentication": true,
      "folder_prefix": ""
    },
    "ftpd": {
      "bindings": [
        {
          "port": 0,
          "address": "",
          "apply_proxy_config": true,
          "tls_mode": 0,
          "certificate_file": "",
          "certificate_key_file": "",
          "min_tls_version": 12,
          "force_passive_ip": "",
          "passive_ip_overrides": [],
          "passive_host": "",
          "client_auth_type": 0,
          "tls_cipher_suites": [],
          "passive_connections_security": 0,
          "active_connections_security": 0,
          "debug": false
        }
      ],
      "banner": "",
      "banner_file": "",
      "active_transfers_port_non_20": true,
      "passive_port_range": {
        "start": 50000,
        "end": 50100
      },
      "disable_active_mode": false,
      "enable_site": false,
      "hash_support": 0,
      "combine_support": 0,
      "certificate_file": "",
      "certificate_key_file": "",
      "ca_certificates": [],
      "ca_revocation_lists": []
    },
    "webdavd": {
      "bindings": [
        {
          "port": 0,
          "address": "",
          "enable_https": false,
          "certificate_file": "",
          "certificate_key_file": "",
          "min_tls_version": 12,
          "client_auth_type": 0,
          "tls_cipher_suites": [],
          "prefix": "",
          "proxy_allowed": [],
          "client_ip_proxy_header": "",
          "client_ip_header_depth": 0,
          "disable_www_auth_header": false
        }
      ],
      "certificate_file": "",
      "certificate_key_file": "",
      "ca_certificates": [],
      "ca_revocation_lists": [],
      "cors": {
        "enabled": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 0,
        "options_passthrough": false,
        "options_success_status": 0,
        "allow_private_network": false
      },
      "cache": {
        "users": {
          "expiration_time": 0,
          "max_size": 50
        },
        "mime_types": {
          "enabled": true,
          "max_size": 1000,
          "custom_mappings": []
        }
      }
    },
    "data_provider": {
      "driver": "postgresql",
      "name": "sftpgo",
      "host": "xxx.xxx.xxx.xxx",
      "port": 5432,
      "username": "########",
      "password": "########",
      "sslmode": 0,
      "disable_sni": false,
      "target_session_attrs": "",
      "root_cert": "",
      "client_cert": "",
      "client_key": "",
      "connection_string": "host='xxx.xxx.xxx.xxx' port=5432 dbname='#######' user='#######' password='##########' sslmode=disable connect_timeout=10",
      "sql_tables_prefix": "",
      "track_quota": 2,
      "delayed_quota_update": 0,
      "pool_size": 0,
      "users_base_dir": "data",
      "actions": {
        "execute_on": [],
        "execute_for": [],
        "hook": ""
      },
      "external_auth_hook": "",
      "external_auth_scope": 0,
      "pre_login_hook": "",
      "post_login_hook": "",
      "post_login_scope": 0,
      "check_password_hook": "",
      "check_password_scope": 0,
      "password_hashing": {
        "bcrypt_options": {
          "cost": 10
        },
        "argon2_options": {
          "memory": 65536,
          "iterations": 1,
          "parallelism": 2
        },
        "algo": "bcrypt"
      },
      "password_validation": {
        "admins": {
          "min_entropy": 0
        },
        "users": {
          "min_entropy": 0
        }
      },
      "password_caching": true,
      "update_mode": 0,
      "create_default_admin": false,
      "naming_rules": 5,
      "is_shared": 0,
      "node": {
        "host": "",
        "port": 0,
        "proto": "http"
      },
      "backups_path": "backups"
    },
    "httpd": {
      "bindings": [
        {
          "port": 8080,
          "address": "",
          "enable_web_admin": true,
          "enable_web_client": true,
          "enable_rest_api": true,
          "enabled_login_methods": 0,
          "enable_https": true,
          "certificate_file": "",
          "certificate_key_file": "",
          "min_tls_version": 12,
          "client_auth_type": 0,
          "tls_cipher_suites": [],
          "proxy_allowed": [],
          "client_ip_proxy_header": "",
          "client_ip_header_depth": 0,
          "hide_login_url": 0,
          "render_openapi": true,
          "web_client_integrations": [],
          "oidc": {
            "client_id": "",
            "client_secret": "",
            "config_url": "",
            "redirect_base_url": "",
            "scopes": [
              "openid",
              "profile",
              "email"
            ],
            "username_field": "",
            "role_field": "",
            "implicit_roles": false,
            "custom_fields": [],
            "insecure_skip_signature_check": false,
            "debug": false
          },
          "security": {
            "enabled": false,
            "allowed_hosts": [],
            "allowed_hosts_are_regex": false,
            "hosts_proxy_headers": [],
            "https_redirect": true,
            "https_host": "",
            "https_proxy_headers": [],
            "sts_seconds": 0,
            "sts_include_subdomains": false,
            "sts_preload": false,
            "content_type_nosniff": false,
            "content_security_policy": "",
            "permissions_policy": "",
            "cross_origin_opener_policy": "",
            "expect_ct_header": ""
          },
          "branding": {
            "web_admin": {
              "name": "",
              "short_name": "",
              "favicon_path": "",
              "logo_path": "",
              "login_image_path": "",
              "disclaimer_name": "",
              "disclaimer_path": "",
              "default_css": "",
              "extra_css": []
            },
            "web_client": {
              "name": "",
              "short_name": "",
              "favicon_path": "",
              "logo_path": "",
              "login_image_path": "",
              "disclaimer_name": "",
              "disclaimer_path": "",
              "default_css": "",
              "extra_css": []
            }
          }
        }
      ],
      "templates_path": "templates",
      "static_files_path": "static",
      "openapi_path": "openapi",
      "web_root": "",
      "certificate_file": "",
      "certificate_key_file": "",
      "ca_certificates": [],
      "ca_revocation_lists": [],
      "signing_passphrase": "",
      "token_validation": 0,
      "max_upload_file_size": 0,
      "cors": {
        "enabled": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 0,
        "options_passthrough": false,
        "options_success_status": 0,
        "allow_private_network": false
      },
      "setup": {
        "installation_code": "",
        "installation_code_hint": "Installation code"
      },
      "hide_support_link": false
    },
    "telemetry": {
      "bind_port": 0,
      "bind_address": "127.0.0.1",
      "enable_profiler": false,
      "auth_user_file": "",
      "certificate_file": "",
      "certificate_key_file": "",
      "min_tls_version": 12,
      "tls_cipher_suites": []
    },
    "http": {
      "timeout": 20,
      "retry_wait_min": 2,
      "retry_wait_max": 30,
      "retry_max": 3,
      "ca_certificates": [],
      "certificates": [],
      "skip_tls_verify": false,
      "headers": []
    },
    "command": {
      "timeout": 30,
      "env": [],
      "commands": []
    },
    "kms": {
      "secrets": {
        "url": "",
        "master_key": "",
        "master_key_path": ""
      }
    },
    "mfa": {
      "totp": [
        {
          "name": "Default",
          "issuer": "SFTPGo",
          "algo": "sha1"
        }
      ]
    },
    "smtp": {
      "host": "",
      "port": 25,
      "from": "",
      "user": "",
      "password": "",
      "auth_type": 0,
      "encryption": 0,
      "domain": "",
      "templates_path": "templates",
      "debug": 0,
      "oauth2": {
        "provider": 0,
        "tenant": "",
        "client_id": "",
        "client_secret": "",
        "refresh_token": ""
      }
    },
    "plugins": []
  }

### What are you using SFTPGo for?

Small business (3-person firm with file exchange?)

**Comment by jcjones87** [comment]
I don't think this is a bug. I'm running SFTPGo in GKE. You probably just need to configure session/cookie affinity in the LB. 

https://cloud.google.com/load-balancing/docs/backend-service#generated_cookie_affinity

**Comment by MaxWinterstein** [comment]
Just dropping my 2 cents here, for anyone coming across:

When running behind `gke gateway api` I had similar issues. Logs showed that GCP was in fact using multiple LoadBalancers to acces the sftpgo backend, and therefore the remote IP always changed and e.g. token broke 

```
"sender":"httpd","message":"the token with id \"cu7b8r7f9qhs73cq0mng\" is not valid for the ip address \"10.18.2.2\""}
```

I use some helm chart to deploy it, so for me the fix was to tell it to accept proxy headers like this:

```yaml
    env:
      SFTPGO_HTTPD__BINDINGS__0__CLIENT_IP_PROXY_HEADER: "X-Forwarded-For"
      SFTPGO_HTTPD__BINDINGS__0__PROXY_ALLOWED: "0.0.0.0/0"
    config:
      common:
        proxy_protocol: 1
        proxy_allowed: "0.0.0.0/0"
```
