### ISSUE TITLE
Equivalent of ssh -vvv debug

### ISSUE THREAD

**Issue by marcinkubica** [drakkan/sftpgo#1412]
### Is your feature request related to a problem? Please describe.

I have client using jsch which can't connect and have no way to determine why. 
```
failed to accept an incoming connection from ip "w.x.y.z": ssh: disconnect, reason 3: com.jcraft.jsch.JSchException: verify: false
```

### Describe the solution you'd like

sftpgo to actually tell why it failed to accept the connection. Verbosity aking to `ssh -vvv` is useful.

### Describe alternatives you've considered

I will have to drop sftpgo and use linux, but I don't want to.

### What are you using SFTPGo for?

Medium business

### Additional context

Loving the app so far. Would like to use it.

**Comment by marcinkubica** [comment]
@drakkan I appreciate your quick closing of this. Does it mean sftpgo has no ability to inform why it's not accepting a connection?

**Comment by drakkan** [comment]
This is just a support request, please check our support policy. Thank you

**Comment by marcinkubica** [comment]
Thanks @drakkan . Does it mean I need to pay for the support to receive information on why sftpgo fails to accept the connection?
