### ISSUE TITLE
Default static and template files shouldn't be in /var/lib

### ISSUE THREAD

**Issue by djmattyg007** [drakkan/sftpgo#142]
It's uncommon for packages to place files into `/var`. Typically this is reserved for runtime generated files. Typically, packages put files like this into `/usr` - usually `/usr/lib` or `/usr/share`.

`/var/lib` would actually be a much more appropriate place for the credentials path, rather than a subdirectory of the config directory (which is usually `/etc`). It's usually frowned upon for program to write to `/etc` (unless the point of the program is specifically to manage configuration).

**Comment by drakkan** [comment]
Hi,

you are probably right, could you please write a concrete proposal here or even better send a pull request to update this [doc](https://github.com/drakkan/sftpgo/blob/master/docs/service.md)? I'll update AUR package once this issue get fixed, thanks!

**Comment by drakkan** [comment]
Hi,

I think that we should use these paths:

- `/usr/share/sftpgo/static`
- `/usr/share/sftpgo/templates`


the oher paths used in AUR package should be fine

**Comment by drakkan** [comment]
fixed in the latest PKKBUILD
