### ISSUE TITLE
Pre Calculated File Checksums

### ISSUE THREAD

**Issue by Belal-Elshinnawey** [drakkan/sftpgo#1424]
### Is your feature request related to a problem? Please describe.

I use SFTPGO as a firmware upgrade source for my devices. I push compiled binaries and my devices fetch these binary files as new firmware. Currently there is no way for my devices to check if the firmware file is downloaded correctly without corruption, the only way to test is through running the file.

### Describe the solution you'd like

I would like a way for sftpgo to automatically calculate file checksum and serve it over the REST API so the downloading device can calculate the checksum while downloading then confirm it with the REST API.

### Describe alternatives you've considered

I considered having a companion file that contains the checksum of the bin file, or even adding the checksum to the file path so my device can extract the checksum while downloading. 

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Calculating checksum is already supported. To be honest, this request seems a bit excessive for a home use case...

**Comment by Belal-Elshinnawey** [comment]
are checksums exposed through the rest api? I couldn't find them in the docs.
