### ISSUE TITLE
search for files in all subfolders

### ISSUE THREAD

**Issue by osadrac** [drakkan/sftpgo#1425]
### Is your feature request related to a problem? Please describe.

It's not a problem, but it would greatly improve the use of searching for stored files

### Describe the solution you'd like

Would it be possible for the DataTable search to list all the files in the subfolders? Now the search only works in the viewed folder

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Hello,

this means move the search feature server side and recurse all the subdirectory. It is unlikely to happen, sorry

**Comment by osadrac** [comment]
I understand, it would be a very useful function also for companies that use it as a file server, I'm new to Go, I'll take a look at what it would look like, if I find an alternative I'll send a PR. Thanks for the answer and congratulations on the project
