### ISSUE TITLE
Exit code 0 when host keys cannot be created

### ISSUE THREAD

**Issue by djmattyg007** [drakkan/sftpgo#143]
I observed sftpgo exiting with a non-error status code after the following entries were logged to the journal:

```
{"level":"info","time":"2020-07-09T18:48:05.854","sender":"sftpd","connection_id":"","message":"No host keys configured and \"/etc/sftpgo/id_ecdsa\" does not exist; try to create a new host key"}
{"level":"error","time":"2020-07-09T18:48:05.865","sender":"service","connection_id":"","message":"could not start SFTP server: open /etc/sftpgo/id_ecdsa: permission denied"}
```

As a side-note, this error occurred because I took away write-permissions for `sftpgo` to `/etc/sftpgo`. It would be nice if these keys could be created using a CLI command (along the same lines as the `initprovider` command), so that I could do it once at setup time and then keep sftpgo from writing to directories that it shouldn't need to.

**Comment by drakkan** [comment]
> I observed sftpgo exiting with a non-error status code after the following entries were logged to the journal:
> 
> ```
> {"level":"info","time":"2020-07-09T18:48:05.854","sender":"sftpd","connection_id":"","message":"No host keys configured and \"/etc/sftpgo/id_ecdsa\" does not exist; try to create a new host key"}
> {"level":"error","time":"2020-07-09T18:48:05.865","sender":"service","connection_id":"","message":"could not start SFTP server: open /etc/sftpgo/id_ecdsa: permission denied"}
> ```
> 

thanks for reporting I'll fix this issue later today

> As a side-note, this error occurred because I took away write-permissions for `sftpgo` to `/etc/sftpgo`. It would be nice if these keys could be created using a CLI command (along the same lines as the `initprovider` command), so that I could do it once at setup time and then keep sftpgo from writing to directories that it shouldn't need to.

You can use `ssh-keygen` if you want to generate the keys yourself. For example we don't support `ed25519` keys generation but if you generate such keys using `ssh-keygen` they will work fine
