### ISSUE TITLE
[Bug]: Sharing a folder with a space at the end of the name prevents sharing links from working properly

### ISSUE THREAD

**Issue by MickaelAdhoc** [drakkan/sftpgo#1431]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

If you try to share an entire folder, but it ends with a space character, the links created will not work

### Steps to reproduce

1. Create a folder ends with space
2. Create a share
3. Access one of the three links created, none will be functional.

### Expected behavior

Let the links work

### SFTPGo version

lastest

### Data provider

sqlite

### Installation method

Community Docker image

### Configuration

same thing on vanilla

**Comment by drakkan** [comment]
It is a one line fix, feel free to send a patch. Thank you. If you are able to run a fork you should also be able to fix bugs :)
