### ISSUE TITLE
[EventManager]: Event Action of type command not being executed sucessfully from SFTPgo 

### ISSUE THREAD

**Issue by felipem1210** [drakkan/sftpgo#1440]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hello @drakkan on first instance, thanks for this amazing project.

In our company my team is implementing this tool as we manage a lot of SFTP servers. We now got into a server which have cronjobs to move files from the SFTP server to s3 buckets.I checked out that the Event Manager module fulfil this. 

Now I'm stuck trying to make it work, my scenario is the following:

I have a rule to execute an action when a user upload a file. The rule is okey, I have seen in logs is triggered. The problem is in the action, I'm using the type "command" and I'm executing a golang script that I added to the Docker image of SFTPGO.

The issue I'm addressing is because my script is not working when the event is triggered, and I'm not able to see any of the logs I have added on my script to troubleshoot issues. Here is the log line from SFTPgo I see:
```
unable to execute action "Test" for rule "Test", elapsed 529.659592ms, err: action "Test" failed: exit status 1
```
Looking in code I see that [this](https://github.com/drakkan/sftpgo/blob/main/internal/common/eventmanager.go#L1473-L1474) line is the one printing the log line I'm seeing but I need to be able to see the logging of my script to troubleshoot why doesn't work.

An additional troubleshoot I did is to run the script manually on the container and it works, so that is a probe that something is wrong when the EventManager executes the script. An additional information I can give is that my script is using environment variables and I'm passing them through the EventManager

Thanks in advance

### Steps to reproduce

1. Add a script that uses envars on sftpgo
2. Create an EventAction of type command that runs this script and use it on an EventRule
3. Avoid adding one of the envars needed on the script to make the script fail.
4. Trigger the action

### Expected behavior

The logs of SFTPgo should show the reason why the EventAction command failed

### SFTPGo version

2.5.4

### Data provider

mysql

### Installation method

Community Docker image

### Configuration

config

### What are you using SFTPGo for?

Enterprise

**Comment by drakkan** [comment]
I'm sorry but we don't provide free support any longer, please check our support policy.
It is unlikely this is a bug (it works fine for me), anyway feel free to send a PR if you find something wrong on the SFTPGo side. Thank you

**Comment by felipem1210** [comment]
Thanks, I ended up writing a file with the logs of my script.
Now I'm trying to get this question answered. https://github.com/drakkan/sftpgo/discussions/1442
