### ISSUE TITLE
[Bug]: API VALIDATION Error

### ISSUE THREAD

**Issue by mcordes92** [drakkan/sftpgo#1444]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hello, I have created an API key which also works under the user, but then I cannot carry out an update user via API as it then tells me

{
    "error": "Validation error: please grant some permissions to this user",
    "message": ""
}

the user I use for the API has all rights

### Steps to reproduce

It's hard to say because it worked until the last update and, strangely enough, it doesn't affect all endpoints

### Expected behavior

I Dont know

### SFTPGo version

2.5.4

### Data provider

sqlite

### Installation method

Community Deb package

### Configuration

Nothting in the Config only create API Keys

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment]
Hello,

this seems more like a support request than a bug.
In any case we no longer provide free support, please check our support policy. If, after further investigation, you can confirm that this is a bug, please submit a PR. Thank you

**Comment by mcordes92** [comment]
I think this is a bug because it worked perfectly with the previous version

**Comment by drakkan** [comment]
> I think this is a bug because it worked perfectly with the previous version

ok, just bisect and found the commit to blame :smile: Thank you!

**Comment by mcordes92** [comment]
I don't understand this right now because it worked in the previous version, I didn't change anything in the configuration. So if I see it correctly, this is a bug and has nothing to do with free support.

**Comment by drakkan** [comment]
I think this is a problem on your end that occurs with any version of SFTPGo. Feel free to investigate further and provide a fix if you disagree. Thank you

**Comment by mcordes92** [comment]
How can this be a problem on my side if I haven't changed anything in the config and it was still working before the update

**Comment by drakkan** [comment]
> How can this be a problem on my side if I haven't changed anything in the config and it was still working before the update

just downgrade to the previous version. I guess you will see the same error.

You haven't even provided a reproducer, you're just sharing an error that indicates a problem on your end.

Please stop demanding bug fixes and/or support. You are using open source software for free. I have invited you several times to investigate the issue and provide a PR (according to the shared error it is very unlikely to be a bug). Thanks for understanding.
