### ISSUE TITLE
Mikrotik Container compatablity

### ISSUE THREAD

**Issue by elico** [drakkan/sftpgo#1452]
### Is your feature request related to a problem? Please describe.

I am running a Mikrotik RouterOS HAP ac3 which has container support.
I am trying to install a gosftp container so it can run ontop of the Mikrotik device.
The container doesn't start.
I tried to run an alpine container and to run the binary from the releases page and I get the next output:
```
 ldd armv7/sftpgo
        /lib/ld-linux-armhf.so.3 (0x76f6e000)
Error loading shared library libresolv.so.2: No such file or directory (needed by armv7/sftpgo)
        libdl.so.2 => /lib/ld-linux-armhf.so.3 (0x76f6e000)
        libpthread.so.0 => /lib/ld-linux-armhf.so.3 (0x76f6e000)
        libc.so.6 => /lib/ld-linux-armhf.so.3 (0x76f6e000)
Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by armv7/sftpgo)
Error relocating armv7/sftpgo: __memset_chk: symbol not found
Error relocating armv7/sftpgo: __res_search: symbol not found
Error relocating armv7/sftpgo: __memcpy_chk: symbol not found
Error relocating armv7/sftpgo: __vfprintf_chk: symbol not found
Error relocating armv7/sftpgo: __fprintf_chk: symbol not found
```

To install the container on a mikrotik device you can use the next commands:
```
/interface/bridge/add name=dockers
/ip/address/add address=172.21.0.254/24 interface=dockers

/interface/veth/add name=veth22 address=172.21.0.22/24 gateway=172.21.0.254
/interface/bridge/port add bridge=dockers interface=veth22

/container/config/set registry-url=https://registry-1.docker.io tmpdir=usb1-part1/pull

/container/envs/add name=gpsftp_envs key=TZ value="Asia/Jerusalem"

/container/envs/add name=gpsftp_envs key=IP value="172.21.0.22"

/container mounts add dst=/srv/sftpgo name=gosftp_data src=usb1-part1/gosftp_data

/container mounts add dst=/var/lib/sftpgo name=gosftp_home src=usb1-part1/gosftp_home

/container/add mounts=gosftp_data,gosftp_home dns=172.21.0.254 remote-image=drakkan/sftpgo:latest interface=veth22 root-dir=usb1-part1/gosftp_root envlist=gpsftp_envs start-on-boot=yes
```

To run my alpine based ssh container you can use then next commands:
```
/interface/bridge/add name=dockers
/ip/address/add address=172.21.0.254/24 interface=dockers

/interface/veth/add name=veth122 address=172.21.0.122/24 gateway=172.21.0.254
/interface/bridge/port add bridge=dockers interface=veth122

/container/config/set registry-url=https://registry-1.docker.io tmpdir=usb1-part1/pull

/container/envs/add name=ssh_envs key=TZ value="Asia/Jerusalem"
/container/envs/add name=ssh_envs key=ADD_ELIEZER_KEYS value="0"
/container/envs/add name=ssh_envs key=DISABLE_PASSWORD_AUTHENTICATION value="1"
/container/envs/add name=ssh_envs key=EXTRA_AUTHORIZED_KEYS_URL_ADMIN value="https://gist.githubusercontent.com/elico/xyz/authorized_keys"

/container/add dns=172.21.0.254 remote-image=elicro/managment-ssh:latest interface=veth122 root-dir=usb1-part1/managment-ssh envlist=ssh_envs start-on-boot=yes
```

### Describe the solution you'd like

To be able to just run the existing container of gosftp or have a static binary for testing.

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional context

There are many Mikrotik devices and it is very helpful to have gosftp as a service that can be installed on these devices.

**Comment by drakkan** [comment]
Hello,

I don't have access to a Mikrotik device, but the steps above are clearly wrong: you're trying to run a sftpgo executable built for glibc on musl libc. Try running the SFTPGo alpine image directly, copy the binary from there or build yourself a static sftpgo binary (we provide custom build only for enterprise plan subscribers)

**Comment by elico** [comment]
@drakkan just for general knowledge Mikrotik provides CHR  VM's images for hyper-v and other Virtualization platforms for testing.

I know how to build the binary however I was pretty sure that there is a static binary release.
The alpine container works great.

If there is an option to publish the bundle release of static binaries it would be great.

Thanks!
