### ISSUE TITLE
Implement possibility to get HTTP headers from file in container

### ISSUE THREAD

**Issue by martin31821** [drakkan/sftpgo#1454]
### Is your feature request related to a problem? Please describe.

I'm using SFTPgo in kubernetes and want to use the k8s service account token to authenticate to an external API on file upload.

Currently, this is not easily possible, since there is no native possibility to use the contents of a file as value for a HTTP header.

### Describe the solution you'd like

I'm proposing a change in the way http headers are handled:

1. Introduce a flag for the HTTP header to indicate whether the header is a template.
2. If this flag is set, run the HTTP header value through `text/template` and provide a `file()` function that can read a file from disk.

### Describe alternatives you've considered

I'm currently working around this by building an own image and executing curl.

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS), Professional user, 1 person business

### Additional context

If you approve my proposed solution, I'd be willing to contribute the feature to both sftpgo and the respective terraform provider.

**Comment by drakkan** [comment]
This is too specific sorry, maybe in the future we can support env vars also for HTTP requests, so you can set the appropriate env vars using a startup hook or something like this.
