### ISSUE TITLE
Export/Import from Data Provider

### ISSUE THREAD

**Issue by chanster** [drakkan/sftpgo#146]
Provide a way to export the data from a provider in order to import to another provider.

**Comment by drakkan** [comment]
Hi,

this should be already possibile using the dumpdata/loaddata REST API. If you don't want to call the REST API yourself you can use the example REST API CLI, please take a look [here](https://github.com/drakkan/sftpgo/blob/master/examples/rest-api-cli/README.md#backup-data)

**Comment by chanster** [comment]
Ah, thanks, I missed the part of the documentation.

**Comment by drakkan** [comment]
No problem. Documentation improvements are alway welcome. If you think the docs can be improved please send a pull request, thank you!
