### ISSUE TITLE
New WebClient UI

### ISSUE THREAD

**Issue by drakkan** [drakkan/sftpgo#1465]
Hi all,

a new WebClient UI is now availble.  You can test it using the current development version.
We hope you find this new user interface more modern and easier to use. It also includes a dark mode.

Please note that this is a work in progress, we are still working with a company specializing in UI/UX to improve it, the final version that will be included in v2.6.0 may differ.

Any constructive feedback is appreciated. 

Thank you to [KeenThemes](https://keenthemes.com/) for granting us a custom license to use their amazing [Mega Bundle](https://keenthemes.com/products/templates-mega-bundle) for SFTPGo UI.

The theme is proprietary, this means:

- KeenThemes HTML/CSS/JS components are allowed for use only within the SFTPGo product and restricted to be used in a resealable HTML template that can compete with KeenThemes products anyhow.
- The SFTPGo WebClient UI (HTML, CSS and JS components) based on this theme is allowed for use only within the SFTPGo product and therefore cannot be used in derivative works/products without an explicit grant from the [SFTPGo Team](mailto:support@sftpgo.com).

**Comment by drakkan** [comment]
Experimental support for localizations has been added to WebClient.

The current implementation lacks some features, for example it is not currently possible to pass a localized string with arguments from the backend.

This is just a test, we are not sure if this feature will be included in v2.6.0. The effort required is not low, as you can see from the related commits, and we are not sure if it is worth it. This feature was only requested by a German company (which does not support the project in any way) and from some Chinese users (SFTPGo has gotten about $5 in four years from China so far, even after allowing them to use Alipay which was the common excuse for not supporting the project).

Localization is an ongoing effort, we need to extract new strings as we add new code, review/merge the contributed localizations and also sooner or later we should add RTL support etc..

**Comment by jechols** [comment]
I'm not sure if this is the right place to ask, so if you delete this I won't be offended - has there been any attention to accessibility (as in WCAG) in this new UI?

**Comment by drakkan** [comment]
> I'm not sure if this is the right place to ask, so if you delete this I won't be offended - has there been any attention to accessibility (as in WCAG) in this new UI?

This is the right place to ask and you asked a good question. 

Unfortunately I didn't consider accessibility in my requirements matrix. I will check with the theme authors but I think this feature will not be supported, at least in the first version, sorry.

**Comment by jechols** [comment]
No worries. Projects like this are often exempt because there are alternate ways to do almost everything (via APIs and command-line SFTP access and such). But I figured I'd ask at least - always easier to convince people to use tech at the university level when it's accessible even when it's not strictly required.

Note that if the authors didn't design for accessibility from the get-go, fixing it later could be a pretty large burden, so it might not be worth trying to remediate until you have another theme refresh/rewrite.

**Comment by patrickap** [comment]
Great, I'm excited to see progress being made. I really like the new interface. Is there any way I can help with testing? I've launched the latest development build, but the file viewer doesn't working on my end. Anyway, thanks for your efforts!

**Comment by drakkan** [comment]
> Great, I'm excited to see progress being made. I really like the new interface. Is there any way I can help with testing? I've launched the latest development build, but the file viewer doesn't work on my end. Anyway, thanks for your efforts!

Yes, testing and constructive feedback are appreciated. Just use one of the edge images or download a build artifact from the action page, the file manager should work. 
We just received the first feedback from our UI/UX consultants, we will push some changes to apply their suggestions (at least partially) in the next few days. We will also try to improve accessibility as much as possible

**Comment by drakkan** [comment]
@jechols after implementing the first suggestions from our UI/UX consultants if I analyze the login page using Lighthouse we have this result

![Schermata del 2023-12-26 11-57-11](https://github.com/drakkan/sftpgo/assets/553263/9bfb8b0b-ff34-4f23-a66f-bc94f2e2aec7)

In addition to fixing the problems reported in Lighthouse also for other pages when possible (sometimes the problems are found in external libraries) do you have any other suggestions for improving accessibility? Thank you

**Comment by patrickap** [comment]
Hey @drakkan!

It turned out my browser was set to a different language, causing the translation to not load properly. A fallback would be great for situations like this where no translation is available.

I'm really liking the new look so far! However, I do have a couple of suggestions for improvement:

1. For file types like JPG, it would be awesome if clicking on the file name opened the image in a preview instead of an immediate download. Maybe offer the download option in the context menu or in the image viewer.

2. Consider making the context menu accessible through a right-click on the entire list entry for better usability.

3. It'd be practical to have infinite scroll for the file manager, especially when dealing with lots of files or folders, so we don't have to navigate through pagination.

Thanks for your efforts!

**Comment by drakkan** [comment]
> Hey @drakkan!
> 

Hi @patrickap, thank you for your testing

> It turned out my browser was set to a different language, causing the translation to not load properly. A fallback would be great for situations like this where no translation is available.
> 

The fallback should already be [working](https://github.com/drakkan/sftpgo/blob/a65e7782def4a847cff531b1252f6d49ea3af4fd/templates/common/base.html#L173).

If I remove all the languages in my browser and I only leave `es`. I see the following requests

- GET `http://localhost:8080/static/locales/es/translation.json`, this returns 404
- GET `http://localhost:8080/static/locales/en/translation.json`, this works and English is used 

> I'm really liking the new look so far! However, I do have a couple of suggestions for improvement:
> 
> 1. For file types like JPG, it would be awesome if clicking on the file name opened the image in a preview instead of an immediate download. Maybe offer the download option in the context menu or in the image viewer.

Preview is available using the eye icon. I will evaluate your suggestion but we should have similar behavior for all file types and preview is not always possible, this is why preview is not the default action.

> 2. Perhaps it would also be beneficial to make the entire list entry clickable, not just the text.
> 3. Consider making the context menu accessible through a right-click on the entire list entry for better usability.
> 4. It'd be practical to have infinite scroll for the file manager, especially when dealing with lots of files or folders, so we don't have to navigate through pagination.
> 

I'll evaluate these suggestions with the help of our UX consultants. Infinite scrolling was evaluated in the past but wasn't easy to implement, I'll check again. Thank you!

> Thanks for your efforts!

**Comment by patrickap** [comment]
> Preview is available using the eye icon. I will evaluate your suggestion but we > should have similar behavior for all file types and preview is not always possible, this is why preview is not the default action.

A uniform behaviour could also be achieved by displaying a viewer when clicking on files without a preview, informing the user that no preview is currently available and offering a download link.

> Infinite scrolling was evaluated in the past but wasn't easy to implement (for example the image gallery will only work with the images you can see in the list, not with the hidden ones and the page loading may slow down if you initialize the image gallery even with non-visible images)

I would not initialise the File Manager and the File Viewer with everything. Pagination is already implemented. If you reach the end of the already loaded area (whether by scrolling the list or navigating through the images), the next page could be loaded automatically.

**Comment by jechols** [comment]
> In addition to fixing the problems reported in Lighthouse also for other pages when possible (sometimes the problems are found in external libraries) do you have any other suggestions for improving accessibility? Thank you

The design team didn't start the new UI with accessibility in mind (and it doesn't look like they have much a11y experience to begin with), so bear in mind that there just isn't much to be done without a considerable amount of effort. It really isn't worth your time until you do another refresh of the UI.

I want to reiterate this: **SFTPGo most likely falls under one of the "exempt" categories** for accessibility. I think that every function it provides has alternatives. The admin side has a lot of APIs, and the client side is basically just gravy: people can just set up WinSCP or Filezilla or something. In a perfect world, SFTPGo's web UI would be 100% conformant, but even if I ran the project it wouldn't be my top priority.

In any case, you did ask, so here's a small list of accessibility issues:

- There aren't many meaningful headings in terms of describing the "outline" of a page (h1, h2, etc) - they seem mostly used for formatting. This means pages don't have a lot of obvious structure, and it's harder for screen-reader users to navigate, as they often rely on headings to (a) "see" the layout, and (b) jump from section to section.
- A lot of places hide or "mute" keyboard focus, so it's hard to tell when you're a keyboard-only user where the focus goes when hitting "tab".
- Some buttons don't work with the keyboard, like the "dark" mode button or the profile button.
- There's no "main" landmark, which can be helpful for screen-reader users to navigate to the content, allowing them to skip the repeated links in the sidebar
- Similarly, there is no "skip" link, which is useful for sighted keyboard-only users to get to the main content
- There are some low-contrast elements which are difficult for users to see
- There are still some fields with no associated label, especially in the "my profile" area
- There are occasionally buttons that have no text, just an icon (like the various "delete" buttons that are just "trash" icons)

I could probably do a major deep-dive and uncover *a whole lot more*, but again, it's really not worth your time to look over it. Next time you do a theme refresh, I'd say just look for designers who know WCAG AA standards and can show you implementations of the same.

Accessibility is a specialized skill, just like programming. When people know it well, they can make a project accessible from the beginning without taking much additional time. Those who don't learn it, on the other hand, often make things worse by trying to shim it in after the fact.

**Comment by drakkan** [comment]
@patrickap your request makes sense. I think we need a custom "multiviewer" that allows to show the preview for all supported file formats and optionally download the file, once we have it we can also remove pagination.
Anyway this change is limited to the FileManager and can also be done later. I think we now have a solid basis to rewrite the WebAdmin too, I just have to decide whether to keep multi-language support or not. I want to prioritize the rewrite of WebAdmin now so I can cut a release, besides the new UI there are many other changes that people are waiting for in the development version and this development cycle is taking forever.

@jechols thanks for the detailed explanation, much appreciated, I asked the authors of KeenTheme and this is their answer

> At the moment the accessibility is not fully supported. We may support it in the near future.

I will wait for this to happen, this will mean a bigger refactoring later because now we still have to rewrite the WebAdmin but trying to add this support now would probably make things worse as you wrote above

**Comment by CaptainLoop** [comment]
Sorry for my noob question but .where can I find the current development version?

**Comment by drakkan** [comment]
> Sorry for my noob question but .where can I find the current development version?

you can use an edge based docker image or download a recent build artifact from the Actions page. You can find the last build artifacts [here](https://github.com/drakkan/sftpgo/actions/runs/7479731256)

**Comment by CaptainLoop** [comment]
Thanks! I test it in the next couple of days. I will write about my experience.

**Comment by drakkan** [comment]
Also the WebAdmin was migrated to the new UI.

**Comment by drakkan** [comment]
The new theme is ready for the first release, thank you all for the suggestions, we will take them into account for future updates
