### ISSUE TITLE
Support for WebDAV

### ISSUE THREAD

**Issue by helmut72** [drakkan/sftpgo#147]
Please add support for WebDAV. This will fulfill the 3 common standards (SFTP, FTPS, WebDAV) for transfering files over the Internet.
https://github.com/drakkan/sftpgo/issues/46#issuecomment-657410741
> and in future other protocols

For WebDAV, there isn't any TLS connection needed, because nearly all use a Reverse Proxy with TLS in front of any Webservice. To use one IP for many Webservices.

Maybe it's possible to use a library that Rclone use:
https://rclone.org/commands/rclone_serve_webdav/

**Comment by drakkan** [comment]
Hi,

webdav support is planned but I don't have a schedule for now. It could take a while as for FTP that I'm finalizing.

TLS should be trivial to add.

The library to use is this [one](https://pkg.go.dev/golang.org/x/net/webdav?tab=doc), I think `rclone` use it too.

Do you use webdav already? Which kind of authentication do you use? Basic, digest, client certificate, other? Thanks

**Comment by helmut72** [comment]
Thanks 👍 

> Which kind of authentication do you use?
Basic, because my current WebDAV server (Apache) use LDAP for it's user backend.

**Comment by drakkan** [comment]
Hi,

I'm working on this, I think that I don't include support for `dead properties`, at least in the initial version, do you use them? Or do you use WebDav for file trasfers only? 

I have to decide what is the best way to add `dead properties` support, probably the cleanest way is to store them inside the data provider, I'll better analyze this feature after the initial version.

Anyway WebDav is a quite complex/heavy protocol, for example listing a directory with a lot of files will be much slower compared to SFTP/FTP: the WebDav client will do a lot of `PROPFIND` requests (tested only using Nautilus for now).

Can you please tell me which WebDav clients you use? So I'll test them too, thank you

**Comment by helmut72** [comment]
My primary use case/Idea is synchronize my Notes (Markdown files) with 1Writer (iOS) and using SSHFS on my Desktop. Means, SFTP and WebDAV need the same folder share. And yes, using a WebDAV share is sometimes slow on the Desktop. That's the reason I prefer SSHFS.

Btw, to have my Notes also Offline on my Desktop, something like Mutagen comes to my mind:
https://mutagen.io
But Mutagen need it's own helper app to sync in both directions. Mutagen is also developed in Golang ;)

**Comment by drakkan** [comment]
Hi,

WebDAV is now supported, it should work for your use case, please take a look [here](https://github.com/drakkan/sftpgo/blob/master/docs/webdav.md) for more info, thank you

**Comment by helmut72** [comment]
Hi,

thank you! Compiled with Go 1.15. SFTP works for the same test user, but WebDAV shows this error:
{"level":"info","time":"2020-08-23T23:06:44.804","sender":"httpd","method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"client_ip:52172","request_id":"d870e8f5b56d/t8nbTVdukN-000059","uri":"http://ip_of_sftpgo:5040/test","user_agent":"ForkLift/3.4","resp_status":405,"resp_size":57,"elapsed_ms":0}

**Comment by drakkan** [comment]
Hi,

I had these unhelpful errors while developing too. I tried to document [them](https://github.com/drakkan/sftpgo/blob/master/docs/webdav.md).

Maybe the issue is this one:

"""
if an object within a directory cannot be accessed, for example due to OS permissions issues or because is a missing mapped path for a virtual folder, the directory listing will fail. In SFTP/FTP the directory listing will succeed and you'll only get an error if you try to access to the problematic file/directory
"""

please try to start with an empty folder and if it works add a single file and so on, to understand if you have issues with a specific file/directory. I'll try to improve the library error messages in future, thank you

**Comment by helmut72** [comment]
It's the login that doesn't work. SFTP works ok. Users home folder is empty.

**Comment by drakkan** [comment]
Ok,  can you please enable verbose logging and post some more log lines? I mean something like this:

```
{"level":"debug","time":"2020-08-24T15:57:11.591","sender":"DAV","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","message":"connection added, num open connections: 1"}
{"level":"info","time":"2020-08-24T15:57:11.591","sender":"DAV","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","message":"User id: 5032, logged in with WebDAV, method: GET, username: \"b\", home_dir: \"/tmp/test_home\" remote addr: \"127.0.0.1:44048\""}
{"level":"debug","time":"2020-08-24T15:57:11.605","sender":"dataprovider_sqlite","connection_id":"","message":"last login updated for user \"b\""}
{"level":"debug","time":"2020-08-24T15:57:11.605","sender":"DAV","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","message":"transfer added, id: 1, active transfers: 1"}
{"level":"info","time":"2020-08-24T15:57:11.605","sender":"Download","elapsed_ms":0,"size_bytes":0,"username":"b","file_path":"/tmp/test_home","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","protocol":"DAV"}
{"level":"debug","time":"2020-08-24T15:57:11.605","sender":"DAV","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","message":"transfer removed, id: 1 active transfers: 0"}
{"level":"debug","time":"2020-08-24T15:57:11.605","sender":"DAV","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","message":"transfer added, id: 2, active transfers: 1"}
{"level":"info","time":"2020-08-24T15:57:11.606","sender":"Download","elapsed_ms":0,"size_bytes":0,"username":"b","file_path":"/tmp/test_home","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","protocol":"DAV"}
{"level":"debug","time":"2020-08-24T15:57:11.606","sender":"DAV","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","message":"transfer removed, id: 2 active transfers: 0"}
{"level":"debug","time":"2020-08-24T15:57:11.606","sender":"DAV","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","message":"transfer added, id: 3, active transfers: 1"}
{"level":"info","time":"2020-08-24T15:57:11.606","sender":"Download","elapsed_ms":0,"size_bytes":0,"username":"b","file_path":"/tmp/test_home","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","protocol":"DAV"}
{"level":"debug","time":"2020-08-24T15:57:11.606","sender":"DAV","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","message":"transfer removed, id: 3 active transfers: 0"}
{"level":"info","time":"2020-08-24T15:57:11.606","sender":"webdavd","elapsed_ms":14,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"127.0.0.1:44048","request_id":"bt1sedvcdrpdqgsclqtg","uri":"http://127.0.0.1:9090/b","user_agent":"curl/7.72.0"}
{"level":"debug","time":"2020-08-24T15:57:11.606","sender":"DAV","connection_id":"DAV_bt1sedvcdrpdqgsclqtg","message":"connection removed, num open connections: 0"}
```

that shows what happen from the initial user login until the response is sent.

to debug the issue you can also try something like this (my user is `b` with password `password`):

```
curl --verbose --anyauth "http://b:password@127.0.0.1:9090/b"
```

and post the output, in my case I have this output

```
*   Trying 127.0.0.1:9090...
* Connected to 127.0.0.1 (127.0.0.1) port 9090 (#0)
> GET /b HTTP/1.1
> Host: 127.0.0.1:9090
> User-Agent: curl/7.72.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Www-Authenticate: Basic realm="SFTPGo WebDAV"
< X-Content-Type-Options: nosniff
< Date: Mon, 24 Aug 2020 13:53:07 GMT
< Content-Length: 13
< 
* Ignoring the response-body
* Connection #0 to host 127.0.0.1 left intact
* Issue another request to this URL: 'http://b:password@127.0.0.1:9090/b'
* Found bundle for host 127.0.0.1: 0x562d91bd45c0 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 9090 (#0)
* Server auth using Basic with user 'b'
> GET /b HTTP/1.1
> Host: 127.0.0.1:9090
> Authorization: Basic YjpwYXNzd29yZA==
> User-Agent: curl/7.72.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 207 Multi-Status
< Content-Type: text/xml; charset=utf-8
< Date: Mon, 24 Aug 2020 13:53:07 GMT
< Content-Length: 522
< 
* Connection #0 to host 127.0.0.1 left intact
<?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>/b/</D:href><D:propstat><D:prop><D:supportedlock><D:lockentry xmlns:D="DAV:"><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:resourcetype><D:collection xmlns:D="DAV:"/></D:resourcetype><D:displayname></D:displayname><D:getlastmodified>Mon, 24 Aug 2020 13:53:07 GMT</D:getlastmodified></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response></D:multistatus>
```

thank you

**Comment by helmut72** [comment]
I have set SFTP_LOG_VERBOSE to 1. Hope this is the correct option. But it's still one line:

This is the output of curl:

``
```
* Expire in 0 ms for 6 (transfer 0x1111880)
*   Trying ip_sftpgo...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x1111880)
* Connected to ip_sftpgo (ip_sftpgo) port 5040 (#0)
> GET /test HTTP/1.1
> Host: ip_sftpgo:5040
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: application/json; charset=utf-8
< Date: Wed, 26 Aug 2020 20:17:30 GMT
< Content-Length: 48
< 
{"error":"","message":"Not Found","status":404}
* Connection #0 to host ip_sftpgo left intact
```

**Comment by drakkan** [comment]
> I have set SFTP_LOG_VERBOSE to 1. Hope this is the correct option. But it's still one line:

Hi, verbose logging is the default please just start sftpgo this way to have verbose logging to the standard output:

```
sftpgo serve -l ""
```

> 
> ```
> {"level":"info","time":"2020-08-26T22:17:30.522","sender":"httpd","method":"GET","proto":"HTTP/1.1","remote_addr":"ip_client:51968","request_id":"97413a06e8dc/lrGbYKDkO5-000008","uri":"http://ip_sftpgo:5040/test","user_agent":"curl/7.64.0","resp_status":404,"resp_size":48,"elapsed_ms":0}
> ```
> 

This seems a different error from the previous one, probably you used the http port configured for REST API here and not the WebDAV one

> This is the output of curl:
> 
> `curl --verbose --anyauth "http://test:test@ip_sftpgo:5040/test"`
> 
> ```
> * Expire in 0 ms for 6 (transfer 0x1111880)
> *   Trying ip_sftpgo...
> * TCP_NODELAY set
> * Expire in 200 ms for 4 (transfer 0x1111880)
> * Connected to ip_sftpgo (ip_sftpgo) port 5040 (#0)
> > GET /test HTTP/1.1
> > Host: ip_sftpgo:5040
> > User-Agent: curl/7.64.0
> > Accept: */*
> > 
> < HTTP/1.1 404 Not Found
> < Content-Type: application/json; charset=utf-8
> < Date: Wed, 26 Aug 2020 20:17:30 GMT
> < Content-Length: 48
> < 
> {"error":"","message":"Not Found","status":404}
> * Connection #0 to host ip_sftpgo left intact
> ```
> 
> I have compiled it with GO 1.15 with this command:
> `go get github.com/drakkan/sftpgo`

I think this is correct

**Comment by helmut72** [comment]
Sorry, shame on me. I mixed up http/webdav port. Thanks, it works now, but it's very slow. I get about 200kb/sec after disable Debugging. I've tried it with my notes folders, about 12MB. Copying the same to Apache WebDAV, it finish before I can open the transfer status.

I also see very high mem and cpu usage. This is what I get while deleting the 12MB folder with many *.md and *.txt files:

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %  
a7254e36d76c        sftpgo              188.23%             614.8MiB / 1.941GiB   30.94% 
```

When finished, CPU goes down to 0%, but mem usage stays at 500MB. To compare: when starting SFTPGo, it use about 12MB RAM.

In this state I can only do some tests. CPU + RAM is limited and SFTPGo use with distance most of my servers CPU/RAM. I have a complete Mailserver (Postfix/Dovecot), Groupware (SOGo), AD (Samba), WebDAV (Apache) and OpenSSH running which use under 1GB RAM, even after some load.

**Comment by drakkan** [comment]
Hi,

memory usage should go down after a while.

Regarding the performance issue currently before each file upload SFTPGo do a database query to authenticate the user and another one to update last login. Additionally if you have quota limits another query is needed to update quota usage. I plan to cache login info for some configurable time in future updates. Can you please test using the memory provider to see what performance we could achieve with this optimization in your use case?

Additionally the webdav library sometimes reads the file to get the mime type, this could be improved too. I'll do some more performance related tests myself in future. Thank you.

**Comment by helmut72** [comment]
Hi,

> memory usage should go down after a while.

start sftpgo: 11 MB usage
login/logout with sftp (to create a home folder): 77 MB usage
wait/idle 3min: still 77 MB usage
login with WebDAV, copy 12 MB: 650 MB usage, over 180% CPU
logout, wait/idle 10min: still 350 MB usage

Copying the same to Apache WebDAV:
wait/idle: 41 MB RAM
copy 12 MB: 42 MB RAM, about 140% CPU
wait/idle 2 sec: 41 MB RAM

CPU is also high on Apache, but the whole copy job takes 3 seconds and not over 2 minutes.

> Additionally if you have quota limits another query is needed to update quota usage

I've created just a simple user. Not much settings so far. In this state it's only for testing.

> I'll do some more performance related tests myself in future.

Thank you. If you think it waste too much time, please consider to focus to your core component, SFTP.

**Comment by drakkan** [comment]
Hi,

I did some profiling, the bottleneck is the password check, argon2 is quite expensive and currently the password is checked for each webdav request, here are some profiling results after copying 1500 files:

```
33.75GB 99.89% 99.89%    33.75GB 99.89%  golang.org/x/crypto/argon2.initBlocks
         0     0% 99.89%    33.75GB 99.89%  github.com/alexedwards/argon2id.ComparePasswordAndHash
         0     0% 99.89%    33.76GB 99.91%  github.com/drakkan/sftpgo/dataprovider.CheckUserAndPass
         0     0% 99.89%    33.76GB 99.91%  github.com/drakkan/sftpgo/dataprovider.SQLiteProvider.validateUserAndPass
         0     0% 99.89%    33.75GB 99.89%  github.com/drakkan/sftpgo/dataprovider.checkUserAndPass
         0     0% 99.89%    33.75GB 99.89%  github.com/drakkan/sftpgo/dataprovider.isPasswordOK
         0     0% 99.89%    33.76GB 99.91%  github.com/drakkan/sftpgo/dataprovider.sqlCommonValidateUserAndPass
         0     0% 99.89%    33.77GB   100%  github.com/drakkan/sftpgo/webdavd.(*webDavServer).ServeHTTP
         0     0% 99.89%    33.76GB 99.91%  github.com/drakkan/sftpgo/webdavd.(*webDavServer).authenticate
         0     0% 99.89%    33.75GB 99.89%  golang.org/x/crypto/argon2.IDKey (inline)
```

as you can see 33.75GB were allocated to check the user password.

Disabling password checking (you cannot do this without changing SFTPGo code) I have these results:

```
5.16MB 12.70% 12.70%     6.17MB 15.18%  io.copyBuffer
       5MB 12.32% 25.02%     6.50MB 16.01%  os.lstatNolog
    2.50MB  6.16% 31.17%     8.50MB 20.93%  path/filepath.walkSymlinks
    2.02MB  4.96% 36.14%     2.02MB  4.96%  os.(*File).readdirnames
    2.01MB  4.94% 41.08%     2.01MB  4.94%  bufio.NewWriterSize
       2MB  4.93% 46.01%        2MB  4.93%  syscall.ByteSliceFromString
    1.50MB  3.69% 49.70%     1.50MB  3.69%  fmt.Sprintf
    1.01MB  2.48% 52.18%     1.01MB  2.48%  io/ioutil.glob..func1
       1MB  2.47% 54.66%        1MB  2.47%  bufio.NewReaderSize
       1MB  2.47% 57.12%        1MB  2.47%  bytes.makeSlice
```

and the transfer time is greatly reduced. 

This performance related issue will be fixed caching the authenticated users for a configurable time (this was already planned). 

For SFTP/FTP this is not an issue since a user authenticate once and then start upload/downloads using the authenticated session.

**Comment by drakkan** [comment]
Please give a try to [this commit](https://github.com/drakkan/sftpgo/commit/dbed110d020e43520785ee4d556925d0b919ea62) you will get a big performance boost.

If you don't want to compile SFTPGo yourself you can get a pre-built binary [here](https://github.com/drakkan/sftpgo/actions/runs/233024883). You must be logged in as GitHub user to download the build artifacts.

Caching is enabled by default, more info [here](https://github.com/drakkan/sftpgo/blob/master/docs/webdav.md).

Thank you

**Comment by helmut72** [comment]
Thank you! Can test it earliest after Sunday.

**Comment by drakkan** [comment]
> Thank you! Can test it earliest after Sunday.

Thank you. You can now set the [RAM usage](https://github.com/drakkan/sftpgo/commit/bdf18fa862b952ed82f34cd94d3104e043050b99) for argon passwords too

**Comment by helmut72** [comment]
Just did a short test because I'm on a limited data plan and it feels a lot better! Thank you! Will do some tests when I'm back to WiFi, but this takes a while.
