### ISSUE TITLE
[Bug]: docker, unable to load certificates (remove quotes in documentation)

### ISSUE THREAD

**Issue by fauust** [drakkan/sftpgo#1471]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

The [ftp tls doc](https://github.com/drakkan/sftpgo/blob/main/docs/howto/lets-encrypt-certificate.md#enable-explicit-ftp-over-tls) suggest loading certificates with quotes, something like:
```txt
SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_FILE="/var/lib/sftpgo/certs/fullchain.pem"
SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_KEY_FILE="/var/lib/sftpgo/certs/privkey.key"
```
But this does not work as it gives the following error:
```console
sftpgo    | {"level":"error","time":"2023-12-06T11:12:55.572","sender":"ftpd","message":"unable to load X509 key pair, cert file \"\\\"/var/lib/sftpgo/certs/fullchain.pem\\\"\" key file \"\\\"/var/lib/sftpgo/certs/privkey.pem\\\"\" error: open \"/var/lib/sftpgo/certs/fullchain.pem\": no such file or directory"}
sftpgo    | {"level":"error","time":"2023-12-06T11:12:55.572","sender":"service","message":"could not start FTP server: open \"/var/lib/sftpgo/certs/fullchain.pem\": no such file or directory"}
```

Workaround is to define the environment variables without quotes:
```txt
SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_FILE=/var/lib/sftpgo/certs/fullchain.pem
SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_KEY_FILE=/var/lib/sftpgo/certs/privkey.key
```

Images tested (as of today, see bellow):
- drakkan/sftpgo:v2.5
- drakkan/sftpgo:v2.5-alpine

```console
❯ docker images
REPOSITORY       TAG           IMAGE ID       CREATED       SIZE
drakkan/sftpgo   v2.5          ea67734fdaac   3 weeks ago   208MB
drakkan/sftpgo   v2.5-alpine   dce604f84b27   3 weeks ago   78.2MB
```

### Steps to reproduce

1. follow https://github.com/drakkan/sftpgo/blob/main/docs/howto/lets-encrypt-certificate.md#enable-explicit-ftp-over-tls
2. restart container with something like `docker-compose down && docker-compose up`
3. ftp server does not start an the container enters in restart loop

### Expected behavior

ftp server starts correctly and TLS is enabled.

### SFTPGo version

v2.5.5

### Data provider

local

### Installation method

Community Docker image

### Configuration

See bug description

### Relevant log output

```shell
sftpgo    | {"level":"error","time":"2023-12-06T11:12:55.572","sender":"ftpd","message":"unable to load X509 key pair, cert file \"\\\"/var/lib/sftpgo/certs/fullchain.pem\\\"\" key file \"\\\"/var/lib/sftpgo/certs/privkey.pem\\\"\" error: open \"/var/lib/sftpgo/certs/fullchain.pem\": no such file or directory"}
sftpgo    | {"level":"error","time":"2023-12-06T11:12:55.572","sender":"service","message":"could not start FTP server: open \"/var/lib/sftpgo/certs/fullchain.pem\": no such file or directory"}
```

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment]
Hello,

thanks for the report. The doc is about an env file loaded directly from SFTPGo that works well with quotes, in your case I think you are using docker compose or something similar which have this issue. It i hard to cover every use case in docs, anyway the error message is quite clear and from it you should understand that you need to remove quotes

**Comment by fauust** [comment]
Oh, indeed, I read too fast and thought that the documentation was speaking about loading env variables the [docker-compose way](https://docs.docker.com/compose/environment-variables/set-environment-variables/#substitute-with-an-env-file). And yes, you are assuming correctly, I am using docker-compose with env variables defined directly in the compose file.

Closing, sorry for the noise and thanks for this awesome project!
