### ISSUE TITLE
[Bug] [Windows11 x64] [Portable Mode] "--ftpd-port" option conflicts with FTPS

### ISSUE THREAD

**Issue by xvim64** [drakkan/sftpgo#1480]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

In portable mode with FTPS, "--ftpd-port" option generates some problems.

### Steps to reproduce

1. extract "sftpgo_v2.5.5_windows_portable.zip" to somewhere.

2. edit sftpgo.json
```
  "ftpd": {
    "bindings": [
      {
        "port": 2020,
        "tls_mode": 1,
        "certificate_file": "go.crt",
        "certificate_key_file": "go.key",
```

3. generate go.crt and go.key in the sftpgo directory
```
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout go.key -out go.crt
```

4. run sftpgo.exe portable with some options.

5. [case 1] panic: runtime error
```
sftpgo.exe portable --ftpd-port=2020 --ftpd-cert go.crt --ftpd-key go.key
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x78 pc=0x7ff62cb6cb08]

goroutine 1 [running]:
github.com/robfig/cron/v3.(*Cron).AddJob(0x0, {0xc0002c6100?, 0xc00053f348?}, {0x7ff62e3492a0, 0xc0004d5c60})
        github.com/robfig/cron/v3@v3.0.1/cron.go:149 +0x28
github.com/robfig/cron/v3.(*Cron).AddFunc(...)
        github.com/robfig/cron/v3@v3.0.1/cron.go:142
github.com/drakkan/sftpgo/v2/internal/common.NewCertManager({0xc00027ce70, 0x1, 0x1}, {0x7ff62e336870, 0x1}, {0x7ff62e05256e, 0xc})
        github.com/drakkan/sftpgo/v2/internal/common/tlsutils.go:302 +0x245
github.com/drakkan/sftpgo/v2/internal/cmd.glob..func10(0x7ff62dbfc700?, {0x7ff62e043b74?, 0x5?, 0x5?})
        github.com/drakkan/sftpgo/v2/internal/cmd/portable.go:147 +0x4d9
github.com/spf13/cobra.(*Command).execute(0x7ff62dbfc700, {0xc00008b770, 0x5, 0x5})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x7ff62dbfc9e0)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/drakkan/sftpgo/v2/internal/cmd.Execute()
        github.com/drakkan/sftpgo/v2/internal/cmd/root.go:108 +0x25
main.main()
        github.com/drakkan/sftpgo/v2/main.go:35 +0x85
```

6. [case 2] FTPS connection is denied.
```
sftpgo.exe portable --ftpd-port=2020
```
I just added the port number in commandline.
But the FTPS connection is denied.

"sftpgo.exe portable" works well with FTPS. // sftpgo.exe reads sftpgo.json

7. [case 3] FTPS is not working without editing sftpgo.json.
```
sftpgo.exe portable --ftpd-port=2020 --ftpd-cert=go.crt --ftpd-key=go.key
```
This causes "panic: runtime error".

### Expected behavior

In the portable mode,
1) no "panic: runtime error".
2) commandline options should be prefered than the sftpgo.json or ignore the sftpgo.json.
3) "tls_mode" option in FTPS is needed.
4) "ignoring sftpgo.json" option will be useful.

### SFTPGo version

2.5.5

### Data provider

local

### Installation method

Other

### Configuration

// sftpgo.json
```
  "ftpd": {
    "bindings": [
      {
        "port": 2020,
        "tls_mode": 1,
        "certificate_file": "go.crt",
        "certificate_key_file": "go.key",
```

### Relevant log output

```shell
see the "panic: runtime error" in "step to reproduce"
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional info

// installation method
sftpgo_v2.5.5_windows_portable.zip

**Comment by drakkan** [comment]
The panic is now fixed, thanks for reporting. As for adding a new option for tls_mode we cannot add a CLI flag for all the supported option. 

tls_mode `0` (the default), allows both plain FTP and FTPES, you can change the default value in the config file or you can override the default value via env var, every configuration parameter in the config file can also be set using an env var, for example (on Linux) you can do something like this:

```
SFTPGO_FTPD__BINDINGS__0__TLS_MODE=1  ./sftpgo portable --ftpd-port=2020 --ftpd-cert=testcerts/localhost.crt --ftpd-key=testcerts/localhost.key
```
