### ISSUE TITLE
[Bug] [Win11 x64] [Portable Mode] SFTP ignores sftpgo.json's port number

### ISSUE THREAD

**Issue by xvim64** [drakkan/sftpgo#1485]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

In portable mode,
SFTP ignores sftpgo.json's port number.

### Steps to reproduce

1. extract "sftpgo_v2.5.5_windows_portable.zip" to somewhere.

2. edit sftpgo.json
// sftpgo.json
```
  "sftpd": {
    "bindings": [
      {
        "port": 3022,  // 2022 (default) --> 3022
...
  "ftpd": {
    "bindings": [
      {
        "port": 2020,  // 0 (default) --> 2020
```

4. run sftpgo as portable
```
sftpgo.exe portable
```

5. SFTP port number is randomly ganerated.
```
INF Portable mode ready, user: "user", password: "Vk87u1M9", public keys: [], directory: "C:\\SFTPGO", permissions: map[/:[list download]], enabled ssh commands: [md5sum sha1sum sha256sum cd pwd scp] file patterns filters: [] SFTP port: 61903 FTP port: 2020
```
SFTP port: 61903
FTP port: 2020

FTP respects the port number of sftpgo.josn.
But SFTP ignores the port number of sftpgo.json.
I have to add "--sftpd-port=3022" to change the SFTP port number.
```
sftpgo portable --sftpd-port=3022
```
And SFTP also ignores the default port number 2022 written in sftpgo.json.

Is it intended?

FTP(S) respects sftpgo.json, but SFTP doesn't.
There is no coherence.
The difference is confusing.

### Expected behavior

In the portable mode,
SFTP, also like FTP, must respect sftpgo.json.

### SFTPGo version

2.5.5

### Data provider

local

### Installation method

Other

### Configuration

see the "step to reproduce"

### Relevant log output

```shell
see the "step to reproduce"
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional info

// installation method
sftpgo_v2.5.5_windows_portable.zip

**Comment by drakkan** [comment]
Hi,

this happens because `--sftpd-port` is 0 by default and 0 means a random port. `ftpd-port` is -1 by default and so the value from the config file/env is used. Probably it should be better documented

**Comment by xvim64** [comment]
> Hi,
> 
> this happens because `--sftpd-port` is 0 by default and 0 means a random port. `ftpd-port` is -1 by default and so the value from the config file/env is used. Probably it should be better documented

The values "--(s)ftpd-port=0" (random prot) on the command line and "port" : 0 (disabled) in sftpdo.json mean different things.
This makes me think twice when using the "--(s)ftpd-port" option.
It would be nice to have consistency between the command line "--(s)ftpd-port=<number>" and sftpgo.json/"port":<number>".
