### ISSUE TITLE
Error if attempting to delete a folder in sftp with S3 provider

### ISSUE THREAD

**Issue by amitm02** [drakkan/sftpgo#149]
When using a GUI client and attempting to delete a folder with files, the client reports an error.
I think it is because there are no real "folder" in S3, for the remove dir operation fails

```
{"level":"info","time":"2020-07-27T18:06:23.182","sender":"Remove","username":"guest","file_path":"/cases/onePage/ccc.pdf","target_path":"","filemode":"","uid":-1,"gid":-1,"access_time":"","modification_time":"","ssh_command":"","connection_id":"d3fcae8ee6304cfbe3c875f5dd4584276be555669f7e28d273274cadd854a748","protocol":"SFTP"}
{"level":"debug","time":"2020-07-27T18:06:23.185","sender":"sftpd","connection_id":"d3fcae8ee6304cfbe3c875f5dd4584276be555669f7e28d273274cadd854a748","message":"new cmd, method: Rmdir, sourcePath: \"/cases/onePage\", targetPath: \"\""}
{"level":"warn","time":"2020-07-27T18:06:23.190","sender":"sftpd","connection_id":"d3fcae8ee6304cfbe3c875f5dd4584276be555669f7e28d273274cadd854a748","message":"failed to remove a dir \"/cases/onePage\": stat error: 404 no such file or directory"}
```

**Comment by drakkan** [comment]
Hi,

if `/cases/onePage/ccc.pdf` is the only file in the folder `/cases/onePage` and the "folder" is implicitally created when you uploaded the file it gets automatically deleted when you remove the file and so you have the `no such file or directory` error posted above.

Maybe SFTPGo could return no error if you try to delete a S3/GCS folder and the cloud provider returns 404. 

I'm quite busy now, maybe I can take a look the next week end. Thank you
