### ISSUE TITLE
[Bug]: I can not  to open the *.xls files in the mapping webdav disk using WPS office software.

### ISSUE THREAD

**Issue by ketergao** [drakkan/sftpgo#1492]
### ⚠️ This issue respects the following points: ⚠️

- [ ] This is a **bug**, not a question or a configuration issue.
- [ ] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

![image](https://github.com/drakkan/sftpgo/assets/54433527/769fad4d-a90f-4993-90b0-4216667a4100)

### Steps to reproduce

1. mount the webdav disk.
2. create xls in the mount disk subdir.   
   eg: 
          /a.xls : it is ok
         /newdir/a.xls:  it is ok
3. I can not open the xls file use wps software.

### Expected behavior

-

### SFTPGo version

last

### Data provider

-

### Installation method

Other

### Configuration

-

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional info

--

**Comment by drakkan** [comment]
Please provide at least some SFTPGo logs and specify the storage provider you are using. Thank you
