### ISSUE TITLE
[oidc] use UserInfo endpoint for OpenIDConnect claims

### ISSUE THREAD

**Issue by michael-doubez** [drakkan/sftpgo#1493]
### Is your feature request related to a problem? Please describe.

Token doesn't contains all claims - some of them are only accessible through the userinfo endpoint.

### Describe the solution you'd like

Use UserInfo from oidc implementation to get additional user information:
https://github.com/coreos/go-oidc/blob/6d6be43e852de391805e5a5bc14146ba3cdd4195/example/userinfo/app.go#L88C29-L88C37

### Describe alternatives you've considered

Provide access token to the pre login script: that would allow enriching sftpgo user.

### What are you using SFTPGo for?

Small business (3-person firm with file exchange?)

### Additional context

Testing the product for suitability

**Comment by drakkan** [comment]
Hello,

thank you for your request, we'd like to know more about your use case (which OIDC provider are you using?) and why you can't add the required field to OIDC claims.

To get support in general and for enterprise specific edge cases like this, we suggest you consider supporting the project in some way, we may or may not answer questions/feature requests here. Thank you

**Comment by michael-doubez** [comment]
Fair enough.
We are not actually using it but evaluating the usability. Whatever the outcome, I'll push your project for a subvention. I personally think it is great and a nice bridge compared to rclone by example.

Regarding OIDC, I realized it is a limitation of the OIDC Provider which requires the scopes to be specified in the token request. When not present, the claims are not added to the id_token. An additional config and AuthCodeOption  would be required.

I am not even sure UserInfo or Introspect endpoints would contain the relevant information as it is.
Closing the request ....

**Comment by drakkan** [comment]
Thanks for the nice words. Setting additional scopes to get more fields in claims is already supported, as you've probably already noticed yourself.

**Comment by james-d-elliott** [comment]
To speak to this from a specification perspective, there are several means by which clients are guaranteed to get access to these claims. 

The [ID Token](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) is only guaranteed to have claims that are necessary for the relevant flow. In most cases this is just the claims listed in the spec. The intent behind scopes and where claims are accessible is detailed in [Requesting Claims using Scope Values](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) where it makes a singular exception where the claims associated to those scopes should be returned in a flow that does not include an Access Token.

> However, when no Access Token is issued (which is the case for the response_type value id_token), the resulting Claims are returned in the ID Token.

Interestingly there is another parameter which allows all requests to be likely to return the claims in the ID Token, which is detailed in the [Requesting Claims using the "claims" Request Parameter](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter) section and subsections.

When you realize the requested / granted scope applies to the Access Token and what the intent of the Access Token is, in addition to the above sections, to me it becomes very clear that the intent is that the claims associated to the standard scopes are intended to be requested from the [User Info Endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo).
