### ISSUE TITLE
Force transfer mode for FTP connections

### ISSUE THREAD

**Issue by adrfalck** [drakkan/sftpgo#1499]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

It'd be great if it was possible to set the transfer mode from automatic to a specific option. We have a case at the moment were all transfers must be binary. Most clients will do this automatically, but we've seen that some transfers have been corrupted because of a Windows machine sending a text file as ASCII and the EOF has been changed. Options could be "default", "ASCII" and "Binary".

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment]
Hello,

the transfer mode is by default "BINARY" and can be changed to "ASCII" by the client. Debug logs are required to investigate this issue.

To get support in general and for edge cases like this, we suggest you consider supporting the project in some way, we may or may not answer questions/feature requests here. Thank you
