### ISSUE TITLE
Allow Host Key Type ED25519

### ISSUE THREAD

**Issue by helmut72** [drakkan/sftpgo#150]
Allow Host Key Type ED25519. Please have a look:
https://github.com/golang/crypto/blob/123391ffb6de907695e1066dc40c1ff09322aeb6/ssh/common.go#L71

Can't get a better score than C in
https://www.sshaudit.com

<img width="1005" alt="Bildschirmfoto 2020-07-28 um 23 22 30" src="https://user-images.githubusercontent.com/1388751/88723495-433a9b00-d129-11ea-8f50-fb9788ec1fc0.png">

OpenSSH get an A+

**Comment by drakkan** [comment]
Hi,

`ED25519` keys are supported already, you only need to generate them yourself (please use `ssh-keygen`). I did the test myself and after properly configuration I get A+.
