### ISSUE TITLE
Repository no longer working as certificate is not verified and site cannot be reached securely.[Bug]: 

### ISSUE THREAD

**Issue by hardida** [drakkan/sftpgo#1501]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

When attempting to do a simple apt update on Debian 12 Bookworm I get the following:
Err:4 https://ftp.osuosl.org/pub/sftpgo/apt bookworm InRelease                                                                                                                 
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 146.112.47.138 443]

### Steps to reproduce

1. perform update of repository data on any distro

OR

2. manually browse to the repository link and see that https connection cannot be established.

### Expected behavior

repository should be able to be accessed using SSL when performing updates

### SFTPGo version

2.5.4

### Data provider

Not sure what you are asking for

### Installation method

Community Deb package

### Configuration

no custom config

### Relevant log output

```shell
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease           
Get:3 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Ign:4 https://ftp.osuosl.org/pub/sftpgo/apt bookworm InRelease          
Ign:4 https://ftp.osuosl.org/pub/sftpgo/apt bookworm InRelease
Ign:4 https://ftp.osuosl.org/pub/sftpgo/apt bookworm InRelease
Err:4 https://ftp.osuosl.org/pub/sftpgo/apt bookworm InRelease                                                                                                                 
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 146.112.47.138 443]
Fetched 48.0 kB in 7s (6,431 B/s)                                                                                                                                              
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://ftp.osuosl.org/pub/sftpgo/apt/dists/bookworm/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 146.112.47.138 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
dharding@vgr-ftosftp01:~$ Err:4 https://ftp.osuosl.org/pub/sftpgo/apt bookworm InRelease
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
It works for me, I can access the repository URL from browser, curl and apt without any problems. For me the repository name resolves to the IP `140.211.166.134`
