### ISSUE TITLE
skip TLS verify for S3

### ISSUE THREAD

**Issue by lr1980** [drakkan/sftpgo#1503]
### Is your feature request related to a problem? Please describe.

For local tests my MinIO use self signed TLS certificates.

### Describe the solution you'd like

So a "skip TLS verify" option would be nice.

### What are you using SFTPGo for?

Medium business

### Additional context

I use sftpgo in Kubernetes with the helm chart.

**Comment by drakkan** [comment]
This is already supported in the development version
