### ISSUE TITLE
feature suggestions/request: pre-actions operations hooks

### ISSUE THREAD

**Issue by amitm02** [drakkan/sftpgo#151]
It would be great to have a pre-actions hooks that acts as a validations.
e.g in addition to "upload" hooks, also "pre-upload" hook.
if the hook returns a status code different from 20x, the upload should be cancelled.

The motivation, is that many times the hooks are used to index the uploaded files or transform it somehow. But if the DB is down or has some issue, you want to prevent the file from being uploaded, else you'll have un-indexed or corrupted data .

**Comment by drakkan** [comment]
Hi,

I don't like this suggestion.

Suppose your upload takes 10 minutes, your db could be ok when the upload starts but could be down when the upload ends.

In general if you do two or more separate HTTP calls you cannot assume that if the first one is ok then the second one will be ok too. Maybe you could save the notification somewhere, for example on disk as JSON, if you fail to process it and then recover the accumulated notifications when you are able to process them again. Another solution is to parse the log files or scan the filesystem periodically. 

This should be handled on your side, sorry

**Comment by amitm02** [comment]
I understand your point. Thanks.

**Comment by vb8448** [comment]
Hi,
i was wondering if a pre-action like pre-upload could be used for file versioning.
Image a use case where you would allow users to update a file but also want to maintain old versions.
With a pre-upload action you could check if the uploading file exists and rename it with a '.v{datetime}' suffix or something similar.
