### ISSUE TITLE
[Bug]: var file lack of documentation for docker, misleading or not working

### ISSUE THREAD

**Issue by todeb** [drakkan/sftpgo#1510]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

From doc:
If you install SFTPGo on Linux using the official deb/rpm packages you can set your custom environment variables in the file /etc/sftpgo/sftpgo.env. SFTPGo also reads files inside the env.d directory relative to config dir (/etc/sftpgo/env.d on Linux 

On docker image used:
```
drakkan/sftpgo:v2.5.6-alpine
```

Tried different paths for mount the same variable file:
```
/etc/sftpgo/sftpgo.env - not applied by sftpgo
/etc/sftpgo/env.d/sftpgo.env - not applied by sftpgo
/var/lib/sftpgo/sftpgo.env - not applied by sftpgo 
/var/lib/sftpgo/env.d/sftpgo.env - applied by sftpgo 
```

For me documentation is not very clear why mount to /var/lib/sftpgo/env.d/sftpgo.env is applied but the others not.
Documentation is about direct linux installation not the docker, but this might be misleading.
Or maybe a bug?

### Steps to reproduce

mount the same env variable to different locations and restart docker container

### Expected behavior

more clear documentation.

### SFTPGo version

drakkan/sftpgo:v2.5.6-alpine

### Data provider

na

### Installation method

Community Docker image

### Configuration

config

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment]
Thanks for your interest in SFTPGo, from the docs

> SFTPGo also reads files inside the env.d directory relative to config dir

on Docker the config dir is `/var/lib/sftpgo`, if you install from deb/rpm the config dir is `/etc/sftpgo`. 
On Docker you can easily set env vars without mounting a config file, anyway the method to use is a your choice

**Comment by kossithedon** [comment]
Just came across the same behavior with the version 2.6.4 of the image drakkan/sftpgo from dockerhub. When the configuration file is mapped at /var/lib/sftpgo/sftpgo.env, the container recognize that the file exist but the loaded configuration is not the content of the file /var/lib/sftpgo/sftpgo.env but it seem to be a default/template configuration. The content of the configuration file is correctly loaded only when it is mapped at /var/lib/sftpgo/env.d/sftpgo.env
