### ISSUE TITLE
would you be open to accepting a PR for wolfi-based image ?

### ISSUE THREAD

**Issue by tuananh** [drakkan/sftpgo#1513]
### Is your feature request related to a problem? Please describe.

Wolfi OS is a lightweight GNU software distribution which is designed around minimalism, making it well-suited for containerized environments. Think of it like a mix of distroless and alpine but glibc-based.

Benefits: 
- can achieve very low CVE (if not 0).
- glibc based so it's compatible with many other tools if necessary.

### Describe the solution you'd like

we can use Dockerfile like currently (using wolfi-base image) and copy the binary from builder image.

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment]
Hello,

thanks for the suggestion but we already have too many docker variants. You have to maintain this variant yourself, sorry.
We offer this service for enterprise plan subscribers
