### ISSUE TITLE
Per user protocol grants

### ISSUE THREAD

**Issue by consocio** [drakkan/sftpgo#1524]
### Is your feature request related to a problem? Please describe.

I need to enable single protocols for single users 

### Describe the solution you'd like

This feature will be useful to limit individual users' access to only the protocols deemed necessary for their activities.
The feature should allow administrators to assign specific protocols to users or user groups. For example, we would like to be able to configure "user1" to only use the SFTP and WEBDAV protocols, while "user2" should have access only to the FTP/S protocols.

### What are you using SFTPGo for?

Medium business

**Comment by CaptainLoop** [comment]
It is already a thing in SFTPGO. In the "user profile -->ACLs --> Denied protocols". You just disable protocols that you want. 
it's pretty clear

![image](https://github.com/drakkan/sftpgo/assets/13140552/36cd1fd8-12f3-48af-9ac9-38d65ff60c1b)
