### ISSUE TITLE
[Bug]: SFTPGo sets incorrect ContentType when using an S3-compatible backend

### ISSUE THREAD

**Issue by foxfire-auspex** [drakkan/sftpgo#1528]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### The bug
Currently, when SFTPGo is configured to use an S3-compatible backend (Ceph S3 in my case) it sets the ContentType metadata attribute to 'binary/octet-stream' for all files by default.

Since this behavior is configurable for WebDAV and the pertaining logic already exists, I believe this is more of a bug than a feature request.

### Why it matters
In my setup, files uploaded to S3 via SFTPGo might be cached by a Varnish proxy. If the proxy delivers content with an incorrect Content-Type header, the receiving browser's behavior changes. For example, in the case of an MP4 video file, chromium-based browsers will immediately begin downloading the entire file instead of playing it in the browser.

Would it be possible to employ the same MIME type detection logic for transfers to S3 as well?

### Steps to reproduce

1. Configure SFTPGo to use an S3-compatible backend
2. Upload any media file (JPG, PNG, MP4, MOV, etc.)
3. Perform a HEAD request on the resulting S3 object
4. Observe the incorrect ContentType of 'binary/octet-stream'

### Expected behavior

SFTPGo should detect and set the correct MIME/Content-Type when transfering files to S3-compatible object storage. For example, a *.mp4 file should have its Content-Type set to 'video/mp4'.

Alternatively, SFTPGo could provide a kind of 'post-upload/pre-transfer-to-S3' hook through which a user might implement their own logic for dealing with metadata.

### SFTPGo version

2.5.6

### Data provider

SQLite

### Installation method

Community RPM package

### Configuration

config

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
I can't reproduce, some samples output from `curl`

```
$ curl --anyauth -I "http://minio:password@127.0.0.1:10080/sub.mkv"
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Www-Authenticate: Basic realm="SFTPGo WebDAV"
X-Content-Type-Options: nosniff
Date: Sat, 03 Feb 2024 13:36:55 GMT
Content-Length: 45

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 13313790
Content-Type: video/x-matroska
Etag: "17b05dc826d8c200cb26fe"
Last-Modified: Sat, 03 Feb 2024 13:36:13 GMT
Date: Sat, 03 Feb 2024 13:36:55 GMT
```

```
$ curl --anyauth -I "http://minio:password@127.0.0.1:10080/file.txt"
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Www-Authenticate: Basic realm="SFTPGo WebDAV"
X-Content-Type-Options: nosniff
Date: Sat, 03 Feb 2024 13:37:17 GMT
Content-Length: 45

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 4034
Content-Type: text/plain; charset=utf-8
Etag: "17b05dc950deb400fc2"
Last-Modified: Sat, 03 Feb 2024 13:36:18 GMT
Date: Sat, 03 Feb 2024 13:37:17 GMT
```

It's always fun to see users running complex things like Ceph, Varnish, and large K8 clusters for home use cases ...
