### ISSUE TITLE
API documentation at https://sftpgo.stoplight.io/

### ISSUE THREAD

**Issue by useronkel** [drakkan/sftpgo#1532]
### Is your feature request related to a problem? Please describe.

Hi
I do not know if you are also the maintainer at https://sftpgo.stoplight.io/....
The version on this site relates to v2.5.4 and is a little bit outdated ;-)

### Describe the solution you'd like

I would love to see the current sftpgo version :-)

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
there are no changes to the API from 2.5.4 to 2.5.6
