### ISSUE TITLE
restriction on virtual folders

### ISSUE THREAD

**Issue by KamranBiglari** [drakkan/sftpgo#1534]
### Describe the solution you'd like

I have a virtual S3 storage with subfolders corresponding to each user shared with multiple users.
I want to restrict access use to see their own folder in and I tried to use ACL do deny * and allow the folder. 
The ACL doesn't apply. 
Would you please help me and is it possible to have this kind of restriction?

S3 mounted as virtual folder /virtual in all accounts.

```
/virtual/*         *  DENIED  HIDDEN
/virtual/user1  *  ALLOW  VISIBLE
```

### What are you using SFTPGo for?

Professional user, 1 person business

**Comment by n0v1** [comment]
You should be able to achieve this by setting the `key_prefix` option on your virtual folder to something like `%username%/`. Look for "key prefix" in https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md for some examples.

**Comment by drakkan** [comment]
You have to set patterns on the same folder. However, depending on your use case, I think there are better ways to achieve this result
