### ISSUE TITLE
[Bug]: ACL permission drop down truncated

### ISSUE THREAD

**Issue by mr-manuel** [drakkan/sftpgo#1541]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

If the drop down menu of the ACL permissions is opened when located in the lower section of the page, the list is truncated.
![grafik](https://github.com/drakkan/sftpgo/assets/12592765/8de88679-c792-4a7a-994c-cf64eafd54c4)

When the drop down menu is located in the upper section of the page, the list is displayed correctly.
![grafik](https://github.com/drakkan/sftpgo/assets/12592765/3cf3be17-3a1a-4dee-8b27-ea96428820b2)

### Steps to reproduce

1. Open the admin page
2. Go to Users -> Edit user -> ACLs.
3. Make sure you don't see the "Per-directory pattern restrictions" modal yet.
4. Click on one of the drop down menus of the ACLs section.
5. Now you see the cut off drop down menu. Once a scrollbar was shown, but all other times not.

### Expected behavior

The drop down menu should be visible.

### SFTPGo version

SFTPGo 2.5.6-a6a92f0d-2023-12-18T17:48:48Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +unixcrypt +portable

### Data provider

Local

### Installation method

Community Docker image

### Configuration

Not relevant

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional info

Tested with Firefox 122.0.1 and Microsoft Edge 121.0.2277.112.

**Comment by drakkan** [comment]
Hello,

this is a known issue, please try the new UI added to the development version, it should be fixed. Thank you

**Comment by mr-manuel** [comment]
Thans for your answer. I will try the edge version then.

Very neat the new GUI! But no entries did load. User and Groups pages where forever loading. I have to check that with a bit more time. I will report then back.

**Comment by drakkan** [comment]
> Thans for your answer. I will try the edge version then.
> 
> Very neat the new GUI! But no entries did load. User and Groups pages where forever loading. I have to check that with a bit more time. I will report then back.

I guess this is related to some caching issue or to the translation system. Please take a look at the web developer console to understand the issue, maybe you use an unsupported language, English should be used in this case but I haven't tested using a browser with no english or italian language.

**Comment by mr-manuel** [comment]
I cleared the cache and checked with developer tools. The browser language is german. With english or italian it works indeed. Is there no fallback to english, if the language is not found?

With the edge version the issue isn't present anymore.

On the users and groups page it would be nice, if an entry also opens on double click instead of pressing Actions -> Edit. Maybe for the other pages as well.

**Comment by drakkan** [comment]
> I cleared the cache and checked with developer tools. The browser language is german. With english or italian it works indeed. Is there no fallback to english, if the language is not found?

it should fallback to [english](https://github.com/drakkan/sftpgo/blob/c8da72a7f7ea10a3ca853f66f0ad80855893b775/templates/common/base.html#L195) but as I said is something I haven't yet tested. 

Just to confirm, after clearing the cache, if you use a browser that supports German and English/Italian but uses German as the default language it doesn't work, if you switch to English or Italian as the default language it works. Did I get it right? Thanks

**Comment by mr-manuel** [comment]
Yes thats correct.

**Comment by drakkan** [comment]
The translations fallback should be now fixed

https://github.com/drakkan/sftpgo/commit/757185256c0e06ac60510ca2e09174b8b2d46f2a

**Comment by mr-manuel** [comment]
I downloaded the latest edge version and can confirm that this is now fixed. Thank you!
