### ISSUE TITLE
[Bug]: Sending email via Event Action command and manual sent mail always fails

### ISSUE THREAD

**Issue by useronkel** [drakkan/sftpgo#1544]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Adding event action: command with name testcommand as shell script (/etc/sftpgo/bin/test.sh)
Content:
```
#!/bin/bash
echo "Testmail"|/usr/bin/mutt -s "test" -- test@example.com
```
Adding event rule: Filesystem on upload execute command testcommand
Result: Sent email stops with postfix error postfix/sendmail[1985607]: fatal: inet_addr_local[getifaddrs]: getifaddrs: Address family not supported by protocol
Replacing command action with email, all went fine.

### Steps to reproduce

1. Create event action command with path to a shell script
2. Add above shell commands to script
3. Sending email will fail, regardless of used mail client (mutt, sendmail, mailx, mail)

### Expected behavior

Emails are sent through shell

### SFTPGo version

v2.5.6

### Data provider

sqlite

### Installation method

Other

### Configuration

Default config

### Relevant log output

```shell
/var/log/maillog
Feb 17 14:41:34 host.example.com postfix/sendmail[1985607]: fatal: inet_addr_local[getifaddrs]: getifaddrs: Address family not supported by protocol
```

### What are you using SFTPGo for?

Enterprise

### Additional info

I'm evaluating SFTPGo for my company

**Comment by drakkan** [comment]
check the systemd unit
