### ISSUE TITLE
On first login via FTP use supplied password.

### ISSUE THREAD

**Issue by KpjComp** [drakkan/sftpgo#1550]
### Is your feature request related to a problem? Please describe.

Not sure if this is currently possible, so marking as feature request.

My old FTP server is used for connecting lots of IOT devices, and the number of FTP users has of course increased.

I'm planning on moving over to FTPGo, the problem is the current FTP server doesn't store the password, but stores the hash.   Getting to all these devices and changing the password would be a big job.

### Describe the solution you'd like

So what would be really useful would be an option to accept any password on the first FTP login, but then assign the supplied password to the FTP user.

### Describe alternatives you've considered

Although the FTP server I'm currently using hashes the password, ironically the log shows them, so I could in theory just search the log to update password, but a way of doing it automatically would be nice.. :)

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS), Professional user, 1 person business

**Comment by drakkan** [comment]
Hello,

SFTPGo can verify passwords in several formats, so you can import your hashed password if the hashing algorithm used in your old solution is supported. Please check the [docs](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

**Comment by KpjComp** [comment]
Cheers, @drakkan , that works a treat.  The old FTP server was using MD5Digest,  so prefixing with {MD5} is exactly what I was looking for   :)
