### ISSUE TITLE
[FEATURE REQUEST] Add folder picker option like WeTransfer

### ISSUE THREAD

**Issue by bludlineaudio** [drakkan/sftpgo#1554]
### Is your feature request related to a problem? Please describe.

Can't upload folders, when dragging and dropping a folder into the Web UI it just flattens it so all files get uploaded but no folders or sub-folders are created

### Describe the solution you'd like

Hi team, great piece of software btw!🙌

---

[WeTransfer](https://wetransfer.com/) makes it very easy to upload whole folders by having a separate button `Or select a folder` (in the 2nd screenshot) which lets the user 🥁 select_a_folder 😲. The folder-picker-popup then allows the user to double-click into folders, and when they've chosen the one they keep that one selected and then select `Upload` on the folder-picker-popup.

I'm happy to give some UI suggestions to make space for the `Select a folder` button?

---

I think this might help:
https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker

I also asked ChatGTP and it said this:
_To implement a folder picker functionality on your website, you would need to use the HTML <input> element with the directory attribute. However, it's important to note that the directory picker feature is currently only supported in certain browsers like Chrome and Edge, and its behavior may vary across different operating systems._

_Here's how you can create a folder picker input in HTML:_
```html
<input type="file" id="folderPicker" webkitdirectory directory multiple>
```

---

I'd appreciate it if you could give me a rough estimation of when it might be likely this feature will be added in if you choose to do so, or an explanation of why it won't be added,
Please let me know if there is a more formal way to request features or if there is any other info you'd need from me.

Thanks in advance 🤗

---

**SFTPGo - Drag-and-drop folder into Web UI (doesn't upload folder and subfolders, it just flattens it all out)**

![image](https://github.com/drakkan/sftpgo/assets/143179790/9f9d85f0-d5dc-49eb-a0d7-4f7b8456d22f)

---

**WeTransfer - Folder-picker-popup**

![image](https://github.com/drakkan/sftpgo/assets/143179790/94240e45-6a01-48fc-ab90-04d0d253ecff)

### Describe alternatives you've considered

I've not, sorry... I'm not sure if I'm doing it a wrong way or if I should be using WebDAV... But I intend to share this as a link with other non-tech-savvy users so they can easily upload via the WebUI 

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Hello,

this would be a good addition and something I would like to add in the future but I don't have a definite plan. A PR would help. Thank you

**Comment by drakkan** [comment]
This feature was implemented differently in the development version
