### ISSUE TITLE
Hide version from login page

### ISSUE THREAD

**Issue by carlosV2** [drakkan/sftpgo#1557]
### Is your feature request related to a problem? Please describe.

The version number is visible in the login page.

This is not bad but it allows for 0-day attacks. Hiding it does not protect from those attacks but, at least, it makes them a bit less likely.

### Describe the solution you'd like

While there are always ways to guess the version number, it should not be easily guessable nor given in such a simple way.

### Describe alternatives you've considered

I've attempted to inspect the code but to no avail. I _think_ the variable that controls that text is `Branding.ShortName` but I've tried to set it via the environment variable `SFTPGO_HTTPD__BINDINGS__BRANDING__SHORT_NAME` without success.

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional context

![image](https://github.com/drakkan/sftpgo/assets/2642839/c8bf9df6-827c-44e0-a68b-d0fcd4fcb6a2)

**Comment by crabique** [comment]
To traverse the httpd.bindings list, you have to go through the binding's index, if you have a single binding there it should be `SFTPGO_HTTPD__BINDINGS__0__BRANDING__SHORT_NAME`.

**Comment by carlosV2** [comment]
Hi @crabique, many thanks for your help. I overlooked the fact that the bindings is a list 🤦🏼‍♂️. This, however, did not removed the version number from the login page. Do you know how can I do it?

**Comment by crabique** [comment]
Is there any specific reason you can't just change it in the config?

In the default config this setting is set to empty [per UI](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L317) separately for web-admin and web-client, you can try `SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__SHORT_NAME` if you really want to do it via env vars.

**Comment by carlosV2** [comment]
Ah! You are right, many thanks. I finally managed to change the short name. The version, however is still showing. Is there a way to remove it?
![image](https://github.com/drakkan/sftpgo/assets/2642839/b60b28b7-843e-4173-b557-aba1aeeb9751)

**Comment by carlosV2** [comment]
Ah! I didn't realise they where different. I managed to change it now, thank you! However, I was expecting that, by providing a short name, I could get rid of the version but I can still see it. Do you know how I can remove the version at least from the login page?
![image](https://github.com/drakkan/sftpgo/assets/2642839/62520d40-2d5a-435d-b60d-74072880d5bd)

**Comment by crabique** [comment]
The version info was actually removed from the template 3 months ago [in this commit](https://github.com/drakkan/sftpgo/commit/c71f0426ae2ec2c5609fb9677d97f13dfdce59d1#diff-a83a9204f02d597e499cd7e05ef467b147e35e6d3047dee9e5a570425de864d0),  but release `2.5.6` still had it.

**Comment by carlosV2** [comment]
Ah! That makes sense. Many thanks for looking into this 🙇🏼‍♂️.

Do you know when is the next release expected to be dropped?

**Comment by carlosV2** [comment]
Ah! That makes sense. Many thanks for looking into this 🙇🏼‍♂️.

Do you know when is the next release expected to be dropped?

**Comment by drakkan** [comment]
@crabique thank you

**Comment by DaniW42** [comment]
@drakkan Is it planned to come up with a env variable or ui setting to hide the "Go to WebAdmin" link?
