### ISSUE TITLE
[Bug]: Emoji In ACME Domain Name Issue?

### ISSUE THREAD

**Issue by chris027** [drakkan/sftpgo#1559]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hi, I'm trying to "request free TLS certificates for your SFTPGo services using the ACME protocol and the HTTP-01 challenge type." But, running into the error below. I'm wondering if it's related to the fact that I'm using a domain name with emojis in it, that gets converted to punycode. 

Error:

unable to obtain certificates: error: one or more domains had a problem: [XXXXX MY DOMAIN XXXXX] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: [XXXXX IP ADDRESS XXXXX]: Invalid response from http://[XXXXX MY DOMAIN XXXXX]/.well-known/acme-challenge/93SKvH2pyeC2o3nMPyeQ2MV7UNQktCMhnjPkmrqgRCg: 404

### Steps to reproduce

1. Go to the web admin > configurations
2. Enter domain name with emojis in it
3. Click submit button.

### Expected behavior

I expected to receive a TLS certificate, but didn't. 

### SFTPGo version

2.5.6

### Data provider

local storage

### Installation method

Other

### Configuration

config - I haven't changed anything yet. I'm just getting started testing this. 

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional info

I'm using Ubuntu 22.04 on a LattePanda Delta single board computer and used ppa:sftpgo/sftpgo to install SFTPGo.

**Comment by chris027** [comment]
Not a bug. I have it working now with an emoji domain.

**Comment by drakkan** [comment]
Never tested emoji domains. Glad it works
