### ISSUE TITLE
sftp set password， not connect

### ISSUE THREAD

**Issue by fangaofeng** [drakkan/sftpgo#156]
I have tested password for authority:
FileZilla:
   can not connect.
bitvise ssh client:
 can not connect.

but when i set publickey+password:
FileZilla:
   can connect.
bitvise ssh client:
   can connect.
sftpgo version:1.0.0
windows 10

**Comment by drakkan** [comment]
This works for me, please read the log file and/or post the relevant part here to understand what's wrong in your setup, thank you

**Comment by fangaofeng** [comment]
this is logger。username：test，password：test. 


{"level":"debug","time":"2020-08-25T15:12:02.415","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"cannot login user \"test\", login method \"password\" is not allowed"}
{"level":"debug","time":"2020-08-25T15:12:02.415","sender":"connection_failed","client_ip":"10.11.2.22","username":"test","login_type":"password","error":"Login method \"password\" is not allowed for user \"test\""}
{"level":"debug","time":"2020-08-25T15:12:07.171","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"cannot login user \"test\", login method \"password\" is not allowed"}
{"level":"debug","time":"2020-08-25T15:12:07.171","sender":"connection_failed","client_ip":"10.11.2.22","username":"test","login_type":"password","error":"Login method \"password\" is not allowed for user \"test\""}
{"level":"debug","time":"2020-08-25T15:12:10.912","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"cannot login user \"test\", login method \"password\" is not allowed"}
{"level":"debug","time":"2020-08-25T15:12:10.912","sender":"connection_failed","client_ip":"10.11.2.22","username":"test","login_type":"password","error":"Login method \"password\" is not allowed for user \"test\""}
{"level":"info","time":"2020-08-25T15:12:24.017","sender":"httpd","method":"GET","proto":"HTTP/1.1","remote_addr":"127.0.0.1:49556","request_id":"pc-service1/RelV4bl6dJ-000029","uri":"http://localhost:8080/web/user/1","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","resp_status":200,"resp_size":23988,"elapsed_ms":1}
{"level":"info","time":"2020-08-25T15:12:30.483","sender":"httpd","method":"POST","proto":"HTTP/1.1","remote_addr":"127.0.0.1:49556","request_id":"pc-service1/RelV4bl6dJ-000030","uri":"http://localhost:8080/web/user/1","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","resp_status":303,"resp_size":0,"elapsed_ms":29}
{"level":"info","time":"2020-08-25T15:12:30.488","sender":"httpd","method":"GET","proto":"HTTP/1.1","remote_addr":"127.0.0.1:49556","request_id":"pc-service1/RelV4bl6dJ-000031","uri":"http://localhost:8080/web/users","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","resp_status":200,"resp_size":12048,"elapsed_ms":1}
{"level":"info","time":"2020-08-25T15:12:36.162","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"User id: 1, logged in with: \"password\", username: \"test\", home_dir: \"/home/sangda/ftptest\" remote addr: \"10.11.2.22:56151\""}
{"level":"debug","time":"2020-08-25T15:12:36.180","sender":"dataprovider_sqlite","connection_id":"","message":"last login updated for user \"test\""}
{"level":"debug","time":"2020-08-25T15:12:36.181","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"connection added, num open connections: 1"}
{"level":"debug","time":"2020-08-25T15:12:36.181","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"connection added, num open connections: 1"}
{"level":"debug","time":"2020-08-25T15:12:36.216","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"requested list file for dir: \"/home/sangda/ftptest\""}
{"level":"debug","time":"2020-08-25T15:12:36.594","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"requested list file for dir: \"/home/sangda/ftptest\""}
{"level":"debug","time":"2020-08-25T15:13:20.369","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"connection closed, sending exit status"}
{"level":"debug","time":"2020-08-25T15:13:20.369","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"sent exit status {Status:0} error: EOF"}
{"level":"debug","time":"2020-08-25T15:13:20.369","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"connection removed, num open connections: 0"}
{"level":"debug","time":"2020-08-25T15:13:34.008","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"connection closed, sending exit status"}
{"level":"debug","time":"2020-08-25T15:13:34.008","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"sent exit status {Status:0} error: EOF"}
{"level":"debug","time":"2020-08-25T15:13:34.008","sender":"sftpd","connection_id":"a36aeb14e310299dfd30b1fbd57a942c40b163da0e09e2cf2b73b223cd927e0f","message":"connection removed, num open connections: 0"}

**Comment by drakkan** [comment]
Hi,

as you can see from the logs you disabled password login method

```
Login method "password" is not allowed for user "test"
```

please remove this configuration for the user "test" if you need to login using a password, thank you

**Comment by fangaofeng** [comment]
Think you . i config denied login method : keyword_inactive ,can login .

**Comment by drakkan** [comment]
Hi, assuming you are using the built-in web interface in the following screen

![Schermata del 2020-08-25 12-47-27](https://user-images.githubusercontent.com/553263/91165633-4b0e4080-e6d1-11ea-9e68-f64afffc54b3.png)

If you don't select anything, all login methods will be allowed,

if you select "password" you will not be able to log in using a password.

If you don't need any particular restrictions, you don't have to select anything
