### ISSUE TITLE
Add a mechanism to read AWS S3 access credentials from environment variables

### ISSUE THREAD

**Issue by DeflateAwning** [drakkan/sftpgo#1562]
### Is your feature request related to a problem? Please describe.

In a deployment on AWS, I'd like to manage the S3 bucket access controls through IAM via policy, which generates the access credentials as environment variables.

### Describe the solution you'd like

I'd like to be able to type something like `[ENV_VAR:AWS_ACCESS_KEY]` in the text fields to setup an S3 virtual folder, and have SFTPGo read the environment variable for those fields as such.

### Describe alternatives you've considered

Currently you have to generate an insecure IAM user (against all the AWS warnings as you go through the process), and then paste in the secret values. These values aren't automatically rotated though, and have to enter the clipboard of developers.

If this already exists, I couldn't find it in the docs.

### What are you using SFTPGo for?

Medium business

### Additional context

![image](https://github.com/drakkan/sftpgo/assets/11021263/e02b363b-1d4b-43ee-b3d3-7897d621baf9)

**Comment by drakkan** [comment]
This is already supported in the same way as the AWS SDK

**Comment by DeflateAwning** [comment]
Can you elaborate, and point to the applicable documentation?

**Comment by washaq00** [comment]
> Can you elaborate, and point to the applicable documentation?

@DeflateAwning Did you figure it out?

**Comment by DeflateAwning** [comment]
No I did not; would you mind sharing the solution?

**Comment by drakkan** [comment]
There is nothing SFTPGo specific to document here. SFTPGo uses the AWS SDK, so just refer to the AWS docs, SFTPGo can use env vars the same way as AWS CLI for example.

I'm sorry if my first reply seemed or was rude. It probably would have been better not to reply at all. 
I'm struggling to make the SFTPGo development financially sustainable and It's quite annoying to see SFTPGo used in environments where you pay for everything else and ask for free support here.

**Comment by DeflateAwning** [comment]
My company is paying for a support license via the AWS Marketplace. We appreciate this project and your development efforts! :)

It would be great to be able to inject the S3 credentials as enviroment variables per-profile. I'm still not really sure how to do that though. No worries if you can't work on this; not essential, but a useful feature imo

**Comment by drakkan** [comment]
@DeflateAwning If you are using our Marketplace offer please contact us directly as explained in our AWS page. 

![Schermata del 2024-10-07 10-52-46](https://github.com/user-attachments/assets/742256e4-44e5-470f-8cff-58b7833ad416)

GitHub issues/discussions are for users asking for free support

**Comment by DeflateAwning** [comment]
I'm not asking for support; I'm requesting that this feature be implemented and/or documented

**Comment by drakkan** [comment]
> I'm not asking for support; I'm requesting that this feature be implemented and/or documented

yes, if you are a commercial user contact us directly, your requests will have higher priority, especially if we see that your subscription has been active for a long time. Thank you
