### ISSUE TITLE
HTTPFS: SFTPGo Not Invoking REST API Calls for File Operations

### ISSUE THREAD

**Issue by S-acoba** [drakkan/sftpgo#1563]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I am currently utilizing SFTPGo in conjunction with a custom storage backend developed in Python Flask, compliant with the REST API documentation outlined in the httpfs.yaml file :
 https://github.com/drakkan/sftpgo/blob/main/openapi/httpfs.yaml.
Upon testing, I have observed that SFTPGo successfully invokes API calls such as /mkdir/{Name}, /readdir/{Name}, and /chmod/{name} .. . However, when it comes to file operation cases, specifically /open/{name} and /create/{name}, SFTPGo does not invoke these REST API calls at all.

This issue is impacting the functionality of my custom storage backend, as these operations are crucial for the proper operation of my application. I would appreciate any assistance in diagnosing and resolving this issue.

### Steps to reproduce

1.Configure SFTPGo with the custom storage backend.
2.Attempt to perform file operations using the /open/{name} and /create/{name} endpoints.
3.Observe that SFTPGo does not invoke the REST API calls for these operations.

### Expected behavior

SFTPGo should invoke the REST API calls for file operations as it does for other operations.
Actual Result: SFTPGo does not invoke the REST API calls for file operations.

### SFTPGo version

2.5.5

### Data provider

Mysql 8.0

### Installation method

Community Deb package

### Configuration

- Both SFTP and FTP Mode Enabled
- Data provider MySQL 
- post upload hook URL
- post download hook URL 

### What are you using SFTPGo for?

Professional user, 1 person business

### Additional info

Python Version: Python 3.8.10 
Flask Version : 3.0.2
Operating System: Ubuntu server 20.04

**Comment by drakkan** [comment]
I think this is an issue on your side
