### ISSUE TITLE
Templates user.html not correct

### ISSUE THREAD

**Issue by rmoreRojoli** [drakkan/sftpgo#157]
App version: 1.0.0
Platform: Windows

After copying the templates and static folder (pulled from latest master) to the C:\Program Files\SFTPGo which is the root path for the app, running the server with bolt backend the user add page is broken at the following section:

```
<div class="form-group row">
        <label for="idProtocols" class="col-sm-2 col-form-label">Denied protocols</label>
        <div class="col-sm-10">
            <select class="form-control" id="idProtocols" name="denied_protocols" multiple>
                template: user.html:77:37: executing "page_body" at <.ValidProtocols>: can't evaluate field ValidProtocols in type httpd.userPage
```

After removing that section several other sections report similar issues and after removing all affected sections it won't submit due to missing requirements.
Can you provide a working templates folder that works with the latest release?

**Comment by drakkan** [comment]
Please better explain what are you doing, you cannot use the latest templates with 1.0.0 version. Templates must match the SFTPGo version or they will not work

**Comment by rmoreRojoli** [comment]
After downloading the source of the 1.0.0 release the templates are working, closing the ticket.
