### ISSUE TITLE
User rights - Removal of features

### ISSUE THREAD

**Issue by Otsegox** [drakkan/sftpgo#1572]
### Is your feature request related to a problem? Please describe.

Not related to a problem

### Describe the solution you'd like

I would like the ability to remove the Sharing feature users have.  I don't want users to upload files, then be able to give other people links to those files.

### Describe alternatives you've considered

I've considered write-only access, but they cannot upload folders via drag-and-drop. Only files.

### What are you using SFTPGo for?

Medium business

### Additional context

For instance. These folks need to upload a folder to us. This folder has multiple folders in it. Each folder has multiple files in it. To upload the entire thing via the write-only access, it would take 30 mins just to navigate all of the folders.  And none of the files they upload should be able to be shared.

**Comment by useronkel** [comment]
Hi.
That's possible out-of-the-box:
Log in as admin, edit user and open the ACL-Accordion.
There you will find the settings for "Web client/REST API".
Set it to shares-disabled, shares-without-password-disabled
Should work for this particular user now ;-)

**Comment by jsuwala** [comment]
For anyone referring to this issue when using the API, the "shares-disabled" value is set in the "filters" property of a user. For example, see below:

```json
{
  "username":        "${USERNAME}",
  "email":           "${EMAIL}",
  "password":        "${PASSWORD}",
  "status":          1,
  "auth_methods":    ["password"],
  "public_keys":     [],  
  "filesystem": {    
  },
  "filters": {
    "web_client": ["shares-disabled"]
  }  
}
```
