### ISSUE TITLE
HTTP upload limited to 30 - Any way to increase this?

### ISSUE THREAD

**Issue by Otsegox** [drakkan/sftpgo#1574]
### Is your feature request related to a problem? Please describe.

It's not related to a known problem

### Describe the solution you'd like

I would like to configure the HTTP interface to allow uploading for many, many files. 4k files would be possible in my use-case.

### Describe alternatives you've considered

Zipping the files is working for now, but that adds extra steps to my users, and they are complaining about going back to not having to zip them. We previously used a paid, proprietary software that allowed uploading unlimited files via the web interface.

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment]
Currently there is no way. Perhaps it will be added to a future version if useful to users/companies helping the project stay alive

**Comment by hugolesta** [comment]
Hello @drakkan 

We have a similar issue that's producing errors in our production environment (2nd time) and it seems to be related to the same limit. 

<img width="1744" alt="Screenshot 2024-05-31 at 15 31 52" src="https://github.com/drakkan/sftpgo/assets/6575715/3bb4f888-f3a4-4ba3-8e53-7fcb05253997">


How do you think this issue should be managed? An HTTP limit of 30 is not that high
