### ISSUE TITLE
Is there a way to set permissions of files uploaded via ftp? 

### ISSUE THREAD

**Issue by nirurin** [drakkan/sftpgo#1581]
### Is your feature request related to a problem? Please describe.

I use sftpgo to create an ftp folder that my camera can automatically upload to. This works fine. But the permissions for the files when they get uploaded seem to be rw/r/r which causes issues when nextcloud (which has access to that same folder) tries to move or delete files. 

### Describe the solution you'd like

WOuld be nice to  set an automated set of permissions for all files uploaded to the folder. 

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Hello, you can set an umask for this, at system level or only for the SFTPGo process

**Comment by nirurin** [comment]
> Hello, you can set an umask for this, at system level or only for the SFTPGo process

Hi, could you please let me know how I would do this with sftpgo  through docker?

**Comment by drakkan** [comment]
> > Hello, you can set an umask for this, at system level or only for the SFTPGo process
> 
> Hi, could you please let me know how I would do this with sftpgo through docker?

please check the docs https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L25

**Comment by nirurin** [comment]
I have added UMASK 770 to the docker compose in unraid, and the container has started up, but files uploaded through it still end up as -rw-r--r-- 

![Screenshot 2024-04-06 204407](https://github.com/drakkan/sftpgo/assets/3751273/80655dd4-911a-43dc-841d-08eb338da153)

I don't seem to have a sftpgo.json file in the docker appdata/config folders for sftpgo, is it hidden inside the docker image filesystem somewhere? How do I get to it?

**Comment by nirurin** [comment]
> > > Hello, you can set an umask for this, at system level or only for the SFTPGo process
> > 
> > 
> > Hi, could you please let me know how I would do this with sftpgo through docker?
> 
> please check the docs https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L25

How do I get to this file tthrough the docker command line?

**Comment by nirurin** [comment]
> Hello, you can set an umask for this, at system level or only for the SFTPGo process

Hello? Anyone got any ideas on this?

**Comment by krezack** [comment]
Just had the same issue and figured it out. So, for anyone else who ends up here while trying to fix this.
https://sftpgo.github.io/2.6/env-vars/

In unraid add a new variable:
Key: SFTPGO_COMMON__UMASK
Value: 000

![image](https://github.com/user-attachments/assets/44bdb8cf-9f22-4d44-b120-f72b6a1cf234)

**Comment by NelsonClark** [comment]
> Just had the same issue and figured it out. So, for anyone else who ends up here while trying to fix this. https://sftpgo.github.io/2.6/env-vars/
> 
> In unraid add a new variable: Key: SFTPGO_COMMON__UMASK Value: 000
> 

Thanks!
