### ISSUE TITLE
FTP-like TOTP auth in SFTP

### ISSUE THREAD

**Issue by Colorata** [drakkan/sftpgo#1583]
### Is your feature request related to a problem? Please describe.

It is not possible to log into SFTP with TOTP using Nautilus(bug). Also, I can't find any SFTP client for Android that supports this feature.

### Describe the solution you'd like

Give an option to authenticate just like FTP: use combination of password and TOTP code in single line

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
For FTP there is no other way. I think you can implement this using a custom auth hook/plugin
