### ISSUE TITLE
Having it so UMASK works to set default permissions for files uploaded via sftpGO

### ISSUE THREAD

**Issue by nirurin** [drakkan/sftpgo#1588]
### Is your feature request related to a problem? Please describe.

When files are uploaded via sftpgo, they have rw--r--r  permissions for 'nobody' (this is on an unraid docker container installed via CA). 
However this means the files are compatible with Nextcloud. Nextcloud can see the files, but trying to move or delete them causes an error. 

### Describe the solution you'd like

I'd like to be able to set permissions for the files to have 777 permissions by default. 

### Describe alternatives you've considered

I have tried adding in an extra parameter '--UMASK 777' when making the container but that didn't have any effect, I then added a new variable field with the UMASK key and the value of 777, but that also had no effect.

Uploaded files by default have the owner 'nobody' and the permissions of -rw--r--r- when I need for them to have rwrwrw.

I know there's a umask line in the sftpgo.json file, at least according to the documentation, but there's nothing that tells me how to actually access or edit that file in docker. 

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by nirurin** [comment]
Anyone? Is this just impossible? Anyone know of a better ftp container that supports this?

**Comment by drakkan** [comment]
Please don't ask the same question over and over, check the documentation instead. As for our [support policy](https://github.com/drakkan/sftpgo?tab=readme-ov-file#support-policy) we don't provide step-by-step support, sorry

**Comment by nirurin** [comment]
The issue is that your documentation doesn't help. The only vague
suggestion it gives doesnt work. It's completely useless.

Oh well ill look for an alternative application and warn people away from
this one.
