### ISSUE TITLE
sftpgo.json should be accessible (docker)

### ISSUE THREAD

**Issue by nirurin** [drakkan/sftpgo#1598]
### Is your feature request related to a problem? Please describe.

The only way to solve my problem with the software, is apparently to access and edit sftpgo.json. However this file is not exposed during the docker install, and does not seem to be available anywhere within the docker image (as far as docker is concerned, the file doesn't exist at all?

### Describe the solution you'd like

The file should exist, or at least be easier to find. 

### Describe alternatives you've considered

Moving to other software. 

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by MilesTEG1** [comment]
I concur to this.

Is there a way to access to this file with bind mount when using docker-compose ?
