### ISSUE TITLE
external auth for web interface

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#160]
Ciao, you should add external authentication for the configuration interface as well as the file-based one also an external one so that you can authenticate the admin also on external sources. 

thank you.

**Comment by drakkan** [comment]
Hi,

can you please better explain your use case?

Adding external auth for REST API/Web interface seems to much, we don't have data providers users for them, if you need authentication for REST API/Web admin you can use a file conforming to the `htpasswd` format. You can also update the users in this file without restarting SFTPGo. An alternate solution is to set up a reverse proxy and authenticate using the web server authentication

**Comment by fdefilippo** [comment]
ciao,  obviously I had thought about the reverse proxy, I will do so, at most I will reopen the issue :)

thnx.

**Comment by drakkan** [comment]
please see #197
