### ISSUE TITLE
[Bug]: Filenames not displayed

### ISSUE THREAD

**Issue by johann34** [drakkan/sftpgo#1606]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I'm using SFTPGo for my personal needs. 
It's a great tool but i'm facing a displaying bug.
When I use SFTPGo WebClient on smartphone (screen size of 6.67 inches), the file list is not shown fine, the filenames are missing.
I maybe suspect there is a trouble with the length of one of my file names.
It's possible to fix it ?
Thanks a lot for your attention.

![Screenshot_2024-05-01-15-54-50-967_com brave browser](https://github.com/drakkan/sftpgo/assets/77899308/ebf5e3a4-6c2a-4025-9b80-84c397074446)

![Screenshot_2024-05-01-15-58-07-380_com cpuid cpu_z](https://github.com/drakkan/sftpgo/assets/77899308/a2a2203c-9d42-429c-b992-00e70ba52261)

Files list correctly shown on desktop browser : 
![files_ok](https://github.com/drakkan/sftpgo/assets/77899308/0e983e27-dc91-4814-b4ab-1b5a52ef225e)

### Steps to reproduce

1. 
2.
3.

### Expected behavior

Files list is shown properly with all file names

### SFTPGo version

2.5.6

### Data provider

sftpgo

### Installation method

Other

### Configuration

config

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Please reopen if this also happens with the development version. Thank you
