### ISSUE TITLE
Support Backingup CiscoDNA by supporting the uname command

### ISSUE THREAD

**Issue by Macleykun** [drakkan/sftpgo#1608]
### Is your feature request related to a problem? Please describe.

We want to make backups from our CiscoDNA but we noticed that we get an error:
CiscoDNA:
Remote server is not supported: Error running uname on remote server: .
SFTPGo:
ssh command not enabled/supported: \"uname

In the documentation: https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/dna-center/2-2-2/admin_guide/b_cisco_dna_center_admin_guide_2_2_2/b_cisco_dna_center_admin_guide_2_2_2_chapter_0110.pdf 
it's never mentioned that uname needs to be able to run, but that's ussually a given.

### Describe the solution you'd like

To support running the uname command, so that CiscoDNA can make backups to SFTPGo using Rsync.

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment]
Support for `uname` may be added but we have no way to test CiscoDNA. Generally is simpler to ship such additions if we can establish a channel for reciprocal access and trust via a support contract. Thank you

**Comment by Macleykun** [comment]
tottaly understand! i do appricate it that you do respond to these questions!
Have a great weekend!

**Comment by Macleykun** [comment]
> Support for `uname` may be added but we have no way to test CiscoDNA. Generally is simpler to ship such additions if we can establish a channel for reciprocal access and trust via a support contract. Thank you

sorry with a support contact you mean that if i can convince the company i work for to pay for the basic plan right?
I want to convince my company to do so eventually, but need to build a good case why they should

**Comment by drakkan** [comment]
> > Support for `uname` may be added but we have no way to test CiscoDNA. Generally is simpler to ship such additions if we can establish a channel for reciprocal access and trust via a support contract. Thank you
> 
> sorry with a support contact you mean that if i can convince the company i work for to pay for the basic plan right? I want to convince my company to do so eventually, but need to build a good case why they should

We offer several form of support. We generally don't add new features with Basic support. 

In an ideal world, companies would support open source software for its maintenance. What if SFTPGo is no longer maintained? Protocols evolve and new algorithms need to be supported, bugs and security issues need to be fixed. Even if the current features are good for your use case, they won't be in 2 or 3 years, SFTPGo needs ongoing efforts and maintenance. 

Also, the open source license gives you freedom but not the guarantee of help. What if you find a blocking issue?

More info

https://sftpgo.github.io/latest/#support

**Comment by rommess** [comment]
Hi @Macleykun ,
we have the same message with our DNA "ssh command not enabled/supported: "uname"
did you find any solution since ?
