### ISSUE TITLE
[Bug]: Power Platform is returning unknown ssh protocol identification error

### ISSUE THREAD

**Issue by bruhnkk** [drakkan/sftpgo#1618]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

similar to https://github.com/drakkan/sftpgo/discussions/1355

If you try to use Microsoft Power Platform SFTP Connector, you aren't be able to connect to SFTPGO.

### Steps to reproduce

1. Open make.powerapps.com
2. Click on Flows (sometimes hidden under ... More in the left menu bar)
3. Click on New Flows
4. Search for SFTP - SSH
5. fill out the informations with the target sftpgo server<img width="404" alt="grafik" src="https://github.com/drakkan/sftpgo/assets/118737649/e8c1620f-a298-4094-add9-46ace24fbb57">
6. Get following Error hint: <img width="439" alt="grafik" src="https://github.com/drakkan/sftpgo/assets/118737649/6c09439c-571d-4676-a511-1fd309b2dbab">
7. Open Browser Developer Tools and check network tab
8. Find this detailed error description: <img width="977" alt="grafik" src="https://github.com/drakkan/sftpgo/assets/118737649/854f4ca0-3d66-412c-a23f-2e0de19fabfb">

### Expected behavior

1. Open make.powerapps.com
2. Click on Flows (sometimes hidden under ... More in the left menu bar)
3. Click on New Flows
4. Search for SFTP - SSH
5. fill out the informations with the target sftpgo server<img width="404" alt="grafik" src="https://github.com/drakkan/sftpgo/assets/118737649/e8c1620f-a298-4094-add9-46ace24fbb57">
6. Connection worked successful

### SFTPGo version

?

### Data provider

?

### Installation method

Community Docker image

### Configuration

config

### What are you using SFTPGo for?

Enterprise

**Comment by drakkan** [comment]
Just tested, it works for me. We provide commercial support if required

https://sftpgo.com/#pricing
