### ISSUE TITLE
[Bug]: Custom S3 endpoint => bucket in host

### ISSUE THREAD

**Issue by asrenzo** [drakkan/sftpgo#1624]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hi,

I use a custom S3 cluster for my tests (a minio cluster with a canonical host aka storage.mydomain.com).
Every request issued by sftpgo fails to reach my Minio cluster because every request updates the host definition with the bucket I wrote in the storage définition of my user profile => https://bucketname.storage.mydomain.com/

Thus none of my requests can reach my minio cluster because bucketname.storage.mydomain.com is not defined in my DNS server.

Am I doing something wrong ?

### Steps to reproduce

1. Setup a local Minio cluster https://storage.mydomain.com
2. Setup a new user with a S3 filesystem accound
3. Bucket = bucketname
4. Region = region-1
5. Access Key = mykey 
6. Access Secret = mysecret
7. Endpoint = https://storage.mydomain.com
8. Use filezilla or sftp command to log in sftpgo with this account

=> Error : 2024-05-20T15:55:16.558 DBG error retrieving directory entries: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "https://bucketname.storage.mydomain.com/?delimiter=%2F&list-type=2&max-keys=5000&prefix=":

### Expected behavior

Shouldn't we call https://storage.mydomain.com/ and not https://bucketnamestorage.mydomain.com/ ?

### SFTPGo version

Latest Docker Alpine : SFTPGo 2.6.0 19e9857f

### Data provider

Mysql 

### Installation method

Community Docker image

### Configuration

Only volumes path

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
I think you are using path-style addressing on the MinIO side, please enable this checkbox

![Schermata del 2024-05-20 19-17-39](https://github.com/drakkan/sftpgo/assets/553263/0e25d7e4-6ee2-4896-a783-31b02281743a)

**Comment by asrenzo** [comment]
This was the exact right answer to my question !
THX !!
