### ISSUE TITLE
[Bug]: "How to use this image" link on docker hub is broken

### ISSUE THREAD

**Issue by Mathieu-COSYNS** [drakkan/sftpgo#1627]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

If you click on the link [SFTPGo GitHub repository](https://github.com/drakkan/sftpgo/blob/master/docker/README.md) on docker hub, you are redirected to the old documentation in github that don't exist anymore since it was moved to <https://sftpgo.github.io/latest/docker/>
![image](https://github.com/drakkan/sftpgo/assets/64072917/56502b31-5afa-4a30-a2f2-dd2e0f4fa460)

### Steps to reproduce

1. Go to <https://hub.docker.com/r/drakkan/sftpgo?uuid=D596746C-D11D-401E-A48C-2CABE8A0B7B8>
2. Click on the link [SFTPGo GitHub repository](https://github.com/drakkan/sftpgo/blob/master/docker/README.md) at the bottom of the page

### Expected behavior

Redirect to <https://sftpgo.github.io/latest/docker/>

### SFTPGo version

v2.6.0

### Data provider

/

### Installation method

Community Docker image

### Configuration

config

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Fixed, thanks
