### ISSUE TITLE
Feature request: user configuration take effect immediate

### ISSUE THREAD

**Issue by ynqjwsm** [drakkan/sftpgo#163]
I found that many configurations (such as user directory permissions, etc.) need to take effect after the user disconnects the sftp connection and reconnects. Can the user configuration take effect immediately?

**Comment by drakkan** [comment]
Hi,

this is technically possible:

1) a simple way is to do a new dataprovider query before each operation, this will impact performance. Currently only WebDAV do a new query for each request and it is very slow. 
2) a more appropriate way is to update the user object for each connected user after a configuration change. This will require some effort, a patch is welcome 

If you don't want to provide a patch, I suggest, at least for now, to disconnect the user via REST API, after a configuration change, if you need to apply the new configuration immediately

**Comment by drakkan** [comment]
Hi, you can now force user disconnection after an update.

I tested pure-ftpd virtual users and the configuration changes will take effect for new logins there too. If you delete a pure-ftpd virtual users it will work until disconnection.

After this change SFTPGo behaves this way:

- if you delete a connected user it will be automatically disconnected
- if you update a logged in user you can choose to force a new login to apply the new configuration or to leave him logged in using the old configuration

Applying the new configuration "live" (without disconnecting the user) is quite complicated, you have to force the disconnection in some cases (for example password,home dir,backend provider change ecc..) and update the user's data without disconnect it in other cases. If you need this feature please submit a pull request or consider sponsoring this development.

Thank you
