### ISSUE TITLE
[Bug]:  sftp direct login will not be updated to the new password

### ISSUE THREAD

**Issue by jojo642** [drakkan/sftpgo#1635]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

After AD/LDAP user change password, http login password will be updated, sftp direct login will not be updated to the new password (still need to use the old password).

### Steps to reproduce

1、AD/LDAP user login sftp
2、Changing user passwords on AD/LDAP platforms
3、 AD/LDAP user login to sftp, new password doesn't work, old one does
4、AD/LDAP user login web, new password succeeds, old one doesn't
5、AD/LDAP user login sftp, new password succeeds, old one doesn't

### Expected behavior

The sftp protocol login prioritizes the use of the authentication plugin over local passwords.

### SFTPGo version

drakkan/sftpgo:v2.6.0-plugins

### Data provider

sqllite

### Installation method

Community Docker image

### Configuration

  "plugins": [
    {
      "cmd": "/usr/local/bin/sftpgo-plugin-auth",
      "type": "auth",
      "auth_options": {
        "scope": 1
      },
      "args": [
            "serve",
        "--ldap-url=ldap://10.10.xx.11:389",
        "--ldap-base-dn=DC=x-xx,DC=xxx",
        "--ldap-bind-dn=CN=ftpadmin,OU=Users,OU=xxxx,DC=x-xxx,DC=xxx",
        "--ldap-password=xxxx",
                "--ldap-search-query=(&(objectClass=user)(sAMAccountType=805306368)(sAMAccountName=%username%))",
        "--skip-tls-verify=1"
      ],
          "auto_mtls": true
    }
  ]

### What are you using SFTPGo for?

Small business (3-person firm with file exchange?)

**Comment by drakkan** [comment]
Closing in favor of #1642
