### ISSUE TITLE
Unable to rsync directory

### ISSUE THREAD

**Issue by Flameborn** [drakkan/sftpgo#164]
Hello,

I'm currently trying to use SFTPGo to rsync a directory.

I've enabled the *rsync* command in *enabled_ssh_commands*.

The server is running Arch, and SFTPGo v1.0.0-dev-9334273-2020-08-19T20:17:13Z, compiled from git. Rsync is installed.

The client is running Ubuntu 20.04, more or less out of the box configuration (Bash is the default shell, etc).

Both server and client have Rsync 3.2.3 (Protocol version 31) installed.

The server reports:

```
"new system command \"rsync\", with args: [--munge-links --server --sender -vvtre.iLsfxCIvu . /mnt/hd2/sounds] fs path \"/mnt/hd2/sounds\" quota check path \"/sounds/fakecontent\""}
command failed: \"rsync\" args: [--server --sender -vvtre.iLsfxCIvu . /sounds/] user: testuser err: permission denied"}
connection removed, num open connections: 0"}
```

The client command is>

```
rsync -rtv -e 'ssh -p 2022' testuser@mydomain.com:/sounds/ .
```

I tried with and without specifying a slash after the colon, as well as with and without specifying the *sounds* directory as a virtual folder.

The folder itself has RWX permissions specified for user, group and other (777).

Any help is greatly appreciated.

**Comment by drakkan** [comment]
Hi, 

this seems a filesystem level permission denied error. 

Please try to write to the destination directory as the user that execute SFTPGo (or with the uid/gid configured for your `testuser`) or try to run SFTPGo as root user (and leave to 0 uid/gid for `testuser`). Thank you

**Comment by Flameborn** [comment]
I am running SFTPGo as *root*, and my *sounds* directory has permissions 777 recursively, on subfolders and files.

According to *passwd -Sa*, there isn't a *testuser* created on the server. Does SFTPGo expect a real user on the system?

**Comment by drakkan** [comment]
> I am running SFTPGo as _root_, and my _sounds_ directory has permissions 777 recursively, on subfolders and files.
> 
> According to _passwd -Sa_, there isn't a _testuser_ created on the server. Does SFTPGo expect a real user on the system?

No SFTPGo uses virtual users that can be optionally mapped to a system user configuring a UID/GID, please post here your `sftpgo.json` and the output of these commands:

```
curl "http://127.0.0.1:8080/api/v1/version"
```

```
curl "http://127.0.0.1:8080/api/v1/user"
```

thank you

**Comment by Flameborn** [comment]
Thank you very much for your help.

My *sftpgo.json*:

```
{
  "sftpd": {
    "bind_port": 2022,
    "bind_address": "",
    "idle_timeout": 15,
    "max_auth_tries": 0,
    "umask": "0022",
    "banner": "",
    "upload_mode": 0,
    "actions": {
      "execute_on": [],
      "hook": ""
    },
    "host_keys": [],
    "kex_algorithms": [],
    "ciphers": [],
    "macs": [],
    "trusted_user_ca_keys": [],
    "login_banner_file": "",
    "setstat_mode": 0,
    "enabled_ssh_commands": [
      "md5sum",
      "sha1sum",
      "cd",
      "pwd",
      "scp",
"rsync"
    ],
    "keyboard_interactive_auth_hook": "",
    "proxy_protocol": 0,
    "proxy_allowed": []
  },
  "data_provider": {
    "driver": "sqlite",
    "name": "/var/lib/sftpgo/sftpgo.db",
    "host": "",
    "port": 5432,
    "username": "",
    "password": "",
    "sslmode": 0,
    "connection_string": "",
    "sql_tables_prefix": "",
    "manage_users": 1,
    "track_quota": 2,
    "pool_size": 0,
    "users_base_dir": "",
    "actions": {
      "execute_on": [],
      "hook": ""
    },
    "external_auth_hook": "",
    "external_auth_scope": 0,
    "credentials_path": "/var/lib/sftpgo/credentials",
    "pre_login_hook": ""
  },
  "httpd": {
    "bind_port": 8022,
    "bind_address": "0.0.0.0",
    "templates_path": "/usr/share/sftpgo/templates",
    "static_files_path": "/usr/share/sftpgo/static",
    "backups_path": "/var/lib/sftpgo/backups",
    "auth_user_file": "",
    "certificate_file": "",
    "certificate_key_file": ""
  },
  "http": {
    "timeout": 20,
    "ca_certificates": [],
    "skip_tls_verify": false
  }
}
```

Version:

```
{"version":"1.0.0-dev","build_date":"2020-08-19T20:17:13Z","commit_hash":"933427
3","features":["+metrics","+gcs","+s3","+bolt","+mysql","+pgsql","+sqlite","+portable"]}
```

Users:

```
[{"id":1,"status":1,"username":"testuser","expiration_date":0,"public_keys":["ssh-rsa KEY testuser@clientHost"],"home_dir":"/mnt/hd2","virtual_folders":[{"id":2,"mapped_path":"/mnt/hd/upload","used_quota_size":0,"used_quota_files":0,"last_quota_update":1594576245509,"virtual_path":"/uploads","quota_size":-1,"quota_files":-1}],"uid":0,"gid":0,"max_sessions":0,"quota_size":0,"quota_files":0,"permissions":{"/":["list","download"],"/uploads":["*"]},"used_quota_size":0,"used_quota_files":0,"last_quota_update":0,"upload_bandwidth":0,"download_bandwidth":0,"last_login":1598900194964,"filters":{"denied_login_methods":["password"]},"filesystem":{"provider":0,"s3config":{},"gcsconfig":{}}}]
```

**Comment by drakkan** [comment]
Hi,

I think this is the problem

```
"permissions": {
      "/": [
        "list",
        "download"
      ],
      "/uploads": [
        "*"
      ]
    },
```

You can use `rsync` only inside the `uploads` virtual path, you haven't granted the required virtual permissions on "/", all the "/" subfolders inherits the `/` permissions if no specific permissions are setted.

Please note that you cannot use `rsync` directly inside "/" since it contains a virtual folders, take a look at the limitations described [here](https://github.com/drakkan/sftpgo/blob/master/docs/ssh-commands.md). You will receive another error if you try this

**Comment by Flameborn** [comment]
> You can use `rsync` only inside the `uploads` virtual path, you haven't granted the required virtual permissions on "/", all the "/" subfolders inherits the `/` permissions if no specific permissions are setted.
Hmmm. I didn't see any new permission in the list regarding *rsync*. Since I am downloading only, I set the list/download permissions. What extra permissions am I missing?
> Please note that you cannot use `rsync` directly inside "/" since it contains a virtual folders, take a look at the limitations described [here](https://github.com/drakkan/sftpgo/blob/master/docs/ssh-commands.md). You will receive another error if you try this
This is a good catch, thank you! I'll have to move this folder to a subdirectory which does not have virtual folders.

**Comment by drakkan** [comment]
Hi,

you need to grant all the permissions listed [here](https://github.com/drakkan/sftpgo/blob/master/sftpd/ssh_cmd.go#L313) I'll add this to the docs. `rsync` is a system command SFTPGo starts it but it is not aware of its operations, the `rsync` command can create, delete, update files or directories it is not under SFTPGo control.

**Comment by Flameborn** [comment]
Ah, that makes sense.

Could you please also mention this for the other supported system commands too, e.g. *git-receive-pack*?

Thank you very much for your help!

**Comment by drakkan** [comment]
> Ah, that makes sense.
> 
> Could you please also mention this for the other supported system commands too, e.g. _git-receive-pack_?
> 
> Thank you very much for your help!

Sure I'all add the following to the next commit, thank you

... we currently support the following system commands:

- `git-receive-pack`, `git-upload-pack`, `git-upload-archive`. These commands enable support for Git repositories over SSH. They need to be installed and in your system's `PATH`.
- `rsync`. The `rsync` command needs to be installed and in your system's `PATH`.

At least the following permissions are required to be able to run system commands:

- `list`
- `download`
- `upload`
- `create_dirs`
- `overwrite`
- `delete`

For `rsync`  we cannot avoid that it creates symlinks so if the `create_symlinks` permission is granted we add the option `--safe-links`, if it is not already set, to the received `rsync` command. This should prevent to create symlinks that point outside the home directory.
If the user cannot create symlinks we add the option `--munge-links`, if it is not already set, to the received `rsync` command. This should make symlinks unusable (but manually recoverable).

**Comment by Flameborn** [comment]
Looks fantastic, thank you!
