### ISSUE TITLE
SHA1/RSA support

### ISSUE THREAD

**Issue by Termin0tor** [drakkan/sftpgo#1649]
### Is your feature request related to a problem? Please describe.

I noticed that there is no official SHA1/RSA support. I'm aware that this is quite an old algorithm, but there are some devices which are still using it, even 2 year old document scanners (e.g. Brother).

### Describe the solution you'd like

Official support for SHA1/RSA which can be manually activated, optionally only for one specific client IP.

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Already supported and disabled by default. Please check the doc to understand how to enable
