### ISSUE TITLE
bcrypt variants are not accepted

### ISSUE THREAD

**Issue by zhangyoufu** [drakkan/sftpgo#1650]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Adding a user with bcrypt password hash using `$2y$` prefix, the user cannot authenticate via FTP.

Related code only recognize `$2a$` prefix:
https://github.com/drakkan/sftpgo/blob/8269adf176b8c3599f4c3ac8d1dae9b8de3d7f13/internal/dataprovider/dataprovider.go#L95
https://github.com/drakkan/sftpgo/blob/8269adf176b8c3599f4c3ac8d1dae9b8de3d7f13/internal/dataprovider/dataprovider.go#L3372-L3375

The interesting part is that some other module does have a more complete bcrypt prefix list:
https://github.com/drakkan/sftpgo/blob/8269adf176b8c3599f4c3ac8d1dae9b8de3d7f13/internal/common/httpauth.go#L39

### Steps to reproduce

1. add a user with bcrypt password hash using `$2y$` prefix
2. login in to FTP server
3. password was rejected

### Expected behavior

password should be accepted

### SFTPGo version

2.6.0

### Data provider

memory

### Installation method

Community Docker image

### Configuration

unrelated

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Hello,

the code in httpauth.go must be compatible with files generated by external tools like `htpasswd`. 

For SFTPGo users bcrypt hashes are generated internally using the `$2a$` prefix. 
If you import them from an external system or generate them from php or similar, you have to write some code and then you can easily adapt/change the prefix. I don't see a valid use case here.
