### ISSUE TITLE
tftp support

### ISSUE THREAD

**Issue by ryanmerolle** [drakkan/sftpgo#1659]
### Is your feature request related to a problem? Please describe.

A bunch of devices still use tftp for loading firmware at boot.  This would be super useful in an all in one file server tool like this.

### Describe the solution you'd like

tftp support

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Hello, it was discussed in #411. I'm not sure it's worth it

**Comment by ryanmerolle** [comment]
> Hello, it was discussed in #411. I'm not sure it's worth it

Usually I’m pretty good at looking to see if there was an existing open or closed issue before posting. I was just looking for an all in one tool for file upload/download for IT workflows.  I guess nothing is stopping me from adding tftp process to the container and pointing it to the same volume.
