### ISSUE TITLE
Arch package permission too wide

### ISSUE THREAD

**Issue by HiFiPhile** [drakkan/sftpgo#166]
Hi,

I'm experimenting switching from Debian to Arch. With your AUR packages it's very convenient to setup sftpgo :)

I found that database stored in `\var\lib\sftpgo\sftpgo.db` has 644 permission, so everyone can peak the contient.

PS: I think it's even better to run under a dedicated system user.

**Comment by drakkan** [comment]
Hi, 

thank your for the suggestion.

I just changed the database permission for `sftpgo-bin` package.

I agree that running as normal user is a better choice but some user could experience permission issues. I have to think about this a bit more, thank you.

**Comment by HiFiPhile** [comment]
Tested work under majaro ;)

**Comment by drakkan** [comment]
Hi, please give a try to [sftpgo-git](https://aur.archlinux.org/packages/sftpgo-git/) PKGBUILD. It run the service as a dedicated user. However this will cause troubles while updating an existing installation, is better to backup the data, uninstall/install the new version and then restore the old data

**Comment by HiFiPhile** [comment]
Hi,

I tested the package, installation goes well. But when I remove it the service is not stopped, with `yay -Rns` flags generated files are still exist in `/etc/sftpgo` and `/var/lib/sftpgo`.

**Comment by drakkan** [comment]
Hi,

I just tryed to remove `openssh` inside a virtual machine

```
pacman -Rns openssh
```

after that:

```
ls -la /etc/ssh/
total 40
drwxr-xr-x  2 root root 4096 Sep 20 07:43 .
drwxr-xr-x 43 root root 4096 Sep 20 07:41 ..
-rw-------  1 root root  668 Feb  2  2018 ssh_host_dsa_key
-rw-r--r--  1 root root  609 Feb  2  2018 ssh_host_dsa_key.pub
-rw-------  1 root root  227 Feb  2  2018 ssh_host_ecdsa_key
-rw-r--r--  1 root root  181 Feb  2  2018 ssh_host_ecdsa_key.pub
-rw-------  1 root root  411 Feb  2  2018 ssh_host_ed25519_key
-rw-r--r--  1 root root  101 Feb  2  2018 ssh_host_ed25519_key.pub
-rw-------  1 root root 1679 Feb  2  2018 ssh_host_rsa_key
-rw-r--r--  1 root root  401 Feb  2  2018 ssh_host_rsa_key.pub
```

```
ps -ef | grep sshd
root         370       1  0 07:38 ?        00:00:00 sshd: /usr/bin/sshd -D [listener] 0 of 10-100 startups
root         470     370  0 07:38 ?        00:00:00 sshd: nicola [priv]
nicola       479     470  0 07:38 ?        00:00:00 sshd: nicola@pts/0
```

I'll try to stop the service inside `pre_remove` but generated files must be manually removed. I cannot find another PKGBUILD that take care about stopping a running service or removing generated files, am I wrong?

**Comment by HiFiPhile** [comment]
Hi,

I'm new to Arch, maybe it's their default behavior :)

**Comment by drakkan** [comment]
> Hi,
> 
> I'm new to Arch, maybe it's their default behavior :)

I agree that this is not ideal and I never noticed this behavior before, however it seems that no PKGBUILD cares.

For example:

- OpenSSH [install](https://github.com/archlinux/svntogit-packages/blob/packages/openssh/trunk/install)
- Postgres and apache have no install at all
- MariaDB [install](https://github.com/archlinux/svntogit-packages/blob/packages/mariadb/trunk/mariadb.install) has a `post_upgrade`

I'll try to stop the service in `pre_remove`. To delete the generated files I have to add them for example inside the `backup` section but since they aren't part of the file installed by the PKGBUILD itself (host keys are generated at startup) you'll get a warning

**Comment by drakkan** [comment]
Hi,

please try the latest `sftpgo-git` PKGBUILD after removing it the service is stopped (if active) and I added a warning about [leftover files](https://aur.archlinux.org/cgit/aur.git/tree/sftpgo-git.install?h=sftpgo-git#n12).

This is very similar to the tomcat [PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/packages/tomcat9/trunk/tomcat9.install)

I'll add these changes to the sftpgo's PKGBUILD once version 1.1.0 will be released, thank you.

**Comment by HiFiPhile** [comment]
Hi,

I've tried the package and it works well :)

In `sftpgo.sysusers`, I think we don't need shell access ?
```
u sftpgo 315 "SFTPGo user" /var/lib/sftpgo /bin/bash
```

**Comment by drakkan** [comment]
> Hi,
> 
> I've tried the package and it works well :)
> 
> In `sftpgo.sysusers`, I think we don't need shell access ?
> 
> ```
> u sftpgo 315 "SFTPGo user" /var/lib/sftpgo /bin/bash
> ```

You need to execute some commands as `sftpgo` user for example to inizialize a file based dataprovider. If I remove shell access `su - sftpgo` will not work. This user will be unable to login anyway

**Comment by HiFiPhile** [comment]
>If I remove shell access su - sftpgo will not work. 

You can add `-s /bin/bash` in `su` command.

**Comment by drakkan** [comment]
[Fixed](https://aur.archlinux.org/packages/sftpgo-git/) thank you!

You need to uninstall, manually remove the user and then reinstall to get the sftpgo user with no shell access

**Comment by HiFiPhile** [comment]
Do you think it's better to put logs in `/var/log/` , maybe create a folder `/var/log/sftpgo` ?

**Comment by drakkan** [comment]
logs go to the journal with the default configuration, do you want to create an empty log folder?

**Comment by HiFiPhile** [comment]
> logs go to the journal with the default configuration

I saw a log file in `/etc/sftpgo` so I thought it writes log there, but in fact it was from an old installation.
