### ISSUE TITLE
[Bug]: The language list should use the constant map 

### ISSUE THREAD

**Issue by mbrade** [drakkan/sftpgo#1660]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Adding a new language needs to have a change in the base.html file on two positions to work.
First line 175 adding a new entry to the constant and than later also in line 196:   supportedLngs: ["en", "it"]

Would be nice if only the constant lngs needs to be adjusted and supportedLngs uses the keys from the constant.

### Steps to reproduce

1. Add a new language file (in our case de)
2. Add a new entry in the  base.html
   const lngs = {
        en: { nativeName: 'English' },
        it: { nativeName: 'Italiano' },
        de: { nativeName: 'Deutsch' }
    };
3. 'Deutsch' is shown in the drop down but can not be choosen. It requires to add also "de" in supportedLngs.

### Expected behavior

Let the const lngs be the only variable that needs to be changed.

### SFTPGo version

2.6.0

### Data provider

https

### Installation method

Other

### Configuration

config

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Please make sure to respect our licensing when creating a derivative work:

https://sftpgo.com/compliance.html

Thank you.
