### ISSUE TITLE
Getting A sqlite3 Error When Attempting To Build 

### ISSUE THREAD

**Issue by mohan-nbs-ont** [drakkan/sftpgo#1662]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Intermittent `sqlite3` error when attempting to build

### Steps to reproduce

Clone the repository
```
git clone https://github.com/drakkan/sftpgo
cd sftpgo
CGO_ENABLED=0 go build -trimpath -ldflags "-w"
# github.com/drakkan/sftpgo/v2/internal/dataprovider
internal/dataprovider/sqlite.go:753:27: undefined: sqlite3.Error
```

### Expected behavior

```
CGO_ENABLED=0 go build -trimpath -ldflags "-w"
```
 - creates `go` binary - `sftpgo`

### SFTPGo version

2.6.99-dev

### Data provider

none

### Installation method

Other

### Configuration

```
sftpgo portable \
  --directory /tmp/sftp \
  --sftpd-port 10000 \
  --username bogus_user \
  --password 'bogus_pa$s' \
  --permissions "*" \
  --public-key "xxxxx"
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
Hi,

sqlite3 requires CGO, if you want to disable CGO also disable sqlite support. 

However sqlite will be automatically disabled if CGO is not enabled once I'll push this local commit in the next few days

[0001-add-cgo-to-build-constraints.zip](https://github.com/user-attachments/files/15888124/0001-add-cgo-to-build-constraints.zip)

If you are re-compiling to create a derivative work please make sure to read our [compliance](https://sftpgo.com/compliance.html) page. Thank you

**Comment by mohan-nbs-ont** [comment]
> Hi,
> 
> sqlite3 requires CGO, if you want to disable CGO also disable sqlite support.
> 
> However sqlite will be automatically disabled if CGO is not enabled once I'll push this local commit in the next few days

thank you!
I will wait for the change.
