### ISSUE TITLE
Add user has no way to actually add the user

### ISSUE THREAD

**Issue by yuppox** [drakkan/sftpgo#167]
Using the Windows binary.

When I go to "add user" in the web GUI, "denied protocols" is the last field. There is no "submit" button or any way to add a user. I also do not see paths (home dir, virtual folders).

**Comment by drakkan** [comment]
Hi,

can you provide some more details? Are you using version 1.0.0 or the latest Git? What browser are you using?

The "Add user" page contains a lot of form fields a scroll bar should appear

![Schermata del 2020-09-14 09-29-47](https://user-images.githubusercontent.com/553263/93056613-f4ab7680-f66c-11ea-8042-065d9cdbe1da.png)

**Comment by drakkan** [comment]
it seems to work fine for me using all modern browser. Please reopen providing more info if needed thank you
