### ISSUE TITLE
error: signal: killed when running completion script

### ISSUE THREAD

**Issue by jdmcd** [drakkan/sftpgo#168]
Hi there,

Thanks again for this great library :) I run a script that looks like the following when a file is uploaded:

```python3
#!/usr/bin/python3

import sys
import requests
import os
from datetime import datetime
import boto3
from botocore.exceptions import ClientError

requestType = sys.argv[1]
path = sys.argv[3]
newPath = sys.argv[4]
ncesID = sys.argv[2]

csvString = open(path,'r').read()
filename = path.split('/')[-1].lower()
api_key = "redacted"
endpoint = "redacted"
headers = {'redacted': api_key, 'Content-Type': 'application/json'}

if requestType == "rename":
    path = newPath

dataForRequest = {'schoolNcesId': ncesID, 'csvString': csvString, 'type': filename}
requests.post(endpoint, json=dataForRequest, headers=headers)
day = datetime.now().strftime("%m-%d-%Y")
time = datetime.now().strftime("%I-%M-%S-%P")
new_filename = f'{ncesID}/{day}/{time}.csv'

s3_client = boto3.client(
    's3',
    aws_access_key_id='redacted',
    aws_secret_access_key='redacted',
    region_name='redacted'
)

try:
    s3_client.upload_file(path, 'redacted', new_filename)
except ClientError as e:
    print(e)

os.remove(path)
```

Today when trying to upload a relatively small file (740kb) I spotted the following error in my logs:
```json
{"level":"debug","time":"2020-09-14T16:21:55.761","sender":"SFTP","connection_id":"","message":"executed command \"/app/upload.py\" with arguments: \"upload\", \"redacted\", \"/redacted\", \"\", \"\", elapsed: 30.002172376s, error: signal: killed"}
```

I'm not sure what's going on but it's causing the script to fail :/ Have you seen this error before?

**Comment by drakkan** [comment]
Hi,

external command are executed with a 30 seconds [timeout](https://github.com/drakkan/sftpgo/blob/master/common/actions.go#L115). This is [documented](https://github.com/drakkan/sftpgo/blob/master/docs/custom-actions.md): "The program must finish within 30 seconds".

From your logs I read `elapsed: 30.002172376s` so SFTPGo killed your script.

If we allow indefinite script execution and you upload for example 1000 files you could have 1000 scripts running at the same time and this will probably make your system unresponsive. 

However if you really want long running scripts a simple workaround is something like this (untested):

1) you configure SFTPGo to execute `/app/upload.sh`
2) `/app/upload.sh` contains something like this:

```
#!/bin/sh

/app/upload.py &
```

SFTPGo can expose S3 over SFTP/FTP/WebDAV directly you don't need to upload files yourself. Can you please better explain your use case? I'm just curious

**Comment by jdmcd** [comment]
Ah - that makes perfect sense, thanks for clarifying. I think I missed that statement in the docs. 

Regarding the usecase, I think the timeout is actually happening on my server, not on S3. So I will investigate that. I've been meaning to look into SFTPGO's native S3 functionality but haven't had a chance yet to look. 

Right now I shipping off the file to my server for processing but in the future it would be super cool to send it to S3 and then use some kind of AWS event stream to see the new file and process it that way.

**Comment by drakkan** [comment]
Ok, thank you for your explaination.

For your info, and if this is appliable for your use case, SFTPGo can directly notify your server via HTTP POST. This way you save the resources required to start an external program.

If you need further assistance or simply you want to support the project please consider a [sponsorship](https://github.com/sponsors/drakkan), thank you
