### ISSUE TITLE
New folder can't be created with Rclone mount

### ISSUE THREAD

**Issue by HiFiPhile** [drakkan/sftpgo#169]
Hi,

I met a pretty strange issue using Rclone to mount SFTPGo share, sometimes new folder can't be created. 
At first I thought it's a Rclone issue, but using `rclone serve` as server I can't reproduce this issue.

You can find the [discussion here](https://forum.rclone.org/t/rclone-cant-create-new-folder-on-sftp-mount/19145).

I'm in version 3925c7ff95fc695bf82089d529714b398793ccdf

**Comment by drakkan** [comment]
Hi,

do you also run SFTPGo on Windows? Looking at the SFTPGo's code it should return `sftp.ErrSSHFxNoSuchFile`.

Do you use the local fs as SFTPGo backend or S3/GCS?

I just added a specific [test case](https://github.com/drakkan/sftpgo/commit/98a6d138d4d03737ce66bc64bf9d63fb407e5020) and CI is happy on Linux,Windows and MacOS.

Can you please try to replace the log [here](https://github.com/drakkan/sftpgo/blob/master/sftpd/handler.go#L214) with something like this?

```
c.Log(logger.LevelDebug, "error running stat on path %#v: %+v %+v %v", p, err, c.GetFsError(err), (c.GetFsError(err) == sftp.ErrSSHFxNoSuchFile))
```

This way we'll get more info.

I'll try to investigate myself later today. Thank you

**Comment by HiFiPhile** [comment]
> do you also run SFTPGo on Windows?

I'm running on Debian 10.

> Do you use the local fs as SFTPGo backend or S3/GCS?

it's zfs mounted by nfs4.

Do you want me to update to HEAD ?

**Comment by drakkan** [comment]
Hi,

I found the issue. Rclone open an SFTP session, then it send an ssh command (`df -k /`) and the connection protocol change from `SFTP` to `SSH` then using the same connection (with protocol now set to SSH) rclone create a directory over SFTP but since the protocol is now SSH SFTPGo returns an error appropriate for the SSH protocol and not for SFTP protocol. I'll push a fix later, thank you for reporting

**Comment by HiFiPhile** [comment]
You're welcome :)

**Comment by HiFiPhile** [comment]
PS : I was thinking about `df` support in SFTPGo, but with virtual folders and quotas it seems like too complicated.

**Comment by drakkan** [comment]
> PS : I was thinking about `df` support in SFTPGo, but with virtual folders and quotas it seems like too complicated.

Yes it is no so easy, however I would like to support `statvfs@openssh.com` in future and not the df system command. We'll see

**Comment by HiFiPhile** [comment]
Confirmed working.

**Comment by drakkan** [comment]
Thank you for confirming, there is another issue to fix now.

Before this change we were closing the whole SSH network connection if a client was idle on a single channel, disconnecting other, possibly active, channels too. Now we close the single channel. 

So now a malicious client could keep the SSH connection active with no open channel and so keeping the server file descriptor allocated. I'll add an additional check to disconnect idle ssh connections too.

**Comment by drakkan** [comment]
> PS : I was thinking about `df` support in SFTPGo, but with virtual folders and quotas it seems like too complicated.

statvfs@openssh.com is now [supported](https://github.com/drakkan/sftpgo/commit/51f110bc7b9610bb74c17ab97db11790e7d87b8e)

```
sftp -P 2022 bb@127.0.0.1
Connected to 127.0.0.1.
sftp> df -h
    Size     Used    Avail   (root)    %Capacity
   7.5GB    1.2GB    6.4GB    6.4GB          15%
sftp> df -i
     Inodes        Used       Avail      (root)    %Capacity
     409600       10022      399578      399578           2%
```

it should work for any supported backend, please let me know if you find this issue. Please note that this isn't the `df` system command.
