### ISSUE TITLE
[Bug]: JSch clients can't connect via publickey after upgrading from v2.5.6 to v2.6.2

### ISSUE THREAD

**Issue by coolbho3k** [drakkan/sftpgo#1694]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hello, after upgrading from v2.5.6 to v2.6.2, a client of ours using JSCh 1.54 has started failing with `no_auth_tried`, with not much else to go on. No other configuration on our SFTPGo server has changed since the upgrade. They're using ssh-rsa:
```
Jul 09 20:16:04 sftpgo sftpgo[2390467]: {"level":"debug","time":"2024-07-09T20:16:04.745","sender":"sftpd","message":"failed to accept an incoming connection from ip \"x.x.x.x\": ssh: disconnect, reason 3: com.jcraft.jsch.JSchException: Auth fail"}
Jul 09 20:16:04 sftpgo sftpgo[2390467]: {"level":"debug","time":"2024-07-09T20:16:04.745","sender":"connection_failed","client_ip":"x.x.x.x","username":"","login_type":"no_auth_tried","protocol":"SSH","error":"ssh: disconnect, reason 3: com.jcraft.jsch.JSchException: Auth fail"}
Jul 09 20:16:05 sftpgo sftpgo[2390467]: {"level":"debug","time":"2024-07-09T20:16:05.199","sender":"sftpd","message":"failed to accept an incoming connection from ip \"x.x.x.x\": ssh: disconnect, reason 3: com.jcraft.jsch.JSchException: Auth fail"}
Jul 09 20:16:05 sftpgo sftpgo[2390467]: {"level":"debug","time":"2024-07-09T20:16:05.199","sender":"connection_failed","client_ip":"x.x.x.x","username":"","login_type":"no_auth_tried","protocol":"SSH","error":"ssh: disconnect, reason 3: com.jcraft.jsch.JSchException: Auth fail"}
```

Username/password authentication with the same client still works fine:
```
Jul 09 21:08:03 sftpgo sftpgo[2390467]: {"level":"info","time":"2024-07-09T21:08:03.980","sender":"SSH","connection_id":"redacted","message":"User \"redacted\" logged in with \"password\", from ip \"x.x.x.x\", client version \"SSH-2.0-JSCH-0.1.54\", negotiated algorithms: {KeyExchange:ecdh-sha2-nistp256 HostKey:ssh-rsa Read:{Cipher:aes128-ctr MAC:hmac-sha2-256 compression:none} Write:{Cipher:aes128-ctr MAC:hmac-sha2-256 compression:none}}"}
Jul 09 21:08:04 sftpgo sftpgo[2390467]: {"level":"debug","time":"2024-07-09T21:08:04.177","sender":"SFTP","connection_id":"SFTP_redacted_1","message":"connection added, local address \"x.x.x.x:22\", remote address \"x.x.x.x:xxxxx\", num open connections: 2"}
```

### Steps to reproduce

It's hard to reproduce as it's difficult to replicate our client's setup, but JSCh 1.54 is the common denominator. All our other clients on publickey logins, including ssh-rsa, work.

### Expected behavior

JSCh 1.54 clients are able to log in.

### SFTPGo version

v2.6.2

### Data provider

SQLite

### Installation method

Community RPM package

### Configuration

Very close to default: https://gist.github.com/coolbho3k/929c8347bc210b723880806bafbe6d9b

### What are you using SFTPGo for?

Medium business

**Comment by coolbho3k** [comment]
@thielj Did you manage to track the issue down? We are still pretty confused about the root cause or even what is going on

**Comment by coolbho3k** [comment]
@thielj @drakkan I THINK we solved this by re-enabling ssh-rsa in the web console - WebAdmin -> Server Manager -> Configurations. I misunderstood this.

**Comment by coolbho3k** [comment]
@thielj Just PEM. To convert: https://stackoverflow.com/a/55740276

**Comment by drakkan** [comment]
> @thielj @drakkan I THINK we solved this by re-enabling ssh-rsa in the web console - WebAdmin -> Server Manager -> Configurations -> public key authentication algorithms. I misunderstood this menu option - I thought at first it was supposed to override/configure the available algorithms, not re-enable disabled ones. Anyway, it now works with my test Java app and JSCh.

jsch seems to be unmaintained, this is sadly what happens to Open Source projects. If they are not financially sustainable, the authors sooner or later lose interest because they have to pay the bills like everyone else and working for free doesn't help. 

In this case you are lucky and there is a maintained [fork](https://github.com/mwiede/jsch) you should consider using this fork instead of jsch, this way you do not need to enable insecure algorithms in SFTPGo.
