### ISSUE TITLE
[Bug]: error creating host key "id_rsa"

### ISSUE THREAD

**Issue by PeeBeerBeach** [drakkan/sftpgo#1709]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I have a running instance of SFTPGO in docker and it suddenly stopped working with a host key error after updating the container:

`2024-07-27T19:59:23.278 WRN error creating host key "id_rsa": open id_rsa: permission denied | sender=sftpd
2024-07-27T19:59:23.278 ERR could not start SFTP server: open id_rsa: permission denied | sender=service`

### Steps to reproduce

1.see above
2.
3.

### Expected behavior

Should just run as it did before

### SFTPGo version

v2.6.2-alpine

### Data provider

MariaDB

### Installation method

Community Docker image

### Configuration

version: "3"
services:
  sftpgo:
    image: "drakkan/sftpgo:alpine"
    user: '1006'
    restart: always
    ports:
      # HTTP
      - "8080:8080"
      # HTTPS
      - "456:443"
      # SFTP
      - "2044:2022"
    environment:
      #Web access
      SFTPGO_HTTPD__BINDINGS__0__PORT: 8080
      SFTPGO_HTTPD__BINDINGS__0__ADDRESS: 0.0.0.0
      SFTPGO_DATA_PROVIDER__DRIVER: "mysql"
      SFTPGO_DATA_PROVIDER__NAME: "sftpgo"
      SFTPGO_DATA_PROVIDER__HOST: "192.168.1.35"
      SFTPGO_DATA_PROVIDER__PORT: 3306
      SFTPGO_DATA_PROVIDER__USERNAME: "..."
      SFTPGO_DATA_PROVIDER__PASSWORD: "..."
      #Defender Protection
      SFTPGO_COMMON__DEFENDER__ENABLED: "true"
      SFTPGO_COMMON__DEFENDER__BAN_TIME: 10080
      SFTPGO_COMMON__DEFENDER__BAN_TIME_INCREMENT: 20
      SFTPGO_COMMON__DEFENDER__THRESHOLD: 5
      SFTPGO_COMMON__DEFENDER__OBSERVATION_TIME: 15
      SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__LOGO_PATH: "/img/login_image.png"
      SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__NAME: "BeerBeach HomeBase"
      SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__SHORT_NAME: "BeerBeach - identify"
      SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__LOGO_PATH: "/img/login_image.png"
      SFTPGO_HTTPD__BINDINGS__0__SECURITY__ENABLED: true
      SFTPGO_SFTPD__BINDINGS__0__MAX_AUTH_TRIES: 3
      SFTPGO_SFTPD__BINDINGS__0__BANNER: "\__W31c0m3 t0 B33rB34ch__/"
    volumes:
      - /srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/data:/srv/sftpgo
      - /srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/config/img:/usr/share/sftpgo/static/img
      - /ftp:/ftp # SKIP_BACKUP
networks:
    default:
        name: sftpgo

### Relevant log output

```shell
`2024-07-27T19:59:23.278 WRN error creating host key "id_rsa": open id_rsa: permission denied | sender=sftpd
2024-07-27T19:59:23.278 ERR could not start SFTP server: open id_rsa: permission denied | sender=service`
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by sdari-dvb** [comment]
This error looks to be related to permission or ownership settings of the dir where the host keys are generated or stored. You might have to chown or chmod for the user 1006 so that it has access to the host keys directory.

**Comment by PeeBeerBeach** [comment]
Strange thing is that it appeared after updating the docker container. Worked fine for a long time before.
I did not look into it yet because i was on vacation. Will check if it is a permission issue.

**Comment by PeeBeerBeach** [comment]
I don't get this. Still looks like a bug to me.

docker file:

`    environment:
      SFTPGO_CONFIG_DIR: '/srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/config'`

Log when starting docker:

`2024-08-19T17:53:18.698 WRN error creating host key "/srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/config/id_rsa": mkdir /srv/dev-disk-by-label-SSD_Data: permission denied | sender=sftpd
2024-08-19T17:53:18.698 ERR could not start SFTP server: mkdir /srv/dev-disk-by-label-SSD_Data: permission denied | sender=service`

CLI file permissions:

`root@debnas:/srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker# ls -l
drwxrwsrwx 3 dockeruser users 4096 19. Aug 18:59 config
`

So SFTPGO should be able to generate the host keys here, no?

**Comment by PeeBeerBeach** [comment]
Well my SFTPGO instance is not usable anymore for me as i cannot start it up anymore.
How can i get this working again and keep the settings including users? Any idea?

It's not a super big deal as this is just used by me privately. But I actually have no clue how to get it up and running again.

**Comment by PeeBeerBeach** [comment]
Thanks Drakkan. I would absolutely confirm what you are saying because it just looks like that.
But I did a `chmod 777 -R /srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker`
I think you can agree that this does the trick!

**Comment by PeeBeerBeach** [comment]
To reassure you:

```shell
root@debnas:/srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker# ls -Rl
.:
insgesamt 16
drwxrwsrwx 3 dockeruser users 4096 20. Aug 18:08 config
drwxrwsrwx 2 dockeruser users 4096 19. Aug 18:54 config2
drwxrwsrwx 2 dockeruser users 4096 19. Aug 18:54 data
drwxrwxrwx 5 dockeruser users 4096 19. Aug 18:51 sftpgoDocker.moved

./config:
insgesamt 4
drwxrwsrwx 2 dockeruser users 4096 19. Aug 18:59 img

./config/img:
insgesamt 0

./config2:
insgesamt 0

./data:
insgesamt 0

./sftpgoDocker.moved:
insgesamt 12
drwxrwxrwx 5 dockeruser users 4096  7. Dez 2023  config
drwxrwxrwx 2 dockeruser users 4096 19. Aug 18:51 config2
drwxrwxrwx 3 dockeruser users 4096 25. Nov 2023  data

./sftpgoDocker.moved/config:
insgesamt 12
drwxrwxrwx 2 dockeruser users 4096  6. Dez 2023  img
drwxrwxrwx 6 dockeruser users 4096 18. Nov 2023  static.ld
drwxrwxrwx 2 dockeruser users 4096  7. Dez 2023  templates

./sftpgoDocker.moved/config/img:
insgesamt 1320
-rwxrwxrwx 1 dockeruser users 1293448  6. Dez 2023  login_image.png
-rwxrwxrwx 1 dockeruser users   54014  6. Dez 2023  login_image.png.old

./sftpgoDocker.moved/config/static.ld:
insgesamt 36
drwxrwxrwx  2 dockeruser users  4096 18. Nov 2023  css
-rwxrwxrwx  1 dockeruser users 16958 18. Nov 2023  favicon.ico
drwxrwxrwx  2 dockeruser users  4096  6. Dez 2023  img
drwxrwxrwx  2 dockeruser users  4096 18. Nov 2023  js
drwxrwxrwx 17 dockeruser users  4096 18. Nov 2023  vendor

./sftpgoDocker.moved/config/static.ld/css:
insgesamt 168
-rwxrwxrwx 1 dockeruser users 170743 18. Nov 2023  sb-admin-2.min.css

./sftpgoDocker.moved/config/static.ld/img:
insgesamt 1404
-rwxrwxrwx 1 dockeruser users 1293448  6. Dez 2023  login_image.png
-rwxrwxrwx 1 dockeruser users   54014  6. Dez 2023  login_image.png.old
-rwxrwxrwx 1 dockeruser users   66679 18. Nov 2023  login_image.png.original
-rwxrwxrwx 1 dockeruser users   14091 18. Nov 2023  logo.png

./sftpgoDocker.moved/config/static.ld/js:
insgesamt 4
-rwxrwxrwx 1 dockeruser users 1265 18. Nov 2023  sb-admin-2.min.js

./sftpgoDocker.moved/config/static.ld/vendor:
insgesamt 60
drwxrwxrwx 3 dockeruser users 4096 18. Nov 2023  bootstrap
drwxrwxrwx 4 dockeruser users 4096 18. Nov 2023  bootstrap-select
drwxrwxrwx 3 dockeruser users 4096 18. Nov 2023  codemirror
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  datatables
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  daterangepicker
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  filepond
drwxrwxrwx 4 dockeruser users 4096 18. Nov 2023  fontawesome-free
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  fonts
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  jquery
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  jquery-easing
drwxrwxrwx 5 dockeruser users 4096 18. Nov 2023  lightbox2
drwxrwxrwx 3 dockeruser users 4096 18. Nov 2023  moment
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  pdfobject
drwxrwxrwx 4 dockeruser users 4096 18. Nov 2023  tempusdominus
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  video-js

./sftpgoDocker.moved/config/static.ld/vendor/bootstrap:
insgesamt 4
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  js

./sftpgoDocker.moved/config/static.ld/vendor/bootstrap/js:
insgesamt 148
-rwxrwxrwx 1 dockeruser users 83253 18. Nov 2023  bootstrap.bundle.min.js
-rwxrwxrwx 1 dockeruser users 62440 18. Nov 2023  bootstrap.min.js

./sftpgoDocker.moved/config/static.ld/vendor/bootstrap-select:
insgesamt 8
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  css
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  js

./sftpgoDocker.moved/config/static.ld/vendor/bootstrap-select/css:
insgesamt 12
-rwxrwxrwx 1 dockeruser users 11120 18. Nov 2023  bootstrap-select.min.css

./sftpgoDocker.moved/config/static.ld/vendor/bootstrap-select/js:
insgesamt 52
-rwxrwxrwx 1 dockeruser users 52249 18. Nov 2023  bootstrap-select.min.js

./sftpgoDocker.moved/config/static.ld/vendor/codemirror:
insgesamt 428
drwxrwxrwx 6 dockeruser users   4096 18. Nov 2023  addon
-rwxrwxrwx 1 dockeruser users   8720 18. Nov 2023  codemirror.css
-rwxrwxrwx 1 dockeruser users 401787 18. Nov 2023  codemirror.js
-rwxrwxrwx 1 dockeruser users  15926 18. Nov 2023  meta.js

./sftpgoDocker.moved/config/static.ld/vendor/codemirror/addon:
insgesamt 16
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  dialog
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  scroll
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  search
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  selection

./sftpgoDocker.moved/config/static.ld/vendor/codemirror/addon/dialog:
insgesamt 12
-rwxrwxrwx 1 dockeruser users  507 18. Nov 2023  dialog.css
-rwxrwxrwx 1 dockeruser users 5252 18. Nov 2023  dialog.js

./sftpgoDocker.moved/config/static.ld/vendor/codemirror/addon/scroll:
insgesamt 8
-rwxrwxrwx 1 dockeruser users 4630 18. Nov 2023  annotatescrollbar.js

./sftpgoDocker.moved/config/static.ld/vendor/codemirror/addon/search:
insgesamt 44
-rwxrwxrwx 1 dockeruser users  2143 18. Nov 2023  jump-to-line.js
-rwxrwxrwx 1 dockeruser users   188 18. Nov 2023  matchesonscrollbar.css
-rwxrwxrwx 1 dockeruser users  3858 18. Nov 2023  matchesonscrollbar.js
-rwxrwxrwx 1 dockeruser users  6216 18. Nov 2023  match-highlighter.js
-rwxrwxrwx 1 dockeruser users 12234 18. Nov 2023  searchcursor.js
-rwxrwxrwx 1 dockeruser users 11863 18. Nov 2023  search.js

./sftpgoDocker.moved/config/static.ld/vendor/codemirror/addon/selection:
insgesamt 4
-rwxrwxrwx 1 dockeruser users 2509 18. Nov 2023  active-line.js

./sftpgoDocker.moved/config/static.ld/vendor/datatables:
insgesamt 264
-rwxrwxrwx 1 dockeruser users  9095 18. Nov 2023  buttons.bootstrap4.min.css
-rwxrwxrwx 1 dockeruser users  1585 18. Nov 2023  buttons.bootstrap4.min.js
-rwxrwxrwx 1 dockeruser users  3342 18. Nov 2023  buttons.colVis.min.js
-rwxrwxrwx 1 dockeruser users   181 18. Nov 2023  colReorder.bootstrap4.min.css
-rwxrwxrwx 1 dockeruser users 11423 18. Nov 2023  dataTables.bootstrap4.min.css
-rwxrwxrwx 1 dockeruser users  2342 18. Nov 2023  dataTables.bootstrap4.min.js
-rwxrwxrwx 1 dockeruser users 25559 18. Nov 2023  dataTables.buttons.min.js
-rwxrwxrwx 1 dockeruser users   568 18. Nov 2023  dataTables.checkboxes.css
-rwxrwxrwx 1 dockeruser users 14079 18. Nov 2023  dataTables.checkboxes.min.js
-rwxrwxrwx 1 dockeruser users 13332 18. Nov 2023  dataTables.colReorder.min.js
-rwxrwxrwx 1 dockeruser users 11944 18. Nov 2023  dataTables.fixedHeader.min.js
-rwxrwxrwx 1 dockeruser users 14657 18. Nov 2023  dataTables.responsive.min.js
-rwxrwxrwx 1 dockeruser users 14174 18. Nov 2023  dataTables.select.min.js
-rwxrwxrwx 1 dockeruser users  4222 18. Nov 2023  ellipsis.js
-rwxrwxrwx 1 dockeruser users   265 18. Nov 2023  fixedHeader.bootstrap4.min.css
-rwxrwxrwx 1 dockeruser users 86839 18. Nov 2023  jquery.dataTables.min.js
-rwxrwxrwx 1 dockeruser users  4301 18. Nov 2023  responsive.bootstrap4.min.css
-rwxrwxrwx 1 dockeruser users  1371 18. Nov 2023  responsive.bootstrap4.min.js
-rwxrwxrwx 1 dockeruser users  1631 18. Nov 2023  select.bootstrap4.min.css

./sftpgoDocker.moved/config/static.ld/vendor/daterangepicker:
insgesamt 40
-rwxrwxrwx 1 dockeruser users  8069 18. Nov 2023  daterangepicker.css
-rwxrwxrwx 1 dockeruser users 32608 18. Nov 2023  daterangepicker.min.js

./sftpgoDocker.moved/config/static.ld/vendor/filepond:
insgesamt 136
-rwxrwxrwx 1 dockeruser users  17447 18. Nov 2023  filepond.min.css
-rwxrwxrwx 1 dockeruser users 117648 18. Nov 2023  filepond.min.js

./sftpgoDocker.moved/config/static.ld/vendor/fontawesome-free:
insgesamt 8
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  css
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  webfonts

./sftpgoDocker.moved/config/static.ld/vendor/fontawesome-free/css:
insgesamt 68
-rwxrwxrwx 1 dockeruser users 57873 18. Nov 2023  fontawesome.min.css
-rwxrwxrwx 1 dockeruser users   677 18. Nov 2023  regular.min.css
-rwxrwxrwx 1 dockeruser users   669 18. Nov 2023  solid.min.css

./sftpgoDocker.moved/config/static.ld/vendor/fontawesome-free/webfonts:
insgesamt 1728
-rwxrwxrwx 1 dockeruser users  34034 18. Nov 2023  fa-regular-400.eot
-rwxrwxrwx 1 dockeruser users 144714 18. Nov 2023  fa-regular-400.svg
-rwxrwxrwx 1 dockeruser users  33736 18. Nov 2023  fa-regular-400.ttf
-rwxrwxrwx 1 dockeruser users  16276 18. Nov 2023  fa-regular-400.woff
-rwxrwxrwx 1 dockeruser users  13224 18. Nov 2023  fa-regular-400.woff2
-rwxrwxrwx 1 dockeruser users 203030 18. Nov 2023  fa-solid-900.eot
-rwxrwxrwx 1 dockeruser users 918991 18. Nov 2023  fa-solid-900.svg
-rwxrwxrwx 1 dockeruser users 202744 18. Nov 2023  fa-solid-900.ttf
-rwxrwxrwx 1 dockeruser users 101648 18. Nov 2023  fa-solid-900.woff
-rwxrwxrwx 1 dockeruser users  78268 18. Nov 2023  fa-solid-900.woff2

./sftpgoDocker.moved/config/static.ld/vendor/fonts:
insgesamt 260
-rwxrwxrwx 1 dockeruser users 11560 18. Nov 2023  LICENSE.txt
-rwxrwxrwx 1 dockeruser users   134 18. Nov 2023  README.txt
-rwxrwxrwx 1 dockeruser users 82564 18. Nov 2023  Roboto-Bold-webfont.woff
-rwxrwxrwx 1 dockeruser users 81348 18. Nov 2023  Roboto-Light-webfont.woff
-rwxrwxrwx 1 dockeruser users 80304 18. Nov 2023  Roboto-Regular-webfont.woff

./sftpgoDocker.moved/config/static.ld/vendor/jquery:
insgesamt 88
-rwxrwxrwx 1 dockeruser users 89795 18. Nov 2023  jquery.min.js

./sftpgoDocker.moved/config/static.ld/vendor/jquery-easing:
insgesamt 8
-rwxrwxrwx 1 dockeruser users 1656 18. Nov 2023  jquery.easing.compatibility.js
-rwxrwxrwx 1 dockeruser users 2302 18. Nov 2023  jquery.easing.min.js

./sftpgoDocker.moved/config/static.ld/vendor/lightbox2:
insgesamt 12
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  css
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  images
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  js

./sftpgoDocker.moved/config/static.ld/vendor/lightbox2/css:
insgesamt 4
-rwxrwxrwx 1 dockeruser users 2532 18. Nov 2023  lightbox.min.css

./sftpgoDocker.moved/config/static.ld/vendor/lightbox2/images:
insgesamt 24
-rwxrwxrwx 1 dockeruser users  280 18. Nov 2023  close.png
-rwxrwxrwx 1 dockeruser users 8476 18. Nov 2023  loading.gif
-rwxrwxrwx 1 dockeruser users 1350 18. Nov 2023  next.png
-rwxrwxrwx 1 dockeruser users 1360 18. Nov 2023  prev.png

./sftpgoDocker.moved/config/static.ld/vendor/lightbox2/js:
insgesamt 12
-rwxrwxrwx 1 dockeruser users 9483 18. Nov 2023  lightbox.min.js

./sftpgoDocker.moved/config/static.ld/vendor/moment:
insgesamt 4
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  js

./sftpgoDocker.moved/config/static.ld/vendor/moment/js:
insgesamt 60
-rwxrwxrwx 1 dockeruser users 58103 18. Nov 2023  moment.min.js

./sftpgoDocker.moved/config/static.ld/vendor/pdfobject:
insgesamt 8
-rwxrwxrwx 1 dockeruser users 5205 18. Nov 2023  pdfobject.min.js

./sftpgoDocker.moved/config/static.ld/vendor/tempusdominus:
insgesamt 8
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  css
drwxrwxrwx 2 dockeruser users 4096 18. Nov 2023  js

./sftpgoDocker.moved/config/static.ld/vendor/tempusdominus/css:
insgesamt 12
-rwxrwxrwx 1 dockeruser users 11963 18. Nov 2023  tempusdominus-bootstrap-4.min.css

./sftpgoDocker.moved/config/static.ld/vendor/tempusdominus/js:
insgesamt 64
-rwxrwxrwx 1 dockeruser users 61588 18. Nov 2023  tempusdominus-bootstrap-4.min.js

./sftpgoDocker.moved/config/static.ld/vendor/video-js:
insgesamt 592
-rwxrwxrwx 1 dockeruser users  43856 18. Nov 2023  video-js.min.css
-rwxrwxrwx 1 dockeruser users 558087 18. Nov 2023  video.min.js

./sftpgoDocker.moved/config/templates:
insgesamt 0

./sftpgoDocker.moved/config2:
insgesamt 0

./sftpgoDocker.moved/data:
insgesamt 4
drwxrwxrwx 3 dockeruser users 4096 25. Nov 2023  data

./sftpgoDocker.moved/data/data:
insgesamt 4
drwxrwxrwx 2 dockeruser users 4096 25. Nov 2023  123


```

**Comment by drakkan** [comment]
> Thanks Drakkan. I would absolutely confirm what you are saying because it just looks like that. But I did a `chmod 777 -R /srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker` I think you can agree that this does the trick!

I generally don't suggest `chmod 777`, anyway what about the following folders?

- `/srv`
- `/srv/dev-disk-by-label-SSD_Data`
- `/srv/dev-disk-by-label-SSD_Data/appdata`

are you sure the user running SFTPGo can write there?

**Comment by PeeBeerBeach** [comment]
No, SFTPGO cannot write in there. SFTPGO is only using folders below the appdata/sftpgoDocker folder after what i understand

**Comment by drakkan** [comment]
> No, SFTPGO cannot write in there. SFTPGO is only using folders below the appdata/sftpgoDocker folder after what i understand

sftpgo user should at least be able to read parent directories. If a parent directory has permissions 700 or 750, sftpgo cannot write to any child directory even if the child directory has permissions 777

**Comment by PeeBeerBeach** [comment]
Parent directory of what? 

Remember:

```dockerfile
environment:
       SFTPGO_CONFIG_DIR: '/srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/config
```

**Comment by drakkan** [comment]
> Parent directory of what?
> 
> Remember:
> 
> ```dockerfile
> environment:
>        SFTPGO_CONFIG_DIR: '/srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/config
> ```
> 
> SFTPGO has all rights on parent folder of config dir.

https://github.com/drakkan/sftpgo/issues/1709#issuecomment-2299421991

**Comment by PeeBeerBeach** [comment]
Well i just gave SFTPGO permission to write to the parent `/srv/dev-disk-by-label-SSD_Data/appdata`
That did not help.

I don't see that i will give it permission to write to my `/srv` folder which is the folder for all the drive mounts on my OS.
I really don't get why that is required. There is nothing configured outside of the `/srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/` folder so why would it need filerights to a wide area of my filesystem?

I have about 20 dockers running. None of them needs filerights outside of any configured directories. It just doesn't make sense, or i am just not getting it.

**Comment by drakkan** [comment]
> Well i just gave SFTPGO permission to write to the parent `/srv/dev-disk-by-label-SSD_Data/appdata` That did not help.
> 
> I don't see that i will give it permission to write to my `/srv` folder which is the folder for all the drive mounts on my OS. I really don't get why that is required. There is nothing configured outside of the `/srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/` folder so why would it need filerights to a wide area of my filesystem?
> 
> I have about 20 dockers running. None of them needs filerights outside of any configured directories. It just doesn't make sense, or i am just not getting it.

you need at least to give read permission to the parent directories (e.g. 755 or 750 and sftpgo group as owner), this is how posix permissions work

**Comment by PeeBeerBeach** [comment]
It has read permissions:

`drwxr-xr-x  11 root root   4096  4. Mär 14:21 srv
`

`drwxr-sr-x 5 root users        4096  9. Apr 17:11 dev-disk-by-label-SSD_Data
`

`drwxrwsr-x+ 27 root users  4096 20. Aug 13:47 appdata
`

**Comment by PeeBeerBeach** [comment]
Maybe we have a misunderstanding here. `srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/` is a folder outside the docker jailed filesystem but a folder on the host system.

I cannot make the sftpgo user own my `/srv` folder which is the root folder for all shared drives OS wide.

**Comment by drakkan** [comment]
> Maybe we have a misunderstanding here. `srv/dev-disk-by-label-SSD_Data/appdata/sftpgoDocker/` is a folder outside the docker jailed filesystem but a folder on the host system.
> 
> I cannot make the sftpgo user own my `/srv` folder which is the root folder for all shared drives OS wide.

you should make sure that sftpgo user can at least access this directory, otherwise is normal that cannot write to folders inside

**Comment by PeeBeerBeach** [comment]
Yes i understand and it can:

```shell
root@debnas:/# su dockeruser
cd /srv/dev-disk-by-label-SSD_Data
ls -l
insgesamt 40
drwxrwsr-x+ 27 root users  4096 20. Aug 13:47 appdata
-rw-------   1 root users  8192 20. Aug 00:25 aquota.group
-rw-------   1 root users  8192 20. Aug 00:25 aquota.user
drwx------   2 root root  16384 22. Okt 2017  lost+found
drwxrwsr-x   6 root users  4096 11. Jul 2018  www

```

**Comment by drakkan** [comment]
ok, just mount the volume to a different path, so the container starts, open a shell inside the container and debug the permission issue with os tools

**Comment by PeeBeerBeach** [comment]
Well i don't get it. The docker should have read permission, so i dont know how to solve it.

Funny thing is that I do not even need the host keys and i do not need SFTP service. I just use the HTML part.

But i commented everything out regarding SFTP but still is trying to start it and fails at the id_rsa file.
What i also do not understand that it worked fine and suddenly with an update it does not anymore.

Is there any way to switch off SFTP and this check for the host keys? I dont need it.

**Comment by drakkan** [comment]
to disable sftp set `SFTPGO_SFTPD__BINDINGS__0__PORT` to `0`
