### ISSUE TITLE
Better permission denied messages

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#171]
When I create a user with upload only permission and the I try to upload a file twice, I receive the following message:

> failure, this command cannot be executed

I think it would be nice to have a better error message, like "Permission denied" maybe adding the fact that it was an overwrite.

WDYT?

**Comment by drakkan** [comment]
Hi,

thank you for your suggestions. It seems to work for me, please take a look here

```
sftp -P 2022 b@127.0.0.1
b@127.0.0.1's password: 
Connected to 127.0.0.1.
sftp> cd bbb/
sftp> put file.txt 
Uploading file.txt to /bbb/file.txt
file.txt                                                                                                                           100% 4034     3.5MB/s   00:00    
sftp> put file.txt
Uploading file.txt to /bbb/file.txt
remote open("/bbb/file.txt"): Permission denied
sftp> quit
```

for the folder `bbb` the logged in user has no `overwrite` permission.

Can you please provide more info? Thank you

**Comment by sagikazarmark** [comment]
Oh yeah, I probably should have mentioned: I used `scp`.

```
❯ scp -P 2022 test  mark@127.0.0.1:
failure, this command cannot be executed
```

**Comment by sagikazarmark** [comment]
Cool, thanks a lot for the quick fix! 🎉
