### ISSUE TITLE
[Bug]: Unable to use persistence.existingClaim

### ISSUE THREAD

**Issue by PradeepSinghChauhan** [drakkan/sftpgo#1737]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

we are already configured with persistence  volume . in v0.20.0 its not working up with a custom name PVC

### Steps to reproduce

update from v0.19 to v0.20  with existing 

### Expected behavior

should use existing one if  persistence.existingClaim is there !

### SFTPGo version

0.20.0

### Data provider

0.20.0

### Installation method

Community Docker image

### Configuration

volumeMounts:
    - name: sftp-storage
      mountPath: /data/sftp
    - name: sftp-storage
      mountPath: /var/lib/sftpgo
volumes:
  - name: sftp-storage
    persistentVolumeClaim:
      claimName: ${volume_claim}
persistence:
  enabled: true
  existingClaim: ${volume_claim}

### Relevant log output

```shell
volumeMounts:
    - name: sftp-storage
      mountPath: /data/sftp
    - name: sftp-storage
      mountPath: /var/lib/sftpgo
volumes:
  - name: sftp-storage
    persistentVolumeClaim:
      claimName: ${volume_claim}
persistence:
  enabled: true
  existingClaim: ${volume_claim}
```

### What are you using SFTPGo for?

Small business (3-person firm with file exchange?)

### Additional info

NA

**Comment by drakkan** [comment]
0.20.0 is not an SFTPGo version, you are reporting here a possible bug for something we don't maintain

> should use existing one if persistence.existingClaim is there !

Please avoid exclamation marks, you are using an open source software for free, we have no obligation
