### ISSUE TITLE
how to use the /folder get endpoint to get subfolders for the root

### ISSUE THREAD

**Issue by musa-raza** [drakkan/sftpgo#175]
Hey, I'm having a little bit of trouble getting the API to function. I can create a folder just fine, lets say the path for that folder is `/dev/test-123`. I also created two sub folders under that folder, with absolute paths of `/dev/test-123/template_one` and `/dev/test-123/template_two`. Let's say I want to get a list of folders under `/dev/test-123`. When I hit the end point with the query `?folder_path=/dev/test-123`, it just returns that folder (`/dev/test-123`) (I think because of the exact match). What am I missing here?

**Comment by drakkan** [comment]
Hi, there is no such API, please take a look at the schema [definition](https://github.com/drakkan/sftpgo/blob/master/httpd/schema/openapi.yaml#L363)

You don't have to recreate a filesystem like structure, just create a virtual folder and assign it to a user, all its contents will be accessibile. 

Please provide more information on what you are trying to achieve, thank you

**Comment by drakkan** [comment]
Please reopen providing more info, thank you
