### ISSUE TITLE
Make Ubuntu package for each release

### ISSUE THREAD

**Issue by wkoszek** [drakkan/sftpgo#176]
Using `goreleaser` would enable us to simplify provisioning. Looking at:

https://github.com/drakkan/sftpgo/blob/master/docs/howto/postgresql-s3.md

Right now it's a bunch of steps. There are several steps that I believe a normal .deb package would solve:

- adding a user
- copying files to the right places
- adding sftpgo to systemd

https://github.com/goreleaser/goreleaser

And if using Goreleaser is too much, it comes with easy .deb builder:

https://nfpm.goreleaser.com/configuration/

I think this would make Dockerfiles much easier too.

**Comment by drakkan** [comment]
Goreleaser does not work well for SFTPGo see #1 for details. I'll try to automate the deb creation using a Github action

**Comment by wkoszek** [comment]
@drakkan Interesting. https://gitlab.com/cznic/sqlite <- this is a SQLite driver which should be 100% CGO free. I wonder if that would be a viable replacement.

**Comment by drakkan** [comment]
> @drakkan Interesting. https://gitlab.com/cznic/sqlite <- this is a SQLite driver which should be 100% CGO free. I wonder if that would be a viable replacement.

Hi, I'm following this project, it's interesting but not ready yet

https://gitlab.com/cznic/sqlite/-/issues/23
https://gitlab.com/cznic/sqlite/-/issues/24

however I'll add a GitHub action to build deb/rpm soon
