### ISSUE TITLE
Add sftpgo.service to the repo

### ISSUE THREAD

**Issue by wkoszek** [drakkan/sftpgo#177]
This doc:

https://github.com/drakkan/sftpgo/blob/master/docs/howto/postgresql-s3.md

Mentions `sftpgo.service`

Can we just add this to the repo?

**Comment by wkoszek** [comment]
Looks like it's the same file as init/sftpgo.service ? Is there a reason why can one just copy it in place?

**Comment by drakkan** [comment]
> Looks like it's the same file as init/sftpgo.service ? Is there a reason why can one just copy it in place?

The only difference is this one

```
User=root
Group=root
```

in the tutorial SFTPGo runs as the `sftpgo` user. 

I plan update [this doc](https://github.com/drakkan/sftpgo/blob/master/docs/service.md) and to change the user to `sftpgo` in the service.

**Comment by wkoszek** [comment]
@drakkan thanks!
