### ISSUE TITLE
[Bug]: Web Client - Problem with displaying file uploading progress

### ISSUE THREAD

**Issue by sigmallc** [drakkan/sftpgo#1773]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

When uploading files to the server, it is difficult to read the information about how many files have been uploaded because the center alignment and length of the file names differ significantly.
![Снимок экрана 2024-09-30 171412](https://github.com/user-attachments/assets/3697017d-4c94-4b3a-8989-24a6ab59c093)

### Steps to reproduce

1. /web/client/files
2. Select an empty folder or click upload files
3. Drag a folder with a large number of files into the drag and drop zone.
4. Save

### Expected behavior

The text alignment of the upload information should be on the right. Then the number of uploaded files will be readable.

### SFTPGo version

2.6.2

### Data provider

*

### Installation method

Community Deb package

### Configuration

config

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
I agree, if you are familiar with HTML please provide a patch. Thank you
