### ISSUE TITLE
GCS Wrong Content-Type

### ISSUE THREAD

**Issue by thomas-advantitge** [drakkan/sftpgo#178]
Some file types have a non-standard Content-Type after upload through the SFTP server:
![image](https://user-images.githubusercontent.com/66438062/94419469-1afc0680-0183-11eb-9299-b7367538c219.png)
It also seems to differ for the same file type:
![image](https://user-images.githubusercontent.com/66438062/94419727-762df900-0183-11eb-8d4d-2283369c4f4d.png)

Wrong content-type values causes browsers like Chrome to download the file with the extension related to the Content-Type (e.g. the application/zip content-type file translates to a file with extension ".zip", causing troubles opening the file).

I took a look in gcsfs.go but didn't see any content-type related setters for the Create method, so not sure the content-type "guessing" is related to sftpgo or the golang client library for Google Cloud Storage.

**Comment by drakkan** [comment]
Hi, 

SFTPGo does not set a content type after creating an [object writer](https://github.com/drakkan/sftpgo/blob/master/vfs/gcsfs.go#L183). It only set `StorageClass` if appropriate.

Based on the doc [here](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L1004)

```
If no ContentType attribute is specified, the content type will be automatically sniffed using net/http.DetectContentType.
```

`DetectContentType` documentation is [here](https://golang.org/pkg/net/http/#DetectContentType). I don't know if I can fix this on the SFTPGo side: I can explicitly set a content type but how can I detect it? If I use `net/http.DetectContentType` we'll get the same behaviour.

I'll try to better investigate better later, maybe I can try to guess the mime type by [extension](https://github.com/drakkan/sftpgo/blob/master/webdavd/file.go#L67), are you able to do some tests using this method? 

Here is an untested patch

```
diff --git a/vfs/gcsfs.go b/vfs/gcsfs.go
index 7ac29e8..dc43799 100644
--- a/vfs/gcsfs.go
+++ b/vfs/gcsfs.go
@@ -7,6 +7,7 @@ import (
        "errors"
        "fmt"
        "io"
+       "mime"
        "net/http"
        "os"
        "path"
@@ -181,6 +182,10 @@ func (fs GCSFs) Create(name string, flag int) (*os.File, *PipeWriter, func(), er
        obj := bkt.Object(name)
        ctx, cancelFn := context.WithCancel(context.Background())
        objectWriter := obj.NewWriter(ctx)
+       contentType := mime.TypeByExtension(path.Ext(name))
+       if contentType != "" {
+               objectWriter.ObjectAttrs.ContentType = contentType
+       }
        if len(fs.config.StorageClass) > 0 {
                objectWriter.ObjectAttrs.StorageClass = fs.config.StorageClass
        }
```

thank you

**Comment by thomas-advantitge** [comment]
Hi @drakkan, thanks for the quick feedback.
I've built from source using your patch and connecting to our GCS bucket, which resulted in a correct mime type!

Created a PR with your changes if you would decide if this is a robust improvement: https://github.com/drakkan/sftpgo/pull/179. I think this should be tackled in the underlying google-cloud-go package, but given the shortness of the fix, it's probably a good improvement!
