### ISSUE TITLE
Port 22 already in use

### ISSUE THREAD

**Issue by mcdappdev** [drakkan/sftpgo#18]
When attempting to start the server I get this error: 

```
2019-07-31T15:34.16.762 ERR could not start SFTP server: listen tcp 0.0.0.0:22: bind: address already in use
```

How can I expose the SFTP server on port 22 when ssh is already running on that port?

**Comment by drakkan** [comment]
Can you use a different network interface/ip address?

For example if your server has ip 192.168.1.2 and 192.168.1.3 you can bind openssh on 192.168.1.2 and sftpgo on 192.168.1.3 (sftpd -> bind_address in sftpgo.conf)

**Comment by mcdappdev** [comment]
That's a good idea. Where can I find those addresses? I am using AWS EC2

**Comment by drakkan** [comment]
Try to read this

https://aws.amazon.com/it/blogs/aws/multiple-ip-addresses-for-ec2-instances-in-a-virtual-private-cloud/

**Comment by mcdappdev** [comment]
Do I update `ListenAddress` in `/etc/ssh/sshd_config`? This is what I added in AWS:

![Screen Shot 2019-07-31 at 11 04 42 AM](https://user-images.githubusercontent.com/11842593/62228334-15d6d800-b383-11e9-9a42-6b4bc8f831de.png)

**Comment by drakkan** [comment]
These seems network addresses and not ip addresses,

I don't know very well ec2, before any change please verify that the address you configure is really available using for example `ip a` otherwise the sevice will not start.

Out of curiosity why you cannot use a different port?

**Comment by mcdappdev** [comment]
This is what I see from `ip a`:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 06:8f:7c:02:11:ac brd ff:ff:ff:ff:ff:ff
    inet 172.31.18.230/20 brd 172.31.31.255 scope global dynamic eth0
       valid_lft 2416sec preferred_lft 2416sec
    inet6 fe80::48f:7cff:fe02:11ac/64 scope link
       valid_lft forever preferred_lft forever
```

I can't use anything other than port 22 because that is what our clients are expecting :( We provide technology services in a very stagnant and slow-moving industry and so asking clients to update a port from 22 to something else is very difficult :(

**Comment by drakkan** [comment]
You have a single ip address here: `172.31.18.230`

You could configure ssh on port 2222 for example if you use openssh only for remote management and not to offer services to you customers, but first check that this port is open and reachable or you will be unable to login on your server :)

**Comment by mcdappdev** [comment]
That worked!! Thank you :)
