### ISSUE TITLE
Information about support? 

### ISSUE THREAD

**Issue by QAnders** [drakkan/sftpgo#1817]
### Is your feature request related to a problem? Please describe.

No information about purchased support 

### Describe the solution you'd like

Some better/clearer information about purchased support would be nice.

We've been using CrushFTP for ages but had some issues and it was a little too complex/big for what we need and I found and installed sftpgo.
Seems like an awesome solution and remarkable that you've managed to keep it open-source. Kudos! And a massive thank you!

However, using it commercially we want some support option so I added a monthly subscription through PayPal. The PayPal payment went through and I can see the charge on the card but I have not gotten any emails about support or any receipt from you.

Company name is Qvalia...

Keep up the good work! The product seems great! 

### What are you using SFTPGo for?

Small business (3-person firm with file exchange?)

**Comment by drakkan** [comment]
Thank you for signing up for one of our support plans. My colleague Marzia has sent an email with information on how to get support to the email address you used to sign up. Please check you inbox or send your support requests directly to support at sftpgo dot com. Thank you!
