### ISSUE TITLE
[Bug]: sftpgo take the wrong ip address if x-forwarded-for header contains multiple ip addresses

### ISSUE THREAD

**Issue by helmut72** [drakkan/sftpgo#1821]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

sftpgo take the wrong ip address if x-forwarded-for header contains multiple ip addresses

It doesn't use the first one (the cllient ip) but the last one.

Please see this:
https://serverfault.com/a/997805

I guess this also makes any "fail2ban" useless.

### Steps to reproduce

1. please two reverse proxy in front of sftpgo
2. take care that trustedIPs is set to avoid deleting x-forwarded-for header
3. look into the logs

### Expected behavior

sftpgo should use the first ip address in this chain.

Please see this:
https://serverfault.com/a/997805

### SFTPGo version

2.6.4

### Data provider

file

### Installation method

Community Docker image

### Configuration

```
SFTPGO_WEBDAVD__BINDINGS__0__PROXY_ALLOWED=127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
SFTPGO_WEBDAVD__BINDINGS__0__CLIENT_IP_PROXY_HEADER="X-Forwarded-For"
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional info

Workaround is using x-real-ip header. This header only contains one ip address, the ip from the client.

```
SFTPGO_WEBDAVD__BINDINGS__0__CLIENT_IP_PROXY_HEADER="X-Real-IP"
```

Thank you.

**Comment by jrTraceParts** [comment]
I may be wrong but it looks like this is the default behavior.

> client_ip_header_depth, integer. Some client IP headers such as X-Forwarded-For can contain multiple IP address, this setting define the position to trust starting from the right. For example if we have: 10.0.0.1,11.0.0.1,12.0.0.1,13.0.0.1 and the depth is 0, SFTPGo will use 13.0.0.1 as client IP, if depth is 1, 12.0.0.1 will be used and so on. Default: 0.

https://docs.sftpgo.com/2.6/config-file/#http-server

I think you should set this parameter to the number of proxies in front of you server minus one.

**Comment by helmut72** [comment]
You are not wrong. Thank you 👍 and sorry for the noise.
