### ISSUE TITLE
Add a way to provide CA certs to be embedded in the docker image

### ISSUE THREAD

**Issue by nodje** [drakkan/sftpgo#1840]
### Is your feature request related to a problem? Please describe.

Configuring an OIDC IDP, SFTPgo container validates the OIDC IDP SSL certificates at startup and fails to start with 
```
sftpgo  | {"level":"error","time":"2024-12-10T08:40:22.131","sender":"service","message":"could not start HTTP server: oidc: unable to initialize provider for URL \"https://keycloak.local.com/realms/ligoj\": Get \"https://keycloak.local.com/realms/ligoj/.well-known/openid-configuration\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
```
if the IDP SSL certificates is not provided by a known CA.
This is typically the case in an enterprise environment which provides it's own PKI.

### Describe the solution you'd like

Be able to provide CA certs in a specific directory mounted in the SFTPgo container, like GitLab container's deployment does (in `data/trusted-certs`), and have SFTPgo process and install them at runtime.

That would be the most convenient

### Describe alternatives you've considered

I had to build the SFTPGo container image by adding a line to copy a CA cert and run the cmd to process it in the Dockefile

### What are you using SFTPGo for?

Enterprise

**Comment by drakkan** [comment]
Thanks for being honest about your SFTPGo usage, appreciated. Most SFTPGo users here are private users and run SFTPGo on large Kubernetes clusters at home.

We can provide commercial support: in addition to adding this little feature that you can probably add also yourself, supporting the project will also ensure that it is maintained and evolved now and in the future and does not disappear as many open source projects unfortunately do.
