### ISSUE TITLE
[Bug]: OIDC authentification redirect_base_url doesn't produce a valid redirectUri

### ISSUE THREAD

**Issue by nodje** [drakkan/sftpgo#1841]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Using v2.6.4 with docker and providing an OIDC configuration with the following config:
```
      - SFTPGO_DATA_PROVIDER_EXTERNAL_AUTH_HOOK=https://keycloak.local.com/realms/ligoj
      # login method: 1 means OIDC for the WebAdmin UI + 2 means OIDC for the WebClient UI
      - SFTPGO_HTTPD_ENABLED_LOGIN_METHODS=3 # means that you can only login using OIDC on both WebClient and WebAdmin UI.
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL=https://keycloak.local.com/realms/ligoj #will add /.well-known/openid-configuration to this url and attempt to retrieve the provider configuration on startup
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID=sftpgo
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET=eCYE7FELLyNaH1EDdAAcGLTMLpHQWg9A
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL=https://sftpgo.local.com/"
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD="preferred_username"
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__ROLE_FIELD="sftpgo_role"
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__IMPLICIT_ROLES="false"
```
and working on the xxx_REDIRECT_BASE_URL element to fix the error I keep getting an invalid redirectUri error from keycloak:

```
2024-12-11 14:48:34,325 WARN  [org.keycloak.events] (executor-thread-42) type="LOGIN_ERROR", realmId="ligoj", realmName="ligoj", clientId="sftpgo", userId="null", ipAddress="172.21.0.1", error="invalid_redirect_uri", redirect_uri="https://sftpgo.local.com\"/web/oidc/redirect"
2024-12-11 14:56:37,796 WARN  [org.keycloak.events] (executor-thread-48) type="LOGIN_ERROR", realmId="ligoj", realmName="ligoj", clientId="sftpgo", userId="null", ipAddress="172.21.0.1", error="invalid_redirect_uri", redirect_uri="https://sftpgo.local.com/web/oidc/redirect\"/web/oidc/redirect"
2024-12-11 14:57:27,815 WARN  [org.keycloak.events] (executor-thread-53) type="LOGIN_ERROR", realmId="ligoj", realmName="ligoj", clientId="sftpgo", userId="null", ipAddress="172.21.0.1", error="invalid_redirect_uri", redirect_uri="https://sftpgo.local.com/\"/web/oidc/redirect"

```
There seem to be a concatenation problem between `redirect_base_url` and `/web/oidc/redirect`

I have been able to fix it manually in the browser URL and make the call which ultimately works if the `redirectUri=https://sftpgo.local.com/web/oidc/redirect`

Though I get an error message from SFTPgo after sending the login info:
```
Invalid authentication request
The authentication request does not meet security requirements
```
sftpgo  | {"level":"debug","time":"2024-12-11T15:01:27.961","sender":"httpd","message":"oidc authentication state did not match"}
sftpgo  | {"level":"warn","time":"2024-12-11T15:01:27.963","sender":"httpd","cipher_suite":"","local_addr":"172.21.0.6:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"172.21.0.3:43084","request_id":"7f69fe7f069a/SvXbo5IbWo-000005","uri":"http://sftpgo.local.com/web/oidc/redirect?state=a0d5319c0920bf2dbfadb6d990baf821aaec79b7ebd48c2f380c55776a6f2842&session_state=18046cc6-41f5-4098-bde7-2cd902e4c83a&iss=https%3A%2F%2Fkeycloak.local.com%2Frealms%2Fligoj&code=cfb8b790-fd69-4cc3-907a-9e165dc73a5d.18046cc6-41f5-4098-bde7-2cd902e4c83a.bca21934-6d59-495d-a1bd-3d8cad2c7692","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","resp_status":400,"resp_size":35673,"elapsed_ms":2}
``` 

I'm guessing at at a Realm Setting->Tokens issue but I have no idea what to configure here, and I can't seem to find anything relevant in the doc.

Help welcome for this `The authentication request does not meet security requirements` issue

### Steps to reproduce

As indicated above

### Expected behavior

As indicated above

### SFTPGo version

2.6.4

### Data provider

unrelated

### Installation method

Community Docker image

### Configuration

As indicated above

### Relevant log output

_No response_

### What are you using SFTPGo for?

Enterprise

### Additional info

_No response_

**Comment by drakkan** [comment]
This isn't a bug, you have a typo in your configuration, please remove the trailing `"`
