### ISSUE TITLE
sftpgo update

### ISSUE THREAD

**Issue by pengbojia** [drakkan/sftpgo#1843]
### Describe the solution you'd like

Hi,
I want to upgrade my SFTPGo from version 2.5.2. What steps should I take? What precautions should I consider? I look forward to your response. Thank you.

### What are you using SFTPGo for?

Enterprise

### Additional context

none

**Comment by drakkan** [comment]
Thanks for using SFTPGo, appreciated.

If you need support, guarantees and advice and want to use a supported copy of SFTPGo, you can consider our commercial [offers](https://sftpgo.com/plans).

As a community user you should be able to support yourself or you can try to open a discussion and hope that other community users will want to invest their time to help you.
