### ISSUE TITLE
Custom SSH proxy in portable mode with custom hooks

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#186]
I'd like embed sftpgo into a custom service and start it in portable mode, so it can basically act as an sftp proxy.

I'd also like to implement a custom hook, that sends a message to a queue (I'd rather not implement it as a process or an HTTP endpoint because of retries, etc)

Is this a supported use case at the moment? Can it even be supported? Tried to find the right extension points, but couldn't so far.

**Comment by drakkan** [comment]
Hi,

If for SFTP proxy you mean using another SFTP instance as "storage" backend in a similar way to S3 ecc... this is planned. I'll try to work on this after 1.1.0 release.

To implement your custom hook what kind of support do you need in SFTPGo? Thank you

**Comment by sagikazarmark** [comment]
> If for SFTP proxy you mean using another SFTP instance as "storage" backend in a similar way to S3 ecc

No, I actually meant "proxying" to a GCS bucket, so that works fine. It's a proxy in the sense that we provide it as an endpoint to upload files.

> To implement your custom hook what kind of support do you need in SFTPGo? Thank you

I was hoping that hooks are simply interfaces with an exec and an http implementation by default (based on the provided config) and that I can implement that interface as a custom hook that sends a message to a message queue.

Something like this:

```golang
type Hook interface{
    SomeEvent(ctx context.Contex, someEvent SomeEvent)
}

type execHook struct {} // execute a process

type httpHook struct {} // call an http URL

type customHook struct {} // my own hook sending a message to a queue
```

**Comment by drakkan** [comment]
No sorry, hooks are not defined in this way but I might consider improving them to be extensible

**Comment by sagikazarmark** [comment]
I think it would make sense for users who want to use sftpgo as a library (which is also a great use case IMO).

**Comment by drakkan** [comment]
> I think it would make sense for users who want to use sftpgo as a library (which is also a great use case IMO).

Yes, SFTPGo is not currently meant to be used as a library. I think we should refactor other things too to allow such use case

**Comment by drakkan** [comment]
regarding your use case what kind of message queue do you plan to use? Maybe I can add support for it directly inside SFTPGo however several hooks require a sync response so a message queue could complicate things (even if you use it as library)

**Comment by sagikazarmark** [comment]
I'm going to use [Watermill](https://github.com/ThreeDotsLabs/watermill) with RabbitMQ and Google PubSub for now.

Since I need certain guarantees for delivery (retry X times, alert if the queue is unavailable, etc), I'm definitely gonna need a custom implementation. For now, I think I'll settle for running a process.

> however several hooks require a sync response

I don't actually want to wait for an answer, I just want to send an event in the queue, so a sync response in this case would be the queue accepting the message.

**Comment by drakkan** [comment]
> I'm going to use [Watermill](https://github.com/ThreeDotsLabs/watermill) with RabbitMQ and Google PubSub for now.
> 
> Since I need certain guarantees for delivery (retry X times, alert if the queue is unavailable, etc), I'm definitely gonna need a custom implementation. For now, I think I'll settle for running a process.
> 
> > however several hooks require a sync response
> 
> I don't actually want to wait for an answer, I just want to send an event in the queue, so a sync response in this case would be the queue accepting the message.

This will work for notifications only hooks, for example the notification for an upload. Other hooks can require a response, for example the `pre-delete` one and other `pre-*` hooks that I could add in future. 

In general all the authentication hooks require a non-generic response too, so a queue seems not suitable for all the use cases.
 
However if you want to contribute your hook to the example directory it could be useful to others too and give ideas for future improvements. Thank you!

**Comment by sagikazarmark** [comment]
Yeah, notifications are my primary use case now, so the rest of the system can process the uploaded files.

Actually, the way you describe hooks sounds awfully familiar to Tusd hooks: https://github.com/tus/tusd/blob/master/docs/hooks.md

**Comment by drakkan** [comment]
Hi, thank you for you PR, I'll review it later this week, however before including SFTPGo inside another application please check that your usage is compatible with the SFTPGo license (GPL-3), thank you

**Comment by sagikazarmark** [comment]
> however before including SFTPGo inside another application please check that your usage is compatible with the SFTPGo license (GPL-3)

I'm not going to distribute it, so it's not a problem, but I fully plan to contribute back any meaningful change anyway, so even if I did, the amount of code I would have to share and provide under GPL-3 would basically be a main.go. 😄
