### ISSUE TITLE
RPM Linux Packages 

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#189]
Hi, please change the path of sftpgo daemon from /usr/bin to /usr/sbin, thnx!

**Comment by drakkan** [comment]
Hi,

I'm unsure, I known that historically daemons are in `/usr/sbin` but please try `man file-hierarchy`

```
/bin/, /sbin/, /usr/sbin/
           These compatibility symlinks point to /usr/bin/, ensuring that
           scripts and binaries referencing these legacy paths correctly find
           their binaries.
```

so `/usr/sbin` seems a legacy path nowaday, for example on Arch Linux `sbin` is a symlink to `bin`

```
ls -la /usr/sbin
lrwxrwxrwx 1 root root 3  3 set 00.30 /usr/sbin -> bin
```

additionally SFTPGo can be also used in portable mode and so it is both a daemon and a user command

**Comment by fdefilippo** [comment]
You are right.
