### ISSUE TITLE
Question about docu

### ISSUE THREAD

**Issue by hall-of-code** [drakkan/sftpgo#191]
Hello,

Im new at sftpgo and I can't find the "Basic usage documenation" ? So ist there any explanation how to add a User ect?

Or are there only the GUI or the REST API, and no Command Line -command for that?

Thx

**Comment by drakkan** [comment]
I wrote some basic instructions [here](https://github.com/drakkan/sftpgo#users-and-folders-management). Feel free to send a pull request to improve them, thank you!
