### ISSUE TITLE
Support for key exchange algorithm

### ISSUE THREAD

**Issue by kesavkolla** [drakkan/sftpgo#192]
I've some old clients which still uses diffie-hellman-group1-sha1 diffie-hellman-group-exchange-sha1 algorithms.  Is it possible to support these algorithms for key exchange?

**Comment by drakkan** [comment]
Hi,

you can explicitly configure the supported kex algos, please take a look [here](https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md) search `kex_algorithms`, 

`diffie-hellman-group1-sha1` should work

**Comment by kesavkolla** [comment]
How to specify the value? Is it I've to give `diffie-hellman-group1-sha1` or `kexAlgoDH1SHA1` ?

**Comment by fdefilippo** [comment]
as @drakkan suggest, just modify the config file sftpgo.json:

>   "sftpd": {
>     "bind_port": 2022,
>     "bind_address": "",
>     "max_auth_tries": 3,
>     "banner": "",
>     "host_keys": [],
>     "kex_algorithms": ["diffie-hellman-group1-sha1","ecdh-sha2-nistp256","and so on"],
>     "ciphers": [],
>     "macs": [],
>
