### ISSUE TITLE
Upgrading to 1.1 PPA from 0.9.6 installed as service

### ISSUE THREAD

**Issue by keybits** [drakkan/sftpgo#193]
Thanks for the recent updates.

I have 0.9.6 running on Ubuntu 20.04 that I installed as a service using this guide: https://github.com/drakkan/sftpgo/blob/master/docs/service.md

I'd like to now use the Ubuntu PPA.

Is there a recommended way to 'upgrade'? Or should I remove everything related to the manually installed version first?

**Comment by drakkan** [comment]
Hi,

I have not tested this updgrade path, I think the package installed using the PPA could have issue if it finds some file already manually installed. Additionally the package installed using the PPA will run using the `sftpgo` user and not as `root` anymore, so you have to change the permissions for home directories of the virtual users etc ...

After 1.1.0 I improved a lot the Docker image and I switched from GitHub Container Registry to DockerHub so I have to make a new release, this will probably happen the next week end. In this release I'll do a small change to the Linux package and the PPA too, so I suggest to wait for 1.1.1 before upgrading. Thank you

**Comment by keybits** [comment]
Thanks for the quick reply 😄 

All good - I'll wait for 1.1.1, then do a clean removal and start fresh with the PPA.

Thanks again for this super useful software.

**Comment by drakkan** [comment]
1.1.1 is now available, regards
