### ISSUE TITLE
transport is getting disconnected

### ISSUE THREAD

**Issue by kesavkolla** [drakkan/sftpgo#194]
I've a very old Java based SFTP client which is trying to use upload a file to sftpgo server. After few seconds of transfer I get an error on client side saying session terminated by server. On the server logs I see error: <nil>

Can someone please help me out to figure out why the server is terminating connection.  Here is the log I've from server:

```json
{"level":"info","time":"2020-10-16T09:12:45.995","sender":"SSH","connection_id":"4e181dd9d235c34fe31c20f66d707762e4402e15","message":"User id: 1, logged in with: \"password\", username: \"roundhill\", home_dir: \"/data/mounts/sftp/roundhill/extracts1/\" remote addr: \"72.252.253.148:62197\""}
{"level":"debug","time":"2020-10-16T09:12:46.085","sender":"dataprovider_sqlite","message":"last login updated for user \"roundhill\""}
{"level":"debug","time":"2020-10-16T09:12:46.085","sender":"common","connection_id":"4e181dd9d235c34fe31c20f66d707762e4402e15","message":"ssh connection added, num open connections: 1"}
{"level":"debug","time":"2020-10-16T09:12:46.141","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"connection added, num open connections: 1"}
{"level":"debug","time":"2020-10-16T09:12:46.383","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"transfer added, id: 1, active transfers: 1"}
{"level":"debug","time":"2020-10-16T09:12:46.632","sender":"common","connection_id":"4e181dd9d235c34fe31c20f66d707762e4402e15","message":"ssh connection removed, num open ssh connections: 0"}
{"level":"warn","time":"2020-10-16T09:12:46.632","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"Unexpected error for transfer, path: \"/data/mounts/sftp/roundhill/extracts1/hs_res_detail_6271083.xml\", error: \"EOF\" bytes sent: 0, bytes received: 65288 transfer running since 249 ms"} 
{"level":"debug","time":"2020-10-16T09:12:46.636","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"atomic upload completed, rename: \"/data/mounts/sftp/roundhill/extracts1/.sftpgo-upload.bu4scvnp9ciu022bqt3g.hs_res_detail_6271083.xml\" -> \"/data/mounts/sftp/roundhill/extracts1/hs_res_detail_6271083.xml\", error: <nil>"} 
{"level":"debug","time":"2020-10-16T09:12:46.636","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"upload file size 65288 stat error <nil>"}
{"level":"info","time":"2020-10-16T09:12:46.636","sender":"Upload","elapsed_ms":252,"size_bytes":65288,"username":"roundhill","file_path":"/data/mounts/sftp/roundhill/extracts1/hs_res_detail_6271083.xml","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","protocol":"SFTP"}
{"level":"warn","time":"2020-10-16T09:12:46.636","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"transfer error: EOF, path: \"/data/mounts/sftp/roundhill/extracts1/hs_res_detail_6271083.xml\""}
{"level":"debug","time":"2020-10-16T09:12:46.636","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"transfer removed, id: 1 active transfers: 0"}
{"level":"debug","time":"2020-10-16T09:12:46.636","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"connection closed, sending exit status"}
{"level":"debug","time":"2020-10-16T09:12:46.637","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"sent exit status {Status:0} error: EOF"}
{"level":"debug","time":"2020-10-16T09:12:46.637","sender":"SFTP","connection_id":"SFTP_4e181dd9d235c34fe31c20f66d707762e4402e15_1","message":"connection removed, num open connections: 0"}
```

**Comment by drakkan** [comment]
Hi,

can I test this client myself?

Is the trasferred file complete? 65288 is the right size or is it truncated?

You could try to disable atomic uploads but I'm not sure this way you will solve the issue

**Comment by kesavkolla** [comment]
It is truncated. We can't test the client. It's some reporting platform, when the report is completed it will upload report to the SFTP server.

**Comment by kesavkolla** [comment]
I don't know this 65288 seems some magic number. I've 3 files which are exactly have 65288 and all three got truncated at that byte location.

**Comment by drakkan** [comment]
The server log means that the client closes the connection before the transfer is completed. 

This error is triggered from pkg/sftp [here](https://github.com/pkg/sftp/blob/master/request-server.go#L170). 

So the clients seems disconnected. This could be caused by a real disconnection or by some unexpected packet but we should enable debug in pkg/sftp to know what is happening.

As first step try to disable atomic uploads, maybe the client does a periodic stat and with atomic uploads enabled the file is uploaded to a temporary location and so not found

**Comment by drakkan** [comment]
To get useful info we should change pkg/sftp code to enable more debug [here](https://github.com/pkg/sftp/blob/master/packet.go#L23) and then compile sftpgo passing `-tags debug`, and we should observe log to the stdout

**Comment by kesavkolla** [comment]
FYI: I changed the upload_mode to 0. Exact same error after 65288 bytes disconnect happened and file is truncated.

**Comment by drakkan** [comment]
another way to provide info is to run the transfer against OpenSSH and in `/etc/ssh/sshd_config` set:

```
LogLevel DEBUG3
```

and restart OpenSSH.

You should get logs like these ones:

```
ott 16 22:40:40 p1 sftp-server[1641]: received client version 3
ott 16 22:40:40 p1 sftp-server[1641]: debug3: request 1: realpath
ott 16 22:40:40 p1 sftp-server[1641]: realpath "."
ott 16 22:40:40 p1 sftp-server[1641]: debug1: request 1: sent names count 1
ott 16 22:40:50 p1 sftp-server[1641]: debug3: request 2: stat
ott 16 22:40:50 p1 sftp-server[1641]: stat name "/tmp/ros.txt"
ott 16 22:40:50 p1 sftp-server[1641]: debug3: request 2: sent status 2
ott 16 22:40:50 p1 sftp-server[1641]: sent status No such file
ott 16 22:40:50 p1 sftp-server[1641]: debug3: request 3: open flags 26
ott 16 22:40:50 p1 sftp-server[1641]: open "/tmp/ros.txt" flags WRITE,CREATE,TRUNCATE mode 0644
ott 16 22:40:50 p1 sftp-server[1641]: debug1: request 3: sent handle handle 0
ott 16 22:40:50 p1 sftp-server[1641]: debug1: request 4: write "/tmp/ros.txt" (handle 0) off 0 len 4034
ott 16 22:40:50 p1 sftp-server[1641]: debug3: request 4: sent status 0
ott 16 22:40:50 p1 sftp-server[1641]: sent status Success
ott 16 22:40:50 p1 sftp-server[1641]: debug3: request 4: close handle 0
ott 16 22:40:50 p1 sftp-server[1641]: close "/tmp/ros.txt" bytes read 0 written 4034
ott 16 22:40:50 p1 sftp-server[1641]: debug3: request 4: sent status 0
ott 16 22:40:50 p1 sftp-server[1641]: sent status Success
```

hopefully they contain useful info to understand what is happening in your case, thank you

**Comment by kesavkolla** [comment]
I've the debug of pkg/sftp. Is there anything fishy here?

```
2020/10/17 04:46:24 Sending packet: 0
2020/10/17 04:46:24 break! -- outgoing: 0; incoming: 0
2020/10/17 04:46:25 incoming id (oid): 1 (2)
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 1
2020/10/17 04:46:25 outgoing id (oid): 1 (2)
2020/10/17 04:46:25 Sending packet: 1
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 0
2020/10/17 04:46:25 incoming id (oid): 2 (3)
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 1
2020/10/17 04:46:25 outgoing id (oid): 2 (3)
2020/10/17 04:46:25 Sending packet: 2
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 0
2020/10/17 04:46:25 incoming id (oid): 3 (4)
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 1
2020/10/17 04:46:25 outgoing id (oid): 3 (4)
2020/10/17 04:46:25 Sending packet: 3
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 0
2020/10/17 04:46:25 incoming id (oid): 4 (5)
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 1
2020/10/17 04:46:25 outgoing id (oid): 4 (5)
2020/10/17 04:46:25 Sending packet: 4
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 0
2020/10/17 04:46:25 incoming id (oid): 5 (6)
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 1
2020/10/17 04:46:25 outgoing id (oid): 5 (6)
2020/10/17 04:46:25 Sending packet: 5
2020/10/17 04:46:25 break! -- outgoing: 0; incoming: 0
```

**Comment by drakkan** [comment]
Hi, these logs are quiet useless, please set:

```
debugDumpTxPacket      = true
debugDumpRxPacket      = true
```

here:

https://github.com/pkg/sftp/blob/master/packet.go#L23

adding some printf inside `Serve` here:

https://github.com/pkg/sftp/blob/master/request-server.go#L140

to exactly understand where the error is generated (packetWorker, serveLoop and inside serveLoop: recvPacket and makePacket) would be useful too. The openssh logs could be help too, so I can compare and try to understand the difference.

Thank you, your debug is really appreciated!

**Comment by drakkan** [comment]
Hi,

do you have updates on this?

I would really like to fix compatibility with this old client, but it's not possible without more information or a way to test it myself,

thank you

**Comment by kesavkolla** [comment]
What my suspect was this old client is using SFTP v1 protocol that's why the client was keep getting disconnected. Now I've replaced old client and using winscp script with SFTP v3 then it started working.

Curious is there any way to support SFTP v1?

**Comment by drakkan** [comment]
OpenSSH removed v1 support with version 7.6 released on 2017-10-03, so if this is the disconnect reason this client should not work with recent OpenSSH versions either. 

I don't think pkg/sftp will accept a patch to add v1 support. I would like to add v6 support instead :)

**Comment by kesavkolla** [comment]
That is true. What to do... I've to deal with companies like Oracle who doesn't update their version of libraries. That's the sad reality. I'm closing this issue as I've found a way to use a modern alternative.

**Comment by drakkan** [comment]
> That is true. What to do... I've to deal with companies like Oracle who doesn't update their version of libraries. That's the sad reality. 

This is how most proprietary software behaves.

I quickly read the SFTP specs, there are really few changes between v1 and v3, while SSH protocol itself was changed a lot, so v1 should be supported in `crypto/ssh` this is quite unlikely

> I'm closing this issue as I've found a way to use a modern alternative.

Good!
