### ISSUE TITLE
Images moved to DockerHub

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#195]
I was a bit surprised (and sad) to see images being moved to DockerHub. What's the reason for that?

DockerHub recently introduced [rate limits](https://docs.docker.com/docker-hub/download-rate-limit/) for unauthenticated image pulls which is a concern for a lot of us.

Can you at least publish images on ghcr.io as well? Here is an example how to do that: https://gist.github.com/sagikazarmark/0119e1f3dde0d8e755fd0ee5a5ef4cdc

**Comment by drakkan** [comment]
Ok, I'll add the image to GHCR too. GHCR seems a beta service and support seems very slow to respond and understand the reported issues. Most users will expect to find docker images on docker hub

**Comment by sagikazarmark** [comment]
> GHCR seems a beta service
It probably is, but it will only get better if people start to use it. :)

> Most users will expect to find docker images on docker hub
I guess that's fair, but it costs nothing to push to both registries.

**Comment by drakkan** [comment]
I just pushed 1.1.1 images to ghcr.

Inside the readme, on ghcr, all relative links are broken. I cannot find a way to unlink the repo readme from the package

**Comment by drakkan** [comment]
Let see if this time I can get a [proper response](https://github.community/t/ghcr-unlink-readme-from-repo/138562)

**Comment by sagikazarmark** [comment]
Thanks!
