### ISSUE TITLE
Replace username with UID

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#196]
Certain security solutions (ie. Kubernetes security policies) check the UID in the container image to enforce using non-root users. Unfortunately, they usually fail when the `USER` is not a UID, so I'd suggest replacing `USER sftpgo` with `USER 1000`, or even better: `USER 1000:1000` to add the GID as well.

**Comment by drakkan** [comment]
[Fixed](https://github.com/drakkan/sftpgo/blob/master/Dockerfile#L63) thank you for reporting
