### ISSUE TITLE
REST API/Web admin users and permissions

### ISSUE THREAD

**Issue by drakkan** [drakkan/sftpgo#197]
Hi,

currently REST API and Web Admin can be protected using HTTP basic authentication via an file created using the Apache's `htpasswd` tool.

This works well for basic needs but I think it can be improved.

We can move the admins inside the data provider and add support for read and write permissions too. After the initial installation a default admin with a predefined password will be created and this admin can create other administrators and set their permissions via REST/API or Web Admin. For example you can create a new admin that can only create users but not terminate active connections and so on.

Maybe external authentication for this administrators could be added too so for example existing LDAP users or such can be used.

What do you think about? Is this feature useful for your use case? Thank you!

**Comment by HiFiPhile** [comment]
Hi,

Currently in my configuration SFTPGO's Web Admin and my other services are hidden behind HAProxy, so I can centralize authentication and use Fail2Ban.

I feel like multi-administrators is a nice to have but niche for most cases. 

Maybe we can start by adding `X-Real-IP` or `X-Forwarded-For` to have real ip in logs and add a Fail2Ban config.

**Comment by drakkan** [comment]
> Hi,
> 
> Currently in my configuration SFTPGO's Web Admin and my other services are hidden behind HAProxy, so I can centralize authentication and use Fail2Ban.
> 
> I feel like multi-administrators is a nice to have but niche for most cases.
> 
> Maybe we can start by adding `X-Real-IP` or `X-Forwarded-For` to have real ip in logs and add a Fail2Ban config.

Thank you for your feedback.

The real ip should be already [supported](https://github.com/drakkan/sftpgo/blob/master/httpd/router.go#L26) can you please confirm? Regarding Fail2Ban I don't know it very well a pull request would be great

**Comment by HiFiPhile** [comment]
> The logs should already contain the real ip.

Indeed, that's the case :)

**Comment by HiFiPhile** [comment]
Hi,

Do you think it's a good idea to add a "trusted reverse proxy" in config ? For anyone who don't use reverse proxy, source ip can be tricked by adding X-Real-IP or X-Forwarded-For.

**Comment by drakkan** [comment]
Hi,

we could add something similar to HA proxy config for reverse proxy too, for example:

- ProxyProtocol
  - `0`, disabled
  - `1`, enabled. Header will be used and requests without header will be accepted
  - `2` required. 
- ProxyAllowed. List of IP addresses and IP ranges allowed to send the proxy header. If proxy protocol=1 and the remote addres is not inside the list then the header will be ignored. If proxy protocol=2 both the proxy header and the remote address (the ip that estabilish the connection) must be inside the allowed list and must match

what do you think about? Thank you

**Comment by HiFiPhile** [comment]
Yes it looks good. Maybe it's better to choose a name other than `Proxy Protocol`

**Comment by ynqjwsm** [comment]
> Hi,
> 
> Currently in my configuration SFTPGO's Web Admin and my other services are hidden behind HAProxy, so I can centralize authentication and use Fail2Ban.
> 
> I feel like multi-administrators is a nice to have but niche for most cases.
> 
> Maybe we can start by adding `X-Real-IP` or `X-Forwarded-For` to have real ip in logs and add a Fail2Ban config.

Hi,
how do you achieve low-level file synchronization ?  use s3 as data provider?

**Comment by HiFiPhile** [comment]
Hi,
What do you mean low-level file synchronization ? I'm using sftpgo to serve local files on my home server.

**Comment by drakkan** [comment]
Hi, 

SFTPGo is useful if you want to serve S3/GCS/Azure buckets over SFTP/FTP,if you want to sync local files with a S3 bucket you probably need another tool, for example [rclone](https://rclone.org/)

**Comment by mikroskeem** [comment]
> Yes it looks good. Maybe it's better to choose a name other than Proxy Protocol

In my opinion this is quite fitting name, mainly because HAProxy also calls it like this: http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

**Comment by HiFiPhile** [comment]
> > Yes it looks good. Maybe it's better to choose a name other than Proxy Protocol
> 
> In my opinion this is quite fitting name, mainly because HAProxy also calls it like this: http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

That's exactly my concern, since here "ProxyProtocol" it's different to Haproxy's ProxyProtocol.  Or we can implement Haproxy's ProxyProtocol.

**Comment by mikroskeem** [comment]
Oops, I'm unable to read.

**Comment by drakkan** [comment]
we can add HAProxy's ProxyProtocol to httpd too, I'm not sure if we can reuse the same configuration parameters we already have in the "common" section. Perhaps the httpd proxy might require a different configuration than sftp/ftp.

**Comment by fdefilippo** [comment]
> Hi,
> 
> currently REST API and Web Admin can be protected using HTTP basic authentication via an file created using the Apache's `htpasswd` tool.
> 
> This works well for basic needs but I think it can be improved.
> 
> We can move the admins inside the data provider and add support for read and write permissions too. After the initial installation a default admin with a predefined password will be created and this admin can create other administrators and set their permissions via REST/API or Web Admin. For example you can create a new admin that can only create users but not terminate active connections and so on.
> 
> Maybe external authentication for this administrators could be added too so for example existing LDAP users or such can be used.
> 
> What do you think about? Is this feature useful for your use case? Thank you!

Hi, I think adding the group field to the users table is the best thing, the admins group will contain the admin users and maybe even the ability to define which user group so that you have many group admins:

- 0 global administrator
- from 1 onwards the gid of the administered groups

cheers, f.

**Comment by sergiz** [comment]
> 
> 
> Hi,
> 
> currently REST API and Web Admin can be protected using HTTP basic authentication via an file created using the Apache's `htpasswd` tool.
> 
> This works well for basic needs but I think it can be improved.
> 
> We can move the admins inside the data provider and add support for read and write permissions too. After the initial installation a default admin with a predefined password will be created and this admin can create other administrators and set their permissions via REST/API or Web Admin. For example you can create a new admin that can only create users but not terminate active connections and so on.
> 
> Maybe external authentication for this administrators could be added too so for example existing LDAP users or such can be used.
> 
> What do you think about? Is this feature useful for your use case? Thank you!

I believe this can already be achieved using existing API. I mean whoever might be interested can already build such interface around it.
