### ISSUE TITLE
Docker config dir

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#198]
Looking at the Docker setup, the config dir is not set to `/etc/sftpgo` and the default is `.` which is `/var/lib/sftpgo`, so essentially the default config file is not loaded. Am I missing something?

I'd probably set `SFTPGO_CONFIG_DIR` as an environment variable. User should most probably mount their config files in that directory anyway. They can still override it using `--config-dir`.

**Comment by atruskie** [comment]
Hi @sagikazarmark. I pushed against setting environment variables in #190 and changes were made in 6c0839e1973083201d7d9c3accc01c473770b396.

You'll see in that issue I pushed to not set environment variables unless necessary.

The image also does use the default config at `/etc/sftpgo/sftpgo.json`. You can verify this yourself with:

```pwsh
C:\Users\Anthony> docker run drakkan/sftpgo
{"level":"info","time":"2020-10-20T00:11:54.128","sender":"service","message":"starting SFTPGo 1.1.1-756c3d05-2020-10-17T20:47:41Z +metrics +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, profile: false"}
{"level":"debug","time":"2020-10-20T00:11:54.137","sender":"config","message":"config file used: '\"/etc/sftpgo/sftpgo.json\"', config loaded:
<...snip...>
```

Then if you want to use a custom config, you mount it in `/var/lib/sftpgo` and it is used automatically.
If you do not want to use a custom config, you don't have to. Just set environment variables as you normally would.

I was also confused when I first read the dockerfile. The magic is: if the config file is missing from the current work directory it will search default paths, as you can see in:

https://github.com/drakkan/sftpgo/blob/b51d795e049e15df03495644d1b0f7f51206583d/config/config.go#L242-L247

**Comment by drakkan** [comment]
@atruskie thank you for explaing how config file is loaded, I have nothing to add. @sagikazarmark please close this issue if you have no further questions regarding this topic

**Comment by sagikazarmark** [comment]
Ah, you are right. Thanks! (Forget the fact that a) I know sftpgo uses Viper and b) I maintain it 😂 )
