### ISSUE TITLE
SQLite db dump and import?

### ISSUE THREAD

**Issue by onerule-be** [drakkan/sftpgo#202]
When running on azure container instances, my preferred dataprovider would be sqlite on a mounted volume. However, that does not work as the db file is always locked. 

Is there a way to periodically dump the sqlite db into a file on a mounted volume? 
Could I load that file into the db when restarting the container?

**Comment by drakkan** [comment]
Hi,

are you running multiple SFTPGo instance using the same SQLite database? If so this usage is not supported by SQLite.

You can use the [dumpdata/loaddata](https://github.com/drakkan/sftpgo/blob/master/httpd/schema/openapi.yaml#L653) REST API to backup/restore your data in a database independent format. See also the [example REST API CLI](https://github.com/drakkan/sftpgo/tree/master/examples/rest-api-cli#backup-data).

After v1.1.1 I also added support to [load users/folders from a dump on startup](https://github.com/drakkan/sftpgo/commit/bb5207ad77a6b99e40de2367fef6de5ee19ad405)

**Comment by onerule-be** [comment]
I'm just running a single SFTPGo instance. The volume on azure container instances is mounted as a CIFS mount. This causes issues with the SQLite DB when stored on the mounted volume.

I'll investigate the API.

**Comment by drakkan** [comment]
This link could help:

https://support.shotgunsoftware.com/hc/en-us/community/posts/209491808-Getting-database-is-locked-on-NFS-and-CIFS-setup

**Comment by onerule-be** [comment]
Thanks for the link. However, azure container instances (via ARM templates) do not let you specify mount parameters. 
The REST API is also not that easily implemented and triggered for me. 

Would it be a big change to trigger the export from the web interface?

**Comment by drakkan** [comment]
A backup is as simple as this:

```
curl "http://127.0.0.1:8080/api/v1/dumpdata?output_file=backup_test.json"
```

or copy the url in a browser. The restore is similar.

It is not exposed from the web since the file is saved on the disk, inside the configured backup path, to avoid to expose sensitive information over the network

**Comment by drakkan** [comment]
In your case, if you are unable to fix the locking issue and you cannot use a provider such as `PostgreSQL` or `MySQL` I suggest to use the memory provider. You can provide initial users using the data_provider `name` configuration key. Search "memory" in this [doc](https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md) for details. In this way you will not be able to persist quotas. 

You could also give a try to the `bolt` provider. It is, from a functional point of view, very similar to `SQLite` provider, but maybe it locks the database file in a way compatible with cifs mounts. Using bolt provider all the features will be available.

**Comment by drakkan** [comment]
> Thanks for the link. However, azure container instances (via ARM templates) do not let you specify mount parameters.

I never user azure container instances, however mount options seem configurable, take a look here:

https://docs.microsoft.com/it-it/azure/aks/azure-files-volume#mount-options

> The REST API is also not that easily implemented and triggered for me.
> 
> Would it be a big change to trigger the export from the web interface?

**Comment by onerule-be** [comment]
> You could also give a try to the `bolt` provider. It is, from a functional point of view, very similar to `SQLite` provider, but maybe it locks the database file in a way compatible with cifs mounts. Using bolt provider all the features will be available.

This solved it for me. The bolt provider has no immediate issues with the CIFS mount.

**Comment by drakkan** [comment]
If bolt provider works fine, please close this issue, thank you
