### ISSUE TITLE
DAV problems accessing files containing : (colon) in name

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#203]
hello, trying to access a file using webdav, whose storage is an s3 (minio), whose name contains ":" I get the following error:

`{"level":"debug","time":"2020-10-25T09:40:13.358","sender":"DAV","connection_id":"DAV_buajjradsk9cfe02f6j0","message":"error running stat on path \"/ack/datafile.bin.ff81b5a8-30c7-41f3-b3b4-19223cbbbd90.2020-10-25.09\": 404 no such file or directory"}
`
```
$ mc stat s3/test/ack/datafile.bin.ff81b5a8-30c7-41f3-b3b4-19223cbbbd90.2020-10-25.09:32:36.355829.COA
Name      : datafile.bin.ff81b5a8-30c7-41f3-b3b4-19223cbbbd90.2020-10-25.09:32:36.355829.COA
Date      : 2020-10-25 09:32:36 CET
Size      : 302 B
ETag      : 5391124ae0ba921b418c77ca7ec4f7ea
VersionID : 6151a8ab-dd43-4962-aa11-5431ad38d6bd
Type      : file
Expiration: 2020-11-02 01:00:00 CET (lifecycle-rule-id: testin)
Metadata  :
  Content-Type: application/octet-stream
```

**Comment by drakkan** [comment]
Hi,

thank you for reporting this issue. I just tested using nautilus as webdav client and it seems to work (both upload and download using minio and local fs as backend).

I get logs such as these ones:

```
{"level":"info","time":"2020-10-25T10:04:51.539","sender":"webdavd","elapsed_ms":11,"method":"GET","proto":"HTTP/1.1","remote_addr":"127.0.0.1:44740","request_id":"buajvcvcdrp5o1coul40","uri":"http://127.0.0.1:10080/tests3/sss/datafile.bin.ff81b5a8-30c7-41f3-b3b4-19223cbbbd90.2020-10-25.09%3A32%3A36.355829.COA","user_agent":"gvfs/1.46.1"}
{"level":"info","time":"2020-10-25T10:04:51.548","sender":"webdavd","elapsed_ms":5,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"127.0.0.1:44740","request_id":"buajvcvcdrp5o1coul4g","uri":"http://127.0.0.1:10080/tests3/sss/datafile.bin.ff81b5a8-30c7-41f3-b3b4-19223cbbbd90.2020-10-25.09%3A32%3A36.355829.COA","user_agent":"gvfs/1.46.1"}
```

can you post the logs for your GET/PROPFIND requests? Is your dav client able to handle the same file using another dav server?

**Comment by fdefilippo** [comment]
it could be the windows client's fault:

```
curl -sS -X PROPFIND -u test:xxxxxxxx -X PROPFIND https://test:2080/test|xmllint --pretty 1 -|grep "<D:href"
<D:href>/test/ack/datafile.bin.f9718504-ea90-4840-a90e-ff6c0f43fef5.2020-10-25.07:38:36.407595.COA</D:href>
```
 and yes windows name can't handle them:

https://docs.microsoft.com/it-it/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#file_and_directory_names
