### ISSUE TITLE
Run as subsystem

### ISSUE THREAD

**Issue by d4z3x** [drakkan/sftpgo#204]
Hi there,

First off, amazing work! And the help and pointers in another repo!

Now, for the point... I've combed through the docs. But I can't find a way to run this as a subsystem through sshd. Using sshd, I need to force members of a specific LDAP/IPA group in Linux to launch the sftpgo binary (much like how the bundled sftp-server works). 

Is this possible? With a subsystem, no need for an auth check or use SSHD inside of soft-go. And run on default port 22-ssh (corp firewall only allows 22)... 

Side note:
Mapping users is almost perfect, and I need to map each user coming in to a system user. I suppose for now, to keep things simple, I can add the users through the web interface, and map the UID to the system user or via the hook run a chmod on an upload/etc event.

**Comment by drakkan** [comment]
Hi,

running SFTPGo as SSH subsystem is not currently supported. I could investigate how to add such support.

If you can run SFTPGo as system service it should be able to handle just fine your use case: you only have to write an external authentication hook that returns the user with the correct home dir and uid/gid

**Comment by farhany** [comment]
> Hi,
> 
> running SFTPGo as SSH subsystem is not currently supported. I could investigate how to add such support.

Would need to plumb io.Stdout, io.Stdin and disable ssh. Thanks for this. I will take a look as well, and see if I can help.
 
> If you can run SFTPGo as system service it should be able to handle just fine your use case: you only have to write an external authentication hook that returns the user with the correct home dir and uid/gid

The problem is that the we need to use port 22 for regular domain authentication, so that wouldn't be a plugin solution, sadly... at this point.

Hooks are pretty awesome.

**Comment by drakkan** [comment]
> > Hi,
> > running SFTPGo as SSH subsystem is not currently supported. I could investigate how to add such support.
> 
> Would need to plumb io.Stdout, io.Stdin and disable ssh. Thanks for this. I will take a look as well, and see if I can help.

Yes, for what I understand, we basically need to wrap `os.Stdin` and `os.Stdout` inside an `io.ReadWriteCloser` and then pass this wrapper to [NewRequestServer](https://github.com/pkg/sftp/blob/master/request-server.go#L51) and it should work.

We could add a new subcommand to sftpgo, something like this:

```
sftpgo sftp-subsystem -u <username> -h <home dir> and so on
```

I'll try to take a look as soon as I have some free time, probably the next weekend, thank you

> 
> > If you can run SFTPGo as system service it should be able to handle just fine your use case: you only have to write an external authentication hook that returns the user with the correct home dir and uid/gid
> 
> The problem is that the we need to use port 22 for regular domain authentication, so that wouldn't be a plugin solution, sadly... at this point.
> 
> Hooks are pretty awesome.

**Comment by d4z3x** [comment]
> > Would need to plumb io.Stdout, io.Stdin and disable ssh. Thanks for this. I will take a look as well, and see if I can help.
> 
> Yes, for what I understand, we basically need to wrap `os.Stdin` and `os.Stdout` inside an `io.ReadWriteCloser` and then pass this wrapper to [NewRequestServer](https://github.com/pkg/sftp/blob/master/request-server.go#L51) and it should work.

I didn't use sftp.NewServer, but the approach should be similar:

```
        channel := os.Stdin

        server, err := sftp.NewServer(
                channel,
                serverOptions...,
        )
```
> We could add a new subcommand to sftpgo, something like this:
> 
> ```
> sftpgo sftp-subsystem -u <username> -h <home dir> and so on
> ```
> 
> I'll try to take a look as soon as I have some free time, probably the next weekend, thank you

Sounds awesome.

**Comment by drakkan** [comment]
Hi,

I just did a quick test and running sftpgo as subsystem seems fine. However I want to know how you actually pass username and home dir, I tryed this with no luck:

```
Subsystem      sftp    /home/nicola/goprojects/sftpgo/sftpgo servesubsys -c /home/nicola/goprojects/sftpgo -U %u -H /tmp/%u -L /tmp
```

I get `%u` and not the username and is the same using this one:

```
Match Group nicola
        ForceCommand /home/nicola/goprojects/sftpgo/sftpgo servesubsys -c /home/nicola/goprojects/sftpgo -U %u -H /tmp/%u -L /tmp
```

Probably configuring `AcceptEnv` I can get `HOME` and `USERNAME` (not tested yet). I have no more time for now, can you please share your relavant `sshd_config`? Thank you

**Comment by drakkan** [comment]
`user.Current` is the [correct way](https://github.com/openssh/openssh-portable/blob/master/sftp-server-main.c#L47) no need to pass user and home dir as command parameteres

**Comment by d4z3x** [comment]
The way the sshd_config works is that does a ```Group|User Match``` and then uses ```ForceCommand``` to run a shell script, which it switches on ```rsync```/```sftp```/```scp``` based on ```$SSH_ORIGINAL_COMMAND```. This allows restricting access to anything you prefer. In my case, I wish them to have no shell access.

**Comment by drakkan** [comment]
So I suppose sftp-server will lookup for username and home dir. I think I'll push this change later today or tomorrow so you can test it. Here is the current usage (it could change before merging):

```
sftpgo startsubsys -h
In this mode SFTPGo speaks the server side of SFTP protocol to stdout and
expects client requests from stdin.
This mode is not intended to be called directly, but from sshd using the
Subsystem option.
For example adding a line like this one in "/etc/ssh/sshd_config":

Subsystem	sftp	sftpgo startsubsys

Command-line flags should be specified in the Subsystem declaration.

Usage:
  sftpgo startsubsys [flags]

Flags:
  -c, --config-dir string    Location for SFTPGo config dir. This directory
                             should contain the "sftpgo" configuration file
                             or the configured config-file and it is used as
                             the base for files with a relative path (eg. the
                             private keys for the SFTP server, the SQLite
                             database if you use SQLite as data provider).
                             This flag can be set using SFTPGO_CONFIG_DIR
                             env var too. (default ".")
  -f, --config-file string   Name for SFTPGo configuration file. It must be
                             the name of a file stored in config-dir not the
                             absolute path to the configuration file. The
                             specified file name must have no extension we
                             automatically load JSON, YAML, TOML, HCL and
                             Java properties. Therefore if you set "sftpgo"
                             then "sftpgo.json", "sftpgo.yaml" and so on
                             are searched.
                             This flag can be set using SFTPGO_CONFIG_FILE
                             env var too. (default "sftpgo")
  -h, --help                 help for startsubsys
  -j, --log-to-journald      Send logs to journald. Only available on Linux.
                             Use:
                             
                             $ journalctl -o verbose -f
                             
                             To see full logs.
                             If not set, the logs will be sent to the standard
                             error
  -v, --log-verbose          Enable verbose logs. This flag can be set
                             using SFTPGO_LOG_VERBOSE env var too.
                              (default true)
  -p, --preserve-home        If the user already exists, the existing home
                             directory will not be changed
```

SFTPGo will get the current user and home directory using `user.Current()`. This mode is not compatible with `bolt` and `sqlite` provider since they don't allow to share the same database among different process

**Comment by d4z3x** [comment]
> So I suppose sftp-server will lookup for username and home dir. I think I'll push this change later today or tomorrow so you can test it. Here is the current usage (it could change before merging):
> 
> ```
> sftpgo startsubsys -h
> In this mode SFTPGo speaks the server side of SFTP protocol to stdout and
> expects client requests from stdin.
> This mode is not intended to be called directly, but from sshd using the
> Subsystem option.
> For example adding a line like this one in "/etc/ssh/sshd_config":
> 
> Subsystem	sftp	sftpgo startsubsys

Can't to start playing with it! I tried to make it work, but I don't know enough of the architecture to decouple the code from ssh, and various data providers it uses. Thank you!

**Comment by drakkan** [comment]
Documentation is here:

https://github.com/drakkan/sftpgo/blob/master/docs/sftp-subsystem.md

please let me know how it works in your use case, thank you

**Comment by d4z3x** [comment]
> please let me know how it works in your use case, thank you

Absolutely. Going to try it now as a subsystem and get more details to you after I give a more thorough test.

**Comment by d4z3x** [comment]
Couple of observations:
- Can't restrict all users to a jailed directory (with either a simple config file option for a subsystem user)
- For above, maybe my search foo isn't very good in reading the docs
- $SFTPGO_USER_HOME_DIR is not set (from hook under common actions)
- common action for mkdir or other *dir commands don't exist, for use cases to chmod dirs, etc.

Any ideas if any of the above can be accomplished?

**Comment by drakkan** [comment]
Hi,

thank you for your feedbacks but I don't know your use case and I'm not sure to fully understand them, can you please clarify with some examples? Thank you

> Couple of observations:
> 
> * Can't restrict all users to a jailed directory (with either a simple config file option for a subsystem user)

if you login with the user `foo` with home dir `/home/fool` sshd starts the subsystem as this user and it can only see `/home/foo`, do you want to set the home to an arbitrary directory? Something like `/common/foo`? And for the user `bar` should have `/common/bar`?

> * For above, maybe my search foo isn't very good in reading the docs
> * $SFTPGO_USER_HOME_DIR is not set (from hook under common actions)

this is expected this env var is set for the hooks inside the `data_provider` section if you modify a user using the REST API

> * common action for mkdir or other *dir commands don't exist, for use cases to chmod dirs, etc.
> 

mkdir system command etc are executed using the system user that executes the subsystem. The subsystem is not executed using the root user.

> Any ideas if any of the above can be accomplished?

Maybe, if you let me know exactly what you mean with some usage examples, thank you!

**Comment by d4z3x** [comment]
> Hi,
> 
> thank you for your feedbacks but I don't know your use case and I'm not sure to fully understand them, can you please clarify with some examples? Thank you

No problem. I didn't mean to make this a tedious conversation. My apologies if I come across that way. Grateful for the new release and subsystem, still. 👍 
 
> > * Can't restrict all users to a jailed directory (with either a simple config file option for a subsystem user)
> 
> if you login with the user `foo` with home dir `/home/fool` sshd starts the subsystem as this user and it can only see `/home/foo`, do you want to set the home to an arbitrary directory? Something like `/common/foo`? And for the user `bar` should have `/common/bar`?

Use case is to chdir to an arbitrary directory for uploading shared content to. Another option (if I think about it), perhaps easier one if I can figure out how to configure virtual dirs inside their home dir would also be fine. Though, both options would be nice to have. 

> > * common action for mkdir or other *dir commands don't exist, for use cases to chmod dirs, etc.
> 
> mkdir system command etc are executed using the system user that executes the subsystem. The subsystem is not executed using the root user.

I understand that. A "dir" create event would allow one to change chmod values for any directories that are created with rwx or rws bits. Though I notice that dirs are created with group=rwx, so it's not much of a problem. Just a nice to have. 
 
> Maybe, if you let me know exactly what you mean with some usage examples, thank you!

Of course! In my use case, the jailed dir: /content/dir is owned by a base group that all users have access to and sub-dirs are restricted to based on their group membership (supplemental gids). For example:

jail directory: ```/content```
```owner```: ```-``` (but as group ownership (GID) is set to rw for files, and rws/rwx for dirs, owner UID doesn't affect access for other users writing to the same dir, this is why the perms are setup this way in the use case)
```group```: ```"content_base_group"``

jail sub-directory: ```/content/dir1```
```owner```: ```-``` (same as above)
```group```: ```content_group_dir1```

jail sub-directory: ```/content/dir2```
```owner```: ```-``` (same as above)
```group```: ```content_group_dir2```

```user_a``` is in groups: ```"content_base"```, and ```"content_group_dir1"```. Therefore, can access ```/content/dir1/*``` but not ```/content/dir2```. 

```user_b``` is in groups: ```"content_base"```, and ```"content_group_dir2"```. Therefore, can access ```/content/dir2/*``` but not ```/content/dir1```.

```user_c``` is in groups: ```"content_base"```, ```"content_group_dir1"``` and ```"content_group_dir2"```. Therefore, can access *both* ```/content/dir1/*``` *and* ```/content/dir2/*```.

I hope it's a bit clearer now. Again, I appreciate the work you put in, and if this is too much work, I understand.

Just final question, how would I use a memory provider? How does one configure it? I tried specifying "memory" and leaving the name to sqlite.db (e.g.), but that didn't work. So not sure what kind of data structure it is looking for. I looked at module for data provider but didn't get much of a clue.

**Comment by drakkan** [comment]
Hi,

I think most of the things you need are already possible by preloading users. A json dump is required to preload users within a memory provider. You can create this dump manually, but probably the easiest way is to create it from another SFTPGo instance, so:, so:

1) install SFTPGo on a test pc (for example your laptop or such)
2) run SFTPGo with the default settings, SQLite provider is fine here
3) use the web interface to create users and set permissions, virtual folders, home dir etc.
4) create a dump, you can use the [example REST API CLI](https://github.com/drakkan/sftpgo/tree/master/examples/rest-api-cli#backup-data) os simply something like this `curl "http://127.0.0.1:8080/api/v1/dumpdata?output_file=dump.json"`. The file `dump.json` will be created inside the configured `backups` directory. Use this file as input for the memory provider
5)  finally start the subsystem mode passing the flag `-p, --preserve-home` so the home directory will not be modified if the user is defined inside the dump

Regarding the directories access you don't need to use `chmod/chown` with SFTPGo: the user running the subsystem command must be able to read and write at file system level, you can define global vor per-directory virtual permissions. For example you can make a directory read only setting the `list` permission only. The directory will be read-only even if the user running the subsystem has write permissions for this directory.  To better understand how this work please do some tests using SFTPGo as standalone server.

After you pre-load the users if some feature is still missing please comment here or open separate issues.

All these things should be already documented but probably the documentation is a bit sparse. I would really appreciate if you can contribute an [how-to style guide](https://github.com/drakkan/sftpgo/tree/master/docs/howto) for the subsystem mode once you get all things working. Thank you

**Comment by drakkan** [comment]
Hi,

do you have any updates? Is it working now? Do you need other features? Thank you
