### ISSUE TITLE
Windows Installer package dose not support Server 2012

### ISSUE THREAD

**Issue by rkanoop** [drakkan/sftpgo#205]
The software MSI packages does not support windows 2012. Is there any chance to release for server platform

**Comment by drakkan** [comment]
Hi,

sftpgo itself should still work on windows7/2012 but I have no way to test it on these OS, the python rest api should not work.
 
You can try to build this setup yourself starting from the portable release and using the inno setup script [here](https://github.com/drakkan/sftpgo/blob/master/windows-installer/sftpgo.iss) you need to change the [MinVersion](https://github.com/drakkan/sftpgo/blob/master/windows-installer/sftpgo.iss#L36) and probaby adjust some paths

**Comment by drakkan** [comment]
Hi the release should work on windows 7 and above, the example REST API CLI will not be installed if Windows version is < 10, thank you

**Comment by drakkan** [comment]
You can also try a test setup [here](https://github.com/drakkan/test-github-actions/releases/download/v0.6.4/sftpgo_v0.6.4_windows_x86_64.exe). Ignore the setup version number it will install the current Git master. Please let me know if it works as expected on Windows 2012, thank you

**Comment by rkanoop** [comment]
SFTPGO.exe is missing in the package. I was able to run the installer. The Program folder doesn't have the "SFTPGO.exe"

**Comment by drakkan** [comment]
Hi,

it is strange, I just tested again the installer (on both windows 7 and windows 8) and it works for me, the only binary not installed is `sftpgo_api_cli.exe` as expected. So if you start the service control from the startup menu it does not work for you?

![Schermata del 2020-11-02 09-07-54](https://user-images.githubusercontent.com/553263/97844218-ee3f8f80-1cea-11eb-8c01-b31c6216e9c8.png)

**Comment by rkanoop** [comment]
Tested again. The exe is placed but a few errors. Refer below  

![image](https://user-images.githubusercontent.com/73527422/97850785-81dc8480-1d1a-11eb-93e1-c5808396bd92.png)

**Comment by drakkan** [comment]
Hi,

the installer should register sftpgo as service and it should automatically run. If you want to start manually you have to specify the config directory that should be `C:\ProgramData\SFTPGo`. Can you please check that your installation looks like the following screenshot?

![Schermata del 2020-11-02 11-02-58](https://user-images.githubusercontent.com/553263/97855468-120ad180-1cfb-11eb-804d-6b01a0b61e6a.png)

If so the service should be already running, you can change the configuration modifying `C:\ProgramData\SFTPGo\sftpgo.json` and restart the service executing (ad admin):

```
sftpgo service stop
sftpgo service start
```

the`Service Control` menu entry could help to control the service

![Schermata del 2020-11-02 11-06-03](https://user-images.githubusercontent.com/553263/97855752-82b1ee00-1cfb-11eb-936a-eb6433e8af7d.png)

thank you

**Comment by rkanoop** [comment]
Thanks, Nicola 

Successfully installed as service. Working as expected!  Brilliant team!

**Comment by drakkan** [comment]
Great! And don't forget to update to 1.2.0 when it will be released (likely the next weekend), this is a test build :)
