### ISSUE TITLE
Sub dirs permissions

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#206]
Hi, permessions for subdirectories are lost on save, no errors in the log files:

> {"level":"info","time":"2020-10-27T11:54:14.041","sender":"httpd","method":"POST","proto":"HTTP/2.0","remote_addr":"10.19.14.156:51656","request_id":"FQDN/RbXE1SQe9G-000047","uri":"FQDN:8443/web/user/1","user_agent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36","resp_status":303,"resp_size":0,"elapsed_ms":4}
> {"level":"info","time":"2020-10-27T11:54:14.061","sender":"httpd","method":"GET","proto":"HTTP/2.0","remote_addr":"10.19.14.156:51656","request_id":"FQDN/RbXE1SQe9G-000048","uri":"https://FQDN:8443/web/users","user_agent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36","resp_status":200,"resp_size":11982,"elapsed_ms":12}
>

**Comment by drakkan** [comment]
Hi,

how are you updating the user? Using the web admin seems to be ok

**Comment by fdefilippo** [comment]
Yes, if I add: /dir1:list,delete,downlaod then submit the form remains empty:

![chrome_CAQPjJdxzJ](https://user-images.githubusercontent.com/16714986/97293049-64a44380-184c-11eb-8d04-78f75a9620b2.png)

**Comment by drakkan** [comment]
ah ok, the right syntax is `/somedir::list,download` not a single `:`, please try this way, thank you

**Comment by fdefilippo** [comment]
ok

**Comment by drakkan** [comment]
This way you can do things like this `/some:dir::list,upload`
