### ISSUE TITLE
Define defaults using viper.SetDefault

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#208]
I noticed a slight issue around configuration. Namely: if the config file containing defaults is missing, environment variables are not recognized.

The root cause of this issue is this: https://github.com/spf13/viper/issues/761

Basically, `AutomaticEnv` doesn't work with `Unmarshal` when the keys that env vars are mapped to does not already exist in Viper via some other way. `AutomaticEnv` tries to look for those keys in environment variables when unmarshaling values on a struct.

I recommend using `SetDefault` to set default values (even empty ones), so that the config file does not have to contain all default/empty values for sftpgo to work.

**Comment by drakkan** [comment]
Hi, 

I am aware of this issue, see [here](https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md#environment-variables) basically you have to ship the default config file if you want to use env vars, as we do for example with the docker image.

I was hoping it would be fixed in viper .. :)

**Comment by sagikazarmark** [comment]
> I was hoping it would be fixed in viper .. :)

It's not likely to be fixed in the near future :\ Mostly because it's not trivial to fix and all the potential solutions have their own downsides.

As far as I can tell, you already set defaults. Not in Viper, but in the global struct directly. So instead of doing that, you could just set the defaults in Viper. :)

**Comment by drakkan** [comment]
> > I was hoping it would be fixed in viper .. :)
> 
> It's not likely to be fixed in the near future :\ Mostly because it's not trivial to fix and all the potential solutions have their own downsides.
> 
> As far as I can tell, you already set defaults. Not in Viper, but in the global struct directly. So instead of doing that, you could just set the defaults in Viper. :)

I would like to avoid to manually set the defaults in viper, it is error prone since I have to write both the key and the value manually, I'll eventually try one the wrapper suggested on the linked viper bug

**Comment by sagikazarmark** [comment]
Either way, tests should probably make sure of the correct behavior.
