### ISSUE TITLE
Allowed/Denied file extensions 

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#209]
Hi, why limit  to file extension when you could use a regex ? 

/somedir::test*,Other*

and so on.

thnx.

**Comment by drakkan** [comment]
We could use filepath [Match](https://golang.org/pkg/path/filepath/#Match). However we probably need a new regexp filter field both to maintain backward compatibility and to help users who are not very familiar with regular expressions.

**Comment by drakkan** [comment]
Please help me to test this feature :)  

You should limit using file extensions or file patters if you configure both all the filters must allow/deny the file. File extensions filter is now deprecated you should only use patterns. For patterns syntax please take a look [here](https://golang.org/pkg/path/#Match). Thank you!

**Comment by fdefilippo** [comment]
of course!
