### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#210]
I'm working on a helm chart for sftpgo (for now covering my needs, but I plan to generalize it)

Would you be interested in hosting it under your account or are you okay with hosting it under mine?

I'd host it under a helm-charts repo on GitHub using the official releaser tool: https://github.com/helm/chart-releaser

But if you want to setup one yourself, I can contribute it there. Let me know what you think.

**Comment by drakkan** [comment]
It's your choice, both options are ok for me. If you choose to host it in your repository, I will add a link somewhere in the docs,

thank you!!!

**Comment by sagikazarmark** [comment]
I'll probably host it in my repository then. Since I'll be actively using it, it'll be easier for me to modify it. I'll let you know once it's public.

**Comment by sagikazarmark** [comment]
An initial version is available here: https://artifacthub.io/packages/helm/sagikazarmark/sftpgo

The source is available here: https://github.com/sagikazarmark/helm-charts/tree/master/charts/sftpgo

**Comment by sagikazarmark** [comment]
FYI the debian image has a bunch of vulnerable packages as shown in the artifact hub link.

**Comment by drakkan** [comment]
> FYI the debian image has a bunch of vulnerable packages as shown in the artifact hub link.

Hi, I noticed these warning, the debian image is built using the debian `buster` tag. It is unlikely it has all these security issues. Generally debian doesn't change the version for a package to apply a security fix, for example if foo 1.2.3-1 has a security issue fixed in 1.2.4 they apply the relevant patch on top of 1.2.3 and the package will become 1.2.3-2, maybe this could confuse the checker.

However I'll try to better understand the issue, thank you

**Comment by sagikazarmark** [comment]
I would consider choosing a distroless image if you prefer having debian image: https://github.com/GoogleContainerTools/distroless

**Comment by drakkan** [comment]
> I would consider choosing a distroless image if you prefer having debian image: https://github.com/GoogleContainerTools/distroless

I don't think that switching to this container will solve the security issues. If you open the report you can see that gcc `8.3.0-6` is considered vulnerable but this is exactly the same version I read [here](https://github.com/GoogleContainerTools/distroless/blob/master/package_bundle_amd64_debian10.versions#L20). For libc-bin `2.28-10` is the same, so probably is the security tool used to generate the report that need to be fixed
