### ISSUE TITLE
Host keys configuration is confusing

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#211]
When trying to run sftpgo from a Docker image, mounting host keys to `/etc/sftpgo` and setting hostkeys to `["id_rsa"]`, it complains about a missing file:

```
could not start SFTP server: open id_rsa: no such file or directory
```

I suspect it's because the config directory is not actually set to the directory `sftpgo.json` is found in (which is `/etc/sftpgo in case of the docker image).

The documentation however says "configuration directory" which seems to be the directory from where sftpgo is running from. It's not the end of the world, but might make sense to explain it better in the docs. (Alternatively: I think you can get the actual directory from Viper)

BTW I found it here: https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md

**Comment by drakkan** [comment]
Hi,

from `sftpgo serve -h`

```
  -c, --config-dir string      Location for SFTPGo config dir. This directory
                               should contain the "sftpgo" configuration file
                               or the configured config-file and it is used as
                               the base for files with a relative path (eg. the
                               private keys for the SFTP server, the SQLite
                               database if you use SQLite as data provider).
                               This flag can be set using SFTPGO_CONFIG_DIR
                               env var too. (default ".")
```

the working directory for the Docker image is `/var/lib/sftpgo` so `id_rsa` is searched inside `/var/lib/sftpgo`.

The config dir is managed using [viper](https://github.com/drakkan/sftpgo/blob/master/cmd/root.go#L95). And it has [these fallbacks](https://github.com/drakkan/sftpgo/blob/master/config/config_linux.go#L8)

**Comment by sagikazarmark** [comment]
Yeah, I figured that out, but it wasn't immediately obvious.

**Comment by sagikazarmark** [comment]
Thanks.
