### ISSUE TITLE
Add a healthz endpoint and exclude it from logs and metrics

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#212]
Kubernetes (and many other orchestrators) require a health endpoint that it can use to check if the application is still running and responding to requests.

Kubernetes usually hits these endpoints every few seconds, so it generates a large traffic that can clutter logs and metrics. 

The closes thing I found is a version endpoint that does nothing, but returns a successful response: `/api/v1/version`

I'd be happy to provide a PR, but wanted to raise an issue first.

**Comment by drakkan** [comment]
Hi,

we could add something like this:

```
router.Get("/healthz", func(w http.ResponseWriter, r *http.Request) {
		render.PlainText(w, r, "OK\r\n")
})
```

to disable logging and metrics we have to exclude the [logger middleware](https://github.com/drakkan/sftpgo/blob/master/httpd/router.go#L27) a PR is welcome, thank you!
