### ISSUE TITLE
Account Permissions and sub-dirs

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#217]
I have a strange issue with an account:

My user defitinion is as follows:

```
      {
        "id": 1,
        "status": 1,
        "username": "test",
        "password": "***",
        "home_dir": "/sftp",
        "uid": 1100,
        "gid": 1100,
        "permissions": {
          "/": [
            "list"
          ],
          "/sftp/test/upload: [
            "list",
            "upload",
            "download",
            "rename",
            "create_dirs",
            "delete"
          ]
        }
      },
```

Although I can list in all directories in /sftp, I wanted to be able to upload to /sftp/test/upload with the above definition. Am i doing something incorrect here?

Using edge

**Comment by drakkan** [comment]
Hi,

if `/sftp/test/upload` the sftp path or the filesystem path? You have to specify the sftp path

**Comment by ryjogo** [comment]
Ah, /sftp/test/upload is the filesystem path. 

I have tried with the relative path, and I still get permission denied.. 
i.e.
`
"permissions": {
          "/": [
            "list"
          ],
          "/test/upload: [
            "list",
            "upload",
            "download",
            "rename",
            "create_dirs",
            "delete"
          ]
        }
`

for /sftp/test/upload

**Comment by drakkan** [comment]
Hi,

the permission denied error from your logs seems a file system level error. SFTPGo runs as uid 1000, can this user creates files on the target path? thank you

**Comment by ryjogo** [comment]
Ah yes, well i guess not as these are uid 1100/ gid 1100 - so perhaps i need to run sftpgo as 1100?

**Comment by drakkan** [comment]
> Ah yes, well i guess not as these are uid 1100/ gid 1100 - so perhaps i need to run sftpgo as 1100?

This is currently not possible without rebuilding the docker image, to support changing uid/gid we should add an entrypoint,

I started a patch some time ago but I never completed it

```
 Dockerfile.alpine                   | 16 ++++------------
 docker/scripts/entrypoint-alpine.sh | 17 +++++++++++++++++
 2 files changed, 21 insertions(+), 12 deletions(-)
 create mode 100755 docker/scripts/entrypoint-alpine.sh

diff --git a/Dockerfile.alpine b/Dockerfile.alpine
index 8e67ae4..0b2cf01 100644
--- a/Dockerfile.alpine
+++ b/Dockerfile.alpine
@@ -28,9 +28,7 @@ RUN set -xe && \
 
 FROM alpine:3.12
 
-RUN apk add --update --no-cache ca-certificates tzdata bash mailcap
-
-SHELL ["/bin/bash", "-c"]
+RUN apk add --update --no-cache ca-certificates tzdata bash mailcap su-exec
 
 # set up nsswitch.conf for Go's "netgo" implementation
 # https://github.com/gliderlabs/docker-alpine/issues/367#issuecomment-424546457
@@ -38,9 +36,6 @@ RUN test ! -e /etc/nsswitch.conf && echo 'hosts: files dns' > /etc/nsswitch.conf
 
 RUN mkdir -p /etc/sftpgo /var/lib/sftpgo /usr/share/sftpgo /srv/sftpgo
 
-RUN addgroup -g 1000 -S sftpgo && \
-    adduser -u 1000 -h /var/lib/sftpgo -s /sbin/nologin -G sftpgo -S -D -H sftpgo
-
 # Install some optional packages used by SFTPGo features
 RUN apk add --update --no-cache rsync git
 
@@ -60,13 +55,10 @@ RUN sed -i "s|\"users_base_dir\": \"\",|\"users_base_dir\": \"/srv/sftpgo/data\"
     sed -i "s|\"backups\"|\"/srv/sftpgo/backups\"|" /etc/sftpgo/sftpgo.json && \
     sed -i "s|\"bind_address\": \"127.0.0.1\",|\"bind_address\": \"\",|" /etc/sftpgo/sftpgo.json
 
-RUN chown -R sftpgo:sftpgo /etc/sftpgo && chown sftpgo:sftpgo /var/lib/sftpgo /srv/sftpgo && \
-    chmod 640 /etc/sftpgo/sftpgo.json && \
-    chmod 750 /etc/sftpgo /var/lib/sftpgo /srv/sftpgo
-
 WORKDIR /var/lib/sftpgo
-USER 1000:1000
 
 VOLUME [ "/var/lib/sftpgo", "/srv/sftpgo" ]
 
-CMD sftpgo serve
+COPY ./docker/scripts/entrypoint-alpine.sh /docker-entrypoint.sh
+ENTRYPOINT ["/docker-entrypoint.sh"]
+CMD ["sftpgo", "serve"]
diff --git a/docker/scripts/entrypoint-alpine.sh b/docker/scripts/entrypoint-alpine.sh
new file mode 100755
index 0000000..04822c7
--- /dev/null
+++ b/docker/scripts/entrypoint-alpine.sh
@@ -0,0 +1,17 @@
+#!/usr/bin/env bash
+set -e
+
+SFTPGO_UID=${SFTPGO_UID:-1000}
+SFTPGO_GID=${SFTPGO_GID:-1000}
+
+if [ "$1" = 'sftpgo' ]; then
+    addgroup -g ${SFTPGO_GID} -S sftpgo
+    adduser -u ${SFTPGO_UID} -h /var/lib/sftpgo -s /sbin/nologin -G sftpgo -S -D -H sftpgo
+    chown -R ${SFTPGO_UID}:${SFTPGO_GID} /etc/sftpgo
+    chown ${SFTPGO_UID}:${SFTPGO_GID} /var/lib/sftpgo /srv/sftpgo
+    chmod 640 /etc/sftpgo/sftpgo.json
+    chmod 750 /etc/sftpgo /var/lib/sftpgo /srv/sftpgo
+    exec su-exec ${SFTPGO_UID}:${SFTPGO_GID} "$@"
+fi
+
+exec "$@"
\ No newline at end of file
-- 
2.29.0
```

I think it should work for the  alpine image, it should be improved to support debian too. For debian we have to replace `su-exec` with [gosu](https://github.com/tianon/gosu). Do you want to help with this patch? Thank you

**Comment by ryjogo** [comment]
Oh that's great news. Yes if you have time that would be great. 

Is the Dockerfile for the edge build on the repo still valid? then i can build a new image

**Comment by drakkan** [comment]
The dockerfiles used for the official image are these ones:

- [Debian](https://github.com/drakkan/sftpgo/blob/master/Dockerfile)
- [Alpine](https://github.com/drakkan/sftpgo/blob/master/Dockerfile.alpine)

you could probably just extented the official image instead of building a new one.  Maybe @sagikazarmark could help here

**Comment by ryjogo** [comment]
Good. idea, if i use the sftpgo alpine image as the base image, then add that patch somehow..

**Comment by drakkan** [comment]
You could also just execute:

```
chown -R 1000:1000 <path to sftogo datadir>
```

**Comment by sagikazarmark** [comment]
I agree, building a custom image from the official one is the easiest thing you can do, although I would assume that you want to mount a directory to that path in which case you have to change the permissions of the directory on the host.

**Comment by drakkan** [comment]
> Good. idea, if i use the sftpgo alpine image as the base image, then add that patch somehow..

I mean something like:

```
FROM drakkan/sftpgo:<tag>
```

and then change just uid/gid (untested I don't know if it works)

**Comment by ryjogo** [comment]
```
FROM drakkan/sftpgo:edge-alpine
RUN chown -R 1100:1100 /var/lib/sftpgo 
```

returns: 

```
 ---> Running in c05561a73703
chown: /var/lib/sftpgo: Operation not permitted
chown: /var/lib/sftpgo: Operation not permitted
```

**Comment by drakkan** [comment]
> ```
> FROM drakkan/sftpgo:edge-alpine
> RUN chown -R 1100:1100 /var/lib/sftpgo 
> ```
> 
> returns:
> 
> ```
>  ---> Running in c05561a73703
> chown: /var/lib/sftpgo: Operation not permitted
> chown: /var/lib/sftpgo: Operation not permitted
> ```

Sorry for the confusion.

I mean `chown 1000:1000 <path to sftpgo data>` on your host system not inside the image. This way you can run the image you already have

**Comment by sagikazarmark** [comment]
Chances are the user at this point is already `1000`: https://github.com/drakkan/sftpgo/blob/36151d1ba9387e8d296cea879b783406c65d3724/Dockerfile.alpine#L68

You probably need to 

```
FROM drakkan/sftpgo:edge-alpine

USER root

RUN chown -R 1100:1100 /var/lib/sftpgo

USER 1100:1100
```

**Comment by drakkan** [comment]
> Chances are the user at this point is already `1000`:
> 
> https://github.com/drakkan/sftpgo/blob/36151d1ba9387e8d296cea879b783406c65d3724/Dockerfile.alpine#L68
> 
> You probably need to
> 
> ```
> FROM drakkan/sftpgo:edge-alpine
> 
> USER root
> 
> RUN chown -R 1100:1100 /var/lib/sftpgo
> 

probably this one is better

RUN chown -R 1100:1100 /var/lib/sftpgo /etc/sftpgo /srv/sftpgo

> USER 1100:1100
> ```

**Comment by ryjogo** [comment]
Ok, the image was build ok, and now on the container startup i get:

```
ERROR 2020/11/05 14:39:56 Couldn't discover absolute path
ERROR 2020/11/05 14:39:56 stat .: permission denied
ERROR 2020/11/05 14:39:56 Couldn't discover absolute path
ERROR 2020/11/05 14:39:56 stat .: permission denied

{"level":"error","time":"2020-11-05T14:39:56.393","sender":"service","message":"error initializing data provider: stat credentials: permission denied"}

```
 with:

```
FROM drakkan/sftpgo:edge-alpine

USER root

RUN chown -R 1100:1100 /var/lib/sftpgo /etc/sftpgo /srv/sftpgo

USER 1100:1100
```

**Comment by drakkan** [comment]
can you please post the `ls -la` ouput for the directory mounted on `/var/lib/sftpgo`? It should have uid:gid 1100 now

**Comment by ryjogo** [comment]
Ah, well i couldn't even do that:

```
bash-5.0$ whoami
whoami: unknown uid 1100
```

I guess i need to:

```
RUN addgroup -g 1100 -S sftpgo && \
    adduser -u 1100 -h /var/lib/sftpgo -s /sbin/nologin -G sftpgo -S -D -H sftpgo
```

**Comment by drakkan** [comment]
I mean outside the container not inside it

**Comment by ryjogo** [comment]
Ah ok, but I am not mounting /var/lib/sftpgo at all..

**Comment by ryjogo** [comment]
However it does seem that the directory uid and gid has not been set in the new image. 

```
bash-5.0$ stat /var/lib/sftpgo
  File: /var/lib/sftpgo
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 13390894    Links: 2
Access: (0750/drwxr-x---)  Uid: ( 1000/ UNKNOWN)   Gid: ( 1000/ UNKNOWN)
```

**Comment by drakkan** [comment]
> However it does seem that the directory uid and gid has not been set in the new image.
> 
> ```
> bash-5.0$ stat /var/lib/sftpgo
>   File: /var/lib/sftpgo
>   Size: 4096            Blocks: 8          IO Block: 4096   directory
> Device: fd00h/64768d    Inode: 13390894    Links: 2
> Access: (0750/drwxr-x---)  Uid: ( 1000/ UNKNOWN)   Gid: ( 1000/ UNKNOWN)
> ```

I should test this case myself, but I have no time now, sorry

**Comment by drakkan** [comment]
Hi, 

it works for me.

Take a look here, this is my folders structure:

```
pwd
/root/test

ls -la
drwxr-xr-x  4 root root   50  6 nov 08.14 .
dr-xr-x---. 7 root root 4096  6 nov 08.10 ..
drwxr-xr-x  3 1100 1100  150  6 nov 08.18 config
drwxr-xr-x  3 1100 1100   18  6 nov 08.18 data
-rw-r--r--  1 root root  123  6 nov 08.12 Dockerfile
```

here is the Dockerfile content:

```
FROM drakkan/sftpgo:edge-alpine

USER root

RUN chown -R 1100:1100 /var/lib/sftpgo /etc/sftpgo /srv/sftpgo

USER 1100:1100
```

Now from the /root/test directory build the Docker image

```
docker build -t sftpgo1100 .
```

and run it

```
docker run --name some-sftpgo1100 -p 8080:8080 -p 2022:2022 --mount type=bind,source=/root/test/data,target=/srv/sftpgo --mount type=bind,source=/root/test/config,target=/var/lib/sftpgo -d sftpgo110
```

Another solution, without modifying the docker image, is to change the owner for you data directory on the host, not inside docker image, for example:

```
chown -R 1000:1000 <path to the dir you want to mount as sftpgo data dir>
```

**Comment by drakkan** [comment]
I added support for running as arbitrary user, please try the latest edge tags.

Documentation is [here](https://github.com/drakkan/sftpgo/tree/master/docker#running-as-an-arbitrary-user)

**Comment by ryjogo** [comment]
Oh thats great, im still having issues here though. Whilst i am running docker, i am deploying in kubernetes. 

`{"level":"error","time":"2020-11-06T11:26:15.165","sender":"service","message":"error initializing data provider: mkdir credentials: permission denied"}
`

```
       - name: sftp
          image: drakkan/sftpgo:edge-alpine
          imagePullPolicy: Always 
          ports:
            - containerPort: 22   
          securityContext:
            runAsUser: 1100 #user root
            runAsGroup: 1100 #group users
          env:
            - name: SFTPGO_SFTPD__BIND_PORT
              value: "2022"
            - name: SFTPGO_SFTPD__BIND_ADDRESS
              value: "0.0.0.0"
            - name: SFTPGO_HTTPD__BIND_PORT
              value: "8080"
            - name: SFTPGO_HTTPD__BIND_ADDRESS
              value: "0.0.0.0" 
            - name: SFTPGO_LOG_VERBOSE 
              value: "true"
          volumeMounts:        
            - name: datadir
              mountPath: /sftp/

```

**Comment by ryjogo** [comment]
same in docker too..

i ran the build as you have suggested, docker build -t sftpgo1100 .

```


$ docker run --name some-sftpgo1100 -p 8080:8080 -p 2022:2022 sftpgo1100

{"level":"info","time":"2020-11-06T11:41:46.233","sender":"service","message":"starting SFTPGo 1.1.1-dev-36151d1b-2020-11-05T11:19:00Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, profile: false load data from: \"\""}
ERROR 2020/11/06 11:41:46 Couldn't discover absolute path
ERROR 2020/11/06 11:41:46 stat .: permission denied
ERROR 2020/11/06 11:41:46 Couldn't discover absolute path
ERROR 2020/11/06 11:41:46 stat .: permission denied
{"level":"debug","time":"2020-11-06T11:41:46.236","sender":"config","message":"config file used: '\"/etc/sftpgo/sftpgo.json\"', config loaded: {Common:{IdleTimeout:15 UploadMode:0 Actions:{ExecuteOn:[] Hook:} SetstatMode:0 ProxyProtocol:0 ProxyAllowed:[] PostConnectHook: idleTimeoutAsDuration:0 idleLoginTimeout:0} SFTPD:{Banner:SFTPGo_1.1.1-dev BindPort:2022 BindAddress: IdleTimeout:0 MaxAuthTries:0 UploadMode:0 Actions:{ExecuteOn:[] Hook:} Keys:[] HostKeys:[] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveHook: PasswordAuthentication:true ProxyProtocol:0 ProxyAllowed:[] certChecker:<nil> parsedUserCAKeys:[]} FTPD:{BindPort:0 BindAddress: ForcePassiveIP: Banner:SFTPGo 1.1.1-dev ready BannerFile: CertificateFile: CertificateKeyFile: ActiveTransfersPortNon20:false PassivePortRange:{Start:50000 End:50100} TLSMode:0} WebDAVD:{BindPort:0 BindAddress: CertificateFile: CertificateKeyFile: Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0} Cache:{Users:{ExpirationTime:0 MaxSize:50} MimeTypes:{Enabled:true MaxSize:1000}}} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:5432 Username: Password:[redacted] SSLMode:0 ConnectionString: SQLTablesPrefix: ManageUsers:1 TrackQuota:2 PoolSize:0 UsersBaseDir:/srv/sftpgo/data Actions:{ExecuteOn:[] Hook:} ExternalAuthHook: ExternalAuthScope:0 CredentialsPath:credentials PreLoginHook: PostLoginHook: PostLoginScope:0 CheckPasswordHook: CheckPasswordScope:0 UpdateMode:0 PasswordHashing:{Argon2Options:{Memory:65536 Iterations:1 Parallelism:2}} PreferDatabaseCredentials:false} HTTPDConfig:{BindPort:8080 BindAddress: TemplatesPath:/usr/share/sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static BackupsPath:/srv/sftpgo/backups AuthUserFile: CertificateFile: CertificateKeyFile:} HTTPConfig:{Timeout:20 CACertificates:[] SkipTLSVerify:false customTransport:<nil>}}"}
{"level":"error","time":"2020-11-06T11:41:46.236","sender":"service","message":"error initializing data provider: stat credentials: permission denied"}
```

**Comment by ryjogo** [comment]
It seems this works when i mount directories to /var/lib/sftpgo and /srv/sftpgo

`docker run --name sftpgo1100 -p 8080:8080 -p 2022:2022 --mount type=bind,source=${PWD}/data,target=/srv/sftpgo --mount type=bind,source=${PWD}/config,target=/var/lib/sftpgo sftpgo1100`

but the problem is, i don't really need to mount these dirs. config dir is non-persistent for this use case - when i start the container up, provision users i should be good to go. 

It seems that /var/lib/sftpgo cannot be chmod 1100 as its built in the image as a mount point?

**Comment by sagikazarmark** [comment]
> It seems that /var/lib/sftpgo cannot be chmod 1100 as its built in the image as a mount point?

Volumes are usually mounted as root, do the owner will be root as well.

There are three common solutions:

- Change the owner in an init container
- Change the default mode of the volume (to something like 777) (not really recommended)
- Set an fsgroup in the security context of the container

**Comment by drakkan** [comment]
@ryjogo sorry I'm unable to fully understand your use case. Do you want to mount `/srv/sftpgo` volume only or no volume at all? How do you plan to persist the host key? 
However all the paths should be configurable via env vars and if you want to mount only one volume this should be possibile. Please let me better understand your use case and I'll try to give some suggestions, thank you

**Comment by ryjogo** [comment]
> * Change the owner in an init container
> * Change the default mode of the volume (to something like 777) (not really recommended)
> * Set an fsgroup in the security context of the container

Yeah ok, so this is a sidecar to a pod, fsgroup would have to be on the other container too i guess. Default mode of the vol could work, and the init container may be a good idea too. .

i think right now i will mount the directories with an emptyDir drive, and this seems to solve the issue at hand here.

**Comment by ryjogo** [comment]
> @ryjogo sorry I'm unable to fully understand your use case. Do you want to mount `/srv/sftpgo` volume only or no volume at all? How do you plan to persist the host keys? Do you have only cloud based users (S3,GCS,Azure) and not local users?
> 
I mount host keys from secrets directly into the config dir



> However all the paths should be configurable via env vars and if you want to mount only one volume this should be possibile using an appropriate configuration.
That might be the solution here actually.. 

> 
> If you don't need to mount any volume the default image should be fine.
> 
> Please let me better understand your use case and I'll try to give some suggestions, thank you

So without mounting anything, it seems i cannot change the permissions on the dir in the image.. i.e. if you run the chmod -R 1100:1100 on the standard image, then without binding any volumes, i.e. just `docker run -it image bash` the /var/lib/sftp is still 1000

**Comment by drakkan** [comment]
> > @ryjogo sorry I'm unable to fully understand your use case. Do you want to mount `/srv/sftpgo` volume only or no volume at all? How do you plan to persist the host keys? Do you have only cloud based users (S3,GCS,Azure) and not local users?
> 
> I mount host keys from secrets directly into the config dir
> 
> > However all the paths should be configurable via env vars and if you want to mount only one volume this should be possibile using an appropriate configuration.
> > That might be the solution here actually..
> 
> > If you don't need to mount any volume the default image should be fine.
> > Please let me better understand your use case and I'll try to give some suggestions, thank you
> 
> So without mounting anything, it seems i cannot change the permissions on the dir in the image.. i.e. if you run the chmod -R 1100:1100 /var/lib/sftpgo on the standard image, then without binding any volumes, run that image i.e. just `docker run -it image bash` the /var/lib/sftp is still 1000:1000
> 

I don't know docker very well and so this could be a trivial question:

- the default image will run as the `sftpgo` user defined inside the image itself. It has 1000 as UID/GID. 
- the `sftpgo` user own both `/etc/sftpgo` and `/var/lib/sftpgo`. If you don't mount anything this user should be able to write to these paths

what am I missing here? Why do you want to run the image as another user if you don't mount any volume?

> either way, for this particular use case this is fixed with the new apline-edge image! so thanks very much for this. however it could be really nice with a env var PUID and GUID to set during startup that facilities this

This could be done using an entrypoint, but I would like to avoid it if not strictly required

**Comment by drakkan** [comment]
Please try the latest edge image, you can use the env vars `SFTPGO_PUID` and `SFTPGO_PGID`, thank you

**Comment by ryjogo** [comment]
Just reporting back, the change works! thanks so much for this

**Comment by drakkan** [comment]
Thank you for reporting back. It should not break @sagikazarmark use case too

**Comment by ryjogo** [comment]
Actually, is this intentional?

```
            - name: SFTPGO_PUID 
              value: "1100"
            - name: SFTPGO_GUID
              value: "1100"
```

```
2020-11-11T18:53:15 - entrypoint, change owner for /etc/sftpgo uid: 1100 gid: 1000
2020-11-11T18:53:15 - entrypoint, change owner for /var/lib/sftpgo uid: 1100 gid: 1000
2020-11-11T18:53:15 - entrypoint, change owner for /srv/sftpgo uid: 1100 gid: 1000
2020-11-11T18:53:15 - entrypoint, run as uid: 1100 gid: 1000
```
Looks like GUID is still 1000?

**Comment by ryjogo** [comment]
Think i see it.

`SFTPGO_PGID=${SFTPGO_PGID:-1000} 
`
Should be GUID not PGID?

**Comment by drakkan** [comment]
Yes, `SFTPGO_PUID` and `SFTPGO_PGID`

**Comment by sagikazarmark** [comment]
Meh, I'm not a huge fan of this, but I can work around it.

> `        echo `date +%Y-%m-%dT%H:%M:%S` - "entrypoint, run as uid: ${SFTPGO_PUID} gid: ${SFTPGO_PGID}"`

If these logs are not absolutely necessary then I'd get rid of them: they will show up in the log and log parsers will potentially be confused, because they await json log.

**Comment by drakkan** [comment]
> Meh, I'm not a huge fan of this, but I can work around it.
> 

this should not affect Kubernetes security policies,can you please confirm?

> > `       echo`date +%Y-%m-%dT%H:%M:%S` - "entrypoint, run as uid: ${SFTPGO_PUID} gid: ${SFTPGO_PGID}"`
> 
> If these logs are not absolutely necessary then I'd get rid of them: they will show up in the log and log parsers will potentially be confused, because they await json log.

yes, I plan to convert to json in future commits, they are useful to debug the used uid/gid

**Comment by sagikazarmark** [comment]
> this should not affect Kubernetes security policies,can you please confirm?

Actually, it does, because the default user is back to root which is not a good practice.

I can work that around by setting a security context manually (I think) and override the entrypoint of the container.

Bind mounts are really frustrating in Docker and entrypoints and gosu are workarounds. Sadly, if you want to use a proper image, you need to manually set permissions.

I'd recommend building a different set of images for "local" usage or just attach a snippet in the docs how people can make images for themselves for local usage.

**Comment by drakkan** [comment]
uhmm ... to make something like this work

```
FROM drakkan/sftpgo:edge-alpine
USER root
RUN chown -R 1100:1100 /var/lib/sftpgo /etc/sftpgo /srv/sftpgo
USER 1100:1100
```

I have to remove the `VOLUME` definition from the base image. 

I'll think a bit more about this the next weekend but probably I have to revert the entrypoint change, sorry. If you search on Docker Hub all the major images use the `--user` flag to change user.

**Comment by sagikazarmark** [comment]
> If you search on Docker Hub all the major images use the --user flag to change user.

Yep. If you need to set permissions, you can do it from an init container (in Kubernetes) or another container (in docker compose)

**Comment by drakkan** [comment]
I removed the entrypoint, you can use `--user` as before or you can build your own image using the official one as a base, here is a sample Dockerfile:

```
FROM drakkan/sftpgo:edge
USER root
RUN chown -R 1100:1100 /etc/sftpgo && chown 1100:1100 /var/lib/sftpgo /srv/sftpgo
USER 1100:1100
```

this should now works with the latest edge variant, thank you

**Comment by r0bb10** [comment]
@drakkan is the --user still working? i cannot get to pass custom id to the sftpgo user in the container.. using docker-compose or docker cli does not change.

```
version: "3"
services:
  sftpgo:
    image: "drakkan/sftpgo:alpine-slim"
    container_name: sftpgo
    user: 1026:100
    restart: always
    ports:
      - 8080:8080
      - 2121:2121
      - 5007:5007
    environment:
      SFTPGO_FTPD__BINDINGS__0__PORT: 2121
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 5007
    volumes:
      - /cloud:/srv/sftpgo
      - /data:/data
      - `.:/var/lib/sftpgo
```

should be correct, but inspecting the container the id of sftpgo is still 1000:1000

```
~$ sudo docker exec -it sftpgo sh
/var/lib/sftpgo $ id sftpgo
uid=1000(sftpgo) gid=1000(sftpgo) groups=1000(sftpgo),1000(sftpgo)
```
