### ISSUE TITLE
AzureBlob Container Root Dir Listing

### ISSUE THREAD

**Issue by YiFeng-Chen** [drakkan/sftpgo#218]
Hi drakkan,

When I use container level SAS token to connect to my AzureBlob, I can't go back to the root directory of the container. As I traced the code of the implementation of AzureBlobFS, I found that when path name is "" or "." , the GetProperties() method will be called to get the properties of the container, but only account level SAS has the permission to access the container property, so this call will return a 403 error.

**Comment by drakkan** [comment]
Hi,

thank you for reporting this issue, can you please check if it is fixed in the last commit?

**Comment by YiFeng-Chen** [comment]
Yes, this issue is fixed, a judgement sentence of whether the svc is existed before calling checkIfBucketExists was added.
Thank you.

**Comment by drakkan** [comment]
Thank you for confirming.
