### ISSUE TITLE
Handle multiple object storage buckets and association on a per-user basis

### ISSUE THREAD

**Issue by Solvik** [drakkan/sftpgo#220]
Hi !

I'm seeking to replace [AWS SFTP Server](https://aws.amazon.com/fr/aws-transfer-family/) with sftpgo to complete my production usage of sftpgo

The main feature is the ability to use the SFTP Server as proxy to multiple buckets.

From what I can see, we can only setup one bucket for the whole `sftpgo` server. Would it be possible to configure multiple objects storage (S3, Azure Blob Storage with the latest release) and configure an user to use either one of them ?

Depending on how you want to that on an architecture point of view, I'd be happy to contribute.

Here's a screenshot for configuration of AWS SFTP Server. Each home directory is a different S3 bucket
![sftpgo](https://user-images.githubusercontent.com/201761/98531689-fe261900-2280-11eb-8467-fcee509b07fd.png)

Thanks!

**Comment by drakkan** [comment]
Hi Solvik,

I'm not sure to fully understand your feature request.

In SFTPGo you can associate a different bucket for each user, for example using the web admin for each user you can configure a different bucket, credentials and so on

![Schermata del 2020-11-09 12-18-50](https://user-images.githubusercontent.com/553263/98535068-c8cffa00-2285-11eb-88ec-c979dfbc6939.png)

so you can have:

- `user1` mapped to S3 bucket `x`
- `user2` mapped to S3 bucket `y`
- `user3` mapped to Azure bucket `z`

and so on, credentials cannot be used from the environment for this to work, so credentials must be set explicitly for each user.

A such setup works fine locally, are you asking for something different? Thank you

**Comment by Solvik** [comment]
Woh :) I feel completely dumb :)

I didn't see that part in the UI and understood that S3 was configured through the json configuration making SFTPGo bound to only one bucket

I should have looked further. I'll submit a PR to add some examples to the documentation and make things easier for the next blinded guy like me :) sorry for the fuss

**Comment by drakkan** [comment]
> Woh :) I feel completely dumb :)
> 
> I didn't see that part in the UI and understood that S3 was configured through the json configuration making SFTPGo bound to only one bucket
> 

No problem :)

> I should have looked further. I'll submit a PR to add some examples to the documentation and make things easier for the next blinded guy like me :) sorry for the fuss

That would be great, many users seem confused, so docs definitely need to be improved. Thank you!

You can also share the same bucket among multiple users by setting a different prefix for each user. You can also combine local and cloud users (using any supported cloud backend).
