### ISSUE TITLE
Fantastic project! A few questions.

### ISSUE THREAD

**Issue by ScubaDrew** [drakkan/sftpgo#221]
Hi, thanks for this amazing project. Working on having my company sponsor. 

1. I was looking around for any documentation related to security - has any testing been done against it? 
2. Production - is anyone running this in production - list of people/companies? That could lend credibility to the project and help adoption

Thanks,
Drew

**Comment by drakkan** [comment]
> Hi, thanks for this amazing project. Working on having my company sponsor.
> 
> 1. I was looking around for any documentation related to security - has any testing been done against it?
> 2. Production - is anyone running this in production - list of people/companies? That could lend credibility to the project and help adoption
> 
> Thanks,
> Drew

Hi,

thank you for evaluating SFTPGo.

Concerning security SFTPGo uses [crypto/ssh](https://github.com/golang/crypto) as the basis for the SSH/SFTP protocol. This library is maintained by Google and I think security audits are done regularly against it.

If you configure SFTPGo appropriately you can easily get A+ in the standard audit test [here](https://www.sshaudit.com/). The policy audit seems specific to OpenSSH.

If you read the issues/pull requests, you can see that many people/companies seem to be using SFTPGo in production. 

I don't know if this is relevant here or not: I published an official Docker image on Docker Hub on October 17, 2020, it has more than 400.000 pulls.

The main advantage here is that this is open source software, if I do something wrong other people can look at the code and open issues or fix it. This cannot happen using obscure proprietary software.
 
In any case I don't want to sell you anything, please try SFTPGo and use it if it meets your requirements. 

If you decide to use it at you company a sponsorship will help to keep the project healthy and well maintained and it is really appreciated,

thank you

**Comment by ScubaDrew** [comment]
Thanks @drakkan ! This is all helpful. I don't feel like you are selling anything at all. 

Great news on the audit test and docker pulls.
