### ISSUE TITLE
AzureBlob's Chtimes method should return nil

### ISSUE THREAD

**Issue by YiFeng-Chen** [drakkan/sftpgo#223]

**Comment by drakkan** [comment]
Hi,

if you want to silently ignore chmod/chown/chtimes for cloud based fs please set `setstat_mode` to `1` or `2` in your configuration file. 

These methods are unsupported for cloud backends and with the default settings I think that we must return an "Operation Unsupported" error,

thank you

**Comment by YiFeng-Chen** [comment]
Great, I agree with your idea , this response is friendly way to tell the client that  the operation is not supported.
