### ISSUE TITLE
sshfs as storage 

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#224]
hi, do you think it would make sense to have an ssh connection as storage (a bit like sshfs), so in summary a sort of sftp proxy? what do you think about it?

https://github.com/nxsre/sshfs-go

thnx.

**Comment by drakkan** [comment]
Hi,

yes it makes sense and it is planned but I don't have a definite schedule, just started experimenting with it yesterday :)

I think I need to patch pkg/sftp client implementation to add WriteAt/ReadAt methods first.

**Comment by fdefilippo** [comment]
Hi, no, I don't want to use sshfs, it was just an idea to show the functionality I'd like to see in sftpgo.
