### ISSUE TITLE
Add KMS support

### ISSUE THREAD

**Issue by drakkan** [drakkan/sftpgo#226]
Hi,

currently SFTPGo stores confidential data such as S3, Azure and GCS keys in encrypted form using the [Secret struct](https://github.com/drakkan/sftpgo/blob/master/vfs/secret.go#L35).

I think this could be improved by adding KMS support. I don't want KMS related code directly inside SFTPGo, I prefer to support KMS using something like [KES](https://github.com/minio/kes). This way SFTPGo can support different KMS systems using a single API and without including KMS related code.

The KMS master cryptographic key must be pre-created and configured in `sftpgo.json`.
With KMS support enabled if you provide, for example, a plain S3 access key, it will be encrypted using the KMS and stored inside SFTPGo as encrypted. The key will be decrypted using the KMS when SFTPGo needs it as plain text (when a user tries to log in).

Hence, using a KMS, SFTPGo only stores confidential data as encrypted (like now) but the difference is that it is unable to decrypt these ciphertext on its own.

I also plan to add a crypto backend (for local fs) and KMS could be used there as well.

Some users such as @sagikazarmark, @jovandeginste  and others mentioned Vault in the past.

What do you think about? I'm open to suggestions before implementing this feature. Thank you!

**Comment by sagikazarmark** [comment]
KES would essentially be an extra layer on top of Vault/Managed KMSes which is not necessarily a bad thing, but it would still be a lock-in on someone else's abstraction if implemented as a sole solution for secret management.

So I'd rather suggest working out a custom (potentially extendable) abstraction for SFTPGo and see how KES or any other KMS/Secret management solution fits there. I'd also keep different use cases in mind:

- Fetch temporary credentials from Vault (using [Secret Engines](https://www.vaultproject.io/docs/secrets/aws))
- Fetch credentials from a secret manager (Vault, Google Secret Manager, etc)
- Decrypt credentials using KMS


Here is an alternate library for KMS abstraction: https://gocloud.dev/howto/secrets/

**Comment by drakkan** [comment]
Hi,

another KMS wrapping library is this one:

https://github.com/hashicorp/go-kms-wrapping

All these libraries basically expose Encrypt / Decrypt methods and this is the main use case I am considering for this first step: SFTPGo stores an encrypted secret and it ask to the KMS system to decrypt it. 

I think any of these libraries is good enough for this scope. KES seems the most interesting since I can encrypt/decrypt via REST API without any initialization code inside SFTPGo, so I can work with a local KES instance and it will work the same way with any supported KMS, the KMS configuration is outside SFTPGo so I can avoid code like this one

```
import (
	"gocloud.dev/secrets"
	_ "gocloud.dev/secrets/<driver>"
)
...
keeper, err := secrets.OpenKeeper(context.Background(), "<driver-url>")
```

that requires at least a minimal test with any supported KMS.

Vault secret engines and Vault in general looks really cool (I just played with it a bit). I could make a separate integration for it but honestly I would like to avoid to support any KMS out of there directly inside SFTPGo. So I could integrate a KMS wrapper to decrypt credentials or object encryption keys and vault to fetch permanent/temporary credentials

**Comment by sagikazarmark** [comment]
Well, the obvious downside of KES is the operational overhead.

I think it's okay if it's the default strategy, as long as the interface allows swapping implementations out.

For the long term, I think it would make sense to come up with a strategy to better support custom sftpgo builds with customized implementations for interfaces, like hooks and now secrets.

So as long as the solution doesn't lock sftpgo in to using a single solution, it should be okay.

**Comment by drakkan** [comment]
Hi,

I did some other tests, initially I tried `go-km-wrapping` since it supports a lot of providers but I didn't like it, maybe it solves different use cases. 

Gocloud secrets seems to work fine, thank your for suggesting it! I'm adding KMS support based on it, to give you an idea this is a full kms provider implementation

```
package kms

const (
	vaultProviderName = "VaultTransit"
)

type vaultSecret struct {
	baseGCloudSecret
}

func newVaultSecret(base baseSecret, url, masterKey string) Provider {
	return &vaultSecret{
		baseGCloudSecret{
			baseSecret: base,
			url:        url,
			masterKey:  masterKey,
		},
	}
}

func (s *vaultSecret) Name() string {
	return vaultProviderName
}

func (s *vaultSecret) IsEncrypted() bool {
	return s.Status == SecretStatusVaultTransit
}

func (s *vaultSecret) Encrypt() error {
	if err := s.baseGCloudSecret.Encrypt(); err != nil {
		return err
	}
	s.Status = SecretStatusVaultTransit
	return nil
}

func (s *vaultSecret) Decrypt() error {
	if !s.IsEncrypted() {
		return errWrongSecretStatus
	}
	return s.baseGCloudSecret.Decrypt()
}
```

and this is the `Provider` interface

```
type Provider interface {
	Name() string
	Encrypt() error
	Decrypt() error
	IsEncrypted() bool
	GetStatus() SecretStatus
	GetPayload() string
	GetKey() string
	GetAdditionalData() string
	SetKey(string)
	SetAdditionalData(string)
	SetStatus(SecretStatus)
}
```

if you embed the base structs, for each provider you only need to implement the 4 methods shown above.

In `sftpgo.json` we have this configuration:

```
"kms": {
    "url": "",
    "master_key_path": ""
  }
```

`url` is the uri for the provider as documented [here](https://gocloud.dev/howto/secrets/). If you want a local secret you can leave the url blank. If you provide the path to a master key file (for example a docker secret), the encryption key is derived from this key using `hkdf`.

All the providers are serialized to the same struct using custom marshal/unmarshal methods, so we keep backward compatibility and we avoid to have a separate sub-struct for each provider:

```
// baseSecret defines the base struct shared among all the secret providers
type baseSecret struct {
	Status         SecretStatus `json:"status,omitempty"`
	Payload        string       `json:"payload,omitempty"`
	Key            string       `json:"key,omitempty"`
	AdditionalData string       `json:"additional_data,omitempty"`
}
``` 

The serialized struct does not contain the master key and the provider url. So you can start using local secrets and then switch to a cloud provider. The local secrets will continue to work if the master key, if any, does not change. Currently if you switch among cloud providers changing the `url` in `sftpgo.json` you will be unable to decrypt the previous data. For example:

- you have some local secrets, this will work even if you change the provider to Vault
- you save some new secrets using Vault. Both Vault and local secrets will work
- you now change the provider to aws. The local secrets will continue to work, the new secrets saved to aws will work but the secrets saved to vault will not work

To fix this I have to serialize the provider url with the secret object but I think this could be a security issue (the url will be saved inside the dumps with the encrypted secret so it will be very easy to decrypt), what do you think about? Thank you
