### ISSUE TITLE
S3 - Cannot rename non empty directory

### ISSUE THREAD

**Issue by onyxg** [drakkan/sftpgo#227]
Well done on a great piece of software!

We can successfully create, edit files, move FILES and create new FOLDERs
But I cannot move or delete folders, receiving the following error:

**"failed to rename \"/files/tretre\" -> \"/tretre\": Cannot rename non empty directory: \"/files/tretre\""**

EC2 Instance, backed up S3 Bucket (with versioning enabled)
Version: sftpgo v1.2.2
Running: ubuntu 20.04 -- sftpgo as a service
User Setup: root user has access to home dir of bucket.

**Comment by drakkan** [comment]
Hi,

this is not supported, please take a look at the [documentation](https://github.com/drakkan/sftpgo/blob/master/docs/s3.md).

S3 has no real folders, they are emulated, renaming a "folder" means making a separate request for each object with the given prefix. If you have a large "folder" this may take a long time and the client will likely time out

**Comment by onyxg** [comment]
Ok thanks, forgot about this caveat, Thank you!

**Comment by onyxg** [comment]
That said, I still can't DELETE Folders, even if they are empty

**Comment by drakkan** [comment]
Hi, deleting empty folders or renaming empty folders should work (I just tested it against minio), can you please provide the logs, thank you

**Comment by onyxg** [comment]
```
{"level":"debug","time":"2020-11-23T13:57:53.348","sender":"SFTP","connection_id":"SFTP_f1325af395ee0aff738ced78453fd28d13f6b035b3997efb0ca0aadea17106b3_1","message":"new cmd, method: Rmdir, sourcePath: \"/public/rewrew\", targetPath: \"\""}
{"level":"warn","time":"2020-11-23T13:57:53.386","sender":"SFTP","connection_id":"SFTP_f1325af395ee0aff738ced78453fd28d13f6b035b3997efb0ca0aadea17106b3_1","message":"failed to remove directory \"/public/rewrew\": Cannot remove non empty directory: \"/public/rewrew\""}
```
![image](https://user-images.githubusercontent.com/12340537/99970626-c6e95900-2da4-11eb-9e0b-8eb4626670b0.png)

**Comment by drakkan** [comment]
When listing empty directory MinIO returns no contents while S3 returns 1 object with the key equal to the prefix. This was broken in the recent refactoring to improve WebDAV performance. 

It should work now, can you please confirm installing the last build artificat when available in the [action page](https://github.com/drakkan/sftpgo/actions/runs/379130000)? Thank you

**Comment by onyxg** [comment]
Rocking, will give it a bash and get back to you!
