### ISSUE TITLE
Unable to disable SFTP backend?

### ISSUE THREAD

**Issue by estelsmith** [drakkan/sftpgo#228]
We are currently able to enable/disable the FTP and WebDav services by setting the `bind_port` option to `0`. It doesn't seem like this is the case with the SFTP service.

Attempting to disable SFTP by setting `bind_port=0` appears to still attempt initializing SFTP.

```
{"level":"info","time":"2020-11-23T22:11:38.240","sender":"service","message":"starting SFTPGo 1.2.2-37fc5898-2020-11-18T18:35:01Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: /, config file: config, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, profile: false load data from: \"\""}
[...]
{"level":"debug","time":"2020-11-23T22:11:38.367","sender":"service","message":"initializing SFTP server with config {Banner:SFTPGo_1.2.2 BindPort:0 BindAddress: IdleTimeout:0 MaxAuthTries:0 UploadMode:0 Actions:{ExecuteOn:[] Hook:} Keys:[] HostKeys:[/tmp/id_rsa] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveHook: PasswordAuthentication:true ProxyProtocol:0 ProxyAllowed:[] certChecker:<nil> parsedUserCAKeys:[]}"}
```

---

This issue becomes a hindrance when one is using SFTPGo as initializing SFTP requires a valid SFTP configuration, so I'm forced to configure SFTP even if I have no intention of using it, such as providing `host_keys`, which the SFTP backend will fail without a correct configuration.

**Comment by drakkan** [comment]
This should be fixed now, thank you for reporting
