### ISSUE TITLE
Feature request: free text field in user configuration for hints and notes

### ISSUE THREAD

**Issue by emetriqChris** [drakkan/sftpgo#230]
Hi,

we're currently moving our sftp to a sftpgo based system. On our old system we had a notes field in the user configuration in which we put hints or notes like a issue number or things like "talk to person x if something goes wrong".

Is it possible to have such a field in sftpgo - editable through the admin webinterface. It doesn't has to be much (for me), something like 50-100 chars is more than enough.

Thanks!
Chris

**Comment by drakkan** [comment]
Yes, I'll add it. A free text field is useful to keep external references too, for example the user id inside an external system/database.

If you are migrating from a proprietary solution I would like to know the things SFTPGo do better and other missing features if any. Thank you

**Comment by emetriqChris** [comment]
Oh cool! Thanks a lot :-)

We're migrating from proftpd with some glue scripts to have the users in a mysql database plus an apache for WebDAV and phpMyAdmin for "administrating" the user accounts by directly altering the database.

It's reliable but not what one would call straight forward. So we looked for a alternative - which is sftpgo ;-) And it's doing a good job :-)

Till now we only miss the notes field plus pure HTTPS (readonly) access so some users may use a browser to have a look at the data stored on the system - but this is not that important since webdav support is buildin even in Windows ;-)

We like that it's an all-in-one solution, the web interface for administrating users, an api, s3 as storage backend, easy to use and high performance on low resources.
