### ISSUE TITLE
SFTPGo fails to start when downgrading

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#233]
When downgrading from the latest master to 1.2.2 SFTPGo fails to start with the following error:

```
{"level":"warn","time":"2020-11-26T10:03:24.196","sender":"dataprovider_mysql","message":"database migration error: Database version not handled: 6"}
{"level":"error","time":"2020-11-26T10:03:24.196","sender":"service","message":"error initializing data provider: Database version not handled: 6"}
```

Obviously, there are potential compatibility issues when running an older version with a newer schema, but it's considered to be a best practice to preserve backwards compatibility in database schema, at least through two minor versions.

IMHO it's not really good that after running a newer version (edge in this case), I can't roll back to the version before.

**Comment by drakkan** [comment]
The database schema changed in master, currently only update path is supported, you should change the database schema manually if you want to use the old version, the change to revert are these ones:

- https://github.com/drakkan/sftpgo/blob/master/dataprovider/sqlite.go#L66
- https://github.com/drakkan/sftpgo/blob/4bb9d07ddeba7537c8ab40526427ceaa3573e6fe/dataprovider/compat.go#L153

the second one is not easy to do manually. Probably the best thing is to restore a dump

**Comment by drakkan** [comment]
I'll try to add a subcommand like this one:

```
sftpgo downgradeprovider -c <config dir> --from 6 --to 4
```

so you can downgrade the schema and data from the new version before installing the old one. From the old to the new you can use the automatic mode or `initprovider` if you prefer a manual management.

Only downgrade from v6 (current master version) to v4 (1.0.0-1.2.x) will be supported the other versions are too old

**Comment by sagikazarmark** [comment]
I don't think it should fail to start when there is a newer schema.

Downgrading is a perfectly valid action when a bug is identified in a newer version. Having to go through schema downgrades is painful.

**Comment by drakkan** [comment]
current git master don't fail to start with a [newer schema](https://github.com/drakkan/sftpgo/blob/master/dataprovider/mysql.go#L225), so starting from the next update I'll try to keep backward compatibility with the previous version
