### ISSUE TITLE
Webdav not respecting user home path

### ISSUE THREAD

**Issue by nader-eloshaiker** [drakkan/sftpgo#234]
Using SFTP, configured user home path is applied in a an sftp session. However, when enabling webdav and logging in using an HTTP session, the home path is the root path and not the configured user home path.

**Comment by drakkan** [comment]
Hi,

it seems to work as expected for me. I have the user "test" with home dir set to `/srv/sftpgo/data/test`

```shell
ls /srv/sftpgo/data/test
file.txt
```

via sftp:

```
sftp -P 2222 test@127.0.0.1
test@127.0.0.1's password: 
Connected to 127.0.0.1.
sftp> ls
file.txt  
sftp> quit
```

via webdav

![Schermata del 2020-11-29 09-09-39](https://user-images.githubusercontent.com/553263/100536712-a9901100-3222-11eb-9b9f-e4d229af440b.png)

The webdav url is `http://127.0.0.1:10080/test`. If I try  `http://127.0.0.1:10080/` I got a 301 http response.

Maybe you are hitting an edge case, please share the exact steps and the relevant logs, thank you

**Comment by drakkan** [comment]
It seems to work as expected, please reopen providing more info if you are still experiencing this issue, thank you
