### ISSUE TITLE
Using drakkan/sftpgo with Azure Container Instance : persisting info in Files Share

### ISSUE THREAD

**Issue by laurentAstonIf** [drakkan/sftpgo#235]
Hello

I'm not sure if this is a bug or a misunderstanding on my side
i have prepared a Container Account with 2 files share, one for data , one for users account 
i'm using a yaml file to build the container instance 

The container is created but when starting i'm getting these errors messages 
{"level":"debug","time":"2020-11-30T17:53:59.081","sender":"dataprovider_sqlite","message":"sqlite database handle created, connection string: \"file:sftpgo.db?cache=shared&_foreign_keys=1\""}
{"level":"warn","time":"2020-11-30T17:53:59.134","sender":"dataprovider_sqlite","message":"error preparing database query \"SELECT version from schema_version LIMIT 1\": no such table: schema_version"}
{"level":"warn","time":"2020-11-30T17:54:04.216","sender":"dataprovider_sqlite","message":"Unable to initialize data provider: database is locked"}
{"level":"error","time":"2020-11-30T17:54:04.216","sender":"service","message":"error initializing data provider: database is locked"}

in the yaml file i have 
volumeMounts:
      - mountPath: /srv/sftpgo
        name: filesharedata
      - mountPath: /var/lib/sftpgo
        name: fileshareuser

and both volumes have readOnly: false property

i was hoping to persit the sftpgo.db in this file share volume

i have also tried with a env variable SFTPGO_COMMON__SETSTAT_MODE=2
which i can see in the log ( config loaded: {Common:{IdleTimeout:15 UploadMode:0 Actions:{ExecuteOn:[] Hook:} SetstatMode:**2** 

i'm using this image : drakkan/sftpgo:v1.2.2

If i'm uploading an existing sftpgo.db which contains users, the container starts and runs 
i then have access to the web site but can't add any user 
=> i'm getting the same error data provider: database is locked

Do anyone has experienced the same kind of problem ?
it looks like files on the Files Shared are readonly
and i don't really see any other option for access rigth in the yaml file 

Thanks

**Comment by drakkan** [comment]
Hi,

try to use `bolt` as dataprovider, this seems the same issue as #202 

thank you

**Comment by laurentAstonIf** [comment]
i will try, thanks
ps : using an existing sftpgo.db with users i was able to upload a file within the shareddata folder (so they are not readonly)

**Comment by laurentAstonIf** [comment]
It works as expected, thank you very much

**Comment by drakkan** [comment]
Thank you for confirming, I just tested a SQLite database over a CIFS mount using `sqlite3` CLI directly, here is the result:

```shell
sqlite3 sftpgo.db 
SQLite version 3.33.0 2020-08-14 13:23:32
Enter ".help" for usage hints.
sqlite> select id FROM users where id=62033;
62033
sqlite> DELETE FROM users where id=62033;
Error: database is locked
sqlite> .quit
```

it works if I set the option `nobrl`. From man cifs

```
nobrl  Do  not  send  byte range lock requests to the server. This is necessary for certain applications that
              break with cifs style mandatory byte range locks (and most cifs servers do not yet support  requesting
              advisory byte range locks).
```

maybe I have to document this behaviour

**Comment by ExterGr** [comment]
I solved this problem just by adding permissions to volumes folders with:
`chmod -R 777 volume-folder`
