### ISSUE TITLE
Switch to viper?

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#24]
Similar as my kingpin suggestion, [viper](https://github.com/spf13/viper) is a great tool for configuration loading. It supports multiple formats out of the box, can go through multiple loading locations (eg. `[$HOME, "/etc/sftpgo/"]`) and has numerous interesting features.

I would also suggest to use `sftpgo.json` instead of `sftpgo.conf` for the `json`-formatted configuration file - my editor would be grateful :-)

**Comment by drakkan** [comment]
We need to evaluate viper and maybe cobra too. But first we need to understand I we need an advanced argument parser, actually we use arguments only for config dir and logging configuration. 

I think the only missing feature is to be able to set the default values for arguments from env vars.

For example instead of hardcode config-dir default to "." we could read a CONFIG_DIR env var and use its value as default or "." if the env var is not defined. To add this feature probably we don't need a dedicated argument parser.

If we make sftpgo a CLI tool too with subcommands ecc.. that a more advanced parser is needed

**Comment by jovandeginste** [comment]
Missed that commit, thx!

**Comment by drakkan** [comment]
Maybe I'm missing something but I think the actual configuration system that simply decode a json file is enough.

The command line arguments are not related to the config options and the only feature that, in my opinion is useful, is to set a default command line argument value from an env var. Viper allows this and many other things, but at the same time this is already implemented with less than 10 line of code.

Am I missing something? What is the rationale for switching to viper? I think we need to add an external depend only if it gives improvements and keep the usage and maintenance complexity low.

I'm open to opinions, thanks!

**Comment by jovandeginste** [comment]
First of all, (this is subjective, but) I don't like to write `json` configuration. Viper allows sysadmin to write their configuration in a number of formats (`yaml`, `toml`, `xml`, ...) To each his own :-)

Then again, I have configuration management that generates the `json` from my own `yaml` source configuration, so it's a minor change. Only when stuff goes wrong, it's easier when the real config is in my preferred language.

Second, I believe this project would be perfect to run in a container. In this case, the less configuration needs to be on disk, the better. So if it would at all be possible to run `sftpgo` without any configuration file, that would be ideal. However, the reality would be that we (as a user of `sftpgo`) will build a docker image with sftpgo and a generic configuration file, and then override whatever is different for every service instance. This means that, in the long run, I _expect_ more configuration values to be configurable through CLI flags until they all are (at least the ones that are broadly used).

I'm not sure I'm actually clarifying anything now :-)

**Comment by drakkan** [comment]
this make sense, I'm not more a sysadmin since about 10 years and probably I forgot as lazy a sysadmin is :)

I'll did some experiments with viper in the coming weeks, thanks for the suggestion!

**Comment by drakkan** [comment]
we use viper now, thanks for your suggestion
