### ISSUE TITLE
If the directory contains more than ~3000 files, sftp client reported an error

### ISSUE THREAD

**Issue by Win32Sector** [drakkan/sftpgo#243]
Hello! We are testing sftpgo. More than 3000 files were uploaded to the user directory. I see them on the filesystem.
But when I try to connect to stfpgo server and try to list directory, I receive an error

"message":"error listing directory: readdirent: no such file or directory"

Is this a normal behaivor? Is it some file count restrictions in sftpgo?

**Comment by drakkan** [comment]
Hi,

I just did a quick test. I added 15.000 files inside a local folders and directory listing works fine in both `sftp` CLI and filezilla.

Can you please share more info? Are you using local fs or a cloud storage provider? Which SFTP client are you using? Thank you

**Comment by Win32Sector** [comment]
We are using sftpgo in kubernetes in Azure AKS.
We are using azurefiles for volume for sftpgo files.

**Comment by drakkan** [comment]
Ok, so you are using a CIFS share, this seems similar to this issue

https://forum.rclone.org/t/seeing-failed-to-read-directory-entry-readdirent-no-such-file-or-directory-with-v1-52-2/17816/11
https://github.com/golang/go/issues/39237

**Comment by drakkan** [comment]
Hi,

this bug should be fixed in go 1.16 (February 2021), meantime please try to set this env var:

```
GODEBUG=asyncpreemptoff=1
```

it could help, thank you

**Comment by Win32Sector** [comment]
Yes, thanx. I will trying to build sftpgo with this env var.

**Comment by drakkan** [comment]
> Yes, thanx. I will trying to build sftpgo with this env var.

I haven't tested it but I think there is no need to rebuild sftpgo, just set the suggested env var before running sftpgo, please let me know if this fix the issue, thank you

**Comment by drakkan** [comment]
Hi,

I did a quick test and setting the suggested env var seems to work, no rebuild is required

**Comment by Win32Sector** [comment]
Yes, we are running sftpgo with GODEBUG=asyncpreemptoff=1 and it is working without issues now
`GODEBUG=asyncpreemptoff=1 /app/sftpgo/bin/sftpgo serve`
