### ISSUE TITLE
/metrics without authentication

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#244]
I am using htpasswd for the mgmt UI, and i wish to scrape the metrics endpoint, i do know its possible to provide basic auth in prometheus scraping, and this already works however is it possible that the /metrics endpoint can be made public?

**Comment by drakkan** [comment]
Hi,

this could be done, but I would like to know the reason you don't want authentication for metrics. I'm sure that if I disable it unconditionally someone will open an issue, so I should make it configurable but I would like to understand the rationale first, thank you

**Comment by ryjogo** [comment]
Hey, Yeah sure 

I mean currently there is no limitation to what a authenticated user can and cannot do. i.e. one cannot make a "metrics" user to only authenticate to the metrics endpoint. Today, if i make a metrics user, and configure this in my application, that username/password can be used to gain control of the UI. 

Perhaps one could define what the user can and cannot do? i.e. mgmt, metrics, api etc.

**Comment by drakkan** [comment]
Hi,

yes this is planned in this release cycle (1.3.0), see #197. I plan to add (admin) users and permissions directly inside the data provider so you don't need to create a password file anymore and you can control permissions for each user. However this isn't a top priority so I'm working on other things first.

**Comment by ryjogo** [comment]
fantastic! thanks, and keep up the great work

**Comment by sagikazarmark** [comment]
Generally speaking, metrics endpoints are usually not exposed to the internet, but rather made available on an internal interface, separate from the main application (eg. on a separate http server listening on a different port), since metrics are more useful to operators than users.

I usually have a separate telemetry server for this purpose: https://github.com/sagikazarmark/modern-go-application/blob/160281d3f32280b4fa3d97b81c4941e2eaa925df/cmd/modern-go-application/main.go#L194

**Comment by drakkan** [comment]
> Generally speaking, metrics endpoints are usually not exposed to the internet, but rather made available on an internal interface, separate from the main application (eg. on a separate http server listening on a different port), since metrics are more useful to operators than users.
> 
> I usually have a separate telemetry server for this purpose: https://github.com/sagikazarmark/modern-go-application/blob/160281d3f32280b4fa3d97b81c4941e2eaa925df/cmd/modern-go-application/main.go#L194

This is a good suggestion, thanks!

**Comment by drakkan** [comment]
Please reopen if #254 does not fix the issue, thank you
