### ISSUE TITLE
sftpgo-api-cli is giving error while creating new user

### ISSUE THREAD

**Issue by dharmendrakariya** [drakkan/sftpgo#246]
Hi, 

when I am using sftpgo-api-cli and firing this below command

```
python sftpgo_api_cli add-user test_username --password "test_pwd" --home-dir="/tmp/test_home_dir" --uid 33 --gid 1000 --max-sessions 2 --quota-size 0 --quota-files 3 --permissions "list" "download" "upload" "delete" "rename" "create_dirs" "overwrite" --subdirs-permissions "/dir1::list,download" "/dir2::*" --upload-bandwidth 100 --download-bandwidth 60 --status 0 --expiration-date 2019-01-01 --allowed-ip "192.168.1.1/32" --fs S3 --s3-bucket test --s3-region eu-west-1 --s3-access-key minio123 --s3-access-secret minio123 --s3-endpoint "http://127.0.0.1:9000" --s3-storage-class Standard --s3-key-prefix "vfolder/" --s3-upload-part-size 10 --s3-upload-concurrency 4 --denied-login-methods "password" "keyboard-interactive" --allowed-patterns "/dir1::*.jpg,*.png" "/dir2::*.rar,*.png" --denied-patterns "/dir3::*.zip,*.rar" --denied-protocols DAV FTP --additional-info "sample info"
```
I am getting this error, am I doing anything wrong?
```
{
  "error": "json: cannot unmarshal object into Go struct field S3FsConfig.filesystem.s3config.access_secret of type string",
  "message": ""
}
```

**Comment by drakkan** [comment]
Hi,

you are likely using incompatible versions, access_secret was changed from a string to a struct so please make sure to use [api cli 1.2.2](https://github.com/drakkan/sftpgo/tree/v1.2.2/examples/rest-api-cli) if you are using sftpgo 1.2.2 or the latest api cli if you are using git master/edge docker image

**Comment by dharmendrakariya** [comment]
hey,

I am using this file, please [see](https://github.com/drakkan/sftpgo/blob/master/examples/rest-api-cli/sftpgo_api_cli).

**Comment by dharmendrakariya** [comment]
hey, Thanks it is working fine.

btw I am opening a PR for that correction.

**Comment by drakkan** [comment]
exactly, you are using git master version against 1.2.2, this is not supported. Please update the server to the  git master too or use the api cli compatible with 1.2.2 version:

https://github.com/drakkan/sftpgo/blob/v1.2.2/examples/rest-api-cli/sftpgo_api_cli

please note the v1.2.2 inside the above link, you are using this:

https://github.com/drakkan/sftpgo/blob/master/examples/rest-api-cli/sftpgo_api_cli

**Comment by dharmendrakariya** [comment]
done, Thanks for the support:)
