### ISSUE TITLE
How to change sftpgo loglevel

### ISSUE THREAD

**Issue by Win32Sector** [drakkan/sftpgo#248]
Hello!

I want to change loglevel of sftpgo logs, but I doesn't find any loglevel settings here
https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md

I find parameter --log-verbose and try to run sftpgo with --log-verbose false, but it isn't what I want. 

I want to log only errors, but by default warning and debug messages in the log.

**Comment by drakkan** [comment]
Hi,

please try `--log-verbose=false` or set the env var `SFTPGO_LOG_VERBOSE=0`, this will remove debug messages, I think other log messages are essential to understand what is sftpgo doing

**Comment by Win32Sector** [comment]
I tried these:
`/app/sftpgo/bin/sftpgo serve --log-verbose false;
`and
```
env:
            - name: SFTPGO_LOG_VERBOSE
              value: "0"
```

But sftpgo is still logging events with debug and warn loglevels

For example:

`{"level":"warn","time":"2020-12-12T11:28:06.967","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: read tcp 10.240.0.20:2022->10.240.1.152:17391: read: connection reset by peer"}{"level":"debug","time":"2020-12-12T11:28:06.967","sender":"connection_failed","client_ip":"10.240.1.152","username":"","login_type":"no_auth_tryed","error":"read tcp 10.240.0.20:2022->10.240.1.152:17391: read: connection reset by peer"}{"level":"warn","time":"2020-12-12T11:28:10.914","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: read tcp 10.240.0.20:2022->10.240.0.105:34896: read: connection reset by peer"}`

**Comment by drakkan** [comment]
> I tried these:
> `/app/sftpgo/bin/sftpgo serve --log-verbose false; `and
> 

this should be `--log-verbose=false`

> ```
> env:
>             - name: SFTPGO_LOG_VERBOSE
>               value: "0"
> ```
> 

this one looks correct

> But sftpgo is still logging events with debug and warn loglevels
> 
> For example:
> 
> `{"level":"warn","time":"2020-12-12T11:28:06.967","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: read tcp 10.240.0.20:2022->10.240.1.152:17391: read: connection reset by peer"}{"level":"debug","time":"2020-12-12T11:28:06.967","sender":"connection_failed","client_ip":"10.240.1.152","username":"","login_type":"no_auth_tryed","error":"read tcp 10.240.0.20:2022->10.240.1.152:17391: read: connection reset by peer"}{"level":"warn","time":"2020-12-12T11:28:10.914","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: read tcp 10.240.0.20:2022->10.240.0.105:34896: read: connection reset by peer"}`

if you configure sftpgo correctly the debug messages will go away, warns will remain

**Comment by drakkan** [comment]
At startup sftpgo will print the received flags:

```
{"level":"info","time":"2020-12-12T12:51:17.044","sender":"service","message":"starting SFTPGo 1.2.2-dev-4d54949-dirty-2020-12-12T09:26:35Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: , log max size: 10 log max backups: 5 log max age: 28 log verbose: false, log compress: false, profile: false load data from: \"\""}
```

so please be sure to see `log verbose: false`

**Comment by Win32Sector** [comment]
`{"level":"info","time":"2020-12-12T12:05:42.995","sender":"service","connection_id":"","message":"starting SFTPGo 1.0.0-1ac4baa-2020-10-15T11:28:29Z +metrics -gcs -s3 -bolt -mysql +pgsql +sqlite -portable, config dir: /app/config, config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, profile: false"}`

but 
ehwn I execute inside container
`env  | grep SFTPGO_LOG
`
SFTPGO_LOG_FILE_PATH=
SFTPGO_LOG_VERBOSE=0

And in the config.json I don't see this parameter.
How can I define it in contig directly?

cat /app/sftpgo/.config/sftpgo/sftpgo.json 
```
{
  "sftpd": {
    "bind_port": 2022,
    "bind_address": "",
    "idle_timeout": 15,
    "max_auth_tries": 0,
    "umask": "0022",
    "banner": "",
    "upload_mode": 0,
    "actions": {
      "execute_on": [],
      "hook": ""
    },
    "host_keys": [],
    "kex_algorithms": [],
    "ciphers": [],
    "macs": [],
    "trusted_user_ca_keys": [],
    "login_banner_file": "",
    "setstat_mode": 0,
    "enabled_ssh_commands": [
      "md5sum",
      "sha1sum",
      "cd",
      "pwd",
      "scp"
    ],
    "keyboard_interactive_auth_hook": "",
    "proxy_protocol": 0,
    "proxy_allowed": []
  },
  "data_provider": {
    "driver": "sqlite",
    "name": "sftpgo.db",
    "host": "",
    "port": 5432,
    "username": "",
    "password": "",
    "sslmode": 0,
    "connection_string": "",
    "sql_tables_prefix": "",
    "manage_users": 1,
    "track_quota": 2,
    "pool_size": 0,
    "users_base_dir": "",
    "actions": {
      "execute_on": [],
      "hook": ""
    },
    "external_auth_hook": "",
    "external_auth_scope": 0,
    "credentials_path": "credentials",
    "pre_login_hook": ""
  },
  "httpd": {
    "bind_port": 8080,
    "bind_address": "127.0.0.1",
    "templates_path": "templates",
    "static_files_path": "static",
    "backups_path": "backups",
    "auth_user_file": "",
    "certificate_file": "",
    "certificate_key_file": ""
  },
  "http": {
    "timeout": 20,
    "ca_certificates": [],
    "skip_tls_verify": false
  }
```

**Comment by drakkan** [comment]
This is a CLI flag not a configuration parameter

```
env | grep SFT
SFTPGO_LOG_VERBOSE=0
nicola@p1 ~/goprojects/sftpgo $ ./sftpgo serve -l ""
{"level":"info","time":"2020-12-12T13:17:36.702","sender":"service","message":"starting SFTPGo 1.2.2-dev-4d54949-dirty-2020-12-12T09:26:35Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: , log max size: 10 log max backups: 5 log max age: 28 log verbose: false, log compress: false, profile: false load data from: \"\""}
```

```
env | grep SFT
./sftpgo serve -l "" --log-verbose=false
{"level":"info","time":"2020-12-12T13:18:54.603","sender":"service","message":"starting SFTPGo 1.2.2-dev-4d54949-dirty-2020-12-12T09:26:35Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: , log max size: 10 log max backups: 5 log max age: 28 log verbose: false, log compress: false, profile: false load data from: \"\""}
```

**Comment by drakkan** [comment]
I just noticed you are using an ancient version `starting SFTPGo 1.0.0-1ac4baa`, I don't remember if this version worked differently, please try to switch to the official [docker image](https://github.com/drakkan/sftpgo/tree/master/docker), thank you

**Comment by Win32Sector** [comment]
ok, I wil try 1.2.2

**Comment by drakkan** [comment]
It works the same way in 1.0.0 too, please take a look here:

```
./sftpgo -v
SFTPGo 1.0.0-1ac4baa-2020-12-12T12:52:48Z +metrics +gcs +s3 +bolt +mysql +pgsql +sqlite +portable

./sftpgo serve -l "" --log-verbose=false
{"level":"info","time":"2020-12-12T13:54:22.026","sender":"service","connection_id":"","message":"starting SFTPGo 1.0.0-1ac4baa-2020-12-12T12:52:48Z +metrics +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: false, log compress: false, profile: false"}
```

and using the env var:

```
export SFTPGO_LOG_VERBOSE=0
./sftpgo serve -l ""
{"level":"info","time":"2020-12-12T13:54:52.161","sender":"service","connection_id":"","message":"starting SFTPGo 1.0.0-1ac4baa-2020-12-12T12:52:48Z +metrics +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: false, log compress: false, profile: false"}
```

please note that boolean flag require the `=`, see [here](https://golang.org/pkg/flag/#hdr-Command_line_flag_syntax)

**Comment by Win32Sector** [comment]
1.2.2 it is working. But "warn" messages still logged.
Can I desable them? 
{"level":"warn","time":"2020-12-12T13:00:59.079","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: read tcp 10.240.0.187:2022->10.240.0.206:56554: read: connection reset by peer"}{"level":"warn","time":"2020-12-12T13:00:59.102","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: read tcp 10.240.0.187:2022->10.240.1.51:7016: read: connection reset by peer"}{"level":"warn","time":"2020-12-12T13:00:59.287","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: read tcp 10.240.0.187:2022->10.240.1.152:17394: read: connection reset by peer"}{"level":"warn","time":"2020-12-12T13:01:10.986","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: read tcp 10.240.0.187:2022->10.240.0.4:39388: read: connection reset by peer"}

**Comment by drakkan** [comment]
Hi,

warning is basically the maximum log level, we log almost nothing at error level, disabling warn log level will mean disable the logs completely.

The particular log message you posted was demoted from warn to debug a long time ago, in v1.2.2 and in current git master we have this:

https://github.com/drakkan/sftpgo/blob/v1.2.2/sftpd/server.go#L285

so with log verbose disabled you shouldn't see it.

It is a warning in 1.0.0:

https://github.com/drakkan/sftpgo/blob/v1.0.0/sftpd/server.go#L345

**Comment by Win32Sector** [comment]
It is strange, but it is working only when I run 

SFTPGO_LOG_VERBOSE=0 /app/sftpgo/bin/sftpgo serve

But it's working. Thanks.
