### ISSUE TITLE
Connecting with WinScp

### ISSUE THREAD

**Issue by ajksharma** [drakkan/sftpgo#25]
Hi,

Sftpgo is running fine on my ubuntu server. (the log is fine)

I have manually inserted a user with a password in the sqlite database.
While connecting via WinScp it throws a authentication error.
Hope I am doing the right steps?

Thanks,

Ajay

**Comment by drakkan** [comment]
Hi, 

please try to add an user using the sample CLI here:

https://github.com/drakkan/sftpgo/tree/master/scripts

and reports back if the login still does not work, thanks

**Comment by drakkan** [comment]
I just tested myself using win scp 5.15.3 portable, and it works as expected, 

please reopen with more info if needed, for example relevant logs and/or database content, thanks!

**Comment by ajksharma** [comment]
Thanks It works.
