### ISSUE TITLE
Attach Azure Fileshare

### ISSUE THREAD

**Issue by pragadeeshraju** [drakkan/sftpgo#251]
Hello,

This seems to be great product, is there any way to use Azure FileShares(Azure files). I could see we were able to only Azure blobs.

Thanks.

**Comment by drakkan** [comment]
Hi,

as far as I understand Azure files should be accessible via SMB mounts so you can mount the share and use it in SFTPGo as local storage. This should work.

**Comment by pragadeeshraju** [comment]
@drakkan thanks for the quick reply. I will try that out and revert. And btw it is great product.

**Comment by drakkan** [comment]
> @drakkan thanks for the quick reply. I will try that out and revert. And btw it is great product.

Hi, 

please note that to use SMB shares you have to the set the `GODEBUG=asyncpreemptoff=1` env var. This bug will be fixed in go 1.16, more details in #243

**Comment by drakkan** [comment]
Hi,

if mounting the share work as expected please close this issue, thank you!
