### ISSUE TITLE
Feature request: User groups

### ISSUE THREAD

**Issue by Flameborn** [drakkan/sftpgo#252]
My current scenario is I'd like to create multiple users having the same directories and virtual folders, as well as permissions defined. At the moment, there is no way to set this up and apply it to multiple users, i.e. multiple users need to be created and configured.

Do you think it'd be possible to add a groups feature, where users belonging to the same group would share the defined fields, unless they are specifically overwritten on a per user basis? For example having a different home directory, or virtual folders.

This would be a huge timesaver.

Edit: I do see similarities with https://github.com/drakkan/sftpgo/issues/225, however, I think my groups solution would be much more elegant, as well as easier to implement when it comes to the web interface part, since you could use a dropdown, similarly to how you can set the active/inactive status for a user during creation.

**Comment by drakkan** [comment]
Currently the only solution is to create a small script using the [REST API CLI](https://github.com/drakkan/sftpgo/tree/master/examples/rest-api-cli), something like this:

```
for username in user1 user2; do
      sftpgo_api_cli add-user $username <other params>
done 
```

If I remember correctly filezilla server has something similar to what you describe. Eventually I'll take a look at it and I could try to add something similar in future but I don't plan to work on this anytime soon, sorry

**Comment by yuppox** [comment]
+1 for this feature.

Cloning is nice but it doesn't help when you have to update a group of users.

**Comment by drakkan** [comment]
Hi,

I'm not going to add groups, at least for now, sorry. I may change my mind in the future, in the past I have added several features that I initially didn't like.

However if you have to create many similar users you can try the templates introduced in this [commit](https://github.com/drakkan/sftpgo/commit/54321c524044559cbe30008c9e527cbd3f56eae0). They are designed in a way that you can create and validate users on a development instance and them import them inside the production instance.

This should allow to easily create/update similar users. It doesn't help if you want to update one or more fields for multiple non-homogeneous users (but even groups do not help in this case). For this use case I'll add an example script that you can customize based on your need before the next release.
