### ISSUE TITLE
Bind SFTP Server to Multiple Ports?

### ISSUE THREAD

**Issue by valdearg** [drakkan/sftpgo#253]
Can the SFTP server bind to multiple ports? I like to bind to default port 22 and a higher port just in case it's blocked elsewhere.

**Comment by sagikazarmark** [comment]
No, it cannot and I don't think it would be trivial to implement (without nasty hacks like a goroutine merging connections).

IMHO it's quite standard that the operator has to choose an appropriate port.

**Comment by drakkan** [comment]
I think we could try to change the configuration from this:

```
"sftpd": {
    "bind_port": 2022,
    "bind_address": "",
    ...
```

to something like this:

```
"sftpd": {
    "bindings": [
      {
        "port": 2022,
        "address": ""
      }
    ],
    ....
```

so you can add other bindings, for example:

```
 "sftpd": {
    "bindings": [
      {
        "port": 2022,
        "address": ""
      },
      {
        "port": 22,
        "address": "192.168.1.1"
      },
      {
        "port": 2222,
        "address": "192.168.1.10"
      }
    ],
    ...
```

for each binding we'll start a new listener, instead of a [single listener](https://github.com/drakkan/sftpgo/blob/master/sftpd/server.go#L184)

**Comment by sagikazarmark** [comment]
I honestly haven't seen any other software allowing to bind a service to multiple ports (except maybe webservers, but it does make sense in that case). I'm not sure it's worth the effort.

A potential alternative is binding sftpgo to a high enough port (eg. 10022) and running a proxy server next to it that binds additional ports. (This is actually what happens when you use a loadbalancer)

**Comment by valdearg** [comment]
Quite a lot of services allow it in my experience, including the regular OpenSSH Server.

**Comment by sagikazarmark** [comment]
Hm, interesting. I wasn't aware of it.

**Comment by drakkan** [comment]
OpenSSH allows to specify multiple `ListenAddress` this should be quite similar to the solution I proposed above, do you agree?

Multiple bindings will be allowed for SFTP and FTP services, I think a single binding is enough for REST API and telemetry services.

**Comment by sagikazarmark** [comment]
I'm still not sure if it's worth the effort, I'd still go with the proxy solution, but if it's an accepted solution I guess it's okay.

**Comment by drakkan** [comment]
I'm trying to implement this:

```
"sftpd": {
    "bindings": [
      {
        "address": "",
        "port": 2022,
        "apply_proxy_config": true
      }
    ],
...
```

the problem here is that viper seems unable to accept a such configuration as env vars. I was hoping something like this would work:

```
SFTPGO_SFTPD__BINDINGS0__PORT=2222
SFTPGO_SFTPD__BINDINGS1__PORT=2224
```

but it doesn't :(

@sagikazarmark is writing a custom decode hook the only solution? thank you

**Comment by sagikazarmark** [comment]
No, unfortunately that's not supported for a wide range of reasons (mapstructure, automatic env in viper, etc).

It's on my radar for some time now, but I don't have a solution at this time. :(

**Comment by drakkan** [comment]
> No, unfortunately that's not supported for a wide range of reasons (mapstructure, automatic env in viper, etc).
> 
> It's on my radar for some time now, but I don't have a solution at this time. :(

No problem, I'll use a ugly hack inside SFTPGo itself. 

If/when viper will support this is more likely that the env var will be:

```
SFTPGO_SFTPD__BINDINGS0__PORT
SFTPGO_SFTPD__BINDINGS1__PORT
```

or

```
SFTPGO_SFTPD__BINDINGS__0__PORT
SFTPGO_SFTPD__BINDINGS__1__PORT
```

I like more the second variant, thank you

**Comment by sagikazarmark** [comment]
> If/when viper will support this is more likely that the env var will be:

IF...very big if 🙂 

Probably the second variant. But I wouldn't rely on what Viper might or might not support.

**Comment by sagikazarmark** [comment]
As an alternative, how about accepting an address as a single, comma separated field?

Something like `SFTPGO_SFTPD__ADDR=127.0.0.1:22,:10022`

AFAIK it's more common to have a single address anyway.

**Comment by drakkan** [comment]
> As an alternative, how about accepting an address as a single, comma separated field?
> 
> Something like `SFTPGO_SFTPD__ADDR=127.0.0.1:22,:10022`
> 
> AFAIK it's more common to have a single address anyway.

This is exactly what I did for host keys when I realized that viper does not support this feature, it was a [slice of structs](https://github.com/drakkan/sftpgo/blob/master/sftpd/server.go#L58) before.

For bindings it looks a bit different because a particular binding might have other properties associated with it. For example I recently added implicit TLS support to ftpserverlib, with the current configuration we can have only implicit or only explicit TLS but not both. Something similar for webdav, we can have HTTP or HTTPS but not both. In my WIP I have something like this:

```
"ftpd": {
    "bindings": [
      {
        "address": "",
        "port": 2121,
        "apply_proxy_config": false,
        "tls_mode": 1,
        "force_passive_ip": ""
      },
      {
        "address": "",
        "port": 2122,
        "apply_proxy_config": true,
        "tls_mode": 2,
        "force_passive_ip": ""
      }
    ],
```

and 

```
"webdavd": {
    "bindings": [
      {
        "address": "",
        "port": 10080,
        "enable_https": false
      },
      {
        "address": "",
        "port": 10443,
        "enable_https": true
      }
    ]
```

I agree that for basic needs a single address is enough but we should support specialized use cases too
