### ISSUE TITLE
HTTP 405 Method Not Allowed response on HEAD request

### ISSUE THREAD

**Issue by sector-f** [drakkan/sftpgo#255]
Attempting HEAD requests on the web server gives a 405 Method Not Allowed Response, rather than the correct response (i.e. the same response as an equivalent GET request).

Interestingly enough, the responses to the HEAD requests that I've attempted include `Content-Length: 33` in the response headers. This is not the actual Content-Length of an equivalent GET request, and no body is actually sent as part of the response (which _is_ actually the correct behavior; RFC 7231 states that "the server MUST NOT send a message body in the response" to a HEAD request).

This is certainly a minor nitpick, but I do like my HTTP servers to follow the standards as closely as possible.

**Comment by sector-f** [comment]
I've never used Chi before, but it looks like it provides a [GetHead middleware](https://pkg.go.dev/github.com/go-chi/chi/middleware#GetHead) out of the box, so hopefully fixing this could just be a single line added to the `httpd/router.go` file?

**Comment by drakkan** [comment]
It should be fixed now, thank you for reporting!
