### ISSUE TITLE
Changing passwords

### ISSUE THREAD

**Issue by yuppox** [drakkan/sftpgo#256]
Is there a way for users to change their passwords?

EDIT:
Could LDAP be an option?

**Comment by drakkan** [comment]
Hi, 

SFTP/FTP protocols do not allow users to change their passwords. An administrator must change passwords for users.

LDAP can be used using external authentication. You can find some examples here:

- https://github.com/drakkan/sftpgo/tree/master/examples/ldapauth
- https://github.com/drakkan/sftpgo/tree/master/examples/ldapauthserver

**Comment by yuppox** [comment]
Thank you!
