### ISSUE TITLE
unmarshal error for field Language of type disconnectMsg

### ISSUE THREAD

**Issue by mcdappdev** [drakkan/sftpgo#26]
After updating to the latest version I get this error message when attempting to connect:

`unmarshal error for field Language of type disconnectMsg`

And then it times out. Any ideas?

**Comment by drakkan** [comment]
Do you have a reproducer?

**Comment by mcdappdev** [comment]
No, because I'm not sure what part of the program is causing the problem. I can share my config file if that helps?

**Comment by drakkan** [comment]
Yes please share the config file. It happens with a particular client or with every clients? Thanks

**Comment by mcdappdev** [comment]
With every client. Here is the config: 

```json
{
    "sftpd": {
        "bind_port": 22,
        "bind_address": "0.0.0.0",
        "idle_timeout": 15,
        "max_auth_tries": 0,
        "umask": "0022",
        "actions": {
            "execute_on": [
                "upload"
            ],
            "command": "/app/upload.sh"
        }
    },
    "data_provider": {
        "driver": "mysql",
        "name": "sftp",
        "host": "HOST-HERE",
        "port": 3306,
        "username": "USERNAME-HERE",
        "password": "PASSWORD-HERE",
        "sslmode": 0,
        "users_table": "users",
        "manage_users": 1,
        "track_quota": 1
    },
    "httpd": {
        "bind_port": 8080,
        "bind_address": ""
    }
}
```

**Comment by drakkan** [comment]
It seems to work for me.

Do It work if you revert to a previous git commit?

**Comment by mcdappdev** [comment]
How do I do that with `go get`? Sorry, I'm a `go` newbie :)

**Comment by drakkan** [comment]
Try this:

```
git clone git@github.com:drakkan/sftpgo.git
cd sftpgo
git log
```
git log will show commit hash and then using for example

```
git checkout 34543fd8619babc0aa803ef72ef3de9849b16f07
```

will revert back to this commit

```
commit fab21dcf51999491b765f935b1497c8c0ce50ab7
Author: Nicola Murino <nicola.murino@gmail.com>
Date:   Wed Jul 31 08:14:31 2019 +0200

    Print initialization errors to standard output
    
    This way debugging configuration and initialization issues is simpler
```

then build this version using

```
go build -i -ldflags "-s -w" -o sftpgo
```

**Comment by drakkan** [comment]
Anyway the test cases pass, so the login works in travis, this is strange.

Does it work on your pc without docker? Can you please share your dockerfile too?

**Comment by mcdappdev** [comment]
Ok, I will try reverting that commit. I actually ended up not running it via docker, so it is just running normally via supervisor on a linux AWS instance.

**Comment by drakkan** [comment]
Do you have the old version that worked before?

**Comment by mcdappdev** [comment]
Oh weird, I think I just discovered the root of the problem, I can ssh into the DNS name provided by AWS but not into the one on my domain. (i.e. sftp.mydomain.com)

**Comment by drakkan** [comment]
anyway this seems a disconnect msg

https://github.com/golang/crypto/blob/master/ssh/messages.go#L40

with a wrong/missing Language field, probably the client disconnects for timeout and/or other reasons. For example

```
ping sftp.mydomain.com
```
is able to resolve the dns name to an ip address?

**Comment by mcdappdev** [comment]
I got it working! Thanks :)

**Comment by drakkan** [comment]
Great! Thanks for reporting back. So this is unrelated to sftpgo itself, am I right?

**Comment by mcdappdev** [comment]
Correct, it was related to Cloudflare not liking traffic on port 22 :)
