### ISSUE TITLE
dynamic fields

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#262]
Hi, it would be really handy if sftpgo exposed some fields: username (maybe tomorrow the group name) and password in some highlights of the configuration. For example in the s3 backend in the fields:

bucket:%username
accessKey:%username
Access Secret:%password
Prefix:%username or %groupname

by doing so, the same credentials can be forwarded to the backend for dynamic mapping and authentication.

**Comment by drakkan** [comment]
Hi,

I don't like to replace values at runtime sorry, 

However replacement is supported in [templates](https://github.com/drakkan/sftpgo/commit/54321c524044559cbe30008c9e527cbd3f56eae0). 

You can create multiple users from a template and dynamic fields are supported in this case

![Schermata del 2021-01-25 21-36-43](https://user-images.githubusercontent.com/553263/105763013-7ed9e480-5f55-11eb-9148-82b1dfc38f50.png)

**Comment by fdefilippo** [comment]
Hi, it would have been very useful in situations where sftpgo acts as a proxy to an internal sftp and with a single definition it could have been mapped.

**Comment by drakkan** [comment]
I cannot satisfy every use case sorry, runtime variable substitution can be dangerous and I think that using external auth you can do what you [describe](https://github.com/drakkan/sftpgo/blob/master/dataprovider/dataprovider.go#L2110)
