### ISSUE TITLE
webdav & mTLS 

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#263]
Hi, webdav with basic authentication is very weak, it would be advisable to be able to carry out mutual authentication by introducing a few simple variables: "x509_auth": true and "ca_path": /path/to/ca so we can have strong auth.

```
caCert, _ := ioutil.ReadFile(ca_path)
caCertPool := x509.NewCertPool()
caCertPool.AppendCertsFromPEM(caCert)

tlsConfig := &tls.Config{
    ClientCAs: caCertPool,
    ClientAuth: tls.RequireAndVerifyClientCert,
}
tlsConfig.BuildNameToCertificate()
```

😃

**Comment by drakkan** [comment]
Hi,

I think it is more than the code snippet you pasted above, I think we have to do the tls handshake inside sftpgo itself to be able to extract to client certificate info and associate them to a sftpgo user in some way. Do you want to try to send a PR? Thank you

**Comment by fdefilippo** [comment]
Hi, I did not think that the 4 lines could serve for what is requested 😋 at the moment it would be interesting to accept only connections coming from clients that have certificates generated by the internal CA, tomorrow it can be extended to verify the match between username and some regex of certificate dn.

**Comment by drakkan** [comment]
Hi,

if we use only the certificate to authenticate a client, we have, in some way, get the sftpgo user that match a given certificate to get the home dir etc.. I think we could easily have a client certificate + basic auth (not tested) but this could create issue to some clients. Does this work with IE? 

I think we should have something similar to the public key auth for sftp/ssh and optionally require cert+password, this could be applied to FTP too.

I haven't analyzed this feature in detail, I could be wrong

**Comment by fdefilippo** [comment]
Hi, yes obviously I explained badly sorry:
client auth (certificates) +
basic auth

**Comment by drakkan** [comment]
Hi,

I think I'll add something similar for FTP too.

Before reporting issues please test using something simple like this:

```
curl -k --anyauth --cert client.crt --key client.key  "https://b:password@localhost:10443/b/file.txt"
```

**Comment by drakkan** [comment]
while supporting client certificate authentication is quite easy it seems there isn't anything built-in in Go to check the certificate against a revocation list ...

**Comment by fdefilippo** [comment]
https://github.com/cloudflare/cfssl/blob/master/revoke/revoke.go

**Comment by drakkan** [comment]
I saw that but I'm not sure I want implement it, at least for now, sorry

**Comment by fdefilippo** [comment]
ok thank you.

**Comment by fdefilippo** [comment]
Hi, at the moment all tests are ok:

$ curl -k -ufdefilippo:WRONG_PASSWORD https://192.168.3.10:2080/
curl: (55) SSL_write() returned SYSCALL, errno = 104
$ curl --cert francesco\@defilippo.org-client.pem --key francesco\@defilippo.org-client-key.pem -k -ufdefilippo:WRONG_PASSWORD https://192.168.3.10:2080/
Unauthorized
$ curl --cert francesco\@defilippo.org-client.pem --key francesco\@defilippo.org-client-key.pem -k -ufdefilippo:PASSWORD -X PROPFIND https://192.168.3.10:2080/fdefilippo
<?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:">

**Comment by fdefilippo** [comment]
maybe in the future we will be able to generate certificates from the management web interface.

https://shaneutt.com/blog/golang-ca-and-signed-cert-go/

**Comment by drakkan** [comment]
Hi,

while this is technically possibile this seems out of the scope here, there are already several projects providing a CA, for example:

https://github.com/smallstep/certificates
https://github.com/OpenVPN/easy-rsa
https://github.com/square/certstrap
https://github.com/google/easypki
https://github.com/FiloSottile/mkcert

I don't want to get the not-invented-here syndrome :)

Some user already think I'm adding too many features, see for example the comment in #260 or the comments for the 1.2.0 release on reddit.

I think you have to use an external tool to manage a private CA

**Comment by fdefilippo** [comment]
you're right maybe it's out of scope sorry but when I get carried away they just escape :)
