### ISSUE TITLE
SFTP: Not able to set multiple users and their respective passwords 

### ISSUE THREAD

**Issue by vishal1504** [drakkan/sftpgo#270]
Hello,

I want to set multiple sftp username, user-specific directory path, and their respective passwords, but could not able to do that.
Not found any sample examples for sftp user configuration(UserName, Password, and User Working Directory).

Please someone help me out, how to configure/parse(steps) the sftp users info?

**Comment by drakkan** [comment]
Hi,

After starting SFTPGo you can manage users and folders using:

- the [web based administration interface](https://github.com/drakkan/sftpgo/blob/master/docs/web-admin.md)
- the [REST API](https://github.com/drakkan/sftpgo/blob/master/docs/rest-api.md)
- the sample [REST API CLI](https://github.com/drakkan/sftpgo/tree/master/examples/rest-api-cli)

SFTPGo uses virtual users unrelated to the system users

**Comment by vishal1504** [comment]
Thanks, drakkan, this works for me.

**Comment by drakkan** [comment]
Thank you for confirming

**Comment by vishal1504** [comment]
Drakkan, Is there any way to parse user configuration through configuration file?

**Comment by drakkan** [comment]
you can load initial data, take a look [here](https://github.com/drakkan/sftpgo/tree/master/docker#loading-initial-data).

If you use the memory provider the initial data must be loaded each time sftpgo starts, if you use a provider different from `memory` you need to load your users only once.

You can create a user dump manually (it is a json file) or you can get a dump using the rest api.

**Comment by vishal1504** [comment]
thanks, drakkan.
