### ISSUE TITLE
How to map sftpgo user to system user? 

### ISSUE THREAD

**Issue by BilalBudhani** [drakkan/sftpgo#271]
Hello, 

Thank you for this great tool. 

I'm trying to set up where sftpgo user is mapped to the respective system user instead of `sftpgo` user. I found the following feature in the README but couldn't find any documentation on how to configure it

> Per user files/folders ownership mapping: you can map all the users to the system account that runs SFTPGo (all platforms are supported) or you can run SFTPGo as root user and map each user or group of users to a different system account (*NIX only).

basically, I want sftpgo's `userA` to be mapped as Ubuntu's `userA` so all the commands executed via SFTP has `userA` as an owner and it should be inside `/home/userA` folder. 

Any idea on how it can be done?

**Comment by drakkan** [comment]
Hi,

assuming you are on *NIX, if you run sftpgo as a non root user, for example the `sftpgo` user, all the uploaded files will be owned by the `sftpgo` user.

If you run SFTPGo as root user, for each SFTPGo virtual user you can set a specific UID/GID:

![Schermata del 2021-01-04 12-39-07](https://user-images.githubusercontent.com/553263/103531569-eb4b5180-4e89-11eb-84eb-844689949d5d.png)

for example if `userA` has uid 1000 and gid 1001 on you system, you can configure these values for your SFTPGo virtual user and then set its home dir to `/home/userA`. 

I'm not a big fan of this mode, I prefer pure virtual users, however it should work, thank you

**Comment by BilalBudhani** [comment]
Hey @drakkan, 

Thanks! This works perfectly fine now. I'm now able to map the user with Ubuntu's system user. 

Can you share more thoughts on why you don't prefer this solution? Also, Initially, I tried using virtual user setup, but then, my webserver (Caddy) couldn't access files inside `/srv/sftpgo/data`. Do you have any ideas on how I could make it work with pure virtual user setup?

**Comment by drakkan** [comment]
> Hey @drakkan,
> 
> Thanks! This works perfectly fine now. I'm now able to map the user with Ubuntu's system user.
> 
> Can you share more thoughts on why you don't prefer this solution? 

- you have to run SFTPGo as root user and this could be a security risk
- you have to add a system user for each virtual user and map it
- this mode is not portable, it works on *NIX only

> Also, Initially, I tried using virtual user setup, but then, my webserver (Caddy) couldn't access files inside `/srv/sftpgo/data`. Do you have any ideas on how I could make it work with pure virtual user setup?

By default the virtual users have a home dir inside `/srv/sftpgo` this folder is only accessible to the sftpgo user and group

```shell
stat /srv/sftpgo
  File: /srv/sftpgo
  Dim.: 4096      	Blocchi: 8          Blocco di IO: 4096   directory
Device: 10302h/66306d	Inode: 10371648    Coll.: 4
Accesso: (0750/drwxr-x---)  Uid: (  315/  sftpgo)   Gid: (  315/  sftpgo)
Accesso  : 2021-01-04 13:28:45.754476530 +0100
Modifica : 2020-10-15 10:24:49.666422269 +0200
Cambio   : 2020-10-15 10:24:49.666422269 +0200
Creazione: 2020-10-15 10:20:22.331705654 +0200
```

you can likely fix the reported issue adding the user that run caddy to the sftpgo group for a read only access or you can set the home dir for your SFTPGo virtual users to a filesystem path accessible to both `caddy` and `sftpgo` system user.

You can choose the setup that better fit your needs regardless of my personal preference

**Comment by BilalBudhani** [comment]
Thank you @drakkan for providing such insightful solutions. I got everything I was looking for. Have a good day.
