### ISSUE TITLE
sftpgo: facing application building issue while importing sftpgo as a libs/modules

### ISSUE THREAD

**Issue by vishal1504** [drakkan/sftpgo#272]
Hi,

I want to start the sftpgo server through my application, but facing an issue while importing the "github.com/drakkan/sftpgo" modules.

So, I have a question, **Can we use this sftpgo as libs/module? If yes, then How?**

I've listed below a few of the issues while building the application with importing sftpgo mod.
**Sample main.go** :
package main 

import (
        "fmt"

        "github.com/drakkan/sftpgo/cmd"
)

func main() {
        fmt.Println("Testing sftgo pkgs")
        cmd.Execute()
}

**List of Error:**
**1.**
 github.com/drakkan/sftpgo/vfs
/root/go/src/github.com/drakkan/sftpgo/vfs/sftpfs.go:167:2: cannot use f (type *sftp.File) as type File in return argument:
        *sftp.File does not implement File (missing WriteAt method)
/root/go/src/github.com/drakkan/sftpgo/vfs/sftpfs.go:178:10: cannot assign *sftp.File to f (type File) in multiple assignment:
        *sftp.File does not implement File (missing WriteAt method)
/root/go/src/github.com/drakkan/sftpgo/vfs/sftpfs.go:180:10: cannot assign *sftp.File to f (type File) in multiple assignment:
        *sftp.File does not implement File (missing WriteAt method)

**2.**
[root@centos7Venu test1]# go build -o sftp main.go
package command-line-arguments
        imports github.com/drakkan/sftpgo
        imports github.com/drakkan/sftpgo: import cycle not allowed

**3.**
[root@centos7Venu sftp]# go build -o sftp sftpserver.go
 github.com/drakkan/sftpgo/sftpd
/root/go/pkg/mod/github.com/drakkan/sftpgo@v1.2.2/sftpd/server.go:137:14: undefined: ssh.ErrPartialSuccess
/root/go/pkg/mod/github.com/drakkan/sftpgo@v1.2.2/sftpd/server.go:146:3: unknown field 'NextAuthMethodsCallback' in struct literal of type ssh.ServerConfig
/root/go/pkg/mod/github.com/drakkan/sftpgo@v1.2.2/sftpd/server.go:439:49: conn.PartialSuccessMethods undefined (type ssh.ConnMetadata has no field or method PartialSuccessMethods)
/root/go/pkg/mod/github.com/drakkan/sftpgo@v1.2.2/sftpd/server.go:667:21: undefined: ssh.ErrPartialSuccess
/root/go/pkg/mod/github.com/drakkan/sftpgo@v1.2.2/sftpd/server.go:691:13: conn.PartialSuccessMethods undefined (type ssh.ConnMetadata has no field or method PartialSuccessMethods)
/root/go/pkg/mod/github.com/drakkan/sftpgo@v1.2.2/sftpd/server.go:708:13: conn.PartialSuccessMethods undefined (type ssh.ConnMetadata has no field or method PartialSuccessMethods)

**please guide me on this.**

**Comment by drakkan** [comment]
Hi,

first of all please note that SFTPGo is a GPLv3 software, if you want to use SFTPGo inside your application you must be sure to respect the [license](https://www.google.com/search?q=gplv3+obligations).

You have the errors posted above because sftpgo uses custom versions for some [packages](https://github.com/drakkan/sftpgo/blob/master/go.mod#L65) to support features not yet available upstream, you have to use the same forks inside your application

**Comment by vishal1504** [comment]
thanks for the clarifications.
