### ISSUE TITLE
SFTP: Facing issue while parsing .json config file to process inside the container.

### ISSUE THREAD

**Issue by vsangale** [drakkan/sftpgo#273]
Hello,

Container: Facing issue while parsing sftpgo.json config file to sftp service, it's taking default config file.

Error::
{"level":"info","time":"2021-01-08T06:22:17.744","sender":"service","message":"starting SFTPGo 1.2.2 +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: /app, config file: /app/sftpgo.json, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, profile: false load data from: \"\""}
{"level":"warn","time":"2021-01-08T05:57:45.439","sender":"config",**"message":"error loading configuration file:** Config File \"sftpgo.json\" Not Found in \"[/app /root/.config/sftpgo  /etc/sftpgo]\""}

Approach 1:
I've set the environment variables appropriately inside the containers as well, but still facing this issue.

Environment :
SFTPGO_CONFIG_DIR=/app/
HOSTNAME=centos7Venu
SFTPGO_CONFIG_FILE=sftpgo.json

Approach 2: Parsing --config-file parameter through command line but showing me the same error.
./sftpgo serve --config-file sftpgo.json

Note:
Checked inside the container file is present in the appropriate location and also verified the permissions
bash-5.0# ls -lrt
total 39992
-rw-r--r--    1 root     root          3841 Jan  8 05:53 **sftpgo.json**
-rwxr-xr-x    1 root     root      40868216 Jan  8 06:29 sftpserver
drwxr-xr-x    2 root     root           160 Jan  8 06:29 templates
drwxr-xr-x    5 root     root            60 Jan  8 06:29 static
drwx------    2 root     root             6 Jan  8 06:31 credentials
-rw-r--r--    1 root     root         45056 Jan  8 06:31 sftpgo.db
-rw-r--r--    1 root     root          7432 Jan  8 06:31 sftpgo.log
-rw-------    1 root     root           725 Jan  8 06:31 id_rsa.pub
-rw-------    1 root     root          3243 Jan  8 06:31 id_rsa
-rw-------    1 root     root            81 Jan  8 06:31 id_ed25519.pub
-rw-------    1 root     root           119 Jan  8 06:31 id_ed25519
-rw-------    1 root     root           161 Jan  8 06:31 id_ecdsa.pub
-rw-------    1 root     root           227 Jan  8 06:31 id_ecdsa

please could you help me to understand, what goes wrong?

Is there any way to disable the picking default configuration option?

**Comment by sagikazarmark** [comment]
You are using SFTPGo 1.2.2 which works slightly differently than HEAD: https://github.com/drakkan/sftpgo/blob/v1.2.2/docs/full-configuration.md

Try this: `SFTPGO_CONFIG_FILE=sftpgo` (or you can omit this setting completely)

**Comment by vsangale** [comment]
@sagikazarmark,

Thanks for the reply, 

Yes, I understood that difference after a debugging sftpgo module.
This solution is working for me, please close the issue.
