### ISSUE TITLE
Question,About "auth_user_file"

### ISSUE THREAD

**Issue by momo8zero** [drakkan/sftpgo#274]
hi 
I want to use REST Api to control sFtpgo server,
and I generated java-cli-client ,about the Basic auth,can you take me the example thanks !!

**Comment by drakkan** [comment]
Hi,

you have to generate the basic auth file using a tool like `htpasswd`, for example:

```
htpasswd -c authfile username
```

please note that I'm reworking this part, in the next days / weeks I will send a commit to store admin users directly inside the data provider and the REST API will require a JWT.

The auth user file will be not required anymore, maybe you could wait for these changes before your integration

**Comment by momo8zero** [comment]
okay, i will continue follow up
 thank you ~ :)

**Comment by drakkan** [comment]
Hi,

JWT auth is now available, please let me know if you find any issues, thank you
