### ISSUE TITLE
S3: stat potentially paginates through thousands of objects to find zero-byte-keyed dirs

### ISSUE THREAD

**Issue by trapped** [drakkan/sftpgo#275]
For context, I'm using the S3 storage backend pointed at a custom S3-compatible server (Backblaze B2) with the SFTP frontend. The bucket contains millions of files amounting to tens of TBs of data.
Clients connect via SFTP, create a new directory and upload a few files in there.

`Mkdir()` at root level *consistently* times out (`error creating dir: "/testdir" error: RequestCanceled: request context canceled; caused by: context deadline exceeded`), looking for zero-byte-keyed dirs through `Stat()` first:

https://github.com/drakkan/sftpgo/blob/a8a17a223a0bc35941366c8b462fa7ceaff9bfdb/vfs/s3fs.go#L123-L131

it then calls `getStatCompat()`, which ends up paginating through **all** files in the bucket (if the directory doesn't yet exist):

https://github.com/drakkan/sftpgo/blob/a8a17a223a0bc35941366c8b462fa7ceaff9bfdb/vfs/s3fs.go#L139-L142

Looking at the code it seems like `getStatCompat()` is only used for finding the aforementioned zero-byte keyed objects; is there any reason not to simply `HEAD <name>/`, which correctly returns metadata for zero-byte keys?

I've implemented the change to `Stat()` in a local branch and it works fine; if there aren't any edge cases or incompatibilities that `getStatCompat()` already accounts for I'll happily submit it in a PR.

Thanks!

**Comment by drakkan** [comment]
Hi,

`getStatCompat()` is there only for backward compatibility because initially we created "directories" as keys with a `/` suffix, we set the content type to `inode/directory` now, this method should be removed in future, for now a `HEAD <name>/` is ok, please submit a PR, thank you!

**Comment by trapped** [comment]
Ah, I see then. Do you think we should explicitly check that `Content-Type` is `inode/directory` and `Content-Size` is `0` before treating the object as a directory?

Also, PR open: #276

**Comment by drakkan** [comment]
> Ah, I see then. Do you think we should explicitly check that `Content-Type` is `inode/directory` and `Content-Size` is `0` before treating the object as a directory?
> 

we should do something like [this](https://github.com/drakkan/sftpgo/blob/master/vfs/gcsfs.go#L122)

> Also, PR open: #276
