### ISSUE TITLE
Rest API via Postman or Curl

### ISSUE THREAD

**Issue by ajksharma** [drakkan/sftpgo#28]
Hi,

I used the python rest client and was successful in creating users.

Is it possible to use the rest api via curl or postman?

I tried calling curl http://localhost:8080/add_user?username=test_username&password=test_pwd&home_dir=/tmp/test_home_dir&uid=33&gid=1000&max_sessions=2&quota_size=0&quota_files=3&permissions='*'&upload_bandwidth=100&download_bandwidth=60

but got an error  {"error":"","message":"Not Found","status":404}

Thanks,

Ajay

**Comment by drakkan** [comment]
Hi,

yes it is possibile but you need to read the OpenAPI schema and do the right requests :)

To add an user the request should be an http POST and not a GET and the parameters should be passed in the POST body as json.

For example this should work to add an user:

```
curl --verbose -H "Content-Type: application/json" -d '{"id": 0, "username": "test_username", "home_dir": "/tmp/test_home_dir", "uid": 33, "gid": 1000, "max_sessions": 2, "quota_size": 0, "quota_files": 3, "permissions": ["list", "download", "upload", "delete", "rename", "create_dirs"], "upload_bandwidth": 100, "download_bandwidth": 6, "password": "test_pwd"}' http://127.0.0.1:8080/api/v1/user
``` 

You can also try an openapi generator tool such as `swagger-codegen` or `openapi-generator`

For example, this command:

```
openapi-generator-cli generate -i https://raw.githubusercontent.com/drakkan/sftpgo/master/api/schema/openapi.yaml -g bash -o /tmp/client
```

will generate a REST API client in /tmp/client as bash scripts using curl.

In the coming weeks I'll add a CLI, similar to the python client, directly inside `sftpgo` command, will this be useful for your use case? What's wrong for you with the python client? 

Thank you in advance for your feedbacks, you'll help me to improve SFTPGo

**Comment by ajksharma** [comment]
Hi Drakkan,

The curl requests works! Thanks! 

The curl & the python sftp client works with a local sftpgo server only. (that is if the sftpgo server is on aws and I execute these clients on my local machine it doesn't work)

Is this by design? or I am doing something wrong?

> In the coming weeks I'll add a CLI, similar to the python client, directly inside sftpgo command, will this be useful for your use case? What's wrong for you with the python client?

I am not sure.  I need to use the api remotely from a web page that could be on another server.

So here are my use cases.

**Use Case 1:**
From a web page I need to enter user details like their 
1. username/pwd, 
2. user directory (auto-created if it doesn't exist ) 

Press the submit button on the web page and the user gets created on the sftpgo server.

This would be a http post request of course.

Also can we create more than one directory for the user? User directories should be auto-created if they don't exist..

**Use Case 2:**

Bulks users creation via csv file.

This could be web based or using the cli client.

I guess the second use-case can be done with the existing python client though it would be handy if we could do it through a file upload on a web page.

Thanks for creating a great software! Appreciate your hard work.

- Ajay

**Comment by drakkan** [comment]
Hi,

the python cli can already connect to a remote server, please try to set a base_url like this:

```
python sftpgo_api_cli.py  --base_url "http://192.168.1.1:8080" get_users
```

on the remote server you need to be sure that the REST API is not listening on localhost only (default configuration). In the config file change the following section as you need

```
"httpd": {
    "bind_port": 8080,
    "bind_address": "127.0.0.1"
  }
```
After the configuration change you need to restart sftpgo. You can read the loaded configuration inside the log files.

Anyway I think a better approach would be to leave the REST API available on localhost only and setup a reverse proxy so you can configure encryption and authentication too.

The user directory is autocreated on the first login if it does not exist and if the user that runs sftpgo has the permissions to create it.

Each user has an home directory, for example `/home/user`. It can create any numbers of directories inside `/home/user`, for example `/home/user/test1`, `/home/user/test1/test2`, `/home/user/test2` and so on but it cannot create directories outside `/home/user`, for example `/home/test` will not be allowed.

An integrated web interface is not planned anytime soon, sorry. But you can easily create your own web interface using the REST API

**Comment by ajksharma** [comment]
Hi Drakkan,

Yes the python cli is working now from my localhost to a remote server. Though there is no authentication.

Regarding the reverse proxy does anyone has a sample file?

Thanks,

Ajay

**Comment by drakkan** [comment]
You can for example configure apache this way:

```
ProxyPass /api/v1 http://127.0.0.1:8080/api/v1
ProxyPassReverse /api/v1 http://127.0.0.1:8080/api/v1
```

if your apache instance listen on port 80 you can connect for example to:

```
http(s)://<remote_ip>/api/v1/user
```

and the request is served by sftpgo listening on 127.0.0.1:8080

Regarding authentication you can easily add it to apache, for example:

```
<Location /api/v1>
	AuthType Digest 
	AuthName "Private"
	AuthBasicProvider file
	AuthUserFile "/etc/httpd/conf/auth_digest"
	Require valid-user
</Location>
```

if you configure authentication you need to instruct the python client to authenticate, for example:

```
python sftpgo_api_cli.py --base_url "http://192.168.1.1:80" --auth_type digest --auth_user=username --auth_password=password get_users
```
HTTP servers such as apache, ngnix ecc.. have a lot of configuration options, please refer to their support channel if you need further helpm thanks!

**Comment by ajksharma** [comment]
Thanks, I would try this & report back

**Comment by drakkan** [comment]
I added this info to the README too,

please note that I just pushed some breaking changes, if you update to the last version you need:

1) execute the database migration script
2) change the launch command to something like this `sftpgo serve` and then add the other arguments as before
3) rename the config file from sftpgo.conf to sftpgo.json (yaml, toml ecc.. are supported too, please take a look at the updated README)

thanks and sorry for the annoyance
