### ISSUE TITLE
Dynamic Sub-dirs

### ISSUE THREAD

**Issue by IoannMelnychuk** [drakkan/sftpgo#284]
Hello, is it possible to pre-create multiple folders in user home-directory?
I've tried to add permissions for sub-dirs, but home-directory is still empty.
Thanks :)

**Comment by drakkan** [comment]
Hi,

you have to create them yourself, once the directories are created the defined virtual permissions are applied

**Comment by sagikazarmark** [comment]
Maybe using hooks for this could be a solution?

**Comment by drakkan** [comment]
Yes, you can use one of the available hooks, for example

https://github.com/drakkan/sftpgo/blob/master/docs/dynamic-user-mod.md

**Comment by IoannMelnychuk** [comment]
@drakkan, cool thank you :)

**Comment by drakkan** [comment]
> @drakkan, cool thank you :)

if you use a script as `add_user` hook you will be unable to get the permissions and so the directories to create. Using an HTTP hook you will get the full user json serialized. 

I'll add a new env var containing the full user, JSON serialized, for the script hook too

**Comment by IoannMelnychuk** [comment]
@drakkan no worries, it's kind of static folders - same across all users :)
Thank you for help

**Comment by IoannMelnychuk** [comment]
@drakkan one more question - will the `add_user` script be called if I use external auth endpoint?

**Comment by drakkan** [comment]
> @drakkan one more question - will the `add_user` script be called if I use external auth endpoint?

No, it will not be called in this [case](https://github.com/drakkan/sftpgo/blob/master/docs/external-auth.md) but if you create the user yourself you could create all the required directories inside the external auth hook itself

**Comment by IoannMelnychuk** [comment]
@drakkan is it possible to get user info on `post-login` hook? https://github.com/drakkan/sftpgo/blob/master/docs/post-login-hook.md

**Comment by drakkan** [comment]
I'll evaluate your request.

Can you confirm that you only need the home directory for your use case?

P.S. out of curiosity what kind of backend do you integrate using external authentication? Thank you

**Comment by IoannMelnychuk** [comment]
@drakkan awesome, thank you, much appreciate it.
Yeah, just home directory will be enough

It is external http endpoint (most likely won't have access to sftp filesystem)

**Comment by drakkan** [comment]
Hi,

please try this simple python script as pre-login hook

```
#!/usr/bin/env python

import json
import os
import sys

user = json.loads(os.environ.get("SFTPGO_LOGIND_USER", ""))

# id is 0 if the user does not exist
if user['id'] > 0:
	home_dir = user['home_dir']
	mydir = os.path.join(home_dir, "mydir")
	os.makedirs(mydir, exist_ok=True)

sys.exit(0)
```

before the end of this week I will decide whether to add more information to the post-login hook as well
