### ISSUE TITLE
can't login with public key after updating to the latest code and updating database

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#29]
I just updated my test setup to the latest master, and ran the sql update line:

```sql
ALTER TABLE "users" RENAME COLUMN "public_key" TO "public_keys";
```

Now I can no longer login with the existing keys.

I reverted to the commit `5ad222fc53c01339b2acecd6849555b7006825b1`: it works.
I cherry-pick `5ad222fc53c01339b2acecd6849555b7006825b1` and run the SQL line: it no longer works.

Should I change something else?

**Comment by jovandeginste** [comment]
OK I see that now the `public_keys` column should be a JSON array. I'll update my database.

**Comment by drakkan** [comment]
Yes I removed the compatibility code

https://github.com/drakkan/sftpgo/commit/2aca4479a5cf7c740db63302d7f4fabaecec7907#diff-13e21084e0dc4eee371c19825c4c597dL284

sorry for the annoyance

**Comment by jovandeginste** [comment]
To anyone who needs to convert, this is for MySQL, might work on other database products:

```sql
update users set public_keys=concat("[\"",replace(public_keys, "\n", "\",\""),"\"]") WHERE public_keys like "%\n%";
```
