### ISSUE TITLE
How to use SFTP backend for SFTP only remote host

### ISSUE THREAD

**Issue by kevin39** [drakkan/sftpgo#292]
Hi,
I'm using the master branch for my tests.

I'm trying to setup an user with SFTP backend but I can't use it properly.

I found this error in logs : 
`Feb  2 21:40:54 utils sftpgo[6157]: {"level":"debug","time":"2021-02-02T21:40:54.438","sender":"connection_failed","client_ip":"::1","username":"XXX","login_type":"publickey","protocol":"SSH","error":"invalid credentials"}`

But my setup is particular : My remote server doesn't allow SSH connection. Only SFTP is allowed and I think SFTPgo is trying to use SSH to connect to the backend.

Some example about my remote server : 

```
# Direct SFTP to remote allowed 
root@utils:/var/log# sftp <remote_user>@<remote server>
<remote_user>@<remote server>'s password:
Connected to <remote server>.
sftp>

# But SSH denied (normal behavior, this server doesn't allow SSH)
root@utils:/var/log# ssh <remote_user>@<remote server>
<remote user>@<remote server>s password:

Connection to <remote server> closed.
root@utils:/var/log#
```

Hope I'm clear about my issue, sorry my english isn't perfect.

edit : or maybe the remote auth is really failing but I'm sure my sftp's id are working. Maybe something is wrong in the sftp's db ? I used the web gui.

edit : Tried to setup my user with and without remote private key -> same behavior
In case it's useful, here the filesystem part of my user, everything seems fine

```
 "filesystem": {
      "provider": 5,
      "s3config": {
        "access_secret": {}
      },
      "gcsconfig": {
        "credentials": {}
      },
      "azblobconfig": {
        "account_key": {}
      },
      "cryptconfig": {
        "passphrase": {}
      },
      "sftpconfig": {
        "endpoint": "<remote server>"
        "username": "<remote user>",
        "password": {
          "status": "Secretbox",
          "payload": "IsuvqFW3rCsFVHSJoikCWLmccJTutk9LyypbHRefGrPzFf2ZjIPmjjjv+hwEDuz6qq+wnw=="
        },
        "private_key": {},
        "prefix": "/"
      }
```

edit 3 : I don't know how my host is filtering sftp vs ssh, so I tried sshfs and my remote server is mouting properly... so I think the problem is really on the sftpgo's side. Well, I don't know what I can do. I'll wait your reply. Thanks.

Thanks

**Comment by drakkan** [comment]
Hi,

is the endpoint in the form [host:port](https://github.com/drakkan/sftpgo/blob/master/httpd/schema/openapi.yaml#L1503)? Port is always required, I'll add an hint to the web ui.

If that's not the problem, can you try using a local SFTPGo account itself as the endpoint? So you can compare the logs.

Is your sftp server something I can install and test on my own? thank you

**Comment by kevin39** [comment]
HI,
No, I didn't set the port ! 
I can't test right now, I will be back to you this evening or tomorrow.

Thanks

**Comment by drakkan** [comment]
Hi,

you are right, if the port is missing nothing useful is logged. I improved the [logs](https://github.com/drakkan/sftpgo/commit/1cde50f05070c0b533b6c30aa1368eb4ed73e02a). You should get something like this now:

```
{"level":"debug","time":"2021-02-03T09:44:44.132","sender":"sftpd","connection_id":"6bf4de45eb464a9a950495a410427186d3a956c20c25178cc2ccd4ef7bac6ca1_1","message":"unable to create filesystem: dial tcp: address 127.0.0.1: missing port in address"}
```

thanks

**Comment by kevin39** [comment]
Yeah :)
Issue fixed by adding the port... That was so easy ^^

Thanks
