### ISSUE TITLE
Move webDav home directory to /

### ISSUE THREAD

**Issue by Flameborn** [drakkan/sftpgo#293]
Currently, the root/home directory for each user is under their username, e.g. *https://IP:WebDavPort/UserName/*

Would it be possible to move this root directory one level up, e.g to *https://IP:WebDavPort/*?

As it stands, the redirects are not followed by most WebDav clients, such as Cadaver, LFTP, CarrotDAV, or Finder in MacOS.

**Comment by drakkan** [comment]
Hi,

could you please better explain why it is an issue to add the username to the path? For example #294 has nothing to do with the path. 

I think it is quite common to have webdav for a subdir and not the whole root.

For SFTPGo it was initially designed this way as webdav requires a file path based locking file system. By prefixing the username, we guarantee unique paths. We currently no longer use a global lock filesystem, each user has its own but a such switch will still require a discrete amount of work and it will break existing setups

**Comment by Flameborn** [comment]
There are several reasons:

1. By not requiring to specify the username in the URL, WebDav  will mirror the behavior of FTP/SFTP.
2. The root */* is never used at the moment.
3. When the WebDav traffic is proxied, e.g. to be accessed via a subdomain having HTTPS enabled, each user needs to have their proxy path defined, in case the root domain needs to be reserved, for example for CardDav and CalDav. By each user being uniformly accessible through the root URL, this can be completely avoided.
4. Similarly, a common CardDav/CalDav directory currently cannot be specified for users, for example to facilitate group sharing, unless a common home directory is used.

**Comment by drakkan** [comment]
> There are several reasons:
> 
> 1. By not requiring to specify the username in the URL, WebDav  will mirror the behavior of FTP/SFTP.
> 2. The root _/_ is never used at the moment.

these points are valid and these are the reasons why i'm thinking about this switch too

> 3. When the WebDav traffic is proxied, e.g. to be accessed via a subdomain having HTTPS enabled, each user needs to have their proxy path defined, in case the root domain needs to be reserved, for example for CardDav and CalDav. By each user being uniformly accessible through the root URL, this can be completely avoided.

> 4. Similarly, a common CardDav/CalDav directory currently cannot be specified for users, for example to facilitate group sharing, unless a common home directory is used.

I'm not sure to understand here, each user will see its own files as for SFTP/FTP if you want to share the same files you have to set a common home dir anyway

**Comment by Flameborn** [comment]
> I'm not sure to understand here, each user will see its own files as for SFTP/FTP if you want to share the same files you have to set a common home dir anyway

That is true. But a CardDav/CalDav client would commonly use HTTPS to access resources. At the moment, this is different for each user, as the prefixes need to be handled externally, i.e. 2 or more users can't just access the same resources via the root URL as a group.

**Comment by Flameborn** [comment]
Thank you very much for taking the time to fix this.

**Comment by drakkan** [comment]
I was thinking about this change myself since a while, my main concern was backward compatibility but since current git master will be released as v2.0.0 soon we can break compatibility now.

Please let me know if it works as expected, thank you

**Comment by Flameborn** [comment]
Ah, just in time then indeed ☺️

I've checked against 17a42a0c119b69882a88c13650fb135dbb9edaba, it seems to be working as expected. Thank you very much again.
