### ISSUE TITLE
WebDav: Allow HEAD method by default

### ISSUE THREAD

**Issue by Flameborn** [drakkan/sftpgo#294]
Some WebDav clients, such as LFTP require the *HEAD* method to be allowed when connecting to a WebDav server. Is it possible to make this available by default?

**Comment by drakkan** [comment]
Hi,

HEAD should work, can you please post some network traces that show the difference with another implementation? 

I suggest to use git master if you are testing webdav, thank you

**Comment by Flameborn** [comment]
Hello,

This is what happens when connecting via LFTP:

```
HEAD /TestUser HTTP/1.1
Host: 192.168.1.48:8082
User-Agent: lftp/4.9.2
Accept: */*
Authorization: Basic XXX
Connection: keep-alive
```

SFTPGo returns:

```
HTTP/1.1 405 Method Not Allowed
Date: Wed, 03 Feb 2021 17:03:37 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```

I unfortunately don't have a test webDav server to compare, but from what I can remember, the *HEAD* method is usually something similar to a *GET* method, returning a directory index minus the response body.

I am suspecting that the *HEAD* request is sent for the root directory in this case.

**Comment by Flameborn** [comment]
Thank you very much.

This fixes connecting to WebDav with all the mentioned clients where it was problematic before.
