### ISSUE TITLE
sftpgo v.2.0.0 mysql

### ISSUE THREAD

**Issue by mcvoigt** [drakkan/sftpgo#298]
Hi, 
Follows the error when I try to use with mysql

![sftpgo_mysql](https://user-images.githubusercontent.com/13902675/107118553-7be9c880-6860-11eb-8ec9-60941b58e3a9.png)

When I change schema_version to 8 in mysql db, sftpgo starts normally

Thanks,
Michael Voigt

**Comment by drakkan** [comment]
Hi,

can you please specify your mysql version? It seems that this query:

```
UPDATE `folders` f1 SET name = (SELECT CONCAT('folder',f2.id) FROM `folders` f2 WHERE f2.id = f1.id);
```

don't work with your mysql version.

Please ensure that the migration 8 is fully applied or you could have issues using virtual folders, here is the full sql

```
ALTER TABLE `folders` ADD COLUMN `name` varchar(255) NULL;
ALTER TABLE `folders` MODIFY `path` varchar(512) NULL;
ALTER TABLE `folders` DROP INDEX `path`;
UPDATE `folders` f1 SET name = (SELECT CONCAT('folder',f2.id) FROM `folders` f2 WHERE f2.id = f1.id);
ALTER TABLE `folders` MODIFY `name` varchar(255) NOT NULL;
ALTER TABLE `folders` ADD CONSTRAINT `name` UNIQUE (`name`);
```

**Comment by drakkan** [comment]
Hi,

I was able to replicate the issue using mysql 5.6, here are the steps to fix your database

```
UPDATE `folders` f1 SET name = CONCAT('folder',f1.id);
ALTER TABLE `folders` MODIFY `name` varchar(255) NOT NULL;
ALTER TABLE `folders` ADD CONSTRAINT `name` UNIQUE (`name`);
```

so I need to release 2.0.1 :)

**Comment by mcvoigt** [comment]
Hi,

MySQL Version 5.7.17

I made the adjustments and it's ok.

Thank you,
Michael

Em sáb., 6 de fev. de 2021 às 10:29, Nicola Murino <notifications@github.com>
escreveu:
