### ISSUE TITLE
httpd ignoring conf file?

### ISSUE THREAD

**Issue by jungle-boogie** [drakkan/sftpgo#3]
Hello,

My conf file is very similar to your example, except I wanted to test out the httpd API and made the changes below.

```
   "httpd":{
       "bind_port":8000,
           "bind_address": ""
   }
```

1. Even though the port has changed to 8000, nothing answers there and still wants to answer on 8080. Tested with `nc` on the localhost and remote host.

2. Even though I have to listening on all available addresses, nothing answers on remote hosts. Tested with a webbrowser and `nc` on two separate hosts.

Am I doing something wrong? A missing comma, period, quotes?

Thanks!

**Comment by drakkan** [comment]
Hi, 

it seems to work as expected for me, please check the log file (default is sftpgo.log)

you should see this line when the config is loaded

```
{"level":"debug","sender":"config","time":"2019-07-26T11:04.56.991","message":"config loaded: {SFTPD:{BindPort:2022 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0022} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:5432 Username: Password: ConnectionString: UsersTable:users ManageUsers:1 SSLMode:0 TrackQuota:1} HTTPDConfig:{BindPort:8000 BindAddress:}}"}
```

and this one when the http server is started:

```
{"level":"debug","sender":"main","time":"2019-07-26T11:04.56.991","message":"initializing HTTP server with config {BindPort:8000 BindAddress:}"}
```

I'm using this config:

```
{
   "sftpd":{
       "bind_port":2022,
       "bind_address": "",
       "idle_timeout": 15,
       "max_auth_tries": 0,
       "umask": "0022"
   },
   "data_provider": {
       "driver": "sqlite",
       "name": "sftpgo.db",
       "host": "",
       "port": 5432,
       "username": "",
       "password": "",
       "sslmode": 0,
       "connection_string": "",
       "users_table": "users",
       "manage_users": 1,
       "track_quota": 1
   },
   "httpd":{
       "bind_port":8000,
       "bind_address": ""
   }
}
```

the name of the config file must be `sftpgo.conf` and is searched inside config dir (default inside the launching dir),

please check these logs too:

```
{"level":"info","sender":"main","time":"2019-07-26T08:10.12.282","message":"starting SFTPGo, config dir: ."}
{"level":"debug","sender":"config","time":"2019-07-26T08:10.12.282","message":"load config from path: sftpgo.conf"}
```
thanks!

**Comment by jungle-boogie** [comment]
Hi @drakkan,

Well it's working now and my log looks good. Thanks for your input and the example conf file.

Keep up the good work with `sftpgo`

I read about this app on hacker news - so congrats for making it there. :)

best!

**Comment by drakkan** [comment]
Glad to know that it works as expected for you too.

Thanks for letting me know about hacker news discussion, I'm reading it now
