### ISSUE TITLE
Logging with public keys

### ISSUE THREAD

**Issue by ajksharma** [drakkan/sftpgo#30]
Hi drakkan,

Would you have an example of how to create a user with his public key?

Maybe using the python client.

Thanks,

Ajay

**Comment by drakkan** [comment]
Hi,

please take a look at the output of `sftpgo_api_cli.py add-user --help` or `sftpgo_api_cli.py update-user --help`

You can use `--public-keys` options to specify one or more public keys for a given user, so for example if the public key content is

```bash
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC03jj0D+djk7pxIf/0OhrxrchJTRZklofJ1NoIu4752Sq02mdXmarMVsqJ1cAjV5LBVy3D1F5U6XW4rppkXeVtd04Pxb09ehtH0pRRPaoHHlALiJt8CoMpbKYMA8b3KXPPriGxgGomvtU2T2RMURSwOZbMtpsugfjYSWenyYX+VORYhylWnSXL961LTyC21ehd6d6QnW9G7E5hYMITMY9TuQZz3bROYzXiTsgN0+g6Hn7exFQp50p45StUMfV/SftCMdCxlxuyGny2CrN/vfjO7xxOo2uv7q1qm10Q46KPWJQv+pgZ/OfL+EDjy07n5QVSKHlbx+2nT4Q0EgOSQaCTYwn3YjtABfIxWwgAFdyj6YlPulCL22qU4MYhDcA6PSBwDdf8hvxBfvsiHdM+JcSHvv8/VeJhk6CmnZxGY0fxBupov27z3yEO8nAg8k+6PaUiW1MSUfuGMF/ktB8LOstXsEPXSszuyXiOv4DaryOXUiSn7bmRqKcEFlJusO6aZP0= nicola@p1
```

you can use

```
sftpgo_api_cli.py update-user <other parameters> --public-keys "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC03jj0D+djk7pxIf/0OhrxrchJTRZklofJ1NoIu4752Sq02mdXmarMVsqJ1cAjV5LBVy3D1F5U6XW4rppkXeVtd04Pxb09ehtH0pRRPaoHHlALiJt8CoMpbKYMA8b3KXPPriGxgGomvtU2T2RMURSwOZbMtpsugfjYSWenyYX+VORYhylWnSXL961LTyC21ehd6d6QnW9G7E5hYMITMY9TuQZz3bROYzXiTsgN0+g6Hn7exFQp50p45StUMfV/SftCMdCxlxuyGny2CrN/vfjO7xxOo2uv7q1qm10Q46KPWJQv+pgZ/OfL+EDjy07n5QVSKHlbx+2nT4Q0EgOSQaCTYwn3YjtABfIxWwgAFdyj6YlPulCL22qU4MYhDcA6PSBwDdf8hvxBfvsiHdM+JcSHvv8/VeJhk6CmnZxGY0fxBupov27z3yEO8nAg8k+6PaUiW1MSUfuGMF/ktB8LOstXsEPXSszuyXiOv4DaryOXUiSn7bmRqKcEFlJusO6aZP0= nicola@p1" <other parameters>
```

then you should be able to login using the key the same way as you do with openssh

**Comment by drakkan** [comment]
Hi again,

to be more clear, you can create your key pair using `ssh-keygen`, for example:

```bash
ssh-keygen -f /tmp/test_key
```

so you have these files:

```
/tmp/test_key 
/tmp/test_key.pub
```

you  can set the content of `/tmp/test_key.pub` as the public key for a given user and then use the private key to login. 

How to instruct an sftp client to use the key is client specific, for example using the openssh sftp client you can use something like this

```
sftp -P 2222 -i /tmp/test_key <username>@127.0.0.1
```
Please reopen if you find a bug in sftpgo and the public key login does not work as expected, anyway several test cases use public key auth so I think it is really unlikely that we have a bug here
