### ISSUE TITLE
Sub dirs permissions does not work

### ISSUE THREAD

**Issue by mcvoigt** [drakkan/sftpgo#303]
Hi
In the user registration, in the field Sub dirs permissions.
When I edit this field, and save it, when editing again I notice that it returns blank.

Regards,
Michael Voigt

**Comment by drakkan** [comment]
Hi, 

please try to specify the permissions as `/somedir::list,upload`. The dir path is the exposed virtual directory (not the file system oath), the separator is `::`

**Comment by mcvoigt** [comment]
Hi,
That's exactly what I did, but when saving it was blank. Now I tried again
and it was normally. I'm going to do more tests, and I'll let you know if I
find the root cause of what caused that behavior.

Regards,
Michael Voigt

Em dom., 7 de fev. de 2021 às 09:58, Nicola Murino <notifications@github.com>
escreveu:

**Comment by mcvoigt** [comment]
Hi
I think I typed some character wrong.
I tried again, as instructed and everything worked ok.
/somedir:: list,upload

Regards,
Michael Voigt

**Comment by drakkan** [comment]
Ok, thank you for your tests

**Comment by mcvoigt** [comment]
I thank you for your excellent work, congratulations
I hope I can contribute in some way for your work and effort
I found your project looking on the internet, and it will be of great use
to me
I see that you are dedicating yourself a lot to this project,
congratulations

Regards,
Michael Voigt

Em dom., 7 de fev. de 2021 às 10:45, Nicola Murino <notifications@github.com>
escreveu:
