### ISSUE TITLE
[Windows] Adding folders with with spaces and/or non english locale

### ISSUE THREAD

**Issue by MrHandy84** [drakkan/sftpgo#308]
Hi there, I have an issue creating folders in web gui.
Software version:
------------------------------------------------------
SFTPGo 2.0.1-cd4a68c-2021-02-06T14:30:52Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
------------------------------------------------------
First image: creating folder with non latin chars (Russian locale).
![2021-02-08 205331](https://user-images.githubusercontent.com/78750568/107260956-c1201d00-6a4f-11eb-9576-98c835f2baf1.png)

Second image creating folder with latin chars, but with space in folder name
![2021-02-08 205555](https://user-images.githubusercontent.com/78750568/107261198-15c39800-6a50-11eb-918b-43fc2006df96.png)

**Comment by drakkan** [comment]
Hi, 

folder names and user names are used inside the URI path, so they are restricted to the following characters `[a-zA-Z0-9-_.~]+$`. This will not affect the folder path that can be any valid absolute path

**Comment by drakkan** [comment]
Hi, I could add another descriptive field in future versions, the current name is an ID more than a name, so this will not change sorry

**Comment by drakkan** [comment]
You can now set `skip_natural_keys_validation` to `true` if you want to use [arbitrary chars for natural keys](https://github.com/drakkan/sftpgo/commit/df41f0c556cf360a179198274ed2116829e0e6bc)
