### ISSUE TITLE
sftpgo wrong parse the serve directory flag while using Windows CMD 

### ISSUE THREAD

**Issue by tianzry** [drakkan/sftpgo#309]
### I try to use sftpgo on Windows 10 using CMD, but I found that sftpgo wrong parse the path to the directory, which flag is -d or --directory.  It parsed the log directory as part of the serve directory, therefore, the serve directory was wrong. Following are the commands and logs :

_sftpgo version: SFTPGo 2.0.1-cd4a68c-2021-02-06T14:30:52Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable_

D:\Tools\sftpgo_v2.0.1_windows_portable_x86_64>.\sftpgo.exe portable -u root -p test1234 -s 22 --ftpd-port 21 -g *  **-d "D:\temp\"** --log-file-path "D:\temp\sftpgo.log"
2021-02-10T15:41:15.222 INF Portable mode ready, user: "root", password: "[redacted]", public keys: [], **directory: "D:\\temp\" --log-file-path D:\\temp\\sftpgo.log",** permissions: map[/:[*]], enabled ssh commands: [md5sum sha1sum cd pwd scp] file patterns filters: [] SFTP port: 22 FTP port: 21

D:\Tools\sftpgo_v2.0.1_windows_portable_x86_64>.\sftpgo.exe portable -u root -p test1234 -s 22 --ftpd-port 21 -g *  **--directory "D:\temp\"** --log-file-path "D:\temp\sftpgo.log"
2021-02-10T15:47:40.894 INF Portable mode ready, user: "root", password: "[redacted]", public keys: [], **directory: "D:\\temp\" --log-file-path D:\\temp\\sftpgo.log",** permissions: map[/:[*]], enabled ssh commands: [md5sum sha1sum cd pwd scp] file patterns filters: [] SFTP port: 22 FTP port: 21

### But  if I use the Powershell to run the same command, all is OK. 

PS D:\Tools\sftpgo_v2.0.1_windows_portable_x86_64> .\sftpgo.exe portable -u root -p test1234 -s 22 --ftpd-port 21 -g *  -d **"D:\temp\"** -l "D:\temp\sftpgo.log"
2021-02-10T15:40:51.253 INF Portable mode ready, user: "root", password: "[redacted]", public keys: [], **directory: "D:\\temp\\",** permissions: map[/:[*]], enabled ssh commands: [md5sum sha1sum cd pwd scp] file patterns filters: [] SFTP port: 22 FTP port: 21

PS D:\Tools\sftpgo_v2.0.1_windows_portable_x86_64> .\sftpgo.exe portable -u root -p test1234 -s 22 --ftpd-port 21 -g *  **-d "D:\temp\"** --log-file-path "D:\temp\sftpgo.log"
2021-02-10T15:44:39.639 INF Portable mode ready, user: "root", password: "[redacted]", public keys: [], **directory: "D:\\temp\\",** permissions: map[/:[*]], enabled ssh commands: [md5sum sha1sum cd pwd scp] file patterns filters: [] SFTP port: 22 FTP port: 21

**Comment by drakkan** [comment]
Hi,

I'm unable to replicate the issue using the command line you posted above, please take a look at the following screen:

![Schermata del 2021-02-10 09-49-55](https://user-images.githubusercontent.com/553263/107486747-b10a5980-6b85-11eb-9461-98840a7fe5cb.png)

I can replicate the issue if I use this command instead:

```
Z:\sftpgo_v2.0.1_windows_portable_x86_64>.\sftpgo.exe portable -u root -p test1234 -s 3022 --ftpd-port 3021 -g * -d "Z:\temp\" --log-file-path "Z:\temp\sftpgo.log"
2021-02-10T09:56:25.321 INF Portable mode ready, user: "root", password: "[redacted]", public keys: [], directory: "Z:\\temp\" --log-file-path Z:\\temp\\sftpgo.log", permissions: map[/:[*]], enabled ssh commands: [md5sum sha1sum cd pwd scp] file patterns filters: [] SFTP port: 3022 FTP port: 3021
```

but this is the expected behaviour, I wrote a wrong command in this case.

Please provide more info, thank you

**Comment by tianzry** [comment]
> Hi,
> 
> I'm unable to replicate the issue using the command line you posted above, please take a look at the following screen:
> 
> ![Schermata del 2021-02-10 09-49-55](https://user-images.githubusercontent.com/553263/107486747-b10a5980-6b85-11eb-9461-98840a7fe5cb.png)
> 
> I can replicate the issue if I use this command instead:
> 
> ```
> Z:\sftpgo_v2.0.1_windows_portable_x86_64>.\sftpgo.exe portable -u root -p test1234 -s 3022 --ftpd-port 3021 -g * -d "Z:\temp\" --log-file-path "Z:\temp\sftpgo.log"
> 2021-02-10T09:56:25.321 INF Portable mode ready, user: "root", password: "[redacted]", public keys: [], directory: "Z:\\temp\" --log-file-path Z:\\temp\\sftpgo.log", permissions: map[/:[*]], enabled ssh commands: [md5sum sha1sum cd pwd scp] file patterns filters: [] SFTP port: 3022 FTP port: 3021
> ```
> 
> but this is the expected behaviour, I wrote a wrong command in this case.
> 
> Please provide more info, thank you

Hi, drakkan,

Thank you for your reply.  I try to replicate my question today on my personal Windows 10(ver:1909) PC today, but I can't. 
I found the issue on my **work PC**, and I will check the issue again and paste the picture here after I go to work. I‘m on holiday now, and  I'll go back on 18 Feb.

Thankyou again! Have a nice day. :)

The following snapshot was got on my personal PC:
[![yBVyVS.jpg](https://s3.ax1x.com/2021/02/11/yBVyVS.jpg)](https://imgchr.com/i/yBVyVS)

**Comment by drakkan** [comment]
ok, please update me on this, thank you

**Comment by tianzry** [comment]
Hi, drakkan,

I'm sorry to pendding this issue for a long time. I double checked the problem on my work PC today, and I found that the reason is that I input the directory path string with Backslash suffix, as you mentioned before, that's not a correct way.

But it really confuses me, because I use the same command on Powershell and CMD, and the Powershell parses it correctly, but CMD not. That may be the different between Powershell and CMD. The following pictures show you the result:
_PS: I posted this issue at first time by pasting the command string directly, and the github Markdown parsed the "D:\temp\\" to "D:\temp", that's my fault, I'm sorry to that. Thank you again!_
![image](https://user-images.githubusercontent.com/19747979/108290476-76c73a80-71cb-11eb-9551-d764ae94e615.png)

![image](https://user-images.githubusercontent.com/19747979/108290551-9cecda80-71cb-11eb-8462-b9e872d25ddf.png)

**Comment by drakkan** [comment]
Hi,

powershell seems to autoescape the `\` while cmd not, anyway thi issue was already discussed, please take a look [here](https://github.com/drakkan/sftpgo/issues/86#issuecomment-595993879): as you can see any windows program seems to behave as SFTPGo

**Comment by tianzry** [comment]
Hi, drakkan,

It's clear now, I think that it should keep the current behavior. Thanks for your help.
