### ISSUE TITLE
Pass env vars to sftpgo docker container

### ISSUE THREAD

**Issue by skoriy88** [drakkan/sftpgo#311]
Hello. 
I try to pass sftpgo env vars using docker-compose, like
    environment:
      SFTPGO_HTTPD__BINDINGS__PORT: 6666
      SFTPGO_HTTPD__BINDINGS__ENABLE_HTTPS: 'true'
      SFTPGO_HTTPD__CERTIFICATE_FILE: /etc/sftpgo/ssl/sftpgo.crt
      SFTPGO_HTTPD__CERTIFICATE_KEY_FILE: /etc/sftpgo/ssl/sftpgo.key

The container runs normally, but inside the container's /etc/sftpgo/sftpgo.json file, I don't see any applied changes.

Maybe I misunderstood something and doing the job the wrong way?
Sorry for annoying.

**Comment by atruskie** [comment]
You won't see the changes inside the config file in the container.

You should see the in the log output when the container starts.

**Comment by skoriy88** [comment]
It seems it is not working.
Here my sftpgo block from docker-compose file 

  sftpgo:
    image: "drakkan/sftpgo:latest"
    privileged: true
    restart: always
    ports:
        - "2022:2022"
        - "8080:8080"
    volumes:
        - /mnt/s3fs/configs/sftp:/var/lib/sftpgo
        - /mnt/s3fs/configs/sftp/sftp_auth:/etc/sftpgo/sftp_auth
        - /mnt/sftp/data:/srv/sftpgo
        - /etc/sftpgo/ssl/sftpgo.key:/etc/sftpgo/ssl/sftpgo.key
        - /etc/sftpgo/ssl/sftpgo.crt:/etc/sftpgo/ssl/sftpgo.crt
    environment:
      SFTPGO_HTTPD__BINDINGS__PORT: 6666
      SFTPGO_HTTPD__BINDINGS__ENABLE_HTTPS: 'true'
      SFTPGO_HTTPD__CERTIFICATE_FILE: /etc/sftpgo/ssl/sftpgo.crt
      SFTPGO_HTTPD__CERTIFICATE_KEY_FILE: /etc/sftpgo/ssl/sftpgo.key


Here the logs from docker-compose up, and as I see it has not change default values....

sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:10.629","sender":"service","message":"starting SFTPGo 2.0.1-cd4a68cc-2021-02-06T14:32:24Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: , log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, load data from: \"\""}
sftpgo_1   | {"level":"debug","time":"2021-02-11T10:48:10.699","sender":"config","message":"config file used: '\"/etc/sftpgo/sftpgo.json\"', config loaded: {Common:{IdleTimeout:15 UploadMode:0 Actions:{ExecuteOn:[] Hook:} SetstatMode:0 ProxyProtocol:0 ProxyAllowed:[] PostConnectHook: MaxTotalConnections:0 DefenderConfig:{Enabled:false BanTime:30 BanTimeIncrement:50 Threshold:15 ScoreInvalid:2 ScoreValid:1 ObservationTime:30 EntriesSoftLimit:100 EntriesHardLimit:150 SafeListFile: BlockListFile:} idleTimeoutAsDuration:0 idleLoginTimeout:0 defender:<nil>} SFTPD:{Banner:SFTPGo_2.0.1 Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] BindPort:0 BindAddress: IdleTimeout:0 MaxAuthTries:0 UploadMode:0 Actions:{ExecuteOn:[] Hook:} Keys:[] HostKeys:[] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveHook: PasswordAuthentication:true ProxyProtocol:0 ProxyAllowed:[] certChecker:<nil> parsedUserCAKeys:[]} FTPD:{Bindings:[{Address: Port:0 ApplyProxyConfig:true TLSMode:0 ForcePassiveIP: ClientAuthType:0}] BindPort:0 BindAddress: ForcePassiveIP: Banner:SFTPGo 2.0.1 ready BannerFile: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] ActiveTransfersPortNon20:true DisableActiveMode:false EnableSite:false HASHSupport:0 CombineSupport:0 TLSMode:0 PassivePortRange:{Start:50000 End:50100}} WebDAVD:{Bindings:[{Address: Port:0 EnableHTTPS:false ClientAuthType:0}] BindPort:0 BindAddress: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0} Cache:{Users:{ExpirationTime:0 MaxSize:50} MimeTypes:{Enabled:true MaxSize:1000}}} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:0 Username: Password:[redacted] SSLMode:0 ConnectionString: SQLTablesPrefix: TrackQuota:2 PoolSize:0 UsersBaseDir:/srv/sftpgo/data Actions:{ExecuteOn:[] Hook:} ExternalAuthHook: ExternalAuthScope:0 CredentialsPath:credentials PreLoginHook: PostLoginHook: PostLoginScope:0 CheckPasswordHook: CheckPasswordScope:0 UpdateMode:0 PasswordHashing:{Argon2Options:{Memory:65536 Iterations:1 Parallelism:2}} PreferDatabaseCredentials:false} HTTPDConfig:{Bindings:[{Address: Port:8080 EnableWebAdmin:true EnableHTTPS:false ClientAuthType:0}] BindPort:0 BindAddress: TemplatesPath:/usr/share/sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static BackupsPath:/srv/sftpgo/backups CertificateFile:/etc/sftpgo/ssl/sftpgo.crt CertificateKeyFile:/etc/sftpgo/ssl/sftpgo.key CACertificates:[] CARevocationLists:[]} HTTPConfig:{Timeout:20 CACertificates:[] SkipTLSVerify:false customTransport:<nil>} KMSConfig:{Secrets:{URL: MasterKeyPath: masterKey:}} TelemetryConfig:{BindPort:10000 BindAddress:127.0.0.1 EnableProfiler:false AuthUserFile: CertificateFile: CertificateKeyFile:}}"}
sftpgo_1   | {"level":"debug","time":"2021-02-11T10:48:10.703","sender":"dataprovider_sqlite","message":"sqlite database handle created, connection string: \"file:sftpgo.db?cache=shared&_foreign_keys=1\""}
sftpgo_1   | {"level":"debug","time":"2021-02-11T10:48:10.722","sender":"dataprovider_sqlite","message":"sql database is up to date, current version: 8"}
sftpgo_1   | {"level":"debug","time":"2021-02-11T10:48:11.393","sender":"service","message":"FTP server not started, disabled in config file"}
sftpgo_1   | {"level":"debug","time":"2021-02-11T10:48:11.393","sender":"service","message":"WebDAV server not started, disabled in config file"}
sftpgo_1   | {"level":"debug","time":"2021-02-11T10:48:11.393","sender":"service","message":"initializing SFTP server with config {Banner:SFTPGo_2.0.1 Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] BindPort:0 BindAddress: IdleTimeout:0 MaxAuthTries:0 UploadMode:0 Actions:{ExecuteOn:[] Hook:} Keys:[] HostKeys:[] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveHook: PasswordAuthentication:true ProxyProtocol:0 ProxyAllowed:[] certChecker:<nil> parsedUserCAKeys:[]}"}
sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:11.405","sender":"sftpd","message":"Loading private host key \"id_rsa\""}
sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:11.406","sender":"sftpd","message":"Host key \"id_rsa\" loaded, type \"ssh-rsa\", fingerprint \"SHA256:RozwFou7rIih7PX3/O7iorKnIg5lz8MHj+VHTUvkIM8\""}
sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:11.406","sender":"sftpd","message":"Loading private host key \"id_ecdsa\""}
sftpgo_1   | {"level":"debug","time":"2021-02-11T10:48:11.412","sender":"httpd","message":"initializing HTTP server with config &{Bindings:[{Address: Port:8080 EnableWebAdmin:true EnableHTTPS:false ClientAuthType:0}] BindPort:0 BindAddress: TemplatesPath:/usr/share/sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static BackupsPath:/srv/sftpgo/backups CertificateFile:/etc/sftpgo/ssl/sftpgo.crt CertificateKeyFile:/etc/sftpgo/ssl/sftpgo.key CACertificates:[] CARevocationLists:[]}"}
sftpgo_1   | {"level":"debug","time":"2021-02-11T10:48:11.433","sender":"telemetry","message":"initializing telemetry server with config {BindPort:10000 BindAddress:127.0.0.1 EnableProfiler:false AuthUserFile: CertificateFile: CertificateKeyFile:}"}
sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:11.433","sender":"telemetry","message":"server listener registered, address: 127.0.0.1:10000 TLS enabled: false"}
sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:11.439","sender":"sftpd","message":"Host key \"id_ecdsa\" loaded, type \"ecdsa-sha2-nistp256\", fingerprint \"SHA256:v98geQIN+MGjyG5bWYOuySY2hGzrN3KLP/glXke9WkM\""}
sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:11.439","sender":"sftpd","message":"Loading private host key \"id_ed25519\""}
sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:11.440","sender":"sftpd","message":"Host key \"id_ed25519\" loaded, type \"ssh-ed25519\", fingerprint \"SHA256:BETwrOzoFbJP81PWqHoWeI9zBEzHl80+wUUbe893mpg\""}
sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:11.476","sender":"sftpd","message":"server listener registered, address: [::]:2022"}
sftpgo_1   | {"level":"debug","time":"2021-02-11T10:48:11.476","sender":"httpd","message":"TLS certificate \"/etc/sftpgo/ssl/sftpgo.crt\" successfully loaded"}
sftpgo_1   | {"level":"info","time":"2021-02-11T10:48:11.478","sender":"httpd","message":"server listener registered, address: [::]:8080 TLS enabled: false"}
compose.cli.verbose_proxy.proxy_callable: docker events <- (filters={'label': ['com.docker.compose.project=docker', 'com.docker.compose.oneoff=False']}, decode=True)

Please, ping me what i've done wrong. 
Thanks a lot!

**Comment by drakkan** [comment]
Hi,

I read:

```
CertificateFile:/etc/sftpgo/ssl/sftpgo.crt CertificateKeyFile:/etc/sftpgo/ssl/sftpgo.key
```

so the cert vars are working.

The bindings are an array, please try `SFTPGO_HTTPD__BINDINGS__0__PORT`

**Comment by skoriy88** [comment]
Thanks a lot!!!
It works! 
Sorry for your time. 
You are a great man!
