### ISSUE TITLE
Cannot delete empty folder (S3 backend)

### ISSUE THREAD

**Issue by akospinter** [drakkan/sftpgo#313]
Hi,

I can't delete empty directories when using S3 storage backend. I can see that error message in the logs: "Cannot remove non empty directory" , but the mentioned directory was definitely empty.

Steps to reproduce:
- configure the SFTPGO with an Amazon S3 backend
- create the following directory structure: `/path/to/dirtodelete`
- try delete `dirtodelete` , it fails with the error message above

**Comment by drakkan** [comment]
Hi,

I'm unable to replicate the issue.

Using MinIO as S3 backend:

```
sftp -P 2022 minio@127.0.0.1
minio@127.0.0.1's password: 
Connected to 127.0.0.1.
sftp> mkdir /path/to/dirtodelete
sftp> ls /path/to/dirtodelete
sftp> rmdir /path/to/dirtodelete
sftp> rmdir /path/to
sftp> rmdir /path
sftp> quit
```

Using AWS S3:

```
sftp -P 2022 awss3new@127.0.0.1
awss3new@127.0.0.1's password: 
Connected to 127.0.0.1.
sftp> ls
sftp> mkdir /path/to/dirtodelete
sftp> ls /path/to/dirtodelete
sftp> rmdir /path/to/dirtodelete
sftp> rmdir /path/to
sftp> rmdir /path
sftp> quit
```

There was a similar issue with some old version, but it should work now with SFTPGo 2.0.x. Can you please specify your SFTPGo version and your S3 backend? Thank you

**Comment by akospinter** [comment]
Hi @drakkan ,
thank you for the quick reply. 
I experienced the mentioned error with the 1.2.2 version (Docker container) .

I upgraded to v2.0.1 and everything seems OK now. 
Thanks for you help.
