### ISSUE TITLE
Local encrypted storage

### ISSUE THREAD

**Issue by perfecto25** [drakkan/sftpgo#314]
Hello, first off, this is an amazing project esp compared to pain of vsftpd

thank you for building this.

question re Local encrypted storage for user,

Im not sure how to use this, I want users to connect and retreive encrypted files, does this encrypt files at rest?

Also once I set it to use Local encrypted (with password), I am unable to download the files as a client,

```
sftp> get file1
Fetching /file1 to file1
remote open("/file1"): Failure
```

Dont see anything in docs re this feature.

Thank you.

**Comment by drakkan** [comment]
Hi,

please take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/dare.md) to understand how Data-at-rest works.

Is `file1` uploaded using sftpgo? If this is not the issue please post some logs, thank you

**Comment by drakkan** [comment]
You are likely trying to download a non-encrypted file, please reopen, providing more info, if this isn't the case, thank you
