### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eetsceeck1** [drakkan/sftpgo#315]
hello guys, thank you for this great project, but please do something about the documentation, there is a really lack of critical information such as, command lines, and what exactly each line of the json means, how should we add the information there, what info is needed for basic, the help argument doesn't really provide any info, where is the MySQL table, and if there is no MySQL table and the sftpgo will create it automatically after an initialization i can understand that, but a lot of things is missing, how to create a user with CLI, how to define a location with CLI and so on and so forth, take a look on curl for example, all of the CLI really detailed on their documentation, 
thank you!

**Comment by drakkan** [comment]
Hi,

I do my best, the documentation is not the fun part and English is not my native language.

Regarding your questions:

> command lines, and what exactly each line of the json means

please take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

> where is the MySQL table, and if there is no MySQL table and the sftpgo will create it automatically after an initialization i can understand that, but a lot of things is missing

the MySQL tables will be auto-created within the configured database, take a look [here](https://github.com/drakkan/sftpgo#data-provider-initialization-and-management) for more info. You can easily inspect the created tables using any MySQL admin tool.

> how to create a user with CLI, how to define a location with CLI and so on and so forth, take a look on curl for example, all of the CLI really detailed on their documentation,

The most convenient way to manage users and folder is the built-in [web admin](https://github.com/drakkan/sftpgo/blob/main/docs/web-admin.md). 

SFTPGo exposes [REST API](https://github.com/drakkan/sftpgo/blob/main/docs/rest-api.md) using an [OpenAPI schema](https://github.com/drakkan/sftpgo/blob/main/httpd/schema/openapi.yaml), within the OpenAPI schema each field is documented (or at least the most relevant ones).  You can use any OpenAPI generator to generate your own client, some generators can also create bash scripts using `curl`. 

You can also try [swagger-ui](https://github.com/swagger-api/swagger-ui) it exposes a web interfaces that can be used both to document the exposed API and for test them. Please take a look [here](https://swagger.io/resources/articles/documenting-apis-with-swagger/).  You can also try [ReDoc](https://github.com/Redocly/redoc).  Both swagger ui and redoc show the curl CLI to use the API yourself. There are several OpenAPI generators out of there, please Google for them and choose the one that better fit your need, you can also create docs as PDF etc..

The documentation could definitely be improved, but I don't have the user's perspective, for me it's all simple and intuitive since I write the code. It would be better if it was improved by the users, do you want to help me with a PR? Thank you!

**Comment by eetsceeck1** [comment]
Hi Nicola thank you for your reply and thank you very much for the project, 
I will start by this that I am not the most pro using the GitHub platform, honestly, 
but on the computer of course its another story, 
about the question if I would like to help you with the project, the answer is Yes!, 
I do many things, cyber security, PHP programming, graphics, and a tons of things on the computer, 
about English, it's not my native language either, my native language is Hebrew, but I think my English is good enough to provide a clear and understandable documentation,

you did sent to me the link: https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md
for some reason I never seen this, even though I were looking for it, 
it is indicating about a large portion of the json parameters but still not all, 
for instance: "connection_string": "", (Mysql), I did not check any each of the Json lines which are missing on the "full-configuration.md" but I believe if one is missing so might other as well,

I think I got the principle behind your software now, I think actually your software doesn't really include a full CLI but limited to very few, and all of the configurations will be set manually or by the Webadmin interface, I am not sure I am very confuse about the structure this program do take care about things, 

I tried also to understand the way the Webadmin is writing parameters into the Json file by taking a  look on the JavaScript files in it, but with a quick look I found nothing related in the JS folder but some jquery for the scrollbar etc, 

I don't know much about OpenAPI or swagger-codegen, I can dive into it of course, but I think I don't know how it can help at all if I don't understand the tree steps that need to be taken on the executable and the software structure, 

what parameters is written into the DB and what parameters is written only the Json, 

if you accept my opinion, I think that all need to be achieved through the program itself without involvement of a third party tool with CLI, every single line need to be configured with CLI, 

if it was the case, we can do a lot of things easier and also develop a new Web interface that manages the whole program without a single command line if desired, or with CLI to whom willing to, 
I can create full PHP admin panel what will including crud with very secure login page and access control, + all the configurations need to be made on the Json or the database's, 
all i need to understand is what exactly each line is about and what kind info need to be inserted in some of them, (i never seen such parameters / and not all included in the md file)

and a CLI commands straight to the point will help me to run them through PHP code and achieve them straight, now I thought maybe were concerned about the PHP how it will run on the server when there is no any PHP server running on the background such as apache or IIS while people just using the SFTP function and not the a fully functional web server, that can be achieve easily with an PHP runner so the interface will be available not only on the browser but also locally as a native program, 

about the documentations, I can create a very fancy and clear documents easy on my machine  am a web developer aside all other things and all is set and ready to do it, 

I think it will be very difficult for us to communicate in here,  
please contact me straight with my email and we might will do a meeting on my computer live with a remote software and we will discuss and close all open corners if you like, once it will happen i will take care everything else the Webadmin, the security, the documentation, and it will easy for you to understand what CLI I am talking about, 

my email is eetsceeck@gmail.com
thank you

**Comment by drakkan** [comment]
> Hi Nicola thank you for your reply and thank you very much for the project,
> I will start by this that I am not the most pro using the GitHub platform, honestly,
> but on the computer of course its another story,
> about the question if I would like to help you with the project, the answer is Yes!,
> I do many things, cyber security, PHP programming, graphics, and a tons of things on the computer,
> about English, it's not my native language either, my native language is Hebrew, but I think my English is good enough to provide a clear and understandable documentation,
> 

This is very appreciated, thank you

> you did sent to me the link: https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md
> for some reason I never seen this, even though I were looking for it,
> it is indicating about a large portion of the json parameters but still not all,
> for instance: "connection_string": "", (Mysql), I did not check any each of the Json lines which are missing on the "full-configuration.md" but I believe if one is missing so might other as well,
> 

for connection_string there is a typo, thank you for spotting this (I'll send an update later today). It is documented as `connectionstring`, you need to specify a connection string in rare case, generally SFTPGo build a connection string for you based on name/host/port/username/password parameters.

If other parameters are missing I will be glad to fix.

> I think I got the principle behind your software now, I think actually your software doesn't really include a full CLI but limited to very few, and all of the configurations will be set manually or by the Webadmin interface, I am not sure I am very confused about the structure this program do take care about things,
> 

SFTPGo is configured using a configuration file, `sftpgo.json` by default, but other formats are supported too (YAML, TOML, etc) or you can configure it via env vars without a configuration file. 

The configuration file contains the application configuration, while the application data (users, folders, admins etc) are stored inside a supported data provider (MySQL, PostgreSQL, SQLite, bolt, ...), the web admin and the REST API allow to manage the data inside the data provider.

> I tried also to understand the way the Webadmin is writing parameters into the Json file by taking a look on the JavaScript files in it, but with a quick look I found nothing related in the JS folder but some jquery for the scrollbar etc,
> 

the web admin does not write to the json file at all.

> I don't know much about OpenAPI or swagger-codegen, I can dive into it of course, but I think I don't know how it can help at all if I don't understand the tree steps that need to be taken on the executable and the software structure,
> 
> what parameters is written into the DB and what parameters is written only into the Json,
> 

users, folders, admins are stored inside the data provider, the application configuration is stored inside the configuration file (but you can also configure sftpgo using env vars). As said above REST API/Web admin manage data inside the data provider. The sys admin configures the application parameters updating the configuration file.

> if you accept my opinion, I think that all need to be achieved through the program itself without the involvement of a third party tool with a CLI, every single line need to be configured with CLI,
> 

this is not possibile using data providers such as sqlite or boltdb, if sftpgo is running you cannot update these database using another program, the database is locked.

> if it was the case, we can do a lot of things easier and also to develop a new Web interface that manages the whole program without a single command line if desired, or with a CLI to whom willing to,
> I can create a full PHP admin panel what will include a crud with a very secure login page and access control, + all the configurations need to be made in the Json or the database's,
> all i need to understand is what exactly each line is about, and what kind of info need to be inserted into some of them, (i never seen such parameters / and not all included in the md file)
> 
> and a CLI commands straight to the point will help me to run them through PHP code and achieve them straight, now I thought maybe you were concerned about the PHP how it will run on the server when there is no any PHP server running in the background such as apache or IIS while people just using the SFTP function and not the a fully functional web server, that can be achieved easily with a PHP runner so the interface will be available not only through the browser but also locally as a native program,
> 

I think it is easier to integrate SFTPGo using the REST API than starting an external program, several users already integrate it this way

> about the documentations, I can create a very fancy and clear documents easy to understand on my machine, I am a web developer aside all of other things and all is set and ready to do it,
> 

SFTPGo does not have a dedicated web site, I will be glad to accept your improvements but the doc should be hosted here on GitHub

> I think it will be very difficult for us to communicate in here,
> please contact me straight with my email and we might will do a meeting on my computer live with a remote software and we will discuss and close all open corners if you like, once it will happen i will take care everything else the Webadmin, the security, the documentation, and it will easy for you to understand what CLI I am talking about,
> 
> my email is [eetsceeck@gmail.com](mailto:eetsceeck@gmail.com)
> thank you

**Comment by eetsceeck1** [comment]
thank you for your reply, its all much clear now,
allow me several days to dive into all the API's possibilities and build schema from a to z and I will replay with answers, and ideas, if you will like it, it will be depends on you if you will be willing to add my features, about a dedicated website, consider it done, Its all on me, you will have an access to the website after it will be build with everything needed and you can change and update the content to whatever you like, 
the documentation will be included in GitHub as well cause I have no idea how to set things in GitHub you will be the one to do it as always, after I will create a documentation in plain text i will convert it into pdf and web versions, you will just need to confirm it that is all legit and true,

thank you

**Comment by drakkan** [comment]
> thank you for your reply, its all much clear now,
> allow me several days to dive into all the API's possibilities and build schema from a to z and I will replay with answers, and ideas, if you will like it, it will be depends on you if you will be willing to add my features, about a dedicated website, consider it done, Its all on me, you will have an access to the website after it will be build with everything needed and you can change and update the content to whatever you like,
> the documentation will be included in GitHub as well cause I have no idea how to set things in GitHub you will be the one to do it as always, after I will create a documentation in plain text i will convert it into pdf and web versions, you will just need to confirm it that is all legit and true,
> 
> thank you

Great, thank you! 

Please use SFTPGo and explore what it allows, if you have any questions I prefer you to write here (on GitHub) so the answers can help others too, better if you open a new issue/discussion by question so the answers are easier to find.

**Comment by NightMachinary** [comment]
@drakkan I have been looking for the available options for `permissions`, and this is the only thing I can find:

```
-g, --permissions strings             User's permissions. "*" means any
                                         permission (default [list,download])
```

**Comment by drakkan** [comment]
> @drakkan I have been looking for the available options for `permissions`, and this is the only thing I can find:
> 
> ```
> -g, --permissions strings             User's permissions. "*" means any
>                                          permission (default [list,download])
> ```

As pointed above user properties are defined inside the [OpenAPI schema](https://github.com/drakkan/sftpgo/blob/main/httpd/schema/openapi.yaml#L1285), if you simply use the built-in web admin you don't need to know them :)

Pull requests to improve the docs are welcome, thank you

**Comment by drakkan** [comment]
I also published the API schema on [stoplight](https://sftpgo.stoplight.io/docs/sftpgo/openapi.yaml), for example permissions are documented [here](https://sftpgo.stoplight.io/docs/sftpgo/openapi.yaml/components/schemas/Permission) but based on the questions asked here I don't think this kind of docs will help

**Comment by NightMachinary** [comment]
[**@drakkan**](https://github.com/drakkan) commented on [Mar 7, 2021, 6:44 PM GMT+3:30](https://github.com/drakkan/sftpgo/issues/315#issuecomment-792294676 "2021-03-07T15:14:23Z - Replied by Github Reply Comments"):
> I also published the API schema on [stoplight](https://sftpgo.stoplight.io/docs/sftpgo/openapi.yaml), for example permissions are documented [here](https://sftpgo.stoplight.io/docs/sftpgo/openapi.yaml/components/schemas/Permission) but based on the questions asked here I don't think this kind of docs will help

This is actually pretty good, but please add it to the readme and `sftpgo --help`.

**Comment by drakkan** [comment]
> [**@drakkan**](https://github.com/drakkan) commented on [Mar 7, 2021, 6:44 PM GMT+3:30](https://github.com/drakkan/sftpgo/issues/315#issuecomment-792294676):
> 
> > I also published the API schema on [stoplight](https://sftpgo.stoplight.io/docs/sftpgo/openapi.yaml), for example permissions are documented [here](https://sftpgo.stoplight.io/docs/sftpgo/openapi.yaml/components/schemas/Permission) but based on the questions asked here I don't think this kind of docs will help
> 
> This is actually pretty good, but please add [the link](https://sftpgo.stoplight.io/docs/sftpgo/openapi.yaml) to the readme and `sftpgo --help`, too.

I just added it. I hope it not generates more confusions

**Comment by drakkan** [comment]
Hi,

I just added a [Getting Started Guide](https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md) that should cover the basic concepts. You still need to know some basic concepts.

If this is not enough pull requests are appreciated. Complaining doesn't help, thank you
