### ISSUE TITLE
SFTP - Wrong error message if too many sessions

### ISSUE THREAD

**Issue by kevin39** [drakkan/sftpgo#317]
Hi,
Using SFTP backend I was having the error "Authentification failed" until I realised to look at my servers log.

It was related to the concurrent session limit. 
See my log : 
Feb 19 19:31:01 utils sftpgo[17252]: {"level":"debug","time":"2021-02-19T19:31:01.487","sender":"sftpd","message":"failed to accept an incoming connection: [ssh: no auth passed yet, Authentication error: could not validate password credentials: too many open sessions: 1]"}

The error "Authentification failed" sent to the client is not good for me. You must use another error code.

Thanks

Server version : SFTPGo 1.2.2-dev-78bf808-2021-02-01T18:05:54Z

**Comment by drakkan** [comment]
Hi,

this don't seem possible sorry, please take a look at the [RFC 4252 section 5.1](https://tools.ietf.org/html/rfc4252#section-5.1):

>If the server rejects the authentication request, it MUST respond
   with the following:

      byte         SSH_MSG_USERAUTH_FAILURE
      name-list    authentications that can continue
      boolean      partial success

When SFTPGo returns an error for one of the supported authentication callbacks, the golang crypto ssh library will always sent a [userAuthFailureMsg](https://github.com/golang/crypto/blob/master/ssh/messages.go#L161) I think this is what rfc4252 dictates

**Comment by kevin39** [comment]
Hi,
I understand you but it may cause some troubles with others users too... Anyway, I don't need it now I know this behavior but this can cause spent time to other users.

**Comment by drakkan** [comment]
Hi,

I'll try to better explain, SFTPGo returns the same error for both SFTP and FTP. For FTP the protocol allows to return an error code and a message, take a look here:

```
ftp 127.0.0.1 2121
Connected to 127.0.0.1.
220 SFTPGo 2.0.2-dev ready
Name (127.0.0.1:nicola): a
331 OK
Password: 
530 Authentication problem: too many open sessions: 1
ftp: Login failed.
```

For SFTP/SSH the response to the authentication requests is this `SSH_MSG_USERAUTH_FAILURE` or `SSH_MSG_USERAUTH_SUCCESS` a single byte and the client shows a message, for example:

```
sftp -P 2022 a@127.0.0.1
a@127.0.0.1's password: 
Permission denied, please try again.
```

SFTPGo code never returns the error `Permission denied, please try again.`. It is generated [client side](https://github.com/openssh/openssh-portable/blob/master/sshconnect2.c#L1065).

Please reopen if you find a client/server pair that allow to customize the auth response, I'll try to investigate in that case and to do the required modifications to golang crypto/ssh. Thank you
