### ISSUE TITLE
Restricting SFTP/SCP algorithms for security reasons

### ISSUE THREAD

**Issue by binou-31** [drakkan/sftpgo#32]
Hello,

Very great project.
Is it possible to add feature of restricting the use of SFTP/SCP Algorithms such as Compression algorithms, Key exchanges, ciphers, or MACs for security reasons ?
A white list to choose algorithms

Thanks

**Comment by drakkan** [comment]
Hi,

thanks for your suggestion, 

currently we use the default values and so:

- ciphers: https://github.com/golang/crypto/blob/master/ssh/common.go#L38
- kex: https://github.com/golang/crypto/blob/master/ssh/common.go#L46
- macs: https://github.com/golang/crypto/blob/master/ssh/common.go#L76

I'll add some configuration options to customize these values.

Compression is actually not supported in golang crypto/ssh library and so it isn't configurable:

https://github.com/golang/go/issues/31369

I'll add support for it once this feature will be added upstream

**Comment by binou-31** [comment]
Thank you for your work. fast and effective.
