### ISSUE TITLE
Ability to let user change their password

### ISSUE THREAD

**Issue by chanster** [drakkan/sftpgo#321]
There isn't a way to directly allow a user to change their password via some type of interface directly with SFTPGo. Currently it looks like we must write a external process that calls the API to update the user information.

**Comment by drakkan** [comment]
Hi,

I will try to add a user portal that allows each user to log in and change their password and/or public keys before the 2.1.0 release.

This is not exactly the kind of task that I like to do, a [sponsorship](https://github.com/sponsors/drakkan) would be appreciated, thank you.

**Comment by fdefilippo** [comment]
Hi, before allowing the change of the public key I would think twice, go for the password but the public key especially if signed by a ca it would be better to be driven by an administrative flag. IMHO 😃

**Comment by drakkan** [comment]
Fixed in https://github.com/drakkan/sftpgo/commit/23d9ebfc91ae9414a5672ab9e7dab47766b320b2
