### ISSUE TITLE
Docker login password unknown

### ISSUE THREAD

**Issue by blieb** [drakkan/sftpgo#322]
Hi,

I try to get the docker image to run, so I run the example:

`docker run --name some-sftpgo -p 127.0.0.1:8080:8080 -p 2022:2022 -d "drakkan/sftpgo:latest"`

next I go to http://127.0.0.1:8080/ and I get a login window. I understand I should be able to add a user there but it requires me to login. how can I add a user? I also don't see a way to do this via command line.

**Comment by blieb** [comment]
Oh Login is: admin / password
Maybe add this to the docker manual :)

**Comment by drakkan** [comment]
Hi,

it is documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/web-admin.md), I'll add a note in the docker docs too, thank you

**Comment by drakkan** [comment]
This is now documented in the docker docs too
