### ISSUE TITLE
Telemetry env vars not working

### ISSUE THREAD

**Issue by johnjelinek** [drakkan/sftpgo#323]
```
$ docker run -p 8080:8080 -p 2022:2022 -p 10000:10000 -e "SFTPGO_TELEMETRY_BIND_ADDRESS=0.0.0.0" -it --rm "drakkan/sftpgo:v2.0.1"
```

I expected this to overwrite the config like it does when I use the examples (e.g.: `-e "SFTPGO_SFTPD__BINDINGS__0__PORT=1234"`). But it doesn't apply, maybe I have the name wrong?

**Comment by drakkan** [comment]
Hi,

you have to use `__` to traverse a struct. This should work `SFTPGO_TELEMETRY__BIND_ADDRESS=0.0.0.0`, thanks

**Comment by johnjelinek** [comment]
Ah, very good. It was unclear to me that telemetry was the struct there. Thank you.
