### ISSUE TITLE
Environmental variables for AWS/S3 backend

### ISSUE THREAD

**Issue by shyamjos** [drakkan/sftpgo#324]
Is there a way to set AWS credentials as environmental variables ?

**Comment by drakkan** [comment]
Yes, you can set the credentials as per AWS docs, please take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/howto/postgresql-s3.md#configure-aws-credentials) and adapt to your configuration if you are using docker and not a distro package

**Comment by shyamjos** [comment]
I have configured it inside docker-compose env  section, but it seems like gosftp is not reading aws vars from shell?
```
#COMMON SETTINGS
SFTPGO_COMMON__UPLOAD_MODE=1
#FIREWALL
SFTPGO_DEFENDER__ENABLED=true
SFTPGO_DEFENDER__BAN_TIME=15
SFTPGO_DEFENDER__BAN_TIME_INCREMENT=5
SFTPGO_DEFENDER__THRESHOLD=3
SFTPGO_DEFENDER__SCORE_INVALID=3
SFTPGO_DEFENDER__SCORE_VALID=3
#DB SETTINGS
SFTPGO_DATA_PROVIDER__DRIVER=mysql
SFTPGO_DATA_PROVIDER__HOST=db
SFTPGO_DATA_PROVIDER__PORT=3306
SFTPGO_DATA_PROVIDER__USERNAME=user
SFTPGO_DATA_PROVIDER__PASSWORD=pass
SFTPGO_DATA_PROVIDER__NAME=appdb
#WEB UI
SFTPGO_HTTPD__BINDINGS__ENABLE_WEB_ADMIN=true
SFTPGO_HTTPD__BINDINGS__PORT=8080
#AWS
aws_access_key_id = AAAA
aws_secret_access_key = BBBB

``
```
logs
NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
`

**Comment by drakkan** [comment]
They probably are case sensitive, also the space before and after `=` could create troubles. 

If you are using v2.0.x this one `SFTPGO_HTTPD__BINDINGS__PORT` will be ignored, please refer to the docs. The defender seems too aggressive: you will basically ban every user that fails to login just once, anyway experiment and find the right settings for your use case, good luck

**Comment by shyamjos** [comment]
Yes that was case-sensitive and space issue!
This is a test setup and I will update defender settings accordingly once we go live !

Also is there any option to create some sub folders at the time of user account creation when S3 backend is used ?
Thanks for the quick response

**Comment by drakkan** [comment]
> Yes that was case-sensitive and space issue!
> This is a test setup and I will update defender settings accordingly once we go live !
> 
> Also is there any option to create some sub folders at the time of user account creation when S3 backend is used ?

virtual folders are currently not supported for non local filesystems, see #241. I plan to add support for them in a future update but I don't have a definite schedule, a sponsorship will help here.

If instead you want to share the same bucket among different users and restrict each user to a specific bucket portion you can set 
a key prefix. 

If you have to add a lot of similar users with different key prefixes the template feature available within the web admin could be useful.

Thank you

> Thanks for the quick response
