### ISSUE TITLE
High availability/Autoscaling setup using Kubernetes

### ISSUE THREAD

**Issue by shyamjos** [drakkan/sftpgo#328]
Hi we are planning to setup sftpgo with s3 backend and multiple replicas (pods) connected to a single MySQL database, Is there any specific configurations required when running more than one instances of  sftpgo (connected to a single DB) ?
Do we need to enable sticky session for SFTP port ?
Do we need to enable  sticky session for admin panel ?

```
#COMMON SETTINGS
SFTPGO_COMMON__UPLOAD_MODE=1
#SFTPD
SFTPGO_SFTPD__HOST_KEYS="/etc/sftpgo/keys/id_rsa"
#DB SETTINGS
SFTPGO_DATA_PROVIDER__DRIVER=mysql
SFTPGO_DATA_PROVIDER__HOST=db
SFTPGO_DATA_PROVIDER__PORT=3306
SFTPGO_DATA_PROVIDER__USERNAME=user
SFTPGO_DATA_PROVIDER__PASSWORD=pass
SFTPGO_DATA_PROVIDER__NAME=appdb
#WEB UI
SFTPGO_HTTPD__BINDINGS__ENABLE_WEB_ADMIN=true
#AWS
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
```

**Comment by drakkan** [comment]
Hi,

yes sticky sessions are required for both SFTP and admin panel. Please take a look [here](https://github.com/drakkan/sftpgo/discussions/281) too.

f you have time, I really appreciate a PR with an [how-to style guide](https://github.com/drakkan/sftpgo/tree/main/docs/howto) that explains this setup, this will help other users, thank you

**Comment by shyamjos** [comment]
Thanks, Will try to create the guide if I get time

**Comment by drakkan** [comment]
Special attention is required when updating SFTPGo, only one node need to update the shared database (you can also manually manage schema updates, maybe it is better in this case).

Sticky sessions are required for the admin GUI/REST API since the cookies/tokens are not shared. 

SFTP and WebDAV should work even without sticky sessions if the storage backend is shared. 

FTP requires sticky sessions: the transfer connection must be handled on the same node that handle the control connection.

**Comment by shyamjos** [comment]
Since ingress-nginx does not support IP restriction for tcp services, Is there a way to configure IP restriction at sftpgo ? My goal is to only allow known IPs.
PS: Ingress-nginx supports proxy-protocol

**Comment by drakkan** [comment]
> Since ingress-nginx does not support IP restriction for tcp services, Is there a way to configure IP restriction at sftpgo ? My goal is to only allow known IPs.
> PS: Ingress-nginx supports proxy-protocol

Yes, you can restrict both users and admins using the rest api or the built-in web admin. For each user you can set Denied IP/Mask or Allowed IP/Mask.

**Comment by drakkan** [comment]
You can also configure global safe/blocklist inside the defender section of the configuration file

**Comment by shyamjos** [comment]
IP blocking is working as expected when proxy-protocol is enabled at ingress-nginx and sftpgo.
Thanks @drakkan

**Comment by shyamjos** [comment]
Does web-ui /api-server also use proxy-protocol ?

**Comment by drakkan** [comment]
> Does web-ui /api-server also use proxy-protocol ?

No, for web ui/api you can use a standard reverse proxy, the client IP will be extracted from the `X-Forwarded-For` or `X-Real-IP` header
