### ISSUE TITLE
Document user JSON representation

### ISSUE THREAD

**Issue by grobie** [drakkan/sftpgo#329]
Thanks so much for this great piece of software! It's been a pleasure to work with so far.

I found the support for [dynamic user creation](https://github.com/drakkan/sftpgo/blob/main/docs/dynamic-user-mod.md) as well as [external auth](https://github.com/drakkan/sftpgo/blob/main/docs/external-auth.md). Both options expect JSON serialized user objects as output, but I couldn't find any documentation of said JSON representation. It would be great to have these interface formats documented somewhere. Other documentation pages using the JSON schema can then link to that page.

**Comment by drakkan** [comment]
Hi,

please take a look at the [OpenAPI schema](https://github.com/drakkan/sftpgo/blob/main/httpd/schema/openapi.yaml)

**Comment by drakkan** [comment]
Hi,

I linked the openapi schema where relevant. 

From the schema you can generate the documentation as HTML or you can use something like [swagger ui](https://github.com/swagger-api/swagger-ui) to to visualize and interact with the API’s resources.

I'm aware that docs can be improved, a pull request would be greatly appreciated, I often miss the user's perspective. Thank you!

**Comment by grobie** [comment]
Thanks for that!

Have you considered publishing the OpenAPI spec somewhere directly? https://stoplight.io/ provides a free plan and a Github integration, so users could check out the latest rendered version without having to import the spec manually. I'd be happy to help out, but I guess it makes most sense to configure stoplight (or a similar service) as the project owner? Let me know otherwise.

**Comment by drakkan** [comment]
Hi,

I did not know stoplight, I'll give it a try, thanks for sharing

**Comment by drakkan** [comment]
Hi, 

I published the API [here](https://sftpgo.stoplight.io/docs/sftpgo/openapi.yaml). To be honest I'm not impressed, I'll not advertise it for now

**Comment by drakkan** [comment]
I was wrong, the spotlight docs are useful for several people, thank you!

**Comment by grobie** [comment]
Glad to hear! I'm affiliated with Stoplight in any way, but would be interested what you find lacking?

sftpgo is an awesome project and I believe it would greatly benefit from easy to use, public documentation. Instead of using a third-party tool, we also could use an open-source OpenAPI docs generator and publish that on a Github Page. With Github Actions, that should be also automatable.

**Comment by drakkan** [comment]
I'm used to swagger-ui, I approached it from the wrong point of view, I mainly tested  `prism-cli` hoping to find something like an OpenAPI fuzzer.

I sometime miss the user perspective.

What OpenAPI doc generator do you suggest? Do you know other projects that do the same? Thank you
