### ISSUE TITLE
k8s deployment fails due to missing "schema_version" sqlite-db-table

### ISSUE THREAD

**Issue by dash042** [drakkan/sftpgo#330]
{"level":"warn","time":"2021-03-01T16:10:06.906","sender":"dataprovider_sqlite","message":"error preparing database query \"SELECT version from schema_version LIMIT 1\": no such table: schema_version"}
{"level":"warn","time":"2021-03-01T16:10:12.003","sender":"dataprovider_sqlite","message":"Unable to initialize data provider: database is locked"}
{"level":"error","time":"2021-03-01T16:10:12.003","sender":"service","message":"error initializing data provider: database is locked"}

am I missing some environment variable that was not documented in the docker-Readme.md?

**Comment by drakkan** [comment]
Hi,

the relevant error here is:

>  database is locked

I guess you are trying to use SQLite over a `cifs` share. Please take a look [here](https://github.com/drakkan/sftpgo/issues/235#issuecomment-736031585): set the `nobrl` mount option for the cifs share or switch to another provider, for example bolt. Please also note that if your data volume is mounted over a cifs share  you need an SFTPGo version built with Go 1.16 (so the `edge` or `edge-slim` variant)

**Comment by dash042** [comment]
yes - the mountpoint is from Azure Files service.
I have several mount options set:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  **- nobrl**

I have also tried "edge" and "edge-slim" - SFTPGo 2.0.2-dev-901cafc6-2021-02-28T11:36:06Z for the latter... no luck unfortunately.

**Comment by drakkan** [comment]
I have no way to test the SQLite and the `nobrl` option using azure file services, it works fine when I mount a cifs partition from Linux, anyway the `bolt` provider is probably the better option in this case if you need an embedded data provider.

Go 1.16 fixes the issue reported [here](https://github.com/drakkan/sftpgo/issues/243), alternately you have to set the `GODEBUG=asyncpreemptoff=1`, but it is probably better to use the `edge` variant that is built using Go 1.16

**Comment by maxk001** [comment]
I have the same error using postgres on aws k8s. 

```
{"level":"debug","time":"2024-05-14T13:27:16.216","sender":"dataprovider_postgresql","message":"postgres database handle created, connection string: \"host='sftpgo-postgres-rw' port='5432' dbname='app' user='app' password='[redacted]' sslmode=disable connect_timeout=10\", pool size: 0"}
{"level":"error","time":"2024-05-14T13:27:16.234","sender":"dataprovider_postgresql","message":"error preparing database query \"SELECT version from schema_version LIMIT 1\": ERROR: relation \"schema_version\" does not exist (SQLSTATE 42P01)"}
{"level":"info","time":"2024-05-14T13:27:16.234","sender":"dataprovider_postgresql","message":"creating initial database schema, version 23"}
{"level":"info","time":"2024-05-14T13:27:16.235","sender":"dataprovider_postgresql","message":"acquired database lock"}
{"level":"error","time":"2024-05-14T13:27:16.236","sender":"dataprovider_postgresql","message":"error preparing database query \"SELECT version from schema_version LIMIT 1\": ERROR: relation \"schema_version\" does not exist (SQLSTATE 42P01)"}
```

I tried using bolt, but I cannot as I need to do custom readiness probe cmd to validate data is in (not doing it yet, so this extra sql is not a reason of current failure)
