### ISSUE TITLE
Docker: unable to access web frontend on 8080

### ISSUE THREAD

**Issue by dash042** [drakkan/sftpgo#331]
Server is running: 
`{"level":"info","time":"2021-03-01T18:28:57.114","sender":"httpd","message":"server listener registered, address: [::]:8080 TLS enabled: false"}`
but unable to connect:
`curl: (7) Failed to connect to localhost port 8080: Connection refused`
using:
`docker run --name some-sftpgo -p 127.0.0.1:8080:8080 -p 2022:2022 -d "drakkan/sftpgo:edge-slim"`

I am using **edge-slim** due to CIFS mount.

**Comment by drakkan** [comment]
Hi,

this should work, are you running the `curl` command from the same server where the container is running? If this isn't the case please try:

```
docker run --name some-sftpgo -p 8080:8080 -p 2022:2022 -d "drakkan/sftpgo:edge-slim"
```

and then `curl "http://<ip where the container run>:8080/"`

**Comment by dash042** [comment]
I am trying from the same server so "localhost" was fine.
Before I did that I tried accessing the web interface in a k8s cluster where I could access port 10000 for metrics but not 8080 for administration...

**Comment by dash042** [comment]
ok I got in my own way there - I had another port open for testing.
Sorry about that!

It works!
