### ISSUE TITLE
Microsoft OneDrive support

### ISSUE THREAD

**Issue by kassemz** [drakkan/sftpgo#332]
Hi,

Are there any plans to add Microsoft OneDrive support as a storage backend?

**Comment by drakkan** [comment]
Hi,

this is not planned sorry, we are not targeting consumer cloud storage for now. Maybe we could support things like this using a plugin once we have a plugin system

**Comment by ConsoleCriminal** [comment]
Um... We use onedrive a lot on a corporate level. (And sharepoint... bleugh.)

**Comment by tooptoop4** [comment]
@ConsoleCriminal check out this other great golang tool: https://rclone.org/onedrive/
