### ISSUE TITLE
Can I disable CSRF token?

### ISSUE THREAD

**Issue by johnjelinek** [drakkan/sftpgo#333]
I'm layer-4 load balancing sftpgo containers. Is there an option to disable the CSRF token since each container wants to generate its own CSRF tokens?

**Comment by drakkan** [comment]
Hi, 

no it is not possibile, you need to use IP source affinity, this should work at layer 4.

**Comment by johnjelinek** [comment]
I'm use then AWS NLB (Network Load Balancer, so I can use load balance SSH and HTTP with the same load balancer) with stickiness turned on ... doesn't seem to be helping though. Same issue. NLB doesn't support cookie stickiness :'(

**Comment by drakkan** [comment]
I have no way to test myself, but based on the following doc

https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html

it should work, please try to contact AWS support, thank you

**Comment by johnjelinek** [comment]
The link you provided is for a legacy service.

**Comment by drakkan** [comment]
Sticky sessions seem to be supported in elbv2 as well

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/sticky-sessions.html

as said above I have no way to test the AWS load balancer.

I can try contacting some of the SFTPGo sponsors who use AWS and ask them if they can let me test this setup but of course they might not be interested in helping you.

As noted above, you are paying for AWS services and not for SFTPGo :) so try contacting AWS support. It's hard for me to believe that their load balancer service doesn't support such basic functionality. Thanks for understanding

**Comment by Solvik** [comment]
Hi !

As mentionned by @drakkan AWS'S NLB does in fact support sticky-sesions, I'm using it for SFTPgo too
With terraform you could use the following snippet, it's the one I use

```
resource "aws_lb_target_group" "sftp-api" {
  name        = "glog-nlb-group-postfix"
  port        = 8080
  protocol    = "TCP"
  target_type = "instance"
  vpc_id      = <vpc_id>

  stickiness {
    enabled = true
    type = "source_ip"
  }
}
```

The provider pull requests that implements it : https://github.com/hashicorp/terraform-provider-aws/pull/15295

Here's a screenshot for a Target Group attributes edition for a NLB : 
![image](https://user-images.githubusercontent.com/201761/109855108-2edaf580-7c58-11eb-97c5-a75f42e12f08.png)

I hope it solves your problem!

**Comment by drakkan** [comment]
Thank you @Solvik, both for providing the configuration snippet and for sponsoring the project.

I want to add that disabling cookies, JWT token and CSRF verification will significantly reduce security and we will go back to the version prior to v2, where the use of the web interface was recommended only on private networks

**Comment by johnjelinek** [comment]
The configuration mentioned in the screenshot and terraform example is already how this was configured at the time this ticket was opened. The stickiness seems to not be working as expected because refresh or clicking in the UI continues to redirect me to the main login screen. We are deploying this only in a private network, that's our use-case.

**Comment by drakkan** [comment]
Hi,

I finally tested this setup myself, it seems to work fine

![Schermata del 2021-06-08 22-37-59](https://user-images.githubusercontent.com/553263/121254541-aac58900-c8aa-11eb-9439-3874851d7fff.png)

maybe you have other issues. If you are still interested you can get support for your setup by purchasing an AMI instance from the AWS marketplace

https://aws.amazon.com/marketplace/seller-profile?id=6e849ab8-70a6-47de-9a43-13c3fa849335

thank you

**Comment by AOE-Review-Backend** [comment]
This AWS setup is only working when you use a load balancer in one subnet. (remote address is not changing)

When the load balancer has more than one subnet it is not working anymore. (switching remote address)

Your CSRF implementation is relying on the remote address (which is only for logging purposes)
https://brightsec.com/blog/6-csrf-protection-best-practices-you-must-know/#csrf-tokens

**Comment by drakkan** [comment]
> This AWS setup is only working when you use a load balancer in one subnet. (remote address is not changing)
> 
> When the load balancer has more than one subnet it is not working anymore. (switching remote address)
> 
> Your CSRF implementation is relying on the remote address (which is only for logging purposes) https://brightsec.com/blog/6-csrf-protection-best-practices-you-must-know/#csrf-tokens

SFTPGo has changed a lot since 2021. The information here is no longer current. Before asking for help please read the support policy. Thanks

**Comment by AOE-Review-Backend** [comment]
This is still valid and I checked the code and also the situation.

Didn't want to create a new issue, when there is already one having the same issue, but created a new one now.

**Comment by pepijnblom** [comment]
Same thing happening in Google Cloud running in Google Kubernetes Engine using a default ingress which creates a loadbalancer

**Comment by pepijnblom** [comment]
@AOE-Review-Backend this helped me to get it working, maybe it can help you: https://github.com/drakkan/sftpgo/issues/975#issuecomment-1239428031
