### ISSUE TITLE
Username regex validation (silently) added in v2.0?

### ISSUE THREAD

**Issue by sindrepm** [drakkan/sftpgo#334]
Hi @drakkan,

Thank you for a great piece of software!

I recently upgraded from 1.2.2 to 2.0.2 and noticed my external auth hook suddenly started to fail. After enabling verbose logging, I noticed this error:

`{"level":"debug","time":"2021-03-03T18:40:15.172","sender":"sftpd","message":"failed to accept an incoming connection: [ssh: no auth passed yet, Authentication error: could not validate password credentials: Validation error: username \"user@example.com\" is not valid, the following characters are allowed: a-zA-Z0-9-_.~]"}`

We're using sftpgo purely with external auth with our existing user database. It seems that in v2.0 you added a regex validation to the username field, which prevents us from passing email address as username. 

See: https://github.com/drakkan/sftpgo/blob/v2.0.0/dataprovider/dataprovider.go#L130

This worked fine in v1.2.2 and I did not see any mentions of this in the release notes, which was a bit surprising considering this is a breaking change.

Is there any particular reason why @ characters no longer is allowed in the username? Of course we can change our code to use a different user ID as the username, but we'd rather avoid it if possible.

Appreciate your comments on the above.

**Comment by drakkan** [comment]
Hi,

this change was part of the REST API v2, I only documented the breaking API change without providing all the details (there are a lot of breaking changes), sorry for this. 

In v1 API we used the database numeric id in the URL [paths](https://github.com/drakkan/sftpgo/blob/v1.2.2/httpd/schema/openapi.yaml#L550), we now use the username. 

This change allows to simplify the management for non SQL data providers, where we had to simulate a numeric id, and above all the use of natural keys allows to identify the same resource in the same way on different installations.

For example, if you want to load balance multiple SFTPGo instances, without a shared data provider, in v1.2.x the user "drakkan" might have ID 1 on the first instance and ID 2 on the second one, so the URL `/user/1` will identify different users on different backends and this is obviously an issue for this use case. It has now been fixed. 

The downside is that we should only use non-reserved characters within the URI, so the regex allows the characters listed in [this RFC](https://www.ietf.org/rfc/rfc3986.txt) section 2.3

> Characters that are allowed in a URI but do not have a reserved
   purpose are called unreserved.  These include uppercase and lowercase
   letters, decimal digits, hyphen, period, underscore, and tilde.

>      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~" 

I also evaluated to use URI like this ones `/users?username=....`, but this isn't an idiomatic way to identity a resource, it is generally used as filter/search parameter.

I understand this is a problem for your use case, please leave me some time to think if it's a good idea to add a setting that allows you to bypass the regular expression validation, sorry for the trouble
