### ISSUE TITLE
Ability to choose the log processing

### ISSUE THREAD

**Issue by binou-31** [drakkan/sftpgo#34]
Hi, 

I have dockerized SFTPgo service with a custom systemD script management.
It's working but i must choose a location path for the logfile with `--log-file-path` argument and i must have to mount a volume only for this. too bad...

Is it possible to have a parameter to change logger process and publish all logs to stdout/stderr ? and avoid to specify a log path and log file ?
With systemD and `LogIdentifier` parameters, it will be easy to processing logs throuth journalctl and syslog.
I can submit Dockerfile and custom SystemD script with a pull request if you want.

Thanks in advance

**Comment by mcdappdev** [comment]
@binou-31 I would love to see the Dockerfile if possible :)

**Comment by drakkan** [comment]
Hi,

You can take a look at the Dockerfile here too:

https://github.com/drakkan/sftpgo/issues/31

it logs to the standard output using a symlink and it uses a two stage build so the run environment has no build deps.

I'll try to add an option to log to the stdout directly as soon as I find some spare time, it should be not so hard. I'll investigate later, after work hours. 

If you want to contribute your dockerfile a pull request is welcome, I would like to structure the docker files in the following way:

- docker -> distribution name -> Dockerfile

I would like to add sample Dockerfiles for centos, debian and alpine as multi stage builds. These should be a starting point, then each user can make its customizations

**Comment by binou-31** [comment]
If it's as fast as my last request, it's more than perfect !! Thanks @drakkan

**Comment by dusty** [comment]
Here is a more recent version of my dockerfile with some stuff not related to this stripped out.

I added versioning for SFTPGO as well as setting some default log env variables to prevent log rotation.
```
FROM golang:1.12-alpine3.10 as sftpgo
ARG SFTPGO_VERSION=0.9.1
RUN apk add --no-cache git gcc g++ ca-certificates \
  && GO111MODULE=on go get -u github.com/drakkan/sftpgo@${SFTPGO_VERSION}

FROM alpine:3.10
RUN  apk add --no-cache tini \
  && adduser sftp -h /app -D \
  && mkdir -p /data /app/log \
  && ln -sf /dev/stdout /app/log/sftpgo.log
COPY --from=sftpgo /go/bin/sftpgo /app
COPY . /app
RUN chown sftp /data /app/id_rsa /app/log
WORKDIR /app
USER sftp
EXPOSE 2022
ENV \
  SFTPGO_CONFIG_DIR=/app \
  SFTPGO_LOG_COMPRESS=0 \
  SFTPGO_LOG_FILE_PATH=/app/log/sftpgo.log \
  SFTPGO_LOG_MAX_AGE=0 \
  SFTPGO_LOG_MAX_BACKUPS=0 \
  SFTPGO_LOG_VERBOSE=0
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/app/entrypoint"]
```

I am using this entrypoint file to generate the config file on start using whatever env variables are supplied for the DB connection
```
#!/bin/ash

cat >/app/sftpgo.json <<-EOF
{
  "sftpd": {
    "bind_port": 2022,
    "bind_address": "",
    "idle_timeout": 15,
    "max_auth_tries": 0,
    "umask": "0022",
    "upload_mode": 1,
    "banner": "sftp",
    "actions": {
      "execute_on": ["upload"],
      "command": "/app/upload",
      "http_notification_url": ""
    },
    "keys": []
  },
  "data_provider": {
    "driver": "mysql",
    "name": "$DB_DATABASE",
    "host": "$DB_HOST",
    "port": $DB_PORT,
    "username": "$DB_USERNAME",
    "password": "$DB_PASSWORD",
    "sslmode": 0,
    "connection_string": "",
    "users_table": "users",
    "manage_users": 1,
    "track_quota": 0
  },
  "httpd": {
    "bind_port": 8080,
    "bind_address": "127.0.0.1"
  }
}
EOF

exec ./sftpgo serve
```

**Comment by drakkan** [comment]
For the stdout/err log outputs I can allow an empty `log-file-path` and then log to stderr or stdout, or allow special keywords such as `stderr` or `stdout`.

What do you think about? Thanks

**Comment by drakkan** [comment]
> Here is a more recent version of my dockerfile with some stuff not related to this stripped out.
> 
> I added versioning for SFTPGO as well as setting some default log env variables to prevent log rotation.
> 
> ```
> FROM golang:1.12-alpine3.10 as sftpgo
> ARG SFTPGO_VERSION=0.9.1
> RUN apk add --no-cache git gcc g++ ca-certificates \
>   && GO111MODULE=on go get -u github.com/drakkan/sftpgo@${SFTPGO_VERSION}
> 
> FROM alpine:3.10
> RUN  apk add --no-cache tini \
>   && adduser sftp -h /app -D \
>   && mkdir -p /data /app/log \
>   && ln -sf /dev/stdout /app/log/sftpgo.log
> COPY --from=sftpgo /go/bin/sftpgo /app
> COPY . /app
> RUN chown sftp /data /app/id_rsa /app/log
> WORKDIR /app
> USER sftp
> EXPOSE 2022
> ENV \
>   SFTPGO_CONFIG_DIR=/app \
>   SFTPGO_LOG_COMPRESS=0 \
>   SFTPGO_LOG_FILE_PATH=/app/log/sftpgo.log \
>   SFTPGO_LOG_MAX_AGE=0 \
>   SFTPGO_LOG_MAX_BACKUPS=0 \
>   SFTPGO_LOG_VERBOSE=0
> ENTRYPOINT ["/sbin/tini", "--"]
> CMD ["/app/entrypoint"]
> ```
> 
> I am using this entrypoint file to generate the config file on start using whatever env variables are supplied for the DB connection

you can entirely configure `sftpgo` using env vars, no need of a config file at all, the README has examples for this

> 
> ```
> #!/bin/ash
> 
> cat >/app/sftpgo.json <<-EOF
> {
>   "sftpd": {
>     "bind_port": 2022,
>     "bind_address": "",
>     "idle_timeout": 15,
>     "max_auth_tries": 0,
>     "umask": "0022",
>     "upload_mode": 1,
>     "banner": "sftp",
>     "actions": {
>       "execute_on": ["upload"],
>       "command": "/app/upload",
>       "http_notification_url": ""
>     },
>     "keys": []
>   },
>   "data_provider": {
>     "driver": "mysql",
>     "name": "$DB_DATABASE",
>     "host": "$DB_HOST",
>     "port": $DB_PORT,
>     "username": "$DB_USERNAME",
>     "password": "$DB_PASSWORD",
>     "sslmode": 0,
>     "connection_string": "",
>     "users_table": "users",
>     "manage_users": 1,
>     "track_quota": 0
>   },
>   "httpd": {
>     "bind_port": 8080,
>     "bind_address": "127.0.0.1"
>   }
> }
> EOF
> 
> exec ./sftpgo serve
> ```

**Comment by binou-31** [comment]
> For the stdout/err log outputs I can allow an empty `log-file-path` and then log to stderr or stdout, or allow special keywords such as `stderr` or `stdout`.
> 
> What do you think about? Thanks

Personally, i prefer if `log-file-path` is empty string, then we do full stdout. it's clearer than other keyword.
By default, if empty --> syslog with stdout/stderr

**Comment by dusty** [comment]
@drakkan Amazing!  I completely missed that part of the docs.

**Comment by binou-31** [comment]
code change even faster than the last time. Wonderful !! Thanks @drakkan

**Comment by drakkan** [comment]
> code change even faster than the last time. Wonderful !! Thanks @drakkan

No problem, but the code is not tested very well, please let me know if you find any issues, thanks!

**Comment by jovandeginste** [comment]
@drakkan I was wanting for this feature too; could you forge a new 0.-release?

**Comment by drakkan** [comment]
@jovandeginste , yes but please let's wait some more days so the feature is more tested.

If you can use the latest dev version meantime you will help with testing :)

**Comment by jovandeginste** [comment]
I'm running it on our quality server with this in the systemd unit file:

```
Environment=SFTPGO_LOG_FILE_PATH=
```

Logs are now coming through with journalctl.

**Comment by drakkan** [comment]
Good, please keep it running for a while and open a new issue if you find problems, I'll do some more tests myself and hopefully a new release this weekend, thanks!

**Comment by drakkan** [comment]
@jovandeginste @dusty  if you use docker please give a look at #37 I posted my work in progress dockerfile too. 
Any suggestions are welcome, 

for example I'm a bit concerned about systemd init script for docker, see the comment there, and probably we could also fine tune some other things, for example the id 1003 can clash with an existing user. But we can also merge as is and then improve later

**Comment by binou-31** [comment]
@jovandeginste  I think `Environment` parameters in systemD does not set variable in docker process. You should set environment variable with `-e ` or `--envfile` in docker command line.
You will find an example in #37 

@drakkan I expected `SFTPGO_LOG_FILE_PATH` was an empty string by default but I notice we must force `SFTPGO_LOG_FILE_PATH=` set empty in env file to send throught journalctl/syslog

**Comment by jovandeginste** [comment]
@binou-31 @drakkan I'm not running it in Docker yet; that is planned for the coming weeks, but I don't expect issues there as it stands... I'm fairly weathered in that respect. The "log to stdout" was a very relevant feature for our "sftpgo in Docker" project (I hate hacks :smiley:)

**Comment by drakkan** [comment]
> @jovandeginste I think `Environment` parameters in systemD does not set variable in docker process. You should set environment variable with `-e ` or `--envfile` in docker command line.
> You will find an example in #37
> 
> @drakkan I expected `SFTPGO_LOG_FILE_PATH` was an empty string by default but I notice we must force `SFTPGO_LOG_FILE_PATH=` set empty in env file to send throught journalctl/syslog

`--log-file-path` is a command line option please take a look at the output of `sftpgo serve --help` or at the README. This command line option is binded, using viper, to an env var, but if you don't set the env var or you don't pass the argument then the default value is `sftpgo.log`

**Comment by drakkan** [comment]
> @drakkan I was wanting for this feature too; could you forge a new 0.-release?

I'll wait some more days before releasing a new beta sorry, I want to see if my pull request for detecting upload/download errors will be included anytime soon in pkg/sftp (see #36)

**Comment by jovandeginste** [comment]
@drakkan I've been running the master branch (updating every few days) on our QA-server; it has not failed yet.

**Comment by drakkan** [comment]
@jovandeginste , thanks for your feedback, I'll release 0.9.2 this week

please make the needed database modifications to handle this change:

https://github.com/drakkan/sftpgo/commit/df96ea7e9f19877f1644e991781efeec7aba8a99

if you have users with permissions != "*" and "upload" permission you need to add "overwrite" permission too
