### ISSUE TITLE
[BUG] webDAV returns illegible responses if it cannot access files on the requested directory

### ISSUE THREAD

**Issue by NightMachinary** [drakkan/sftpgo#340]
E.g., create some directory at `/root/bad_dir` that is not readable by `sftpgo`, and try to acess `/root` by a webDAV client.

```
{"level":"warn","time":"2021-03-09T12:21:17.225","sender":"DAV","connection_id":"DAV_c13je1ecie6mq9luiti0","message":"could not open file \"/Volumes/x/.Trashes\" for reading: open /Volumes/x/.Trashes: permission denied"}
{"level":"error","time":"2021-03-09T12:21:17.225","sender":"webdavd","message":"http: superfluous response.WriteHeader call from github.com/go-chi/chi/v5/middleware.(*compressResponseWriter).WriteHeader (compress.go:302)"}
{"level":"info","time":"2021-03-09T12:21:17.225","sender":"webdavd","elapsed_ms":3,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"192.168.1.8:52223","request_id":"c13je1ecie6mq9luiti0","uri":"http://192.168.1.56:8114/x/","user_agent":"","error":"permission denied"}
{"level":"debug","time":"2021-03-09T12:21:17.225","sender":"DAV","connection_id":"DAV_c13je1ecie6mq9luiti0","message":"connection removed, close fs error: <nil>, num open connections: 0"}
```

This bug does not exist in the FTP server; There, you'll need to try to access the faulty directory to get an error, and you can access, e.g., `/root/good_dir` without problems.

**Comment by drakkan** [comment]
Hi,

this is documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/webdav.md)

```
if an object within a directory cannot be accessed, for example due to OS permissions issues or because is a missing mapped path for a virtual folder, the directory listing will fail. In SFTP/FTP the directory listing will succeed and you'll only get an error if you try to access to the problematic file/directory
```

I think this should be fixed in https://pkg.go.dev/golang.org/x/net/webdav

**Comment by NightMachinary** [comment]
@drakkan Feel free to close the issue then.

**Comment by drakkan** [comment]
Thank you for finding the upstream issue.

We already use a customized net/webdav (upstream has very poor performance), I'll test the linked patch and I'll apply to the [sftpgo net/webdav branch](https://github.com/drakkan/net/tree/sftpgo) if it works as expected. 

Unfortunately upstream is not very responsive :(

**Comment by drakkan** [comment]
I tested the available patch. It just skip a file or a directory that returns permission denied and so it does not appear in directory listing. 

This is a good start, I'll do some more tests the next week end to understand if it is possibile to list the resource and give error when accessed instead of silently ignore it.

**Comment by drakkan** [comment]
Listing a problematic file or directory and returning an error when accessed as per SFTP/FTP is not easy and requires a discrete rewrite in net / webdav, so for now problematic files / directories are omitted.

The required changes are in my [fork](https://github.com/drakkan/net/tree/sftpgo). I'll not backport them to 2.0.x branch for now
