### ISSUE TITLE
how to configure log related setting in the json file

### ISSUE THREAD

**Issue by ledmirage** [drakkan/sftpgo#346]
hi, need some help regarding logging configuration.

i read the documentation it seems to me the log related setting (max age, max size etc) are configured via command line parameters, i cannot find them in the json config file. Can they be configured in json config file?

apologies if this is not the right place for this question.

thanks.

**Comment by drakkan** [comment]
Hi,

you can configure logging related settings via command line arguments or env vars. Can you please explain why this isn't possible for your use case?

Adding these settings to the configuration file means that we can log errors loading config file or we should log them in some hard coded way and this isn't ideal

**Comment by drakkan** [comment]
To apply a change like this you need to restart sftpgo, so you can restart it with the right flags, or you can use env vars. Env vars are available for both command line flags e configuration keys. Take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#environment-variables).

Default log settings are questionable:

- if you run sftpgo as service you don't want stdout logging
- if you run interactively you don't want file logging etc..

**Comment by ledmirage** [comment]
thanks, i will close this issue :)
