### ISSUE TITLE
cutomize login page

### ISSUE THREAD

**Issue by yannalf** [drakkan/sftpgo#347]
Thank you for your input on my previous inquery . 
Is it possible to custimoze login page , logo and color 
Regards

**Comment by drakkan** [comment]
Hi,

this is currently not possible.

SFTPGo uses [this](https://github.com/startbootstrap/startbootstrap-sb-admin-2) free bootstrap template, you can customize it to suite your needs. However please note that SFTPGo is an AGPL-3 licensed software, if you modify it please be sure to respect the license.

You can also build your own interface using the exposed REST API.

I don't plan to add these kind of customizations, at least for now, sorry
