### ISSUE TITLE
Environmental variable configuration for data_provider not working (user error?)

### ISSUE THREAD

**Issue by dusty** [drakkan/sftpgo#35]
Is this the correct syntax?  When I do not provide a configuration file and instead set these env variables it doesn't seem to be applying those values.

```
SFTPGO_DATA_PROVIDER__DRIVER=mysql
SFTPGO_DATA_PROVIDER__NAME=mydb
SFTPGO_DATA_PROVIDER__HOST=127.0.0.1
SFTPGO_DATA_PROVIDER__PORT=330
```

```
sftp    | {"level":"info","sender":"cmd","time":"2019-09-03T20:47.33.437","message":"starting SFTPGo, config dir: ., config file: sftpgo, log max size: 10 log max backups: 0 log max age: 0 log verbose: true, log compress: false"}
sftp    | {"level":"warn","sender":"config","time":"2019-09-03T20:47.33.438","message":"error loading configuration file: Config File \"sftpgo\" Not Found in \"[/app/.config/sftpgo /etc/sftpgo /app]\". Default configuration will be used: {SFTPD:{Banner:SFTPGo BindPort:2022 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0022 UploadMode:0 Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} Keys:[] IsSCPEnabled:false} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:5432 Username: Password: SSLMode:0 ConnectionString: UsersTable:users ManageUsers:1 TrackQuota:1} HTTPDConfig:{BindPort:8080 BindAddress:127.0.0.1}}"}
sftp    | 2019-09-03T20:47.33.438 WRN error loading configuration file: Config File "sftpgo" Not Found in "[/app/.config/sftpgo /etc/sftpgo /app]". Default configuration will be used.
sftp    | {"level":"warn","sender":"dataProvider","time":"2019-09-03T20:47.33.438","message":"sqlite database file does not exists, please be sure to create and initialize a database before starting sftpgo"}
sftp    | {"level":"error","sender":"cmd","time":"2019-09-03T20:47.33.438","message":"error initializing data provider: stat sftpgo.db: no such file or directory"}
sftp    | 2019-09-03T20:47.33.438 ERR error initializing data provider: stat sftpgo.db: no such file or directory
sftp exited with code 1
```

**Comment by binou-31** [comment]
`SFTPGO_DATA_PROVIDER__DRIVER` should be `SFTPGO_SFTPD__DATA_PROVIDER__DRIVER`

See exemple in README to set the execute_on

**Comment by drakkan** [comment]
The configuration looks correct, the problem seems related to this:

https://github.com/spf13/viper/issues/584

I'll investigate later. If you provide a config file your env vars will override the configured values, but with no config file the env vars will not be used

**Comment by dusty** [comment]
Thanks.  I added a default json file and it worked.

**Comment by drakkan** [comment]
As suggested in the linked viper issue I could set for each config key a default via viper with something like this:

```
viper.SetDefault("data_provider__driver", "sqlite")
```

and then create the default config using something like this:

```
ProviderConf: dataprovider.Config{
			Driver:           viper.Get("data_provider__driver"),
                        ....
```

It is a bit late in my timezone, I want to think about this a little better before writing this code

**Comment by drakkan** [comment]
I don't want to implement the manual workaround for now, sorry. It is error prone since even using reflection I have to manually type the config option name, for example

```
field, _ := reflect.TypeOf(config).Elem().FieldByName("Name")
field.Tag.Get("mapstructure")
``` 
if you find a solution that does not require to type "Name"  please write it here as code snippet and I'll will be glad to implement it, or send a pull request and it will be accepted, 

I would like something like `config.Name`, for example, so type errors cannot happen.

thanks!

**Comment by dusty** [comment]
Thanks for the update, just dropping in a default config file and overriding it with ENV variables is good enough for me.
