### ISSUE TITLE
enforcing auto data retention

### ISSUE THREAD

**Issue by codinted** [drakkan/sftpgo#351]
Is there way we can configure the data retention for various users or folders. Like after 30 days files will be deleted or archived.

**Comment by drakkan** [comment]
Hi,

this is currently not possible inside SFTPGo itself. 

Maybe we could add this feature as a plugin once we have support for a plugin system.

To add this feature we would have to periodically scan the entire filesystem and check the access / modification time of the files or store all files within the data provider. Both solutions have drawbacks. I don't plan to add this feature anytime soon sorry

**Comment by codinted** [comment]
Hi,
Thanks for the update. This is a really cool project.
Another question- is there any way to map user object to ldap schema? Currently everytime user logins using ldap auth, the user object rewrites or created based on authentication response. 
To get around this issue I am thinking of creating a base user objects according to access policies based on different access methods, folder mappings, storage types and other configs and apply/update these in the ldapauth script return object.

**Comment by drakkan** [comment]
Hi,

does the [check-password](https://github.com/drakkan/sftpgo/blob/main/docs/check-password-hook.md) hook help for your use case? 

If you want to define your users inside SFTPGo you can use this hook to validate the password against LDAP/active directory. The user will not be modified in this case.

**Comment by codinted** [comment]
Thanks for quick response. 
check password hook will work in my case.
Thanks.

**Comment by drakkan** [comment]
Hi,

you can now inspect the existing user, if any, within the ext auth hook and return an empty response if auth is ok and the user should not be updated.

This way you can still create the user if it is missing while to use the chek-password hook the user must already exist

**Comment by codinted** [comment]
wow, thanks man!!
I was reading up the doc on external_auth_hook again. I was not aware we can use the auth hook per user basis for external/internal users.
how can I enable this?

**Comment by drakkan** [comment]
Hi,

if you use the web ui you can disable the external auth hook for "internal users"

![Schermata del 2021-04-10 17-14-38](https://user-images.githubusercontent.com/553263/114274806-7a837a80-9a20-11eb-99c8-969c8a8d9819.png)

if the user does not exist, external authentication will be called, you can return a user with `external_auth_disabled` set to `true` if you want create internal users from your hook, please have a look at the OpenAPI schema for more details:

https://sftpgo.stoplight.io/docs/sftpgo/openapi.yaml/components/schemas/HooksFilter
https://github.com/drakkan/sftpgo/blob/main/httpd/schema/openapi.yaml#L1427

These changes will be included in v2.1.x (it isn't planned soon sorry) so you have to use the `edge` docker image variants or a recent build artificat.

**Comment by codinted** [comment]
ohh, got it. Nice.
Again, thanks for the quick reply!

**Comment by drakkan** [comment]
There are a lot of different questions here. Please open a new issue/discussion if there are unanswered questions/open issues thank you
