### ISSUE TITLE
[Feature Request] New backend: io/fs

### ISSUE THREAD

**Issue by qin-nz** [drakkan/sftpgo#352]
[io/fs](https://pkg.go.dev/io/fs) is official filesystem interface in go 1.16, someone may implement a new backend that use `io/fs` only.

**Comment by drakkan** [comment]
Hi,

SFTPGo is an application and not a library, the vfs implementation is an internal detail and it isn't relevant for final users. (SFTPGo is for final users not for developers)

The methods exposed in io/fs are not enough, we have to extend it with many new methods anyway and [ValidPath](https://pkg.go.dev/io/fs#ValidPath) is quite problematic for our usage.

I think this could be done in future but it is premature now, io/fs should adopted in libraries like pkg/sfp and ftpserverlib before I can consider it for SFTPGo
