### ISSUE TITLE
Inconsistency between the OpenAPI schema and actual API

### ISSUE THREAD

**Issue by ramnes** [drakkan/sftpgo#356]
Hey there, thanks for the great software!

If a test user is created through the admin interface without any kind of configuration, a `GET /users` request on the API will return something like this:

```json
[
  {
    "id": 1,
    "status": 1,
    "username": "test",
    ...
    "filesystem": {
      "provider": 0,
      "s3config": {
        "access_secret": {}
      },
      "gcsconfig": {
        "credentials": {}
      },
      "azblobconfig": {
        "account_key": {}
      },
      "cryptconfig": {
        "passphrase": {}
      },
      "sftpconfig": {
        "password": {},
        "private_key": {}
      }
    }
  }
]
```

The `s3config` and `gcsconfig` fields are inconsistent with the OpenAPI schema, which asks for a few inner fields to be required: 

```yaml
    S3Config:
      ...
      required:
        - bucket
        - region
    GCSConfig:
      ...
      required:
        - bucket
```

This difference between the schema and answer breaks the OpenAPI client generator I'm using, namely [triaxtec/openapi-python-client](https://github.com/triaxtec/openapi-python-client), which seems quite normal.

The easy fix would be to remove `required`, obviously. There is probably a way in OpenAPI to make these fields required for POST requests but not GET ones, but I don't know the specification well enough to offer a diff, I'm sorry.

It seems to me that another solution would be to make `filesystem` contain only the fields that are actually configured. This is probably the simplest and cleanest solution, but I'm not sure where to look in the codebase.

On a side note, it feels weird to me to return things such as the S3 access secret in this API endpoint. What's the rationale?

**Comment by drakkan** [comment]
Hi,

the fields are required if you define an s3 config. Anyway you are right they should be removed, then if you defined an s3 config without a bucket the validation will fail.

The returned secrets are encrypted, the rationale is that you need a way to understand if the secret is set

**Comment by ramnes** [comment]
Thanks for the insanely quick fix! <3

**Comment by drakkan** [comment]
Hi,

if you are using 2.0.x please regenerate your client definitions using the schema [here](https://github.com/drakkan/sftpgo/blob/2.0.x/httpd/schema/openapi.yaml) and please let me know if you find other issues like this, thank you!
