### ISSUE TITLE
Fails to build v1.2.2

### ISSUE THREAD

**Issue by lsowen** [drakkan/sftpgo#357]
Trying to build v1.2.2 (in preparation for upgrade to the 2.0.x branch).

```bash
git clone https://github.com/drakkan/sftpgo.git
git checkout v1.2.2
go build -i -ldflags "-s -w -X github.com/drakkan/sftpgo/utils.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/utils.date=`date -u +%FT%TZ`"  -o sftpgo
```

Failed to build with the error: `go: github.com/drakkan/crypto@v0.0.0-20201118124913-1ba5185435c1: invalid version: unknown revision 1ba5185435`.  As far as I can tell, that is valid, because if I clone `github.com/drakkan/crypto` I cannot find a revision referred to be sha `1ba5185435c1`.   Is it possible a revision wasn't pushed to that repo?

**Comment by drakkan** [comment]
Hi,

this happens because the commit hashes change each time I rebase my forks. 

If for some reason you cannot use a prebuilt binary, please use the vendored sources:

```
mkdir sftpgo
cd sftpgo
curl -O -L https://github.com/drakkan/sftpgo/releases/download/v1.2.2/sftpgo_v1.2.2_src_with_deps.tar.xz
tar xvf sftpgo_v1.2.2_src_with_deps.tar.xz
go build -ldflags "-s -w" -mod vendor -o . ./...
```

thank you

**Comment by lsowen** [comment]
hi @drakkan, would it be possible to not rebase the commits that release tags of sftpgo rely on?  We really like sftpgo (way better than the home grown mess of OpenSSH scripting we were doing), but losing the commit history of the dependencies makes it harder to code audit when we do an upgrade.

**Comment by drakkan** [comment]
Hi, you have the src_with_deps package for each release so the source are available.

Creating a separate branch each time I rebase is overkilling. 

Until my changes are merged upstream I'll try to maintain a separate branch of my forks for each active SFTPGo branch so you will be able to build the latest available minor version, for each branch, using the commands you tried above.

This means that I'll create a `sftpgo-2.0.x` branch for my [crypto](https://github.com/drakkan/crypto/tree/sftpgo) and [net](https://github.com/drakkan/net/tree/sftpgo) forks. 

I'll not create a separate branch for the [ftp client fork](https://github.com/drakkan/ftp/tree/sftpgo), it is used only in test cases and it is not required for builiding SFTPGo.

**Comment by lsowen** [comment]
@drakkan  that is awesome, I really appreciate it!

**Comment by drakkan** [comment]
Done

https://github.com/drakkan/crypto/commits/sftpgo-2.0.x
https://github.com/drakkan/net/commits/sftpgo-2.0.x
