### ISSUE TITLE
Cannot upload to Azure Blob due to wrong localTempDir

### ISSUE THREAD

**Issue by codref** [drakkan/sftpgo#359]
I'd like to use sftpgo with Azure blobs, although I'm having some difficulties with the upload.  
More precisely I do not understand if this is "by design" of it's an issue:  

The method NewAzBlobFs uses a temporary directory to support the upload. This directory is set here https://github.com/drakkan/sftpgo/blob/8a1249878add9109f879ea7086bccdbd412342d9/vfs/azblobfs.go#L56  

I struggled to find where this dir is initialized - as I was looking for a *configurable* value, although is set here https://github.com/drakkan/sftpgo/blob/8a1249878add9109f879ea7086bccdbd412342d9/dataprovider/user.go#L241 - which is the reason why the server is failing all the uploads, trying to write on `/` of my system, as I put that path in the user's home (since the web ui forces you to have something in there!).  

Am I loosing some piece - like a missing config somewhere?  
The workaround of course would be to set the home into something writable at server level - e.g. `/tmp`.  

Can you provide a better advice?

**Comment by drakkan** [comment]
Hi,

I probably need to update the docs, in the [azure docs](https://github.com/drakkan/sftpgo/blob/main/docs/azure-blob-storage.md) I wrote

> This backend is very similar to the S3 backend, and it has the same limitations.

and in [s3 docs](https://github.com/drakkan/sftpgo/blob/main/docs/s3.md):

> A local home directory is still required to store temporary files.

If you install from distro packages you have `users_base_dir` configured to `/srv/sftpgo/data`

> `users_base_dir`, string. Users default base directory. If no home dir is defined while adding a new user, and this value is a valid absolute path, then the user home dir will be automatically defined as the path obtained joining the base dir and the username

So you don't need to manually specify an home dir for each user. The user home dir will be auto created if missing but this directory must still be in a writable path

**Comment by codref** [comment]
Wow, thanks! This can be closed.  
I confirm that if the `"users_base_dir": "",` is not empty, everything works as expected!  
Would be useful to have some "warning" displayed either in the console or in the GUI to highlight wrong configuration patterns.
