### ISSUE TITLE
Service exits with a stack dump after SIGQUIT

### ISSUE THREAD

**Issue by sindrepm** [drakkan/sftpgo#360]
Hi,

I'm running multiple (unrelated) instances of sftpgo in Kubernetes, and about the same time 5 of these instances failed to terminate during a rolling update. Basically Kubernetes was trying to kill the pod but it's stuck "Terminating" because sftpgo fails to exit.

On the logs of all 5 pods this error stack trace is printed:

```
{"level":"info","time":"2021-03-23T23:01:59.113","sender":"sftpd","message":"server listener registered, address: [::]:2022"}
SIGQUIT: quit
PC=0x479bc1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x24671e8, 0x80, 0x0, 0x0, 0x0, 0xc0006c0148, 0x7ffcc501ce58, 0x47979c, 0x7ffcc501ce78, 0x413bdf, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:587 +0x21
runtime.futexsleep(0x24671e8, 0x7ffc00000000, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os_linux.go:45 +0x46
runtime.notesleep(0x24671e8)
        /usr/local/go/src/runtime/lock_futex.go:159 +0x9f
runtime.stoplockedm()
        /usr/local/go/src/runtime/proc.go:2085 +0x8d
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:2617 +0x48c
runtime.park_m(0xc000600000)
        /usr/local/go/src/runtime/proc.go:2851 +0x9d
runtime.mcall(0x2)
        /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive, 3 minutes]:
github.com/drakkan/sftpgo/service.(*Service).Wait(0xc000100c00)
        /workspace/service/service.go:222 +0x45
github.com/drakkan/sftpgo/cmd.glob..func6(0x23f3f80, 0x2498770, 0x0, 0x0)
        /workspace/cmd/serve.go:39 +0x1f8
github.com/spf13/cobra.(*Command).execute(0x23f3f80, 0x2498770, 0x0, 0x0, 0x23f3f80, 0x2498770)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x23f3d00, 0x2, 0x8, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/drakkan/sftpgo/cmd.Execute()
        /workspace/cmd/root.go:83 +0x31
main.main()
        /workspace/main.go:21 +0xc5

goroutine 94 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000120f80)
        /go/pkg/mod/go.opencensus.io@v0.22.6/stats/view/worker.go:276 +0x105
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.6/stats/view/worker.go:34 +0x68

goroutine 127 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0x7f7871405df8, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000c4f18, 0x72, 0x0, 0x0, 0x186581e)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000c4f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc0000c4f00, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0003c4500, 0x1, 0x1, 0xc0005ae000)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0003c4500, 0x1861f03, 0x5, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock.go:261 +0x65
github.com/drakkan/sftpgo/sftpd.(*Configuration).serve(0xc000632000, 0x1af5600, 0xc0003c4500, 0xc0007f7380, 0x0, 0x0)
        /workspace/sftpd/server.go:271 +0x114
github.com/drakkan/sftpgo/sftpd.(*Configuration).Initialize.func4(0xc00010e600, 0xc000632000, 0xc0007f7380, 0x0, 0x0, 0x7e6, 0x101)
        /workspace/sftpd/server.go:256 +0x18a
created by github.com/drakkan/sftpgo/sftpd.(*Configuration).Initialize
        /workspace/sftpd/server.go:235 +0x5e5

goroutine 126 [chan receive, 3 minutes]:
github.com/drakkan/sftpgo/service.registerSigUSR1.func1(0xc000201e60)
        /workspace/service/sigusr1_unix.go:17 +0x45
created by github.com/drakkan/sftpgo/service.registerSigUSR1
        /workspace/service/sigusr1_unix.go:16 +0xab

goroutine 125 [chan receive, 3 minutes]:
github.com/drakkan/sftpgo/service.registerSigHup.func1(0xc000201d40)
        /workspace/service/sighup_unix.go:23 +0x58
created by github.com/drakkan/sftpgo/service.registerSigHup
        /workspace/service/sighup_unix.go:22 +0xab

goroutine 124 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:150 +0x45

goroutine 122 [chan receive, 3 minutes]:
github.com/drakkan/sftpgo/sftpd.(*Configuration).Initialize(0xc000632000, 0xc000040072, 0x12, 0x0, 0x0)
        /workspace/sftpd/server.go:263 +0x4c5
github.com/drakkan/sftpgo/service.(*Service).startServices.func1(0xc000632000, 0xc000100c00)
        /workspace/service/service.go:149 +0x12f
created by github.com/drakkan/sftpgo/service.(*Service).startServices
        /workspace/service/service.go:147 +0x385

goroutine 120 [select]:
github.com/drakkan/sftpgo/common.startIdleTimeoutTicker.func1()
        /workspace/common/common.go:191 +0xbc
created by github.com/drakkan/sftpgo/common.startIdleTimeoutTicker
        /workspace/common/common.go:189 +0x9a

goroutine 121 [select]:
github.com/drakkan/sftpgo/dataprovider.startAvailabilityTimer.func1()
        /workspace/dataprovider/dataprovider.go:1650 +0xa8
created by github.com/drakkan/sftpgo/dataprovider.startAvailabilityTimer
        /workspace/dataprovider/dataprovider.go:1648 +0x97

rax    0xca
rbx    0x24670a0
rcx    0x479bc3
rdx    0x0
rdi    0x24671e8
rsi    0x80
rbp    0x7ffcc501ce40
rsp    0x7ffcc501cdf8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xf7
r13    0x0
r14    0x1a9d2f4
r15    0x0
rip    0x479bc1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```
I'm not exactly what to read from this, but maybe a bug causing a deadlock or something?

Here's the event log from Kubernetes:

```
 Warning  FailedKillPod  9s (x910 over 38h)  kubelet, gke-xxx-node-name  error killing pod: [failed to "KillContainer" for "sftp" with KillContainerError: "rpc error: code = Unknown desc = an error occurs during waiting for container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\" to be killed: wait container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\" stop timeout", failed to "KillPodSandbox" for "ca820a56-8bbe-4a08-9eed-5047b847e083" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to stop container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\": an error occurs during waiting for container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\" to be killed: wait container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\" stop timeout"]
```

**Comment by drakkan** [comment]
> Hi,
>
Hi
 
> I'm running multiple (unrelated) instances of sftpgo in Kubernetes, and about the same time 5 of these instances failed to terminate during a rolling update. Basically Kubernetes was trying to kill the pod but it's stuck "Terminating" because sftpgo fails to exit.
> 

I think sftpgo exits with a stack dump, this is the [default behaviour](https://golang.org/pkg/os/signal/#hdr-Default_behavior_of_signals_in_Go_programs) for Go programs. Do you want to send a patch? Thank you


> On the logs of all 5 pods this error stack trace is printed:
> 
> ```
> {"level":"info","time":"2021-03-23T23:01:59.113","sender":"sftpd","message":"server listener registered, address: [::]:2022"}
> SIGQUIT: quit
> PC=0x479bc1 m=0 sigcode=0
> 
> goroutine 0 [idle]:
> runtime.futex(0x24671e8, 0x80, 0x0, 0x0, 0x0, 0xc0006c0148, 0x7ffcc501ce58, 0x47979c, 0x7ffcc501ce78, 0x413bdf, ...)
>         /usr/local/go/src/runtime/sys_linux_amd64.s:587 +0x21
> runtime.futexsleep(0x24671e8, 0x7ffc00000000, 0xffffffffffffffff)
>         /usr/local/go/src/runtime/os_linux.go:45 +0x46
> runtime.notesleep(0x24671e8)
>         /usr/local/go/src/runtime/lock_futex.go:159 +0x9f
> runtime.stoplockedm()
>         /usr/local/go/src/runtime/proc.go:2085 +0x8d
> runtime.schedule()
>         /usr/local/go/src/runtime/proc.go:2617 +0x48c
> runtime.park_m(0xc000600000)
>         /usr/local/go/src/runtime/proc.go:2851 +0x9d
> runtime.mcall(0x2)
>         /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
> 
> goroutine 1 [chan receive, 3 minutes]:
> github.com/drakkan/sftpgo/service.(*Service).Wait(0xc000100c00)
>         /workspace/service/service.go:222 +0x45
> github.com/drakkan/sftpgo/cmd.glob..func6(0x23f3f80, 0x2498770, 0x0, 0x0)
>         /workspace/cmd/serve.go:39 +0x1f8
> github.com/spf13/cobra.(*Command).execute(0x23f3f80, 0x2498770, 0x0, 0x0, 0x23f3f80, 0x2498770)
>         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0x23f3d00, 0x2, 0x8, 0x1)
>         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
> github.com/drakkan/sftpgo/cmd.Execute()
>         /workspace/cmd/root.go:83 +0x31
> main.main()
>         /workspace/main.go:21 +0xc5
> 
> goroutine 94 [select]:
> go.opencensus.io/stats/view.(*worker).start(0xc000120f80)
>         /go/pkg/mod/go.opencensus.io@v0.22.6/stats/view/worker.go:276 +0x105
> created by go.opencensus.io/stats/view.init.0
>         /go/pkg/mod/go.opencensus.io@v0.22.6/stats/view/worker.go:34 +0x68
> 
> goroutine 127 [IO wait, 3 minutes]:
> internal/poll.runtime_pollWait(0x7f7871405df8, 0x72, 0x0)
>         /usr/local/go/src/runtime/netpoll.go:222 +0x55
> internal/poll.(*pollDesc).wait(0xc0000c4f18, 0x72, 0x0, 0x0, 0x186581e)
>         /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
> internal/poll.(*pollDesc).waitRead(...)
>         /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
> internal/poll.(*FD).Accept(0xc0000c4f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc
> net.(*netFD).accept(0xc0000c4f00, 0x0, 0x0, 0x0)
>         /usr/local/go/src/net/fd_unix.go:172 +0x45
> net.(*TCPListener).accept(0xc0003c4500, 0x1, 0x1, 0xc0005ae000)
>         /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
> net.(*TCPListener).Accept(0xc0003c4500, 0x1861f03, 0x5, 0x0, 0x0)
>         /usr/local/go/src/net/tcpsock.go:261 +0x65
> github.com/drakkan/sftpgo/sftpd.(*Configuration).serve(0xc000632000, 0x1af5600, 0xc0003c4500, 0xc0007f7380, 0x0, 0x0)
>         /workspace/sftpd/server.go:271 +0x114
> github.com/drakkan/sftpgo/sftpd.(*Configuration).Initialize.func4(0xc00010e600, 0xc000632000, 0xc0007f7380, 0x0, 0x0, 0x7e6, 0x101)
>         /workspace/sftpd/server.go:256 +0x18a
> created by github.com/drakkan/sftpgo/sftpd.(*Configuration).Initialize
>         /workspace/sftpd/server.go:235 +0x5e5
> 
> goroutine 126 [chan receive, 3 minutes]:
> github.com/drakkan/sftpgo/service.registerSigUSR1.func1(0xc000201e60)
>         /workspace/service/sigusr1_unix.go:17 +0x45
> created by github.com/drakkan/sftpgo/service.registerSigUSR1
>         /workspace/service/sigusr1_unix.go:16 +0xab
> 
> goroutine 125 [chan receive, 3 minutes]:
> github.com/drakkan/sftpgo/service.registerSigHup.func1(0xc000201d40)
>         /workspace/service/sighup_unix.go:23 +0x58
> created by github.com/drakkan/sftpgo/service.registerSigHup
>         /workspace/service/sighup_unix.go:22 +0xab
> 
> goroutine 124 [syscall, 3 minutes]:
> os/signal.signal_recv(0x0)
>         /usr/local/go/src/runtime/sigqueue.go:147 +0x9d
> os/signal.loop()
>         /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
> created by os/signal.Notify.func1.1
>         /usr/local/go/src/os/signal/signal.go:150 +0x45
> 
> goroutine 122 [chan receive, 3 minutes]:
> github.com/drakkan/sftpgo/sftpd.(*Configuration).Initialize(0xc000632000, 0xc000040072, 0x12, 0x0, 0x0)
>         /workspace/sftpd/server.go:263 +0x4c5
> github.com/drakkan/sftpgo/service.(*Service).startServices.func1(0xc000632000, 0xc000100c00)
>         /workspace/service/service.go:149 +0x12f
> created by github.com/drakkan/sftpgo/service.(*Service).startServices
>         /workspace/service/service.go:147 +0x385
> 
> goroutine 120 [select]:
> github.com/drakkan/sftpgo/common.startIdleTimeoutTicker.func1()
>         /workspace/common/common.go:191 +0xbc
> created by github.com/drakkan/sftpgo/common.startIdleTimeoutTicker
>         /workspace/common/common.go:189 +0x9a
> 
> goroutine 121 [select]:
> github.com/drakkan/sftpgo/dataprovider.startAvailabilityTimer.func1()
>         /workspace/dataprovider/dataprovider.go:1650 +0xa8
> created by github.com/drakkan/sftpgo/dataprovider.startAvailabilityTimer
>         /workspace/dataprovider/dataprovider.go:1648 +0x97
> 
> rax    0xca
> rbx    0x24670a0
> rcx    0x479bc3
> rdx    0x0
> rdi    0x24671e8
> rsi    0x80
> rbp    0x7ffcc501ce40
> rsp    0x7ffcc501cdf8
> r8     0x0
> r9     0x0
> r10    0x0
> r11    0x286
> r12    0xf7
> r13    0x0
> r14    0x1a9d2f4
> r15    0x0
> rip    0x479bc1
> rflags 0x286
> cs     0x33
> fs     0x0
> gs     0x0
> ```
> 
> I'm not exactly what to read from this, but maybe a bug causing a deadlock or something?
> 
> Here's the event log from Kubernetes:
> 
> ```
>  Warning  FailedKillPod  9s (x910 over 38h)  kubelet, gke-xxx-node-name  error killing pod: [failed to "KillContainer" for "sftp" with KillContainerError: "rpc error: code = Unknown desc = an error occurs during waiting for container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\" to be killed: wait container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\" stop timeout", failed to "KillPodSandbox" for "ca820a56-8bbe-4a08-9eed-5047b847e083" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to stop container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\": an error occurs during waiting for container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\" to be killed: wait container \"0e945350c892a4c12526ea5447b80282b478a22fd2638f2a7fb15c58e298d40d\" stop timeout"]
> ```

**Comment by drakkan** [comment]
You have to provide more info, it is expected that a program exits producing a core dump when it receives a SIGQUIT,

please take a look [here](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html).

kubernetes should send a `SIGTERM` and if the sftpgo does not exit after 30 seconds it should send a `SIGKILL`, do you have a custom configuration?

**Comment by sindrepm** [comment]
> You have to provide more info, it is expected that a program exits producing a core dump when it receives a `SIGQUIT`,
> 
> please take a look [here](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html).

You are right! The stack trace is expected, I wasn't aware of that and assumed the application had crashed.

> kubernetes should send a `SIGTERM` and, if the sftpgo does not exit after 30 seconds, it should send a `SIGKILL`, do you have a custom configuration?

I'm not running a custom configuration but on Google GKE (managed Kubernetes). Kubernetes is sending the SIGTERM/SIGKILL and sftpgo seem to catches them and exit as expected, but for some reason Kubernetes still thinks the container is running and refuse to kill it. I suspect it could be related to a [bug](https://github.com/containerd/containerd/issues/2744) in containerd. 

Is it possible that the main pid is killed but leaves a subprocess/goroutine running?

**Comment by drakkan** [comment]
> > You have to provide more info, it is expected that a program exits producing a core dump when it receives a `SIGQUIT`,
> > please take a look [here](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html).
> 
> You are right! The stack trace is expected, I wasn't aware of that and assumed the application had crashed.
> 
> > kubernetes should send a `SIGTERM` and, if the sftpgo does not exit after 30 seconds, it should send a `SIGKILL`, do you have a custom configuration?
> 
> I'm not running a custom configuration but on Google GKE (managed Kubernetes). Kubernetes is sending the SIGTERM/SIGKILL and sftpgo seems to catch the signals and exit as expected, but for some reason Kubernetes still thinks the container is running and refuse to kill it. I suspect it could be related to a [bug](https://github.com/containerd/containerd/issues/2744) in containerd. I've checked and my GKE version is using containerd 1.2.10.
> 
> Is it possible that the main pid is killed but leaves a subprocess/goroutine running?

I'm unable to reproduce, I tested this way:

```
docker kill --signal=TERM some-sftpgo
```

both the debian and the alpine image print the following log (added in v2.0.3):

```
"level":"debug","time":"2021-03-28T21:03:07.342","sender":"service","message":"Received interrupt request"}
```

and exit.

If I send a SIGQUIT this way:

```
docker kill --signal=SIGQUIT some-sftpgo
```

the running container exits printing a dump, this is expected

**Comment by drakkan** [comment]
Please reopen providing more info if you still have this issue, thank you
