### ISSUE TITLE
IP continuously requesting the sFTP container

### ISSUE THREAD

**Issue by BastienPerdriau** [drakkan/sftpgo#366]
Hello there!

We started to use the app a few months ago with an Azure integration (so with Azure File Storage and the container running on Azure Container Instance).

Since it runs, we see continuous requests from internal IPs in the logs, as following. IP changes from one instance to another, and it's always two IPs : 
```
{"level":"debug","time":"2021-03-30T07:02:22.785","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
{"level":"debug","time":"2021-03-30T07:02:22.786","sender":"connection_failed","client_ip":"10.92.0.6","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}
{"level":"debug","time":"2021-03-30T07:02:32.070","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
{"level":"debug","time":"2021-03-30T07:02:32.070","sender":"connection_failed","client_ip":"10.92.0.4","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}
```

And when we block inbound traffic from these IPs to the container, the logs are a bit different : 
```
{"level":"debug","time":"2021-03-30T08:01:38.028","sender":"sftpd","message":"failed to accept an incoming connection: read tcp 10.244.200.5:4022->10.240.255.56:52445: read: connection reset by peer"}
{"level":"debug","time":"2021-03-30T08:01:38.028","sender":"connection_failed","client_ip":"10.240.255.56","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"read tcp 10.244.200.5:4022->10.240.255.56:52445: read: connection reset by peer"}
```

It bother us because it seems to use most of the memory/cpu of the container (for nothing ?) and we have to restart it sometimes.

Do you have a clue of what it could be ? Maybe a healthcheck or something else ?

**Comment by drakkan** [comment]
Hi,

this could be an healthcheck or bots. The built-in [defender](https://github.com/drakkan/sftpgo/blob/main/docs/defender.md) could help here. However you need to know if there is an healthcheck and whitelist its IP to avoid issues

**Comment by BastienPerdriau** [comment]
Hi,

To be noticed, we are using the v1.2.2 of app.
We just tried to use the 2.0.3 and we don't see any connection attempt anymore.

We shall update our sftp in order to use this version when we update our application to use the v2 API.

Regards,

**Comment by drakkan** [comment]
If the connections come from bots, they should try to connect regardless of the SFTPGo version, however please let me know your results with 2.0.3.

I think I will also add a rate limiter before 2.1, that might help too

**Comment by drakkan** [comment]
Hi,

rate limiting is now also supported. It can also be connected to the defender and thus hosts that repeatedly exceed the configured limit can be automatically blocked

https://github.com/drakkan/sftpgo/blob/main/docs/rate-limiting.md

I think there is nothing more to do here
