### ISSUE TITLE
Content-Type error when creating a Google Cloud Storage folder 

### ISSUE THREAD

**Issue by GitRubb** [drakkan/sftpgo#367]
I've released sftpgo as a container image with the supplied Dockerfile to a GCE instance. Using the web admin interface when creating a Google Cloud Storage folder I'm seeing the following error:

"request Content-Type isn't multipart/form-data"

I've tried filling in all form fields etc. Any help with this will be much appreciated!

**Comment by drakkan** [comment]
Hi,

thank you for reporting this issue, it should be fixed now, the updated docker image will be available in about 30 minutes, as soon as the [CI](https://github.com/drakkan/sftpgo/actions/runs/709345876) ends.

**Comment by GitRubb** [comment]
What a quick fix, thank you so much!!
