### ISSUE TITLE
Virtual directory setting error report How to set

### ISSUE THREAD

**Issue by sxj1991** [drakkan/sftpgo#371]
I dont‘t know how to setting virtual directory. I follow example test,but result error.  I don't know what's wrong,if you know the reason,please give me a message,thanks！
![image](https://user-images.githubusercontent.com/51181987/114114295-2b035880-9913-11eb-9e68-d934878fe3b1.png)
![image](https://user-images.githubusercontent.com/51181987/114114314-3787b100-9913-11eb-95e0-f3433fec88d6.png)
![image](https://user-images.githubusercontent.com/51181987/114114352-45d5cd00-9913-11eb-97cb-cf8407879d91.png)
![image](https://user-images.githubusercontent.com/51181987/114114368-4ec69e80-9913-11eb-97e7-9bc2e21d25b1.png)

**Comment by drakkan** [comment]
Hi,

you have to create a virtual folder from the folders section first

![Schermata del 2021-04-09 08-16-19](https://user-images.githubusercontent.com/553263/114137096-fb9d1d80-990b-11eb-804c-0e6fda5a4017.png)

 and then reference it by name

![Schermata del 2021-04-09 08-16-52](https://user-images.githubusercontent.com/553263/114137103-ff30a480-990b-11eb-94b3-48bf4a2eaf9b.png)

**Comment by drakkan** [comment]
Please reopen if the above instructions don't work, thank you
