### ISSUE TITLE
Creating multiple sftpgo installations in one database returns foreign key error

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#372]
I need several similar sftpgo instances running; to simplify setup, I create a single database with one user, and run each sftpgo instance with its own `SFTPGO_DATA_PROVIDER__SQL_TABLES_PREFIX`. This creates the tables inside the database nicely, and the first instance runs fine.

However, when running the second instance, it fails to create its schema because:

```
database migration error: Error 1826: Duplicate foreign key constraint name 'folders_mapping_folder_id_fk_folders_id'
error initializing data provider: Error 1826: Duplicate foreign key constraint name 'folders_mapping_folder_id_fk_folders_id'
```

Apparently, the foreign key constraints are not "namespaced" with the tables prefix.

The same issue will rise for `folders_mapping_user_id_fk_users_id`.

**Comment by drakkan** [comment]
This seems MySQL specific, anyway it should work now, thank you for reporting

**Comment by jovandeginste** [comment]
Okay thanks! Was indeed with MySQL. Thanks for fixing!
