### ISSUE TITLE
[FTP] "Anonymous" account

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#373]
I'm converting old ftp servers to an sftpgo setup. One of the features I'm running into that I can't seem to find in sftpgo is the concept of an anonymous account. Basically, this is an account (with some name, eg. "anonymous") for which any password is valid.

Is this something sftpgo should support out of the box? (eg. a "anonymous" flag next to the "password" field). Or must this be solved with an external auth program?

**Comment by drakkan** [comment]
Hi,

this isn't supported, I'm unsure if add a such feature. 

In recent versions (git main) external auth and check password hooks can be disabled on a per-user basis, so an easy way could be:

1) define a [check password hook](https://github.com/drakkan/sftpgo/blob/main/docs/check-password-hook.md) with FTP only scope 
2) create an `anonymous` user.
3) disable the check password hook for all users except `anonymous`

**Comment by jovandeginste** [comment]
It works as you suggest, but this means I need to update every other user. This may be overlooked by a colleague, at any future time. Might an approach with a number of "fallback" auth hooks be an option?

**Comment by drakkan** [comment]
for backward compatibility we cannot have external auth defined within the config file and disabled by default for all the users.

In your hook you can deny authentication for any username expect `anonymous` so a wrong configuration will simply not work.

Can you please elaborate your idea about fallback hooks? If this will remain backward compatible I'll consider it, thank you

**Comment by jovandeginste** [comment]
My idea for fallback hooks, is "iterate over all authentication systems until one succeeds". This may be a setting for the whole daemon, or per user, with the same default of "false", which is what it does now.

Basically, what I have, is a number of accounts in the database, and an external auth script that says "sure!" if the account name is "anonymous" (see below).

My goals is to authenticate users, unless they log in as "anonymous" (and any password they provide).

In the normal case, they have their own space in their "homedir", otherwise it's a shared space where part (`/pub`) is public downloadable, and part (`/upload`) is writable (but not downloadable).

```bash
#!/bin/bash -eu

if [[ "${SFTPGO_AUTHD_USERNAME:=}" != "anonymous" ]]; then
  cat <<EOF
{
  "status": 0,
  "username": "",
  "home_dir": "/dev/null",
  "permissions": null
}
EOF
  exit 1
fi

cat <<EOF
{
  "status": 1,
  "username": "anonymous",
  "home_dir": "/home/ftp",
  "uid": 102,
  "gid": 65534,
  "permissions": {
    "/": [
      "list"
    ],
    "/pub/": [
      "list",
      "download"
    ],
    "/upload/": [
      "list",
      "upload"
    ]
  }
}
EOF
```

**Comment by jovandeginste** [comment]
(Small note: "until one succeeds" -> "or all fail", of course :))

**Comment by drakkan** [comment]
Hi,

I don't have time to test now (I could take a test myself later today), but something very similar to your suggestion should already be implemented:

- external auth or pre-login hook: if you return an empty response SFTPGo will check the credentials against the ones stored within the data provider
- check password hook: you can return status `2` and `to_verify` equal to the received password

I don't remember if there are any specific test cases so I'm not sure if they work as described, I'll check later.

**Comment by drakkan** [comment]
so basically try to change the first part of your script to something like this:

```
if [[ "${SFTPGO_AUTHD_USERNAME:=}" != "anonymous" ]]; then
  exit 0
fi
```

**Comment by jovandeginste** [comment]
What difference would that make?

**Comment by drakkan** [comment]
you should reach the code [here](https://github.com/drakkan/sftpgo/blob/main/dataprovider/dataprovider.go#L2392) and so the external auth hook will return the user within the data provider.

This use case is documented in this [way](https://github.com/drakkan/sftpgo/blob/main/docs/external-auth.md):

> an empty string, or no response at all, if authentication succeeds and the existing SFTPGo user does not need to be updated. Please note that in versions 2.0.x and earlier an empty response was interpreted as an authentication error

When I added this code I didn't have your use case in mind, but it should fit

**Comment by jovandeginste** [comment]
I think this was exactly the pointer I needed! Thank you so much :-)
