### ISSUE TITLE
[FTP] FileZilla complains about missing TLS session resumption on the data connection

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#374]
I have an issue starting sftpgo's ftp frontend with some TLS parameters. I am very much not an FTP expert, so I may be doing something very wrong here...

I started sftpgo with (among others) these params:

(Based on [this code/comment](https://github.com/drakkan/sftpgo/blob/main/ftpd/ftpd.go#L32-L34))

```bash
SFTPGO_FTPD__BINDINGS__0__ADDRESS=[::]
SFTPGO_FTPD__BINDINGS__0__PORT=990
SFTPGO_FTPD__BINDINGS__0__TLS_MODE=1
SFTPGO_FTPD__BINDINGS__1__ADDRESS=[::]
SFTPGO_FTPD__BINDINGS__1__PORT=21
SFTPGO_FTPD__BINDINGS__1__TLS_MODE=0
SFTPGO_FTPD__CERTIFICATE_FILE=/var/lib/sftpgo/certificate
SFTPGO_FTPD__CERTIFICATE_KEY_FILE=/var/lib/sftpgo/certificateKey
SFTPGO_FTPD__PASSIVE_PORT_RANGE__END=20010
SFTPGO_FTPD__PASSIVE_PORT_RANGE__START=20000
```

I expect connections over port 21 to be "plain", and over port 990 to require TLS.

This seems to work, and eg. curl has no issues with it. However, FileZilla complains about the "TLS session resumption". Did I miss something obvious?

![2021-04-15_16-30-36](https://user-images.githubusercontent.com/3170771/114887015-58b33a80-9e08-11eb-858d-fb73d4d5ff1c.png)

**Comment by jovandeginste** [comment]
I did more tests, and now I can't reproduce. May have been the specific device from where I was doing the previous tests. Or maybe some form of caching in the client there, I'm totally confused now! I'll check again later, close for now.

**Comment by drakkan** [comment]
Hi,

I think you are experiencing [this](https://github.com/golang/go/issues/25228). Using implicit TLS (`TLS_MODE=2`) could be a workaround if this is an issue for you, please let me know, thank you

**Comment by jovandeginste** [comment]
I digged deeper, apparently a slightly newer version of FileZilla on the issue-side.

The [changelog](https://filezilla-project.org/versions.php) contains:
> 3.53.0-rc1 (2021-03-05)
> New features:
>    Require explicit confirmation on FTP servers not supporting TLS session esumption on the data connection

I guess this is the problem here...?

**Comment by jovandeginste** [comment]
I want the "new" ftp server to behave as close as possible to the old server, but with newer ciphers and more modern management features. I think I'm still achieving that goal. Newer clients can switch to sftp (or check the "allow").

**Comment by jovandeginste** [comment]
Is this something you wish to look into, or is it really depending on the go issue upstream?

For me it will most probably not be an issue, so I don't mind to close it.

**Comment by drakkan** [comment]
I noticed this behavior some time ago, as far as I can understand it should be fixed upstream

**Comment by drakkan** [comment]
It seems I was wrong, please confirm that it works now, thank you!

**Comment by jovandeginste** [comment]
Can you clarify your question? I'll try to answer as I understand it now:

It "works" in all cases, with the caveat that recent FileZilla shows the (scary) warning. If you accept that warning, it just works.

I have only tested with limited versions of lftp, curl and FileZilla.

**Comment by drakkan** [comment]
Please test using the latest [commit](https://github.com/drakkan/sftpgo/commit/21fbcf4556b43841f95915ab2a204337a1571564), TLS session resumption should be supported now and then the warning should no longer appear

**Comment by jovandeginste** [comment]
Should/could this be available in the "edge" docker image?

**Comment by drakkan** [comment]
> Should/could this be available in the "edge" docker image?

Yes as soon as the CI builds it

https://github.com/drakkan/sftpgo/actions/runs/754711698

**Comment by jovandeginste** [comment]
Seems to work! :+1: Great work, thanks!!
