### ISSUE TITLE
[FTP] Adding passive ports without a passive IP gives error `index out of range`

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#376]
I configured the passive port range, but first forgot, then misplaced the passive ip configuration. Sftpgo then gives a confusing "index out of range" error, probably because it's searching for the passive ip and not finding it?

**Comment by drakkan** [comment]
Hi, `force_passive_ip` is not required, you can left it empty. It is useful behind NAT (you put the external ip there). It is used to reply to the `PASV` command. Modern clients should use `EPSV`.

Can you please share the problematic configuration? thank you

**Comment by jovandeginste** [comment]
The config I had was:

```
"SFTPGO_FTPD__BANNER=Ftpserv",
"SFTPGO_FTPD__BINDINGS__0__PORT=990",
"SFTPGO_FTPD__BINDINGS__0__TLS_MODE=1",
"SFTPGO_FTPD__BINDINGS__0__ADDRESS=[::]",
"SFTPGO_FTPD__BINDINGS__1__PORT=21",
"SFTPGO_FTPD__BINDINGS__1__TLS_MODE=0",
"SFTPGO_FTPD__BINDINGS__1__ADDRESS=[::]",
```

It gave an error because it was refusing PASV connections:

I then added these lines:

```
"SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=xyz",
"SFTPGO_FTPD__BINDINGS__1__FORCE_PASSIVE_IP=xyz",
```

And then it worked. But first I misplaced those lines (without the `BINDINGS__0__`).

The original configuration seems to work with `curl`, but not with `lftp` (lftp/4.8.4), which gives:

> `ls' at 0 [500 Unhandled internal error: runtime error: index out of range [1] with length 1]

This is the debug output after the password line:

```text
<--- 230 Password ok, continue   
---> PWD
<--- 257 "/" is the current directory
---> PBSZ 0
<--- 200 Whatever
---> PROT P
<--- 200 OK
---> PASV
<--- 500 Unhandled internal error: runtime error: index out of range [1] with length 1
---- Switching passive mode off
---> LIST
---> ABOR
---- Closing aborted data socket
```

**Comment by jovandeginste** [comment]
FWIW, same issue with or without SSL

**Comment by jovandeginste** [comment]
Reading through the lftp changelog, I see a number of `EPSV` related changes. Using this:

```
set prefer-epsv yes
```

seems to fix the issue.

Since I need to support as many clients as possible, I will keep the explicit IP's, but the error message should still be handled I think? (It looks like a code bug)

**Comment by drakkan** [comment]
Hi,

the error is from [here](https://github.com/fclairamb/ftpserverlib/blob/master/client_handler.go#L478). I'm a ftpservelib contributor too and I will be happy to fix, after a first quick test I'm unable to reproduce the issue:

```
<--- 257 "/" is the current directory
---> PASV
<--- 227 Entering Passive Mode (127,0,0,1,195,145)
---- Connessione del socket dei dati a (127.0.0.1) porta 50065
---- Data connection established
---> LIST
```

I have client (lftp 4.9.2) and server on localhost, I'll try harder later

**Comment by jovandeginste** [comment]
Sure! Make sure to have a proxy. I had no issue before, since the active mode worked too (until I added a proxy in between)

**Comment by drakkan** [comment]
Are you using haproxy or something else?

**Comment by jovandeginste** [comment]
Something else: Citrix NetScaler; I'm working on another issue report regarding this ...

**Comment by jovandeginste** [comment]
(I doubt the exact proxy server will have effect here, if you use it purely as a TCP reverse proxy)

**Comment by drakkan** [comment]
I'll try using haproxy

**Comment by drakkan** [comment]
It seems to work behind haproxy too, are you able to share a network dump for a plain ftp session? The password will be visible in clear text so please use a test account

**Comment by jovandeginste** [comment]
While trying to get a dump, I noticed all traffic became SSL after a point. Apparently, even though I didn't enable ssl, lftp tried to upgrade the connection (which is good, I think?)

Current configuration (ftpd):

```
"SFTPGO_FTPD__BANNER=Ftpserv",
"SFTPGO_FTPD__BINDINGS__0__PORT=990",
"SFTPGO_FTPD__BINDINGS__0__APPLY_PROXY_CONFIG=true",
"SFTPGO_FTPD__BINDINGS__0__TLS_MODE=1",
"SFTPGO_FTPD__BINDINGS__0__ADDRESS=[::]",
"SFTPGO_FTPD__BINDINGS__1__PORT=21",
"SFTPGO_FTPD__BINDINGS__1__APPLY_PROXY_CONFIG=true",
"SFTPGO_FTPD__BINDINGS__1__TLS_MODE=0",
"SFTPGO_FTPD__BINDINGS__1__ADDRESS=[::]",
"SFTPGO_FTPD__PASSIVE_PORT_RANGE__START=20000",
"SFTPGO_FTPD__PASSIVE_PORT_RANGE__END=20010",
"SFTPGO_FTPD__CERTIFICATE_FILE=/var/lib/sftpgo/certificate",
"SFTPGO_FTPD__CERTIFICATE_KEY_FILE=/var/lib/sftpgo/certificateKey",

```

The "good" log:

```
$ lftp -d ftp://xxx
---- Resolving host address...
---- 1 address found: xxx
lftp xxx:~> set ftp:ssl-allow false
lftp xxx:~> ls
---- Connecting to xxx
<--- 220 Ftpserv
---> FEAT
<--- 211- These are my features
<---  CLNT
<---  UTF8
<---  SIZE
<---  MDTM
<---  REST STREAM
<---  EPRT
<---  EPSV
<---  MLSD
<---  MLST
<---  MFMT
<---  AUTH TLS
<---  PBSZ
<---  PROT
<--- 211 end
---> CLNT lftp/4.8.4
<--- 200 Good to know
---> OPTS UTF8 ON
<--- 200 I'm in UTF8 only anyway
---> USER xx
<--- 331 OK
---> PASS yy
<--- 230 Password ok, continue   
---> PWD
<--- 257 "/" is the current directory
---> PASV
<--- 227 Entering Passive Mode (xyz,78,38)
---- Connecting data socket to (xyz) port 20006
---- Data connection established
---> LIST
<--- 150 Using transfer connection
**** data-socket: Connection reset by peer
---- Closing data socket
-rw-r--r-- 1 ftp ftp         1064 Sep 12  2019 file
<--- 226 Closing transfer connection
```

In the "bad" log, I see this after the `FEAT` list:

```
<--- 211 end
---> AUTH TLS
<--- 234 AUTH command ok. Expecting TLS Negotiation.
---> CLNT lftp/4.8.4
Certificate: [...]
  Trusted
<--- 200 Good to know      
[...]
---> PASV
<--- 227 Entering Passive Mode (xyz,78,38)
---- Connecting data socket to (xyz) port 20006
---- Data connection established
---> LIST
<--- 150 Using transfer connection
**** gnutls_handshake: The TLS connection was non-properly terminated.
---- Closing data socket
<--- 550 Issue during transfer: tls: first record does not look like a TLS handshake
```

**Comment by jovandeginste** [comment]
Now I can't link this to the passive ip anymore. Maybe there was another issue while I was setting everything up, which got mixed.

**Comment by drakkan** [comment]
tls_mode 0 means accept both cleartext and encrypted sessions.

This is for sure something to fix but I need to be able to reproduce it to provide a fix

**Comment by drakkan** [comment]
Hi,

I looked at ftpserverlib code, I'm able to reproduce using a setting like this:

```
"force_passive_ip": " ",
```

or any invalid IPv4. Could this be your case?

**Comment by drakkan** [comment]
I reported the issue [upstream](https://github.com/fclairamb/ftpserverlib/issues/235). As first step I'll validate the IP address you configure within SFTPGo

**Comment by jovandeginste** [comment]
I'm off for the day, but I'm sure I didn't configure an invalid ip. I did configure _no_ ip, and I'm not sure what that triggers in the code (didn't check)

**Comment by drakkan** [comment]
> I'm off for the day, but I'm sure I didn't configure an invalid ip. I did configure _no_ ip, and I'm not sure what that triggers in the code (didn't check)

I was able to replicate the reported issue using an IP containing a single space, any invalid IPv4 address (and so also an IPv6 address) will lead to the reported crash in ftpserverlib.

Maybe there is another case but it is not evident reading the ftpserverlib PASV related code. If you are able to reproduce please reopen providing more info. 

If you update to the latest `edge` image SFTPGo will refuse to start if the configured passive ip is not a valid IPv4 address.
Before updating you could set an invalid ip and you should replicate the issue.

**Comment by jovandeginste** [comment]
I will try to replicate, and upgrade to latest edge, after the weekend. Expect more issues to be reported ☺️ (or maybe not, I got most things working for now).

Unless you are willing to support smb as a protocol? 💀

**Comment by jovandeginste** [comment]
(And thank you so much for all your work! I'm still a very happy user of your software, and very happy to collaborate!)

**Comment by drakkan** [comment]
> I will try to replicate, and upgrade to latest edge, after the weekend. Expect more issues to be reported  (or maybe not, I got most things working for now).
> 
> Unless you are willing to support smb as a protocol?

No thanks :wink: at some point I could consider [go-smb2](https://github.com/hirochachacha/go-smb2) but it has a very small users base and I'm sure there are a lot of edge cases :sweat_smile:

**Comment by jovandeginste** [comment]
> > Unless you are willing to support smb as a protocol?
> 
> No thanks wink, at some point I could consider [go-smb2](https://github.com/hirochachacha/go-smb2) but it has a very small users base and I'm sure there are a lot of edge cases sweat_smile

This is the client side; I was talking about a SMB server .....

**Comment by drakkan** [comment]
> > > Unless you are willing to support smb as a protocol?
> > 
> > 
> > No thanks wink, at some point I could consider [go-smb2](https://github.com/hirochachacha/go-smb2) but it has a very small users base and I'm sure there are a lot of edge cases sweat_smile
> 
> This is the client side; I was talking about a SMB server .....

This is unlikely, maybe in future I could add a smb storage backend, to avoid to manually mount smb shares, this could be useful mainly for windows users, for now I suggest to use the `startup_hook` to mount shares etc..

**Comment by jovandeginste** [comment]
> This is unlikely, maybe in future I could add a smb storage backend, to avoid to manually mount smb shares, this could be useful mainly for windows users, for now I suggest to use the `startup_hook` to mount shares etc..

I believe you still misunderstand me. I mean other clients will connect to sftpgo using the smb protocol. So sftpgo would be the smb server, as it is now the (s)ftp or webdav server.

To be totally clear: I don't expect you to implement this. This is a legacy flow existing in the project I'm currently "upgrading", and I want that part to die.

**Comment by drakkan** [comment]
> > This is unlikely, maybe in future I could add a smb storage backend, to avoid to manually mount smb shares, this could be useful mainly for windows users, for now I suggest to use the `startup_hook` to mount shares etc..
> 
> I believe you still misunderstand me. I mean other clients will connect to sftpgo using the smb protocol. So sftpgo would be the smb server, as it is now the (s)ftp or webdav server.
> 
> To be totally clear: I don't expect you to implement this. This is a legacy flow existing in the project I'm currently "upgrading", and I want that part to die.

Yes, I understood, and this is unlikely to happen. 

Maybe in future I could add the client side part so you can use an smb share backend without manually mounting it, in a similar way for S3, other SFTP servers etc.
