### ISSUE TITLE
[FTP] "proxy protocol" only works for first ftp port binding

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#377]
I configure the ftpd module with two ports (bindings): 21 & 990 (plain & ssl)

The default value for `apply_proxy_config` is only applied to the first port binding, unless I explicitly specify them in the configuration.

This may also impact other protocols...?

**Comment by drakkan** [comment]
Yes, if you don't have a base configuration for a binding there is no default, you have to set all the values. The first binding has a default since it is included within the config

**Comment by jovandeginste** [comment]
OK, this is non-intuitive. Something to fix?
