### ISSUE TITLE
[FTP] Enabling proxy protocol on data connections with TLS gives TLS error

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#382]
When I configure our edge-router to add proxy protocols to both control and data connections, I get this error (with `curl`):

```
* SSL re-using session ID
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xxx:10990 
* Closing connection 0
```

(NB: my ftp server is listening on port 10990 for TLS-enabled connections)

When I only add it to the control connection, it works as expected (but without proxy headers in the data connections)

**Comment by drakkan** [comment]
Hi,

I'm not sure proxy headers must be handled on data connections, do you know other FTP servers that support this feature?

**Comment by jovandeginste** [comment]
No, no idea! I didn't know about this protocol until last week.

**Comment by drakkan** [comment]
Please take a look at the FAQ here:

https://htmlpreview.github.io/?https://github.com/Castaglia/proftpd-mod_proxy_protocol/blob/master/mod_proxy_protocol.html

it seems that proxy protocol should not be enabled on data connections

**Comment by jovandeginste** [comment]
Yes, apparently. I was expecting the client ip to be relevant there too... There is authentication, anyway...

**Comment by drakkan** [comment]
> Yes, apparently. I was expecting the client ip to be relevant there too... There is authentication, anyway...

There is no authentication, a port is negotiated on the (authenticated) control connection, if someone intercept or guess this port he can use the data connection to send arbitrary data. The only security is the TLS session resumption

**Comment by jovandeginste** [comment]
... oh my god :scream: And without TLS there is _no_ _check_ _what_ _so_ _ever_....
