### ISSUE TITLE
fail2ban sftpgo.log file location?

### ISSUE THREAD

**Issue by id4vip** [drakkan/sftpgo#384]
I want to configure sftpgo with fail2ban. Please guide me what thing I have to write on “ logpath=?”. I have setup almost everything default configuration but not able to find any sftpgo.log file anywhere. Please tell me the location of this file so that this thing works with fail2ban.
sftpgo/fail2ban/jails/sftpgo.conf

[sftpgo]

enabled = true

port = 2022

filter = sftpgo

action = iptables-allports[name=sftpgo]

logpath = ????

backend = systemd

maxretry = 5

bantime = 600

findtime = 86400

**Comment by drakkan** [comment]
Hi,

you can enable file logging using the `--log-file-path` CLI argument or the `SFTPGO_LOG_FILE_PATH` env var, please take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md).

If you are using a distro package and SFTPGo is started using the default systemd unit it reads env vars from the file `/etc/sftpgo/sftpgo.env`, see [here](https://github.com/drakkan/sftpgo/blob/main/init/sftpgo.service#L12).

So you can enable file logging this way (as root):

```
echo "SFTPGO_LOG_FILE_PATH=/srv/sftpgo/logs/sftpgo.log" > /etc/sftpgo/sftpgo.env
```

and then create the log dir and make sure that the sftpgo user can write there:

```
mkdir -p /srv/sftpgo/logs
chown sftpgo:sftpgo /srv/sftpgo/logs 
```

However I suggest to give a try to the built-in [defender](https://github.com/drakkan/sftpgo/blob/main/docs/defender.md). If you use the development version, the defender can also be integrated with the rate limiters. You can download pre-built distro packages for development version from the [actions](https://github.com/drakkan/sftpgo/actions) page

**Comment by id4vip** [comment]
Thanks, I am able to run fail2ban with this image. now i just want to add geoipblock functionality. is that thing is possible if i define the blacklisted countries. system will not allow those countries ip to connect to server. some thing like this docker compose
"https://github.com/dadatuputi/bitwarden_gcloud/blob/master/docker-compose.yml". it is good functionality to add in this software to secure our tiny server from brute forces by blocking high risk countries.
thanks & really appreciate their hard work to  sftpgo administrators & developers.

  countryblock:
    # The block script will block any country (defaults to CN and AU)
    # Requires cap_add as listed and privileged because it uses iptables and ipset
    # https://hub.docker.com/_/alpine/
    image: alpine:latest
    restart: always
    container_name: countryblock
    volumes:
    - ${PWD}/countryblock/block.sh:/block.sh:ro
    network_mode: "host"
    privileged: true
    cap_add:
    - NET_ADMIN
    - NET_RAW
    environment:
    - COUNTRIES
    - COUNTRYBLOCK_SCHEDULE
    - TZ
    command: >
      sh -c 'apk --update --no-cache add ipset iptables ip6tables wget bash tzdata &&
             ln -sf /proc/1/fd/1 /var/log/block.log &&
             echo "$COUNTRYBLOCK_SCHEDULE bash /block.sh update" >> /etc/crontabs/root &&
             crond -d 8 &&
             bash /block.sh start'

**Comment by drakkan** [comment]
Hi,

you can enable the defender modifying your config file or via env vars, please refer to the links above. 

The defender supports also blocklists/allowlists, so if you want to block the connections from a particular country you can write a small script that download the aggregated zone from some site such as this [one](https://www.ipdeny.com/ipblocks/data/aggregated/), convert them to the json format expected from sftpgo and then send a `SIGHUP` to sftpgo so it reloads the list
