### ISSUE TITLE
Virtual Folder Backends?

### ISSUE THREAD

**Issue by jasonrojas** [drakkan/sftpgo#386]
I read through some of the open issues and didn't see anyone asking this, are there any plans on adding support to allow a virtual folder to have its own S3 backend config?

For example if a user has access to:
/Folder1
/Folder2
/Some/Other/Folder

I want to be able to create the following map based on paths:

/Folder1 -> s3://bucket1/folder1
/Folder2 -> s3://bucket2/
/Some/Other/Folder -> s3://bucket3/some/other/folder

Ideally I would be determining this access based off of ldap group memberships and an external auth service that would provide the user payload back at time of authentication for dynamic user mods.

**Comment by drakkan** [comment]
Hi,

this feature is already implemented in the development version, please use the `edge` docker variant or download a recent build artificat from the [Actions](https://github.com/drakkan/sftpgo/actions) page, thank you

**Comment by jasonrojas** [comment]
@drakkan AMAZING!!! Thanks!!!! This is exactly what I am looking for!
