### ISSUE TITLE
Use dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#388]
The latest release appears to have some (unrelated) vulnerabilities in the container image.

I know we've talked about this topic a couple times before, so here are some ideas:

One way to make sure your dependencies (including container base images) are always up-to-date is using Dependabot. [Here](https://github.com/dexidp/dex/blob/master/.github/dependabot.yml) is an example configuration.

Another thing you can do is publishing images daily with the actual date attached to the image tag. A lot of floks do this, but personally I'm not a huge fan.

You can also install specific package versions instead of installing the latest. That way you can upgrade the packages when there is a vulnerability found. It's better from a build reproducability perspective, but it probably requires a lot of maintenance and I don't know about any tools that could automate this at the moment.

Anyway, setting up dependabot would be a good start IMHO.

**Comment by drakkan** [comment]
Hi,

I have considered dependabot/renovate in the past, but I have never done it in depth, I think it can create problems with the forks we use. Before updating crypto and net packages we need to rebase our patches, can be this done automatically?

**Comment by sagikazarmark** [comment]
Dependabot is not fully automated, it only creates PRs for you, so you can easily ignore packages you don't want to update. You can also use it only for Docker.

You can find a list of options for excluding a single dependency: https://github.com/dexidp/dex/pull/2094#issue-620813981

Also, I think your replaces would always win anyway.

**Comment by drakkan** [comment]
I'll give it a try, thank you

**Comment by drakkan** [comment]
Dependabot is spammy, it should open one pull request for ecosystem and not one for each dependency, this feature is not yet supported ...

**Comment by sagikazarmark** [comment]
Well, it is, but at least it keeps you on your toes and doesn't let you fall behind with dependencies. :)
