### ISSUE TITLE
admin user enumeration

### ISSUE THREAD

**Issue by kardianos** [drakkan/sftpgo#395]
As of v2.0.4, it is possible to check if a username is a valid admin user with the sqlite backend. When provided a bad username and a non-empty password, the error message will return: `not found: sql: no rows in result set`. An valid username and invalid credentials will return `invalid credentials`.

It may be beneficial to make say `invalid credentials` in both cases.

Also, thank you for your work.

**Comment by drakkan** [comment]
Thank you for noticing this. It was the same for FTP and WebDAV too (SFTP hides the underlying authentication error). It should be fixed now
