### ISSUE TITLE
enable_web_admin false doesn't function standalone

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#398]
If you set `enable_web_admin` to `false` (there is no binding with it set to `true`), you still have to set templates_path and static_files_path to empty string otherwise you get

> error loading required template: open /some/path/templates/base.html: no such file or directory

Shouldn't it check for existence of templates and static files only if they will actually be used?

On the other hand, even if you set `enable_web_admin` to true, and templates/static files are empty string, the interface will be disabled. So if you don't want to use interface at all you have to set templates_path and static_files_path to empty string, but if you want interface only one some bindings, you have to manage that using enable_web_admin.

**Comment by drakkan** [comment]
> If you set `enable_web_admin` to `false` (there is no binding with it set to `true`), you still have to set templates_path and static_files_path to empty string otherwise you get
> 
> > error loading required template: open /some/path/templates/base.html: no such file or directory
> 
> Shouldn't it check for existence of templates and static files only if they will actually be used?
> 

Thank you for reporting, I'll give a look as soon as I have some free time

> On the other hand, even if you set `enable_web_admin` to true, and templates/static files are empty string, the interface will be disabled. So if you don't want to use interface at all you have to set templates_path and static_files_path to empty string, but if you want interface only one some bindings, you have to manage that using enable_web_admin.

**Comment by sergiz** [comment]
I think that setting templates/static files to empty string is relict from https://github.com/drakkan/sftpgo/issues/131, but then you added support for multiple bindings and enable_web_admin setting for each of them. The cleanest solution would probably be to only check for existence of templates/static files if at least one binding has enable_web_admin set to true.

**Comment by drakkan** [comment]
> I think that setting templates/static files to empty string is relict from #131, but then you added support for multiple bindings and enable_web_admin setting for each of them. The cleanest solution would probably be to only check for existence of templates/static files if at least one binding has enable_web_admin set to true.

Yes, I agree. I'm working on #339 and so I'm changing this code, I'll address this issue as part of this work or after merging it

**Comment by drakkan** [comment]
Fixed in https://github.com/drakkan/sftpgo/commit/23d9ebfc91ae9414a5672ab9e7dab47766b320b2
