### ISSUE TITLE
Setting default credentials at boot time

### ISSUE THREAD

**Issue by Smana** [drakkan/sftpgo#408]
Hi there,

Sorry if the information lies somewhere in the documentation but I wasn't able to find it so far:
Is it possible to set the default credentials for the web ui and API at init time please ?

Our use case is to deploy sftpgo on Kubernetes and we'd like to secure it as well as provision users using initContainers.
Does it make sense ?

Thanks for your help

**Comment by drakkan** [comment]
Hi,

please take a look [here](https://github.com/drakkan/sftpgo/discussions/375)

**Comment by Smana** [comment]
Perfect, thank you  @drakkan !
