### ISSUE TITLE
Support for custom actions that rename files

### ISSUE THREAD

**Issue by SlvrEagle23** [drakkan/sftpgo#409]
In our workflow, we have a process by which we "sanitize" filenames that are uploaded via our web UI in order to improve compatibility with downstream applications, and have applied that same functionality via uploads from SFTPgo. 

This works fine for many purposes, but SFTPgo doesn't know that the custom action actually modified something in the directory and it should reload the directory for the user to show the changed file. If a user tries to interact with a file that was renamed in this manner, the system will return that the file doesn't exist (as it no longer does at the path the user sees).

I'm not certain of what the best way to implement this would be, but I would imagine similar to the "pre-delete" hook returning a non-zero exit code indicating that the deletion still needs to take place, if custom actions returned a certain exit code it would be an indicator to reload the directory contents before listing them to the user.

As an alternative, it would also be practical in our case to have support for a custom hook or other configuration option that would allow any newly uploaded or renamed files to be renamed via a specific process whose sole job was to take the input path and return the "sanitized" one.

**Comment by drakkan** [comment]
Hi,

the server cannot trigger a client reload, I think that the client reloads the directory contents as soon the upload ends. Your hook is executed in a separate goroutine and so the rename happen after the client reloads the directory contents. Maybe I could add a sync variant for the upload hook so sftpgo wait for the hook to finish before sending the end upload response. This could cause issues to some clients that could try to upload the file again: after an upload ends some clients check the uploaded size but in this case the expected file is not found
