### ISSUE TITLE
Exceeding Uncommitted Block Count with Azure Blob Storage

### ISSUE THREAD

**Issue by cedwards39** [drakkan/sftpgo#419]
Hi there, while testing with azure blob storage backend I am running into an issue where azure appears to have reached the limit for uncommitted blocks. I have been testing with various file sizes and occasionally the transfer is ending with EOF, seemingly before committing any blocks, which appears to be causing this.

I was reading online that there is GC built into blob storage that runs every so often to remove these but was unable to find a way to expedite that process or otherwise work around it. Sftpgo now fails as soon as it tries to upload the first part. Any help here would be much appreciated - otherwise I'm guessing I'll need to scrap and re-create the blob storage container that I'm using.

```
{"level":"debug","time":"2021-05-12T19:48:20.811","sender":"SFTP","connection_id":"SFTP_788efc03ca2dd2f9d6538ad5bfcf17843ff2b989d44abfda190ffffb6caf1028_1","message":"transfer added, id: 1, active transfers: 1"}
{"level":"debug","time":"2021-05-12T19:48:21.330","sender":"Azure Blob SAS URL \"\"","connection_id":"788efc03ca2dd2f9d6538ad5bfcf17843ff2b989d44abfda190ffffb6caf1028_1","message":"multipart upload error: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=BlockCountExceedsLimit) =====\nDescription=The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.\nRequestId:41a4bced-401e-0028-6c67-47c003000000\nTime:2021-05-12T19:48:21.3283833Z, Details: \n   Code: BlockCountExceedsLimit\n   PUT https://relexsftpstorage.blob.core.windows.net/sftp-dev-test/temp_50GB_file?blockid=aqaaaaaaaaa%3D&comp=block&se=2042-01-01t00%3A00%3A00z&sig=REDACTED&sp=rwdl&sr=c&sv=2018-11-09&timeout=240\n   Content-Length: [4194304]\n   User-Agent: [SFTPGo-2.0.2_cebd069 Azure-Storage/0.13 (go1.15.8; linux)]\n   X-Ms-Client-Request-Id: [783280a9-162d-45de-6896-7720c5ffa2a0]\n   X-Ms-Version: [2019-12-12]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 409 The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.\n   Content-Length: [269]\n   Content-Type: [application/xml]\n   Date: [Wed, 12 May 2021 19:48:20 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [783280a9-162d-45de-6896-7720c5ffa2a0]\n   X-Ms-Error-Code: [BlockCountExceedsLimit]\n   X-Ms-Request-Id: [41a4bced-401e-0028-6c67-47c003000000]\n   X-Ms-Version: [2019-12-12]\n\n\n"}
{"level":"debug","time":"2021-05-12T19:48:21.389","sender":"Azure Blob SAS URL \"\"","connection_id":"788efc03ca2dd2f9d6538ad5bfcf17843ff2b989d44abfda190ffffb6caf1028_1","message":"pool error, upload for part 1 not started"}
```

**Comment by drakkan** [comment]
Hi,

it seems this is a continuation of this [discussion](https://github.com/drakkan/sftpgo/discussions/416) (same file name, same blob storage URL). Are you trying to upload a bigger file now? Or are you trying multiple concurrent 50GB uploads? It seems you are using the default part size (4MB) this means that the total allowed size for uncommited blocks is 400GB. If you exceeds this number please increase the upload part size, it is configurable on a per-user basis.

If instead there were uncommitted blocks from previous failed transfers you can read the following troubleshooting (point 2)

https://techcommunity.microsoft.com/t5/azure-paas-blog/troubleshooting-invalidblock-the-specified-block-list-is-invalid/ba-p/1870350

or wait for the GC on the blob storage (I think it runs every 7 days)

**Comment by cedwards39** [comment]
This was really helpful, thanks! I uploaded an empty file with the same name and now everything is running smoothly.
