### ISSUE TITLE
max file upload size limit is invalid in upload_mode 2

### ISSUE THREAD

**Issue by CodyGuo** [drakkan/sftpgo#420]
1. limit size 10485760，file size 11293841
2. cancel after half of uploading files using winscp
3. select the breakpoint to resume uploading the file again
4. uploaded successfully

expect upload failure

**Comment by drakkan** [comment]
Thank you for reporting this issue, it should be fixed now. 

WinSCP, differently from OpenSSH, does not set the `APPEND` flag while resuming a file transfer, so we now detect a resume if the client uploads to an existing file and the `TRUNCATE` flag is not set.

**Comment by drakkan** [comment]
unfortunately this change, while fixing WinSCP usage, breaks some other use cases, some test cases now fail, I have to find another way

**Comment by CodyGuo** [comment]
thanks
