### ISSUE TITLE
[FTP] FileZilla still complains about missing TLS session resumption on the data

### ISSUE THREAD

**Issue by msim888** [drakkan/sftpgo#431]
Hi there!

The latest FileZilla client still complains about missing TLS session resumption on the data.
I'm using SFTPGo 2.0.4.
![fz](https://user-images.githubusercontent.com/73604538/119094731-1211bb00-ba1a-11eb-880f-d0fc7219baf4.png)
I guess that's fixed but it seems it isn't.

**Comment by drakkan** [comment]
Hi,

this is fixed in the development version, please try one of the edge variants if you are on Docker or download a recent build artifact from [here](https://github.com/drakkan/sftpgo/actions/workflows/development.yml). This fix will be included in v2.1.0

**Comment by msim888** [comment]
Thank you for the answer, drakkan!
Our SFTPGo server is not on Docker - it's working as Windows service.
Is it safe to use development version in Production?
And if yes what exactly I need to download from the link you provided and how to implement it in our working SFTPGo server?

**Comment by drakkan** [comment]
Hi,

the development version will become v2.1.0 soon, so it should be safe but you should test it yourself to be sure it works fine for your use case.

To upgrade your existing installation you can use this procedure (not tested):

- download the `sftpgo-windows-latest-go-1.16` build artifact from here
- stop the running service
- replace your `sftpgo.exe` and the `static` and `templates` folders using the ones within the build artifact
- update your `sftpgo.json` merging your changes with the new version you find within the build artifact
- restart the windows service
- check the logs if something goes wrong

I have limited free time and I don't have a definite schedule for v2.1.0, if you need more in-depth support/troubleshooting or you want I prioritize your issues (for example the v2.1.0 release) please consider a [sponsorship](https://github.com/sponsors/drakkan) thank you

**Comment by msim888** [comment]
Thank you very much, drakkan!

**Comment by msim888** [comment]
I think we can close that issue then. Will wait 2.1.0 official release.
