### ISSUE TITLE
Continue directory listing when a symlink outside the home directory is encountered

### ISSUE THREAD

**Issue by Flameborn** [drakkan/sftpgo#432]
Currently, SFTPGo does not allow symlinks that point to a location outside the defined *home* directory.

When they are encountered, however, SFTPGo stops listing the remaining directories. In my case, these are defined virtual folders.

Unless there is a security implication, I think that SFTPGo should continue listing the remaining items, essentially logging, but ignoring the encountered symlinks.

**Comment by drakkan** [comment]
Hi,

no time to test now, I suppose this happen only with webdav, can you please confirm? thank you

**Comment by Flameborn** [comment]
Hello,

Via SFTP, a symlink shows up, even if it points to a directory outside the defined home directory. Virtual folders show up properly.

On WebDav, neither shows up if the symlink is present.

**Comment by Flameborn** [comment]
Thank you very much ☺️
