### ISSUE TITLE
SFTPGo and Traefik

### ISSUE THREAD

**Issue by Nico83500** [drakkan/sftpgo#433]
Hi,
I would like to know if it's possible to use SFTPGo behind Traefik 2 ?
Thank you !

**Comment by drakkan** [comment]
Hi,

this question seems related to Traefik and not to SFTPGo. 

I tested SFTPGo behind HAProxy and it works fine (both SFTP and FTP). SFTPGo supports proxy protocol v1 and v2 too. For WebDAV and the web interfaces you can use a standard HTTP proxy (tested HAProxy, Apache, NGINX). 

So basically it should work. I have no time to test it myself, please try to follow the instructions [here](https://doc.traefik.io/traefik/routing/entrypoints/). If you want to proxy the FTP service you have to know how the FTP protocol works

**Comment by Nico83500** [comment]
Thank you, it works behind Traefik : 

>      - "traefik.enable=true"
>      - "traefik.docker.network=my_network"
>      - "traefik.http.routers.sftpgo-ui.entrypoints=https"
>      - "traefik.http.routers.sftpgo-ui.rule=Host(`sftpgo.domain.tld`)"
>      - "traefik.http.routers.sftpgo-ui.middlewares=mymiddlewares@file"
>      - "traefik.http.routers.sftpgo-ui.service=sftpgo-ui"
>      - "traefik.http.services.sftpgo-ui.loadBalancer.server.port=8080"
>      - "traefik.tcp.routers.sftpgo-sftp.entrypoints=sftpgo"
>      - "traefik.tcp.routers.sftpgo-sftp.rule=HostSNI(`*`)"
>      - "traefik.tcp.routers.sftpgo-sftp.service=sftpgo-sftp"
>      - "traefik.tcp.services.sftpgo-sftp.loadBalancer.server.port=2022"

Don't forget to add an entrypoint and the 2022 port to Traefik config.

**Comment by drakkan** [comment]
Thank you for sharing your configuration
