### ISSUE TITLE
atomic mode temp path configuration

### ISSUE THREAD

**Issue by ledmirage** [drakkan/sftpgo#436]
from the doc:

files are uploaded to a temporary path and renamed to the requested path when the client ends the upload.

from my own observation, it seems file still uploaded to the configured home folder, but it will append a suffifx (.filepart) to it. is there a way to configure it to upload to another path entirely ?

**Comment by drakkan** [comment]
Hi,

atomic uploads are not enabled by default, can you confirm that you have `upload_mode` set to `1` in your configuration file? 

The `.filepart` extension is added by some clients (maybe WinSCP), if you enable atomic uploads server side the file name will be something like this `.sftpgo-upload.c2m9s9m10d1uv456u7tg.sub.mkv`. 

The temporary file will be in the same folder as the destination file, this is the only way to guarantee atomic renaming (otherwise the rename will actually be a copy and this will cause issues)

**Comment by drakkan** [comment]
I will better evaluate your request when I have more free time. From a quick search no other similar software seems to implement what you describe, for example pure-ftpd and proftpd work the same way as SFTPGo. Do you know other similar software with this feature? Can you please better explain the rationale? The atomic upload purpose is to avoid to use the file before the upload is completed, a file named `.sftpgo-upload.c2m9s9m10d1uv456u7tg.sub.mkv` is clearly a temporary file, the end user should download the `sub.mkv` file once it appears. Maybe a most common feature is to add an option that does not allow files starting with a dot

**Comment by ledmirage** [comment]
the use case is more for machine to machine file transfer/consumption, rather than human
this is to prevent down stream app consume the file too early before the file is fully uploaded

current atomic upload (upload mode = 1) will works as well but may require code change in order for downstream app to recognize the prefix added (.sftpgo-upload.) and do not consume it if such prefix exists.

if we can have tmp folder support, then it will work with any app that monitors folder for incoming file without code change to check for filename

**Comment by ledmirage** [comment]
thanks for your consideration.

just curious, for the sponsorship, is there one time sponsor option rather than monthly?

**Comment by drakkan** [comment]
Monthly donations help keep SFTPGo development sustainable in the long run so this is the preferred option. A small amount every month is much better than a one off donation as it allows planning for the future.

If you prefer a on off donation I can setup some tiers. 

I also plan to make SFTPGo available in AWS and similar marketplaces, so buying from there will help make development and maintenance sustainable. I don't use SFTPGo in production myself. Thank you

**Comment by ledmirage** [comment]
thanks for your advice.

Availability on AWS may not be a concern for me now as I am using SFTPGo more for on premise deployment rather than cloud, for now.

**Comment by drakkan** [comment]
If you are interested, I have enabled custom amounts, they can be both monthly and one-time, thanks
