### ISSUE TITLE
how to know when  error occurs in sftpgo server 

### ISSUE THREAD

**Issue by sxj1991** [drakkan/sftpgo#437]
dear my friends， i have one  demand. I have programmer connect sftpgo server，but i dont't know how to do that 

when  error occurs in sftpgo server . i need restart my server right now but i don't know my server is closed.

if you know how to do, please tell me thanks.

**Comment by drakkan** [comment]
Hi,

I don't completely understand what you mean, sorry, can you clarify please? Maybe posting some logs could help me to better understand the issue you are trying to report. 

If you only want to monitor if the server is active you can use the health check endpoint, for example:

```
curl "http://127.0.0.1:8080/healthz"
```

**Comment by sxj1991** [comment]
hello thanks friend,but i hava other question.
 i find log only one file...for long time,this file must be more large, i uncertain sftpgo have corresponding strategy reduce sftpgo.log file size.
thanks, all the time give me help.

**Comment by drakkan** [comment]
Hi,

by default the log files are rotated when they reach 10MB and we keep 5 old log files, this is configurable, have a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

**Comment by sxj1991** [comment]
wow you are right,thanks my friend ,but I am not sure how can custom private  log properties . you know different people have different demands. 
ps: I want to subscription Twitter or YouTube  , i must be fun...lol

**Comment by drakkan** [comment]
You can pass the appropriate arguments to the `serve` subcommand or set some environment variables. Please take a look at the documentation page linked above, here are the relevant parts.

```
  -z, --log-compress           Determine if the rotated log files
                               should be compressed using gzip. This flag can
                               be set using SFTPGO_LOG_COMPRESS env var too.
                               It is unused if log-file-path is empty.
                               
  -l, --log-file-path string   Location for the log file. Leave empty to write
                               logs to the standard output. This flag can be
                               set using SFTPGO_LOG_FILE_PATH env var too.
                                (default "sftpgo.log")
  -a, --log-max-age int        Maximum number of days to retain old log files.
                               This flag can be set using SFTPGO_LOG_MAX_AGE env
                               var too. It is unused if log-file-path is empty.
                                (default 28)
  -b, --log-max-backups int    Maximum number of old log files to retain.
                               This flag can be set using SFTPGO_LOG_MAX_BACKUPS
                               env var too. It is unused if log-file-path is
                               empty. (default 5)
  -s, --log-max-size int       Maximum size in megabytes of the log file
                               before it gets rotated. This flag can be set
                               using SFTPGO_LOG_MAX_SIZE env var too. It is
                               unused if log-file-path is empty.
                                (default 10)
  -v, --log-verbose            Enable verbose logs. This flag can be set
                               using SFTPGO_LOG_VERBOSE env var too.
                                (default true)

```

**Comment by sxj1991** [comment]
my friend,I mean how to add new log field. lol

**Comment by sxj1991** [comment]
thanks my friend

**Comment by sxj1991** [comment]
hello,i change the source code.
![image](https://user-images.githubusercontent.com/51181987/120303664-a412a100-c301-11eb-8a07-1f193daba7c3.png)
i found log the log content is different due to different systems，but i don‘t know why？
this is windows
![image](https://user-images.githubusercontent.com/51181987/120304032-fa7fdf80-c301-11eb-8cbe-9bd0c9f49a7c.png)

this is centos7

![image](https://user-images.githubusercontent.com/51181987/120304316-43d02f00-c302-11eb-8d2f-1f039d2c7822.png)

i compile instruction ’go build‘

my friend if you hava idea please tell me,thank you

**Comment by sxj1991** [comment]
I find my problem, and then fix it...lol
