### ISSUE TITLE
FTP: 553 File exist (overwrite denied) 

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#442]
Hi, just a little question about overwrite permission. If I denied the overwrite permission sftpgo return the error code: 550-Could not access file: permission denied. I would propose to return: 553-File exists (overwrite denied)

**Comment by drakkan** [comment]
Hi,

this is a good suggestion but ftpservelib does not allow to customize error codes, please take a look [here](https://github.com/fclairamb/ftpserverlib/blob/master/handle_files.go#L75). So we should allow to send custom error codes in ftpserverlib to allow this feature
