### ISSUE TITLE
Suggestion: add passive ports to Docker documentation

### ISSUE THREAD

**Issue by lfritsche** [drakkan/sftpgo#447]
When trying to follow your Docker instructions: https://github.com/drakkan/sftpgo/tree/main/docker I encountered refused connections when trying to connect via FTP and FTP over TLS.

I was now able to resolve my issue and would suggest, that you add the port mapping `50000-50100:50000-50100` to the Docker instructions. Otherwise only SFTP will be available.

Thanks!

**Comment by drakkan** [comment]
Please take a look at the updated docs, thank you
