### ISSUE TITLE
SFTPGO_HTTPD__WEB_ROOT isn't work

### ISSUE THREAD

**Issue by lemonbalmleaves** [drakkan/sftpgo#448]
Hello, I'm using a docker image.
docker image: ghcr.io/drakkan/sftpgo:edge-alpine

I was following an example and the document
[https://github.com/drakkan/sftpgo/blob/main/docker/README.md#enable-webdav-service](https://github.com/drakkan/sftpgo/blob/main/docker/README.md#enable-webdav-service)
[https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#environment-variables](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#environment-variables)

But SFTPGO_HTTPD__WEB_ROOT environment is not work.
I also have modified sftpgo.json file then it's not applied

```bash
➜  dir git:(develop) ✗ docker run --name some-sftpgo \
    -p 127.0.0.1:8080:8080 \
    -p 2022:2022 \
    -e SFTPGO_HTTPD__WEB_ROOT=sftpgo \
    -d "drakkan/sftpgo:edge-alpine"
c5d4c674a6621393f42b9e0d6ea57f6a2b046378e6dc75efb82a4524e2613327
➜  dir git:(develop) ✗ curl http://127.0.0.1:8080     
<a href="/web/admin/setup">Found</a>.

➜  dir git:(develop) ✗ curl http://127.0.0.1:8080/sftpgo

{"message":"Not Found"}
➜  dir git:(develop) ✗```

**Comment by drakkan** [comment]
Hi,

please set an absolute path, otherwise, as documented, the setting will be ignored

> web_root, string. Defines a base URL for the web admin and client interfaces. If empty web admin and client resources will be available at the root ("/") URI. If defined it must be an absolute URI or it will be ignored

**Comment by lemonbalmleaves** [comment]
@drakkan my mistake. thx, it's works

**Comment by drakkan** [comment]
thank you for confirming
