### ISSUE TITLE
Web client not working

### ISSUE THREAD

**Issue by tsvane** [drakkan/sftpgo#453]
Hi.

Just fired up the docker image and transfering all the stuff from my Windows box (Filezilla). SFTP transfer and /web/admin is working fine. But /web/client is showing "The page you are looking for does not exist.". I have been scrolling the docs and as far as i can read the web client should be enabled by default.

What am i missing?

**Comment by drakkan** [comment]
Hi,

to use the web client you need to use an edge docker variant

**Comment by tsvane** [comment]
Just like that, and it is working like a charm. Does the doc need to be a bit more clear about the client part?
Anyway issue is solved :)

**Comment by drakkan** [comment]
Hi,

thank you for your sponsorship, much appreciated.

Regarding the docs if you use the 2.0.x branch you should refer to the 2.0.x [docs](https://github.com/drakkan/sftpgo/tree/2.0.x). I understand that this is not very intuitive, this ambiguity should be solved as soon as I release v2.1.0 that should happen soon

**Comment by tsvane** [comment]
Your welcome, the project is just what i was looking for as replacement service for my virtual Windows running Filezilla as i am moving as much as possible to docker on a couple of RPi and a HP MicroServer to save energy.

Your absolutely right, i mixed up the branches when i read the docs.
TBH i thought of edge as an edge service or something that you would setup in the DMZ and then proxied the connection to the backend service. TIL that edge is not always network related 😄

**Comment by drakkan** [comment]
In this case edge is the development branch :)
