### ISSUE TITLE
Support for FTPs

### ISSUE THREAD

**Issue by binou-31** [drakkan/sftpgo#46]
Many SFTP servers support the FTPS protocol too. To ensure compatibility if someone wants to use SFTPgo instead of their FTP server, it would be wise to support FTPs as well.

**Comment by drakkan** [comment]
Your request make sense but FTP is a very old protocol designed when Internet was very different from now, it is not interesting for me. 

There are many excellent FTP servers already (for example I like pure-ftpd). 

I'll accept a pull request that add this feature but I'll not work on this myself, sorry

**Comment by fdefilippo** [comment]
hello, yes i know this is a very time consuming task but using a good framework for example   https://github.com/fclairamb/ftpserver might be worth it right?  😀

**Comment by drakkan** [comment]
@fdefilippo that library looks good, anyway I think that FTP is a legacy technology, I have limited free time and I don't want to spend it to add support for something "legacy". As said before, I'll accept a well written pull request that doesn't decrease tests coverage.

Anyway I think we cannot do something better than existing FTP servers and you could also use the SFTPGo dataprovider actions to add/update/remove FTP users after you add/update/remove users in SFTPGo.

For example you can create a valid Pure-FTPd virtual user using something like this in your custom command executed after a new user is added:

```
echo "$SFTPGO_USER_USERNAME:$SFTPGO_USER_PASSWORD:$SFTPGO_USER_UID:$SFTPGO_USER_GID::$SFTPGO_USER_HOME_DIR/./::::::::::::" >> /tmp/pureftpd.passwd
pure-pw mkdb /tmp/pureftpd.pdb -f /tmp/pureftpd.passwd
```

**Comment by jeremybusk** [comment]
Agree. No reason to implement ftp as it is an old protocol and really offers no advantage over sftp as you have to deal with firewall issues because of control and data being on different ports. Converting automation ftp(s) scripts to use sftp is an easy task to do.  If I were to add another protocol it would be webdav. Sounds like a project another contributor could add to this excellent project. I've been really impressed with sftpgo.

**Comment by sergiz** [comment]
My vote also goes against this. The package should stay focused on its goal. Adding additional bloat to it will just make it harder to maintain.

**Comment by fdefilippo** [comment]
Although you think that ftp/s is an old protocol (and it is), I add non atomic, it is in fact somewhat used for data exchange. I therefore believe that support is important for sftpgo so that it can replace many products that support it.

**Comment by drakkan** [comment]
@fdefilippo I have nothing against FTP and I know that it is (still) widely used. If SFTPGo was a "corporate" product then FTP support would be a top priority for sure, but it is an open source product that I develop in my free time. I don't even use SFTPGo in production!

There are other new features to add that are more interesting for me from a technically point of view.

This doesn't mean that I'll never add FTP support myself but for now I prefer to work on other features. 
I really appreciate your comments and your suggestions, thanks!

**Comment by fclairamb** [comment]
Hi, 
I'm the maintainer of the [ftpserverlib](https://github.com/fclairamb/ftpserverlib) library which I created (forked actually) to allow people to easily build their server. Thank you @drakkan for the fixes to this library.

We all agree that FTP sucks in many ways. still, it has the huge benefit of being used on many devices and for decades. And there are still many new devices that use it. I think this library is mostly used for receiving video camera streams (that's what I built for) and creating receiving endpoints for legacy systems.

The integration can't be very difficult, it requires to at least translate the FS backend [afero calls](https://github.com/spf13/afero) to the [vfs](https://github.com/drakkan/sftpgo/blob/master/vfs/vfs.go) ones and do something similar for the logging.

That being said, I wonder if it wouldn't be simpler & cleaner to simply run an [ftpserver](https://github.com/fclairamb/ftpserver) instance connected to sftpgo itself as it already supports sftp. Changing the ftpserver to allow to forward all user/pass auth requests to another sftp server should be pretty straightforward.

**Comment by drakkan** [comment]
@fclairamb, first of all thank you for your FTP library. Its code is simple and clean and it is really easy to read/change. I evaluated other FTP libraries too and I think ftpserverlib is the best one!

I'm now working on this issue and I already integrated `ftpserverlib` in SFTPGo locally. It was very easy! I'm now refactoring some SFTPGo code so it can be shared between SFTP and FTP and in future other protocols.

I have some other changes for ftpserverlib locally, I added some convenience, optional, driver interfaces to avoid to use `afero` for transfering files. This way is much simpler to use multipart uploads for S3 backend and so achieve the best possible performance and to get notified about unexpected errors. I also plan to write a ftpserverlib patch to allow TLS only. I'll send these changes in the next days/weeks. I think supporting client certificate auth for FTP should be not so hard too but I don't plan to work on this for now.

Regarding your idea I think it will work but it will lead to suboptimal performances:

1) for plain FTP you will encrypt the data anyway connecting from ftpserver to SFTPGo via SFTP
2) for FTPS data are encrypted twice
3) we could hit some performance related issues using pkg/sftp as sftp client. 

Here are some performance numbers for my current integration inside SFTPGo.

Plain FTP:

```
ftp> put test_file.zip 
227 Entering Passive Mode (127,0,0,1,195,162)
150 Using transfer connection
226 Closing transfer connection
1055510234 bytes sent in 0,629 seconds (1,6e+03 Mbytes/s)
```

```
ftp> get test_file.zip /tmp/test.zip
227 Entering Passive Mode (127,0,0,1,195,175)
150 Using transfer connection
226 Closing transfer connection
1055510234 bytes received in 0,714 seconds (1,41e+03 Mbytes/s)
```

FTPS:

```
time curl  -k --ssl-reqd -u b:password "ftp://localhost:2121/test_file.zip" -o /tmp/a.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1006M  100 1006M    0     0   909M      0  0:00:01  0:00:01 --:--:--  909M

real	0m1,125s
user	0m0,543s
sys	0m0,507s
```

S3 (local minio) over FTP:

```
ftp> get test-file.zip /tmp/a.zip
227 Entering Passive Mode (127,0,0,1,195,159)
150 Using transfer connection
226 Closing transfer connection
1055510234 bytes received in 1,11 seconds (907 Mbytes/s)
```

S3 (local minio) over FTPS:

```
time curl -k --ssl-reqd -u tests3:password "ftp://localhost:2121/test-file.zip" -o /tmp/a.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1006M  100 1006M    0     0   555M      0  0:00:01  0:00:01 --:--:--  555M

real	0m1,888s
user	0m0,572s
sys	0m0,686s
```

I think we cannot achieve these performances without integrating ftpserverlib directly inside SFTPGo

**Comment by drakkan** [comment]
Hi all,

this feature finally shipped. 

There is something wrong with the [QuotaLimits](https://github.com/drakkan/sftpgo/blob/master/ftpd/ftpd_test.go#L621) test case that I need to better investigate, it ever fails on FreeBSD.

Anyway please let me know how it works for you. FTP support is disabled by default, you need to set a port inside the configuration file to enable it.

If you use SFTPGo at your company please consider to sponsor the project. I don't run SFTPGo in production and some form of sponsorship would help enabling me to spend my time working on the project. [GitHub sponsorship](https://github.com/sponsors/drakkan) is now enabled on my profile, thanks

**Comment by fclairamb** [comment]
Thank you for [your amazing contribution work](https://github.com/fclairamb/ftpserverlib/pulls?q=author%3Adrakkan) to the [ftpserverlib](https://github.com/fclairamb/ftpserverlib) !

**Comment by drakkan** [comment]
> Thank you for [your amazing contribution work](https://github.com/fclairamb/ftpserverlib/pulls?q=author%3Adrakkan) to the [ftpserverlib](https://github.com/fclairamb/ftpserverlib) !

@fclairamb thank you to you for merging them so quickly! I chose the right library with the right maintainer!

**Comment by drakkan** [comment]
Hi all,

if you use FTP with SFTPGo you should give a try to the latest git master, it contains several new features and fixes. 

Instead of commenting on this old issue I opened a discussion [here](https://github.com/drakkan/sftpgo/discussions/260) thanks!
