### ISSUE TITLE
"login incorrect" when log in to admin interface with other token than initial token

### ISSUE THREAD

**Issue by dani-91** [drakkan/sftpgo#461]
Hi,
when I log in to web admin interface with the same token I got on the first run when I created the initial admin user with password, then the authentification works. But if I log in from another browser or if I delete the cookies of my browser then I can't log in with no admin user at all altough I entered the correct username and password. I use the docker version, I don't know if this also happens with the normal version. The problem only appears on version 2.1.0. On 2.0.4 it works.

**Comment by drakkan** [comment]
Hi,

I'm not sure to fully understand your issue. In v2.1.0 we have the admin UI (`/web/admin`) and the client UI (`/web/client`), can you please confirm that you are trying to login to the web admin UI and not to the client UI?

**Comment by dani-91** [comment]
Hey,

thank you for the quick help. You are right, the browser forwarded me to /web/client on the new session. You can close the issue :-)

**Comment by drakkan** [comment]
Yes, by default we forward to `/web/client` (if the web client is enabled) to simplify the things for end users
