### ISSUE TITLE
Database not upgraded when upgrading to v2.1.10

### ISSUE THREAD

**Issue by Flameborn** [drakkan/sftpgo#462]
Hello,

I've just upgraded to 0c2640b. When I start SFTPGo, I get an error message about my database version (9) being too old. I'm using Postgresql as my data provider.

Unless I misunderstood something, I believe SFTPGo should auto-migrate my database, as per the README. the *initprovider* command returns this error message as well.

```
WRN Unable to initialize/update the data provider: database version 9 is too old, please see the upgrading docs
```

Is there anything I can do to upgrade my database?

**Comment by drakkan** [comment]
Hi, the supported update path is from the previous version to the current one, for example from 2.0.x to 2.1.x, you are trying to update from pre 2.1 to current git master (2.2). Please install v2.1.0 first and then you can update to git master again

**Comment by Flameborn** [comment]
Thank you very much, this makes sense.

**Comment by zvekan** [comment]
I would suggest to add check part into installer so if you try update from 2.4 to 2.6 to give error i info what to do to avoid this problem.
