### ISSUE TITLE
Issue with Cloud Storage integration

### ISSUE THREAD

**Issue by simonebruzzechesse** [drakkan/sftpgo#464]
Hi all, we are facing an issue with sftpgo integration with Google Cloud Storage. After configuring a Virtual Folder with Storage type "Google Cloud Storage" we assign permissions to a user and everything seems to work fine. The user is able to connect and, according to the permissions, upload or download files. The only issue we are experiencing is related to those folders that are empty, with no folders and files inside. Trying to CD into such folders result in an error with the following description:

`Couldn't stat remote file: No such file or directory`

Please fine below an example of the configuration required to reproduce the error.

In this example, Outbound folder is an existing folder in the GCP bucket, as we can see in the image below of the Google Cloud Platform console.

![unnamed (1)](https://user-images.githubusercontent.com/60114646/123250397-4a5d5b00-d4ea-11eb-990d-90b4a9c3630b.png)

With a sftp user that has all the permissions at bucket level, we can LS into the root folder and view both Outbound and Inbound folder.
![unnamed (2)](https://user-images.githubusercontent.com/60114646/123250585-87295200-d4ea-11eb-9d1e-f97ed806302d.png)

But we can’t cd into the "Outbound" folder.

![unnamed (3)](https://user-images.githubusercontent.com/60114646/123250650-9b6d4f00-d4ea-11eb-8641-9fca16612422.png)

Even though it is possible in the "Inbound" folder which is not empty.

![unnamed (4)](https://user-images.githubusercontent.com/60114646/123250769-be97fe80-d4ea-11eb-8041-5a131bdda9a9.png)

Did you experience the same issue? Is there something we can do to solve this issue? Of course we would like to avoid placing a dummy file in every empty folder of the bucket.

**Comment by drakkan** [comment]
Hi,

do you need to use the bucket from both the Google Cloud web console and SFTPGo? If you create the Outbound folder from SFTPGo it should work fine

**Comment by drakkan** [comment]
Please try the latest commit, SFTPGo should be compatible with Google Cloud console now

**Comment by simonebruzzechesse** [comment]
Hi,

thank you very much for the quick reply and hotfix. Since we were creating folders with GCS API we didn't notice that using an sftp client everything was working fine. Actually we figured out how to solve the issue with a dummy file with the folder name and type inode/directory. It seems to have solved our problem but we would like to test the new commit to check if we can avoid the "dummy file" workaround. We will get back to you as soon as we have tested the new feature.

Thanks again for your time and support.

**Comment by drakkan** [comment]
Hi,

the workaround you described should work. 

You can test the latest version using one of the edge docker images or by downloading a build artificat from [here](https://github.com/drakkan/sftpgo/actions/runs/968836227).

If you can, please consider a [sponsorship](https://github.com/sponsors/drakkan), this will allow me to have enough time to fix the reported issues and to improve the project in general. Thanks

**Comment by simonebruzzechesse** [comment]
Hi,

We were able to test the newer version of the software and everything seems to work fine now. We were able to upload files and work with folders in genereal both from Cloud Console and SFTPGO client. Thanks a lot for your support. We are currently evaluating the software, we will definetely consider a sponsorship in the future.

Best regards,
Simone
