### ISSUE TITLE
Is it safe to run multiple instances of sftpgo?

### ISSUE THREAD

**Issue by stephan2012** [drakkan/sftpgo#466]
Can you run sftpgo safely with multiple instances on the same data?

I have deployed sftpgo to a Kubernetes cluster and run it in multiple instances. All share a Ceph Filesystem, which also hosts the SQLite database. External requests enter the cluster through a Kubernetes Ingress so that any instance may serve the request. While file serving seems to work fine, I have noticed that an obtained token for the REST API works for the issuing instance only. The [docs](https://github.com/drakkan/sftpgo/blob/main/docs/rest-api.md) say

> WT tokens are not stored and we use a randomly generated secret to sign them so if you restart SFTPGo all the previous tokens will be invalidated and you will get a 401 HTTP response code.

So, sftpgo currently does not really support running behind a load balancer? Would it be sufficient to share the secret somehow?

**Comment by drakkan** [comment]
Hi,

I don't recommend to point multiple instances to the same SQLite database, you could randomically get a "database is locked" error. Please use PostgreSQL/MySQL if you want to share the same database. CockroachDB is a good choice if you want a distributed database.

For the HTTP part, you currently have to configure persistent connections to the same server.

**Comment by stephan2012** [comment]
@drakkan, thanks for your feedback. Much appreciated. 

I will leave it up to you to close this issue or take shared secrets for the token generation as a feature request.

**Comment by drakkan** [comment]
> @drakkan, thanks for your feedback. Much appreciated.
> 
> I will leave it up to you to close this issue or take shared secrets for the token generation as a feature request.

Hi,

I'll add this new setting to the configuration file:

```
"signing passphrase": "",
```

if empty, default, SFTPGo will work as now: a different signing key will be generated each time SFTPGo starts. 

For your use case you could set the same passphrase on all your nodes so the tokens/csrf will be valid on every node

**Comment by stephan2012** [comment]
Cool, thanks. This is a perfect fit for running sftpgo in Kubernetes.

**Comment by stephan2012** [comment]
By the way, when sftpgo would accept the secret as an environment variable, one can populate it directly from a Kubernetes Secret.

**Comment by drakkan** [comment]
> By the way, when sftpgo would accept the secret as an environment variable, one can populate it directly from a Kubernetes Secret.

Exactly. You could also rotate this secret periodically for added security
