### ISSUE TITLE
uid/gid not write in fs users create in sftpgo

### ISSUE THREAD

**Issue by jamishwork** [drakkan/sftpgo#467]
Hello, I hope you are well! I wanted to consult you, since I am trying to configure an access and I need the user to have the same uid and gid in the fs, and it is not taking me. It writes me the files that I am uploading with uid = 1000 and gid = 99, how can I get it to write the uid / gid that I have in the fs? Thank you very much in advance

**Comment by drakkan** [comment]
Hi,

you can simply run sftpgo using your fs user. Alternately you can change the fs permissions to match the ones of the sftpgo user. Are you using SFTPGo on docker or from distro packages? I need more details to give you exact instructions

**Comment by lnieva** [comment]
Hi, 
The same thing happened to me, in the web environment I specify the uid and gid, but when I connect by sftp with the user and create a file, it gives me the uid of sftpgo and not the one I configured

**Comment by drakkan** [comment]
> Hi,
> The same thing happened to me, in the web environment I specify the uid and gid, but when I connect by sftp with the user and create a file, it gives me the uid of sftpgo and not the one I configured

Hi,

you need to execute sftpgo as root for this to work

**Comment by lnieva** [comment]
I have it in a docker, the docker runs with root and in DockerFile I delete the USER 1000: 1000, but it remains the same, it does not generate the chown with the uid / gid that I configure

**Comment by drakkan** [comment]
> I have it in a docker, the docker runs with root and in DockerFile I delete the USER 1000: 1000, but it remains the same, it does not generate the chown with the uid / gid that I configure

Just tested, it works for me, I used this Dockerfile

```
FROM drakkan/sftpgo
USER root
```

I built the new image and ran it. From the web UI, I added a new user with UID 101 and GID 102 and the uploaded files have this UID/GID

**Comment by lnieva** [comment]
I am using the Dockerfile that you have in sftpgo / Dockerfile, if I use it it doesn't work for me, but the one you gave me yes, will there be any difference?

**Comment by drakkan** [comment]
> I am using the Dockerfile that you have in sftpgo/Dockerfile, if I use it it doesn't work for me, but the one you gave me yes, will there be any difference?

The image generated from the default Dockerfile does not run as root user. To be able change uid/gid you must be root. If a chown fails there is a specific log too
