### ISSUE TITLE
Create admin user/password

### ISSUE THREAD

**Issue by tekkisse** [drakkan/sftpgo#468]
can not find any documentation suggesting that the initial admin user and password can be created as part of the setup configuration ?  Am i missing something here ?

there is reference to loading "initial data" but no idea what this means ??

**Comment by drakkan** [comment]
Please take a look at the [getting started guide](https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md#Initial-configuration). This feature is supported in v2.1

**Comment by tekkisse** [comment]
awesome answer - i search everywhere.  Your getting started guide is great, not sure how i missed the link to this.

We hope to put this in production and if we do i will see about our company becoming a sponsor, thanks for what look like a great balance of features

**Comment by drakkan** [comment]
> Is there a possibility to create an initial user in config file?

In the development version (future v2.2) you can create the initial admin using env vars, please search for `create_default_admin` [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

**Comment by dsfrederic** [comment]
@drakkan Thanks for your reply! 

What does this sentence mean? 
> "You can also create the first admin by loading initial data."

I didn't provide any user AFAIK and I'm not prompted to setup a new admin user. (I've even tried to remove the created config files .db etc and restarted the container) Is there any method to find the existing admin user?

**Comment by drakkan** [comment]
> @drakkan Thanks for your reply!
> 
> What does this sentence mean?
> 
> > "You can also create the first admin by loading initial data."
> 
> I didn't provide any user AFAIK and I'm not prompted to setup a new admin user. (I've even tried to remove the created config files .db etc and restarted the container) Is there any method to find the existing admin user?

Please take a look [here](https://github.com/drakkan/sftpgo/discussions/375) for an example. You can find more info about loading data [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)
