### ISSUE TITLE
about quot Quota size (bytes) problem

### ISSUE THREAD

**Issue by sxj1991** [drakkan/sftpgo#469]
hello my friend，i have a problem need your help.
![image](https://user-images.githubusercontent.com/51181987/124535296-7660d080-de48-11eb-9505-2954f2bb54b4.png)
i use filezilla upload file，quot Quota size is historical capacity but actual capacity is 0 kb. upload is failed
![image](https://user-images.githubusercontent.com/51181987/124537989-7f07d580-de4d-11eb-941d-cbbeea5500e6.png)
if you know how to do, please tell me thanks.

**Comment by drakkan** [comment]
If you removed the files outside SFTPGo, you have to select the user and click "Quota scan" from the web UI

**Comment by sxj1991** [comment]
thanks my friend
