### ISSUE TITLE
Idle timeout 

### ISSUE THREAD

**Issue by mauriceleejy** [drakkan/sftpgo#471]
Hello

I have a nodejs application running with `ssh2` module. `ssh2` has a keepalive mechanism which periodically sends data to the server but from my testing, it does not seem to prolong the connection to SFTPGo server (connection is still closed due to idle_timeout). 

```
keepaliveInterval - integer - How often (in milliseconds) to send SSH-level keepalive packets to the server (in a similar way as OpenSSH's ServerAliveInterval config option). Set to 0 to disable. Default: 0

keepaliveCountMax - integer - How many consecutive, unanswered SSH-level keepalive packets that can be sent to the server before disconnection (similar to OpenSSH's ServerAliveCountMax config option). Default: 3
```

Can I check how does SFTPGo determine idleness?

**Comment by drakkan** [comment]
Hi,

an ssh client open a connection and on this connection it can open several sessions such as SFTP, SSH commands etc. 

SFTPGo determine idleness for SFTP sessions based on the last received command, so an high level method. If you keep open an SFTP connection without sending any command for more than 15 minutes (by default) the session will be closed. If the SSH connection has no active sessions for more than 3 minutes it will be closed too. 

So if you want to keep alive an SFTP session you have to periodically send an SFTP command, for example you can request the current dir.

**Comment by mauriceleejy** [comment]
Hello

I have tested periodically sending an SFTP command to read current directory and the connection does not timeout. 

You are right, seems like my client can only detect when the connection is down and not the session itself. 

Thank you for your help!
