### ISSUE TITLE
Enviroment variables not working

### ISSUE THREAD

**Issue by Kareltje1980** [drakkan/sftpgo#474]
Hi,

Thanks for the software, it is much appreciated!

Docker image: drakkan/sftpgo
Sftpgo version: 2.1.0
I use a docker-compose.yaml to disable the web client using the enviroment variables as follows:

```
 environment:
      - SFTPGO_COMMON__DEFENDER__ENABLED=true 
      - SFTPGO_DATA_PROVIDER__USERS_BASE_DIR=/data/prodigy/FTP
      - SFTPGO_HTTPD__BINDINGS__ENABLE_WEB_CLIENT=true
      - SFTPGO_HTTPD__BINDINGS__ENABLE_WEB_ADMIN=false
```

I expect it to turn of the web client, but still allow the admin account. The first 2 work but Client and Admin are both ignored. I checked the json file, and there I can see the settings for both stay on true. Unfortunatly it is not possible to edit that file.

Thanks again.

**Comment by drakkan** [comment]
Hi,

please take a look at the docs [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#environment-variables). Bindings are a list you have to use something like `SFTPGO_HTTPD__BINDINGS__0__ENABLE_WEB_CLIENT`

**Comment by Kareltje1980** [comment]
Thanks, that was the solution!!
