### ISSUE TITLE
sftp go support master/slave ?

### ISSUE THREAD

**Issue by fangaofeng** [drakkan/sftpgo#475]
i have two host ,  with keeplived for ha.  how to config sftpgo sync folders and files?

**Comment by drakkan** [comment]
Hi,

SFTPGo is not a sync solution. 

You can use a distributed data provider such as cockroach if you want to replicate your data (users etc..) or you can simply point multiple SFTPGo instances to the same database. If you use a cloud based storage provider this is enough. For local storage you can use something like ceph, drbd etc.. Anyway this must be configured outside SFTPGo
