### ISSUE TITLE
sftpgo upload hava problem

### ISSUE THREAD

**Issue by sxj1991** [drakkan/sftpgo#479]
today , i try upload file find No such file or directory problem.

but i see my server directory is exist.

![image](https://user-images.githubusercontent.com/51181987/125590377-60a14b6c-702e-4f25-9116-6be159a4a9d4.png)
![image](https://user-images.githubusercontent.com/51181987/125590453-6aaddef7-a0d7-49eb-a289-b2a552b7be8d.png)

if you know  reason , please tell me why，thanks my friend
![image](https://user-images.githubusercontent.com/51181987/125593440-ba78ab34-0431-4030-aa92-af7a6687727e.png)

**Comment by drakkan** [comment]
Hi,

it is hard to help you without any other info. You have enabled atomic uploads, so when you upload a new file it is first saved to a temporary location and then renamed to the final one. From the log above the rename fail. The temporary file may have been deleted/renamed by another process, for example. You have to understand what happen on your server this is something that generally works fine

**Comment by sxj1991** [comment]
yeah you are right, I have fixed this bug.I have a other program that deleted files,and i forgot this thing.

Thank you for taking the time to answer my doubts
