### ISSUE TITLE
[GCS] - credential storage location

### ISSUE THREAD

**Issue by nrx-ops** [drakkan/sftpgo#480]
Hi,
I deployed sftpgo in gke with postgres backend.
It works fine but I was a bit surprised when I try to connect a user to a GCS backend:
When I configure my user, his json key is stored on pod fs. I workaround it, using a volume desdicated to these files but I wonder why json file is not stored in DB.
There is a way to store json credz in config DB?

**Comment by drakkan** [comment]
Hi,

please take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md), you can set `prefer_database_credentials` to `true`

**Comment by silent-lad** [comment]
The doc states this setting will be removed in future so is there any alternative provided for the same?
 
 `Deprecation warning: this setting is deprecated and it will be removed in future versions, we'll use true as default and will remove prefer_database_credentials and credentials_path.`

**Comment by drakkan** [comment]
> The doc states this setting will be removed in future so is there any alternative provided for the same?
> 
> `Deprecation warning: this setting is deprecated and it will be removed in future versions, we'll use true as default and will remove prefer_database_credentials and credentials_path.`

Hi,

`prefer_database_credentials` is now `true` by default in the development version, in future versions we'll remove `prefer_database_credentials` and `credentials_path` and we'll always store credentials in the database. 

Do you need to store your credentials on disk? I think it was a mistake to store the credentials on disk in the first place

**Comment by silent-lad** [comment]
I can't find docs to have a single gcs creds to be persist on the pods.
My usecase is 
1. We don't have to reupload new gcp service account json for each user
2. Everytime the pods are reloaded/deleted the service account gets lost.

**Comment by silent-lad** [comment]
Ah okay. No I needed to store it in DB only I thought you are removing that feature only. Thanks for the clarification 😄
