### ISSUE TITLE
Running the Docker image on fargate doesn't work

### ISSUE THREAD

**Issue by antipopp** [drakkan/sftpgo#482]
I'm trying to deploy the image through AWS ECS/Fargate. It runs ok but whatever way I try to access either the admin platform or the SFTP server it gets timed out.

I don't understand if the basic Docker image needs extra configurations, I'm just expermienting with it and I don't need much stuff.

These are the env vars I pass to the container:
AWS_ACCESS_KEY_ID=key
AWS_SECRET_ACCESS_KEY=key
AWS_REGION=eu-south-1
AWS_BUCKET=bucketname
SFTPGO_HTTPD__BINDINGS__0__ADDRESS=localhost
SFTPGO_SFTPD__BINDINGS__0__ADDRESS=localhost

Port mapping:
Host: 8080 Container: 8080 TCP
Host: 2022 Container: 2022TCP

On the ECS configs I've also set awsvpc as Network Mode, my other containers work just fine

**Comment by drakkan** [comment]
Hi,

please try to remove these env vars:

```
SFTPGO_HTTPD__BINDINGS__0__ADDRESS=localhost
SFTPGO_SFTPD__BINDINGS__0__ADDRESS=localhost
```

**Comment by antipopp** [comment]
My bad! Network Security Groups blocked me out of the task. Sorry for bothering.
