### ISSUE TITLE
S3 - enable public-read

### ISSUE THREAD

**Issue by spmfox** [drakkan/sftpgo#484]
(Thank you for your help with the previous issue)

Is there an easy way to allow public reads (--acl public-read) for S3 storage? I know this is probably what most people would not want, so I'm okay if this is something that has to be edited or patched when building a custom version.

I see that 'storage class' is exposed in the GUI but I don't see an option for enabling the public read ACL.

**Comment by drakkan** [comment]
Hi,

SFTPGO currently doesn't set any ACL. I could add this feature in future. But I have to map ACL to chmod/chown SFTP commands too, and this is not so easy.  Can't this be set as the default at bucket level or for a specific prefix?

**Comment by spmfox** [comment]
Sorry I'm still new at S3, I figured out how to enable a policy on the bucket for public read on all existing and future files so I think we are good here.

Thank you again for the help.
