### ISSUE TITLE
Listing directory doesn't work with Azurite

### ISSUE THREAD

**Issue by zjajo** [drakkan/sftpgo#487]
Repro steps:
- just try to connect to Azurite container

Logs:
{"level":"warn","time":"2021-07-27T13:01:24.361","sender":"SFTP","connection_id":"SFTP_ab8ad8b70e9f6db16f41159189023e7c005d94fa_1","message":"could not open file \"\" for reading: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.13.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=) =====\nDescription=failed to unmarshal response body, Details: (none)\n GET http://127.0.0.1:10000/devstoreaccount1/ftp-test/?timeout=31536001\n Authorization: REDACTED\n User-Agent: [SFTPGo-2.1.0_a09cf5c8 Azure-Storage/0.13 (go1.16.5; linux)]\n X-Ms-Client-Request-Id: [f473bc3a-bbbe-417c-4812-be8cc376eb27]\n X-Ms-Date: [Tue, 27 Jul 2021 13:01:24 GMT]\n X-Ms-Version: [2019-12-12]\n --------------------------------------------------------------------------------\n RESPONSE Status: 404 Not Found\n Content-Length: [19]\n Content-Type: [text/plain; charset=utf-8]\n Date: [Tue, 27 Jul 2021 13:01:24 GMT]\n X-Content-Type-Options: [nosniff]\n\n\nEOF\n"}

**Comment by drakkan** [comment]
Hi,

it works for me using azurite 3.14.0, here is my configuration

![Schermata del 2021-07-27 15-38-56](https://user-images.githubusercontent.com/553263/127163820-363dea4c-df0b-43d3-a1ad-c4ee0d062127.png)

Please provide more info, thank you

**Comment by zjajo** [comment]
Hi,

there was nothing in Azurite logs, but I could make it work by changing Endpoint to Docker image IP address. For some reason it didn't work with port forwarding. 

Thanks

**Comment by drakkan** [comment]
From your logs this url `http://127.0.0.1:10000/devstoreaccount1/ftp-test/?timeout=31536001` returned 404. I guess you have a different service on localhost port 10000 or a wrong port forwarding.
