### ISSUE TITLE
Add Graviton instances to AWS Marketplace installation

### ISSUE THREAD

**Issue by isae** [drakkan/sftpgo#488]
Hello! Thanks for your work.

Recently I've installed SFTPGo using AWS Marketplace. However, it would be nice to have an option to install it on t4g instances, which are 30% percent cheaper then similar t2 ones.

**Comment by drakkan** [comment]
Hi,

thank you for evaluating SFTPGo, I'll try to add arm64 AMI images in the near future, hopefully in time for v2.1.1

**Comment by drakkan** [comment]
Hi,

sorry for the long delay. I just sent arm64 AMIs, based on SFTPGo v2.1.2, for review. Support for Graviton instances is expected to be available before the end of the next week. I will keep you updated, thanks

**Comment by drakkan** [comment]
Hi,

Graviton instances are now available:

https://aws.amazon.com/marketplace/pp/prodview-a3kiicfzpiteo
https://aws.amazon.com/marketplace/pp/prodview-o52zpfhckfkcy
https://aws.amazon.com/marketplace/pp/prodview-rrodwoq74gvdk

thanks for your patience
