### ISSUE TITLE
Doesn't work for me? No SFTP login. Ubuntu 21.04

### ISSUE THREAD

**Issue by jradxl** [drakkan/sftpgo#489]
Installed the PPA,
Installation and running of the server proceeds without issues.
Clear documentation allows me to create my first account, and I can start up WebDav.
BUT i cannot connect to sftp
Your getting started documentation doesn't say i need to do any further configuration for localhost, and provides the initial example,
$ sftp -P 2022 nicola@127.0.0.1
But this doesn't allow a login.
UFW port is open....
But all i see is listening on ipv6, which isn't any good for me on a home network.
```
root@myserver:/etc/sftpgo# netstat -tnlp | grep sftp
tcp        0      0 127.0.0.1:10000         0.0.0.0:*               LISTEN      152537/sftpgo       
tcp6       0      0 :::2022                 :::*                    LISTEN      152537/sftpgo       
tcp6       0      0 :::2023                 :::*                    LISTEN      152537/sftpgo       
tcp6       0      0 :::8080                 :::*                    LISTEN      152537/sftpgo
```
Please help

**Comment by jradxl** [comment]
OK, I APT PURGED the installation, cleared out all the DIRS and reinstalled, allowing me to create the Admin account again.
Now it works. Clearly tcp6 was a red-herring.

But I don't know what the User's "Denied protocols" and "Denied login methods" options are for, which has no method for changing.

**Comment by drakkan** [comment]
Hi,

the "protocols denied" setting allows you to deny some protocols per user. For example, if you want to allow FTP only for a user, you can deny the `SSH`,` DAV` and `HTTP` protocols.

The  "denied login methods" setting is similar. For example, if you only want to allow public key logins, you can deny all other login methods.

I'm not sure what you are trying to report. What do you mean for "has no method for changing"? In the web admin you can change both these settings using a standard html multi select field: you can hold down the control (command on mac) button to select multiple options or to deselect the selected ones. If you are trying to report a different things please describe better the issue and attach the relevant SFTPGo logs, thanks

**Comment by jradxl** [comment]
Thank you for your clarification....
Since my first installation attempt failed to allow any login, my "brain" was now focused on the software being "denied all" until some protocols were enabled - hence I thought I needed to remove the entries in  "protocols denied". It had not occurred to me that was this option was the opposite logic - select to deny, with multiple selections via an additional key press.
And my failed first install attempt was probably due to not understanding difference between "web/admin/login" and "web/client/login", in spite of reading your documentation.

**Comment by drakkan** [comment]
ok, thank you.

The admin/client difference should be clearer in the v2.2.x, see #485. It is quite confusing in v2.1.0.

If you have any other suggestions, you are welcome, thank you
