### ISSUE TITLE
[web client] user does not have download permission but can download

### ISSUE THREAD

**Issue by CodyGuo** [drakkan/sftpgo#493]
user does not have download permission but can download

**Comment by drakkan** [comment]
Hi,

it seems to work for me, if I remove the download permission I have the following error while trying to download a file

![Schermata del 2021-08-03 10-09-18](https://user-images.githubusercontent.com/553263/127981419-52c0ae8f-d5ea-4850-b805-b52052faa4b5.png)

can you please share more details? For example a user dump or the exact steps to reproduce the issue

**Comment by CodyGuo** [comment]
mouse click on the file name to download
![image](https://user-images.githubusercontent.com/10672966/127985469-d77d3e54-6b21-49af-a7c4-d637886984d9.png)

**Comment by CodyGuo** [comment]
use download button 

![image](https://user-images.githubusercontent.com/10672966/127985754-ec419cad-c400-4bed-85f8-fcac6e91e9c7.png)

jump to invalid page

![image](https://user-images.githubusercontent.com/10672966/127985784-2e3b55ce-3187-40c1-86e2-dcfc5bd3d86c.png)

**Comment by drakkan** [comment]
I believe you :) but please share the exact permissions granted to this user (including per-directory permissions if any) and the sftpgo logs so I can try to reproduce, thanks

**Comment by CodyGuo** [comment]
![image](https://user-images.githubusercontent.com/10672966/127988252-b0f7bb64-6132-4c35-bd18-b2657a67b7d0.png)


![image](https://user-images.githubusercontent.com/10672966/127988546-7e7abe4d-94dc-49b6-a84c-035b05adb12b.png)

**Comment by CodyGuo** [comment]
![image](https://user-images.githubusercontent.com/10672966/127988673-1f6bea37-d198-4732-9e8c-b27e9776343f.png)

**Comment by CodyGuo** [comment]
master version: SFTPGo 2.1.0-9541843-dirty

**Comment by CodyGuo** [comment]
Cannot download after clearing the browser cache

**Comment by drakkan** [comment]
If you look at the sftpgo logs there are no download requests, so this is a caching issue. Maybe I can avoid browser caching by adding a timestamp to the query string

**Comment by CodyGuo** [comment]
ok, thanks.
