### ISSUE TITLE
Auto data retention 

### ISSUE THREAD

**Issue by n-h-mdla** [drakkan/sftpgo#495]
Would it be possible to implement an auto data-retention policy, where files are automatically deleted after a configurable amount of time (for example, 90 days)? This could be set via an env variable and would help with compliance with things like GDPR. Thanks!

**Comment by drakkan** [comment]
Hi,

this could be done but it requires a discrete effort and I'm time-constrained, a sponsorship would help, thanks

**Comment by perfecto25** [comment]
+1 for this request, our clients are asking if possible to remove their ftp data after X days, dont want to bash script this if possible natively

**Comment by drakkan** [comment]
I'm currently working on a big refactor (builtin 2FA using authenticator apps). I'll better evaluate this feature after finishing it. @perfecto25 thank you for sponsoring the project

**Comment by drakkan** [comment]
Hi,

I'm analyzing this feature. The most flexible way to support auto data retention is to set a retention per folder, something like this:

```
// DataRetention defines a per-folder retention
type DataRetention struct {
	// Virtual path, this is the path seen by SFTPGo clients.
	// If no other more specific retention is defined, it also applies to subdirectories
	Path string `json:"path"`
	// Retention time in hours.
	// The minimum accepted value is 12. 0 means no file will be deleted
	Retention int `json:"retention"`
}
```

therefore for simple setups it is sufficient to set `/` as folder and the desired retention, but for more complex setups it is still possible to set different retention times on different paths.

However, I'm worried about user mistakes:

- SFTPGo users can have overlapped home dirs: for example user1 has `/home/user1` as the home dir and user2 has `/home/user1/user2`. If you set a retention for user1 but not for user2, user2 files will be deleted anyway. You have to se a 0 retention on path `/user2` for user1 in this case
- Virtual folders can be shared among multiple users. You have to know what you are doing as for overlapping home dirs. It could be really easy to inadvertently delete a large shared folder.

For these reasons I'm not sure whether to add support for data retention in a fully automated way or just add REST APIs and warn that this is a danger zone (you can lose your files) and you need to be careful before using this feature. Providing only REST APIs (and so requiring to read some docs before enabling this feature) should prevent users from inadvertently deleting files or at least I should have fewer complaints.

**Comment by drakkan** [comment]
I added basic data retention support via REST API, in future updates I'll add report capabilities via email or a custom hook/plugins.

You can find an example usage [here](https://github.com/drakkan/sftpgo/tree/main/examples/data-retention)
