### ISSUE TITLE
Problem with admin passwords and client portal 

### ISSUE THREAD

**Issue by jdmcd** [drakkan/sftpgo#497]
Hi there,

Two things:
1. I am trying to disable the client web portal using `SFTPGO_HTTPD__BINDINGS__ENABLE_WEB_CLIENT=0` and it's not working (the client portal is still accessible). I've also tried `SFTPGO_HTTPD__BINDINGS__ENABLE_WEB_CLIENT=false`
2. When I spin up a new server with no admin user and create the admin user/password, if I log out and attempt to log back in I get an "invalid credentials" error. I have verified I am using the admin portal and am positive I am using the right password. I am using MySQL as the backing engine.

Here is the full docker command I'm running:

```
docker run --name some-sftpgo \
    -p 8080:8080 \
    -p 2022:2022 \
    -e SFTPGO_DATA_PROVIDER__DRIVER=mysql \
    -e SFTPGO_DATA_PROVIDER__HOST=redacted \
    -e SFTPGO_DATA_PROVIDER__USERNAME=redacted \
    -e SFTPGO_DATA_PROVIDER__PASSWORD=redacted \
    -e SFTPGO_DATA_PROVIDER__PORT=3306 \
    -e SFTPGO_DATA_PROVIDER__NAME=redacted \
    -e SFTPGO_DATA_PROVIDER__SSLMODE=0 \
    -e SFTPGO_COMMON__UPLOAD_MODE=1 \
    -e SFTPGO_COMMON__ACTIONS__EXECUTE_ON=upload,rename \
    -e SFTPGO_COMMON__ACTIONS__HOOK=redacted \
    -e SFTPGO_COMMON__SETSTAT_MODE=1 \
    -e SFTPGO_HTTP__TIMEOUT=20 \
    -e SFTPGO_TELEMETRY__BIND_PORT=0 \
    -e SFTPGO_HTTPD__BINDINGS__ENABLE_WEB_CLIENT=0 \
    -e SFTPGO_HTTPD__SIGNING_PASSPHRASE=redacted \
    -d "drakkan/sftpgo@sha256:ee54aa40d35621c35f3fac23d49550b7f288daffcb9be6fa489575a99d229994"
```

**Comment by drakkan** [comment]
Hi,

please give a look [here](https://github.com/drakkan/sftpgo/issues/474)

**Comment by jdmcd** [comment]
Thanks so much! Any idea about the admin password?

**Comment by drakkan** [comment]
after disabling the web client only the web admin interface is available, are you still unable to login? 

It  works for me locally.

If you delete the admin user from the database (`admins` table), the setup screen will appear again and you could try to create a new admin user. The password is hashed in a non reversible way, you cannot get the clear text password from the stored hash

**Comment by jdmcd** [comment]
No problem, that makes sense! Thanks much
