### ISSUE TITLE
[web client] admin/connections cannot manage users logged in by http client

### ISSUE THREAD

**Issue by CodyGuo** [drakkan/sftpgo#498]

**Comment by drakkan** [comment]
HTTP is a stateless protocol, an HTTP client authenticates each request using a Cookie or basic credentials. For WebDAV and web client you can see and abort ongoing transfers but not disconnect them since there isn't a persistent connection as for SFTP/FTP

**Comment by CodyGuo** [comment]
can it support removing all the http sessions logged in by user?
```go
cookie := &http.Cookie{
    Name:   cookieName,
    Value:  "",
    Path:   "/",
    MaxAge: -1,
}
http.SetCookie(w, cookie)
```

**Comment by drakkan** [comment]
I'm not sure this is really doable, we should track all the cookie/jwt tokens and present them in the list of the connected clients. I think we cannot detect a user that closes the browser or a brower tab and so it will be listed as connected until the token/cookie expires. Please try to write a patch and share it when you think you have something working.

However I think this approach is wrong, if we really want to track the connected users we should use a websocket or something similar to have a persistent connection (this cannot work for WebDAV). Using the web socket approach you will have other issues.

I don't plan to work on this, please send a PR if this is an important feature for you.

Thanks
