### ISSUE TITLE
defender scores?

### ISSUE THREAD

**Issue by erwiese** [drakkan/sftpgo#499]
Hi, 
sorry but it is unclear to me how to set the different defender score types. There are default values 1,2,3.
E.g. what does it mean if I set **score_invalid** to 0, or to 10?
Great tool anyway!

**Comment by drakkan** [comment]
Hi,

please take a look at the doc [here](https://github.com/drakkan/sftpgo/blob/main/docs/defender.md). 

When the total score exceed the configured threshold the host is banned, so if score_invalid is 10 and the threshold is 8 the offending host will be banned as soon as it tries to login using an invalid user. If instead score_invalid is 3 and threshold is 8, it will be banned after 3 login attempts with an invalid user within the configured observation_time

**Comment by erwiese** [comment]
So it is a weighting for different events. I was of course reading the docs,  but only now it is clear.
Thanks!

**Comment by drakkan** [comment]
writing docs is not one of my best skills :)

Can you please suggest how to improve the docs and/or send a PR? This would be greatly appreciated so that other users don't have the same confusion. Thanks

**Comment by erwiese** [comment]
I will try my best. Apart from that I find the docs are very helpfull, not too much text and clear.
