### ISSUE TITLE
How to put an public / private key for SFTP

### ISSUE THREAD

**Issue by Arkantium** [drakkan/sftpgo#503]
Hi,

Im not understand how to put a public & private key to sftpGo.
I have generate an public / private key with putty, i have put the public key on my user in sftpGo
How to put the private key ? (im on windows) if any of us can help me :)
Thanks in advance

**Comment by drakkan** [comment]
Hi,

you can generate your public/private key pair using puttygen

![puttygen](https://user-images.githubusercontent.com/553263/129624355-bee4c872-bc2c-4be5-8bec-e54f624b81fb.png)

Save the private key on your client PC.

Paste the public key, in OpenSSH format, in the SFTPGo admin UI

![sftpgo_add_pubkey](https://user-images.githubusercontent.com/553263/129624426-4cdd4fc2-1e49-4922-a70e-e1b21b31844b.png)

Configure your SFTP client to use the saved private key, for example FileZilla

![filezilla](https://user-images.githubusercontent.com/553263/129624578-cfd3ed5d-64f4-43fe-b54c-6b815675f94f.png)

Take a look at the SFTPGo logs and confirm the public key login

```
{"level":"debug","time":"2021-08-16T22:16:05.248","sender":"SSH","connection_id":"3cb4cd40f212b0d32cec4cf9ebdee5d019a2b21838729c11dd4b1b55e04ea795","message":"User \"bb\", logged in with: \"publickey: SHA256:upI/uGMZ+prvfVRorGmuVubNBA8KOlUK4xOtpGKidLo:ecdsa-key-20210816\", from ip: \"192.168.1.129\", client version \"SSH-2.0-FileZilla_3.55.1\""}
```

**Comment by Arkantium** [comment]
Yeah ! So easy :)
Thanks you for the support !!!

**Comment by d-j-a** [comment]
> Hi,
> 
> you can generate your public/private key pair using puttygen
> 
> ![puttygen](https://user-images.githubusercontent.com/553263/129624355-bee4c872-bc2c-4be5-8bec-e54f624b81fb.png)
> 
> Save the private key on your client PC.
> 
> Paste the public key, in OpenSSH format, in the SFTPGo admin UI
> 
> ![sftpgo_add_pubkey](https://user-images.githubusercontent.com/553263/129624426-4cdd4fc2-1e49-4922-a70e-e1b21b31844b.png)
> 
> Configure your SFTP client to use the saved private key, for example FileZilla
> 
> ![filezilla](https://user-images.githubusercontent.com/553263/129624578-cfd3ed5d-64f4-43fe-b54c-6b815675f94f.png)
> 
> Take a look at the SFTPGo logs and confirm the public key login
> 
> ```
> {"level":"debug","time":"2021-08-16T22:16:05.248","sender":"SSH","connection_id":"3cb4cd40f212b0d32cec4cf9ebdee5d019a2b21838729c11dd4b1b55e04ea795","message":"User \"bb\", logged in with: \"publickey: SHA256:upI/uGMZ+prvfVRorGmuVubNBA8KOlUK4xOtpGKidLo:ecdsa-key-20210816\", from ip: \"192.168.1.129\", client version \"SSH-2.0-FileZilla_3.55.1\""}
> ```

This was so helpful- thanks so much. I might also add a bit of helpful info for anyone on WinSCP- you can save the passphrase of the resulting key file with Pageant via these directions:
https://winscp.net/eng/docs/ui_pageant

Make sure to use a master password on WinSCP!!!!!
