### ISSUE TITLE
DARE options for s3 backend configurations

### ISSUE THREAD

**Issue by n-h-mdla** [drakkan/sftpgo#504]
Hi,

This might be due to me misunderstanding the application, but it doesn't seem possible to use the DARE/KMS system with cryptfs for implementations that use s3 as their data store. During my testing when adding the specific configs (env var SFTPGO_KMS__SECRETS__MASTER_KEY: XXXX), the file would be encrypted at the local level but not when viewing the file using the aws cli.
`sftpgo@sftp-test-1:/srv/sftpgo/data/test01gpg$ cat aug13.txt 
ڣ�N|]�<����z��!�*
                 ��+�X�SL� �r�����<�c#n��
��8M,�/�n�9u54��|Z';��y^4UYF`

`[20:10:32][:~]$ aws --profile sftpgo --endpoint=http://s3.xxxx.com s3 cp s3://test01/test01gpg/aug13.txt -
aug 13th test for gpg`

Is this the case, or have I misunderstood how DARE works, specifically with KMS? Is there a way to encrypt files uploaded through sftpgo as they head towards s3 for storage? Thanks as always!

**Comment by drakkan** [comment]
Hi,

you are correct, `cryptfs` will only work for local filesystem. For S3 and other cloud backends you can configure server side encryption, please take a look [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-encryption.html)

**Comment by viniciusgava** [comment]
@drakkan Is it possible to provide a server side customer key with SftpGo, avoiding the use of KMS?
Since I use a S3 compatibility, I encrypted the data using customer key.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html
