### ISSUE TITLE
[FTP] login timeout

### ISSUE THREAD

**Issue by CodyGuo** [drakkan/sftpgo#507]
Hi

sftpgo config
```json
 "ftpd": {
    "bindings": [
      {
        "port": 2121,
        "address": "",
        "apply_proxy_config": true,
        "tls_mode": 0,
        "force_passive_ip": "",
        "client_auth_type": 0,
        "tls_cipher_suites": [],
        "passive_connections_security": 0,
        "active_connections_security": 0,
        "debug": false
      }
    ],
    "banner": "",
    "banner_file": "",
    "active_transfers_port_non_20": true,
    "passive_port_range": {
      "start": 50000,
      "end": 50100
    },
    "disable_active_mode": false,
    "enable_site": false,
    "hash_support": 0,
    "combine_support": 0,
    "certificate_file": "",
    "certificate_key_file": "",
    "ca_certificates": [],
    "ca_revocation_lists": []
  },
```

FileZilla
![image](https://user-images.githubusercontent.com/10672966/129860412-66c1c5f4-b1ae-4aff-8ff6-a72f108e1bba.png)

sftpgo debug log
![image](https://user-images.githubusercontent.com/10672966/129861900-caf6597f-4490-4e07-b481-71f462c305f6.png)

**Comment by drakkan** [comment]
Hi,

I'm unable to replicate, it seems that the server does not send the welcome message in your case. You could try to enable FTP debugging or share a network dump. No other ideas sorry

**Comment by CodyGuo** [comment]
config `debug: true`

use `telnet xxx 2121`

need to enter multiple times to get a response
![image](https://user-images.githubusercontent.com/10672966/129878095-e142121e-ae14-4093-94e2-6c534cab1d0e.png)

**Comment by CodyGuo** [comment]
`tcpdump -i eth0 tcp port 2121 -w 2121.cap`

[2121.zip](https://github.com/drakkan/sftpgo/files/7006317/2121.zip)

**Comment by drakkan** [comment]
it works fine here, I don't need to press enter to get a response

```
telnet 127.0.0.1 2121
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
220 SFTPGo 2.1.0-dev ready
quit
221 Goodbye
Connection closed by foreign host.
```

the tcpdump looks fine, the server sent the welcome message very soon, the client closed the connection after 20 seconds

**Comment by CodyGuo** [comment]
`"proxy_protocol": 1`：connection timed out 
`"proxy_protocol": 0`：connection ok

**Comment by drakkan** [comment]
Hi,

the documentation is wrong, using `"proxy_protocol": 1` we still try to read the proxy header and it will be ignored if we receive a proxy header from an IP that isn't in the allowed list. The documented behaviour is wrong, this works for SFTP since the client sends some data after estabilishing the connection to complete the SSH handshake, but it cannot work for FTP. 

If you enable the proxy protocol only requests with a proxy header will work, I'll update the docs.

**Comment by CodyGuo** [comment]
ok，thanks

**Comment by drakkan** [comment]
it should work better once https://github.com/pires/go-proxyproto/issues/75 is fixed
