### ISSUE TITLE
Delete with S3 backend

### ISSUE THREAD

**Issue by jdmcd** [drakkan/sftpgo#509]
I have a user who says (and I've confirmed) that they no longer have permission to delete from their bucket now that we use S3 as the backend. I've confirmed that the user has the permission assigned in the UI/database.

**Comment by drakkan** [comment]
It should work, please post the SFTPGo logs and specify your S3 backend if different from AWS S3

**Comment by jdmcd** [comment]
```
{"level":"warn","time":"2021-08-20T17:46:23.271","sender":"SFTP","connection_id":"SFTP_56b863e59bf7b02480380b2f810fb6cf563f847bb4c3e7825d3e3c59a97b6f85_1","message":"failed to remove a file/symlink \"/redacted/redacted\": AccessDenied: Access Denied\n\tstatus code: 403, request id: 03FANQCDHJQHD2B4, host id: XUjnc+hEuumy+bSb3Cdx5pXi8X11GON4wFq7tCIeGrzerrHvgHEClM9YojlDRmEd0A+un8AtyC0="}
```

It is AWS S3

**Comment by drakkan** [comment]
Hi,

as you can see from your logs the AWS backend returns 403, please check the bucket permissions on AWS, thanks

**Comment by jdmcd** [comment]
That did it, thanks!
