### ISSUE TITLE
portable/User Mode

### ISSUE THREAD

**Issue by deknos** [drakkan/sftpgo#51]
Hi, 
it would be cool, if your sftpgo server would have the following feature, a portable mode.
a user can start sftpgo, perhaps with --portable as parameter, but has at least to provide the parameter directory, where he has access. 
at most he has to deliver the parameters

* password (could be generated by sftpgo as well, so optional)
* user (could be optional)
* port (has to be a non privileged port)

and this should stop when the user stops/exits the program.
 
Additionally (especially for mobile users) you could output an qrcode which has the sftp-url with user, port, ip/name as qr-code, perhaps as mode even with password, so mobile users could just use the qrcode to create an connection.

i would be willing to try helping with it, but i am a total newbie in go, though i wrote programs in python and perl back in the day.

**Comment by drakkan** [comment]
Hi,

this is an interesting feature thanks for your suggestion. 

Until now sftpgo is mainly developed for servers but adding a portable mode should not be too hard.
No problem if you cannot contribute code, I'll work on sftpgo code myself but first I need to think more about implementation details.
The qrcode part is not completly clear to me, I think an android/iOS app is needed to automatically connect to the server after reading the qrcode, am I wrong?
Probably an app is needed to estabilish sftp connection too, do you already use a such app?

**Comment by jovandeginste** [comment]
@drakkan eg. total commander can connect to sftp servers; the QR code might contain something like `sftp://username:password@ip-address:port/`

**Comment by drakkan** [comment]
@jovandeginste 
do you mean this app?

https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander

the qrcode content should not be a problem I just want to find some existing apps that support qrcode based connections and set the qrcode content to what they expect. @deknos if you can help to find compatibile apps this will be appreciated more than code contribution :)

**Comment by jovandeginste** [comment]
@drakkan yes that one, and this plugin: https://play.google.com/store/apps/details?id=com.ghisler.tcplugins.SFTP

**Comment by dkmbw** [comment]
ys, @jovandeginste had the right hunch. because someone on reddit asked about a mobile version, i thought about connecting to it via mobile and doing urls on mobile is hard, qrcodes are better there :)

at least that was my thought trail. that wouldnt be as important as the portable mode itself.

**Comment by drakkan** [comment]
Here is my draft implementation

```
./sftpgo portable --help
To serve the current working directory with auto generated credentials simply use:

sftpgo portable

Please take a look at the usage below to customize the serving parameters

Usage:
  sftpgo portable [flags]

Flags:
  -d, --directory string      Path to the directory to serve. This can be an absolute path or a path relative to the current directory (default ".")
  -h, --help                  help for portable
  -p, --password string       Leave empty to use an auto generated value
  -g, --permissions strings   User's permissions. "*" means any permission (default [*])
  -k, --public-key strings    
      --scp                   Enable SCP
  -s, --sftpd-port int        0 means a random non privileged port
  -u, --username string       Leave empty to use an auto generated value
```

suggestions?

Regarding the QR Code I have yet to test Total Commander app but for what I can understand reading their docs the QR Code is available for "WiFi transfer" where a desktop client and a mobile app will comunicate using some sort of proprietary protocol (not SFTP/SCP). The SFTP plugin seems to allow to insert ip and credential only, I cannot see a QR Code there. If so we cannot exchange a QR Code with Total Commander. Anyway I'll do more tests the next weekend

**Comment by dkmbw** [comment]
Wow, that looks great. Perhaps should the QR-Code an extra issue/requirement/feature and we just do the portable mode for now?  Just a suggestion, i do not want that you have to mix up too much stuff.

But the draft looks great!

**Comment by jovandeginste** [comment]
You can generate the QR code to just render that URL and leave the resolution of that URL to the OS. What I mean is, ideally:

1. User starts `sftpgo portable [...]`
2. `sftpgo` renders a QR code with the URI (this may be using ASCII, as an example: `echo "sftp://username:password@ip-address:port/" | qrencode -o - -t ASCII`)
3. Separate barcode scanner app:
  a. The (other) user opens his default barcode scanner app and scans the code.
  b. The barcode scanner app asks the user which app to open with the URI
4. One app for everything: 

However:

I just read [this thread](https://www.ghisler.ch/board/viewtopic.php?t=42837) which means Total Commander is not usable here (at this point). I did a quick search but found no sftp client which would open a shared URI (eg. through intents) or even a copy/paste URI. Anyone else has an app that would enable a reasonable flow?

**Comment by dkmbw** [comment]
i had the same impression, but i thought browsers would implement sftp as well and thought the URL could be used by them. but i tried and noticed that this wont work. so... i have to look for apps, which could do that, i know of no one atm.

**Comment by drakkan** [comment]
Here is a basic implementation

https://github.com/drakkan/sftpgo/commit/a4cddf4f7f38eb0930a686007a80ad1e46b4c475

not yet well tested and there are some things that I don't like :)

Any feedback is welcome!

For the mobile app part let's see what `RemoteFiles`'s author answer to my ticket before to decide how to proceed. 

Thanks for this suggestion

**Comment by deknos** [comment]
Works like a charm for me! That is really awesome!

**Comment by drakkan** [comment]
Good, thanks for the feedback.

I did some tests with several Go libraries for multicast dns, for now the one that works better is this one:

https://github.com/grandcat/zeroconf

I'm able to find the service from Android using native java API.

I want to test this library too

https://github.com/oleksandr/bonjour

and then I'll push this part too and I'll close the bug. Thank you to everyone
