### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by audouts** [drakkan/sftpgo#511]
Hi.

I'm using 1.0.0 and would like to upgrade to the latest. How can I do that, safely?

Thank you!

**Comment by drakkan** [comment]
Hi,

please take a look at the [upgrading docs](https://github.com/drakkan/sftpgo/#upgrading). In short you have to install 1.2.x, then 2.0.x and finally 2.1.0

**Comment by audouts** [comment]
Thank you. I see that the docs explain that you need to go upward through those versions but what is unclear to me is *how* to upgrade.

I'm using the `tar.xz` file. Do I unpack that in the same place as my current installation? Or somewhere else and move certain files?

**Comment by drakkan** [comment]
You need to update the data within your data provider so basically you have to install 1.2.x somewhere, configure it to use the same data provider as the previous version and start 1.2.x version or use the `initprovider` command (from the new version). You should see a log such as this one:

```
updating database version: 11 -> 12
```

and then repeat the same steps for 2.0.x

**Comment by audouts** [comment]
Thanks. So I downloaded 1.2.x and updated the json to match. Then I ran sftpgo and that seemed to work.
I did the same thing with 2.0.x, which also worked. I noticed that the admin page, when refreshed, asked for credentials.

When I tried 2.1.x, everything looked the same as the other two upgrades but my admin credentials did not work.

**Comment by drakkan** [comment]
> Thanks. So I downloaded 1.2.x and updated the json to match. Then I ran sftpgo and that seemed to work.
> I did the same thing with 2.0.x, which also worked. I noticed that the admin page, when refreshed, asked for credentials.
> 
> When I tried 2.1.x, everything looked the same as the other two upgrades but my admin credentials did not work.
> 

in v2.1.0 we have the admin UI and the web client UI, please make sure you are logging in to the URL `/web/admin/login`

> Edit:
> I also don't see `sftpgo_api_cli.py` in 2.0.4. Is there a replacement? I use that script.

No sorry, that script was deprecated, you can use one of the available OpenAPI generators. Please be sure to use the OpenAPI specification matching your version, 2.1.x specs are [here](https://github.com/drakkan/sftpgo/blob/2.1.x/httpd/schema/openapi.yaml). There is also a community maintained [sftpgo-client](https://github.com/ramnes/sftpgo-client)

**Comment by audouts** [comment]
> 
> No sorry, that script was deprecated, you can use one of the available OpenAPI generators. Please be sure to use the OpenAPI specification matching your version, 2.1.x specs are [here](https://github.com/drakkan/sftpgo/blob/2.1.x/httpd/schema/openapi.yaml). There is also a community maintained [sftpgo-client](https://github.com/ramnes/sftpgo-client)

Okay. I have no idea what an OpenAPI generator is, so I'll have to research that.

**Comment by drakkan** [comment]
OpenAPI generators allow to generate an SFTPGo client from the OpenAPI specifications.

Several generators are available, for example:

https://github.com/OpenAPITools/openapi-generator
https://swagger.io/tools/swagger-codegen/

based on your needs you could also evaluate to use something like `curl` directly.
The SFTPGo API are evolving quickly, I have no time to maintain a client too

**Comment by audouts** [comment]
Okay. Thanks for your help and for SFTPGo :)

**Comment by audouts** [comment]
Hmm. Since I upgraded, I can't log in. I just get
```could not accept a channel: EOF```
and then the connection is removed.
