### ISSUE TITLE
Auto admin creation with docker

### ISSUE THREAD

**Issue by cchris-org** [drakkan/sftpgo#512]
Hi,

docker-compose.yml

```
...

environment:
  SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN: 1
  SFTPGO_DEFAULT_ADMIN_USERNAME: admin
  SFTPGO_DEFAULT_ADMIN_PASSWORD: something

...
```
but admin login works only with "admin" / "password"?! :(

**Comment by drakkan** [comment]
Hi,

I guess you are using 2.1.0 version and you are referring to the development version docs. Please switch to the `edge` docker image or refer to the [2.1.x docs](https://github.com/drakkan/sftpgo/blob/2.1.x/docs/full-configuration.md)

**Comment by cchris-org** [comment]
Ups ..  Thanks :D
