### ISSUE TITLE
panic in ServeHTTP: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by jmkristian** [drakkan/sftpgo#516]
WebDAV requests fail with status "500 Internal Server Error". The log (attached) contains "panic in ServeHTTP: "unaligned 64-bit atomic operation".
[panic.txt](https://github.com/drakkan/sftpgo/files/7069908/panic.txt)

This seems to be caused by a bug in golang on the armv7l architecture, for example my Raspberry Pi 3. Fixes have been proposed [here](https://github.com/golang/go/issues/36606) and [here](https://github.com/golang/go/issues/19057). Some people have worked around it by carefully shuffling field declarations to achieve the required alignment.

I built sftpgo from source code.
$ ./sftpgo -v
SFTPGo 2.1.0-dev-b903a6e-dirty-2021-08-27T20:47:49Z +metrics -azblob -gcs -s3 -bolt -mysql -pgsql +sqlite +portable
$ go version
go version go1.17 linux/arm
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
$ uname -mpisr
Linux 5.4.0-1041-raspi armv7l armv7l armv7l

**Comment by drakkan** [comment]
Hi,

can you please confirm that it works now? This bug recurs from time to time, I should test at least one 32-bit platform using GitHub actions

**Comment by drakkan** [comment]
It should not happen anymore in future

https://github.com/drakkan/sftpgo/commit/16ba7ddb34de09ed5e3c77a53d9a7a581a047e73

**Comment by jmkristian** [comment]
That solved the problem. Thank you!

> can you please confirm that it works now?
