### ISSUE TITLE
uploading and downloading is failing

### ISSUE THREAD

**Issue by vangahari** [drakkan/sftpgo#522]
Hello Team, 

We arefacing the issue while uploading and downloading the files from s3 bucket
We are using filezilla to connect to the sftp
I created a user and i tried to upload and download but it seems required more permissions or absolute path (or s3 endpoint)
Pls see below pictures
<img width="846" alt="Screenshot 2021-08-31 at 5 22 10 PM" src="https://user-images.githubusercontent.com/45491142/131498805-b53690b0-5fbd-40b7-9268-df53d9928330.png">
<img width="706" alt="Screenshot 2021-08-31 at 5 26 26 PM" src="https://user-images.githubusercontent.com/45491142/131498825-cb562a84-22d7-41aa-a82c-205ea001f7b5.png">
<img width="549" alt="Screenshot 2021-08-31 at 5 28 14 PM" src="https://user-images.githubusercontent.com/45491142/131498828-fe4c6739-a61e-47af-8c2c-1cba9b7ef7c2.png">
<img width="1440" alt="Screenshot 2021-08-31 at 5 28 26 PM" src="https://user-images.githubusercontent.com/45491142/131498830-0e538be4-af1f-4873-b681-7499d65df8f3.png">

It is saying listing all the directories is successful, but when it comes to upload/download is failing.

See the user Configuration, I gave * for user permissions 
<img width="1162" alt="Screenshot 2021-08-31 at 5 33 05 PM" src="https://user-images.githubusercontent.com/45491142/131499407-cf3a0e18-cc61-4dfb-a72c-62a29de6fc63.png">
<img width="1172" alt="Screenshot 2021-08-31 at 5 33 42 PM" src="https://user-images.githubusercontent.com/45491142/131499423-7af25c5f-3da1-475a-a79b-155fc4ec29a1.png">
<img width="1168" alt="Screenshot 2021-08-31 at 5 33 56 PM" src="https://user-images.githubusercontent.com/45491142/131499434-8177d268-3bd3-4a6e-8033-ba2cbead3506.png">

Please suggest us, if we are missing anything

**Comment by yashpatel20** [comment]
I am also facing this same issue. Any help regarding this would be really appreciated.

**Comment by drakkan** [comment]
Please try to set the home dir to a writable location, `/` is generally only writable from the root user. The home dir should be writable from the user running SFTPGo.

**Comment by vangahari** [comment]
@drakkan, Thanks for the quick for the reply.
I have tried with the user home path, but still we are facing same issue. We are using aws s3 bucket for storage. Is that required permissions to store the data for normal user where we created these users from WebUI.

<img width="1164" alt="Screenshot 2021-08-31 at 6 37 58 PM" src="https://user-images.githubusercontent.com/45491142/131508522-5f36d100-1b42-4d88-80bc-1d4e279b6ac1.png">
<img width="670" alt="Screenshot 2021-08-31 at 6 21 34 PM" src="https://user-images.githubusercontent.com/45491142/131508567-2468b7a0-a01b-4ff4-9cd7-2a7bdbc5d183.png">

Can you check the above issue, when we are uploading I see this marked issue as shown in the above 

Also pls have a look into the conf file which i was using
Dockerfile
<img width="1169" alt="Screenshot 2021-08-31 at 6 36 54 PM" src="https://user-images.githubusercontent.com/45491142/131509071-b0ee7716-d8c7-464c-8c6d-a4b84641475a.png">

Json file for configuration
{
    "common": {
        "idle_timeout": 15,
        "upload_mode": 0,
        "actions": {
            "execute_on": [],
            "hook": ""
        },
        "setstat_mode": 0,
        "proxy_protocol": 0,
        "proxy_allowed": [],
        "post_connect_hook": ""
    },
    "sftpd": {
        "bind_port": 2022,
        "bind_address": "",
        "max_auth_tries": 0,
        "banner": "",
        "host_keys": [],
        "kex_algorithms": [],
        "ciphers": [],
        "macs": [],
        "trusted_user_ca_keys": [],
        "login_banner_file": "",
        "enabled_ssh_commands": [
            "md5sum",
            "sha1sum",
            "cd",
            "pwd",
            "scp"
        ],
        "keyboard_interactive_auth_hook": "",
        "password_authentication": true
    },
    "ftpd": {
        "bind_port": 2021,
        "bind_address": "",
        "banner": "",
        "banner_file": "",
        "active_transfers_port_non_20": false,
        "force_passive_ip": "",
        "passive_port_range": {
            "start": 50000,
            "end": 51000
        },
        "certificate_file": "",
        "certificate_key_file": "",
        "tls_mode": 0
    },
    "webdavd": {
        "bind_port": 0,
        "bind_address": "",
        "certificate_file": "",
        "certificate_key_file": "",
        "cors": {
            "enabled": false,
            "allowed_origins": [],
            "allowed_methods": [],
            "allowed_headers": [],
            "exposed_headers": [],
            "allow_credentials": false,
            "max_age": 0
        },
        "cache": {
            "users": {
                "expiration_time": 0,
                "max_size": 50
            },
            "mime_types": {
                "enabled": true,
                "max_size": 1000
            }
        }
    },
    "data_provider": {
        "driver": "postgresql",
        "name": "sftpgo",
        "host": "DB_HOST",
        "port": 5432,
        "username": "DB_USER",
        "password": "DB_PASS",
        "sslmode": 0,
        "connection_string": "",
        "sql_tables_prefix": "",
        "manage_users": 1,
        "track_quota": 2,
        "pool_size": 0,
        "users_base_dir": "/srv/sftpgo/data",
        "actions": {
            "execute_on": [],
            "hook": ""
        },
        "external_auth_hook": "",
        "external_auth_scope": 0,
        "credentials_path": "credentials",
        "prefer_database_credentials": false,
        "pre_login_hook": "",
        "post_login_hook": "",
        "post_login_scope": 0,
        "check_password_hook": "",
        "check_password_scope": 0,
        "password_hashing": {
            "argon2_options": {
                "memory": 65536,
                "iterations": 1,
                "parallelism": 2
            }
        },
        "update_mode": 0
    },
    "httpd": {
        "bind_port": 8080,
        "bind_address": "",
        "templates_path": "templates",
        "static_files_path": "static",
        "backups_path": "/srv/sftpgo/backups",
        "auth_user_file": "",
        "certificate_file": "",
        "certificate_key_file": ""
    },
    "http": {
        "timeout": 20,
        "ca_certificates": [],
        "skip_tls_verify": false
    },
    "kms": {
        "secrets": {
            "url": "",
            "master_key_path": ""
        }
    }
}

**Comment by drakkan** [comment]
You have to set `force_passive_ip` to your external ip address, however FileZilla seems to fix this configuration issue on client side for you.

I have no time to test your custom Dockerfile sorry, it seems that your user (uid 1100) cannot create files in `/srv` path try to manually inspect your docker container

**Comment by vangahari** [comment]
Hello, @drakkan, 
I have changed some permissions, and i restarted the container, seems sftp service got started
But i am not able to login the sftp webUI, its saying connection refused. 
When the service started the UI also should be accessible right..? 
and even i tried with old configuration, still its not accessible, its saying connection refused, but in container logs seems service got started
<img width="1440" alt="Screenshot 2021-09-01 at 7 52 35 AM" src="https://user-images.githubusercontent.com/45491142/131602136-8036e63b-eed5-44f7-9277-ac5dfeb62c1b.png">

Please see the logs below,

**Comment by drakkan** [comment]
Hi,

as you can see from your logs the HTTP server address is 127.0.0.1, please check your configuration file/env vars

**Comment by vangahari** [comment]
Hi @drakkan, even with old configuration is running in localhost only, but we were able to access it. Now we cant access it

**Comment by vangahari** [comment]
Hi @drakkan, somehow i was able to setup sftpgo using manual Installation 

https://tomjorge.me/how-to-deploy-an-ftp-backed-by-an-s3-bucket
If you face deb file issue, download deb file to your local machine and upload it to remote server and install using dpkg

https://github.com/drakkan/sftpgo/releases

If you face issues with certbot, use openssl:
https://linuxize.com/post/creating-a-self-signed-ssl-certificate/

**Comment by drakkan** [comment]
> Hi @drakkan, somehow i was able to setup sftpgo using manual Installation
> 
> https://tomjorge.me/how-to-deploy-an-ftp-backed-by-an-s3-bucket
> Here I faced deb file download issue, so I download it to my local machine and upload it to remote server and install using dpkg package manager
> 
> https://github.com/drakkan/sftpgo/releases
> 
> I was not able to generate certs using certbot, So I openssl it worked for me:
> https://linuxize.com/post/creating-a-self-signed-ssl-certificate/
> 
> I followed this official doc https://github.com/drakkan/sftpgo/blob/main/docs/howto/postgresql-s3.md
> But it didnt work for me, may be we need to add ssl certs here to make it work.
> 

there are several way to add TLS certs, using openssl is fine, I like lego, take a look here

https://github.com/drakkan/sftpgo/blob/main/docs/howto/lets-encrypt-certificate.md

> Please look into these issues and suggest us to go for right direction. Any suggestions would be helpful and appreciated

I'm sorry but I don't have enough time to help users in step by step troubleshooting for free. Your setup is quite common and many users have no issues to use SFTPGo with an S3 bucket, it is unlikely that you are experiencing a bug in SFTPGo.

Please try to follow the official docs without customizations and customize things once you have a basic setup working

https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md
https://github.com/drakkan/sftpgo/tree/main/docker

thanks
