### ISSUE TITLE
Error bind port 21 Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by DEK4** [drakkan/sftpgo#527]
Hello,

I install sftpGo on my ubuntu server 20.04LTS.

When I set the port 21 on ftpd json config file I get this error:

> pe:0 TLSCipherSuites:[] ciphers:[]}] BindPort:0 BindAddress: ForcePassiveIP: Banner:SFTPGo 2.1.0 ready BannerFile: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] ActiveTransfersPortNon20:true DisableActiveMode:false EnableSite:false HASHSupport:0 CombineSupport:0 TLSMode:0 PassivePortRange:{Start:50000 End:50100}}"}
> Sep  2 16:03:09  sftpgo[5629]: {"level":"info","time":"2021-09-02T16:03:09.037","sender":"ftpd","message":"starting FTP serving, binding: :21"}
> Sep  2 16:03:09 sftpgo[5629]: {"level":"error","time":"2021-09-02T16:03:09.037","sender":"service","message":"could not start FTP server: listen tcp :21: bind: permission denied"}

JSON config:
 ```
"ftpd": {
    "bindings": [
      {
        "port": 21,
        "address": "",
        "apply_proxy_config": true,
        "tls_mode": 0,
        "force_passive_ip": "",
        "client_auth_type": 0,
        "tls_cipher_suites": []
      }
    ],
    "banner": "",
    "banner_file": "",
    "active_transfers_port_non_20": true,
    "passive_port_range": {
      "start": 50000,
      "end": 50100
    },
    "disable_active_mode": false,
    "enable_site": false,
    "hash_support": 0,
    "combine_support": 0,
    "certificate_file": "",
    "certificate_key_file": "",
    "ca_certificates": [],
    "ca_revocation_lists": []
  },
```

netstat -tanup command:

```
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      418/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3124/sshd: /usr/sbi 
tcp        0      0 10.20.0.9:39520         169.254.169.254:80      ESTABLISHED 718/
tcp        0      0 10.20.0.9:22            74.125.17.2:33240       ESTABLISHED 3132/sshd: 
tcp        0      0 10.20.0.9:39508         169.254.169.254:80      ESTABLISHED 562/
tcp        0      0 10.20.0.9:36228         66.102.1.95:443         TIME_WAIT   -                   
tcp        0      0 10.20.0.9:57760         142.251.5.95:443        ESTABLISHED 562/
tcp        0      0 10.20.0.9:57758         142.251.5.95:443        ESTABLISHED 718/
tcp6       0      0 :::22                   :::*                    LISTEN      3124/sshd: /usr/sbi 
udp        0      0 127.0.0.1:323           0.0.0.0:*                           2185/chronyd        
udp        0      0 127.0.0.53:53           0.0.0.0:*                           418/systemd-resolve 
udp        0      0 10.20.0.9:68            0.0.0.0:*                           414/systemd-network 
udp6       0      0 ::1:323                 :::*                                2185/chronyd        

```

If I set 0 (zero) con port config on FTP sftpGO run without problems.

Any idea?

Thanks

**Comment by drakkan** [comment]
Hi,

SFTPGo runs, by default, using an unprivileged user. Only root can bind a socket on ports < 1024. To fix this issue you need to override the systemd unit and run the SFTPGo service as root user

**Comment by HunterNyan** [comment]
> Hi,
> 
> SFTPGo runs, by default, as an unprivileged user. Only root can bind a socket on ports < 1024. To fix this issue you need to override the systemd unit and run the SFTPGo service as root user

I can't vouch for ever just defaulting to running things as root as a method to solve something. However, my way of solving this was to set the binary capabilities to allow it to bind to the ports: setcap 'cap_net_bind_service=+ep' /sftpgo 

ref: https://man7.org/linux/man-pages/man7/capabilities.7.html

**Comment by drakkan** [comment]
> > Hi,
> > SFTPGo runs, by default, as an unprivileged user. Only root can bind a socket on ports < 1024. To fix this issue you need to override the systemd unit and run the SFTPGo service as root user
> 
> I can't vouch for ever just defaulting to running things as root as a method to solve something. However, my way of solving this was to set the binary capabilities to allow it to bind to the ports: setcap 'cap_net_bind_service=+ep' /sftpgo
> 
> ref: https://man7.org/linux/man-pages/man7/capabilities.7.html

much better than running the service as root, thanks for sharing

**Comment by drakkan** [comment]
This is now documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#binding-to-privileged-ports)
