### ISSUE TITLE
disallow changing credentials for some users

### ISSUE THREAD

**Issue by mbunkus** [drakkan/sftpgo#528]
I'm running a site with several user accounts that serve different purposes. One of those is a shared "upload only" account that I give out to users of my software where they can upload anything, but download nothing (in order to prevent my server from becoming a trading space for illegal/copyrighted stuff). This is working fine with the permission system sftpgo offers.

That account has a password that's publicly known.

However, some clever people decided to change the password for that account via the web UI. Each time this happens, I only realize this after another potential uploader complains about not being able to log in. I have to log in as an admin and change the password back.

What I would very much like to have is a user-specific setting that disallows any change to the credentials, both the password and the pubkeys. I see that there's an entry called `publickey-change-disabled` already, but nothing for passwords.

Preventing access to the `/web/client/credentials` path is not an option for me as I have personalized user accounts on the server, too, and they should definitely be able to change their password.

Thanks!

sftpgo 2.1.0

**Comment by drakkan** [comment]
This is now supported in the development version, thanks for your suggestion

**Comment by mbunkus** [comment]
Thank you so much for implementing it so quickly. Much appreciated!

**Comment by tooptoop4** [comment]
@mbunkus i'm interested in using this feature, can u share where the config goes? its not in full-configuration.md

**Comment by mbunkus** [comment]
@tooptoop4 Sure. As it's a per-user setting, you configure it in the admin web UI (`/web/admin/login`) when you configure the user. In the "ACLs" section there's a setting called "Web client/REST API" where you can disable several functionality wrt. changing the user, including resetting or changing the password and other authentication methods.
