### ISSUE TITLE
Allow users to upload and download files from Web interface.

### ISSUE THREAD

**Issue by tan-vo-cityblock** [drakkan/sftpgo#533]
Hi there,

Is it possible to configure sftpgo to allow users to upload and download file from the web interface instead of Sftp clients? Thank you so much!

**Comment by drakkan** [comment]
Hi,

this feature is already implemented in the development version and it will be included in v2.2.x.

Please take a look [here](https://github.com/drakkan/sftpgo/discussions/519) for more detailed info
