### ISSUE TITLE
Traefik Authentication Header Username

### ISSUE THREAD

**Issue by ajl000** [drakkan/sftpgo#534]
Hi Nicola,

I would like to use SFTPGO behind Traefik with SSO.  After login, TraefikForwardAuth can add a header such as 
X-SFTPGo-Username: adam_law

I was wondering whether you would consider programming this form of authentication into SFTPGo.

Regards

Adam

**Comment by drakkan** [comment]
Hi,

if you can set any arbitrary header then API key authentication should work

https://github.com/drakkan/sftpgo/blob/main/httpd/schema/openapi.yaml#L4141

it is available in the development version.

The development version also support auth plugins, it should be relatively easy to add LDAP, local user authentication support, etc

**Comment by drakkan** [comment]
Hi,

if I understand this request correctly you want to authenticate your SFTPGo users using oauth2.

TraefikForwardAuth seems to use this library

https://github.com/coreos/go-oidc

I think we can't just trust a header, we need to implement oauth2 support directly within SFTPGo and match the user authenticated via oauth2 with an SFTPGo username (e.g. SFTPGo username should match the user's email or some other field).

This is probably only applicable to web client/web admin UI. I plan to work on #495 in the next few weeks. I'll better evaluate this feature after shipping auto data retention. Thanks for your suggestion

**Comment by drakkan** [comment]
This was fixed by setting the right cookie header in TraefikForwardAuth

**Comment by ajl000** [comment]
Thanks drakkan - for the "signing passphrase" option https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L219 ,
