### ISSUE TITLE
Suggestion: add dependencies in vendor dir

### ISSUE THREAD

**Issue by jovandeginste** [drakkan/sftpgo#54]
It seems to be a common practice now in Goland to add your dependencies in the `vendor/` dir. This would mean I (as a contributor) would not need to get my own copy of your dependencies, since they live inside your git tree.

Just a suggestion.

**Comment by drakkan** [comment]
This seems the old way to manage modules deps  (before Go 1.11), we use go modules

https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away

I think `vendor` dir is used nowadays for compatibility reasons only.

A pratical example in `sftpgo` is the `pkg/sftp` version, we need current git master, using go.mod we'll use the git commit specified here:

https://github.com/drakkan/sftpgo/blob/master/go.mod#L15

even without a `vendor` dir, sftpgo will not use a `pkg/sftp` version installed to your gopath but the required version is downloaded in `~/go/pkg/mod/...`

**Comment by jovandeginste** [comment]
You are right, but apparently in our work environment we like to have the code base contain all dependencies. This makes sure our builds work even if github is unreachable or our internet connection is borked. As I said, it was a suggestion :-)

**Comment by drakkan** [comment]
This seems more a build related issue, can you please try something like this:

```
git clone https://github.com/drakkan/sftpgo.git
cd sftpgo
go mod vendor
```

and then even without internet connection:

```
go build -mod=vendor -i -ldflags "-s -w -X github.com/drakkan/sftpgo/utils.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/utils.date=`date -u +%FT%TZ`" -o sftpgo
```

**Comment by jovandeginste** [comment]
Yes, that's (more or less) what I did so far. However, the "go mod vendor" fetches the remote dependencies. Our CI/CD runs in a clean container at every run.

**Comment by drakkan** [comment]
If your container has no internet access `git clone` will fail too, my suggestion was to prepare the source in a private repo using:

```
git clone https://github.com/drakkan/sftpgo.git
cd sftpgo
go mod vendor
```

and then use this private repo to clone and build from another machine/container without internet access.

Anyway I'll evaluate better your suggestion later. The vendor dir is about 25MB and this is my main concern to add it to this repo

**Comment by drakkan** [comment]
Hi,

I don't want to copy all the deps in the repo (25MB), the only alternative is to use git submodules but they seem not so easy to maintain and they require manual work each time a new depencency is added (not tested fow now, I only read the docs on how to do this). 

Using `go mod vendor` as explained above is really simple, so I propose to add, for each stable release, a source download tarball that includes sftpgo and the vendor dir with all depends so you can download this source package instead of git clone and so if you build using `go build -mod=vendor` you don't need internet access

**Comment by jovandeginste** [comment]
Yes, I'll continue using `go mod vendor`

**Comment by drakkan** [comment]
please note that I added `sftpgo_0.9.3_with_deps.tar.xz` to the release page. This source package contains the vendor dir and so you can build it offline

**Comment by jovandeginste** [comment]
Thanks! However, for building an rpm from release, I use your compiled release archive. The dependencies are useful when building from source, eg. when preparing a PR.

**Comment by drakkan** [comment]
If you can make a pull request that handle vendor dir using git submodules I'll accept it and I'll try to maintain for future modules updates

**Comment by jovandeginste** [comment]
I'm not a fan of using submodules, in fact. I'd rather remember to run `go mod vendor` than use submodules...

**Comment by drakkan** [comment]
Yes, they seem not so easy, let's closing then, feel free to reopen if you have a solution that avoids to have duplications in the main repo

**Comment by jovandeginste** [comment]
Don't think there is a solution. I understand your concern, and respect that. Again, it was a (open) suggestion. Thanks for debating the issue :smiley:

**Comment by drakkan** [comment]
Thanks to you for the suggestion. Please continue to open issues for any suggestion/idea, I'm open to discussions
