### ISSUE TITLE
key_prefix - automatically the username?

### ISSUE THREAD

**Issue by ScubaDrew** [drakkan/sftpgo#541]
Is there a way to have the key_prefix value the username or do I have to populate every key_prefix with the username manually?

**Comment by drakkan** [comment]
Hi,

there are several ways.

From the web ui you can use a template

![Schermata del 2021-09-18 09-53-26](https://user-images.githubusercontent.com/553263/133881198-e65de80f-ce2e-44a5-a3ba-8e75bf30e568.png)

a template can be empty or it can be generated from an existing user (just select an user before clicking on "Template")

![Schermata del 2021-09-18 09-55-49](https://user-images.githubusercontent.com/553263/133881288-fd84da9a-d874-42a4-a011-2f7178a79d48.png)

you can then set key prefix as `%username%/`

**Comment by ScubaDrew** [comment]
Fantastic. Thank you @drakkan 

We are making progress on getting this setup and I'll raise company sponsorship with the team soon.
