### ISSUE TITLE
proxy_allowed doesn't work in httpd

### ISSUE THREAD

**Issue by helmut72** [drakkan/sftpgo#543]
I've set following environment variables in the Docker Image 2.1.2 (drakkan/sftpgo:v2-alpine-slim):

```
SFTPGO_HTTPD__BINDINGS__0__PROXY_ALLOWED=192.168.1.1/32
SFTPGO_WEBDAVD__BINDINGS__0__PROXY_ALLOWED=192.168.1.1/32
```

First one doesn't work, always shows 192.168.1.1, second one works, shows the public IP.

**Comment by drakkan** [comment]
Fixed, thanks. This only affects the logged ip. IP restrictions etc. use the correct ip also without this fix

**Comment by helmut72** [comment]
That was fast, thank you.

**Comment by drakkan** [comment]
It will take time for the fix to be included in a release :)

**Comment by drakkan** [comment]
> By mistake I typed the wrong password and saw, that Defender and Log files show and block the IP of my Reverse Proxy when accessing through WebDAV. Shouldn't the public IP being logged and blocked?

please check the docs. Proxy settings changed in v2.3.0, for example now you have to set the proxy header to lock for

**Comment by helmut72** [comment]
`client_ip_proxy_header `. Thanks, works.

**Comment by drakkan** [comment]
> `client_ip_proxy_header `. Thanks, works.

added to v2.3.0 release notes, thanks for noticing
