### ISSUE TITLE
Google cloud storage - no space left on device

### ISSUE THREAD

**Issue by chandininekkantti** [drakkan/sftpgo#544]
I'm using SFTPgo Docker on Google cloud with GCS as storage. I have created a user and selected storage as GCS and everything seems to be working. However, when I start the FTP transfer roughly 4TB with each file around 1GB the transfers are failing with following message. I'm using a large GC instance with 300GB and 64memory. Do I need to have 4TB space on local too ? Sorry if this question is too basic. I have looked at the documentation but there is nothing much on google cloud. 

`Response:	550 Issue during transfer: write /srv/sftpgo/data/test/pipefile392761208: no space left on device`

**Comment by drakkan** [comment]
Hi,

temporary files are stored locally, using unliked files, until the transfer is completed, so you need enough local space for them.

**Comment by chandininekkantti** [comment]
Thanks for your quick reply. When you say the transfer to complete, you mean for each file or all files (4TB) ? Is there an option in SFTPGo once the transfer of one file is complete, it is deleted locally to free-up the space ? It seems redundant to use GCS when you can afford lot of local storage.

**Comment by drakkan** [comment]
Hi,

it works exactly as you describe.So you have more than 300GB of concurrent transfers or the partition where `/srv/sftpgo/data/test` is located to has less space available.
