### ISSUE TITLE
No first time user setup on web portal

### ISSUE THREAD

**Issue by robtrooper** [drakkan/sftpgo#548]
sftpgo version 2.1.2.
Windows 64 bit

I have previously installed sftpgo with the windows release without issue. Trying this version on a new Windows install and i don't get the first time web install admin user setup. The admin/password is not working. 
I've tried adding 
{
    "create_default_admin": true,
    "SFTPGO_DEFAULT_ADMIN_USERNAME": "admin",
    "SFTPGO_DEFAULT_ADMIN_PASSWORD": "password",
    "common": {

to the begining of sftpgo.json in C:\ProgramData\SFTPGo but no change.
Not sure what i'm doing wrong.
I'm not setting a provider and just going with the default db which i understand to be the auto sqlite.

**Comment by robtrooper** [comment]
/web/admin/setup worked thank you.
I was opening http://127.0.0.1:8080 which was then opening the client url, somehow.
User error. I blame lack of sleep.

**Comment by drakkan** [comment]
uhm .. it's not the user's fault, you should be automatically redirected to the setup page, I will improve it in v2.2.x, thanks for noticing
