### ISSUE TITLE
Feature request: custom authentication backends (HTTP API?)

### ISSUE THREAD

**Issue by and3rson** [drakkan/sftpgo#555]
We are currently looking for an SFTP server that would be able to authenticate users using some existing backend (in our case - our own HTTP API which uses LDAP & PostgreSQL under the hood).

Would it make sense to implement a new dataprovider - say, "jsonapi", which (instead of using a database) would send HTTP requests to a configured URL e. g. `POST user_host/user_prefix/sftpgo/login`? Users then would be able to implement their own backends that manage their own users. Those backends would simply serve the endpoints that are required by sftpgo.

If this is something that would be welcome in this project, I would be glad to contribute that to this repository.

Thanks!

**Comment by drakkan** [comment]
Hi,

this is already supported, please take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/external-auth.md).

The development version also supports [auth plugins](https://github.com/drakkan/sftpgo/blob/main/docs/plugins.md).
