### ISSUE TITLE
Documentation on setting up systemd service

### ISSUE THREAD

**Issue by ok-nick** [drakkan/sftpgo#556]
Excuse my lack of knowledge, but I've currently reached the [MySql/MariaDB setup in the docs](https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md#use-mysqlmariadb-data-provider) and it assumes that you already have a service unit file setup. I'm definitely a noob at all this, so it would be very helpful there is some kind of template for the recommended unit.

I built sftpgo from source for my raspberry pi 4 so that it will run on Debian 10 (would be very nice if this was precompiled). Not sure if a unit file is supposed to be automatically created, but this is my setup.

Would be cool if there was a discord server for this project. It's always nice to ask questions in real-time and easily look up old questions.

**Comment by ok-nick** [comment]
Ah, I didn't see the top folder for all the how-tos. This is perfectly explained and the template is found [here](https://github.com/drakkan/sftpgo/blob/main/init/sftpgo.service).
Anyways, I'd still definitely suggest including pre-compiled Debian 10 packages and creating a discord server.

**Comment by drakkan** [comment]
Hi,

raspberry pi 4 should be arm64 based, the arm64 deb available on the [release page](https://github.com/drakkan/sftpgo/releases/tag/v2.1.2) shoul work with any (recent) Debian version. Please let me know if it works on RPI 4 too I have tested it on several other ARM64 boards, thanks

**Comment by ok-nick** [comment]
AFAIK, raspberry pi os is currently 32bit, armv7l. I hear they are working on a 64bit os, but it hasn't yet been released.

**Comment by drakkan** [comment]
yuo are right rasperry pi os 64 bit is still beta. I'll evaluate if I can add arm7 support to CI and so generate deb/rpm packages also for this architecture before v2.2.0, thanks

**Comment by drakkan** [comment]
I added [armv7 support to the CI](https://github.com/drakkan/sftpgo/commit/cd72ac4fc942d34b265b9872d39e62c665bbe795), please give a try to produced deb for arm that you can find [here](https://github.com/drakkan/sftpgo/actions/runs/1272910278) and let me know if it works on RPI.

You have to remove the manually installed SFTPGo since the paths could conflict.

Thanks

**Comment by ok-nick** [comment]
Thanks, I tried out the armv7 deb and it works perfectly.
