### ISSUE TITLE
Feature suggest: Public key in file

### ISSUE THREAD

**Issue by anotherdevs** [drakkan/sftpgo#56]
Hi

When giving the user a uid/guid it would also be nice to have the option to use a file as public key repository.

Just like normal users have it.

**Comment by drakkan** [comment]
Hi,

can you please explain  your suggestion with an usage example?

For example:

1) you have a system user `sftpgo` with `uid` 1003, `gid` 1003 and home dir `/home/sftpgo`
2) you put some public keys inside `/home/sftpgo/.ssh`, for example `id_test1.pub`, `id_test2.pub` and so on
3) you create some sftp users for example `sftp_user1`, `sftp_user2` and so on and each of this user is mapped with uid 1003
4) sftpgo should lookup the mapped uid (1003), find its home dir and search for public keys. All the mapped users will be able to login with any found public key

as alternative we could search for public keys inside the home directory defined for each user inside sftpgo data provider.

I don't like these solutions I want to keep all the user data inside the SFTPGo data provider and not search things here and there.

Anyway please provide an usage example to better evaluate your suggestion, thanks!

**Comment by drakkan** [comment]
Please reopen providing an usage example and I'll re-evaluate this request, thanks!
