### ISSUE TITLE
Feature Request: File Hashing / checkFile extension

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#565]
Hi, could you implement the checksum extension?

https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-extensions-00#section-3

thank you.

**Comment by drakkan** [comment]
Hi,

I started working on this a [long time ago](https://github.com/pkg/sftp/pull/326). It requires to add SFTP v6 support in pkg/sftp first and it is not a quick task. If you want this to happen please consider submitting a patch or sponsoring pkg/sftp. Once pkg/sftp will support SFTP v6 I'll add these extensions. Thanks.
