### ISSUE TITLE
Allow Users to Edit Text Files from the Web Interface

### ISSUE THREAD

**Issue by ajl000** [drakkan/sftpgo#567]
It would be great if txt files could be securely edited from the web interface.  MD5 would also be great.
Not overly important for me though as I can download, edit and then reupload.  
Bit different on a public computer.

**Comment by drakkan** [comment]
Hi,

this would be limited to plain text files as you wrote. Basically we could allow you to open files with certain extensions and under a certain size within a text area. If I add things like an HTML editor, I think we might have problems with image links, for example

**Comment by drakkan** [comment]
Maybe I can also try something a bit more advanced like this:

https://github.com/codemirror/codemirror
https://github.com/ajaxorg/ace

These editors are specialized for code, I'm not sure we need them

**Comment by ajl000** [comment]
Hi Nicola,

Thanks for your message.

I have used codemirror a lot. It's really good for xml which is great as I
use basex quite a bit (it's slow but fast to code).

I am not sure how codemirror handles json. From memory not overly well but
that is no issue for me.

If you have academic users  then  fiduswriter has some good reviews.

So for me codemirror is best. I am not sure about others.

Many thanks for considering this.

Adam

**Comment by drakkan** [comment]
Hi,

I'm trying to use codemirror.

I added a small edit icon to the file list

![filelist](https://user-images.githubusercontent.com/553263/136592602-57ecf723-ed13-42d3-9d97-f81f190314a4.png)

that open the edit page

![edit](https://user-images.githubusercontent.com/553263/136592638-d6531f4e-ec2d-42e8-b411-053780c594a3.png)

I plan to use only the search codemirror addon. I don't think we need a full editor here. This is only for basic file editing.

I hope to find enough time this weekend to finalize this feature.

**Comment by ajl000** [comment]
Hi Nicola,

Many thanks, this is brilliant.  I had a look at
https://github.com/filebrowser/filebrowser a while ago.  They edited on
double click (not intuitive).

I had a thought of somehow using the locking of webdav to keep track of who
has checked out a file (eg the user is intending overwriting).  I found
https://stackoverflow.com/questions/69457145/filesystem-backed-locksystem-for-x-net-webdav
which notes 'back locking' to the local file system.  Backlocking would be
complicated.

Anyway I had some thoughts on how to display simple locking (eg just an
indicator), should it be a feature needed by others.  I don't need it but
came across it some time ago using huddle.com as an alternative to
concurrent editing.  Thought I would mention it.

A pdf is attached.

Regards

Adam

**Comment by ajl000** [comment]
Hi Nicola,

Some more of my thoughts.  I haven't put in copy/paste icons like
filebrowser.

I find somethings like elfinder have too many icons - I would have a
separate menu if they were to be included.

Also I use MSWord alot. I wish they had an icon search function, so that I
could easily find the right icon.

Anyway these are just thoughts. I am not requesting ... just vocalising.

Cheers

Adam

**Comment by ajl000** [comment]
Hi Nicola

Thanks for your message.

>>Regarding the locking this could be an issue also with SFTP/FTP,

If you do ever have a locking system ... please consider creating a hidden
file like '{filename}' + '###SFTPGO_locked.hidden' with user and date
information when the file is locked.  Automated file monitoring programs
such as Febooti Automation WorkShop + (Say Dopus Explorer) can then spot
file creation and take action for the backend - locking the file from
direct editing as well.

 A webhook would be even better, but possibly not for cloud storage.

>>Your suggestion to group icons is interesting, I'll give a try (if adding
multiple button groups to a data table will not kill me

Please don't spend any time on this for me.  I just thought that too many
icons might look confused like elFinder.

>>web sharing feature

If sharing could be disabled it would be great.  I don't want to allow
sharing as it can introduce security issues (like symlinks ... where
symlinks can at least be controlled by admin).

>>Concurrent editing is interesting but I don't think the SFTPGo client UI
will become a collaborative platform.

Some businesses might want to collaboratively edit a document with a
client.  This said, I don't need it.

Thanks again

Adam
NB  I hope to provide a recurring sponsorship similar to the small
sponsorship just paid. When I get one user beyond me!

**Comment by drakkan** [comment]
Hi,

yes, sharing will be an optional feature, you can disable it with a specific permission like the other client user interface features.
