### ISSUE TITLE
Feature suggest: Let users be disabled and expire

### ISSUE THREAD

**Issue by anotherdevs** [drakkan/sftpgo#57]
Hi

It would be great to have users to be able to be disabled and expire.

Disabled:
Users in UNIX can be locked. This option doesn't seems to be implemented here.

Expire:
If we can ulitize the actions and http notification webhook to tell the datastore when a user was last used, we can utilise the API to disable/lock user after a certain time, if no last used variable was to be implemeted.

In UNIX we can use the lastlogin command to see when a user has last had it's successful connection.

**Comment by drakkan** [comment]
Hi, 

thanks for your suggestion, I like it.

I think we could add the following new fields for each user:

- `expiration_date`
- `last_login`

so a user cannot login if it is expired (based on the configured expiration date) and you can user the `last_login` field for any custom check
