### ISSUE TITLE
Web Client allow upload, create, delete files and folders

### ISSUE THREAD

**Issue by helmut72** [drakkan/sftpgo#571]
Or integrate something like Filebrowser:
https://github.com/filebrowser/filebrowser

Thank you

**Comment by helmut72** [comment]
Sorry, I found this:
https://github.com/drakkan/sftpgo/issues/533

**Comment by drakkan** [comment]
Hi,

no problem, if you try an edge based docker image or one of the latest build artifact, can you please confirm that WebDAV works fine for your use case? I just pushed an important change, this commit

https://github.com/drakkan/sftpgo/commit/6eb154bb7455f7229e7a4ac774ce75abf99c41f1

includes this patch to the webdav library

https://github.com/drakkan/net/commit/97d22ae145a674ee68daf3b2a85f6acf14598baa

This should fix an issue reported using the Windows WebDAV client.

New docker images should be available in about 1 hour. Thanks

**Comment by helmut72** [comment]
Thanks. WebDAV works with a few tested clients. But I don't have Windows available right now.
