### ISSUE TITLE
Can't create default admin

### ISSUE THREAD

**Issue by CrusaderX** [drakkan/sftpgo#572]
Can somebody help me with creating default admin with `create_default_admin` settings in config file? Because it doesn't create my admin user with any of options:
1. Run sftpgo serve with pre-exported `SFTPGO_DEFAULT_ADMIN_USERNAME` and `SFTPGO_DEFAULT_ADMIN_PASSWORD` environment variables.
2. Run sftpgo as a systemd unit with
```
      [Unit]
      Description=SFTPGo Server
      After=network.target

      [Service]
      User=sftpgo
      Group=sftpgo
      Type=simple
      WorkingDirectory=/opt/sftpgo
      Environment=SFTPGO_CONFIG_DIR=/opt/sftpgo/
      Environment=SFTPGO_CONFIG_FILE=/opt/sftpgo/sftpgo.json
      Environment=SFTPGO_LOG_FILE_PATH=/var/log/sftpgo.log
      Environment=SFTPGO_DEFAULT_ADMIN_USERNAME=poweruser
      Environment= SFTPGO_DEFAULT_ADMIN_PASSWORD=myRandomPassword
      EnvironmentFile=-/etc/sftpgo/sftpgo.env
      ExecStart=/usr/bin/sftpgo serve
      ExecReload=/bin/kill -s HUP $MAINPID
      LimitNOFILE=8192
      KillMode=mixed
      PrivateTmp=true
      Restart=always
      RestartSec=10s

      [Install]
      WantedBy=multi-user.target
```
config installed via `apt` package with `2.1.2-1ppa1` version.

`/opt/sftpgo/` directory is mounted as smb share with `nobrl` option. Before I've tested all possible variants I've stopped sftpgo service and deleted all content inside config dif. And if I run it freshly I see that there is an admin user in sftpgo.db with `admin` username, which is not the username I provided before.

**Comment by CrusaderX** [comment]
It works, got confused because of documentation, main branch doesn't cover latest version? :)

**Comment by drakkan** [comment]
No sorry, main branch is the development version. 2.1.x has its branch, 2.0.x has it branch ecc.. I have to clarify this in some way, it confuses many users
