### ISSUE TITLE
Error with WebDAV to SFTP Backend, works with SFTP to SFTP Backend

### ISSUE THREAD

**Issue by asheroto** [drakkan/sftpgo#575]
Hey there @drakkan, thank so much for your work on this, it's a great tool!

I'm trying to connect to an SFTP server on the backend (server using OpenSSH) but am getting error `SSH_FX_FAILURE` when doing so.  It only affects WebDAV.  Without changing any settings, if I open the virtual folder using an SFTP connection, it shows the backend server's file structure fine.

Computer via SFTP > SFTPGo > Virtual Folder SFTP Backend > Success
Computer via WebDAV > SFTPGo > Virtual Folder SFTP Backend > Fails with SSH_FX_FAILURE

---

Figured out what is causing this.  If a folder is symlinked, SFTP doesn't find out about it until that folder is opened, whereas WebDAV, at least in Windows, tries to access that folder upon opening its parent folder.

Computer via SFTP > SFTPGo > Virtual Folder SFTP Backend:
accessing `/parent` with `/parent/inaccessible` subdirectory inside of it works until I open `/parent/inaccessible`
any accessible folders are fine

Computer via WebDAV > SFTPGo > Virtual Folder SFTP Backend:
accessing `/parent` with `/parent/inaccessible` subdirectory inside of it does not let me open `/parent` at all
cannot access any folders as long as at least 1 folder is inaccessible

Error from log:
`Oct 16 00:07:35 control sftpgo[29746]: {"level":"info","time":"2021-10-16T00:07:35.724","sender":"webdavd","elapsed_ms":86,"method":"PROPFIND","proto":"HTTP/2.0","remote_addr":"<redacted>","request_id":"c5l5s5p6q9grffh6gui0","uri":"https://mySFTPGOserver/virtualfolder","user_agent":"Microsoft-WebDAV-MiniRedir/10.0.19043","error":"sftp: \"Failure\" (SSH_FX_FAILURE)"}`

`Oct 16 00:43:43 control sftpgo[31376]: {"level":"warn","time":"2021-10-16T00:43:43.931","sender":"sftpfs \"<redacted>"","connection_id":"DAV_c5l6d3p6q9gri73uier0","message":"Invalid path resolution, dir \"/real/path/to/404\" original path \"/website/public_html/404\" resolved \"/home/user/web/website/public_html/404\" err: path \"/real/path/to/404\" is not inside: \"/home/user/web\""}`

---

Also discovered another issue.  If you're using WebDAV -> SFTPGo -> S3 Backend, a password of `Abcde!+` will not work but `Abcde` will work.  If using `Abcde!+` logs say "invalid credentials".  If you remove the S3 Backend virtual folder, without changing anything, you can successfully login without error (local folders work fine).

Thank you

**Comment by drakkan** [comment]
Hi,

this is a know issue, please take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/webdav.md), if the SFTP backend returns a permission error the problematic directory is omitted from the directory listing but if it returns a generic error like in your case the directory listing will fail.

Regarding the password issue I configured my minio backend this way:

```
# Local export path.
MINIO_VOLUMES="/srv/minio/data/"
# Server user.
MINIO_ROOT_USER=root
# Server password.
MINIO_ROOT_PASSWORD=Abcdef!+
# Use if you want to run Minio on a custom port.
# MINIO_OPTS="--address :9199"
```

I have no issues connecting to it, which S3 backend are you using?

**Comment by asheroto** [comment]
I see.  Thanks for that.

Got the password issue resolved as well.

**Comment by drakkan** [comment]
after this [change](https://github.com/drakkan/sftpgo/commit/4a6a4ce28dd130c1331b49ad4e75de3898fdb7e5) the problematic directory should be excluded from the webdav directory listing. Can you please confirm? To test this change you need to use the latest development version. You can download a build artificat for you os one [CI](https://github.com/drakkan/sftpgo/actions/runs/1348753448) completes or you can use an edge based docker image once [the build](https://github.com/drakkan/sftpgo/actions/runs/1348753440) ends. Thanks

**Comment by drakkan** [comment]
I also backported this change to the 2.1.x branch so it will be included if I'll make a new 2.1.x release, but I'm not sure this will happen.

You can find build artifact for the 2.1.x branch [here](https://github.com/drakkan/sftpgo/actions/runs/1348781148)

**Comment by drakkan** [comment]
Not related to this issue, I see you are working on an SFTPGo chocolatey package

https://github.com/asheroto/ChocolateyPackages/tree/master/SFTPGo

please let me know if you submit it to the community packages so I'll add the link to the main README. If you prefer you can also send a PR to add the new package [here](https://github.com/drakkan/sftpgo#installation) thanks

**Comment by asheroto** [comment]
Hello, yes, and I just updated it.

However, when I try to push it I get an error, as if someone else already has it uploaded.  Yet, the last time I tried was 5 months ago and I believe that was the problem back then.

![image](https://user-images.githubusercontent.com/49938263/137596842-e741ba64-1a07-4f8c-9363-578d5d64fbbc.png)

I will e-mail a mod about it and report back.  Updated changes have been published to that repo if you want to see.

**Comment by asheroto** [comment]
> I also backported this change to the 2.1.x branch so it will be included if I'll make a new 2.1.x release, but I'm not sure this will happen.
> 
> You can find build artifact for the 2.1.x branch [here](https://github.com/drakkan/sftpgo/actions/runs/1348781148)

Okay, cool.  I just pushed the Chocolatey package, will let you know when it's up, usually it takes a few days for them to approve it.  For the next release of sftpgo, do you want to / plan on setting a package icon?  It's generally the icon of the EXE or company logo, visible to the left of the title in the listing and the package page.  If so just add it somewhere in the repo and I'll link it to the package so that icon will appear next release.

https://community.chocolatey.org/packages

**Comment by drakkan** [comment]
> > I also backported this change to the 2.1.x branch so it will be included if I'll make a new 2.1.x release, but I'm not sure this will happen.
> > You can find build artifact for the 2.1.x branch [here](https://github.com/drakkan/sftpgo/actions/runs/1348781148)
> 
> Okay, cool. I just pushed the Chocolatey package, will let you know when it's up, usually it takes a few days for them to approve it. For the next release of sftpgo, do you want to / plan on setting a package icon? It's generally the icon of the EXE or company logo, visible to the left of the title in the listing and the package page. If so just add it somewhere in the repo and I'll link it to the package so that icon will appear next release.
> 
> https://community.chocolatey.org/packages

Hi, thank you!

Regarding the logo, well I have no company, this is an hobby project. For the AWS marketplace I used the image [here](https://raw.githubusercontent.com/drakkan/sftpgo/main/docs/howto/img/logo.png) as logo. Not sure whether to add it to the exe as is or without characters, similar to the favicon used for web pages.

Regarding you package, please note that the correct URL is `http://localhost:8080` and not `https://localhost:8080`, please fix this [here](https://github.com/asheroto/ChocolateyPackages/blob/master/SFTPGo/tools/ChocolateyInstall.ps1#L26).

**Comment by asheroto** [comment]
Ah nice catch. I request that Chocolatey reject the package so I can submit the correction.  I have pushed the commit with the changes.

For the icon, I like yours, but I came up with a few that you might like to check out. Freely acquired from Reshot.com and IconFinder.com.  Modified in Photoshop.  It's good to leave a margin around the image so it fits nicely, and you'll want to pick one with square dimensions.

![image](https://user-images.githubusercontent.com/49938263/137622140-764dacd6-150f-418a-b36f-75f1da63f12d.png)

![image](https://user-images.githubusercontent.com/49938263/137622145-7703da55-3dd2-4206-bddb-6ebd3055d042.png)

![image](https://user-images.githubusercontent.com/49938263/137622151-ae012858-a5f3-4f59-8867-11140a75bf29.png)

![image](https://user-images.githubusercontent.com/49938263/137622155-bf33c9e5-6b96-41d9-b9a4-cd794288cfbe.png)

[You can download a 7z archive here](https://mega.nz/file/eCZWEZRT#EH4W_vBQy9RtLkewwBPbBL_ij7MvBJpHJu9LF7XR3tk).  Includes PSD (Photoshop) file, png file, and svg file (converted to vector for easy resizing) as well as the font files used.  My way of contributing to the project! :-)

**Comment by drakkan** [comment]
there is also another small typo [here](https://github.com/asheroto/ChocolateyPackages/blob/master/SFTPGo/tools/ChocolateyInstall.ps1#L3): it should be SFTPGo, maybe this can be fixed in a future update

**Comment by asheroto** [comment]
Here's what the installation will look like, except once approved users will just type `choco install sftpgo` to install.

![image](https://user-images.githubusercontent.com/49938263/137697189-b85d322d-48c7-4ab0-8310-017854d067d4.png)

**Comment by asheroto** [comment]
Hey what's a good email address for you so I can communicate?

**Comment by drakkan** [comment]
> Hey what's a good email address for you so I can communicate?

Hi you can write to my public email address nicola.murino at gmail.com

**Comment by asheroto** [comment]
Thanks, sent you an email.
