### ISSUE TITLE
Local folder as another user

### ISSUE THREAD

**Issue by asheroto** [drakkan/sftpgo#577]
Not a bug this time but a question, hope that's okay.

I have a few different virtual folders with different user accounts as the owner.  When I create a new file in one of these, sftpgo is the owner, but I want the owner to be a different username.

Is there a way to accomplish this?  I was looking at doing a custom action/command and by running `chown` on the file/folder, but if there's a simpler or more recommended way I'd rather use that.

Thanks again 👍

**Comment by drakkan** [comment]
You can run sftpgo as root user and then set the wanted UID/GID when you configure your user. Alternately you can run sftpgo as a different user. 

If you want a different user per-directory the only way is a custom hook

**Comment by asheroto** [comment]
Perfect, thanks, didn't see the UID before 👍
