### ISSUE TITLE
Modifying SSH2/SFTP values based on connecting client

### ISSUE THREAD

**Issue by Solvik** [drakkan/sftpgo#578]
Hello

We have a problem with some clients using SFTPGo servers.
We've switched thousands of accounts from proftpd to sftpgo and anticipated this problem which we mitigated with our old platform for the moment.

With proftpd there's a feature called `SFTPClientMatch` which can modify several parameters based on the client. 
For example in our case, the channelWindowSize to 1GB
Here's [the link to proftpd documentation](http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPClientMatch)

Is there a way to come up with such a feature within sftpgo ? I'd be happy to work on implementing this with your guidance :)

**Comment by drakkan** [comment]
ok, let me know if you can provide me something to test. 

As first step you could try to compile SFTPGo against a patched crypto/ssh with `channelWindowSize = 32 * channelMaxPacket`

**Comment by drakkan** [comment]
Hi @Solvik, 

Do you have some news about this? Based on the info [here](https://forum.directadmin.com/threads/proftpd-issue-with-sftp.63352/) I downloaded trial version of ws_ftp but it seems to work fine. 

From what I understand I guess our default can only create issues for clients that expect a windows size as signed int32 and then they overflow. 

If this is the case something like this:

```
channelWindowSize = 64 * channelMaxPacket -1
```

should work with every client. However if I'll have a client with this issue or a reproducer I'll try to make the windowSize configurable as in ProFTPD. Thanks

**Comment by drakkan** [comment]
Hi,

I tested myself the trial version of ws_ftp against proftpd/mod_sftp and it works without changing the default channel window size, so this workaround seems required for older versions.

However please note that proftpd/mod_sftp uses by default a very big windows size (4GB) while golang/crypto/ssh (the library used in SFTPGo) use a 2MB window size, the same as [OpenSSH](https://github.com/openssh/openssh-portable/blob/master/channels.h#L212), so probably this issue does not affect SFTPGo. 

I'll leave the issue open for further investigations, please let me know if you find a client with this issue, thank you.

**Comment by Solvik** [comment]
Hello @drakkan , sorry for getting back to you this late.

A recent ws_ftp didn't have the issue.

We've worked around this issue by making the only few customers move away from their old client. 
So this issue isn't a problem anymore.

Thanks for digging, I'm closing this issue and hope nobody encounters this problem in the future :)

**Comment by drakkan** [comment]
uhm .. so you have this problem with SFTPGo and some old clients too? I would like to be able to replicate it and fix it
