### ISSUE TITLE
reverse proxy prefix

### ISSUE THREAD

**Issue by cyayon** [drakkan/sftpgo#579]
Hello,

is it possible to define an http (web admin and client) prefix to be able to use a reverse proxy in front of ?

i tried to use nginx but i didn't manage because a prefix is required to use a subdir /sftpgo/web/client or /sftpgo/web/admin for example.

Thanks.

**Comment by cyayon** [comment]
Thanks !!

**Comment by derekmahar** [comment]
Please note the new [location of `web_root`](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L317) in the [default SFTPGo configuration](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json).  I guess this location changes as new lines appear before `web_root` in the default configuration.

**Comment by derekmahar** [comment]
I use the following [NGINX](https://www.nginx.com/) reverse proxy configuration for SFTPGo in [SWAG](https://github.com/linuxserver/docker-swag):

```
$ docker exec --interactive --tty swag bash
# cat /config/nginx/proxy-confs/sftpgo.subfolder.conf
location /sftpgo {
    return 301 $scheme://$host/sftpgo/;
}

location ^~ /sftpgo/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Script-Name /sftpgo;

    location ^~ /sftpgo/web {
        proxy_pass http://sftpgo:8080;
    }

    location ^~ /sftpgo/dav {
        proxy_pass http://sftpgo:10080;
    }
}
```

SFTPGo configuration:

```
$ docker exec --interactive --tty sftpgo sh
/var/lib/sftpgo $ cat sftpgo.json
{
  "httpd": {
    "web_root": "/sftpgo/web"
  },
  "webdavd": {
    "bindings": [
      {
        "prefix": "/sftpgo/dav"
      }
    ]
  }
}
```

- SFTPGo Web Client URL: https://192.168.0.3/sftpgo/web/web/client/login
- SFTPGo Web Admin URL: https://192.168.0.3/sftpgo/web/web/admin/login
- SFTPGo WebDAV URL: https://192.168.0.3/sftpgo/dav

For a reason I don't yet understand, https://192.168.0.3/sftpgo/web/web redirects to https://192.168.0.3/sftpgo/web/web/client/login, but https://192.168.0.3/sftpgo/web redirects to https://192.168.0.3/web/client/login (sftpgo prefix is absent).

**Comment by drakkan** [comment]
Hi,

it seems to work for me

```
curl --verbose "http://127.0.0.1/sftpgo/web"
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /sftpgo/web HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.83.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Server: nginx/1.20.2
< Date: Tue, 07 Jun 2022 07:31:45 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 51
< Connection: keep-alive
< Location: /sftpgo/web/web/client/login
< 
<a href="/sftpgo/web/web/client/login">Found</a>.

* Connection #0 to host 127.0.0.1 left intact
```

can you post your curl output and the SFTPGo logs? If you are trying with a browser try to clear the cache

**Comment by derekmahar** [comment]
> can you post your curl output and the SFTPGo logs? If you are trying with a browser try to clear the cache

Curl correctly redirected https://192.168.0.3/sftpgo/web to https://192.168.0.3/sftpgo/web/web/client/login.

After clearing the cache in Firefox, Firefox also redirected https://192.168.0.3/sftpgo/web to https://192.168.0.3/sftpgo/web/web/client/login.  Before clearing the cache, why was Firefox redirecting to https://192.168.0.3/web/client/login?  (Had I cleared my Firefox cache or used curl earlier, I would have saved myself a lot of time tweaking and testing my reverse proxy configuration!  On the bright side, at least I now have a much better understanding of the NGINX location directive.)

Curl output:

```
ubuntu@raspberrypi1:~$ curl --insecure --verbose https://192.168.0.3/sftpgo/web
*   Trying 192.168.0.3:443...
* Connected to 192.168.0.3 (192.168.0.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=<redacted>
*  start date: May  9 05:09:32 2022 GMT
*  expire date: Aug  7 05:09:31 2022 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0xaaaad8026e60)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /sftpgo/web HTTP/2
> Host: 192.168.0.3
> user-agent: curl/7.81.0
> accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 302
< server: nginx
< date: Tue, 07 Jun 2022 14:48:22 GMT
< content-type: text/html; charset=utf-8
< content-length: 51
< location: /sftpgo/web/web/client/login
<
<a href="/sftpgo/web/web/client/login">Found</a>.

* Connection #0 to host 192.168.0.3 left intact
```
(Note that I redacted the domain name in the certificate to avoid publishing my home server address.)

**Comment by drakkan** [comment]
browsers cache everything, this has happened to me several times, so now I always use `curl` for this type of test :smile: 

For my info, a user asked a similar question on [reddit](https://www.reddit.com/r/homelab/comments/v4529r/what_is_the_best_way_to_setup_and_remotely_access/) some days ago.

Are you the same user? If not I'll link this answer on reddit, thanks

**Comment by derekmahar** [comment]
> for webdav I suggest something like this:
> 
> ```
> location ^~ /sftpgo/dav {
>              client_max_body_size 0;
>              proxy_set_header Host $host;
>              proxy_pass http://127.0.0.1:10080;
> }
> ```
> 
> the default value for `client_max_body_size` is 1m. The `Host` header is required for rename and copy webdav operations. You could also evaluate `proxy_http_version 1.1;` nginx use http 1.0 by default. And maybe you also want to set something like this `proxy_set_header X-Real-IP $remote_addr;` to get the real client IP and add the proxy IP in the [trusted list](https://github.com/drakkan/sftpgo/blob/v2.3.0/sftpgo.json#L152)

As far as I can tell, my SFTPGo WebDAV server is so far is working without any errors.  (I'm so satisfied with it, actually, that I've already deleted my complicated and troublesome Nextcloud server.  The SFTPGo WebDAV server is also superior to the WebDAV server in TrueNAS which supports only a single user.)

I neglected to post it, but `/config/nginx/proxy.conf` in the SWAG docker container includes `proxy_set_header Host $host;` and `proxy_set_header X-Real-IP $remote_addr;`:

```
ubuntu@raspberrypi1:~$ docker exec --interactive --tty swag bash
root@DockSTARTer:/# cat config/
.donoteditthisfile.conf  custom-services.d/       fail2ban/                log/                     www/
crontabs/                dns-conf/                geoip2db/                nginx/
custom-cont-init.d/      etc/                     keys/                    php/
root@DockSTARTer:/# cat config/nginx/proxy.conf
## Version 2021/10/26 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/proxy.conf

# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Proxy Connection Settings
proxy_buffers 32 4k;
proxy_connect_timeout 240;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
proxy_http_version 1.1;
proxy_read_timeout 240;
proxy_redirect  http://  $scheme://;
proxy_send_timeout 240;

# Proxy Cache and Cookie Settings
proxy_cache_bypass $cookie_session;
#proxy_cookie_path / "/; Secure"; # enable at your own risk, may break certain apps
proxy_no_cache $cookie_session;

# Proxy Header Settings
proxy_set_header Connection $connection_upgrade;
proxy_set_header Early-Data $ssl_early_data;
proxy_set_header Host $host;
proxy_set_header Proxy "";
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Real-IP $remote_addr;
```

I will add `client_max_body_size 0;` to the WebDAV server reverse proxy configuration.

For completeness, here is the contents of `config/nginx/resolver.conf`:

```
ubuntu@raspberrypi1:~$ docker exec --interactive --tty swag bash
root@DockSTARTer:/# cat config/nginx/resolver.conf
# This file is auto-generated only on first start, based on the container's /etc/resolv.conf file. Feel free to modify it as you wish.

resolver  127.0.0.11 valid=30s;
```

**Comment by derekmahar** [comment]
I recently revisited my [SWAG and SFTPGo reverse proxy configuration](https://github.com/drakkan/sftpgo/issues/579#issuecomment-1147755381) in order to remove the duplicate copy of subpath "web/" in the SFTPGo Web Client and Admin URLs.

SWAG configuration:
```
ubuntu@raspberrypi1:~$ docker exec --interactive --tty swag bash
root@swag:/# cat /config/nginx/proxy-confs/sftpgo.subfolder.conf
location /sftpgo {
    return 301 $scheme://$host/sftpgo/;
}

location ^~ /sftpgo/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Script-Name /sftpgo;

    location ^~ /sftpgo/dav/ {
        client_max_body_size 0;
        proxy_set_header Host $host;
        proxy_pass http://sftpgo:10080/sftpgo/dav/;
    }

    location ^~ /sftpgo/ {
        proxy_pass http://sftpgo:8080/sftpgo/;
    }
}
```

Note that in each inner location block, I appended the location URL fragment to the original `proxy_pass` URL.  In the WebDAV inner location block, I replaced `proxy_pass` URL "http://sftpgo:10080" with "http://sftpgo:10080/sftpgo/dav/" and in the HTTP server inner location block, I replaced `proxy_pass` URL "http://sftpgo:8080" with "http://sftpgo:8080/sftpgo/".  To construct these `proxy_pass` URLs, I followed some tips from [Nginx: Everything about proxy_pass](https://dev.to/danielkun/nginx-everything-about-proxypass-2ona).

SFTPGo configuration:
```
ubuntu@raspberrypi1:~$ docker exec --interactive --tty sftpgo sh
/var/lib/sftpgo $ cat /var/lib/sftpgo/sftpgo.json
{
  "httpd": {
    "web_root": "/sftpgo"
  },
  "webdavd": {
    "bindings": [
      {
        "prefix": "/sftpgo/dav"
      }
    ]
  }
}
```

Note that I removed the trailing "/web" subpath from the httpd server `web_root` and left the webdavd server `prefix` unchanged.

Send a request to the SFTPGo HTTP server:
```
ubuntu@raspberrypi1:~$ curl --insecure --verbose https://192.168.0.3/sftpgo/
*   Trying 192.168.0.3:443...
* Connected to 192.168.0.3 (192.168.0.3) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.redviking.duckdns.org
*  start date: Apr  7 05:09:54 2024 GMT
*  expire date: Jul  6 05:09:53 2024 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
*   Certificate level 0: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://192.168.0.3/sftpgo/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: 192.168.0.3]
* [HTTP/2] [1] [:path: /sftpgo/]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET /sftpgo/ HTTP/2
> Host: 192.168.0.3
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/2 302
< server: nginx
< date: Sat, 01 Jun 2024 23:08:49 GMT
< content-type: text/html; charset=utf-8
< content-length: 47
< location: /sftpgo/web/client/login
<
<a href="/sftpgo/web/client/login">Found</a>.

* Connection #0 to host 192.168.0.3 left intact
```

Note that the duplicate "/web" subpath in the location URL is gone!

**Comment by biomassboilers** [comment]
I know this issue is closed, but it seems to be a current issue, as [no matter what I do, SFTPGo refuses to run properly behind a reverse proxy](https://github.com/drakkan/sftpgo/discussions/2051). It doesn't display any HTML/JS/CSS, and redirects to 404, no matter what is set in `web_root`, and `web_admin_root` no longer (?) seems to exist or work.
