### ISSUE TITLE
Feature suggest: Let the API create a UNIX user

### ISSUE THREAD

**Issue by anotherdevs** [drakkan/sftpgo#58]
Hi

Can it be possible (and it's a huge security risk) to have the API to create a new UNIX user?

It's useful for when you want to use the uid/guid parameters to have more granular control of the folders in the users home folder.

**Comment by drakkan** [comment]
Hi,

creating a UNIX user requires root permission and it is OS specific while SFTPGo should remain cross platform.

I propose to add custom actions/HTTP notifications after a user is created, deleted, updated so you can have your logic there.

**Comment by drakkan** [comment]
fixed in https://github.com/drakkan/sftpgo/commit/acdf35104730d38873b94db83dc159a7eb3e435c

you can now add a custom commad to create the UNIX user if you want, thanks for the suggestion
