### ISSUE TITLE
Logs generated at level "debug" even though it's disabled?

### ISSUE THREAD

**Issue by asheroto** [drakkan/sftpgo#580]
Logged into my server and checked the log file.... 200 MB! 😲

In my service...
```
/etc/systemd/system/multi-user.target.wants/sftpgo.service
```

This is my ExecStart value...
```
/usr/bin/sftpgo serve --log-verbose false
```

But checking the log file, I see tons of lines containing the level "debug"...
```
Oct 21 09:02:06 control sftpgo[22362]: {"level":"debug","time":"2021-10-21T09:02:06.665","sender":"DAV","connection_id":"asdfasdfasdf","message":"connection removed, close fs error: <nil>, num open connections: 0"}
```

I was using the default log, `/var/log/syslog`, but I just changed the log path, specifying in ExecStart...
```
/usr/bin/sftpgo serve --log-verbose false --log-file-path /etc/sftpgo/sftpgo.log --log-max-size 10
```

Reloaded daemon and restarted service, but it still is showing level "debug" as well as "info"
```
{"level":"debug","time":"2021-10-21T09:14:17.041","sender":"DAV","connection_id":"asdfasdf","message":"transfer removed, id: 5 active transfers: 0"}
{"level":"info","time":"2021-10-21T09:14:17.041","sender":"webdavd","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/2.0","remote_addr":"1.2.3.4:853","request_id":"c5onbe96q9gv7lni0s40","uri":"https://asdfasdfsdaf:1111/as/apidfasdf.asdfasfd.net/asdfasdf","user_agent":"Microsoft-WebDAV-MiniRedir/10.0.19043"}
{"level":"debug","time":"2021-10-21T09:14:17.041","sender":"DAV","connection_id":"asdfasdf","message":"connection removed, close fs error: <nil>, num open connections: 0"}
{"level":"debug","time":"2021-10-21T09:14:17.084","sender":"DAV","connection_id":"asdfasdf","message":"connection added, num open connections: 1"}
{"level":"debug","time":"2021-10-21T09:14:17.085","sender":"DAV","connection_id":"asdfasdf","message":"error running stat on path \"/seasdfasdf": file does not exist"}
{"level":"info","time":"2021-10-21T09:14:17.085","sender":"webdavd","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/2.0","remote_addr":"1.2.3.4:853","request_id":"c5onbe96q9gv7lni0s4g","uri":"https://asdfasdfads:1111/asdfasdf/desktop.ini","user_agent":"Microsoft-WebDAV-MiniRedir/10.0.19043","error":"file does not exist"}

```

I did not see anything about log levels as parameters except for `--log-verbose` but did notice this...
![image](https://user-images.githubusercontent.com/49938263/138296770-7b10228a-7e0b-4861-8d43-11692e2c3563.png)

I do not have the "debug" string anywhere in my `sftpgo.json` file.... I am using WebDAV not FTP, does sftpgo expect a debug string in the WebDAV section as well?

Thanks man!

**Comment by TheManchineel** [comment]
This is still a problem for me. I'm using the official Docker container (drakkan/sftpgo:latest) and `-e SFTPGO_LOG_VERBOSE=0`, and yet debug-level lines still print out in the log

**Comment by TheManchineel** [comment]
For anyone looking now, it's SFTPGO_LOG_LEVEL=error

**Comment by percenuage** [comment]
Hi, the env var `SFTPGO_LOG_LEVEL=error` doesn't work on Kubernetes. I still have log level "info" 
```yaml
# values.yaml
image:
  repository: drakkan/sftpgo
  tag: v2.3.3-alpine

command: [ "/bin/sh", "-c" ]
args: ["sftpgo initprovider && sftpgo serve"]

env:
  SFTPGO_LOG_LEVEL: error
```
```
{"level":"info","time":"2024-03-01T18:04:44.075","sender":"httpd" ...
```
I saw this doc https://github.com/drakkan/sftpgo/blob/main/docs/logs.md but I don't understand how to use it.

Thx for your help :)

**Comment by percenuage** [comment]
Up /open

**Comment by lucker999** [comment]
The same on FreeBSD, tried all the above, namely
SFTPGO_LOG_LEVEL=error
SFTPGO_LOG_VERBOSE=0

Still have many lines of  debug and info level in the log
