### ISSUE TITLE
Fail2ban integration: Adding the source IP address in logs

### ISSUE THREAD

**Issue by binou-31** [drakkan/sftpgo#59]
Hello Drakkan, 

I was thinking about fail2ban integration with sftpgo but unfortunatly, they is no the source IP address in logs.
I notify two cases :

When user does not exist: 
`{"level":"warn","sender":"sqlite","connection_id":"","time":"2019-11-10T20:09.25.756","message":"error authenticating user: toto, error: Not found: sql: no rows in result set"}`

When user exist but password failed: 
`{"level":"warn","sender":"sftpd","connection_id":"","time":"2019-11-10T20:10.08.775","message":"failed to accept an incoming connection: [ssh: no auth passed yet, could not validate credentials, could not validate credentials, could not validate credentials, could not validate credentials, could not validate credentials]"}`
In this second case, user is not mentioned in the log. Is it normal ? 

I'm not developer, but if someone add IP in logs, i'll make the fail2ban configuration :)
Regards,

**Comment by drakkan** [comment]
@binou-31 thanks for your suggestion, I'll try to implement it myself. 

In addition to the cases you listed I think the following one should be considered too:

- a client connect but never login or do something (you can simulate with something like `telnet 127.0.0.1 2022`), after 2 minutes the client will be disconnected with this log:

```
{"level":"warn","sender":"sftpd","connection_id":"","time":"2019-11-11T08:48.23.374","message":"failed to accept an incoming connection: read tcp 127.0.0.1:2022->127.0.0.1:37502: i/o timeout"}
```

**Comment by binou-31** [comment]
Thanks, 

I summarize the logs without the source IP address we needed for fail2ban:

*  User does not exist
<pre><code>{"level":"warn","sender":"sqlite","connection_id":"","time":"2019-11-10T20:09.25.756","message":"error authenticating user: toto, error: Not found: sql: no rows in result set"}</code></pre>
* Password failed
<pre><code>{"level":"warn","sender":"sftpd","connection_id":"","time":"2019-11-11T10:02.23.144","message":"failed to accept an incoming connection: [ssh: no auth passed yet, could not validate credentials, could not validate credentials, could not validate credentials]"}</code></pre>
* Incoming connection aborted can be use to flood log.
  * `echo | nc -t 127.0.0.1 2022`
<pre><code>{"level":"warn","sender":"sftpd","connection_id":"","time":"2019-11-11T10:04.28.616","message":"failed to accept an incoming connection: EOF"}</pre></code>
* Connection Timeout
  * With `$IP` is source IP already mentioned
<pre><code>{"level":"warn","sender":"sftpd","connection_id":"","time":"2019-11-11T10:06.03.175","message":"failed to accept an incoming connection: read tcp 172.17.0.5:2022->$IP:20852: i/o timeout"}</pre></code>

**Comment by drakkan** [comment]
@binou-31 this seems too complex, I'm adding a new logging category something like this

- **"auth_failed"**
    - `sender` string. `auth_failed`
    - `level` string
    - `username`, string. Can be empty if the client open the connection and don't try to login
    - `host` string.
    - `login_type` string. Can be `public_key`, `password` or `no_auth_tryed`
    - `error` string. Optional error description

so you will have logs such as this ones:

- Connection Timeout
```
{"level":"debug","sender":"auth_failed","username":"","host":"127.0.0.1","login_type":"no_auth_tryed","error":"read tcp 127.0.0.1:2022->127.0.0.1:41694: i/o timeout","time":"2019-11-11T11:35.18.869"}
```

- Incoming connection aborted
```
{"level":"debug","sender":"auth_failed","username":"","host":"127.0.0.1","login_type":"no_auth_tryed","error":"EOF","time":"2019-11-11T11:37.14.480"}
```

- User does not exist
```
{"level":"debug","sender":"auth_failed","username":"nicolaa","host":"127.0.0.1","login_type":"public_key","error":"Not found: sql: no rows in result set","time":"2019-11-11T11:38.18.975"}
```

or
 
```
{"level":"debug","sender":"auth_failed","username":"nicolaa","host":"127.0.0.1","login_type":"password","error":"Not found: sql: no rows in result set","time":"2019-11-11T11:38.20.136"}
```
- Invalid credentials
```
{"level":"debug","sender":"auth_failed","username":"nicola","host":"127.0.0.1","login_type":"public_key","error":"Invalid credentials","time":"2019-11-11T11:39.50.031"}
```

or 

```
{"level":"debug","sender":"auth_failed","username":"nicola","host":"127.0.0.1","login_type":"password","error":"Invalid credentials","time":"2019-11-11T11:39.53.282"}
```

what do you think about?

Please note that many ssh clients will implictly try public_key authentication so a lot of failed public key auths could be normal if you are logging in using passwords

**Comment by drakkan** [comment]
is it useful to better integrate fail2ban to have separate logging sender for auth_failed and timeouts/Incoming connection aborted? Thanks

**Comment by drakkan** [comment]
I did some test myself and it seems to work:

```
fail2ban-regex '{"level":"debug","time":"2019-11-11T14:42:58.224","sender":"connection_failed","username":"","host":"127.0.0.1","login_type":"no_auth_tryed","error":"EOF"}' '"host":"<HOST>".*\"login_type":"no_auth_tryed"'

Running tests
=============

Use   failregex line : "host":"<HOST>".*\"login_type":"no_auth_tryed"
Use      single line : {"level":"debug","time":"2019-11-11T14:42:58.224",...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] "host":"<HOST>".*\"login_type":"no_auth_tryed"
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.02 sec]
```

```
fail2ban-regex '{"level":"debug","time":"2019-11-11T14:58:11.772","sender":"connection_failed","host":"127.0.0.1","username":"nicola","login_type":"password","error":"Credentials cannot be null or empty"}' '"host":"<HOST>".*\"login_type":"password"'

Running tests
=============

Use   failregex line : "host":"<HOST>".*\"login_type":"password"
Use      single line : {"level":"debug","time":"2019-11-11T14:58:11.772",...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] "host":"<HOST>".*\"login_type":"password"
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.02 sec]
```

I'll push these changes and I'll close the bug, please reopen if it doesn't work for you

**Comment by jovandeginste** [comment]
May I humbly suggest renaming `host` to `client_ip`? Unless I misunderstood the lines, of course...

**Comment by drakkan** [comment]
> May I humbly suggest renaming `host` to `client_ip`? Unless I misunderstood the lines, of course...

`client_ip` is better, thanks!

**Comment by binou-31** [comment]
Hello drakkan,

Sorry for my absence. You work very fast, as usually !!
It's perfect for fail2ban.
Once i have more time, i'll make the fail2ban configuration and i'll send you a merge request to update the README as well.

Many thanks for your work !

**Comment by drakkan** [comment]
> Hello drakkan,
> 
> Sorry for my absence. You work very fast, as usually !!
> It's perfect for fail2ban.
> Once i have more time, i'll make the fail2ban configuration and i'll send you a merge request to update the README as well.

this would be great! Please add the config to the log section where I already mentioned Fail2ban, thanks!

> 
> Many thanks for your work !
