### ISSUE TITLE
Action example

### ISSUE THREAD

**Issue by audouts** [drakkan/sftpgo#591]
Is there an example for an "upload" action?

Specifically, I would like to see how to move a file, after the upload completes.

Thanks!

**Comment by drakkan** [comment]
Hi,

assuming you are on Linux and you are using the local filesystem, you can change the configuration like this

```json
...
"actions": {
      "execute_on": ["upload"],
      "execute_sync": [],
      "hook": "/tmp/upload_action.sh"
},
...
```

and add this content to `/tmp/upload_action.sh` (you have to add the execute bit to this file)

```bash
#!/bin/bash

DESTDIR=/tmp
FILE_NAME=$(basename "$SFTPGO_ACTION_PATH")
mv $SFTPGO_ACTION_PATH $DESTDIR/$FILE_NAME

exit 0
```

this way each uploaded file will be moved to `/tmp`, please take a look at the docs [here](https://github.com/drakkan/sftpgo/blob/main/docs/custom-actions.md) for all the supported env vars.

Please be aware that some clients try to stat the uploaded files and they could error out if you move it

**Comment by audouts** [comment]
Excellent. Thank you! Yes, I'm using Linux. If I added a short delay, would a client be able to stat during that? Otherwise, a stat error probably isn't a big deal.

**Comment by drakkan** [comment]
a delay could help, it depends on your use case :)
