### ISSUE TITLE
Load balanced setup interruptions / Support multile storages per user

### ISSUE THREAD

**Issue by Roni1993** [drakkan/sftpgo#598]
Hey drakkan,

first, thanks for pouring so much work into this project. sftpgo has been a charm to work with so far.

However, I'm currently hitting a limited use-case in my personal project.
I ideally want to be able to dynamically add folders/volumes to a users home based on a workload that runs in a k8s cluster.
sftpgo also runs as a loadbalanced workload within the k8s cluster. My problem is that as soon as a new/additional workload gets spun up i need to add its volume to sftpgo which requires new sftpgo instances.

So is it possible to set up a proxy/LB in a way that the user is fully unaware of a proxy switching to a different sftpgo instance during an upload?

Should this not be possible, my next best solution would be to let each workload publish it's volume cluster internally via sftp & i would simple route these through sftpgo. However i would need to be able to set multiple storages per user to use it. 
(e.g. 1 user, 3 workloads, 3, sftps)

I hope I could roughly explain my use-case & hope that this question isn't too open-ended

**Comment by Roni1993** [comment]
Note: i just skimed through the docs & realized that my 2nd request was added as a feature in 2.1 and i was using 2.0 up until now

**Comment by drakkan** [comment]
Hi,

I'm not sure to fully understand your question, you can add/remove virtual folders dynamically, the already logged in users will not see the change. A virtual SFTP filesystem should resolve this issue. 

You could also consider to use a MinIO/Ceph cluster (or something similar) and use it as storage backend for SFTPGo

**Comment by Roni1993** [comment]
I think that using the virtual folders & setting thes up dynamically should work for my use-case.
Regarding the load-balancing, is there any way i can check that i have correctly set up the loadbalancer & sftpgo?

**Comment by drakkan** [comment]
> I think that using the virtual folders & setting thes up dynamically should work for my use-case. Regarding the load-balancing, is there any way i can check that i have correctly set up the loadbalancer & sftpgo?

For SFTP it's quite simple, every connection will be redirected to a backend and served by that backend. For HTTP, in v2.1.x you need to enable sticky sessions to make sure the same source is always redirected to the same backend. If you are using the development version (it will become v2.2.0 in a few weeks), you can configure a shared [signing_passphrase](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L223) for all nodes therefore no special care is needed even for the stateless HTTP sessions

**Comment by Roni1993** [comment]
alright, thanks i'll try that!

**Comment by drakkan** [comment]
Please re-open or post here if you have other questions
