### ISSUE TITLE
Take action on uploaded file

### ISSUE THREAD

**Issue by mcdappdev** [drakkan/sftpgo#6]
Hi there,

Thanks for this great library! Having something like this would have saved my team and I a bunch of time had it been around a year ago :) 

One thing that we do that doesn't seem to be supported in this library is taking immediate action on a file that is added to the server. So when upload.csv gets added to a user's folder, we immediately pick it up, ship it off to a different server via an API, and delete the file (via a script that is pretty fragile). 

Is something like that in scope for this project? I think it would be an amazing addition that could really pull this together as a fully managed solution.

Regardless of if it is possible or not, we plan to switch to this project in the near future :) Thank you for your work!!

**Comment by drakkan** [comment]
Hi,

I'm glad you find sftpgo useful. 

I plan to add an upload script configuration in future updates. This way you can configure an absolute path to an external command that is called with the uploaded file path as argument.

Is this what you need?

**Comment by mcdappdev** [comment]
That would be so amazing!!! That’s exactly what we would need :)

**Comment by drakkan** [comment]
it is now supported

https://github.com/drakkan/sftpgo/commit/48451a992429d1514a4007ee7041a3c9c1c62838

you can executed an external command or send an http get on upload, download, delete or rename

**Comment by mcdappdev** [comment]
Thank you!!

**Comment by mcdappdev** [comment]
Haven't been able to get this to work, perhaps it's something I'm doing wrong. Here is what I added to my config:

```json
        "actions": {
            "execute_on": [
                "upload"
            ],
            "command": "/app/upload.sh"
        }
```

And this is my script:

```bash
 #!/bin/bash 
echo $@ >> test.txt
```

When I upload a file, though, it doesn't output anything to the `test.txt` file. I've verified that running `/app/upload.sh a b c` outputs `a b c` to `test.txt` from inside the container. Any ideas?

**Comment by drakkan** [comment]
Hi,

can you paste the logs for an upload? Thanks

**Comment by mcdappdev** [comment]
Here are the logs:

```
{"level":"debug","sender":"sftpd","time":"2019-07-28T12:56.48.675","message":"file upload/replace started for path \"/schools/jimmy/IHB_Agreement_and_Waiver_Template.pdf\" user: jimmy"}
{"level":"info","sender":"SFTPUpload","elapsed_ms":638,"size_bytes":12812638,"username":"jimmy","file_path":"/schools/jimmy/IHB_Agreement_and_Waiver_Template.pdf","connection_id":"eba26fd41757033e18423ff2b261297522ebe6822a13b57fed58db3f62982e5d","time":"2019-07-28T12:56.49.314"}
{"level":"debug","sender":"sftpd","time":"2019-07-28T12:56.49.316","message":"executed command \"/app/upload.sh\" with arguments: upload, /schools/jimmy/IHB_Agreement_and_Waiver_Template.pdf, , error: fork/exec /app/upload.sh: exec format error"}
```

Looks like I'm getting an error where you're not: `fork/exec /app/upload.sh: exec format error`

**Comment by drakkan** [comment]
ah ok so the space before `#!/bin/bash` in your script is not a copy/paste error, try to remove it to have a valid shebang

**Comment by mcdappdev** [comment]
Oh yikes, good catch!! Let me try that now.

**Comment by mcdappdev** [comment]
That worked!! Thank you :)

**Comment by drakkan** [comment]
Great!

Please let me know how sftpgo works in general for your use case. I think the only missing feature for the first "stable" release is atomic upload, but let's wait a bit and see what other users report back

**Comment by mcdappdev** [comment]
Sounds good! I'm almost done Dockerizing the entire setup, and once that's done I'm planning on deploying to AWS ECS and replacing our current home-grown (bad) system :)

**Comment by drakkan** [comment]
I suggest to do accurate tests before to replace a working system :)

**Comment by mcdappdev** [comment]
Oh yeah of course :) By atomic upload do you mean that right now notifications will be sent before the upload is complete?

**Comment by drakkan** [comment]
No I mean that the uploaded file has a temporary name before the upload complete.

For example an sftp client start to upload the file `test.dat` this file is first uploaded to a temporary file for example `.123456789.temp` where `123456789` is something unique like a GUID and after the upload complete the file is renamed to `test.dat`, this way a client cannot download `test.dat` until the upload finish

**Comment by drakkan** [comment]
> Oh yeah of course :) By atomic upload do you mean that right now notifications will be sent before the upload is complete?

No, the upload actions are called after the file is closed, see here:

https://github.com/drakkan/sftpgo/blob/master/sftpd/transfer.go#L50

**Comment by mcdappdev** [comment]
Awesome! I’m so excited to use this in production :)
