### ISSUE TITLE
Storage S3: error running stat on path "/": failure"

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#601]
Hi, doing a test with a backend s3 something is wrong, using ftp

curl -vk -u test:test ftp://10.0.0.5:2021/

* Connected to test.lab.lan (10.0.0.5) port 2021 (#0)
> TYPE A
< 200 Type set to ASCII
> LIST
< 450 Could not list: failure
* Remembering we are in dir ""
* Connection #0 to host test.lab.lan left intact

the sftp log:

Nov  3 17:33:00 test sftpgo: {"level":"debug","time":"2021-11-03T17:33:00.635","sender":"FTP","connection_id":"FTP_0_434","message":"error running stat on path \"/\": failure"}

the s3 mapping:
![image](https://user-images.githubusercontent.com/16714986/140103384-a41a2734-f1bb-4cb5-a0e6-9c0e6595ad16.png)

what have I missing?

**Comment by drakkan** [comment]
Hi,

stat on `/` will be generate an HEAD bucket request, can your S3 account perform this request?

**Comment by fdefilippo** [comment]
Yes, is it possible to have the s3 calls written in the logs?

**Comment by drakkan** [comment]
You have to recompile SFTPGo as described [here](https://github.com/drakkan/sftpgo/issues/483#issuecomment-884381757)

**Comment by fdefilippo** [comment]
-----------------------------------------------------
2021/11/03 18:52:23 DEBUG: Request s3/HeadBucket Details:
---[ REQUEST POST-SIGN ]-----------------------------
HEAD /test HTTP/1.1
Host: 10.0.0.5:9000
User-Agent: aws-sdk-go/1.40.41 (go1.17.2; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=test/20211103/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=8415aaabe7477ca79e2b8cba16e7fc659f6bedb62dc5d29f15fe368a276258a9
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211103T175223Z

**Comment by drakkan** [comment]
so you have probably found the problem, you have no response from the s3 backend

**Comment by fdefilippo** [comment]
therefore, the request seems to start but then on the minio side I don't see it coming. using mc admin trace --call s3 local but nothing seems to arrive, I don't know what to watch anymore!

using curl or mc client everything works fine.

if you have ideas they are welcome :)

**Comment by drakkan** [comment]
I'm not sure, here is my local configuration

![Schermata del 2021-11-04 11-34-24](https://user-images.githubusercontent.com/553263/140299248-42bfcce3-1da7-4463-b841-fe56b3e530b6.png)

do you have `Use path-style addressing` checked?

**Comment by fdefilippo** [comment]
path style, the version I am using is: 2.1.2 and Use path-style addressing there is not!

**Comment by drakkan** [comment]
in 2.1.x path-style addressing is used by default if you set an endpoint

**Comment by fdefilippo** [comment]
sorry to bother you, i have tried with any client and it works with all: s3cmd, aws-cli, mc. can I do anything else in the code to figure out what's going on?

**Comment by fdefilippo** [comment]
eureka!

{"level":"warn","time":"2021-11-04T15:50:17.114","sender":"SFTP","connection_id":"SFTP_915bd3db9917a3e9709489153e4299f5fddab208_1","message":"error listing directory: RequestError: send request failed\ncaused by: Get \"https://10.0.0.5:9000/test?delimiter=%2F&list-type=2&prefix=\": x509: cannot validate certificate for 10.0.0.5 because it doesn't contain any IP SANs"}
