### ISSUE TITLE
MSSQL Support

### ISSUE THREAD

**Issue by MetUys** [drakkan/sftpgo#602]
Good day,

Would you consider offering support for Microsoft SQL server?

**Comment by drakkan** [comment]
Hi,

maybe in future, after v2.2.0, meantime you can try this fork

https://github.com/QualityBytes/sftpgo

The fork has no MSSQL specific test cases, this is a blocker to merge it

**Comment by MetUys** [comment]
Hi @drakkan ,
Maybe we can discuss offline (out of this topic) regarding sponsorship to get this option added (we would be very happy that this stays public for everyone's benefit)

**Comment by drakkan** [comment]
Hi,

as you like, you can reach me at the email address you see in each commit, nicola dot murino at gmail dot com

**Comment by drakkan** [comment]
Please re-open or contact me if you are still interested in this feature.

This won't happen without sponsorship, sorry
