### ISSUE TITLE
Custom Logfile name Variables

### ISSUE THREAD

**Issue by MetUys** [drakkan/sftpgo#604]
Hi,

Thanks for this great project.

We have a need for our logs files to use variables in the file name is this supported?
i.e. systemname_log_datestamp.log

If it is what options are available?

**Comment by drakkan** [comment]
Hi,

the default log files have these names

```
- sftpgo-2021-09-29T20-56-08.363.log
- sftpgo-2021-10-10T15-19-34.380.log
- sftpgo-2021-10-19T01-28-36.944.log
- sftpgo.log
```

where `sftpgo.log` is the current log file and the others are the archived ones, you can customize the log file name by using the `-l, --log-file-path` flag (default sftpgo.log). 

In the example above `2021-09-29T20-56-08.363` is the UTC time when the log file was rotated.

Full docs [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

**Comment by fdefilippo** [comment]
or by using rsyslog:

template(name="sftpgo" type="string" string="/var/log/sftpgo/%HOSTNAME%_log_%TIMESTAMP%.log")
if ($programname contains "sftpgo") then {
  action(type="omfile" dynaFile="sftpgo")
  stop
}

**Comment by drakkan** [comment]
@fdefilippo good trick, thanks!

P.S. I suspect @MetUys is on Windows

**Comment by MetUys** [comment]
correct, Windows

**Comment by drakkan** [comment]
> correct, Windows

does my answer above help? You can customize the log file name and each rotated log file has a datetime. Variable replacement for the log file name is not currently supported

**Comment by MetUys** [comment]
I have setup a scheduled task to send the rotatelogs command o the service. this is working well, and happy with the output of the archived log format.

It would be nice that it managed that by using the variable log, but since we already have a maintenance task for other things, adding the rotatelogs command to that is not really an issue (just something to be aware of in our deployments).

thanks for the feedback.
