### ISSUE TITLE
SSL Certificate peer Check client Side

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#605]
hello, after reporting the issue #601, thanks to drakkan's suggestions, i found the problem: sftpgo cannot validate certificate , is there any way to ignore the check? 

Thank you.

**Comment by drakkan** [comment]
Hi,

we should override the http client used in aws sdk and provide one that skip certs validation, but this way https is useless :)

I have no time to try now but I think you could create a proper certificate and import your root CA in the system trust store

**Comment by fdefilippo** [comment]
hi, obviously the CA is in the truststore the other clients are working fine. I also tried setting the SSL_CERT_FILE =/path/to/cafile environment variable but it didn't help.

**Comment by drakkan** [comment]
are the other clients working without disabling ssl verification? Please check the first link above, you are connecting using an IP address and it seems missing in the server certificate

**Comment by fdefilippo** [comment]
Yes the other clients working without disabling ssl verification.

"error listing directory: RequestError: send request failed\ncaused by: Get \"https://test.lab.lan:9000/sysc?delimiter=%2F&list-type=2&prefix=\": x509: certificate signed by unknown authority"

but if I use curl from the same host:

$ curl -s https://test.lab.lan:9000
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>16B49E31BFDBB74E</RequestId><HostId>e1b96bd9-c187-46fe-bb94-493d6998bf34</HostId></Error>

**Comment by drakkan** [comment]
No time to check now, I used this procedure in a private Go project in the past and the CA added to the truststore was recognized with no issues. Have you restarted SFTPGo after adding your CA to the truststore?

**Comment by fdefilippo** [comment]
yes of course :)

**Comment by fdefilippo** [comment]
```
--- s3fs.no-check.go    2021-11-05 17:39:59.448342275 +0100
+++ s3fs.go     2021-11-05 10:50:33.138124013 +0100
@@ -13,8 +13,6 @@
        "path/filepath"
        "strings"
        "time"
-  "net/http"
-  "crypto/tls"

        "github.com/aws/aws-sdk-go/aws"
        "github.com/aws/aws-sdk-go/aws/awserr"
@@ -74,24 +72,6 @@
        }
        awsConfig := aws.NewConfig()

-  // InsecureSkipVerify
-  tr := &http.Transport{
-                //Proxy:                 http.ProxyFromEnvironment,
-                //Dial:                  d.Dial,
-                //TLSHandshakeTimeout:   60  time.Second,
-                //ResponseHeaderTimeout: 60  time.Second,
-                //MaxIdleConns:          128,
-                //MaxIdleConnsPerHost:   1,
-                //IdleConnTimeout:       60  time.Second,
-                //ExpectContinueTimeout: 1  time.Second,
-                TLSClientConfig: &tls.Config{
-                        InsecureSkipVerify: true,
-                        //NextProtos:         []string{"h2", "http/1.1"},
-                },
-  }
-
-  awsConfig.HTTPClient = &http.Client{Transport: tr}
-
        if fs.config.Region != "" {
                awsConfig.WithRegion(fs.config.Region)
        }
```

**Comment by drakkan** [comment]
I want to avoid something like this

**Comment by fdefilippo** [comment]
Hi, can't you add an option in the future release?

**Comment by drakkan** [comment]
I just tested, it works for me, I used certstrap to create a CA

```
./certstrap-dev-14dbcb06-linux-amd64 init --common-name "Cert Auth"
./certstrap-dev-14dbcb06-linux-amd64 request-cert --domain localhost --ip 127.0.0.1 --common-name localhost
./certstrap-dev-14dbcb06-linux-amd64 sign localhost -CA "Cert Auth"
```

I copied the generated certificate and key to minio folder (renaming them):

```
ls -la /var/lib/minio/.minio/certs/
totale 20
drwx------ 3 minio minio 4096  5 nov 18.27 .
drwx------ 3 minio minio 4096 30 dic  2019 ..
drwx------ 2 minio minio 4096 30 dic  2019 CAs
-r--r----- 1 minio minio 1675  5 nov 18.28 private.key
-r--r--r-- 1 minio minio 1537  5 nov 18.28 public.crt
```

I copied the root CA to the trust store:

```
cp out/Cert_Auth.crt /etc/ca-certificates/trust-source/anchors/
update-ca-trust
```

finally I started minio and SFTPGo, I changed the minio endpoint to `https://127.0.0.1:9000` and it worked fine

![tlsminio](https://user-images.githubusercontent.com/553263/140554938-b601dcb8-4d76-41d1-89b5-9d7fe71c6ca3.png)

I tested on ArchLinux but I think it should work on any Linux distro.

`InsecureSkipVerify` should be used only for testing

**Comment by fdefilippo** [comment]
I did the exact same thing but using mkcert on rhel 7.x, all clients work except sftpgo :( I will do further investigation.

**Comment by drakkan** [comment]
I just tested on a centos 7 vm. I installed sftpgo 2.1.2 using the rpm from the release page.

Before adding my root CA I can replicate the reported error

```
nov 05 21:07:11 localhost.localdomain sftpgo[8127]: {"level":"warn","time":"2021-11-05T21:07:11.124","sender":"SFTP","connection_id":"SFTP_aa49b944d8012f990fe9bd8f44265260135f209300078552305addd54fef20b4_1","message":"error listing directory: RequestError: send request failed\ncaused by: Get \"https://127.0.0.1:9000/test?delimiter=%2F&list-type=2&prefix=\": x509: certificate signed by unknown authority"}
```

I copied my root CA in `/etc/pki/ca-trust/source/anchors`:

```
ls -la /etc/pki/ca-trust/source/anchors/Cert_Auth.crt 
-r--r--r--. 1 root root 1761  5 nov 21.05 /etc/pki/ca-trust/source/anchors/Cert_Auth.crt
```

and executed the following commands:

```
update-ca-trust
systemctl restart sftpgo.service
```

and SFTPGo works fine now

**Comment by drakkan** [comment]
Hi,

were you able to fix the issue? Did you have to do something other than the above instructions? Thanks

**Comment by fdefilippo** [comment]
No, most likely there is some problem that I cannot identify, as soon as I have time I will do a more in-depth investigation. Thank you.

**Comment by CampinCarl** [comment]
For anyone coming across this thread using Docker instead of a native install, you can achieve the same effect as `update-ca-certificates` by dropping your certificate into the container and setting the `SSL_CERT_DIR` environment variable so Go recognizes it.

I used a `config` stanza, but you could just as easily bind mount it using a volume based on your preference. I'm using Alpine (though it should be similar w/ other distributions), so I just added my private root CA to `/etc/ssl/certs` and set `SSL_CERT_DIR` to match.

Hope this helps.
