### ISSUE TITLE
Exit/terminate session before login command

### ISSUE THREAD

**Issue by MetUys** [drakkan/sftpgo#607]
Hi,

We have a very simple TCP port check service to test ports are up and responding on remote systems.
It basically checks for a response and sends the close command (whatever that maybe per service).

For FTP we are able to use the "quit" command to successfully close the session immediately after port opened and "welcome banner" is presented. so all is good on that side.

However, Im unable to do the same on the SFTP port. I have tried a myriad of commands but none are successful. The session eventually does disconnect after the timeout reaches, but the concern here is if the service is executed at a faster rater than the session timeout, then we could have a resource exhaustion issue if executed enough times.

Is there a command to close the SFTP session after the "welcome banner" but before login/auth is submitted?
I have tried: quit, exit, close, end, disconnect, ~, ~. , "ctrl-d", etc. but no luck.

**Comment by drakkan** [comment]
Hi,

I suppose you are connecting using a plain TCP so you you don't  execute the SSH handshake. You could simply close the connection on the client side once you read the SSH banner (I think this is what most checkers done) or you can send more than 255 chars, in this case the connection will be closed with an error like this:

```
ssh: overflow reading version string
```

If you are concerned about DoS or such please take a look at these docs:

https://github.com/drakkan/sftpgo/blob/main/docs/defender.md
https://github.com/drakkan/sftpgo/blob/main/docs/rate-limiting.md

P.S. allow list for the rate limiter was added after v2.1.x and currently it is only supported in the development version

**Comment by drakkan** [comment]
You should have enough info
