### ISSUE TITLE
Error when initializing with empty tables

### ISSUE THREAD

**Issue by atruskie** [drakkan/sftpgo#608]
Hi,

I'm using sftpgo in my dev environment. Sometimes my integration tests reset the state of the database by truncating all tables between tests. When this happens sftpgo will fail to start the next time it runs with:

```
{"level":"warn","time":"2021-11-09T23:54:00.701","sender":"dataprovider_postgresql","message":"Unable to initialize data provider: pq: relation \"sftpgo_schema_version\" already exists"}
{"level":"error","time":"2021-11-09T23:54:00.702","sender":"service","message":"error initializing data provider: pq: relation \"sftpgo_schema_version\" already exists"}
```

The key issue is the table exists, but because it is empty the migration version check fails.

I'm hesitant to call this a bug - it's not sftpgo's fault that something else is messing with its tables. I'm changing my code/tests so that it doesn't trigger this case.

However, I can see value in sftpgo being a little more robust about its initialization process. I've run into this problem a couple of times now (for different reasons too) and the only solution I've come up with is a script that drops all the sftpgo tables.

My first naive thought was that sftpgo could add `IF NOT EXISTS` to its schema creation statements - but that could risk invalid schemas being used. 

Alternately, a force migrate/create option could be useful (and dangerous) way to ensure sftpgo always can start.

Details:

- Provider: postgresql
- sftpgo version: SFTPGo 2.1.0-a09cf5c8-2021-06-16T15:59:31Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
- Using inside docker compose

**Comment by drakkan** [comment]
Hi,

I'm not sure how to handle this. SFTPGo uses the `schema_version` table to get the current schema version and decide if the database needs a migration to work with the running version. If you delete the `schema_version` content it tries to execute all the migrations from the beginning and it fails since the tables already exists. 

If we use `IF NOT EXISTS` we could use an invalid schema as you stated above. 

Instead of dropping all the tables you could delete all the data except the `schema_migration` table.

Maybe I could add a `resetprovider` command, documenting that it could delete all the data and asking for confirmation, something like this:

https://github.com/sftpgo/sftpgo-plugin-eventstore/blob/main/cmd/cmd.go#L128

**Comment by atruskie** [comment]
Hi, thanks for the response.

> Instead of dropping all the tables you could delete all the data except the schema_migration table.

I'm not sure how that would help.

- Automated tools truncated the tables (I didn't plan it, or intend it) 
- I had to drop the tables to get the database in a state where sftpgo would even work

> Maybe I could add a resetprovider command, 

That could be useful 😄. I had a little bit of a panic there because I thought I'd missed that command but I see it is part of a plugin 😅 .

But yeah, `resetprovider` might be useful in such cases where the database is stuck in a non-recoverable state for some reason (like this case).

---

I should note: the other time I ran into this issue was when another tool was maintaining the schema of my database. It created the tables and since they were empty sftpgo failed to initialize.

Again, not sftpgo's fault, and again I've since configured my other tool to ignore the sftpgo database. However, when I was in that case, the only option was to truncate tables. `resetprovider` would be useful in that case too.

**Comment by atruskie** [comment]
Another thought: it might be good to add a validation the schema version check. Something like:

- get schema version
    - if error
        - if table exists
            - raise error "We can't determine schema version because the schema_migration table is empty. The sftpgo database might be corrupted. Consider using the resetprovider command."

This would avoid it trying to migrate and give a clear description of the problem.
