### ISSUE TITLE
Expose OpenAPI documentation in web interface

### ISSUE THREAD

**Issue by mjpieters** [drakkan/sftpgo#609]
Could the OpenAPI.yaml file be made available to the web API, together with a OpenAPI renderer (like [Redoc](https://github.com/Redocly/redoc/))?

This would require two new endpoints:

- One serving the `schema/openapi.yaml` file
- One serving a template that pulls in the renderer

For a set of example templates, see the [Flask-Smorest template folder](https://github.com/marshmallow-code/flask-smorest/tree/16c706487de40c08cb65aaf012953502845169c1/flask_smorest/spec/templates); that project offers a choice of three different renderer projects. Personally, I favour Redoc.

The advantage would be that you can quickly get accurate and current API documentation for the installed and running SFTPGo version, in human-readable form in your browser.

**Comment by drakkan** [comment]
Hi,

I'm not sure. To render the openapi schema locally I generally copy [swaggerui files](https://github.com/swagger-api/swagger-ui/tree/master/dist) and the SFTPGo openapi definition within the `static` folder

```
nicola@p1 ~/goprojects/sftpgo/static $ ls
css  favicon.ico  js  swaggerui  vendor
```

and I connect to `http://localhost:8080/static/swaggerui/`. I'm not sure all the users want a such endpoint, and there are also many renderers available

**Comment by mjpieters** [comment]
> To render the openapi schema locally I generally copy swaggerui files and the SFTPGo openapi definition within the static folder

That's quite a hassle when using a docker container though. And, you have to know that that's how OpenAPI specs can be rendered and where to find a renderer to ad to the static folder. It's a 'batteries included' thing.

> I'm not sure all the users want a such endpoint, and there are also many renderers available.

Different users will always have different needs; we don't use the WebDAV or FTP servers yet the project offers those. :-) And because it's a template, if there is a local requirement to use a different renderer, you can swap out the template. Pick one you feel comfortable including in sftpgo. :-)

**Comment by drakkan** [comment]
I just tryed redoc, the generated documentation is very good, but it seems that if you also want to try the API you have to use a project like this:

https://github.com/wll8/redoc-try

that basically opens swaggerui inside redoc. So I think I'll include swagger ui directly. I have to make it configurable though
