### ISSUE TITLE
Unable connect WebDAV using Windows file explorer

### ISSUE THREAD

**Issue by kice** [drakkan/sftpgo#614]
I just cannot get my file explorer connect to sftpgo, and it works just fine with WinSCP. And I can connect to a WebDAV server host by IIS using file explorer.

Win file explorer just said "the folder you entered does not appear to be valid" for sftpgo WebDAV, and I am using Windows 10.

Maybe I missed some config or just sftpgo dose not support this feature?

**Comment by drakkan** [comment]
Hi,

this works fine for me, please provide more details and check the usage for the windows client:

https://docs.microsoft.com/en-us/iis/publish/using-webdav/using-the-webdav-redirector#webdav-redirector-registry-settings

for example if you don't configure the https for SFTPGo you have to set `BasicAuthLevel` to `2`. Please take a look or include the sftpgo logs if you think your client is correctly configured

**Comment by kice** [comment]
After capturing with mitmproxy, I found that sftpgo will return `HTTP 401` for `OPTIONS` requests before authorization, while IIS will return 200 with supported methods. 

File explorer dose not make any requests after the first `OPTIONS` requests was rejected by 401 (and looks like need to restart `WebClient` windows service as well, or otherwise file explorer will refuse make any more requests to the same address).

Any chance will we "adapte" to this kind of "feature"?

**Comment by kice** [comment]
@drakkan Thanks for your suggestion, but it looks like dose not work on my pc.

**Comment by drakkan** [comment]
strange, can you please share the wireshark dump or at least the version of your client? It works fine for me using `Microsoft-WebDAV-MiniRedir/10.0.19043`. I'll try to fix if I can reproduce, thanks

**Comment by kice** [comment]
Nerver mind, I just forgot to restart `WebClient` service after changing the registry.

Beside that, what if add other auth method, like `Negotiate / NTLM`?

Changing every manchine's registry is kindof painful.

Ref: https://www.ietf.org/rfc/rfc4559.txt

**Comment by drakkan** [comment]
To fix this issue you could just configure [https for SFTPGo](https://github.com/drakkan/sftpgo/blob/main/docs/howto/lets-encrypt-certificate.md), if you plan to use webdav I think you need to change the registry anyway, for example the default file size limit is only 50MB.

I'll search if there are some Go libraries available for server side NTLM but it's probably easier to implement digest authentication

**Comment by drakkan** [comment]
Negotiate / NTLM seems too Windows specific, I don't plan to work on this sorry
