### ISSUE TITLE
Defender with multiple sftpgo instances

### ISSUE THREAD

**Issue by n-h-mdla** [drakkan/sftpgo#616]
Hi Drakkan,

Wondering if it's possible to revisit defender with multiple sftpgo instances. We are evaluating running sftpgo in kubernetes and one thing we noticed is that the native defender blocks an IP address on the pod the login attempt happens on - which makes sense. 
The issue is then two fold:
- Repeated login attempts from the bad IP address could be routed to another sftpgo instance/pod - after a short while it will be banned again but this gives a bad actor n attempts to brute force logging in, where n=the number of sftpgo instances running in the environment 
- If the ban needs to be un-done, there's no way from the UI (using a load balanced HTTPproxy in k8s) to specify what pod you are dropped on, so it's a bit of Russian roulette to land on a pod where the IP is banned to un ban it. Example: IP 1.2.3.4 is banned on sftpgo-pod-1. User logs into the sftpgo admin page to un ban them, but they are logged into sftpgo-pod-2. The defender page doesn't show the banned IP, and the user will now need to log out/try again or use incognito mode to try and drop into sftpgo-pod-1 to un-ban that IP

Is it possible to have some sort of defender sync, similar to your implementation of 'is_shared' for the data_provider? 

Many thanks!

**Comment by drakkan** [comment]
Hi,

in the future I could add a defender implementation that stores data in the dataprovider so if you use a shared or distributed data provider (MySQL, PostgreSQL, CockroachDB) the defender is automatically synchronized.

Let's see if anyone wants to sponsor this feature. Thanks
