### ISSUE TITLE
External Authentication Hook discrepency in POST req

### ISSUE THREAD

**Issue by mike-k0** [drakkan/sftpgo#617]
Hi, it appears the "public_key" parameter in the external authentication hook POST request does not match up to the value of my public key in my `~/.ssh` directory. Is this intended, or am I just doing something wrong?

**Comment by drakkan** [comment]
Hi,

the public key you get in the `public_key` field is the one the client sends. I just tested adding something like this in `.ssh/config`:

```
Host 127.0.0.1 
   IdentityFile ~/.ssh/id_gitlab_gst
   User a 
   Port 2022
```

If I login using the user `a` I get the expected key in the external auth hook. Please try something like this:

```
sftp -vvv -P 2022 a@127.0.0.1
```

you shoud see the offered key, for example:

```
debug1: Offering public key: /home/nicola/.ssh/id_gitlab_gst ED25519 SHA256:cXVpBLUjQMVAoBA58OHPrcC2Q5eby+n7CZ3VQrds4iU explicit agent
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: /home/nicola/.ssh/id_gitlab_gst ED25519 SHA256:cXVpBLUjQMVAoBA58OHPrcC2Q5eby+n7CZ3VQrds4iU explicit agent
```

and in the POST request you will get the value for that key

**Comment by trippy22** [comment]
Have you tried this with an RSA key specifically?

**Comment by mike-k0** [comment]
Would you be able to try this with an RSA key?

**Comment by drakkan** [comment]
It works for me with RSA keys too:

```
$ cat /home/nicola/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHm14ajvIvOdDiofqhA4ETWSTVvhH+QER9jtgsCxlp9YcxWLRUN+jdHPe7X9totLJU2UkSUPwZ7vItKqb3PXJvp14JGeOsSbjyI+2IadFcTE1xhEy4FEW8fKy6QplFpG6tlHbxGhX8p4e3Z5j/HjeDoX3DXcoVvGt/I25LjDISPw+dCnG/BUGH5QtyBi6axOpql+7MqBCNySWfzw3Pr0YbBfsh2l8IihOankAVeVeYfIcb7+KGUZxy8qE8/BHD33qgmmEuswDCP8Z4G+XLkJ0JAVZRLxZwl8dRKLR5peDAmwKNuAReAVclzQ/ECQPu3bisy9nK3Ebaai0W9fcSDpeL nicola@t540p
```

and this is what I receive in the auth hook:

```
{"ip":"127.0.0.1","keyboard_interactive":"","password":"","protocol":"SSH","public_key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHm14ajvIvOdDiofqhA4ETWSTVvhH+QER9jtgsCxlp9YcxWLRUN+jdHPe7X9totLJU2UkSUPwZ7vItKqb3PXJvp14JGeOsSbjyI+2IadFcTE1xhEy4FEW8fKy6QplFpG6tlHbxGhX8p4e3Z5j/HjeDoX3DXcoVvGt/I25LjDISPw+dCnG/BUGH5QtyBi6axOpql+7MqBCNySWfzw3Pr0YbBfsh2l8IihOankAVeVeYfIcb7+KGUZxy8qE8/BHD33qgmmEuswDCP8Z4G+XLkJ0JAVZRLxZwl8dRKLR5peDAmwKNuAReAVclzQ/ECQPu3bisy9nK3Ebaai0W9fcSDpeL\\n","tls_cert":"", ....
```

please provide more info/logs, thank you

**Comment by mike-k0** [comment]
Is there a particular way I can debug the POST request data in the logs? I tried setting `SFTP_GO_VERBOSE = 1` in the container (this is the container with the edge tag if that matters), but I couldn't find anything.

**Comment by mike-k0** [comment]
I set up my own local webserver and forwarded requests to it, and things seemed fine. This problem might be isolated to the endpoint I'm using for the authentication hook, which is AWS API Gateway/AWS Lambda. I'm not sure why the request payload would be getting modified, though (it's only the latter half of the public key string that get modified).

**Comment by mike-k0** [comment]
More specifically, it might be something more specific to my ssh config on my OS X machine. I don't know what's causing the change of the payload, but when testing on a different machine, I couldn't replicate the problem either.

**Comment by mike-k0** [comment]
I think this was an issue on my end. I was able to find the exact keys listed in `ssh-add -L` in the payload after some further testing.

The only small discrepancy I found is that there is sometimes an extra whitespace at the end of the payload for the public key (although I guess this can just be fixed with stripping whitespace).

Also, is there a specific setting to specifically require password+publickey for multi auth? I've been playing around with that but it doesn't seem like both a pw and public key are sent in the external auth hook for me.

**Comment by drakkan** [comment]
Hi,

you have to return a user that is only allowed to authenticate multi-step auth, your hook will be invoked for each authentication step so you need to validate public key and password separately, SFTPGo will take care that the client uses the allowed sequence.  Obviously your hook must return consistent responses: if you change the denied login methods between authentication steps the behaviour will be undefined.

I added a small test case and a note to the docs.

The public key should have a `\n` at the end, just trim it if it create issues to the library you use. I think the Go library serialize the public key this way because the `\n` is required if you want to save the key to a file

**Comment by mike-k0** [comment]
Hi, @drakkan, thank you for the additional explanations!

However, I am not having any luck with setting up multi factor auth. If I return a user json with: `denied_login_methods: ["publickey", "password"]`, authentication simply doesn't work since there are multiple steps in the process.

If I don't deny any login methods, and have `external_auth_scope` set to `3`, and I return both a publickey and a password in the user response, I'm still able to log in with only just presenting a valid public key. Is there a specific way to structure a user json response to ensure both a public key and password are requested for?

**Comment by drakkan** [comment]
> Hi, @drakkan, thank you for the additional explanations!
> 
> However, I am not having any luck with setting up multi factor auth. If I return a user json with: `denied_login_methods: ["publickey", "password"]`, authentication simply doesn't work since there are multiple steps in the process.
> 

this should work, the client must authenticate using the public key first. SFTPGo sends a partial success and then it must send the password. Take a look at the test case [here](https://github.com/drakkan/sftpgo/blob/main/sftpd/sftpd_test.go#L2805).

You should see logs like the following ones:

```
{"level":"debug","time":"2021-11-25T22:04:35.898","sender":"dataprovider_sqlite","message":"external auth completed for user \"test_user_sftp\", elapsed: 9.478688ms"}
{"level":"debug","time":"2021-11-25T22:04:35.987","sender":"sftpd","connection_id":"1bd1e67a9e8bcd8c53c980d99f7450d603263d41ac1865df4b5d364cbd0fc50b","message":"user \"test_user_sftp\" authenticated with partial success"}
{"level":"debug","time":"2021-11-25T22:04:36.017","sender":"dataprovider_sqlite","message":"external auth completed for user \"test_user_sftp\", elapsed: 4.931397ms"}
{"level":"debug","time":"2021-11-25T22:04:36.103","sender":"osfs","connection_id":"1bd1e67a9e8bcd8c53c980d99f7450d603263d41ac1865df4b5d364cbd0fc50b","message":"root directory \"/tmp/test_user_sftp\" for user \"test_user_sftp\" does not exist, try to create, mkdir error: <nil>"}
{"level":"debug","time":"2021-11-25T22:04:36.103","sender":"SSH","connection_id":"1bd1e67a9e8bcd8c53c980d99f7450d603263d41ac1865df4b5d364cbd0fc50b","message":"User \"test_user_sftp\", logged in with: \"publickey+password\", from ip: \"127.0.0.1\", client version \"SSH-2.0-Go\""}
```

note the `partial success` and then the `logged in with: \"publickey+password\"`. Please be sure that your client is attempting to authenticate using public key and password in this order

> If I don't deny any login methods, and have `external_auth_scope` set to `3`, and I return both a publickey and a password in the user response, I'm still able to log in with only just presenting a valid public key. Is there a specific way to structure a user json response to ensure both a public key and password are requested for?

**Comment by mike-k0** [comment]
I was able to get it working as you described after modeling my configuration based on the test case! Thank you @drakkan!

I don't know if this is exactly possible, but is there any way to disable the external auth hook from being called if someone passes in a password first instead of the expected key? e.g `sftp -o PreferredAuthentications=password -P 2022 user@127.0.0.1`

The current behavior of course does not allow the user to proceed (even if they have the correct password - since the denied login methods prohibits them from doing so - which is good), but I was wondering if there was a way to prevent the external hook from being executed in that particular scenario (or if this is not possible since it's up to the hook to return that password authentication is not allowed)

**Comment by drakkan** [comment]
SFTPGo need to fetch the user to understand the allowed login methods and when using external auth the user is fetched by executing the external auth hook, so this is not possible sorry
