### ISSUE TITLE
ftp doesn't work in docker

### ISSUE THREAD

**Issue by helmut72** [drakkan/sftpgo#618]
relevant parts of:

docker-compose.yml

```
    ports:
      - 21:2021/tcp
      - 10000-10999:10000-10999/tcp
```

sftpgo.env

```
SFTPGO_FTPD__BINDINGS__0__ADDRESS=0.0.0.0
SFTPGO_FTPD__BINDINGS__0__PORT=2021
SFTPGO_FTPD__BINDINGS__0__TLS_MODE=0
SFTPGO_FTPD__BINDINGS__0__DEBUG=true
SFTPGO_FTPD__PASSIVE_PORT_RANGE__START=10000
SFTPGO_FTPD__PASSIVE_PORT_RANGE__END=10999
SFTPGO_FTPD__DISABLE_ACTIVE_MODE=true
```

Login is ok, but no data is transfered. I think it's something with port range. Just a common passive ftp.

**Comment by helmut72** [comment]
I forgot:
`SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=`

But what if I use 2 network interfaces?

**Comment by drakkan** [comment]
You can bind to specific network interfaces and define multiple bindings for example:

```
SFTPGO_FTPD__BINDINGS__0__ADDRESS=192.168.1.2
SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=....
....
SFTPGO_FTPD__BINDINGS__1__ADDRESS=192.168.0.2
SFTPGO_FTPD__BINDINGS__1__FORCE_PASSIVE_IP=...
```

You also have to configure appropriately docker networking. Please note that this setup is only required for clients that use the `PASV` command. `EPSV`  does not require to specify a passive IP.

Maybe I could also allow to specify a different passive ip based on the ip of the connecting client but I'm not sure this will help for your use case

**Comment by helmut72** [comment]
That's the solution, thank you!


> You can bind to specific network interfaces and define multiple bindings for example:
> 
> ```
> SFTPGO_FTPD__BINDINGS__0__ADDRESS=192.168.1.2
> SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=....
> ....
> SFTPGO_FTPD__BINDINGS__1__ADDRESS=192.168.0.2
> SFTPGO_FTPD__BINDINGS__1__FORCE_PASSIVE_IP=...
> ```

That's the solution, thank you!
