### ISSUE TITLE
Docker Container SSH Server Fingerprint/Identity

### ISSUE THREAD

**Issue by mike-k0** [drakkan/sftpgo#619]
Is there a particular place the server fingerprint / identity is stored?

I'm hosting the container in a serverless container solution for Azure, and was wondering if I could preserve the fingerprint for the ECDSA key that's presented to the client on connection (in the event the container resource is re-provisioned).

I'm guessing if this is possible it could be done with mounting a permanent volume since the disk is ephemerally created currently, but is there a specific place this information is currently stored on disk?

edit: I am assuming the argument is `host_keys`, but I was just wondering where on a docker disk they are currently stored.

**Comment by drakkan** [comment]
Hi,

sorry for the late response. I suppse you found the configuration key yourself. Some SFTPGo users uses a docker secret for this
