### ISSUE TITLE
Question: Authenticating via external script command?

### ISSUE THREAD

**Issue by SlvrEagle23** [drakkan/sftpgo#62]
Hello!

I'm trying to integrate SFTP access into an existing application which has its own user accounts and roles defined internally. Because the main application is in PHP and uses the built-in argon2i password hashing method, its passwords are hashed in a slightly different format than the one `sftpgo` expects, so I can't just point this app at the same database that the web application is using.

What I'm curious to find out is whether authentication via invoking a script is possible in the current version of this application. I see a number of built-in locations where hooks can be called to either programs or external URLs, including one in the `data_providers` section, but it doesn't appear that this hook can actually handle authentication.

Given this app already has its own internal REST API, my current plan is just to use either that REST API or a small SQLite database to sync up the web application's user accounts and the `sftpgo` accounts periodically.

Is that the current best solution for this kind of setup? Thanks in advance for your assistance, and a massive kudos to the team who built this wonderful application, as it solves a number of problems I've been having with my existing FTP implementation.

**Comment by drakkan** [comment]
Hi,

can you please share an example of a password stored in your existing database so i can understand the format? If you use argon2i instead of argon2id I think I can support checking passwords in this format too.

An external auth script could be useful too, I can add support for something similar to this:

https://download.pureftpd.org/pub/pure-ftpd/doc/README.Authentication-Modules

**Comment by SlvrEagle23** [comment]
@drakkan Yep, that's exactly what we're using right now, PureFTPD's standalone external authentication support. It's a little convoluted to have to run a separate process to do the authentication, but it allows the main app to handle authentication exactly as it needs to.

Of course, all of our users (and we) collectively can't stand using FTP itself any more, so we're hopping over to SFTP and yours is far and away the best solution we've found.

Our current hashed passwords look like:

```
$argon2i$v=19$m=65536,t=4,p=1$OU1MZUZlSjFpZ09jTksvRg$fwItGZpz2dMFIH5TytRzwcqueKxWA2YGY5S3+sRz/t4
```

which is indeed _very_ close to how it appears to be stored by the app, just using Argon2I.

We did actually just complete an update to PHP 7.4 which will allow us to use Argon2ID directly, which may yield a format that's already supported.

Rather than make sure sftpgo's DB schema lines up with my own application's, I'm currently just using a little cron task that generates a JSON backup of users from the main database and "restores" them into sftpgo, which keeps the two synced up quite nicely.

**Comment by SlvrEagle23** [comment]
Update: by switching to argon2id and manually specifying the cost parameters, I was able to yield a hashed password that identically matches how `sftpgo` stores passwords, and thus can be used directly when syncing user accounts:

This script:

```php
<?php
echo password_hash('test', \PASSWORD_ARGON2ID, [
    'memory_cost' => 65535,
    'time_cost' => 3,
    'threads' => 2,
]);
```

yields

```
$argon2id$v=19$m=65535,t=3,p=2$QTdnRVFtR05Ta1poUHExYg$boxbQPU7ILgEna8ejuTTnT82gFMfW/1iylLoOCAWBbo
```

**Comment by drakkan** [comment]
> Update: by switching to argon2id and manually specifying the cost parameters, I was able to yield a hashed password that identically matches how `sftpgo` stores passwords, and thus can be used directly when syncing user accounts:
> 
> This script:
> 
> ```
> <?php
> echo password_hash('test', \PASSWORD_ARGON2ID, [
>     'memory_cost' => 65535,
>     'time_cost' => 3,
>     'threads' => 2,
> ]);
> ```
> 
> yields
> 
> ```
> $argon2id$v=19$m=65535,t=3,p=2$QTdnRVFtR05Ta1poUHExYg$boxbQPU7ILgEna8ejuTTnT82gFMfW/1iylLoOCAWBbo
> ```

thanks for the update, I think sftpgo can check passwords with different values for m,t and p too.

Regarding the external authentication I want to add this feature too, I have to think a bit more how to manage users quota in this case

**Comment by drakkan** [comment]
External authentication is now supported, please comment here and/or open separate issues if you find problems using it or you have suggestions to improve it. Thanks!

**Comment by SlvrEagle23** [comment]
@drakkan My goodness, that's an astounding turnaround! We've already implemented sftpgo in our application, but I'll likely switch us over to this just for convenience.

**Comment by SlvrEagle23** [comment]
@drakkan Just an update, we've switched over to using the external authentication support and it works like a charm. We had to do some minor workarounds due to the fact that the sftpgo application doesn't pass the environment variables it receives down to the "child" commands (either the upload notifications or the auth command), but with our setup that's trivial to remedy.

Thank you again for your rapid turnaround, and for your work overall on this project. :)

**Comment by drakkan** [comment]
@SlvrEagle23 thanks for your feedback very appreciated!

> @drakkan Just an update, we've switched over to using the external authentication support and it works like a charm. We had to do some minor workarounds due to the fact that the sftpgo application doesn't pass the environment variables it receives down to the "child" commands (either the upload notifications or the auth command), but with our setup that's trivial to remedy.

For the external auth this is intentional, we clear any previous env vars too, this is because we are passing sensitive information (the password as clear text) and we want that these info are propagated only to the external auth program.

Regarding the upload notifications we don't set environment variables but we just pass command arguments

> 
> Thank you again for your rapid turnaround, and for your work overall on this project. :)

No problem I'm glad to improve SFTPGo
