### ISSUE TITLE
Allowed IP/Mask field 

### ISSUE THREAD

**Issue by sebPomme** [drakkan/sftpgo#621]
Hi,

We are having issues to fill long lists of IPs in the `Allowed IP/Mask` field.  
The field cannot take more than 256 chars so we currently have to edit its html value by hand or use the API.

Maybe it should be a `textarea` instead of an `input` to allow for bigger values?

Thanks in advance
:apple:

**Comment by drakkan** [comment]
Thank you for reporting, it should be fixed now

**Comment by sebPomme** [comment]
Fixed !

:apple:
