### ISSUE TITLE
Compile sftpgo for Windows arm64

### ISSUE THREAD

**Issue by mirogl** [drakkan/sftpgo#624]
Hi
I´m trying to compile the sources for Windows arm64.

I use:

`go version
go version go1.17.2 windows/arm64

aarch64-w64-mingw32-gcc.exe --version
clang version 13.0.0 (https://github.com/llvm/llvm-project.git d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
Target: aarch64-w64-windows-gnu
Thread model: posix
InstalledDir: C:\Program Files\llvm-mingw\bin

C:\Users\miros\Downloads\sftpgo-2.2.0>aarch64-w64-mingw32-g++.exe --version
clang version 13.0.0 (https://github.com/llvm/llvm-project.git d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
Target: aarch64-w64-windows-gnu
Thread model: posix
InstalledDir: C:\Program Files\llvm-mingw\bi
`

The compile works with the flag:

`go build -tags nosqlite`

but then i can´t start  the application, since SQLite is disabled

`sftpgo.exe serve
2021-11-27T16:19:48.084 ERR error initializing data provider: SQLite disabled at build time`

If i try to  build with sqllite with the following env settings:

```
set CC=aarch64-w64-mingw32-gcc.exe
set CXX=aarch64-w64-mingw32uwp-g++.exe
set CGO_ENABLED=1
set GOOS=windows
set GOARCH=arm64
go build -v
```

i get the following error:

```
runtime/cgo
github.com/mattn/go-sqlite3
# github.com/drakkan/sftpgo/v2
.debug_frame+1MB: addpesym: could not map .debug_frame+1MB symbol with non .text or .rdata or .data section
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a38c9
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.ValueOf$abstract
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a38dc
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.ValueOf$abstract
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a38e5
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.escapes$abstract
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a38f8
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.escapes$abstract
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a3901
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.unpackEface$abstract
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a3918
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.unpackEface$abstract
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a3929
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.unpackEface$abstract
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a3932
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.unpackEface$abstract
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a35ff
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.(*rtype).Kind$abstract
sym 181547: invalid relocation: R_DWARFSECREF .debug_info+0x2a3618
sym 181547: unsupported obj reloc R_DWARFSECREF/4 to go.info.reflect.(*rtype).Kind$abstract
C:\Program Files\Go\pkg\tool\windows_arm64\link.exe: too many errors
```

Any hints or do I need to open a issue at github.com/mattn/go-sqlite3 ? I think it would help to have the build instructions for sftpgo on Windows arm64 in your repo.

Thanks
Miro

**Comment by drakkan** [comment]
Hi,

your compile commands look correct but I have no way to test on Windows arm64.

If you want to run SFTPGo on Windows ARM64 you can just compile it with CGO disabled and then use the bolt provider instead of SQLite.

**Comment by mirogl** [comment]
Hi @drakkan,
many thanks - I switched to the bolt provider now and it works. So will close the issue.
Have a nice day.
Miro

**Comment by drakkan** [comment]
It would be still useful to provide SFTPGo for Windows ARM64 but I have currently no way to test it. 

A quick solution would be to build it with CGO disabled and switch to use bolt as default data provider, this is what I did for the distroless docker image (there is a similar sqlite issue there). I'll evaluate this workaround in the future.

**Comment by mirogl** [comment]
Hi @drakkan 
If you have a Raspberry Pi - then you could test it there - but it is quite slow - https://worproject.ml/ ;-)
Yes, this options sounds great - build with CGO disabled and bolt as default provider.
If i can test anything for you, then dont hesitate to contact me, i have a Surface Pro X and a Samung Galaxy Book S - but both have already Windows 11 installed - so I don´t have a Windows 10 system anymore for testing.

Thanks
Miro

**Comment by drakkan** [comment]
Hi,

can you please download and test the installer [here](https://github.com/drakkan/sftpgo/actions/runs/1513219896)? Thanks

**Comment by mirogl** [comment]
Hi @drakkan,
thanks - i could install it on my windows arm64 and got the following files under:

```
C:\Program Files\SFTPGo
28.11.2021  20:17    <DIR>          .
28.11.2021  20:17    <DIR>          ..
28.11.2021  18:18            35.182 LICENSE.txt
28.11.2021  18:47        34.177.864 sftpgo.exe
28.11.2021  20:17            26.133 unins000.dat
28.11.2021  20:16         3.149.128 unins000.exe
28.11.2021  20:17            24.097 unins000.msg
```

when i try to init the provider i get

`>sftpgo.exe initprovider
2021-11-28T20:17:57.000 INF Initializing provider: "sqlite" config file: ""
2021-11-28T20:17:57.000 WRN Unable to initialize/update the data provider: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub`

With the github version i had a sftpgo.json file - this is missing in this installation. Is this normal ? Because in my github version i changed in  sftpgo.json file 

```
 "data_provider": {
    "driver": "bolt",
    "name": "bolt.db",
    "host": "",
```

When i copy my sftpgo.json file to the new instalaltion i get 

```
C:\Program Files\SFTPGo>sftpgo.exe initprovider
2021-11-28T20:23:55.000 INF Initializing provider: "bolt" config file: "C:\\Program Files\\SFTPGo\\sftpgo.json"
2021-11-28T20:23:55.000 INF Data provider successfully initialized/updated

C:\Program Files\SFTPGo>sftpgo.exe serve
2021-11-28T20:24:01.024 INF No host keys configured and "id_rsa" does not exist; try to create a new host key
2021-11-28T20:24:01.025 ERR error loading required template: open templates\webadmin\base.html: Das System kann den angegebenen Pfad nicht finden.
panic: open templates\webadmin\base.html: Das System kann den angegebenen Pfad nicht finden.

goroutine 132 [running]:
github.com/drakkan/sftpgo/v2/util.LoadTemplate(0x0, {0x4000261158, 0x2, 0x2})
        github.com/drakkan/sftpgo/v2/util/util.go:377 +0x19c
github.com/drakkan/sftpgo/v2/httpd.loadAdminTemplates({0x40004ffdd6, 0x9})
        github.com/drakkan/sftpgo/v2/httpd/webadmin.go:311 +0x1664
github.com/drakkan/sftpgo/v2/httpd.(*Conf).Initialize(0x40002cea00, {0x7ff7eb5faf52, 0x1})
        github.com/drakkan/sftpgo/v2/httpd/httpd.go:443 +0x2f4
github.com/drakkan/sftpgo/v2/service.(*Service).startServices.func2(0x40002cea00, 0x40004b8000)
        github.com/drakkan/sftpgo/v2/service/service.go:185 +0x3c
created by github.com/drakkan/sftpgo/v2/service.(*Service).startServices
        github.com/drakkan/sftpgo/v2/service/service.go:184 +0x35c

```

it seems some more files are missing.

Thanks
Miro

**Comment by mirogl** [comment]
additional info - the Installer is still win32 - the installed sftpgo binary is windows arm64 - great - thanks.

```
file sftpgo_windows_arm64.exe
sftpgo_windows_arm64.exe: PE32 executable (GUI) Intel 80386, for MS Windows

file sftpgo.exe
sftpgo.exe: PE32+ executable (console) Aarch64 (stripped to external PDB), for MS Windows

```

**Comment by drakkan** [comment]
Hi,

you don't need to init the provider yourself. SFTPGo should be installed as windows service and it should be already running, can you please confirm?

The configuration file and the database should be installed in `C:\ProgramData\SFTPGo`

**Comment by mirogl** [comment]
Hi,

ok - without init i get:

```
C:\Program Files\SFTPGo>sftpgo.exe serve
2021-11-28T21:04:38.078 INF No host keys configured and "id_rsa" does not exist; try to create a new host key
2021-11-28T21:04:38.080 ERR could not start telemetry server: listen tcp 127.0.0.1:10000: bind: Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden.
```

The port is already in use due to netstat -na

`  TCP    127.0.0.1:10000        0.0.0.0:0              ABHÖREN`

When I change the port and saved
C:\Program Files\SFTPGo\sftpgo.json to

` "telemetry": {
    "bind_port": 10001,
    "bind_address": "127.0.0.1",
    "enable_profiler": false,
    "auth_user_file": "",
    "certificate_file": "",
    "certificate_key_file": "",
    "tls_cipher_suites": []
  },`

but then i get

```
C:\Program Files\SFTPGo>sftpgo.exe serve
2021-11-28T21:08:22.095 INF No host keys configured and "id_rsa" does not exist; try to create a new host key
2021-11-28T21:08:23.015 ERR unable to bind on tcp4 address: listen tcp4 :8080: bind: Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.
```

Strange is, with self compiled the version from Github there was no problem with 8080 - i tested the gui.

Thanks
Miro

**Comment by drakkan** [comment]
please try:

```
sftpgo.exe service status
```

as admin

**Comment by mirogl** [comment]
i execute everything in an admin cmd session - also the commands before.

so this gives me 

```
C:\Program Files\SFTPGo>sftpgo.exe service status
Service status: "running"
```

**Comment by drakkan** [comment]
> i execute everything in an admin cmd session - also the commands before.
> 
> so this gives me
> 
> ```
> C:\Program Files\SFTPGo>sftpgo.exe service status
> Service status: "running"
> ```

good, so the service is running as expected. Just connect to "http://127.0.0.1:8080/web/admin" to create the first user. You should also have some menu entries

**Comment by mirogl** [comment]
ok - thanks - yes works. So the error "ERR unable to bind on tcp4 address: listen tcp4 :8080:" can be ignored.
The telemetry port 10000 - is this normal, that is is already used ?

**Comment by drakkan** [comment]
> ok - thanks - yes works. So the error "ERR unable to bind on tcp4 address: listen tcp4 :8080:" can be ignored. The telemetry port 10000 - is this normal, that is is already used ?

You have these errors because sftpgo is already running and so it listens on these ports.

If you want to start/stop sftpgo yourself you can use the portable version or until I'll tag v2.1.1 the build artifact. The windows installer installs SFTPGo as service and automatically starts it, no need for manual steps

**Comment by drakkan** [comment]
Thanks for your tests!

**Comment by mirogl** [comment]
ok - great - Many many thanks for your implementation. Never had it running as a service - so did´t know it.
Miro

**Comment by drakkan** [comment]
You can use the build artificat for now and the portable version, when I'll tag v2.1.1, if you want to manually start/stop SFTPGo. The windows installer tries to make the things simple and does not require manual steps
