### ISSUE TITLE
Upgrade 2.1.0 to 2.2.0 not logging connections.

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#626]
Although i can login, and use the webclient like normal, it seems the logging has gone:

```{"level":"info","time":"2021-11-29T05:28:33.657","sender":"service","message":"starting SFTPGo 2.2.0-b6bcf0cd-2021-11-27T10:55:29Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: /sftp/enactor/sftpgo/config, config file: , log max size: 10 log max backups: 5 log max age: 28 log verbose: false, log compress: false, log utc time: false, load data from: \"/etc/sftpgo/users.json\""}
{"level":"info","time":"2021-11-29T05:28:33.672","sender":"service","message":"data loaded from file \"/etc/sftpgo/users.json\" mode: 0, quota scan 0"}
{"level":"info","time":"2021-11-29T05:28:33.673","sender":"sftpd","message":"Loading private host key \"/etc/sftpgo/id_rsa\""}
...
{"level":"info","time":"2021-11-29T05:28:33.673","sender":"sftpd","message":"Loading private host key \"/etc/sftpgo/id_ed25519\""}
...
{"level":"info","time":"2021-11-29T05:28:33.676","sender":"sftpd","message":"server listener registered, address: 0.0.0.0:2022"}
{"level":"info","time":"2021-11-29T05:28:33.710","sender":"telemetry","message":"server listener registered, address: 0.0.0.0:10000 TLS enabled: false"}
{"level":"info","time":"2021-11-29T05:28:33.711","sender":"httpd","message":"server listener registered, address: 0.0.0.0:8080 TLS enabled: false"}
```

I do have verbose logging off, but on version 2.1.0 the sftpd connections were shown with this value set to false.

**Comment by ryjogo** [comment]
I can see before we had:
```
{"level":"info","time":"2021-11-28T20:57:00.548","sender":"SSH","connection_id":"3bb6628a0f05e954e059ac85e2c2ef50dc744f599d1d54e939a51bd52323b9b8","message":"User id: 6, logged in with: \"password\", username: \"xxxxxx\", home_dir: \"/sftp/\" remote addr: \"xxxxxx\""}
```
but these messages seem to have gone.

**Comment by drakkan** [comment]
Hi,

that log was demoted to [debug](https://github.com/drakkan/sftpgo/blob/main/sftpd/server.go#L409), if you have many login/logout it will fill your logs, do you find it useful even with log verbose disabled?

**Comment by ryjogo** [comment]
Ah i see.. Yeah it was actually very useful, although verbose is a little too much. Our health checks for the sftpgo service from our loadbalancers are causing a lot of noise in the verbose logs.

**Comment by ryjogo** [comment]
@drakkan  Oh, maybe i misunderstood the question? It's not that useful without the connection messages.

**Comment by ryjogo** [comment]
Have we a bit more control over the log level? i.e. WARN/INFO/DEBUG/TRACE etc?

**Comment by drakkan** [comment]
I changed back the connections log to the info level in the linked commit. You will find this change in the new edge versions as soon as CI ends and in v2.2.1 when I'll tag it

**Comment by drakkan** [comment]
> Have we a bit more control over the log level? i.e. WARN/INFO/DEBUG/TRACE etc?

This will not help in this case. I demoted a log to debug and you don't want the other debug logs. It is quite subjective, for me is good to log users connection at info level
