### ISSUE TITLE
"Spam-like" connections

### ISSUE THREAD

**Issue by mike-k0** [drakkan/sftpgo#628]
Hi, I seem to have found a similar issue describing the issue I am currently facing: #366 

The workload I am testing is running on ACI (Azure Container Instance). I am using the container tagged with the version: `v2.1.2`

I currently have all of the following disabled entirely: `httpd, ftpd, webdavd, telemetry, smtp`. I am not using any plugins. The data provider used is the default in-memory one (SQLite). 

The only service I have running is sftpd. I have tried changed the default port for sftpd and regenerated the container a few times (to see if perhaps some sort of bots were spam connecting).

I was simply wanting to clarify that this isn't due to some setting in sftpgo - and is more likely to be some sort of internal checking / heartbeat system in Azure (at which point I will engage with them).

The debug messages I am seeing look like the following below - 

I see an upwards of about 10-30 messages like this per minute. There is usually no username in the payload in all of these requests.

```
{"level":"debug","time":"2021-11-29T19:17:39.106","sender":"connection_failed","client_ip":"10.240.255.56","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"read tcp 10.244.3.5:2022->10.240.255.56:62964: read: connection reset by peer"}
{"level":"debug","time":"2021-11-29T19:17:40.551","sender":"sftpd","message":"failed to accept an incoming connection: read tcp 10.244.3.5:2022->10.240.255.55:52189: read: connection reset by peer"}
{"level":"debug","time":"2021-11-29T19:17:40.551","sender":"connection_failed","client_ip":"10.240.255.55","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"read tcp 10.244.3.5:2022->10.240.255.55:52189: read: connection reset by peer"}
{"level":"debug","time":"2021-11-29T19:17:45.124","sender":"sftpd","message":"failed to accept an incoming connection: read tcp 10.244.3.5:2022->10.240.255.56:63098: read: connection reset by peer"}
{"level":"debug","time":"2021-11-29T19:17:45.124","sender":"connection_failed","client_ip":"10.240.255.56","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"read tcp 10.244.3.5:2022->10.240.255.56:63098: read: connection reset by peer"}
{"level":"debug","time":"2021-11-29T19:17:45.893","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
{"level":"debug","time":"2021-11-29T19:17:45.893","sender":"connection_failed","client_ip":"10.240.255.56","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}
{"level":"debug","time":"2021-11-29T19:17:45.898","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
{"level":"debug","time":"2021-11-29T19:17:45.898","sender":"connection_failed","client_ip":"10.240.255.56","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}
```

**Comment by drakkan** [comment]
Hi,

if you enable the defender these IP will be blocked but it is probably better to understand with Azure if this heartbeat is a vital service

**Comment by mike-k0** [comment]
@drakkan - this might not be something part of Azure Container Instances, but perhaps something with Kubernetes. I tried deploying the container as a pod in AKS, and I am seeing the same spam connections from internal IPs on K8s. 

I'm not sure if you have a similar small sized AKS cluster to test with, but from first glance it appears like this behavior might be something internal to Kubernetes and it is being picked up in debug logs.

**Comment by drakkan** [comment]
I see something similar if I test SFTPGo behind HAProxy. These alive checks are inoffensive, just ignore the logs or disable verbose logging if you don't want to see them
