### ISSUE TITLE
Sharing files without zipping

### ISSUE THREAD

**Issue by soda-pop-ice-cream** [drakkan/sftpgo#629]
Hi there!
Is there a way to share(single) files without archivation or implement such feature?
I mean, if you sharing some type of file that already compressed(or some huge file lile 5-10GB, zipping them one more time sounds like wasting of time and IO resources.
Mockup screenshot how i see that feature added:
![screenshot](https://user-images.githubusercontent.com/80998901/143982038-a85cead8-0d7e-4a8d-83ee-f8c17b8ae6d4.png)
:

**Comment by drakkan** [comment]
This is a good suggestion, thank you.

You can test this feature by downloading a build artifact from [here](https://github.com/drakkan/sftpgo/actions/runs/1522579389) or using an edge docker variant. A feedback is appreciated, thanks

**Comment by soda-pop-ice-cream** [comment]
Thank you! This build works works just flawlessly!
