### ISSUE TITLE
What happens if you delete a file outside of sftpgo when using object storage?

### ISSUE THREAD

**Issue by the-maldridge** [drakkan/sftpgo#631]
Title says it all.  When mapping an object store via the S3 API option for the VFS, what happens if you delete files in S3 without using sftpgo?  Does this corrupt referential integrity in the database in some way, and if so how does one recover from this?

**Comment by drakkan** [comment]
Hi,

SFTPGo does not store file references in the database. It only stores the number of files and their size (if quota tracking is enabled). If you add/delete files with external tools the SFTPGo quota checks will not be accurate. You can manually start a quota scan from the admin UI or update the quota periodically using a script like [this one](https://github.com/drakkan/sftpgo/tree/main/examples/quotascan).

**Comment by the-maldridge** [comment]
I see.  So as long as I'm not using quotas, or at least as long as they don't need to be super accurate w.r.t. deletes, it sounds like I should be fine. Thanks for taking the time to answer my question!
