### ISSUE TITLE
concurrent testing log print error no such file or directory 

### ISSUE THREAD

**Issue by sxj1991** [drakkan/sftpgo#634]
I use sftpgo-version 2.0.4 , I concurrent testing number 1000，I get message,i see the part of is success ，the ohther part of is error.
![image](https://user-images.githubusercontent.com/51181987/144366096-e7689097-f80a-46fd-b9cd-309bc2c4dc8e.png)
if you know why please tell me thanks

**Comment by drakkan** [comment]
This report seems similar to this [one](https://github.com/drakkan/sftpgo/issues/479).

Not related to this issue but please note that 2.0.4 is not supported anymore. Only the latest stable branch (currently 2.2.x) and the development version are supported

**Comment by sxj1991** [comment]
> This report seems similar to this [one](https://github.com/drakkan/sftpgo/issues/479).
> 
> Not related to this issue but please note that 2.0.4 is not supported anymore. Only the latest stable branch (currently 2.2.x) and the development version are supported

Thank you for your help.This time things are different， I from the log file get a message.
Although I get an error message， upload is a success. it's work.
![image](https://user-images.githubusercontent.com/51181987/144623533-a93584d6-5254-4487-84f3-6cac7208629b.png)
![image](https://user-images.githubusercontent.com/51181987/144623496-d5632d5b-ed1c-4966-bff8-94ee38114917.png)
![image](https://user-images.githubusercontent.com/51181987/144623449-74a59ebb-2c28-451a-a5be-0c5f36d7af0a.png)

**Comment by drakkan** [comment]
I'm not able to help only from a screenshot, try to provide some reproducible steps and please update to a more recent version
