### ISSUE TITLE
Caching logic ambiguity

### ISSUE THREAD

**Issue by danjamesmay** [drakkan/sftpgo#635]
Hi drakkan,

We have been using the new `is_shared` option (implemented in [this commit](https://github.com/drakkan/sftpgo/commit/bcf088f586a7b8fb85d8dc1445c7289be1e22f8c) and documented [here in v2.2.0](https://github.com/drakkan/sftpgo/blame/v2.2.0/docs/full-configuration.md#L216), but we are not sure the documentation describes the caching logic accurately.

We created a fresh mysql database and sftpgo running with 2 hosts under a load balancer and run an automated test to:
- create a new user (calling admin API)
- logs in as this new user using key created above (calling the load balancer)
- uploads a test file

What we observed from the logs:
- user created on host A (via admin API)
- logged in on host B immediately (via load balancer) and successfully uploaded a file

We also observed a "start caches check", which runs every minute.

The confusion is that we were not expecting to be able to log in as our newly created user immediately, we thought we would have to wait for the other host to pick up the user from the DB. We are pleasantly surprised by this behaviour though as it means we have access to all users across hosts as soon as they are created. I was just wondering if this behaviour is as expected, and this functionality will remain in later versions?

The documentation mentions the cache is updated in 10m intervals. This looks like it should be 1m.

**Comment by drakkan** [comment]
Hi,

users can always login immediately, SFTPGo uses caches for webdav users and for passwords (if `password_caching` is `true`).

So if you change a password (for any user) or the home directory for a webdav user on host A and the user has already logged in on host B and so it has been cached, then the new password  and/or the new home directory will only be used, on host B, after the cache is updated.

As for the update interval you are right, currently the check is done every minute, but it is probably too frequent, I don't think users are continuously updated. I believe that doing this check every 10 minutes, as documented, is a better choice

**Comment by AntonyKing7D** [comment]
Does the `password_caching` setting affect public keys as well ?

**Comment by drakkan** [comment]
> Does the `password_caching` setting affect public keys as well ?

only passwords. Checking passwords is quite expansive:

- bcrypt is cpu intensive
- argon2id is both cpu and memory intensive

if you have a lot of simultaneous logins, checking passwords without caching them will lead to high loads

**Comment by drakkan** [comment]
Please reopen if you have other questions
