### ISSUE TITLE
Can not start the sftpgo service on my pc.

### ISSUE THREAD

**Issue by JerryLiew** [drakkan/sftpgo#636]
I  dowanloaded the binary file,and install it totally in defalut options. after everything is installed,i run the "Service Control" in the start menu, the i use command "sftpgo service start",i got "Service started!",but the windows service is always stopped.if i start the service manual in the service manager , it prompts "windows can not start the SFTPGO service ,error 1067 :the process terminated unexpectedly".
All i did was just install it. What might be the reason for this? thanks a lot.
![image](https://user-images.githubusercontent.com/51161678/144439025-67babbf5-11c0-4a8f-b852-cae254f09851.png)

**Comment by drakkan** [comment]
Please check the logs `C:\ProgramData\SFTPGo\logs\sftpgo.log`. 

SFTPGo uses TCP port 8080 for HTTP service, TCP port 10000 for telemetry and TCP port 2022 for SFTP service by default, make sure the configured ports are not used by other services or edit the configuration according to your needs. The configuration file is `C:\ProgramData\SFTPGo\logs\sftpgo.json`.

**Comment by JerryLiew** [comment]
Great!! It started successfully.Under your guidance,i found a software which is using the port 10000.i have changed the SFTPGo's 
  port configuration.thank you again.

**Comment by drakkan** [comment]
No problem, the setup for v2.2.1 will show a README at the end explaining this.
