### ISSUE TITLE
Official Plugins (docker)

### ISSUE THREAD

**Issue by mike-k0** [drakkan/sftpgo#637]
Are any docker containers built already with some of the "official" plugins included (for example, the KMS plugin). If not I am assuming you recommend we would have to rebuild the container with the binaries for the plugins we'd like to enable?

**Comment by drakkan** [comment]
Hi,

you can also mount a volume and make the plugin available this way. Creating an image with all supported plugins will greatly increase its size. I'm sure someone would complain :)
