### ISSUE TITLE
Feature request: Keyboard interactive auth

### ISSUE THREAD

**Issue by 4O4** [drakkan/sftpgo#64]
Hi, first of all I'd like to thank you for this amazing project. I was looking for such a simple and hackable sftp server for a very long time. Great work!

Are you interested in implementing Keyboard Interactive Authentication? It could be used to perform multi factor authentication. I think it's necessary to allow to specify custom executables in this case in order to do dynamic questions / answers handling (similar to how external auth program works now).

**Comment by drakkan** [comment]
> Hi, first of all I'd like to thank you for this amazing project. I was looking for such a simple and hackable sftp server for a very long time. Great work!

Thanks!
 
> Are you interested in implementing Keyboard Interactive Authentication? It could be used to perform multi factor authentication.

Yes, it could be a useful addition. Honestly I never used it, I have to better understand how it works first

> I think it's necessary to allow to specify custom executables in this case in order to do dynamic questions / answers handling (similar to how external auth program works now).

**Comment by 4O4** [comment]
Great! I'll see if I can implement it myself to some degree and perhaps I'll send you a PR with an initial implementation if I come up with anything usable :)

**Comment by drakkan** [comment]
A PR would be great, otherwise some sample configurations for openssh and/or other open source servers (I want to test and read other source code and implementations) could be enough, thanks!

**Comment by 4O4** [comment]
Sounds good :) Let me just mention one gotcha in case you missed it - keyboard interactive auth doesn't specifically need to ask for user's password. 
It's correct to assume that most of the times you want this behavior for multi-factor auth (password challenge first, then other challenges) but it should also be possible to authenticate using only these other non-password challenges without asking for password. It would be wise to eventually support both cases :)

It's also worth noting that most SFTP GUI clients handle the standard keyboard-interactive MFA scenario rather well (by standard scenario I mean password challenge first, then other challenges), but they rely on some implementation details. 
When user has his password stored / pre-entered somewhere in the server connection settings in his client, this password will be sent automatically as a response to first challenge from the server, but only if this challenge looks like a password challenge. IIRC clients do this by checking if the prompt of the first challenge is something like "Password for user@host:" (or some part of that string, or a pattern, I'm not sure). As a result you can have your password saved and don't need to reenter it every time you connect to the server. Only the responses to the next challenges are needed in this case. Would be nice

**Comment by drakkan** [comment]
> Sounds good :) Let me just mention one gotcha in case you missed it - keyboard interactive auth doesn't specifically need to ask for user's password.

questions and answers validation is delegated to the external program. If you want to ask for the password you have to ask it inside your external program and you can check the user answer against the hashed password available as env var

> It's correct to assume that most of the times you want this behavior for multi-factor auth (password challenge first, then other challenges) but it should also be possible to authenticate using only these other non-password challenges without asking for password. It would be wise to eventually support both cases :)
> 
> It's also worth noting that most SFTP GUI clients handle the standard keyboard-interactive MFA scenario rather well (by standard scenario I mean password challenge first, then other challenges), but they rely on some implementation details.

I tested my work in progress implementation against filezilla and sftp CLI command and both seems to work fine, anyway open new issues once I merge this change if you think something can be improved, thanks!

> When user has his password stored / pre-entered somewhere in the server connection settings in his client, this password will be sent automatically as a response to first challenge from the server, but only if this challenge looks like a password challenge. IIRC clients do this by checking if the prompt of the first challenge is something like "Password for user@host:" (or some part of that string, or a pattern, I'm not sure). As a result you can have your password saved and don't need to reenter it every time you connect to the server. Only the responses to the next challenges are needed in this case.

**Comment by jovandeginste** [comment]
Out of curiosity, does this also support out-of-band MFA? We (@work) have an MFA system which will push a notification to an app on our smartphone, to verify that we actually did try to login (for web based applications). I was wondering if this would be usable here too. In other words, the challenges is not going through sftpgo to the sftp client, but through the internet to the client's smartphone.

**Comment by drakkan** [comment]
@jovandeginste 

The external program receive the username as env var, it generate and send a pin code to the client's smartphone and ask for this code using a question. 

The user answer to the question with the received code, your external program will receive the code (the answer to the question) on its standard input and so it allows or denies login based on the received code.

So it should work but you have to wrote the external program to generate and validate the pin.

**Comment by jovandeginste** [comment]
In the workflow I described, the pin code is not entered through the SFTP client, but directly on the smartphone. Basically, the user clicks the "yes it's me" button on the smartphone app (after unlocking that app), the app sends a "okay" back to the MFA service, which sends the "okay" to the sftpgo external program.

**Comment by drakkan** [comment]
@jovandeginste this should be tested the current implementation was not written with this use case in mind. 

This goroutine will wait for the client response:

https://github.com/drakkan/sftpgo/blob/master/dataprovider/dataprovider.go#L814

anyway if your external program write `{"auth_result":1}` after it receive the "yes it's me" confirmation and exits then SFTPGo should read the `auth_result` here:

https://github.com/drakkan/sftpgo/blob/master/dataprovider/dataprovider.go#L797

and authenticate the user. 

The goroutine will probably hang for ever (or maybe will be closed in golang ssh implementation when the connection ends). I can try to fix this if useful for your use case.

**Comment by 4O4** [comment]
> In the workflow I described, the pin code is not entered through the SFTP client, but directly on the smartphone. Basically, the user clicks the "yes it's me" button on the smartphone app (after unlocking that app), the app sends a "okay" back to the MFA service, which sends the "okay" to the sftpgo external program.

This doesn't fit the kbd-interactive use case because... well, there is no interaction with keyboard :) It's doable however, If I understood you correctly you only need external auth program in this case. In your program you check user's credentials first, then notify your MFA service and then start polling for status on this auth request (has "yes" been pressed already? if not then wait a bit more, repeat)

**Comment by 4O4** [comment]
@drakkan thanks for implementing this already! I was trying to do it by myself but you are way quicker than I am :) I'm going to test it this afternoon or tomorrow but at first glance it looks very promisnig

**Comment by drakkan** [comment]
> > In the workflow I described, the pin code is not entered through the SFTP client, but directly on the smartphone. Basically, the user clicks the "yes it's me" button on the smartphone app (after unlocking that app), the app sends a "okay" back to the MFA service, which sends the "okay" to the sftpgo external program.
> 
> This doesn't fit the kbd-interactive use case because... well, there is no interaction with keyboard :) It's doable however, If I understood you correctly you only need external auth program in this case. In your program you check user's credentials first, then notify your MFA service and then start polling for status on this auth request (has "yes" been pressed already? if not then wait a bit more, repeat)

yes this is not included in RFC 4256 (https://tools.ietf.org/html/rfc4256) anyway if we can support it with little effort and without breaking the standard case I'll accept a pull request or fix the current implementation myself if someone provide a test program

**Comment by drakkan** [comment]
> @drakkan thanks for implementing this already! I was trying to do it by myself but you are way quicker than I am :) I'm going to test it this afternoon or tomorrow but at first glance it looks very promisnig

Good! Please let me know if you find issues.I only tested using the sample program included in the docs and the even simplest one used for test cases

**Comment by jovandeginste** [comment]
My use case is not yet pertinent, I was just wondering. I will however start a project here at work with a central role for sftpgo, with users authenticating to it. I may need to investigate this avenue if our security folks ask me to. And you already did (part of) the work, which is awesome!

**Comment by drakkan** [comment]
@jovandeginste for the use case you describe the external auth seems a better choice:

- you let SFTPGo starts the external auth program
- the external auth program generate the pin
- when the client send the "ok is me" response the external auth program authenticate the user

maybe we only need to increase the external auth timeout that currently is 15 seconds

**Comment by jovandeginste** [comment]
Got it, thanks! Maybe make the timeout a configurable value.
