### ISSUE TITLE
Transfer errors logged as warnings

### ISSUE THREAD

**Issue by danjamesmay** [drakkan/sftpgo#649]
Hi drakkan,

I was looking to visualise transfer errors (or other errors related to sftp uploads) emitted from the sftpgo service. However, I've noticed some of these errors are actually emitted as warnings.

For example:
```
{
message | connection closed with error: unexpected EOF
connection_id | SFTP_fa38afae4aa00491faac3eb15520790d1343354ea0c0ebee6f46fc225fc2b0a1_1
level | warn
sender | SFTP
time | 2021-12-15T16:15:13.424
}
```

This seems to happen with all variations of messages (another example: `Unexpected error for transfer, path: "testuser/testfile.flac", error: "unexpected EOF" bytes sent: 0, bytes received: 17343200 transfer running since 350 ms`

Errors from `sender | dataprovider...` also come through as warnings.

I can probably just visualise warnings as errors on my dashboard, but it would be great to have these come through as errors in the log schema. Thanks!

**Comment by drakkan** [comment]
Hi,

I'll try to give a look the next week, however the whole package rarely logs at error level, warnings are basically errors.

Are you aware of the eventstore/search plugins? 

https://github.com/sftpgo/sftpgo-plugin-eventstore
https://github.com/sftpgo/sftpgo-plugin-eventsearch

They can save the events directly to your database and you can search them via REST API

https://sftpgo.stoplight.io/docs/sftpgo/b3A6MjUzNDc0Nzg-get-filesystem-events

so you don't need to parse the log files.

**Comment by drakkan** [comment]
Hi,

it should be better now. I used warning as errors in many places, thanks for spotting this.

Sometime the log level to use it is really subjective and perhaps other changes may be needed
