### ISSUE TITLE
Support for Logging to stdout/stderr

### ISSUE THREAD

**Issue by SlvrEagle23** [drakkan/sftpgo#65]
Hello!

We're using SFTPGo in a Docker environment, and while the flatfile logging option isn't particularly difficult for us to work around (using other tools like Dockerize), it's always much easier if we can just pass output directly to stdout/stderr, where the Docker stack can manage it according to its own log rotation rules.

Would this be rather straightforward to support in the app?

**Comment by drakkan** [comment]
Hi,

this feature is already supported, you can simply start sftpgo passing an empty log file, for example:

```
sftpgo serve -l ""
```

or setting the env var `SFTPGO_LOG_FILE_PATH`.

For docker the sample alpine Dockerfile already logs to stdout, for the debian based one you change the env var here https://github.com/drakkan/sftpgo/blob/master/docker/sftpgo/debian/Dockerfile#L62 to:

```
ENV SFTPGO_LOG_FILE_PATH=""
```

or simply use the docker `-e` flag to override that env var, for example:

```
docker run <options> -e SFTPGO_LOG_FILE_PATH= <other options>
```

**Comment by SlvrEagle23** [comment]
@drakkan Ah, so it does! Works like a charm. Thank you :)

**Comment by drakkan** [comment]
Great! Thanks for reporting back
