### ISSUE TITLE
sftpgo charts unable to login with multiple replicas

### ISSUE THREAD

**Issue by jonjesse** [drakkan/sftpgo#652]
When using multiple replicas the authentication token is not shared between replicas so depending which replica you hit you may or may not be authenticated:

This request works:
curl -I -k -H "Authorization: Bearer $BEARER" https://sftpgo-dev.mydomain.com/api/v2/users
**HTTP/2 200** 
server: nginx/1.19.2
date: Fri, 17 Dec 2021 20:21:45 GMT
content-type: application/json; charset=utf-8
vary: Accept-Encoding
strict-transport-security: max-age=15724800; includeSubDomains

This request doesn't work (hits the other replica)
curl -k -H "Authorization: Bearer $BEARER" https://sftpgo-dev.mydomain.com/api/v2/users
**{"error":"token is unauthorized","message":"Unauthorized"}**

Also the webUI doesn't let you login at all, the error message is:
**unable to verify form token: token is unauthorized**

When deploying chart with single replica, everything is working fine
Using latest chart 0.10.0, with app version 2.2.0

**Comment by drakkan** [comment]
Hi,

you can configure sticky sessions or set the same [signing passphrase](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L227) on all your nodes. If empty (the default) a random signing passphrase will be generated each time SFTPGo starts. If you set a signing passphrase you should consider rotating it periodically for added security.

**Comment by jonjesse** [comment]
Hi Drakkan,

Thanks much, that fixed the issue, appreciate your help.
