### ISSUE TITLE
Web Client: Moving files between folders?

### ISSUE THREAD

**Issue by juliuswz** [drakkan/sftpgo#653]
I tried renaming as we do on an sftp server but apparently this isn't possible.

**Comment by drakkan** [comment]
Hi,

so basically you want to set the full path in the "New name" field. I'll try to check it out when I have time

**Comment by juliuswz** [comment]
Hello, 
Yeah, it might be easier than implementing a full-featured "move file" option 

Thank you

**Comment by drakkan** [comment]
Hi,

you can now specify a target directory when you rename a file/dir

![Schermata del 2021-12-25 17-11-01](https://user-images.githubusercontent.com/553263/147389134-bdfd7c49-0a70-412f-9f61-62ebd8553a4a.png)

This is a javascript only modification, help with testing is welcome, I'm not a javascript expert and hacks like this seems required to handle special chars (note the replace to properly handle spaces):

```
$("#rename_new_dir").val(decodeURIComponent("{{.CurrentDir}}".replace(/\+/g, '%20')));
```

I'm sure there is some other corner case. 

You can test this change by downloading a build artifact for your OS from [here](https://github.com/drakkan/sftpgo/actions/runs/1622096280) or by using one of the edge docker variants once [CI](https://github.com/drakkan/sftpgo/actions/runs/1622096279) builds it. Thank you

**Comment by juliuswz** [comment]
Hello,

I tested with both files and directories with and without special characters and they all worked. Great!

Maybe it would be interesting to open the dialog with the "New Name" already filled in with the old one (obviously from the point of view of someone who is just moving files and not renaming). 

Thank you very much.

**Comment by drakkan** [comment]
> Hello,
> 
> I tested with both files and directories with and without special characters and they all worked. Great!
> 

Thank you

> Maybe it would be interesting to open the dialog with the "New Name" already filled in with the old one (obviously from the point of view of someone who is just moving files and not renaming).
>

This way if a user click without changing anything it will rename a file on itself:

```
"file_path":"/home/nicola/webdav/testlock.sh","target_path":"/home/nicola/webdav/testlock.sh"
```

This way the file could be lost/damaged.

I have to add a server side check to refuse such requests.
 
> Thank you very much.

**Comment by juliuswz** [comment]
> This way if a user click without changing anything it will rename a file on itself:
> 
> ```
> "file_path":"/home/nicola/webdav/testlock.sh","target_path":"/home/nicola/webdav/testlock.sh"
> ```
> 
> This way the file could be lost/damaged.
> 
> I have to add a server side check to refuse such requests.
> 

Got it. I'll take a look at it. 
Thank you again!

**Comment by drakkan** [comment]
> > This way if a user click without changing anything it will rename a file on itself:
> > ```
> > "file_path":"/home/nicola/webdav/testlock.sh","target_path":"/home/nicola/webdav/testlock.sh"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way the file could be lost/damaged.
> > I have to add a server side check to refuse such requests.
> 
> Got it. I'll take a look at it. Thank you again!

I fixed the rename with source = target locally, I'll add some test cases later today or tomorrow and I'll push the change, thanks for let me noticing this issue

**Comment by juliuswz** [comment]
Ok. Let me know and I'll be glad to test it.

**Comment by drakkan** [comment]
It should be ok now

https://github.com/drakkan/sftpgo/commit/76eb1ea83a72aaea188eb34ab4a400a20aa949fa

these changes will be part of the upcoming v2.2.1 that should happen this week, any testing is welcome, thank you

**Comment by juliuswz** [comment]
I tested again and everything is ok.
Now properly handling if the source and target are the same.

Thank you, that was really fast :)

**Comment by drakkan** [comment]
Great, thank you for your feedback
