### ISSUE TITLE
portable mode, "-v" does not work

### ISSUE THREAD

**Issue by vip123456789** [drakkan/sftpgo#655]
portable mode, "-v" does not work，does not print the log information out~

**Comment by drakkan** [comment]
Hi,

please try something like this

```bash
./sftpgo portable -v -l /tmp/log
```

to have verbose logs you have to specify a log file

**Comment by vip123456789** [comment]
How to display the log in the command line window instead of a log file，thank you~

**Comment by drakkan** [comment]
This is not possible in portable mode, you will be unable to read the auto generated user and port to connect to. If you want console log you can simply start sftpgo like this:

```shell
./sftpgo serve -l ""
```

you then connect to the web ui and create a user as explained in the getting started guide

https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md#Initial-configuration
