### ISSUE TITLE
Add additional details to fs events in notifier plugin

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#656]
The following information (maybe more, don't know) is missing from the FS event details:
- Filesystem provider
- Bucket name

They are available in hooks though. My understanding is that plugins are supposed to be lower level constructs, so I'd assume plugins can do (almost) everything that hooks can.

**Comment by drakkan** [comment]
Currently plugins cannot do things that are possible using hooks, for example notifier plugins don't handle pre-events and sync actions as hook, they just get the notifications. We probably need to add a separate plugin to react to actions.

The only expection is the metadata plugin, it has no hook-based equivalent .

However we can certainly add provider, bucket and endpoint to notifier plugins adding them within a struct, maybe we can just move the `ActionNotification` to the plugin package and use it

**Comment by sagikazarmark** [comment]
Personally, I really like the new hook system, because it allows easier immediate integration with SFTPGo. At least I find it easier, even though it's a low level thing.

Still, I think it would be great if plugins could eventually replace hooks/provide all the features they do, so at least the implementation could be plugin-based.

I certainly plan to rewrite my hooks as plugins.

I could send a PR adding the above three parameters to the notifier plugin, but can I also ask your opinion about #658? Maybe we could do that first, so that we only have to break plugins once.

**Comment by drakkan** [comment]
> Personally, I really like the new hook system, because it allows easier immediate integration with SFTPGo. At least I find it easier, even though it's a low level thing.
> 
> Still, I think it would be great if plugins could eventually replace hooks/provide all the features they do, so at least the implementation could be plugin-based.
> 
> I certainly plan to rewrite my hooks as plugins.
> 
> I could send a PR adding the above three parameters to the notifier plugin, but can I also ask your opinion about #658? Maybe we could do that first, so that we only have to break plugins once.

yes, I'm trying to work on this right now, not sure if I have enough time today

**Comment by drakkan** [comment]
> Personally, I really like the new hook system, because it allows easier immediate integration with SFTPGo. At least I find it easier, even though it's a low level thing.

I think many people find it easier than writing a plugin and this is the reason it will be always supported

> Still, I think it would be great if plugins could eventually replace hooks/provide all the features they do, so at least the implementation could be plugin-based.
> I certainly plan to rewrite my hooks as plugins.

I would like to avoid a double notification: from sftpgo to the plugin via RPC and then from the plugin to the external system via HTTP/script execution. This seems a waste of resources even if pratically the times should be not noticeable

> I could send a PR adding the above three parameters to the notifier plugin, but can I also ask your opinion about #658? Maybe we could do that first, so that we only have to break plugins once.
> 
yes, I'm trying to work on this right now, I'm moving the `ActionNotification` struct to the notifier plugin package, not sure if I have enough time today

**Comment by sagikazarmark** [comment]
> I would like to avoid a double notification: from sftpgo to the plugin via RPC and then from the plugin to the external system via HTTP/script execution. This seems a waste of resources even if pratically the times should be not noticeable

In distributed systems eventually consistency is an accepted drawback, so in case of the notifier plugin I don't think it's a problem. Also, the local RPC call is cheap.
