### ISSUE TITLE
Plugins could receive a struct instead of a dozen of parameters

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#658]
I guess that hard couples the plugin implementation to the relevant plugin package, but it would also make extending the list of parameters as well (currently adding new parameters is a breaking change).

**Comment by sagikazarmark** [comment]
Do you need help with updating the existing plugins? If so, I'd be happy to send some PRs once the changes are released.

**Comment by drakkan** [comment]
Hi,

I already updated the existing plugin locally, I have to find some time to test them.
I am also waiting because I have not yet abandoned the idea of providing a sdk as a separate module and therefore I would like to do the tests only once
