### ISSUE TITLE
Can't limit SFTPGO_SFTPD__HOST_KEX_ALGORITHMS

### ISSUE THREAD

**Issue by helmut72** [drakkan/sftpgo#661]
I want to secure my SFTP connections:

```
SFTPGO_SFTPD__HOST_KEYS="id_ed25519"
SFTPGO_SFTPD__HOST_KEX_ALGORITHMS="kexAlgoCurve25519SHA256"
SFTPGO_SFTPD__HOST_CIPHERS="chacha20Poly1305ID,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
SFTPGO_SFTPD__MACS="hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com"
```

Keys, ciphers and macs looks good and are limited. But it looks like kex isn't limited to kexAlgoCurve25519SHA256. It's only possible to change the order.

From the documentation [full configuration](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md) both macs and kex mentioned 'preference order'. But macs can be limited to the one I have explicit configured and kex not.

Because of this my server got bad results. From sshcheck.com:
<img width="1160" alt="Bildschirmfoto 2022-01-05 um 09 46 21" src="https://user-images.githubusercontent.com/1388751/148191788-a3059e14-6ec5-4149-b8f4-523cb828812a.png">

From sshaudit.com (result is a D score):
<img width="1002" alt="Bildschirmfoto 2022-01-05 um 09 45 57" src="https://user-images.githubusercontent.com/1388751/148191902-d18ecec1-eee7-46cc-a6ad-a062f7e61446.png">

**Comment by drakkan** [comment]
Hi,

I think you specified the wrong names, take a look [here](https://github.com/drakkan/sftpgo/discussions/368).

You have to set the string value and not the Go constant name, take a look here

https://github.com/golang/crypto/blob/master/ssh/kex.go#L28

chacha20Poly1305ID is wrong too for the same reason:

https://github.com/golang/crypto/blob/master/ssh/cipher.go#L638

Finally note that we use a patched version of crypto/ssh and I also added support for `aes256-gcm@openssh.com`, so you can also set this cipher if you want

https://github.com/drakkan/crypto/blob/sftpgo/ssh/transport.go#L21

**Comment by helmut72** [comment]
Hello, thank you!

Changing to
```
SFTPGO_SFTPD__HOST_KEYS="id_ed25519"
SFTPGO_SFTPD__HOST_KEX_ALGORITHMS="curve25519-sha256@libssh.org"
SFTPGO_SFTPD__HOST_CIPHERS="chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
SFTPGO_SFTPD__MACS="hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com"
```
doesn't help to limit KEX to curve25519-sha256 only.

**Comment by drakkan** [comment]
Hi,

please try this way:

```
SFTPGO_SFTPD__HOST_KEYS="id_ed25519"
SFTPGO_SFTPD__KEX_ALGORITHMS="curve25519-sha256@libssh.org"
SFTPGO_SFTPD__CIPHERS="chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
SFTPGO_SFTPD__MACS="hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com"
```
at startup SFTPGo log the used configuration, for example:

```
{"level":"debug","time":"2022-01-05T11:41:55.356","sender":"service","message":"initializing SFTP server with config {Banner:SFTPGo_2.2.1-dev Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] MaxAuthTries:0 Actions:{ExecuteOn:[] ExecuteSync:[] Hook:} HostKeys:[id_ed25519] KexAlgorithms:[curve25519-sha256@libssh.org] Ciphers:[chacha20-poly1305@openssh.com aes256-gcm@openssh.com aes128-gcm@openssh.com aes256-ctr aes192-ctr aes128-ctr] MACs:[hmac-sha2-512-etm@openssh.com hmac-sha2-256-etm@openssh.com] TrustedUserCAKeys:[] LoginBannerFile: EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveAuthentication:false KeyboardInteractiveHook: PasswordAuthentication:true FolderPrefix: certChecker:<nil> parsedUserCAKeys:[]}"}
```

**Comment by helmut72** [comment]
OMG ... shame on me. Now it's working! Thank you!!

**Comment by helmut72** [comment]
Sorry to disturb again. With this settings:

```
SFTPGO_SFTPD__HOST_KEYS="id_ed25519"
SFTPGO_SFTPD__KEX_ALGORITHMS="curve25519-sha256@libssh.org"
SFTPGO_SFTPD__CIPHERS="chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
SFTPGO_SFTPD__MACS="hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com"
```

... doing a test with [SSH Audit](https://sshaudit.com), my logs shows this one:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9dd6d6]
goroutine 238 [running]:
golang.org/x/crypto/ssh.newPacketCipher({{0x2519330, 0x1, 0x1}, {0x2519331, 0x1, 0x1}, {0x2519332, 0x1, 0x1}}, {{0xc0005d9420, ...}, ...}, ...)
	golang.org/x/crypto@v0.0.0-20211215153901-e495a2d5b3d3/ssh/transport.go:246 +0x136
golang.org/x/crypto/ssh.(*transport).prepareKeyChange(0xc00078dd40, 0xc00070dc00, 0x25c8380)
	golang.org/x/crypto@v0.0.0-20211215153901-e495a2d5b3d3/ssh/transport.go:81 +0x12f
golang.org/x/crypto/ssh.(*handshakeTransport).enterKeyExchange(0xc0002afa20, {0xc0005b3a40, 0x0, 0x0})
	golang.org/x/crypto@v0.0.0-20211215153901-e495a2d5b3d3/ssh/handshake.go:606 +0x4a8
golang.org/x/crypto/ssh.(*handshakeTransport).kexLoop(0xc0002afa20)
	golang.org/x/crypto@v0.0.0-20211215153901-e495a2d5b3d3/ssh/handshake.go:301 +0xa6
created by golang.org/x/crypto/ssh.newServerTransport
	golang.org/x/crypto@v0.0.0-20211215153901-e495a2d5b3d3/ssh/handshake.go:143 +0x13d
```

I'm use `drakkan/sftpgo:v2-alpine-slim`

Should I open a new issue?

**Comment by drakkan** [comment]
can you replicate the issue after removing `hmac-sha2-512-etm@openssh.com`? It is not supported in crypto/ssh, maybe the library accepts the value and then crash while trying to use it. I'll investigate later today

**Comment by helmut72** [comment]
No crash anymore. That's enough for me. If it's not supported, I don't use it. Thanks a lot!

**Comment by drakkan** [comment]
I looked at the code, the library does not check the values for mac, kex etc..., it will simply crash if you pass an unsupported value. The problem is that the supported values are private so I have to copy and keep them in sync if I want to validate the supported values in SFTPGo. I'll decide later, thanks for spotting this issue

**Comment by helmut72** [comment]
It's up to you. I'm not sure anymore why I have added it. I think my server is now secured more than enough regarding SFTP.

**Comment by drakkan** [comment]
> It's up to you. I'm not sure anymore why I have added it. I think my server is now secured more than enough regarding SFTP.

You could have issues with old clients :)

**Comment by drakkan** [comment]
It should be better now

https://github.com/drakkan/sftpgo/commit/ec1d20f46f2242690b80902fd78be96812caa597

please note that `hmac-sha2-512-etm@openssh.com` and `hmac-sha2-512` are only available in the development version for now

**Comment by helmut72** [comment]
I've looked into the source. Now the documentation is more clear and you send an output if unsupported. Thanks!
