### ISSUE TITLE
Custom URL with NGINX reverse proxy

### ISSUE THREAD

**Issue by acourter27** [drakkan/sftpgo#663]
I have to imagine I'm missing something stupid, but when I'm running docker I can get everything to work fine locally, but not externally.

I'm running this (--rm for testing) to start the docker:
`
sudo docker run --name sftpgo \
 --rm \
 -p 8012:8080 \
 -p 2022:2022 \
 --mount type=bind,source=/home/aaron/sftpgo,target=/srv/sftpgo \
 --mount type=bind,source=/home/aaron/sftpgo/home,target=/var/lib/sftpgo \
 -d "drakkan/sftpgo:latest"
`

My reverse proxy is simple
`
server {
  server_name sftp.[masked].net;
  location / {
    proxy_pass "https://localhost:8012";
    proxy_set_header Host $host;
  }
}
`

I have the URL routing to my public IP (I host other sites & apps without any issues).

I'm getting to the server just fine, but I'm getting a bad gateway error.

**Comment by drakkan** [comment]
Hi,

I'm not sure, maybe you didn't configure https and so it should be `proxy_pass "http://localhost:8012";`

**Comment by acourter27** [comment]
I have https configured with LetsEncrypt at the NGINX level; I just didn't include all that info.

Here's the full NGINX file.
```
server {
	server_name sftpgo.[masked].net;
	location / {
		proxy_pass "https://localhost:8012";
		proxy_set_header Host $host;
	}

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sftpgo.[masked].net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sftpgo.[masked].net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = sftpgo.[masked].net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	server_name sftpgo.[masked].net;
    return 404; # managed by Certbot


}
```

**Comment by acourter27** [comment]
Sorry, it was indeed something stupid. You're right about the "http"; that was the listener for port 80 so it needed to be http; then it routes to https. I changed that and it works fine.

Just needed someone to bounce it off of I guess. Thanks!
