### ISSUE TITLE
S3 bucket issue

### ISSUE THREAD

**Issue by mp-vpatel** [drakkan/sftpgo#667]
Hi, 
I have installed the latest version and added AWS S3(Compatible) but I am getting errors when I try to update or download a file. 

Practically, it does not allow me to do anything. I could see the folders and files inside but I cannot upload or download those. I am not sure what I have to do. 

This AccessKey and Access Secret key has full access to my bucket. As I am utilizing this for other projects without any [concern.] 

Here is the error:
`unable to read file "/CC2.2.6.jpg": failure`

From the Admin portal I have added:
Bucket
Access Key
Access Secret
Region
Key Prefix

-everything else is with a default value. Here are the snapshot.

![s3-issue](https://user-images.githubusercontent.com/80788035/148500603-df895362-f4c2-435f-aa4b-d67d5c59a1b9.jpg)
![s3-issue-2](https://user-images.githubusercontent.com/80788035/148500606-b7beacc5-84df-4bb5-b3a1-a0ea57fceb91.jpg)

Please guide me on what I have to do to overcome this error.

**Comment by drakkan** [comment]
Hi,

please post/read SFTPGo logs, they should contain more details about this, thanks

**Comment by fdefilippo** [comment]
I could be wrong but from the screenshot it seems that the endpoint is missing.

**Comment by mp-vpatel** [comment]
@drakkan - Here are the logs: 
{"level":"debug","time":"2022-01-07T13:32:36.385","sender":"HTTP","connection_id":"HTTP_c7c41t4conkg00911h20","message":"connection added, local address \"172.17.0.3:8080\", remote address \"172.17.0.1:60051\", num open connections: 1"}
{"level":"error","time":"2022-01-`07T13:32:36.549","sender":"HTTP","connection_id":"HTTP_c7c41t4conkg00911h20","message":"could not open file \"/Test-viral/CC2.2.6.jpg\" for reading: open /srv/sftpgo/data/viral/pipefile4175208302: permission denied"}`
{"level":"debug","time":"2022-01-07T13:32:36.550","sender":"HTTP","connection_id":"HTTP_c7c41t4conkg00911h20","message":"connection removed, local address \"172.17.0.3:8080\", remote address \"172.17.0.1:60051\" close fs error: <nil>, num open connections: 0"}
{"level":"info","time":"2022-01-07T13:32:36.550","sender":"httpd","local_addr":"172.17.0.3:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"172.17.0.1:60051","request_id":"drakkan-sftpgo1/o4hT8Ckyb7-000223","uri":"http://192.168.86.76:8080/web/client/files?path=%2FCC2.2.6.jpg&_=1641562058","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36","resp_status":200,"resp_size":43176,"elapsed_ms":185}
{"level":"debug","time":"2022-01-07T13:32:36.972","sender":"HTTP","connection_id":"HTTP_c7c41t4conkg00911h30","message":"connection added, local address \"172.17.0.3:8080\", remote address \"172.17.0.1:60051\", num open connections: 1"}
{"level":"debug","time":"2022-01-07T13:32:37.008","sender":"HTTP","connection_id":"HTTP_c7c41t4conkg00911h30","message":"connection removed, local address \"172.17.0.3:8080\", remote address \"172.17.0.1:60051\" close fs error: <nil>, num open connections: 0"}
{"level":"info","time":"2022-01-07T13:32:37.008","sender":"httpd","local_addr":"172.17.0.3:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"172.17.0.1:60051","request_id":"drakkan-sftpgo1/o4hT8Ckyb7-000224","uri":"http://192.168.86.76:8080/web/client/dirs?path=%2F&_=1641562351644","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36","resp_status":200,"resp_size":185,"elapsed_ms":36}

I am not sure why I am receiving permission denied. I am accessing the same S3 bucket using the S3 browser with the same AWS_Key and AWS_Seceret. I could also download the same file using the S3 browser. 

@fdefilippo -  Endpoint is not required I guess so I have not put that in there.

**Comment by mp-vpatel** [comment]
In addition my permission for this particular bucket is " "**Action": "s3:***"," and **mpmain/*** under IAM policy.

**Comment by drakkan** [comment]
The user running the sftpgo service cannot write temporary files to `/srv/sftpgo/data/viral`.

**Comment by mp-vpatel** [comment]
Thank you @drakkan. I was adding "Volume" in my docker and picking "/" root path as a mount path. Once I have switched to "sftpgo" user path, everything started to flow again. 

Thank you very much and I absolutely love this tool. Great work!
