### ISSUE TITLE
Ask for detailed transfer logs configuration 

### ISSUE THREAD

**Issue by Fancy-Guo** [drakkan/sftpgo#668]
![image](https://user-images.githubusercontent.com/45280948/148519687-a78f1b08-6447-494f-a66c-7b5920750d70.png
Didn't work...emmmm

**Comment by drakkan** [comment]
In you image I read `SFTPGO_LOG_FILE`, if you read the doc [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md), you can see that you have to set `SFTPGO_LOG_FILE_PATH`. Also please be sure that the `sftpgo` user can write to the configured file. This one will work for sure:

```
SFTPGO_LOG_FILE_PATH=/srv/sftpgo/logs/sftpgo.log
```
