### ISSUE TITLE
SSH Key External Authentication

### ISSUE THREAD

**Issue by derekbking** [drakkan/sftpgo#671]
Hi,

I am trying to get external authentication working for key files. I can accept keys without validating at the public key property. How can I validation the public key property? Does this need to be done manually within my Rest API? I can provide more details if necessary. Mainly, I just wanted to know if there was a way to leverage the library while still using an external Rest API for authentication.

Thank you!

**Comment by drakkan** [comment]
Hi,

there is nothing built in but keep in mind that the public key you receive is serialized is a format suitable for inclusion in an OpenSSH authorized_keys file (it always ends with a new line). So if you store the public key in the same format in your backend, this is a simple string comparison.

If the SFTPGo users already exists and your hook returns an empty response the public key will be compared with the ones already stored for the user, if any. If your hook returns a non-empty response the public key is automatically accepted and stored and so the user will be logged-in

**Comment by derekbking** [comment]
Thank you, I was overcomplicating this process and it seems to be working just fine now. I went into a bit of a rabbit hole with this one. I thought the client was generating a new public key that we had to ensure was generated from the same private key. Turns out the pub key in the DB was just a different key.
