### ISSUE TITLE
Web Client: Instant Share

### ISSUE THREAD

**Issue by gitpubber** [drakkan/sftpgo#674]
Hello @drakkan , Thanks for sftpgo. It's very good project and i like it.

My use case is to access files hosted in server on Android phone and Desktop. And i host sftpgo in server to serve them. Those hosted files in server are mostly multimedia files(movies ,songs and images).

But, for me , i need to play those multimedia files on media player.
* **SFTP**  is supported by File Managers that i use on Android and also VLC. But, it is very slow.
* **FTP** is good and faster but there is lack of support for FTP in Android file managers and VLC.
* **HTTP** is really good and fast for streaming . For this, i go to web client, share the file, copy the shared link and paste it in media player. Too much hassle.

So, please add instant share capability which lets me to Select the file to play it in media player. It can be protected by Basic Auth or token to account in REST query.

**Comment by drakkan** [comment]
Hi,

maybe WebDAV could help here.

Files are already available via REST API

https://sftpgo.stoplight.io/docs/sftpgo/b3A6MTY2OTU4OTI-download-a-single-file

but I'm not sure how you can get and send the bearer token

**Comment by gitpubber** [comment]
But, WebDAV too doesn't have good clients on Android :(

**Comment by drakkan** [comment]
@gitpubber did you close this issue because you found a solution? Can you please elaborate? Thanks

**Comment by gitpubber** [comment]
@drakkan , it was closed accidentally.

nope, solution is not found. 

i think best solution here is :
1) one button which creates share link and copies that share link to clipboard
2) share link must expire in some certain time configurable by user.

**Comment by drakkan** [comment]
expiration is already supported, I think I cold make shares "browsable" to fix this, so you can have a link to access a single shared folder and browse all the files there and/or copy the download link.

However I'm busy with other things now, this may take a while

**Comment by helmut72** [comment]
This feels like one common sharing feature what Nextcloud provides. Other sharing features are:

- Mandatory/optional password requirement for the download link to specific users: Not everyone is allowed to create links without a password for security reason.
- Mandatory/optional maximum time limit (x days) for the download link to specific users. Not everyone is allowed to create endless download links, because primary storage is something else.
- If it's a shared folder, optionally others (without an user account in sftpgo) can upload files.
- Notifications (eg. via smtp or a webhook), when a file was downloaded or uploaded.

**Comment by drakkan** [comment]
Hi guys,

I have a WIP like this that should fix this issue:

![Schermata del 2022-02-05 17-08-22](https://user-images.githubusercontent.com/553263/152649320-2f236ca2-55c9-49bc-8acb-f9072f2b7ccc.png)

basically if you share a single folder it could be browsed and you can download single files.

@helmut72 regarding your requests:

1) Mandatory/optional password requirement: ok I'll add this in the future
2) Mandatory/optional maximum time limit. I'm not sure here, the shared path is part of the user quota so it can already be limited.
3) Folders can have read or write scope. Upload, for external users, is supported for folders with write scope.
4) Notifications: maybe I'll add a hook in the future

Working on the web ui is really difficult for me, I don't like HTML and Javascript and my skills are quite basic. If you want to improve this basic UI please send a PR, thanks for your understanding

**Comment by franklouwers** [comment]
Any way to get this to work without the UI? So we can generate a share link which uses Basic Authentication?

**Comment by lucker999** [comment]
> Perhaps a user will need to generate a temporarily link, in which any http client can download using that link.

Yes, please, but not temporary! A file with a config doesn't need to be timed. A link with a loooooong unique hash is more than enough! Try to guess that :)
