### ISSUE TITLE
Support with S3 integration

### ISSUE THREAD

**Issue by ricardojmv85** [drakkan/sftpgo#68]
I have some questions about the s3 configuration parameters listed in the doc.

* s3 endpoint is always required? if it is, you are referring to an s3 access point?

**Comment by drakkan** [comment]
Hi,

S3 endpoint is required for S3 compatible object storage, for example `MinIO`, if you are connecting to AWS you can leave it blank

**Comment by ricardojmv85** [comment]
Ty @drakkan, just another question: How is the pattern for the class storage and the region paremetwe

**Comment by drakkan** [comment]
storage class can be empty too and the default value will be used.

The region is required and must match the one configured for your bucket, you can ge the list of the available regions in aws docs:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions

for example the region for my test bucket is Frankfurt so in the SFTPGo configuration I have `eu-central-1`

**Comment by ricardojmv85** [comment]
Ty @drakkan

**Comment by drakkan** [comment]
@ricardojmv85 no problem, I'll try to improve the docs

**Comment by drakkan** [comment]
@ricardojmv85 the documentation should be better now, If you find something other is missing please comment here or send a pull request, documentation updates are always welcome! thanks

**Comment by ricardojmv85** [comment]
Hi @drakkan, could u please list me the set of permissions you gave to your aws user. I am experiencing problems with the bucket directory listing, i got "remote readdir("/"): Failure"

**Comment by drakkan** [comment]
@ricardojmv85 sorry I have only one aws account. I think aws objects are, by default, private, so they are accessibile only to the owner. Can you please confirm that the bucket owner is able to list,write s3 objects while other user cannot do the same?

You can create a bucket policy to change this (probably you need to change the permissions for existing objects). Have you read the documentation here?

https://aws.amazon.com/it/premiumsupport/knowledge-center/cross-account-access-s3/

currently sftpgo does not set any ACL while uploading objects to S3, so the default bucket policy is applied. If you think this is useful for your use case I can add support for canned ACL

https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#CannedACL

but I think that you can set a default bucket policy to allow access to other users, please let me know if you solve your issue, thanks!

**Comment by ricardojmv85** [comment]
Hi @drakkan thank you for your response, unfortunately i continuing  having this issue.
I have a bucket just as you with the default conf, just one user with admin role, but still having this problem. I do not know if it is related with the docker configuration described in the debian Dockerfile

**Comment by drakkan** [comment]
OK, so probably there is some configuration issue, can you please post your sftpgo logs?

You can also log to stdout, for the debian based dockerfile change the env var here:

https://github.com/drakkan/sftpgo/blob/master/docker/sftpgo/debian/Dockerfile#L62 

to:

```
ENV SFTPGO_LOG_FILE_PATH=""
```

or simply use the docker -e flag to override that env var, for example:

```
docker run <options> -e SFTPGO_LOG_FILE_PATH= <other options>
```

Here is my sample AWS config

![Schermata del 2020-02-12 08-28-43](https://user-images.githubusercontent.com/553263/74312628-5b348300-4d72-11ea-978f-1fa6a84f982f.png)

do you see relevant difference with your?

**Comment by ricardojmv85** [comment]
Here are my logs for debian image:
```
{"level":"info","time":"2020-02-12T16:18:50.089","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.5-dev-553ccea-2020-02-05T21:58:47Z, config dir: /app/config, config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false"}
sftp_1  | {"level":"debug","time":"2020-02-12T16:18:50.091","sender":"config","connection_id":"","message":"config file used: '/app/config/sftpgo.json', config loaded: {SFTPD:{Banner:SFTPGo_0.9.5-dev BindPort:2022 BindAddress: IdleTimeout:60 MaxAuthTries:0 Umask:0022 UploadMode:0 Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd] KeyboardInteractiveProgram:} ProviderConf:{Driver:postgresql Name:postgres Host:localhost Port:5432 Username:postgres Password:[redacted] SSLMode:0 ConnectionString: UsersTable:users ManageUsers:1 TrackQuota:2 PoolSize:0 UsersBaseDir:/app/data Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} ExternalAuthProgram: ExternalAuthScope:0 CredentialsPath:credentials} HTTPDConfig:{BindPort:8080 BindAddress: TemplatesPath:/app/web/templates StaticFilesPath:/app/web/static BackupsPath:/app/backups AuthUserFile: CertificateFile: CertificateKeyFile:}}"}
sftp_1  | {"level":"debug","time":"2020-02-12T16:18:50.092","sender":"postgresql","connection_id":"","message":"postgres database handle created, connection string: \"host='localhost' port=5432 dbname='postgres' user='postgres' password='[redacted]' sslmode=disable connect_timeout=10\", pool size: 0"}
sftp_1  | {"level":"debug","time":"2020-02-12T16:18:50.109","sender":"service","connection_id":"","message":"initializing SFTP server with config {Banner:SFTPGo_0.9.5-dev BindPort:2022 BindAddress: IdleTimeout:60 MaxAuthTries:0 Umask:0022 UploadMode:0 Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd] KeyboardInteractiveProgram:}"}
sftp_1  | {"level":"debug","time":"2020-02-12T16:18:50.110","sender":"utils","connection_id":"","message":"set umask to 0022 (18)"}
sftp_1  | {"level":"info","time":"2020-02-12T16:18:50.110","sender":"sftpd","connection_id":"","message":"Loading private key: /app/config/id_rsa"}
sftp_1  | {"level":"debug","time":"2020-02-12T16:18:50.109","sender":"httpd","connection_id":"","message":"initializing HTTP server with config {BindPort:8080 BindAddress: TemplatesPath:/app/web/templates StaticFilesPath:/app/web/static BackupsPath:/app/backups AuthUserFile: CertificateFile: CertificateKeyFile:}"}
sftp_1  | {"level":"info","time":"2020-02-12T16:18:50.112","sender":"sftpd","connection_id":"","message":"server listener registered address: [::]:2022"}
sftp_1  | {"level":"info","time":"2020-02-12T16:19:44.503","sender":"sftpd","connection_id":"3cb0292a2e17abf9981dac256bc63732763968230abc59ab359338194003d88a","message":"User id: 3, logged in with: \"password\", username: \"user3\", home_dir: \"/app/data/user1\" remote addr: \"127.0.0.1:58698\""}
sftp_1  | {"level":"debug","time":"2020-02-12T16:19:44.506","sender":"postgresql","connection_id":"","message":"last login updated for user \"user3\""}
sftp_1  | {"level":"debug","time":"2020-02-12T16:19:44.508","sender":"sftpd","connection_id":"3cb0292a2e17abf9981dac256bc63732763968230abc59ab359338194003d88a","message":"connection added, num open connections: 1"}
sftp_1  | {"level":"debug","time":"2020-02-12T16:19:44.516","sender":"sftpd","connection_id":"3cb0292a2e17abf9981dac256bc63732763968230abc59ab359338194003d88a","message":"requested list file for dir: \"/test\""}
sftp_1  | {"level":"warn","time":"2020-02-12T16:19:45.686","sender":"sftpd","connection_id":"3cb0292a2e17abf9981dac256bc63732763968230abc59ab359338194003d88a","message":"error listing directory: &awserr.baseError{code:\"RequestError\", message:\"send request failed\", errs:[]error{(*url.Error)(0xc000526510)}}"}
```

My config looks just as yours. I am filling the same fields with their respective values.

**Comment by drakkan** [comment]
Hi, 

the aws sdk errors out with this logs:

```
&awserr.baseError{code:\"RequestError\", message:\"send request failed\", errs:[]error{(*url.Error)(0xc000526510)}}"
```

this is a bit cryptic, anyway I get the same error if I remove ths DNS setting (or if I can't connect to AWS).

This could be a trivial question: are you sure that your container is able to resolve aws hostnames and to connect to them?

**Comment by obedespinoza** [comment]
Hi, @drakkan I was able to replicate the error and check if the container was able to reach AWS, which it has. Searching the problem I found this link 

https://github.com/aws/aws-sdk-go/issues/2821

Which states that maybe is how the connection is made in the go client.

**Comment by drakkan** [comment]
Hi,

S3 implementation is quite new and it is mainly tested against MinIO, so we can have a bug, anyway my AWS test bucket works fine so I'm unable to replicate the issue. 

To better understand the problem I improved error logs with this commit:

https://github.com/drakkan/sftpgo/commit/5b47292366cb89f1ff2732d7796d49bf1da5196e

so for example if I set a wrong region I have now this error log:

```
{"level":"warn","time":"2020-02-13T08:25:08.420","sender":"sftpd","connection_id":"0dacfa1e99c3acb8900fe64c1c7b428342ab80d4eab5a131ce8ab820dd5483f0","message":"error listing directory: RequestError: send request failed\ncaused by: Get https://sftpgodevel.s3.eu-central-1a.amazonaws.com/?delimiter=%2F&list-type=2&prefix=chroot%2Fuser1%2F: dial tcp: lookup sftpgodevel.s3.eu-central-1a.amazonaws.com: no such host"}
```

that is far more clear than the previous one.

So please update to the latest git version and post your logs again, thanks!

**Comment by ricardojmv85** [comment]
Hi @drakkan, 
Good news here, thanks to the improved logs and the help of @obedespinoza  it was easy to found that the application coudn't make SLL connections with the AWS endpoint, this because the image that is generated by the Debian Dockerfile does not count with a CA certificate.

I made a  [pull request](https://github.com/drakkan/sftpgo/pull/71)  including an addition in the Debian Dockerfile.

Thanks for all the support.

**Comment by drakkan** [comment]
It is strange, the endpoint for my test bucket is `https://sftpgodevel.s3.eu-central-1.amazonaws.com` and it works in both debian and alpine dockerfile, anyway thanks for your pull request.

**Comment by heneryville** [comment]
@drakkan I can answer that. AWS Transfer costs $0.30 per hour, which is about ~$230 per month to run.

**Comment by drakkan** [comment]
> @drakkan I can answer that. AWS Transfer costs $0.30 per hour, which is about ~$230 per month to run.

yes now i know, people here want to use SFTPGo for free and also get free support. I'm not that [naive anymore](https://github.com/drakkan/sftpgo#support-policy). I have to pay my bills and if that can't happen with SFTPGo I have to do other jobs instead of also providing free support
