### ISSUE TITLE
WebDAV over HTTPS and certificates

### ISSUE THREAD

**Issue by lmattcris** [drakkan/sftpgo#685]
I'm trying to set up a simplistic/specific configuration to have WebDAV access over HTTPS, though maybe due to my lack of skills I'm not successful. The access over HTTP works fine, so the basic configuration is OK.
My server is on a local network, what I want to avoid is just anyone sniffing on plain packets, so I have no real domain or exposure to the internet. I have a client on 192.168.0.100 and a server on 192.168.0.101.  Using OpenSSL I created the dummy CA and certificate files, but it's unclear to me how to configure sftpgo. In the config file, I modified the configuration as in
```
"webdavd": {
    "bindings": [
      {
        "port": 8088,
        "address": "",
        "enable_https": true,
        "client_auth_type": 0,
        "tls_cipher_suites": [],
        "prefix": "",
        "proxy_allowed": []
      }
    ],
    "certificate_file": "certs/myserver.local.crt",
    "certificate_key_file": "certs/myserver.local.key",
    "ca_certificates": [],
    "ca_revocation_lists": [],
    "cors": {
      "enabled": false,
      "allowed_origins": [],
      "allowed_methods": [],
      "allowed_headers": [],
      "exposed_headers": [],
      "allow_credentials": false,
      "max_age": 0
    },
    "cache": {
      "users": {
        "expiration_time": 0,
        "max_size": 50
      },
      "mime_types": {
        "enabled": true,
        "max_size": 1000
      }
    }
  },
```
However this is insufficient, and on access from the client I have an error for "something that's wrong", but no real detail - Ok, my CA configuration isn't specified, but I'm really not sure how I shall state it...

**Comment by drakkan** [comment]
Hi,

your configuration looks correct, the issue here is that your clients don't trust your dummy CA, you can manually import your CA on all the clients. This is doable if you have only few clients. The following tutorial could help (untested)

https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/

**Comment by lmattcris** [comment]
That's exactly the guide I followed, which is very simple and clear, but...
My application (which right now runs on the same machine, and accesses the server on "https://127.0.0.1/something") still whines about an "AuthenticationException: remote certificate hasn't been considered valid" (I'm succinctly translating here, as the message is originally in the local language). "Something is wrong" (this is the claim that accompanies a broken fridge, car, or software alike), I'm still trying to translate it in a more technical form... 😄

**Comment by drakkan** [comment]
please post the output of this command:

```shell
openssl s_client -servername 192.168.0.101 -connect 192.168.0.101:8088
```

it should print something like:

```
verify error:num=18:self signed certificate
verify return:1
```

or something like this for a certificate added to the local trust

```
depth=1 CN = Cert Auth
verify return:1
depth=0 CN = localhost
verify return:1
---
Certificate chain
 0 s:CN = localhost
   i:CN = Cert Auth
---
```

once this command print the expected output your client should work too. Please note that the server name (the one you use to connect to the server) must match the one in the certificate

**Comment by lmattcris** [comment]
That's exactly the guide I followed, which is very simple and clear, but...
My application (which right now runs on the same machine, and accesses the server on "https://127.0.0.1/something") still whines about an "AuthenticationException: remote certificate hasn't been considered valid" (I'm succinctly translating here, as the message is originally in the local language). "Something is wrong" (this is the claim that accompanies a broken fridge, car, or software alike), I'm still trying to translate it in a more technical form... 😄 

EDIT
I made it, my fault: forgot to set `hosts` file with `myserver.local`, that in this case had to be on 127.0.0.1

As a recap, running test on Win 10 pro:

- Used [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) for `openssl`
- Created the dummy CA and the key with `openssl` as in one easy [example](https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/) guide
- Set up the certificate and key in `sftpgo.json`, set `"enable_https": true`
- Added the .pem CA file in root certificates, doing **exactly** what the guide shows - _Note that you can do it slightly differently, the certificate will still appear in the list but if you open it a warning tells that it can't be used! Didn't figure why_
- Added a line similar to `127.0.0.1  myserver.local` to `C:\Windows\System32\drivers\etc\hosts`

**Comment by drakkan** [comment]
Thanks for sharing!
