### ISSUE TITLE
No work Default 21 port to ftp

### ISSUE THREAD

**Issue by am0ral93** [drakkan/sftpgo#693]
I welcome everyone. I have sftpgo and proftpd on the same server. proftpd is running on port 21. I tried to change its port and generally disabled it through systemctl. I want to completely get away from it and connect Sftpgo. But getting error on sftpgo when changing sftpgo.json to port 21. What could be? Do I need to wear proftpd completely?

**Comment by am0ral93** [comment]
> I welcome everyone. I have sftpgo and proftpd on the same server. proftpd is running on port 21. I tried to change its port and generally disabled it through systemctl. I want to completely get away from it and connect Sftpgo. But getting error on sftpgo when changing when changing sftpgo.json to port 21. What could be? Do I need to wear proftpd completely?

-rw-r--r--  1 root root   433 Dec 31 16:32  sftpgo.service - 
I read in another thread that you need to run the script as root, but this does not help.

● sftpgo.service - SFTPGo Server
     Loaded: loaded (/lib/systemd/system/sftpgo.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-01-24 11:34:24 MSK; 288ms ago
    Process: 25927 ExecStart=/usr/bin/sftpgo serve (code=exited, status=1/FAILURE)
   Main PID: 25927 (code=exited, status=1/FAILURE)

**Comment by drakkan** [comment]
Hi,

proftpd generally starts as root, while SFTPGo uses a non root user by default. If you want to bind to ports < 1024 you need to change the SFTPGo systemd unit and set root as user or you can set the `cap_net_bind_service` capability on the sftpgo binary. Take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#binding-to-privileged-ports) for details

**Comment by am0ral93** [comment]
> Hi,
> 
> proftpd generally starts as root, while SFTPGo uses a non root user by default. If you want to bind to ports < 1024 you need to change the SFTPGo systemd unit and set root as user or you can set the `cap_net_bind_service` capability on the sftpgo binary. Take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#binding-to-privileged-ports) for details

[Unit]
Description=SFTPGo Server
After=network.target

[Service]
User=root
Group=root
Type=simple
WorkingDirectory=/etc/sftpgo
Environment=SFTPGO_CONFIG_DIR=/etc/sftpgo/
Environment=SFTPGO_LOG_FILE_PATH=
EnvironmentFile=-/etc/sftpgo/sftpgo.env
ExecStart=/usr/bin/sftpgo serve
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=8192
KillMode=mixed
PrivateTmp=true
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target

Just in case, I also sent a script
and I don't have rules on the server. ubuntu 20

**Comment by drakkan** [comment]
> > Hi,
> > proftpd generally starts as root, while SFTPGo uses a non root user by default. If you want to bind to ports < 1024 you need to change the SFTPGo systemd unit and set root as user or you can set the `cap_net_bind_service` capability on the sftpgo binary. Take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#binding-to-privileged-ports) for details
> 
> [Unit] Description=SFTPGo Server After=network.target
> 
> [Service] User=root Group=root Type=simple WorkingDirectory=/etc/sftpgo Environment=SFTPGO_CONFIG_DIR=/etc/sftpgo/ Environment=SFTPGO_LOG_FILE_PATH= EnvironmentFile=-/etc/sftpgo/sftpgo.env ExecStart=/usr/bin/sftpgo serve ExecReload=/bin/kill -s HUP $MAINPID LimitNOFILE=8192 KillMode=mixed PrivateTmp=true Restart=always RestartSec=10s
> 
> [Install] WantedBy=multi-user.target
> 
> Just in case, I also sent a script and I don't have rules on the server. ubuntu 20

ok, execute

```
systemctl daemon-reload
systemctl restart sftpgo.service
```

and if it still fails, post the sftpgo logs, thank you

**Comment by am0ral93** [comment]
root@ftp:/etc/sftpgo# getcap /usr/bin/sftpgo
/usr/bin/sftpgo = cap_net_bind_service+ep

- also added what you mentioned

**Comment by am0ral93** [comment]
> > > Hi,
> > > proftpd generally starts as root, while SFTPGo uses a non root user by default. If you want to bind to ports < 1024 you need to change the SFTPGo systemd unit and set root as user or you can set the `cap_net_bind_service` capability on the sftpgo binary. Take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#binding-to-privileged-ports) for details
> > 
> > 
> > [Unit] Description=SFTPGo Server After=network.target
> > [Service] User=root Group=root Type=simple WorkingDirectory=/etc/sftpgo Environment=SFTPGO_CONFIG_DIR=/etc/sftpgo/ Environment=SFTPGO_LOG_FILE_PATH= EnvironmentFile=-/etc/sftpgo/sftpgo.env ExecStart=/usr/bin/sftpgo serve ExecReload=/bin/kill -s HUP $MAINPID LimitNOFILE=8192 KillMode=mixed PrivateTmp=true Restart=always RestartSec=10s
> > [Install] WantedBy=multi-user.target
> > Just in case, I also sent a script and I don't have rules on the server. ubuntu 20
> 
> ok, execute
> 
> ```
> systemctl daemon-reload
> systemctl restart sftpgo.service
> ```
> 
> and if it still fails, post the sftpgo logs, thank you

Thanks, It'S WORK. Thanks for your hard work
