### ISSUE TITLE
Use SatusFound instead of StatusMovedPermanently in web path redirect

### ISSUE THREAD

**Issue by jeremy-clerc** [drakkan/sftpgo#695]
Hello,

Using StatusMovedPermanently (301) for redirects is cached by the browser, which means if you reuse the fqdn for another project/test it is broken and you need to clear the cache, etc.

A simple example is *localhost*, one may test different things on localhost, this project, then another one.

Would you accept a PR to change StatusMovedPermanently to SatusFound in the different redirects ?

Thanks.

**Comment by drakkan** [comment]
We have just two 301 redirects, I think we can change them to 302. However, I want keep this [one](https://github.com/drakkan/sftpgo/blob/main/httpd/httpd.go#L564). Thanks

**Comment by jeremy-clerc** [comment]
Sure no problem, my issues are mainly with / to /web/(client|admin) paths.
PR in #696 thanks!
