### ISSUE TITLE
Feature request: add "Denied" to sub-directory permission

### ISSUE THREAD

**Issue by HiFiPhile** [drakkan/sftpgo#70]
Maybe I've overlooked something, but it seems like there is no way to block a user form accessing a sub-directory.

Currently I'm using only `listing` as permission to prevent download, but user can still see the content.

**Comment by drakkan** [comment]
Hi,

you are right, as workaround you can currently set something like this `/subdir:chtimes`. I plan to allow to set empty perms on subdirs later today, after my work hours, thanks
