### ISSUE TITLE
http upload is limited to 1g filesize 

### ISSUE THREAD

**Issue by mnoha** [drakkan/sftpgo#710]
Hi all, 
I'm trying to upload a file bigger than 1g via http. the upload always stops at exactly 1G. It works with native webdav (using winscp as webdav client. 
my environment: 
Server: ubuntu 20, fully patched as docker Server using the sftpgo Container from hub.docker.com. 
Docker-compose file: 

version: '3'
services:
  webdav:
    image: drakkan/sftpgo
    container_name: sftpgo
    ports:
      - 8080:8080
      - 2022:2022
      - 10080:10080
    environment:
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 10080
    volumes:
      - ./data:/srv/sftpgo/data
      - ./sftpgo:/var/lib/sftpgo
      - ./config:/etc/sftpgo

data_provider: sqllight, TLS not enabled 

I added a testuser and tryed to upload a 1.2 G file (ubuntu.iso ). Upload fails at 1G 
I tried to increase the mime_types.max_size parameter from 1000 to 10000, no results. 

Log of sftpgo: 
xxxxxxx@apu22:~/docker-compose/apu22/docker-webdav$ docker-compose up 
Creating sftpgo ... done
Attaching to sftpgo
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.564","sender":"service","message":"starting SFTPGo 2.2.2-a7921500-2022-02-06T14:15:00Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: ., config file: , log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, log utc time: false, load data from: \"\""}
sftpgo    | {"level":"debug","time":"2022-02-06T16:06:45.626","sender":"config","message":"config file used: '\"/etc/sftpgo/sftpgo.json\"', config loaded: {Common:{IdleTimeout:15 UploadMode:0 Actions:{ExecuteOn:[] ExecuteSync:[] Hook:} SetstatMode:0 TempPath: ProxyProtocol:0 ProxyAllowed:[] StartupHook: PostConnectHook: PostDisconnectHook: DataRetentionHook: MaxTotalConnections:0 MaxPerHostConnections:20 DefenderConfig:{Enabled:false Driver:memory BanTime:30 BanTimeIncrement:50 Threshold:15 ScoreInvalid:2 ScoreValid:1 ScoreLimitExceeded:3 ObservationTime:30 EntriesSoftLimit:100 EntriesHardLimit:150 SafeListFile: BlockListFile:} RateLimitersConfig:[{Average:0 Period:1000 Burst:1 Type:2 Protocols:[SSH FTP DAV HTTP] AllowList:[] GenerateDefenderEvents:false EntriesSoftLimit:100 EntriesHardLimit:150}] idleTimeoutAsDuration:0 idleLoginTimeout:0 defender:<nil>} SFTPD:{Banner:SFTPGo_2.2.2 Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] MaxAuthTries:0 Actions:{ExecuteOn:[] ExecuteSync:[] Hook:} HostKeys:[] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveAuthentication:false KeyboardInteractiveHook: PasswordAuthentication:true FolderPrefix: certChecker:<nil> parsedUserCAKeys:[]} FTPD:{Bindings:[{Address: Port:0 ApplyProxyConfig:true TLSMode:0 ForcePassiveIP: PassiveIPOverrides:[] ClientAuthType:0 TLSCipherSuites:[] PassiveConnectionsSecurity:0 ActiveConnectionsSecurity:0 Debug:false ciphers:[]}] Banner:SFTPGo 2.2.2 ready BannerFile: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] ActiveTransfersPortNon20:true DisableActiveMode:false EnableSite:false HASHSupport:0 CombineSupport:0 PassivePortRange:{Start:50000 End:50100}} WebDAVD:{Bindings:[{Address: Port:10080 EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[] Prefix: ProxyAllowed:[] allowHeadersFrom:[]}] CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0} Cache:{Users:{ExpirationTime:0 MaxSize:50} MimeTypes:{Enabled:true MaxSize:10000}}} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:0 Username: Password:[redacted] SSLMode:0 ConnectionString: SQLTablesPrefix: TrackQuota:2 PoolSize:0 UsersBaseDir:/srv/sftpgo/data Actions:{ExecuteOn:[] ExecuteFor:[] Hook:} ExternalAuthHook: ExternalAuthScope:0 CredentialsPath:credentials PreLoginHook: PostLoginHook: PostLoginScope:0 CheckPasswordHook: CheckPasswordScope:0 UpdateMode:0 PasswordHashing:{BcryptOptions:{Cost:10} Argon2Options:{Memory:65536 Iterations:1 Parallelism:2} Algo:bcrypt} PreferDatabaseCredentials:false SkipNaturalKeysValidation:false PasswordValidation:{Admins:{MinEntropy:0} Users:{MinEntropy:0}} PasswordCaching:true DelayedQuotaUpdate:0 CreateDefaultAdmin:false IsShared:0} HTTPDConfig:{Bindings:[{Address: Port:8080 EnableWebAdmin:true EnableWebClient:true EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[] ProxyAllowed:[] HideLoginURL:0 RenderOpenAPI:true WebClientIntegrations:[] allowHeadersFrom:[]}] TemplatesPath:/usr/share/sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static BackupsPath:/srv/sftpgo/backups OpenAPIPath:/usr/share/sftpgo/openapi WebRoot: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] SigningPassphrase:[redacted] MaxUploadFileSize:1048576000 Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0}} HTTPConfig:{Timeout:20 RetryWaitMin:2 RetryWaitMax:30 RetryMax:3 CACertificates:[] Certificates:[] SkipTLSVerify:false Headers:[] customTransport:<nil> tlsConfig:<nil>} KMSConfig:{Secrets:{URL: MasterKeyPath: MasterKeyString: masterKey:}} MFAConfig:{TOTP:[{Name:Default Issuer:SFTPGo Algo:sha1 algo:0}]} TelemetryConfig:{BindPort:0 BindAddress:127.0.0.1 EnableProfiler:false AuthUserFile: CertificateFile: CertificateKeyFile: TLSCipherSuites:[]} PluginsConfig:[] SMTPConfig:{Host: Port:25 From: User: Password:[redacted] AuthType:0 Encryption:0 Domain: TemplatesPath:/usr/share/sftpgo/templates}}"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.627","sender":"kms","message":"secret provider registered for scheme: \"local\", encrypted status: \"Secretbox\""}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.627","sender":"kms","message":"secret provider registered for scheme: \"builtin\", encrypted status: \"AES-256-GCM\""}
sftpgo    | {"level":"debug","time":"2022-02-06T16:06:45.627","sender":"plugins","message":"initialize"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:06:45.627","sender":"smtp","message":"configuration disabled, email capabilities will not be available"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:06:45.628","sender":"dataprovider_sqlite","message":"sqlite database handle created, connection string: \"file:sftpgo.db?cache=shared&_foreign_keys=1\""}
sftpgo    | {"level":"debug","time":"2022-02-06T16:06:45.636","sender":"dataprovider_sqlite","message":"sql database is up to date, current version: 15"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:06:45.640","sender":"dataprovider_sqlite","message":"delayed quota update loop started, wait time: 0s"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:06:45.640","sender":"dataprovider_sqlite","message":"delayed quota update loop ended, wait time: 0s"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.641","sender":"service","message":"FTP server not started, disabled in config file"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.641","sender":"service","message":"telemetry server not started, disabled in config file"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.642","sender":"service","message":"initializing SFTP server with config {Banner:SFTPGo_2.2.2 Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] MaxAuthTries:0 Actions:{ExecuteOn:[] ExecuteSync:[] Hook:} HostKeys:[] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveAuthentication:false KeyboardInteractiveHook: PasswordAuthentication:true FolderPrefix: certChecker:<nil> parsedUserCAKeys:[]}"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.642","sender":"httpd","message":"initializing HTTP server with config {Bindings:[{Address: Port:8080 EnableWebAdmin:true EnableWebClient:true EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[] ProxyAllowed:[] HideLoginURL:0 RenderOpenAPI:true WebClientIntegrations:[] allowHeadersFrom:[]}] TemplatesPath:/usr/share/sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static BackupsPath:/srv/sftpgo/backups OpenAPIPath:/usr/share/sftpgo/openapi WebRoot: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] SigningPassphrase:[redacted] MaxUploadFileSize:1048576000 Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0}}"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.643","sender":"sftpd","message":"Loading private host key \"id_rsa\""}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.644","sender":"webdavd","message":"initializing WebDAV server with config {Bindings:[{Address: Port:10080 EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[] Prefix: ProxyAllowed:[] allowHeadersFrom:[]}] CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0} Cache:{Users:{ExpirationTime:0 MaxSize:50} MimeTypes:{Enabled:true MaxSize:10000}}}"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.659","sender":"sftpd","message":"Host key \"id_rsa\" loaded, type \"ssh-rsa\", fingerprint \"SHA256:W7UxNk/XohDFZf9DcZYJI285SxO/WiiVH9D8NU9/0NM\""}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.659","sender":"sftpd","message":"Loading private host key \"id_ecdsa\""}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.668","sender":"sftpd","message":"Host key \"id_ecdsa\" loaded, type \"ecdsa-sha2-nistp256\", fingerprint \"SHA256:Zs493W4vl37QZR/1NvYriYHXB/SQDyOLWl4r0ktEqUM\""}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.668","sender":"sftpd","message":"Loading private host key \"id_ed25519\""}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.671","sender":"webdavd","message":"server listener registered, address: [::]:10080 TLS enabled: false"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.694","sender":"sftpd","message":"Host key \"id_ed25519\" loaded, type \"ssh-ed25519\", fingerprint \"SHA256:8bapZ4RwIXvNQi4fqYiz4mYuqWrBkm9yLBeEQY1+5g8\""}
sftpgo    | {"level":"debug","time":"2022-02-06T16:06:45.695","sender":"sftpd","message":"enabled SSH commands [md5sum sha1sum cd pwd scp]"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.696","sender":"sftpd","message":"server listener registered, address: [::]:2022"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:45.909","sender":"httpd","message":"server listener registered, address: [::]:8080 TLS enabled: false"}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:59.421","sender":"httpd","local_addr":"172.24.11.31:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.41.40:63227","request_id":"b3ff97fb0193/bZTvLQgflD-000001","uri":"http://192.168.41.1:8080/","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","resp_status":301,"resp_size":52,"elapsed_ms":0}
sftpgo    | {"level":"info","time":"2022-02-06T16:06:59.429","sender":"httpd","local_addr":"172.24.11.31:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.41.40:63227","request_id":"b3ff97fb0193/bZTvLQgflD-000002","uri":"http://192.168.41.1:8080/web/client/login","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","resp_status":200,"resp_size":4843,"elapsed_ms":3}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:09.691","sender":"osfs","connection_id":"HTTP_c7vv4bd17c4ce965rt3g","message":"root directory \"/srv/sftpgo/data/testuser\" for user \"testuser\" does not exist, try to create, mkdir error: <nil>"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:09.710","sender":"dataprovider_sqlite","message":"last login updated for user \"testuser\""}
sftpgo    | {"level":"info","time":"2022-02-06T16:07:09.710","sender":"httpd","local_addr":"172.24.11.31:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"192.168.41.40:63227","request_id":"b3ff97fb0193/bZTvLQgflD-000003","uri":"http://192.168.41.1:8080/web/client/login","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","resp_status":302,"resp_size":0,"elapsed_ms":360}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:09.718","sender":"HTTP","connection_id":"HTTP_c7vv4bd17c4ce965rt4g","message":"connection added, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:63227\", num open connections: 1"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:09.741","sender":"HTTP","connection_id":"HTTP_c7vv4bd17c4ce965rt4g","message":"connection removed, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:63227\" close fs error: <nil>, num open connections: 0"}
sftpgo    | {"level":"info","time":"2022-02-06T16:07:09.741","sender":"httpd","local_addr":"172.24.11.31:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.41.40:63227","request_id":"b3ff97fb0193/bZTvLQgflD-000004","uri":"http://192.168.41.1:8080/web/client/files","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","resp_status":200,"resp_size":42994,"elapsed_ms":26}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:09.907","sender":"HTTP","connection_id":"HTTP_c7vv4bd17c4ce965rt5g","message":"connection added, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:63227\", num open connections: 1"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:09.911","sender":"HTTP","connection_id":"HTTP_c7vv4bd17c4ce965rt5g","message":"connection removed, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:63227\" close fs error: <nil>, num open connections: 0"}
sftpgo    | {"level":"info","time":"2022-02-06T16:07:09.912","sender":"httpd","local_addr":"172.24.11.31:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.41.40:63227","request_id":"b3ff97fb0193/bZTvLQgflD-000005","uri":"http://192.168.41.1:8080/web/client/dirs?path=%2F&_=1644163629762","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","resp_status":200,"resp_size":27,"elapsed_ms":8}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:20.190","sender":"HTTP","connection_id":"HTTP_c7vv4e517c4ce965rt6g","message":"connection added, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:63228\", num open connections: 1"}
sftpgo    | {"level":"info","time":"2022-02-06T16:07:20.194","sender":"httpd","local_addr":"172.24.11.31:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.41.40:63227","request_id":"b3ff97fb0193/bZTvLQgflD-000006","uri":"http://192.168.41.1:8080/web/client/profile","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","resp_status":200,"resp_size":12544,"elapsed_ms":11}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:20.194","sender":"HTTP","connection_id":"HTTP_c7vv4e517c4ce965rt6g","message":"transfer added, id: 1, active transfers: 1"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:34.004","sender":"HTTP","connection_id":"HTTP_c7vv4e517c4ce965rt6g","message":"uploaded file size 1048576000"}
sftpgo    | {"level":"info","time":"2022-02-06T16:07:34.004","sender":"Upload","local_addr":"172.24.11.31:8080","remote_addr":"192.168.41.40:63228","elapsed_ms":13809,"size_bytes":1048576000,"username":"testuser","file_path":"/srv/sftpgo/data/testuser/ubuntu-20.04.3-live-server-amd64.iso","connection_id":"HTTP_c7vv4e517c4ce965rt6g","protocol":"HTTP"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:34.004","sender":"HTTP","connection_id":"HTTP_c7vv4e517c4ce965rt6g","message":"transfer removed, id: 1 active transfers: 0"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:34.005","sender":"HTTP","connection_id":"HTTP_c7vv4e517c4ce965rt6g","message":"connection removed, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:63228\" close fs error: <nil>, num open connections: 0"}
sftpgo    | {"level":"info","time":"2022-02-06T16:07:34.005","sender":"httpd","local_addr":"172.24.11.31:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"192.168.41.40:63228","request_id":"b3ff97fb0193/bZTvLQgflD-000007","uri":"http://192.168.41.1:8080/web/client/file?path=%2F%2Fubuntu-20.04.3-live-server-amd64.iso","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","resp_status":500,"resp_size":113,"elapsed_ms":13819}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:34.514","sender":"HTTP","connection_id":"HTTP_c7vv4hl17c4ce965rt70","message":"connection added, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:63227\", num open connections: 1"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:35.090","sender":"HTTP","connection_id":"HTTP_c7vv4hl17c4ce965rt70","message":"transfer added, id: 1, active transfers: 1"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:48.599","sender":"HTTP","connection_id":"HTTP_c7vv4hl17c4ce965rt70","message":"uploaded file size 1048576000"}
sftpgo    | {"level":"info","time":"2022-02-06T16:07:48.599","sender":"Upload","local_addr":"172.24.11.31:8080","remote_addr":"192.168.41.40:63227","elapsed_ms":13508,"size_bytes":1048576000,"username":"testuser","file_path":"/srv/sftpgo/data/testuser/ubuntu-20.04.3-live-server-amd64.iso","connection_id":"HTTP_c7vv4hl17c4ce965rt70","protocol":"HTTP"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:48.599","sender":"HTTP","connection_id":"HTTP_c7vv4hl17c4ce965rt70","message":"transfer removed, id: 1 active transfers: 0"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:48.599","sender":"HTTP","connection_id":"HTTP_c7vv4hl17c4ce965rt70","message":"connection removed, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:63227\" close fs error: <nil>, num open connections: 0"}
sftpgo    | {"level":"info","time":"2022-02-06T16:07:48.599","sender":"httpd","local_addr":"172.24.11.31:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"192.168.41.40:63227","request_id":"b3ff97fb0193/bZTvLQgflD-000008","uri":"http://192.168.41.1:8080/web/client/file?path=%2F%2Fubuntu-20.04.3-live-server-amd64.iso","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","resp_status":500,"resp_size":113,"elapsed_ms":14090}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:49.114","sender":"HTTP","connection_id":"HTTP_c7vv4ld17c4ce965rt7g","message":"connection added, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:56405\", num open connections: 1"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:07:49.784","sender":"HTTP","connection_id":"HTTP_c7vv4ld17c4ce965rt7g","message":"transfer added, id: 1, active transfers: 1"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:08:03.843","sender":"HTTP","connection_id":"HTTP_c7vv4ld17c4ce965rt7g","message":"uploaded file size 1048576000"}
sftpgo    | {"level":"info","time":"2022-02-06T16:08:03.843","sender":"Upload","local_addr":"172.24.11.31:8080","remote_addr":"192.168.41.40:56405","elapsed_ms":14058,"size_bytes":1048576000,"username":"testuser","file_path":"/srv/sftpgo/data/testuser/ubuntu-20.04.3-live-server-amd64.iso","connection_id":"HTTP_c7vv4ld17c4ce965rt7g","protocol":"HTTP"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:08:03.843","sender":"HTTP","connection_id":"HTTP_c7vv4ld17c4ce965rt7g","message":"transfer removed, id: 1 active transfers: 0"}
sftpgo    | {"level":"debug","time":"2022-02-06T16:08:03.843","sender":"HTTP","connection_id":"HTTP_c7vv4ld17c4ce965rt7g","message":"connection removed, local address \"172.24.11.31:8080\", remote address \"192.168.41.40:56405\" close fs error: <nil>, num open connections: 0"}
sftpgo    | {"level":"info","time":"2022-02-06T16:08:03.843","sender":"httpd","local_addr":"172.24.11.31:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"192.168.41.40:56405","request_id":"b3ff97fb0193/bZTvLQgflD-000009","uri":"http://192.168.41.1:8080/web/client/file?path=%2F%2Fubuntu-20.04.3-live-server-amd64.iso","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","resp_status":500,"resp_size":113,"elapsed_ms":14733}

Network setup: 
Client and Server are in the same subnet. 
172.24.11.31  Docker IP of container 
192.168.41.40  Client 
192.168.41.1   Docker Server 

What is wrong? 
BR Martin

**Comment by drakkan** [comment]
Hi,

1GB is the [default limit](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L232), you can change it changing the config file or using an env var. Please take a look at the docs [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md) for more details

**Comment by drakkan** [comment]
I just did a test by changing the default limit and I was able to upload a 4GB file with no issue, please reopen providing more info if it does not work for you, thanks

**Comment by fengjia126** [comment]
Which parameter of the configuration file is modified? I have the same problem, thank you!

**Comment by asheroto** [comment]
@drakkan the line number changed in your link. What is the new line number for changing the 1GB default limit?

Error Ox800700DF: The file size exceeds the limit allowed and cannot be saved.

Ran into that today and am looking to change the config.

**Comment by drakkan** [comment]
> @drakkan the line number changed in your link. What is the new line number for changing the 1GB default limit?
> 
> Error Ox800700DF: The file size exceeds the limit allowed and cannot be saved.
> 
> Ran into that today and am looking to change the config.

the default is no limit now. The limit was only for the WebClient. It is unlikeky you get that error from the WebClient UI

**Comment by asheroto** [comment]
Ah shoot, I skimmed the issue and didn't read it.

So I'm actually getting that error over WebDAV. I can copy a 300 MB zip file to my WebDAV folder, for instance, but can't copy it back to my computer.

![image](https://github.com/drakkan/sftpgo/assets/49938263/52d46ddb-4d41-4926-be01-113b8e6b0208)

I can create a different issue if you need me to.

I've tried a few files around 30 MB and less and it works fine, not sure what the limit is that breaks it.

Using local storage.

**Comment by asheroto** [comment]
No user quota.

**Comment by drakkan** [comment]
this is a Windows limitation, change you registry setting, is documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/webdav.md)

@asheroto I appreciate you made a small personal donation last year and sold me the certificates I use to sign the Windows binaries, I also think I'll renew them from you when they expire, but please note the [support policy](https://github.com/drakkan/sftpgo#support-policy) has changed compared to the past, I no longer provide free support, Thank you for understanding

**Comment by asheroto** [comment]
Thanks!

No problem, I will make another donation too.

So it's okay to post the issue in the Issues tab, but officially _you_ won't be the one to provide support unless I have a paid support plan, right? Or should one not post in the Issues tab at all? Makes sense - a lot of users now. I'm happy for you that you got some type of paid plan in place. I think we had briefly discussed how you could monetize it. I think charging for support is a good plan as it keeps everything open source.

Just a thought - if you don't already have a bot for the Issues, you could create one easily with Pipedream. I've been using that a lot and love it, they have a ton of integrations.

Let me know when you're ready for the next cert. Looks like the cert expires Nov 2024. I think I gave you the cert at cost or close to it, so that's a small contribution as a special thank you. 😊

**Comment by drakkan** [comment]
> Thanks!
> 
> No problem, I will make another donation too.
> 
> So it's okay to post the issue in the Issues tab, but officially _you_ won't be the one to provide support unless I have a paid support plan, right?

right, as you can see many issues have no answers now or are closed as invalid if they are just support requests and not real bugs.

> Or should one not post in the Issues tab at all? Makes sense - a lot of users now. I'm happy for you that you got some type of paid plan in place. I think we had briefly discussed how you could monetize it. I think charging for support is a good plan as it keeps everything open source.
> 

Let's see if this model works

> Just a thought - if you don't already have a bot for the Issues, you could create one easily with Pipedream. I've been using that a lot and love it, they have a ton of integrations.
> 

I'll give a look, thank you

> Let me know when you're ready for the next cert. Looks like the cert expires Nov 2024. I think I gave you the cert at cost or close to it, so that's a small contribution as a special thank you. blush

I will contact you before November 2024 and buy certificates for another 3 years, thank you!

**Comment by costin3141** [comment]
I just got an error trying to upload a large file using a webdav mount in ubutnu gnome ui. Is sftpgo blocking it or what is the reason here?
