### ISSUE TITLE
sftpgo expose to the internet

### ISSUE THREAD

**Issue by c-erb** [drakkan/sftpgo#711]
I wonder if it would be advisable to expose sftpgo to the internet. I am especially thinking about the webinterface as I am sure that at least exposing the ssh port wouldn't be a problem. But some information about this in general would be helpful.

**Comment by drakkan** [comment]
Hi,

if you are paranoid you can proxy SFTPGo behind nginx or something similar. In general it should be safe to expose the HTTP UI to the internet:

- SFTPGo should not be affected by slowloris style attacks
- CSRF is used

You can also tweak the supported ciphers (this should be done for ssh too). Take a look at the docs and at the following issues for previous discussions about this topic:

https://github.com/drakkan/sftpgo/issues/661
https://github.com/drakkan/sftpgo/issues/316

If you want to contribute an hardening guide it would be appreciated, thanks
