### ISSUE TITLE
FTP passive mode timeout on STOR command

### ISSUE THREAD

**Issue by maximeancellin** [drakkan/sftpgo#714]
Hi,

I would use SFTPGO to use `ftpd` server in passive mode.
I use a default configuration.

But when I try to store a document I have the following error:
```
425 accept tcp [::]:50065: i/o timeout
```

The port is correctly open (checked with netstat)

How to reproduce issue:

1. Configure ftpd server:
```json
  "ftpd": {
    "bindings": [
      {
        "port": 2021,
        "address": "",
        "apply_proxy_config": true,
        "tls_mode": 0,
        "force_passive_ip": "",
        "passive_ip_overrides": [],
        "client_auth_type": 0,
        "tls_cipher_suites": [],
        "passive_connections_security": 0,
        "active_connections_security": 0,
        "debug": false
      }
    ],
    "banner": "",
    "banner_file": "",
    "active_transfers_port_non_20": true,
    "passive_port_range": {
      "start": 50000,
      "end": 50100
    },
    "disable_active_mode": false,
    "enable_site": false,
    "hash_support": 0,
    "combine_support": 0,
    "certificate_file": "",
    "certificate_key_file": "",
    "ca_certificates": [],
    "ca_revocation_lists": []
  },
```
2. Run server
```sh
go run main.go serve
```
3. Create user in web console
4. Use telnet to emulate client
```sh
$ telnet localhost 2021
USER {created user}
PASS {created password}
TYPE I
PASV
STORE file.txt
```

Maybe my configuration is not complete, and if you have any inputs about that, I will very happy to learn how to setup passive mode.

Or it's real bug.

Thanks by advance for your help

**Comment by drakkan** [comment]
Hi,

please try a real FTP client, PASV will return a port to connect to, using telnet you will be unable to connect to that port

**Comment by maximeancellin** [comment]
Hi,

You are right !

Sorry for the disturb.

Thanks
