### ISSUE TITLE
Directories are not created

### ISSUE THREAD

**Issue by dslthomas** [drakkan/sftpgo#716]
Hi there,

I have to ask now. I use Ubuntu 20.04 and installed the sftpgo server via ppa. Unfortunately, no local folders are created when I set up a new user. How can I solve the problem?

Thank you and greetings from Hamburg

**Comment by drakkan** [comment]
Hi,

the local folders are checked/created when the user logins. Are you unable to login? Please post some logs, thanks

**Comment by dslthomas** [comment]
Hi there,
Please excuse the late reply. The problem went away after I rebooted the server. So it must have been a misconfiguration on my part.

**Comment by drakkan** [comment]
No problem, It is strange that a reboot fixed the issue, however I'm glad it works now. The next time please post also some logs so we can better understand what is happeing.

**Comment by dslthomas** [comment]
hmmm, there seems to be an error in the translation. Not restart but new installation. Excuse me, but I have to use the translator.
