### ISSUE TITLE
HA dataprovider?

### ISSUE THREAD

**Issue by ScubaDrew** [drakkan/sftpgo#718]
I'm wondering if there is a way we could leverage cloud storage (I previously moved a mobile gaming companies user data from Cassandra DB to Cloud Storage - don't underestimate this infinitely horizontally scalable datastore) or other cloud-managed databases (DynamoDB, Firestore, BigTable) to get away from the failure points that are involved with Postgres and MySQL. PG and MySQL are more difficult to achieve HA. They require patching and upgrades that often result in downtimes unless run in complex configurations which really add to the overhead of running an FTP server. 

Going a bit further, I realize that running a PG/MySQL instance(s) means monitoring those instances, even if I am leveraging a cloud-managed instance - I still need to keep an eye on disk-space, CPU usage, etc. I need to respond to situations where maybe due to growth we need to scale up the instance, which will need downtime scheduled with FTP users.

**Comment by drakkan** [comment]
Hi,

SFTPGo support [CockroachDB](https://www.cockroachlabs.com/) that is quite simple to scale. 

I think all the cloud managed database that support Postgres or MySQL syntax should work, see for example [here](https://github.com/drakkan/sftpgo/discussions/492#discussioncomment-1804922). 

I'm open to add support for new providers but I need to understand their limit (NoSQL stores could give troubles with object relations)

**Comment by ScubaDrew** [comment]
Hi, I did not realize you supported CockroachDB. Sorry I missed that. I think in this case Google Spanner should also work.

The Google Cloud SQL - both PG and MySQL instance types do have monthly upgrades which can cause downtime. Also, scaling, etc would cause downtime. 

I'll investigate Cockroach / Cloud Spanner. Thank you @drakkan !

**Comment by drakkan** [comment]
Hi, 

CockroachDB works fine, it is tested in the CI pipeline after each commit. 

I don't think that spanner will work, their [database/sql driver](https://github.com/googleapis/go-sql-spanner) for Go is still a work in progres

**Comment by ScubaDrew** [comment]
Very nice, CockroachDB is a very promising product, I am glad you support it. 

I personally can't justify the complexity of setting up a CockroachDB cluster. We are on Google Cloud and I need to only leverage cloud-hosted solutions. My team does not have any expertise in running or maintaining CockroachDB, unfortunately.

Thanks as always @drakkan !

**Comment by drakkan** [comment]
Currently the best choice for your use case seems Cloud SQL for PostgreSQL instance, it should have less than [30 seconds downtime](https://cloud.google.com/sql/docs/postgres/maintenance) during a maintenance window. The SFTPGo dataset should be small even if you have thousands of users.

You are kindly sponsoring the project so I'll give a look at spanner, but adding this support will require some time, hope you understand, thank you

**Comment by drakkan** [comment]
> @drakkan I think we are okay with PG. Sometimes PG has things like right now we have big projects to do v9 -> v13 upgrade. These can be longer downtimes and testing etc...
> 
> Anyway, I don't think you need to look into spanner for me. We'll be okay on PG.
> 

it might be interesting in general. I will queue this activity as low priority

> BTW we use [google-cloud-go](https://github.com/googleapis/google-cloud-go)/spanner/

Yes, this is the currently supported driver and requires writing a new SFTPGo data provider from scratch, this is why I said it requires some time. 

If, instead, a database/sql driver like this [one](https://github.com/googleapis/go-sql-spanner) was stable I could reuse the existing sql code that is shared for postgres, mysql, crdb and sqlite providers. In this case the integration would be almost zero effort. For example to support crdb I just added the code [here](https://github.com/drakkan/sftpgo/blob/main/dataprovider/sqlcommon.go#L2266)
