### ISSUE TITLE
MLSD Close connection

### ISSUE THREAD

**Issue by MyTheValentinus** [drakkan/sftpgo#720]
Hello,

Thanks for your tools. 
I have an error when old FTP client (or Filezilla) connect with FTP protocol to my instance, the connection was closed by server when client launch: `MLSD` command.

I'm using the version 2.2 with docker.

![Capture d’écran 2022-02-15 à 12 47 49](https://user-images.githubusercontent.com/6104498/154056261-27093bdc-f45e-4006-9b0d-5ce5ac6c09c1.png)

Log server only one line: `sftpgo_1  | {"level":"info","time":"2022-02-15T11:48:03.454","sender":"FTP","connection_id":"FTP_0_3","message":"User \"myuser\" logged in with \"password\" from ip \"212.XX.XX.XX\""}`

Thanks

**Comment by MyTheValentinus** [comment]
This due to network error. We need to open port, but dont forget to map to the docker container too for passive port range ! ;)

**Comment by drakkan** [comment]
glad you was able to fix the issue yourself
