### ISSUE TITLE
Force Two-factor auth

### ISSUE THREAD

**Issue by Digl** [drakkan/sftpgo#721]
Hi!
I would like to force enable all users to use mfa.
Is this already possible somehow?
What would be the easiest approach (a hook)?
Use a third party mfa config tool for mfa initialization only?

Br, Matthias

**Comment by drakkan** [comment]
Hi,

this feature is not currently supported. Each user can decide to enable multi-factor authentication.

I could add a new setting to specify protocols that require MFA. Users can log into the web UI but can't do anything until they set up multi-factor authentication. If MFA is required for SSH, users cannot log in via SSH until they set MFA and so on.

I'm now busy working on several requests from project sponsors, this may take a while

**Comment by Digl** [comment]
Hi! That sounds great.
I would highly appreciate it if you could find some time to implement this.

Thank you very much!

**Comment by drakkan** [comment]
This is an interesting feature and sooner or later I will add it but I have a daily job completely unrelated to SFTPGo and therefore I have limited time. 
If someone comes and sponsors another feature, then this development will be postponed. Thanks for understanding

**Comment by Digl** [comment]
I totally understand!
If I would find a sponsor, how would be proceed?

**Comment by drakkan** [comment]
If you can help the project with a [sponsorship](https://github.com/sponsors/drakkan) I'll prioritize this feature otherwise it will happen anyway, since it is a suggestion I like, but with an indefinite schedule

**Comment by drakkan** [comment]
done, but please note that if everyone takes and no one helps the project, SFTPGo will become unsustainable in the long term and you will be forced to switch to another software, probably proprietary and not free :worried:
