### ISSUE TITLE
Sftpgo Phrometheus about Grafana dashboard

### ISSUE THREAD

**Issue by momo8zero** [drakkan/sftpgo#722]
Hello ,I used SFTPGO It's very easy and powerful!!

So I need to monitor it , do you support Grafana dashboard at Phrometheus?

**Comment by drakkan** [comment]
Hi,

you have to enable the `telemetry` endpoint. Prometheus metrics will be available at the `/metrics` URL, take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#telemetry-server)

**Comment by momo8zero** [comment]
Yes, I had Prometheus metrics , and I want use Grafana to monitor it , and I need Grafana dashboard json file , about this

**Comment by drakkan** [comment]
Hi,

this seems unrelated to SFTPGo, it was discussed in the past [here](https://github.com/drakkan/sftpgo/discussions/326), so it should work

**Comment by momo8zero** [comment]
Thank you !
