### ISSUE TITLE
Narrow down container

### ISSUE THREAD

**Issue by Yamakasi** [drakkan/sftpgo#726]
Hi,

Is it possible to narrow down the container so we don't have:

- Adminpanel
- Userpanel
- API
- (External Storage Bakend)

I also wonder if the local host user is really needed as I see various (S)FTP(S) / Chroot solutions which don't.

Thanks for the great work!

**Comment by drakkan** [comment]
Hi,

admin, user UI and API can be disabled at runtime, just remove any HTTP bindings or set the port to `0`. 

External storage backends can be disabled at [build time](https://github.com/drakkan/sftpgo/blob/main/docs/build-from-source.md). 

The local user is not strictly required, we can simply run the container as a non-root user by specifying the ID/GID as we do in the distroless image where there is no utility to create users, but it should not hurt. 
I guess you plan to use the memory provider with a dump file.

The build time for the current docker images is already high, see [here](https://github.com/drakkan/sftpgo/actions/runs/1853923195) and sometime I have to manually restart the builds. 
I don't plan to add other build variants to the GitHub workflows, sorry. 

You can build the docker image yourself to fit your specific use case.

**Comment by Yamakasi** [comment]
Thanks for the quick en detailed reply! It looks like I can perfecly fine with that, thanks a lot! I start building right away!

Can I also remove the UI/API from from the build ? Or will it break things ?

**Comment by drakkan** [comment]
> > EDIT: the distroless image is [13.25 MB](https://hub.docker.com/layers/drakkan/sftpgo/edge-distroless-slim/images/sha256-0cc87b25f73b429a5c2befa0a164f88d323053507fda0816c108bca99974a774?context=explore). We could save a few more MB but does this really matter?
> 
> It's more a personal thing that I like to ditch stuff out that won't be used, that's why roll_eyes

There is nothing wrong with that

**Comment by Yamakasi** [comment]
> > > EDIT: the distroless image is [13.25 MB](https://hub.docker.com/layers/drakkan/sftpgo/edge-distroless-slim/images/sha256-0cc87b25f73b429a5c2befa0a164f88d323053507fda0816c108bca99974a774?context=explore). We could save a few more MB but does this really matter?
> > 
> > 
> > It's more a personal thing that I like to ditch stuff out that won't be used, that's why roll_eyes
> 
> There is nothing wrong with that

I'm really happy you agree! That's why you were able to create great software! 👍
