### ISSUE TITLE
Clarification with blob storage backend

### ISSUE THREAD

**Issue by mike-k0** [drakkan/sftpgo#727]
If using a blob storage backend, does the storage on a container / VM have to have enough disk space to load all the files from the blob storage?

**Comment by mike-k0** [comment]
So if someone is uploading files to the blob storage backend in a separate process (outside of the SFTP server), everything would be fine if someone connects and it lists very large files, as well as if they tried downloading them?

**Comment by drakkan** [comment]
Yes, all is fine expect that SFTPGo does not update the quota usage if you upload files externally. You can periodically call the api to update the quota, see [here](https://github.com/drakkan/sftpgo/tree/main/examples/quotascan) if you need to enforce quotas in SFTPGo

**Comment by drakkan** [comment]
correct, 0 means that you don't want quota enforcement
