### ISSUE TITLE
Issue configuring oidc through sftpgo.json

### ISSUE THREAD

**Issue by pyunramura** [drakkan/sftpgo#728]
Hi. I've been using sftpgo for a few weeks now and it's been working phenomenally. Currently I'm in the process of configuring the oidc section within the sftpgo.json. I should note that sftpgo is running within a docker container using the standard image from ghcr.io/drakkan/sftpgo, but as I needed to make quite a few modifications I decided to copy and edit the config file in lieu of assigning a swath of environment variables. The config is located at /var/lib/sftpgo/sftpgo.json within the container environment, and it was picked up automatically to my surprise. I copied the OIDC section from the documentation, with the resulting json structure as follows:

```
"httpd": {
  "bindings": [
    {
      "port": 8080,
      "address": "",
      "enable_web_admin": true,
      "enable_web_client": true,
      "enable_https": false,
      "client_auth_type": 0,
      "tls_cipher_suites": [],
      "proxy_allowed": [],
      "hide_login_url": 0,
      "render_openapi": true,
      "web_client_integrations": [],
      "oidc": {
        "client_id": "<redacted>",
        "client_secret": "<redacted>",
        "config_url": "https://<redacted>.auth0.com/",
        "redirect_base_url": "https://<redacted>",
        "username_field": "nickname",
        "role_field": ""
      }
    }
  ],
```

I'm using auth0.com as my OIDC provider which may cause problems, but after looking through the logs it seems the entire section is not parsed from the config file at all. Is this due to some misconfiguration on my part? I'm also not seeing any option within the webui to login through OIDC either. I can scrub and submit some logs if needed. Any help would be greatly appreciated.

**Comment by drakkan** [comment]
Hi,

OIDC support was added recently and it is not included in any "stable" release, please try an edge docker variant. If the configuration is parsed successfully you should see an option to login with OpenID Connect on both web admin and web client login screen

**Comment by pyunramura** [comment]
That's likely my issue. I'll give the edge variant a shot and let back to you with any questions. Thanks for the quick reply!

**Comment by pyunramura** [comment]
Alright, it seems that switching to edge was the change needed to get the OIDC section initialized.

Now I'm running into  the following error on the web-ui:

`Unable to parse OpenID token claims: no username field`

with the following log file lines:

```
{"level":"debug","time":"2022-02-21T21:48:12.878","sender":"httpd","message":"unable to parse oidc token claims: no username field"}
{"level":"debug","time":"2022-02-21T21:48:12.878","sender":"httpd","message":"oidc: provider logout URL not set, unable to logout from the OP"}
```

here is the openid-configuration provided by auth0 at https://<redacted>.auth0.com/.well-known/openid-configuration

```
issuer | "https://<redacted>.auth0.com/"
authorization_endpoint | "https://<redacted>.auth0.com/authorize"
token_endpoint | "https://<redacted>.auth0.com/oauth/token"
device_authorization_endpoint | "https://<redacted>.auth0.com/oauth/device/code"
userinfo_endpoint | "https://<redacted>.auth0.com/userinfo"
mfa_challenge_endpoint | "https://<redacted>.auth0.com/mfa/challenge"
jwks_uri | "https://<redacted>.auth0.com/.well-known/jwks.json"
registration_endpoint | "https://<redacted>.auth0.com/oidc/register"
revocation_endpoint | "https://<redacted>.auth0.com/oauth/revoke"
scopes_supported |  
    0 | "openid"
    1 | "profile"
    2 | "offline_access"
    3 | "name"
    4 | "given_name"
    5 | "family_name"
    6 | "nickname"
    7 | "email"
    8 | "email_verified"
    9 | "picture"
    10 | "created_at"
    11 | "identities"
    12 | "phone"
    13 | "address"
response_types_supported |  
    0 | "code"
    1 | "token"
    2 | "id_token"
    3 | "code token"
    4 | "code id_token"
    5 | "token id_token"
    6 | "code token id_token"
code_challenge_methods_supported |  
    0 | "S256"
    1 | "plain"
response_modes_supported |  
    0 | "query"
    1 | "fragment"
    2 | "form_post"
subject_types_supported |  
    0 | "public"
id_token_signing_alg_values_supported |  
    0 | "HS256"
    1 | "RS256"
token_endpoint_auth_methods_supported |  
    0 | "client_secret_basic"
    1 | "client_secret_post"
claims_supported |  
    0 | "aud"
    1 | "auth_time"
    2 | "created_at"
    3 | "email"
    4 | "email_verified"
    5 | "exp"
    6 | "family_name"
    7 | "given_name"
    8 | "iat"
    9 | "identities"
    10 | "iss"
    11 | "name"
    12 | "nickname"
    13 | "phone_number"
    14 | "picture"
    15 | "sub"
request_uri_parameter_supported | false
```

 I made it further at least!

I've tried changing the `username_field` from `nickname` to `name` with no success.

Any idea where to go from here?

**Comment by drakkan** [comment]
Based on the auth0 docs, I think that these fields are missing because auth0 seems to return them only if the application specify the `profile` scope:

https://auth0.com/docs/get-started/apis/scopes/sample-use-cases-scopes-and-claims
https://auth0.com/docs/secure/tokens/json-web-tokens/create-namespaced-custom-claims

and currently SFTPGo requests only the (mandatory) `openid` scope. I need some time to understand what is the best way to handle, this I could:

1) hardcode the `profile` scope
2) make additional scopes configurable

**Comment by drakkan** [comment]
Please retry using the latest edge image once [CI completes](https://github.com/drakkan/sftpgo/actions/runs/1880672039) and reopen the issue if it still does not work.

I think we don't need another setting, now we always add the profile and email scope to oauth2 requests. I think keycloack should not return username and email field if only the `openid` scope is requested but maybe it has some valid reason to do so.

From your logs I noticed that auth0 does not support the [frontchannel logout](https://openid.net/specs/openid-connect-frontchannel-1_0.html) feature. This means that once you logout from SFTPGo the token will not be invalidated and so if you click "Login with OpenID" again you will be logged in directly without requesting the credentials, this will make very difficult to switch user

**Comment by pyunramura** [comment]
# How to authorize sftpgo via OpenID Connect using the auth0.com provider

## Note: This assumes you have:

Have a created and working auth0 account

Already created an "app" specific to sftpgo

Have the "Client ID" and "Client Secret" for the sftpgo app

### Filling sftpgo Login URI / Allowed Callback URLs / Logout URLs / Web Origins

(Section WIP)

### Setting up custom claims to map sftpgo users to auth0 users

From atuh0 website:

On the left bar select "User Management" > "Users"

For each user you want mapped to an sftpgo user:

Select the user you want mapped to an **already created** sftpgo user.

Scroll to "app_metadata"

Between the curly brackets enter the "preferred_username" and "user_role" fields like so:

```
{
  "preferred_username": "your_sftpgo_username",
  "user_role": "user"
}
```

Should look like so:

![7](https://user-images.githubusercontent.com/35285259/155112782-4ab8dea4-7a3d-4f78-bf55-028232752f28.png)

Click "Save"

On the left bar select "Actions" > "Library"

Select "Build Custom" button at the top right

Fill the action name with something descriptive. I chose `sftpgo preferred_username user_role claims`

Make sure "Login / Post Login" is selected under "Triggers"

Select the "Create" button

In the text field, erase the pre-populated contents

Paste the code block shown below; be sure to specify a proper namespace under the "const namespace" variable:

```
exports.onExecutePostLogin = async (event, api) => {
  const namespace = 'https://sftpgo.your_website.com';
  const { preferred_username, user_role } = event.user.app_metadata;

  if (event.authorization) {
    // Set claims 
    api.idToken.setCustomClaim(`${namespace}/preferred_username`, preferred_username);
    api.idToken.setCustomClaim(`${namespace}/user_role`, user_role);
  }
};
```

Should look like so:

![4](https://user-images.githubusercontent.com/35285259/155112881-fddf43db-92ae-48dd-9c32-fc04855c8c33.png)

Select "Deploy"

On left bar select "Actions" > "Flows"

Select the "Login" flow

On the right side "Add Action" menu select "Custom". Your created flow 'sftpgo preferred_username user_role claims' should appear.

Click and drag the 'sftpgo preferred_username user_role claims' block between the "Start" and "Complete". In my case it was after the "Rules (Legacy)" block.

Should look like so:

![8](https://user-images.githubusercontent.com/35285259/155113015-7df61b2f-7a46-4eda-9719-86a4766e2894.png)

Select the "Apply" button on the top right.

Now, edit the sftpgo.json config file (or use env vars) paste the following code block in the "httpd" > "bindings" section; making sure to substitute for the proper values from your auth0 application.

```
"oidc": {
    "client_id": "your_auth0_app_client_id",
    "client_secret": "your_auth0_app_client_secret",
    "config_url": "https://example.auth0.com/",
    "redirect_base_url": "https://sftpgo.your_website.com",
    "username_field": "https://sftpgo.your_website.com/preferred_username",
    "role_field": "https://sftpgo.your_website.com/user_role"
}
```

Save the file and reload the instance. On the web-ui you should see a "Login with OpenID" button below the "Login" button, which will redirect you to your auth0 page for login. Once logged in, it should return you to your sftpgo admin/client page.

**Comment by pyunramura** [comment]
> Please retry using the latest edge image once [CI completes](https://github.com/drakkan/sftpgo/actions/runs/1880672039) and reopen the issue if it still does not work.

I will give it a go. Thanks for the help!

> I think we don't need another setting, now we always add the profile and email scope to oauth2 requests. I think keycloack should not return username and email field if only the `openid` scope is requested but maybe it has some valid reason to do so.
> 
> From your logs I noticed that auth0 does not support the [frontchannel logout](https://openid.net/specs/openid-connect-frontchannel-1_0.html) feature. This means that once you logout from SFTPGo the token will not be invalidated and so if you click "Login with OpenID" again you will be logged in directly without requesting the credentials, this will make very difficult to switch user

That indeed could be an issue. I'm not sure if I'll have problems in practice or not (typically I log in my admin user in a private window), but for other users it very well may be a deal-breaker. Thank you for the heads up!

**Comment by drakkan** [comment]
Thank you for the tutorial!

I think the latest edge variant should work as expected, the id_token should contain the nickname field now since I added `profile` to the oauth2 scopes. 

The tutorial is still useful because it explains how to set a custom field that is required to map admin users, thanks!

**Comment by pyunramura** [comment]
Of course, and I'm glad to help wherever I can, even if it's simply documentation. Hopefully anyone else running into the same issue find the tutorial helpful. And thank you so much for this wonderful project!

**Comment by drakkan** [comment]
Hi,

after testing the latest version, if all work as expected and you have enough free time you could send a PR for your tutorial so we can add it in the [howto section](https://github.com/drakkan/sftpgo/tree/main/docs/howto). No obligations of course. Thanks
