### ISSUE TITLE
Can't upgrade to 2.2 -- "could not start SFTP server: unsupported key-exchange algorithm "diffie-hellman-group18-sha512"

### ISSUE THREAD

**Issue by ScubaDrew** [drakkan/sftpgo#731]
We lost some kex that we had in use. Maybe we should not be using them?

```
"kex_algorithms": [
      "curve25519-sha256@libssh.org",
      "diffie-hellman-group18-sha512",
      "diffie-hellman-group16-sha512",
      "diffie-hellman-group14-sha256",
      "ecdh-sha2-nistp256",
      "ecdh-sha2-nistp384",
      "ecdh-sha2-nistp521"
    ],
```

**Comment by drakkan** [comment]
Hi,

these KEXs are not supported in `golang/crypto/ssh`. We accepted any value in previous versions, but this could cause crashes if clients used one of the unsupported algorithms, see for example [here](https://github.com/drakkan/sftpgo/issues/661#issuecomment-1005622091). So I explictly documented the supported algos and I added a check to validate them. The supported values are documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md). We support the following KEXs:  `curve25519-sha256@libssh.org`, `ecdh-sha2-nistp256`, `ecdh-sha2-nistp384`, `ecdh-sha2-nistp521`, `diffie-hellman-group14-sha1`, `diffie-hellman-group1-sha1`. Default values are: `curve25519-sha256@libssh.org`, `ecdh-sha2-nistp256`, `ecdh-sha2-nistp384`, `ecdh-sha2-nistp521`, `diffie-hellman-group14-sha1`.

Also take  a look [here](https://github.com/golang/crypto/blob/master/ssh/kex.go#L22).

**Comment by ScubaDrew** [comment]
Thank you @drakkan for keeping us from running into an issue! 

Hopefully they add `diffie-hellman-group14-sha256` soon.

![image](https://user-images.githubusercontent.com/18055237/155237753-0dfe6f15-9382-4875-af25-9eb8f6af92ec.png)

**Comment by drakkan** [comment]
I'll read the specs, if the only difference is the hash method I'll add it myself. We already use a golang/crypto [fork](https://github.com/drakkan/crypto/commits/sftpgo) which add support for some ciphers and macs that are trivial to implement.

Unfortunately upstream is quite irresponsive about these things. For example I submitted a patch to add multi-step authentication support years ago and still haven't received a comment. I also tried to contact @FiloSottile directly with no luck

**Comment by drakkan** [comment]
Take a look [here](https://github.com/golang/crypto/pull/206). I tested locally and it works fine. I'll wait a bit to see if it can be included upstream, otherwise I'll add this patch to the crypto fork used in SFTPGo

**Comment by ScubaDrew** [comment]
@drakkan Thank you for the detailed work on this. Let's hope they will review and merge. It is not urgent from my end, so we can give them some time and avoid using a fork.

**Comment by drakkan** [comment]
I also added group-16-sha512 and group-18-sha512, so all the KEXs listed in your configuration above should be supported. 

Now we just have to wait ...
