### ISSUE TITLE
AWS Container Marketplace option

### ISSUE THREAD

**Issue by kyanar** [drakkan/sftpgo#732]
I'm deploying SFTPGo currently as an EC2 AMI, but I'd be super keen to drop the unnecessary instances and shift to containers all the way, are there plans to offer SFTPGo on the AWS Marketplace in container deployment format for use with EKS and ECS?

**Comment by drakkan** [comment]
Hi,

I'll explore this option, thank you for the suggestion

**Comment by drakkan** [comment]
Hi,

for your usage is a container image enough or do you need an helm chart? Thanks

**Comment by kyanar** [comment]
Hi there, either option works. I like Helm charts, but I can just as easily build those myself for our environment. Thanks for looking into this option!

**Comment by drakkan** [comment]
Ok, I have read the AWS requirements and instructions, I need to make some code changes to integrate the AWS Measurement Service and then I will start the submission process. This may take a few weeks, the approval process requires several steps, it was quite long also for the AMI images. 

I'll start with a container image that looks like the simplest option. If other users are interested in this delivery method I will try to add an helm chart in the future. Thanks again for this suggestion

**Comment by drakkan** [comment]
it's taking forever sorry, I'm trying to solve some issues with the help of the AWS support

**Comment by drakkan** [comment]
Hi,

sorry for the long delay. A first version is now available

https://aws.amazon.com/marketplace/pp/prodview-lz2dadhmmi57w

this version supports x86_64 images (both distroless and full variants). I will be adding an ARM64 based image in the next few days. AWS does not support multiple architectures for the same container product. I started a new product submission. Thanks for your patience

**Comment by drakkan** [comment]
I give up. I'm in an endless loop with the AWS marketplace support. I got no-sense replies like this:

> Amd64 and arm64 images are not supported. You must use image built for specific environment for example Linux with x86 or Linux with ARM.

ECR accepts just fine manifests and arm64 images, but when I try to add them as new version the marketplace fails the scan or refuses the manifest format (I'm using v2-2, v2-1 is deprecated)

![Schermata del 2022-04-21 12-50-03](https://user-images.githubusercontent.com/553263/164708496-6aec8cec-8590-42de-a100-4ad4c7469914.png)

![Schermata del 2022-04-22 12-35-45](https://user-images.githubusercontent.com/553263/164708520-889eae2d-4a7c-435c-bc42-30de9cc34734.png)

**Comment by drakkan** [comment]
arm64 container is now available

https://aws.amazon.com/marketplace/pp/prodview-7jqer6rxpc7qw

thanks for your patience
