### ISSUE TITLE
Cache External Authentications

### ISSUE THREAD

**Issue by kyanar** [drakkan/sftpgo#733]
External authentications currently reach out to hit the external data source for every authentication. For some backends, this might be a bit aggressive, and we might be perfectly happy to accept that a user deactivation may not be immediate.

Would it be possible to provide an option to cache external authentication results and permit successful user and password combinations to be reused for future authentication attempts without a remote backend hit? I assume this would mean the locally created user would have to have the password saved when they are created.

This would also allow an administrator to opt to keep the service available when backend auth is unavailable, at least for existing users.

**Comment by drakkan** [comment]
Hi,

currently you can just examine the existing user you receive in your external auth hook and return an empty response (without hitting your auth provider) if you  don't want to modify it.

However, I could also add an option in SFTPGo to not call the external hook at all, something like external_users_cache_time or similar. Please give me a few days to think about it. Thank you

**Comment by the-maldridge** [comment]
What about adding an optional field to the data that is returned from the provider that is an indication of how long the provider says the value is good for?  This would be in line with the way other cache architectures such as that in HTTP work and would enable the provider to allow less critical accounts to be cached longer than accounts with access to more sensitive data.
