### ISSUE TITLE
CoreFTP is not able to not connect using SFTP

### ISSUE THREAD

**Issue by hkadim** [drakkan/sftpgo#735]
Cannot connect using coreFTP http://www.coreftp.com/download.html.

This may be a coreFTP issue but using it I can connect to other SFTP servers (like 1and1) without issues.

![image](https://user-images.githubusercontent.com/32095451/155508469-082feccc-d2dd-437b-88c8-ba4897f3cef7.png)

**Comment by drakkan** [comment]
the latest release seems from 2011

http://www.coreftp.com/news.html

please try to enable some old MACs/KEXs/ciphers that are disabled by default. Please search for ciphers [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

**Comment by drakkan** [comment]
It works for me with the default configuration

![Schermata del 2022-02-24 11-56-52](https://user-images.githubusercontent.com/553263/155511717-36440cd2-7ccf-4aed-9398-a2d741b1b7eb.png)

I just downloaded the latest free version

**Comment by hkadim** [comment]
Thank you for the prompt response.
My problem is that all clients can connect without any issues, only CoreFTP is failing.
BTW => the last CoreFTP Version 2.2 (build 1960), updated Sep 28th, 2020 http://www.coreftp.com/forums/viewtopic.php?t=4023051
I noticed that I still have the sftpgo version SFTPGo 1.2.2-37fc589-2020-11-18T18:33:47Z
I am going to install the sftpgo last version.

**Comment by drakkan** [comment]
to preserve your SFTPGo data you have to upgrade in multiple steps, take a look [here](https://github.com/drakkan/sftpgo#upgrading):

- 1.2.x => 2.0.4
- 2.0.4 => 2.1.2
- 2.1.2 => 2.2.2

**Comment by drakkan** [comment]
This seems to work with recent versions, please re-open if you still have issue after updating SFTPGo, thanks
