### ISSUE TITLE
Using port 22 for SFTP.

### ISSUE THREAD

**Issue by chetanmadaan** [drakkan/sftpgo#737]
Hello,

I am trying to use port 22 for the SFTP setup. However, following the directions https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md#binding-to-privileged-ports didn't help.

Is it possible to use port 22 as default for SFTP?

Thanks,
Chetan

**Comment by drakkan** [comment]
Hi,

it works fine, this was discussed several times in the past, you must be sure that no other service is already listening on port 22 (OpenSSH listens by default on this port) and follow the istructions you linked above.

Also take a look [here](https://github.com/drakkan/sftpgo/issues/693) it is the same issue but for port 21

**Comment by chetanmadaan** [comment]
Yes, Thank you. It works.

Here is documentation on how to get sshd service off port 22.
https://gist.github.com/tusharf5/89a094de01321880fdf44bf1d4e4ea4c
