### ISSUE TITLE
Feature request: SSH tunneling

### ISSUE THREAD

**Issue by helmut72** [drakkan/sftpgo#738]
Would be cool to allow SSH tunneling too. Restrictions could be solved like adding virtual folders to a user, but for tunneling there are no folders but rule sets to different destinations, eg. to ip addresses, to a network range, to different tcp ports.

This saves another TCP port running on the same  public IP or on a different public IP on TCP 22 and remote management is at one place.

Thank you.

**Comment by drakkan** [comment]
Hi,

I don't plan to add this feature in the near future, sorry. The maintenance burden is increasing rapidly and I need more sponsors to have enough free time for the project

**Comment by helmut72** [comment]
Hello Nicola, yes, take your time for stabilization of the current features first. It was just an idea while trying RPort, a management for remote tunnels.

**Comment by helmut72** [comment]
sftpgo is about files
