### ISSUE TITLE
Banned host doesn't show up in Defender Tab

### ISSUE THREAD

**Issue by sangyye** [drakkan/sftpgo#742]
Hello,

I use this version of sftpgo:
```
SFTPGo 2.2.1-794afbf8-2021-12-31T13:26:00Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
```

Currently I using sftpgo and I have a Monitoring Services to watch that the ssh port is available, and this worked fine for a time. Sadly the node was now added to the banlist:
```
{"level":"debug","time":"2022-02-25T13:29:55.845","sender":"SSH","message":"connection refused, ip \"192.168.7.2\" is banned"}
```
But it was not showing up in the webinterface on the Defender Tab, but it has an entry in the Postgresql Database:
```
sftp=# select * from defender_hosts;
 id |       ip       |   ban_time    |  updated_at
----+----------------+---------------+---------------
  1 | 192.168.7.2 | 1645859931493 | 1645859031493
```
and also in the Defender Events
```
sftp=# select * from defender_events;
  id  |   date_time   | score | host_id
------+---------------+-------+---------
 8179 | 1645781148817 |     2 |       1
 8180 | 1645781448749 |     2 |       1
 8181 | 1645781752903 |     2 |       1
 8182 | 1645782056286 |     2 |       1
 8183 | 1645782359496 |     2 |       1
 8184 | 1645782663402 |     2 |       1
 8185 | 1645782965074 |     2 |       1
 8186 | 1645783266442 |     2 |       1
 8187 | 1645783567835 |     2 |       1
 8188 | 1645783868509 |     2 |       1
 8189 | 1645784171432 |     2 |       1
 8190 | 1645784290077 |     2 |       1
 8191 | 1645784589482 |     2 |       1
 8192 | 1645784890976 |     2 |       1
 8193 | 1645785191358 |     2 |       1
 8194 | 1645785231487 |     2 |       1
 8172 | 1645779038700 |     2 |       1
 8173 | 1645779338614 |     2 |       1
 8174 | 1645779639188 |     2 |       1
 8175 | 1645779942678 |     2 |       1
 8176 | 1645780246259 |     2 |       1
 8177 | 1645780547833 |     2 |       1
 8178 | 1645780847803 |     2 |       1
(23 rows)
```

As I cannot remove the host from the banlist via the webinterface I tried to add the Host to the allow list but that didn't help either. The Host is still blocked, can I remove the entries in the database to get my host to reach the sftpgo instance again or would that messing something up?

Thanks in advance.

**Comment by drakkan** [comment]
Hi,

how many banned hosts do you have in your database? The query is limited to the configured [entries_hard_limit](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L31). 

However manually removing the IP from the banlist is not the solution, you should add it to the safelist. Please check the docs [here](https://github.com/drakkan/sftpgo/blob/main/docs/defender.md). If you think that the docs could be improved a PR is welcome. Thanks

**Comment by sangyye** [comment]
Hi,

thanks for answering, I only have this one host in the database, I haven't shortend the output, that is everything in it.
Also I added the Host to the safelist but it is still being blocked, it seems to me that the entry in the database takes preference before the safelist. As I'm not seeing anything in the webinterface, I was asking if i can just remove the entries in the database or if this will mess something up?

**Comment by drakkan** [comment]
Can you please search for this [log](https://github.com/drakkan/sftpgo/blob/main/common/defender.go#L268)?

**Comment by sangyye** [comment]
Yes, for me it looks like this
```
{"level":"info","time":"2022-02-25T13:57:00.547","sender":"common","message":"list \"/etc/sftpgo/defender/safelist\" loaded, ip addresses loaded: 4/4 networks loaded: 3/3"}
```

**Comment by drakkan** [comment]
I cannot reproduce

```
sftpgo.db=# insert into defender_hosts (ip,ban_time,updated_at) values('192.168.7.2',1645859931493,1645859031493);
INSERT 0 1
sftpgo.db=# select * from defender_hosts;
 id |     ip      |   ban_time    |  updated_at   
----+-------------+---------------+---------------
  6 | 192.168.7.2 | 1645859931493 | 1645859031493
(1 riga)
```

and I can see the banned host
![Schermata del 2022-02-25 17-22-18](https://user-images.githubusercontent.com/553263/155750301-18919789-c19e-4171-a5fc-e106ede395fd.png)

**Comment by sangyye** [comment]
Do you use chrome? Because I was using firefox and not seeing anything now I have tried the chrome browser and the entry is there. That is strange. I will check what is different there, but thanks a lot, that has already helped me.

**Comment by drakkan** [comment]
> Do you use chrome? Because I was using firefox and not seeing anything now I have tried the chrome browser and the entry is there. That is strange. I will check what is different there, but thanks a lot, that has already helped me.

Yes I use chromium, but I can see the hosts also in firefox.

However the safelist don't allow to add new host events. If the host is already banned you have to delete it from the web admin or from the database.

Now that it is in the safelist no more events will be generated and so it cannot be banned anymore

**Comment by sangyye** [comment]
Okay, it seems that is was something in my Firefox setup, I will have to check that. But thanks that solved my problem and now everything is working like expecting. Thanks a lot.

**Comment by drakkan** [comment]
This is likely the same issue as #759 and should be fixed now
