### ISSUE TITLE
Readdir errors for gcs vfs because of context timeouts

### ISSUE THREAD

**Issue by kirecek** [drakkan/sftpgo#746]
Hello,

I noticed we cannot list files in case google bucket contains a huge amount of files.

```
sftp> ls
remote readdir("<path>"): Failure
```

The reason is context timeout which is statically set to 30 seconds here: https://github.com/drakkan/sftpgo/blob/f5a0559be6f48e2f0cbe0c9c09937b0c2f7f4095/vfs/gcsfs.go#L70

So I am wondering if it does make sense to take any action here like change readdir mechanism (no idea yet) or at least make timeouts configurable? WDYT?

Thank you :)

**Comment by drakkan** [comment]
Hi,

we need an upper limit to avoid waiting forever, maybe we could use the ctxLongTimeout (5 minutes), but if listing a directory takes that long the system is pretty unusable. Just to get an idea how many files do you have in this "directory"?

**Comment by kirecek** [comment]
> Just to get an idea how many files do you have in this "directory"?

Hehe, with time it grew pretty big because we are keeping objects forever. It's over half a million files that take cca ~2 minutes to list.

I agree that waiting that much time is not very user-friendly (luckily `ls` is not a very common operation) but also settings limits for clients do not seem right hence the question/issue to check if it would make sense to "fix" it in sftpgo.

Pagination sounds good. Basically, information about pages is already present in the [object iterator](https://pkg.go.dev/cloud.google.com/go/storage#ObjectIterator) so maybe using LongTimeout for entire thing and short 30s timeout per API call would not be a bad thing?

**Comment by drakkan** [comment]
> > Just to get an idea how many files do you have in this "directory"?
> 
> Hehe, with time it grew pretty big because we are keeping objects forever. It's over half a million files that take cca ~2 minutes to list.
> 
> I agree that waiting that much time is not very user-friendly (luckily `ls` is not a very common operation)

it depends, if you use a client like FileZilla it sends a list dir command after the initial connection and after each upload, so uploading 10 small files with a client like this will take forever :smile: Also the SFTPGo web client does not work well with huge file lists.

But probably you use SFTPGo in a different way.

> but also settings limits for clients do not seem right hence the question/issue to check if it would make sense to "fix" it in sftpgo.
> 
> Pagination sounds good. Basically, information about pages is already present in the [object iterator](https://pkg.go.dev/cloud.google.com/go/storage#ObjectIterator) so maybe using LongTimeout for entire thing and short 30s timeout per API call (page) would not be a bad thing?

We don't need the long timeout, a 30 seconds timeout for each page is enough. I recently refactored azure blob vfs to use their new SDK and now list dir works exactly that way.

The change shouldn't be that hard and I will try to do it, however I don't feel very motivated, you are paying for the storage and the rest and you are not helping the SFTPGo project :cry:
