### ISSUE TITLE
Proxy Protocol Enabled

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#747]
```
          - name: SFTPGO_COMMON__PROXY_PROTOCOL
            value: '1'
          - name: SFTPGO_COMMON__PROXY_ALLOWED
            value: '10.0.0.0/8'
```

When enabling this on 'v2.2.1' , i get timeouts with SFTP. The service seems to run, but nothing can connect.

Here are the logs:
```
{"level":"debug","time":"2022-03-04T07:26:40.472","sender":"sftpd","message":"enabled SSH commands [md5sum sha1sum cd pwd scp]"}
{"level":"info","time":"2022-03-04T07:26:40.478","sender":"sftpd","message":"server listener registered, address: 0.0.0.0:2022"}
{"level":"debug","time":"2022-03-04T07:26:40.478","sender":"httpd","message":"initializing HTTP server with config {Bindings:[{Address: Port:8080 EnableWebAdmin:true EnableWebClient
:true EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[] ProxyAllowed:[] HideLoginURL:0 RenderOpenAPI:true WebClientIntegrations:[] allowHeadersFrom:[]}] TemplatesPath:/usr/share
/sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static BackupsPath:/sftp/sftpgo/backups OpenAPIPath:/usr/share/sftpgo/openapi WebRoot: CertificateFile: CertificateKeyFil
e: CACertificates:[] CARevocationLists:[] SigningPassphrase:[redacted] MaxUploadFileSize:1048576000 Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] All
owCredentials:false Enabled:false MaxAge:0}}"}
```

From the debug messages i cannot see that the proxy-protocol was applied?

Further more, we are doing a healthcheck from the proxy to the sftpd - just a basic TCP connection.. when i do enable debug.. we see a lot of these

```
{"level":"debug","time":"2022-03-04T07:26:41.970","sender":"connection_failed","client_ip":"10.42.97.1","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}
{"level":"debug","time":"2022-03-04T07:26:42.013","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
{"level":"debug","time":"2022-03-04T07:26:42.013","sender":"connection_failed","client_ip":"10.42.10.128","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}
{"level":"debug","time":"2022-03-04T07:26:42.048","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
```

When the proxy-protocol flags are enabled, it seems the healthchecks are logged but on the load-balancer, they are marked as unhealthy.. so it seems like the healthchecks aren't getting through.

**Comment by drakkan** [comment]
what proxy are you using? Please also post some SFTPGo logs otherwise I can only guess

**Comment by ryjogo** [comment]
@drakkan Sorry, took a while to get the logs..  So i think its something to do with the proxy allowed, a the loadbalancer sees the serves as offline, hence why we cannot connect. When we remove the proxy allowed, the healthchecks are OK

**Comment by drakkan** [comment]
strange. I just tested this configuration with haproxy

```
 "proxy_protocol": 1,
 "proxy_allowed": ["192.168.1.0/24"],
```

haproxy connects from localhost so the proxy header is ignored.

Here is the relevant haproxy config:

```
server sftpgo1 127.0.0.1:2022 check send-proxy-v2 weight 10 inter 5s rise 2 fall 3
```

and it works as expected. I can connect to SFTPGo using the proxy.

If I set `proxy_protocol` to 2 then the connection is not accepted as expected.

You should understand the interation between your proxy and SFTPGo. I have no other idea sorry

**Comment by drakkan** [comment]
> ```
>           - name: SFTPGO_COMMON__PROXY_PROTOCOL
>             value: '1'
>           - name: SFTPGO_COMMON__PROXY_ALLOWED
>             value: '10.0.0.0/8'
> ```
> 
> When enabling this on 'v2.2.1' , i get timeouts with SFTP. The service seems to run, but nothing can connect.
> 
> Here are the logs:
> 
> ```
> {"level":"debug","time":"2022-03-04T07:26:40.472","sender":"sftpd","message":"enabled SSH commands [md5sum sha1sum cd pwd scp]"}
> {"level":"info","time":"2022-03-04T07:26:40.478","sender":"sftpd","message":"server listener registered, address: 0.0.0.0:2022"}
> {"level":"debug","time":"2022-03-04T07:26:40.478","sender":"httpd","message":"initializing HTTP server with config {Bindings:[{Address: Port:8080 EnableWebAdmin:true EnableWebClient
> :true EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[] ProxyAllowed:[] HideLoginURL:0 RenderOpenAPI:true WebClientIntegrations:[] allowHeadersFrom:[]}] TemplatesPath:/usr/share
> /sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static BackupsPath:/sftp/sftpgo/backups OpenAPIPath:/usr/share/sftpgo/openapi WebRoot: CertificateFile: CertificateKeyFil
> e: CACertificates:[] CARevocationLists:[] SigningPassphrase:[redacted] MaxUploadFileSize:1048576000 Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] All
> owCredentials:false Enabled:false MaxAge:0}}"}
> ```
> 
> From the debug messages i cannot see that the proxy-protocol was applied?
> 
> Further more, we are doing a healthcheck from the proxy to the sftpd - just a basic TCP connection.. when i do enable debug.. we see a lot of these
> 
> ```
> {"level":"debug","time":"2022-03-04T07:26:41.970","sender":"connection_failed","client_ip":"10.42.97.1","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}
> {"level":"debug","time":"2022-03-04T07:26:42.013","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
> {"level":"debug","time":"2022-03-04T07:26:42.013","sender":"connection_failed","client_ip":"10.42.10.128","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"EOF"}
> {"level":"debug","time":"2022-03-04T07:26:42.048","sender":"sftpd","message":"failed to accept an incoming connection: EOF"}
> ```
> 
> When the proxy-protocol flags are enabled, it seems the healthchecks are logged but on the load-balancer, they are marked as unhealthy.. so it seems like the healthchecks aren't getting through.


I see similar logs here:

```
{"level":"debug","time":"2022-03-04T09:16:07.334","sender":"sftpd","message":"failed to accept an incoming connection: read tcp 127.0.0.1:2022->127.0.0.1:37296: read: connection reset by peer"}
{"level":"debug","time":"2022-03-04T09:16:07.334","sender":"connection_failed","client_ip":"127.0.0.1","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"read tcp 127.0.0.1:2022->127.0.0.1:37296: read: connection reset by peer"}
```

but haproxy reports that the backend is up as expected.

If the proxy is not allowed to send the proxy headers I have logs like these ones:

```
{"level":"debug","time":"2022-03-04T09:19:27.432","sender":"connection_failed","client_ip":"127.0.0.1","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"proxyproto: upstream connection sent PROXY header but isn't allowed to send one"}
```

the backend is still alive and I can connect, the proxy header is ignored.

Try to investigate on the proxy side

**Comment by ryjogo** [comment]
Thanks, I will investigate further

**Comment by drakkan** [comment]
I guess you have a load balancer like AWS, take a look [here](https://github.com/pires/go-proxyproto#aws)

**Comment by drakkan** [comment]
please reopen providing more info, I think this is a loadbalancer configuration issue
