### ISSUE TITLE
Feature Request: add some TAG to s3 object

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#748]
Hi, it would be interesting to be able to tag files transferred using s3 type storage. For example the source ip and the username of the transferred files.

thank you.

f.

**Comment by drakkan** [comment]
Hi,

the feature is quite generic and requires a high level of configurability. If I add something like this, I'm sure other users will request different tags.

The maintenance burden is increasing rapidly and I need more sponsors to have enough free time for the project. 

I am starting to prioritize requests from project sponsors or those that I find technically interesting. I don't plan to add this feature in the near future, sorry.
