### ISSUE TITLE
How to install sftpGO with Traefik

### ISSUE THREAD

**Issue by WiFEED** [drakkan/sftpgo#751]
Hello, I would like to install SftpGO with Traefik, the problem is that it does not work,

I access the dashboard without problem but when I connect with Filezilla in SFTP it doesn't work and I really don't understand why...?

My configuration : 

traefik.yml
![image](https://user-images.githubusercontent.com/101096113/157002441-74231645-c7f6-4753-90ed-57e0c3b5a9df.png)

docker-compose.yml

`version: '3.3'
services:

  ftp:
    container_name: ftp
    image: drakkan/sftpgo:edge-alpine-slim
    networks:
           network-traefik:
              ipv4_address: 192.168.128.xxx
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ftp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.ftp.entrypoints=sftp" 
      - "traefik.tcp.services.ftp.loadbalancer.server.port=2022"
      - "traefik.http.routers.uiftp.rule=Host(`MYDOMAIN.FR`)"
      - "traefik.http.routers.uiftp.entrypoints=https"
      - "traefik.http.routers.uiftp.tls.certresolver=http"
      - "traefik.http.services.uiftp.loadbalancer.server.port=8080"
 
networks:
   network-traefik:
       external: **true`**

I'm really stuck help me! :D

**Comment by drakkan** [comment]
Hi,

I'm not familiar with Traefik sorry, (I tested haproxy and it works well), 

maybe this link could help

https://www.georglutz.de/blog/2020/06/20/homeassistant-with-traefik-and-ssh/

**Comment by WiFEED** [comment]
I'm really unlucky! I have already followed this tutorial but it doesn't work either..

Sftpgo, Container logs don't tell me I'm trying to connect to port 2222, 

There is no modification to make in the configuration file of sftpgo? to say that I am using a reverse proxy?

**Comment by puntopaz** [comment]
There was another user who claimed it works behind Traefik, and shared the configuration settings: https://github.com/drakkan/sftpgo/discussions/434.
Maybe checking your settings against his/hers will help you

**Comment by drakkan** [comment]
> Thank you for this quick feedback!
> 
> Ohh... I'm really unlucky! I have already followed this tutorial but it doesn't work either.. Sftpgo, Container logs don't tell me I'm trying to connect to port 2222, There is no modification to make in the configuration file of sftpgo? to say that I am using a reverse proxy?
> 

It should work with no modifications. 

If traefik is able to send a proxy header as documented [here](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt), you have also to configure the proxy protocol in SFTPGo.

Using the proxy protocol you will see the real client IP, without proxy configuration all clients will have the proxy IP as source address but the connection should work fine.

> I need to create local user or sftp user on sftpgo dashboard? thank you

You need at least an SFTP user. SFTPGo uses virtual users (no local system users), before testing the proxy make sure that the defined SFTPGo user works as expected connecting directly to the SFTPGo IP.

The [getting start guide](https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md) could help for this.

**Comment by WiFEED** [comment]
> There was another user who claimed it works behind Traefik, and shared the configuration settings: #434. Maybe checking your settings against his/hers will help you

Hello @puntopaz, I try this, now i have access denied on filezilla ... but nothing in my logs container sftpgo....

**Comment by WiFEED** [comment]
> > Thank you for this quick feedback!
> > Ohh... I'm really unlucky! I have already followed this tutorial but it doesn't work either.. Sftpgo, Container logs don't tell me I'm trying to connect to port 2222, There is no modification to make in the configuration file of sftpgo? to say that I am using a reverse proxy?
> 
> It should work with no modifications.
> 
> If traefik is able to send a proxy header as documented [here](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt), you have also to configure the proxy protocol in SFTPGo.
> 
> Using the proxy protocol you will see the real client IP, without proxy configuration all clients will have the proxy IP as source address but the connection should work fine.
> 
> > I need to create local user or sftp user on sftpgo dashboard? thank you
> 
> You need at least an SFTP user. SFTPGo uses virtual users (no local system users), before testing the proxy make sure that the defined SFTPGo user works as expected connecting directly to the SFTPGo IP.
> 
> The [getting start guide](https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md) could help for this.


Ok i follow this guide ... 

![image](https://user-images.githubusercontent.com/101096113/157015653-0bed6142-a3cb-4a46-9925-c68c4cfbed0a.png)
 
On this picture, 

Endpoint, i need to write ? domain.fr:22 | domain.fr:2022 | serverdockerIP:22 | serverdockerIP:2022 ? or dockercontainerSFTPGOIP: 22? or dockercontainerSFTPGOIP: 2022

I dont really understand this point .. sorry

**Comment by drakkan** [comment]
You are trying to create an SFTPGo user that uses another SFTP server as storage, you need a local user if you want to use the local storage

**Comment by WiFEED** [comment]
> You are trying to create an SFTPGo user that uses another SFTP server as storage, you need a local user if you want to use the local storage

I will explain to you what I want to do,
I have lamp and lemp servers on docker, my goal is to make sftp servers for each container so that I can connect from the outside
for the moment I am trying without the containers attached

**Comment by drakkan** [comment]
> > You are trying to create an SFTPGo user that uses another SFTP server as storage, you need a local user if you want to use the local storage
> 
> I will explain to you what I want to do, I have lamp and lemp servers on docker, my goal is to make sftp servers for each container so that I can connect from the outside for the moment I am trying without the containers attached

start using a local user. Local user means a user that uses local storage (for example a docker volume). Once this works you can define other user types if you really need them

**Comment by WiFEED** [comment]
ssh: connect to host 192.168.128.x(IPCONTAINERSFTPGOSERVER) port 2022: Connection timed out
Connection closed but i can connect to the dashboard with the new user

**Comment by drakkan** [comment]
> ssh: connect to host 192.168.128.x(IPCONTAINERSFTPGOSERVER) port 2022: Connection timed out Connection closed but i can connect to the dashboard with the new user

Is the port 2022 exposed? If you use the commands described [here](https://github.com/drakkan/sftpgo/tree/main/docker) it should work

**Comment by WiFEED** [comment]
ssh: connect to host 2022 port 22: Unknown error
Connection closed

with this docker-compose

`version: '3.3'
services:

  ftp:
    container_name: ftp
    image: drakkan/sftpgo:edge-alpine-slim
    networks:
           network-traefik:
              ipv4_address: 192.168.128.xxx
    ports:
       - "2022:2022"
    labels:
       - "traefik.enable=true"
       - "traefik.docker.network=network-traefik"
       - "traefik.http.routers.uiftp.entrypoints=https"
       - "traefik.http.routers.uiftp.rule=Host(`MYDOMAIN`)"
       - "traefik.http.routers.uiftp.tls.certresolver=http"
       - "traefik.http.routers.uiftp.service=uiftp"
       - "traefik.http.services.uiftp.loadbalancer.server.port=8080"
    
       - "traefik.tcp.routers.sftpgo-sftp.entrypoints=sftpgo"

       - "traefik.tcp.routers.sftpgo-sftp.rule=HostSNI(`*`)"
       - "traefik.tcp.routers.sftpgo-sftp.service=sftpgo-sftp"
       - "traefik.tcp.services.sftpgo-sftp.loadbalancer.server.port=2022"
       
      
networks:
   network-traefik:
       external: true`

**Comment by drakkan** [comment]
> ssh: connect to host 2022 port 22: Unknown error Connection closed
> 
> with this docker-compose
> 
> `version: '3.3' services:
> 
> ftp: container_name: ftp image: drakkan/sftpgo:edge-alpine-slim networks: network-traefik: ipv4_address: 192.168.128.xxx ports: - "2022:2022" labels: - "traefik.enable=true" - "traefik.docker.network=network-traefik" - "traefik.http.routers.uiftp.entrypoints=https" - "traefik.http.routers.uiftp.rule=Host(`MYDOMAIN`)" - "traefik.http.routers.uiftp.tls.certresolver=http" - "traefik.http.routers.uiftp.service=uiftp" - "traefik.http.services.uiftp.loadbalancer.server.port=8080" - "traefik.tcp.routers.sftpgo-sftp.entrypoints=sftpgo" - "traefik.tcp.routers.sftpgo-sftp.rule=HostSNI(`*`)" - "traefik.tcp.routers.sftpgo-sftp.service=sftpgo-sftp" - "traefik.tcp.services.sftpgo-sftp.loadbalancer.server.port=2022" networks: network-traefik: external: true`
> 
> With the docker machine i can connect to the sftp (in local) but in external i cant ...
> 
> logs :
> 
> {"level":"info","time":"2022-03-07T11:33:21.238","sender":"SSH","connection_id":"228a655a193faaae994d0756929423624dca4bf7e2fdfaba560a48a6e6a03e79","message":"User "david" logged in with "password", from ip "IPTRAEFIK", client version "SSH-2.0-OpenSSH_8.4p1 Debian-5""}
> 
> ![image](https://user-images.githubusercontent.com/101096113/157029185-0fdd15a3-ca2f-4dcc-a7dd-7a7f902ace57.png)

uhm ... this seems an issue related to the Traefik configuration. I never used Traefik before

**Comment by WiFEED** [comment]
@drakkan Is it possible that it is the firewall of the docker machine???

**Comment by drakkan** [comment]
> @drakkan Is it possible that it is the firewall of the docker machine???

It could be if from the same machine it works, but I would expect an error like connection refused or timeout, not connection closed

**Comment by WiFEED** [comment]
> > @drakkan Is it possible that it is the firewall of the docker machine???
> 
> It could be if from the same machine it works, but I would expect an error like connection refused or timeout, not connection closed


The local user created on the sftpgo admin dashboard should work from the outside normally?

**Comment by drakkan** [comment]
> > > @drakkan Is it possible that it is the firewall of the docker machine???
> > 
> > 
> > It could be if from the same machine it works, but I would expect an error like connection refused or timeout, not connection closed
> 
> The local user created on the sftpgo admin dashboard should work from the outside normally?
> 
> On Filezilla I have to connect with the address of the docker container? do you agree?

It depends on the docker network configuration, with the default config you have to expose the ports for example:

```
docker run --name some-sftpgo -p 8080:8080 -p 2022:2022 -d "drakkan/sftpgo:tag"
```

then if docker runs on the IP 192.168.1.1 you have to connect to 192.168.1.1 (not the internal docker network). Port 8080 is the admin UI and port 2022 is the SFTP service.

If you can connect to port 8080 to create users (directly without Traefik) you should be able to connect to the SFTP service on the same IP using port 2022. You should also see the connection logs in the SFTPGo logs

**Comment by WiFEED** [comment]
My network Traefik have : 192.168.128.0/24

My bridge netowrk have : 172.17.0.0/16

Suppose my container is at 192.168.128.253

So i need to connect on Filezilla with 192.168.128.253 with the port 2022 or domain.fr port 2022 ? do you agree?

**Comment by drakkan** [comment]
> My network Traefik have : 192.168.128.0/24
> 
> My bridge network have : 172.17.0.0/16
> 
> Suppose my container is at 192.168.128.253
> 
> So i need to connect on Filezilla with 192.168.128.253 with the port 2022 or domain.fr port 2022 ? do you agree?

Yes, try this way. If the connection comes to the SFTPGo instance you should see some logs

**Comment by WiFEED** [comment]
Unfortunately it doesn't work... I really don't understand why, all the configuration is good... On the traefik forum nobody answered me either...

**Comment by drakkan** [comment]
> Unfortunately it doesn't work... I really don't understand why, all the configuration is good... On the traefik forum nobody answered me either... and nothing in log say i'm trying to connect on port 2022...

can you confirm that a direct connection to the SFTPGo image works? This is the first step, once this work you have to investigate on the traefik side

**Comment by WiFEED** [comment]
> > Unfortunately it doesn't work... I really don't understand why, all the configuration is good... On the traefik forum nobody answered me either... and nothing in log say i'm trying to connect on port 2022...
> 
> can you confirm that a direct connection to the SFTPGo container works? This is the first step, once this work you have to investigate on the traefik side

With the commande sftp on docker machine?

**Comment by drakkan** [comment]
> > > Unfortunately it doesn't work... I really don't understand why, all the configuration is good... On the traefik forum nobody answered me either... and nothing in log say i'm trying to connect on port 2022...
> > 
> > 
> > can you confirm that a direct connection to the SFTPGo container works? This is the first step, once this work you have to investigate on the traefik side
> 
> With the commande sftp on docker machine?

using sftp cli or Filezilla or any other sftp client

**Comment by WiFEED** [comment]
![image](https://user-images.githubusercontent.com/101096113/157248360-780e4b30-cfc3-4bb4-a6e2-0fd3a632bc7f.png)

On the Docker Machine i can access to the container with the command sftp -p 2022 user@ip but on filezilla in external i cant ... 

![image](https://user-images.githubusercontent.com/101096113/157249310-1235b0a3-a1ad-40a7-9844-6f639eeb3b3c.png)

**Comment by WiFEED** [comment]
> > ![image](https://user-images.githubusercontent.com/101096113/157248360-780e4b30-cfc3-4bb4-a6e2-0fd3a632bc7f.png)
> > On the Docker Machine i can access to the container with the command sftp -p 2022 user@ip but on filezilla or on terminal visual studio for example in external i cant ...
> > ![image](https://user-images.githubusercontent.com/101096113/157249310-1235b0a3-a1ad-40a7-9844-6f639eeb3b3c.png)
> 
> Ok, so this is the first issue you have to fix. SFTPGo is running and works locally but the port 2022 is not exposed or blocked by a firewall

The fact that it tells me connection expired, connection closed, can it really be the firewall? for me it would rather return me "Connection refused" if it was the firewall which would be the cause

**Comment by drakkan** [comment]
If you use docker compose this is a basic configuration that works for me

```
version: "3.9"

services:
  sftpgo:
    container_name: sftpgo
    image: drakkan/sftpgo:edge-distroless-slim
    ports:
      - "8080:8080"
      - "2022:2022"
    #volumes:
      #- /mnt/sftpgo/data:/srv/sftpgo/data
      #- /mnt/sftpgo/config:/var/lib/sftpgo
    #environment:
    #  - SFTPGO_SFTPD__MAX_AUTH_TRIES=12
```

the machine running docker has `192.168.1.12` as IP address and I can connect to both port 8080 (SFTPGo web UI) and port 2022 (SFTP).

If you have a firewall try to disable it for testing

**Comment by WiFEED** [comment]
Do you create a sftp user ? or local user?

**Comment by drakkan** [comment]
I tested a local user. An SFTP user uses another SFTP server as storage instead of the local disk. But even if you don't create a user you should see the connection logs in the container output.

**Comment by WiFEED** [comment]
Oh ok I get it! thank you, in the container logs I see the connection logs to the WEB UI interface but I do not see the logs when I try to connect to my container in sftp

**Comment by drakkan** [comment]
> Oh ok I get it! thank you, in the container logs I see the connection logs to the WEB UI interface but I do not see the logs when I try to connect to my container in sftp. I just see the log on the port 8080

ok, try to disable the firewall and see if it makes any difference. It is really hard to help you ...

**Comment by WiFEED** [comment]
![image](https://user-images.githubusercontent.com/101096113/157260770-a3229293-2f04-4ff5-bba7-b5609c3da9e1.png)

The port 2022 is closed on the container ? it's normal ?

**Comment by WiFEED** [comment]
The port 2022 is closed on the container sftpgo

**Comment by drakkan** [comment]
but if you are able to connect locally, how can the port be closed? Are you checking the same IP address you use to connect to the port 80? Have you tried to disable the firewall?

**Comment by drakkan** [comment]
Sorry this is an open source project not a free help center

**Comment by WiFEED** [comment]
> Désolé, il s'agit d'un projet open source et non d'un centre d'aide gratuit. Je ne veux pas être grossier mais j'ai des choses à faire pour mon travail quotidien

No problem, you helped me a lot, thank you for your patience and for your explanations! I will try to do everything possible to make this configuration a success and I will keep you posted on this post! Thank you so much ! Have a good day ++

**Comment by WiFEED** [comment]
Hello Drakkan, it works! Thank you for your involvement and your help... It was the firewall that was the problem, thank you very much! My configuration works perfectly now! We can close this issue!

**Comment by drakkan** [comment]
Thanks for reporting back, another user is also writing a detailed Traefik tutorials, it should be available soon

**Comment by LTGIV** [comment]
Hi, just checking in to let y'all know that the article is done!

[File Traefik: Serve files securely via SFTP, HTTPS, and WebDAV with SFTPGo proxied behind Traefik.](https://LTG.FYI/File-Traefik)
