### ISSUE TITLE
Banned host doesn't show up in Defender Tab 

### ISSUE THREAD

**Issue by lucatiozzo91** [drakkan/sftpgo#758]
Hello,

I use this version of sftpgo:

`SFTPGo 2.2.1-794afbf8-2021-12-31T13:26:00Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable`

I'm using mysql as data_provider and provider mode in the defender.driver conf. I've 2/3 instances of sftpgo with the same confs and db behind a TCP load balancer

Sometimes I noticed some differences between data in the UI defender tab and data stored in database.
More specifically,  there are currently banned hosts in the defender_host table which don't have any more associated records in the defender events table. Ban time of this hosts is after the current time so they are really banned at the moment. 
In this situation the hosts aren't displayed on the UI

I attach an example with the 2 tables and the UI taken at the same moment

For example the host with id: 4148 is banned but not showed on UI

Table defender events:

```
234,1647421344991,1,3952
235,1647421345047,1,3952
242,1647422705848,1,3952
243,1647422705910,1,3952
249,1647424069275,1,3952
250,1647424069329,1,3952
255,1647425411727,1,3952
256,1647425411783,1,3952
258,1647425434705,1,4108
236,1647421865652,1,4108
237,1647421865667,1,4108
238,1647422102639,1,4108
239,1647422102647,1,4108
240,1647422133191,1,4108
241,1647422133198,1,4108
244,1647423002719,1,4108
245,1647423002726,1,4108
246,1647423033261,1,4108
247,1647423033285,1,4108
279,1647426034479,1,4108
251,1647424204237,1,4108
252,1647424204244,1,4108
253,1647425404233,1,4108
254,1647425404249,1,4108
257,1647425434697,1,4108
278,1647426034473,1,4108
267,1647426003966,1,4108
266,1647426003955,1,4108
233,1647421004304,1,4131
259,1647425636786,1,4131
248,1647423188070,1,4199
262,1647425992173,1,4211
263,1647425993625,1,4211
264,1647425995088,1,4211
265,1647425996516,1,4211
260,1647425989552,1,4211
268,1647426005021,1,4211
269,1647426006436,1,4211
270,1647426007879,1,4211
271,1647426009369,1,4211
272,1647426010790,1,4211
273,1647426012220,1,4211
274,1647426013646,1,4211
275,1647426015097,1,4211
276,1647426016521,1,4211
277,1647426019013,1,4211
261,1647425990762,1,4211
280,1647426124603,1,4231
281,1647426127715,1,4231
282,1647426130763,1,4231
```

Table defender host:

```
3952,193.3.19.87,0,1647425411782
4108,213.209.219.19,0,1647426034475
4131,45.9.20.25,0,1647425636786
4199,45.9.20.73,0,1647423188069
4231,193.169.255.199,0,1647426130762
4211,179.85.43.19,1647428119021,1647426019012
4148,155.56.216.57,1647456840270,1647420300245
4146,155.56.216.40,1647459782408,1647420002397
```

UI:

<img width="1420" alt="Schermata 2022-03-16 alle 11 25 52" src="https://user-images.githubusercontent.com/49106317/158571960-35ecc6ab-d99e-4c9e-ab73-824d9d338309.png">

I noticed that host's records disappear from UI when their last associated record in defender_events table is deleted by the cleanup function. I think the bug is in the query runned by this function:

https://github.com/drakkan/sftpgo/blob/d73be7aee5ff15cc4e000a3ec99f7284cec5ce6a/dataprovider/sqlcommon.go#L1712

Thanks in advance.

**Comment by drakkan** [comment]
I'm unable to replicate after a first try, here is my db:

```
sftpgo.db=# select * from defender_events;
 id |   date_time   | score | host_id 
----+---------------+-------+---------
 16 | 1647429812075 |     2 |      15
 17 | 1647429816202 |     2 |      15
(2 righe)

sftpgo.db=# select * from defender_hosts;
 id |    ip     |   ban_time    |  updated_at   
----+-----------+---------------+---------------
  7 | ::1       | 1647432303280 | 1647429603273
 15 | 127.0.0.1 |             0 | 1647429816202
(2 righe)
```

I can see both hosts
![Schermata del 2022-03-16 12-32-08](https://user-images.githubusercontent.com/553263/158580873-915ee257-4c4f-4e36-913d-ca473bda5f20.png)

I'll try again later, if there is a bug it doesn't seem related to banned IP with no scores

**Comment by drakkan** [comment]
can you please post your defender configuration and any relevat env var if you override some values? Thanks

**Comment by lucatiozzo91** [comment]
I think the problem is the query that load data from defender_host table. When a host is banned but the updated time is in the past the query don't load the record.

I'v find a solution changing the condition of the query.
