### ISSUE TITLE
[Feature request] Event Manager

### ISSUE THREAD

**Issue by lublak** [drakkan/sftpgo#762]
Currently it is only possible to define the hooks via config.
Thereby the server must be restarted.
It would be practical to set the events via the interface and to define multiple urls (also via the interface).

**Comment by drakkan** [comment]
Hi,

I have a temporal undefinite plan to simply the configuration by moving some settings from the config file to the data provider so we can easily set them from the web ui, but this will likely happen after v2.3, I currently have several other requets from project sponsors.

Can you please better explain what do you mean when you write "and to define multiple urls (also via the interface)"?
The events contains the info about the user so one endpoint is generally enough

**Comment by lublak** [comment]
Hi @drakkan,

thanks for the very fast answer.
Here is roughly what I meant. I think pictures say more than a thousand words.

![grafik](https://user-images.githubusercontent.com/44057030/158819022-402be4ef-8119-4017-bb24-7760d84f1824.png)
![grafik](https://user-images.githubusercontent.com/44057030/158820546-46bff62e-f434-41c0-a204-7d2338ae01ac.png)

Thus, different events can be defined with different hooks.

**Comment by drakkan** [comment]
Hi,

honestly this seems excessive, I feel the current configurability is enough. If you want this level of customization you can write your own eventsreceiver plugin.

Additionally I don't want to create a separate page for each configuration (one for hooks, another one for max connections etc.), I want a single server configuration page divided in different sections and move them some configurations that can be applied without a restart

**Comment by drakkan** [comment]
There is no way to extend the interface within a plugin or to write to existing database. The existing plugins use a separate database.

You could simply notify the events to a single plugin/hook and then multiplex from there. 

I can understand that you want to be able to change a hook url without restarting the server but I cannot understand why you need to forward, for example, upload events to an endpoint and download events to another one. SFTPGo cannot support any particular use case out of there, however, as explained above you could write a simple wrapper that receive and forwards the events (using a plugin or a hook).

Are you trying to expose SFTPGo to external admins? Do you want to integrate SFTPGo with a legacy application that accepts different events on different URLs and you don't want to change this application?

**Comment by lublak** [comment]
@drakkan 
I want to use SFTPGo events with n8n webhooks.
That means I would have to enter a new address in sftpgo for each workflow with a webhook.
But of course I don't want to have another webfrontend for every single mini system, so I want to extend sftpgo then.

But I also understand that you don't want the system to be more complicated than it is.
I think I will abandon the idea and develop a plugin with its own frontend and login.
Possibly also a consideration would be an interaction.
A plugin which communicates directly with n8n, but to what extent that is possible, I can not say yet.

**Comment by drakkan** [comment]
Hi,

in the future I would like to add something like [this](https://support.cerberusftp.com/hc/en-us/articles/115001954490-Creating-and-Editing-Event-Rules) or better. A generic event manager not restricted to file operations, but for now is only an implementation idea, I don't think I'll have time to work on this soon

**Comment by lublak** [comment]
That would be really good. 
And that it cannot be implemented immediately is clear. In any case, this function would be really handy.
Here are other products that implement such a function.

https://www.crushftp.com/crush8wiki/Wiki.jsp?page=UserManagerEvents
https://enterprisedt.com/products/completeftp/doc/guide/html/processtriggers.html

**Comment by drakkan** [comment]
I agree that it is a good addition and is probably one of the last missing pieces to fill the gap with similar proprietary solutions.   The other missing piece is the multi tenancy support and I would like to add it in v2.3 (I'm reaching an agreement with a company interested in this feature so this have priority. 
For v2.4 I'll try to add the event manager and task scheduler so we can also automate backups, quota checks ecc..

**Comment by drakkan** [comment]
Please note the diff

```
54 files changed, 10238 insertions(+), 869 deletions(-)
```

And I've postponed a lot of features that can be implemented in the event manager. I think this is the last time I'll add such huge feature for free.
Since most of the users here just ask and don't give anything back, I'm now considering a dual license option with some features only available in the paid version.

**Comment by lublak** [comment]
@drakkan 
That is a lot of work. By the way, I'm not a person who asks and doesn't like to give anything back. But since I'm not very fluent, I'll only send a little something now and then. I hope that's okay for you anyway. Besides, it will take a few more days before I can send anything. Maybe a tip: Put your sponsor info stuff at the top. It's really hard to find at the bottom because most people don't scroll much. Maybe it will change if you put it at the top.
Maybe it can also bring something if you actively advertise it.
The first time you start sftpgo, a screen with: We also accept donations.
Currently it is very invisible and I almost overlooked it.

**Comment by lublak** [comment]
@drakkan I think what I noted would not be so pushy.
Especially in the setup it would not bother anyone if once said that you accept donations.
And in the readme such a small part at the top would not bother at all.
Also another thing just with private users. Sponsoring means for me rather: Every month a bar of money to provide.
Possibly the word donations should be used.

Sponsoring: GitHub link
Small donations: PayPal link

Something like this.
Badgets can also really help. They are well visible but are now also not too pushy.
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/donate?hosted_button_id=JQL6GBT8GXRKC)

**Comment by drakkan** [comment]
> @drakkan I think what I noted would not be so pushy. Especially in the setup it would not bother anyone if once said that you accept donations. And in the readme such a small part at the top would not bother at all. Also another thing just with private users. Sponsoring means for me rather: Every month a bar of money to provide. Possibly the word donations should be used.
> 
> Sponsoring: GitHub link Small donations: PayPal link
> 
> Something like this. Badgets can also really help. They are well visible but are also not too pushy. [![Donate](https://camo.githubusercontent.com/2bfa6102e99ff9a137185897b0a566aa0977a4790348c462e6951829e787af8f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f446f6e6174652d50617950616c2d677265656e2e737667)](https://www.paypal.com/donate?hosted_button_id=JQL6GBT8GXRKC)

I will try to better highlight the donation / sponsorship possibilities. A direct link to Paypal has caused me problems in the past. My Paypal account has been suspended for violating the rules. They didn't tell me the exact reason but I think it happened because people clone the repo and the link appears in multiple repositories
