### ISSUE TITLE
[Docker] Permissions denied when upload or create directory 

### ISSUE THREAD

**Issue by WiFEED** [drakkan/sftpgo#763]
Hello, I have a new problem, it is impossible to upload a file i get this
 "/web/public/shoppingfb.jpg: open for writing: permission denied "

![image](https://user-images.githubusercontent.com/101096113/158814978-79f24d51-8214-4d7d-abe6-f981b5bab84d.png)

The star is fine for everything activated? so to allow everything?

There is another problem also when I modify my docker-compose then I do a " docker-compose up -d " I have to recreate the administrator account and all users would you have a solution?

**Comment by drakkan** [comment]
Hi,

when you set per-directory permissions you need to define a virtual path (the path seen by SFTP clients) not the full filesystem path.

To persist the data you need to mount a docker volume as for any other docker image

**Comment by WiFEED** [comment]
Ok, except I want to access another container's folder, so I'm forced to create a volumes for the other container on the docker-compose of the sftp

Like that

![image](https://user-images.githubusercontent.com/101096113/158819654-00c15d65-f849-4e8a-aaf3-cdc01a1ba29a.png)

So I think I have to put the full path of the file system

**Comment by drakkan** [comment]
If you have a volume defined as `</local/path>:/srv/sftpgo/data` then the container will see the volume data within `/srv/sftpgo/data`. Please remove the per-directory permissions and, if still does not work, ensure that your volume has the appropriate filesystem permissions as described [here](https://github.com/drakkan/sftpgo/tree/main/docker#where-to-store-data). If something goes wrong the first things to look at and to share are the log files :-)

**Comment by WiFEED** [comment]
Hi, 

I did as you told me, I removed the permissions per directory and it doesn't work, in the sftpgo log files it just tells me permissions denied when I try to create a folder or a file or even upload

**Comment by drakkan** [comment]
ok, outside the container execute:

```
chown -R 1000:1000 /mnt/docker/docker-compose/siteweb/c2
```

where `/mnt/docker/docker-compose/siteweb/c2` is the folder you mount as volume

**Comment by WiFEED** [comment]
Ok but when i create  this volume i cant access web UI cause the container won't start

volumes:
     - "./sftp/var/lib/sftpgo:/var/lib/sftpgo"
     - 
Log : sender":"service","message":"error initializing data provider: unable to open database file: no such file or directory"}

**Comment by drakkan** [comment]
> Ok but when i create this volume i cant access web UI cause the container won't start
> 
> volumes: - "./sftp/var/lib/sftpgo:/var/lib/sftpgo" - Log : sender":"service","message":"error initializing data provider: unable to open database file: no such file or directory"}

this happens because filesystem permissons are wrong. SFTPGo runs using 1000 as UID and GID, this user cannot write to the mounted directory, this is the same reason why you cannot upload files and you can fix with a similar command to the one I wrote above

**Comment by WiFEED** [comment]
> > Ok, mais lorsque je crée ce volume, je ne peux pas accéder à l'interface utilisateur Web car le conteneur ne démarre pas
> > volumes : - "./sftp/var/lib/sftpgo:/var/lib/sftpgo" - Journal : expéditeur":"service","message":"erreur lors de l'initialisation du fournisseur de données : impossible d'ouvrir le fichier de base de données : aucun fichier de ce type ou répertoire"}
> 
> cela se produit parce que les autorisations du système de fichiers sont erronées. SFTPGo fonctionne en utilisant 1000 comme UID et GID, cet utilisateur ne peut pas écrire dans le répertoire monté, c'est la même raison pour laquelle vous ne pouvez pas télécharger de fichiers et vous pouvez corriger avec une commande similaire à celle que j'ai écrite ci-dessus

Like chown -R 1000:1000 /etc/sftpgo 
       chown -R 1000:1000 /var/lib/sftpgo ?

**Comment by drakkan** [comment]
Thanks for reporting back

**Comment by Eliophot** [comment]
Hello @drakkan ,

- SFTPGO Docker + multiple WordPress Dockers
- Ubuntu

I have the same issue, actually, if I change the permissions to 1000:1000, it works with my SFTPGO user, but WordPress, which uses 33:33, can no longer write. It's a vicious circle.
I changed the UID:GID of the SFTPGO user to 33:33, but it doesn't work. Any other ideas?
