### ISSUE TITLE
how i can access files and edit them through rest api

### ISSUE THREAD

**Issue by codesiddhant** [drakkan/sftpgo#764]

**Comment by drakkan** [comment]
Just [read](https://sftpgo.stoplight.io/docs/sftpgo/b3A6MTY2OTU4OTI-download-a-single-file) the file, and then [upload](https://sftpgo.stoplight.io/docs/sftpgo/b3A6MzM3OTMxMzY-upload-a-single-file) the modified version

**Comment by codesiddhant** [comment]
It's will compuse lots data I want to update file every second is this is any way to stream file editing like ssh ?

**Comment by drakkan** [comment]
This not currently supported. Do you want to append at the end of the file or writing data at a specified offset?

**Comment by codesiddhant** [comment]
I wanna append something at file using SFTP based backend

**Comment by codesiddhant** [comment]
Any possibility with socket.io and Put Feature of SFTP ?

**Comment by drakkan** [comment]
> After getting a line number and content from user using socketio and later edit the particular file using some (sed / awk) commands via SSH on SFTP based Clients ?

A such hack using sed/aws is out of question. We could expose a REST API that wraps [pwrite](https://man7.org/linux/man-pages/man2/pwrite.2.html) and so allows to write data to a specified offset (in bytes) that could be the end of the file if you want to append or in the middle of the file if you want to overwrite existing data.

However this will not work with all the supported storage providers, in details:

- local filesystem: OK
- encrypted local filesystem: KO
- S3: KO
- Google Cloud Storage: KO
- Azure Blob: KO
- SFTP: OK if buffer_size = 0

Do you want to send a patch or [sponsor](https://github.com/sponsors/drakkan) this development?
