### ISSUE TITLE
[OIDC] Add debuging to the login steps

### ISSUE THREAD

**Issue by pacrutchet** [drakkan/sftpgo#766]
Hello,

Would it be possible to have more information in the logs about the received data from the OIDC login ? it would be nice to select a username from those info.

I'm using Auth0 and the username is my email address, this is not accepted as the @ is not an authorized character in the username. I tried fixing the username in the pre_login script, but a mismatch between the received OIDC username and the one returned by the pre_login script seems to not be permitted.

Thanks a lot!

**Comment by drakkan** [comment]
Hi,

we can print the received fields and we already do this in some cases, see [here](https://github.com/drakkan/sftpgo/blob/main/httpd/oidc.go#L188) for example.

You can use any UTF-8 chars for usernames by setting [naming_rules](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L207) to `1`.

Full docs [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md) see the "Configuration file" section

**Comment by pacrutchet** [comment]
Thanks a lot!
I have set the naming_rules to 1 and it fixed my issue of username.
But now I have the following error:
"httpd","message":"unable to get the sftpgo user associated with oidc token: Validation error: please set a password or at least a public_key"

Should I set a generic password via the pre_login_hook ?

**Comment by drakkan** [comment]
Yes, a password or a public key is required to use the account with other protocol or without OIDC. If you want only use the web client UI and you don't plan to login via SFTP etc, just set a random password

**Comment by pacrutchet** [comment]
Works great! thanks a lot!

**Comment by drakkan** [comment]
No problem, if you can please consider [sponsoring](https://github.com/sponsors/drakkan) the project, thanks
