### ISSUE TITLE
Add jq to the full docker images

### ISSUE THREAD

**Issue by markpash** [drakkan/sftpgo#767]
Hi,

I'm currently trying to write a script for `pre_login_hook` but I noticed that `jq` (a command-line json parser) is not in the docker images. This would be really useful parsing the `SFTPGO_LOGIND_USER` variable which contains json data.
Would you consider adding this package to the "full" docker image?

**Comment by drakkan** [comment]
Hi,

jq is now included but if you need heavier dependencies, please consider building your own Docker image using the "official" ones as a base, I can't include everything, hope you understand
