### ISSUE TITLE
Web interface is broken in v2.2.2

### ISSUE THREAD

**Issue by CompuRoot** [drakkan/sftpgo#771]
Updated to v2.2.2 (Linux x86_64, Debian 10)

Now, when I go to admin's account to update user's services, there only user name, password and textarea for public key. There no usual fields to setup folders, enable/disable services, nothing.
The same things if I trying to add new user. 

On the bottom of screen following message:
```
template: user.html:141:32: executing "page_body" at <.FsWrapper>: can't evaluate field FsWrapper in type httpd.userPage
```

If I login as an user, I can not browse any files, the area that should display files and folders is empty.

I don't have custom `user.html` for sure.

All allowed services (WebDAV, SFTP) still working and if you connect directly over WebDAV for example I can see and manage all files.

**Comment by drakkan** [comment]
Hi,

it seems you are using v2.2.1 executable with v2.2.2 templates

**Comment by CompuRoot** [comment]
@drakkan Thanks a lot ! 

You right, it was version v2.2.0, I updated everything except executable, my bad :(

Thank you one more time, really appreciated !
