### ISSUE TITLE
Unsupported key-exchange algorithm "curve25519-sha256"

### ISSUE THREAD

**Issue by CompuRoot** [drakkan/sftpgo#772]
`SFTPgo` v2.2.2

---

If setting  `kex_algorithms` in `sftpd` set as such in `sftpgo.json`:

```
    "kex_algorithms": [
        "curve25519-sha256" 
    ],
```
where this settings comes from [documentation](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md), where it says that 

> `curve25519-sha256` is supported `kex_algorithms`

 but it fact it need to be: `curve25519-sha256@libssh.org`, so as result, `sftpgo` won't start and throw error:
```
{"level":"error","time":"2022-03-24T03:30:01.537","sender":"service","message":"could not start SFTP server: unsupported key-exchange algorithm \"curve25519-sha256\""}
```

**Comment by drakkan** [comment]
Hi,

the docs you refer is for the development version, please check the docs in the 2.2.x branch

https://github.com/drakkan/sftpgo/blob/2.2.x/docs/full-configuration.md

I recently added support for more KEXs and removed sha1 based algos from the default settings, but these changes are only in the development version for now

**Comment by CompuRoot** [comment]
Got it, I would keep in mind in a future to check documentation from release branch only.

Thanks again !
