### ISSUE TITLE
Verbose logging can not be turned off

### ISSUE THREAD

**Issue by CompuRoot** [drakkan/sftpgo#773]
`SFTPgo` v2.2.2

---

According to:

`sftpgo help serve`:

```
  -v, --log-verbose            Enable verbose logs. This flag can be set
                               using SFTPGO_LOG_VERBOSE env var too.
                                (default true)

```
It makes verbose logging always turned on since it `default true` , regardless if option `-v` is present or not, so as result log file flooded with all `debug` messages.

Suggestion is to turn option `-v` by default to `false` and if one might need full debug messages, then option `-v` will do what it supposed to do - "verbose logging".

**Comment by drakkan** [comment]
Hi,

please take a look [here](https://github.com/drakkan/sftpgo/issues/580#issuecomment-948682310), boolean flags are not very intuitive in Go

**Comment by CompuRoot** [comment]
@drakkan you are one of the best !

Thank you very much !

**Comment by TheManchineel** [comment]
This is still a problem for me. I'm using the official Docker container (drakkan/sftpgo:latest) and `-e SFTPGO_LOG_VERBOSE=0`, and yet debug-level lines still print out in the log

**Comment by TheManchineel** [comment]
For anyone looking now, it's SFTPGO_LOG_LEVEL=error
