### ISSUE TITLE
i wondered how one can use ssh commands on SFTP hosts ?

### ISSUE THREAD

**Issue by tech2secure** [drakkan/sftpgo#775]
hey! first of all thanks for making this awesome tool. 
I am closely looking at the source code of the project inside the Sftpd directory I found something like ssh_cmd.go and now I am wondering that is possible to send an ssh command or run any script on an SFTP host from the REST API or web dashboard?

I tried [https://sftpgo.stoplight.io/docs/sftpgo/b3A6MjUzNDc0Nzg-get-filesystem-events](This ) but still no luck?
Please someone what is the use of these events and how to enable/use them that are mentoined in the API documentation 

thanks

**Comment by drakkan** [comment]
Hi,

for details about supported SSH commands take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/ssh-commands.md). The supported SSH commands can be executed only via SSH at the moment

**Comment by drakkan** [comment]
Regarding the question about filesystem events, here is the description you can read in [stoplight](https://sftpgo.stoplight.io/docs/sftpgo/b3A6MjUzNDc0Nzg-get-filesystem-events)

> Returns an array with one or more filesystem events applying the specified filters. This API is only available if you configure an "eventsearcher" plugin

The eventsearcher plugin can be found [here](https://github.com/sftpgo/sftpgo-plugin-eventsearch). This plugin allows to search for download,upload and other events
