### ISSUE TITLE
Creating folders on an Azure Blob Storage backend

### ISSUE THREAD

**Issue by RaghavBatra** [drakkan/sftpgo#776]
Hi! Cool project first of all. Secondly, I am trying to connect the SFTPGO client with an Azure Blob backend. When I try to `mkdir` a new folder, however, it appears as a 0B file on my Storage Account. 

This is not the case for local backend, which can create any number of folders. 

Is this something on the Azure (cloud) side or do I need to configure my server correctly? Either way, appreciate any inputs.

Thanks!

**Comment by drakkan** [comment]
Hi,

Azure Blob and other cloud backends have no folder concept, so to simulate a folder we create a 0 byte key with mime type set to `inode/directory` when you use mkdir.

**Comment by RaghavBatra** [comment]
OK so basically it's not possible then? 

**Another possibly related issue:**
The structure of the root folder is given below. As a user, I want to be able to go into the `incoming` folder. But I get `Can't change directory: "/incoming" is not a directory`. Is this related to the above in any way?

![image](https://user-images.githubusercontent.com/23087140/160173012-e55ebefe-b7d5-4f06-9903-4e3dfc0aa614.png)

**Comment by drakkan** [comment]
Not sure about your second question, can you please report the directory listing for the "client" directory as seen with an SFTP client? For example ls -la from cli sftp or a screenshot from filezilla or similar client. Does the "incoming" blob appear there? Or do you see an empty directory listing?

**Comment by RaghavBatra** [comment]
Sure:
The sftgo-test/client directory is set as the "prefix" directory
![image](https://user-images.githubusercontent.com/23087140/160189688-04aae660-4a36-42ce-a1cc-347c89d7fb85.png)
![image](https://user-images.githubusercontent.com/23087140/160189869-fedab385-37e9-44ef-a0f4-ea93cb7a88a3.png)

Both "incoming" and "outgoing" are directories created directly on the storage account
![image](https://user-images.githubusercontent.com/23087140/160189883-fa08d03e-afeb-462d-9704-0c01297dd91d.png)

Lmk if you need more & thanks!

**Comment by drakkan** [comment]
This seems something strange. Using the azurite emulator I'm unable to replicate the issue. 

Can you confirm that if you create these directories from SFTPGo all works as expected?

I don't have access anymore to a real azure account, if you can, please send me some test credentials to my private email address and I'll try to take a look. Thanks

**Comment by RaghavBatra** [comment]
Interesting. Yes, I am able to create directories if "incoming" is a virtual folder. Maybe that's the trick!? But the issue with creating folders within that folder is that it still does not translate to Azure Storage ... Any suggestions on how to handle that?
Would it be easier to just have everything locally on the container and push it to the storage account using Python?

I can ask my manager if I can generate test credentials for you. In the meantime, I will chat here. THanks!

**Comment by drakkan** [comment]
as said cloud storage does not have folders, only object with `/` in the name and the folder as simulated. For S3 and GCS their "storage managers" create 0 byte key with a trailing slash to simulate folder and we do the same in SFTPGo. For Azure this seems not recommended

https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

> Avoid blob names that end with a dot (.), a forward slash (/), or a sequence or combination of the two. No path segments should end with a dot (.).

I'm sorry but without a test account is difficult to understand what is happening. Do you use the Azure Storare Explorer or another tool to create these "folders"?

**Comment by RaghavBatra** [comment]
Yeah Azure is wonky ....
I used the Add Directory option on the Portal. I can get back to you about test credentials on Monday!

**Comment by drakkan** [comment]
maybe they create an object with a trailing `/`, I can adapt the sftpgo code, but first I need to be sure. I'll check once I have a test account, thanks

**Comment by drakkan** [comment]
I just got access to a free tier Azure account and it seems to work as I initially described, take a look at the following screenshot

![Schermata del 2022-03-26 10-42-48](https://user-images.githubusercontent.com/553263/160234014-146237bc-26e6-4def-b5f8-206a93a252ec.png)

Directories created using the storage browser are virtual and I cannot list them via SFTP until I upload a file. 

In SFTPGo when you issue a mkdir command a sort of placeholder must be created (we cannot create a non-existing object via SFTP), so we create a 0 byte blob with a directory content type. If you access the account via SFTP you have a coherent directory listing.

Anyway would be interesting to understand what is the issue with your "incoming" and "outcoming" directories. Please take a look at the SFTPGo logs, maybe there is a permission issue or something similar

**Comment by drakkan** [comment]
If I create directory using blob with a trailing `/` as for other storage backends I endup with something like this:

![Schermata del 2022-03-26 11-51-24](https://user-images.githubusercontent.com/553263/160236254-e63751ef-42bc-40ea-bc02-1a83376ab0c5.png)

I created `a/`

**Comment by drakkan** [comment]
can you please share the content type for your "incoming" and "outcoming" folders? Can you post the SFTPGo logs with the error when you try to change directory? Thanks

**Comment by RaghavBatra** [comment]
Hi there, thanks for your help! Unfortunately, upper management decided to go with something else. Appreciate the quick responses.

**Comment by drakkan** [comment]
No problem, upper management generally prefer closed source products. 

If you can, please post the content type for these folders, I'm interested in better understanding this issue in any case. Thanks

**Comment by RaghavBatra** [comment]
Will try to do over the week!

**Comment by deaksa** [comment]
I have similar issues with azure blob storage.
Folders created by sftpgo are not seems to be folders and cannot upload to them, but is if manually creat a folder in the container i can upload files to them vie sftpgo. 
On the other hand, I cant browse folder contents on the web client, it just downloads 0 byte file.

**Comment by drakkan** [comment]
> I have similar issues with azure blob storage. Folders created by sftpgo are not seems to be folders and cannot upload to them, but is if manually creat a folder in the container i can upload files to them vie sftpgo. On the other hand, I cant browse folder contents on the web client, it just downloads 0 byte file.

I'm sorry but you are not adding any info to fix this issue. As you can read above I cannot reproduce. Can you provide more info or give me access to a storage account with this issue? Thanks

**Comment by deaksa** [comment]
> I'm sorry but you are not adding any info to fix this issue. As you can read above I cannot reproduce. Can you provide more info (for example content type and metadata of the objects identified as directories) or give me access to a storage account with this issue? Thanks

I'll create a dummy storage account and send you the access details to your e-mail.

**Comment by drakkan** [comment]
> > I'm sorry but you are not adding any info to fix this issue. As you can read above I cannot reproduce. Can you provide more info (for example content type and metadata of the objects identified as directories) or give me access to a storage account with this issue? Thanks
> 
> I'll create a dummy storage account and send you the access details to your e-mail.

Thanks, after looking at the source code of azure blob fuse I think you should see the `hdi_isfolder` metadata key. Anyway having a test account is ideal

**Comment by deaksa** [comment]
> > > I'm sorry but you are not adding any info to fix this issue. As you can read above I cannot reproduce. Can you provide more info (for example content type and metadata of the objects identified as directories) or give me access to a storage account with this issue? Thanks
> > 
> > 
> > I'll create a dummy storage account and send you the access details to your e-mail.
> 
> Thanks, after looking at the source code of azure blob fuse I think you should see the `hdi_isfolder` metadata key. Anyway having a test account is ideal

I have sent you an email. What I have found during repro, the problem occurs only when the Data Lake Gen 2 features are enabled.

**Comment by drakkan** [comment]
Fixed in the latest commit, thanks for the test environment, very useful

**Comment by aellwein** [comment]
Stumbled upon this issue.
We have seen something very related to this:
If some new "folder" was created with our previous SFTP solution, it gets a "<noname>" 0 bytes blob.
This folder cannot be deleted by SFTPGo afterwards ("cannot delete non-empty directory")
By looking in the SFTPGo Web UI we see a "." (dot) empty file:
<img width="1586" alt="Screenshot 2024-08-12 at 14 05 44" src="https://github.com/user-attachments/assets/e1f7a413-4c60-4ded-a59e-18e683600ab1">
