### ISSUE TITLE
Redirect HTTP to HTTPS options

### ISSUE THREAD

**Issue by Borduhh** [drakkan/sftpgo#777]
With HTTPS being the defacto for the web now, we would love to see an `env` variable to convert HTTP to HTTPS for the web client. Currently, we are only listening on either 80 or 443 with HTTPS enabled in docker. With a cert attached, if we were to access the web client on 80, we would just get the default Chrome "This site can't be reached" error.

It would be nice to be able to do that within the service versus having to set up a proxy in front.

**Comment by drakkan** [comment]
Thanks for the suggestion, this feature is now supported, you can test by using one of the edge variants

**Comment by Borduhh** [comment]
Is there any documentation about setting it up?

**Comment by drakkan** [comment]
Hi,

if you are looking for an howto style guide, no there is no such documentation.

I just added two settings, they are documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md):

>   `https_redirect`, boolean. Set to `true` to redirect HTTP requests to HTTPS. Default: `false`.
      `https_host`, string. Defines the host name that is used to redirect HTTP requests to HTTPS. Default is blank, which indicates to use the same host. For example, if `https_redirect` is enabled and `https_host` is blank, a request for `http://127.0.0.1/web/client/login` will be redirected to `https://127.0.0.1/web/client/login`, if `https_host` is set to `www.example.com` the same request will be redirected to `https://www.example.com/web/client/login`.

I think you have two define two bindings: one with https disabled and the redirect enabled and another one for https

**Comment by drakkan** [comment]
Hi,

thanks for reporting back, but you don't need to run two sftpgo instances, you can add multiple bindings to the same instance. For example `SFTPGO_HTTPD__BINDINGS__0__...`,`SFTPGO_HTTPD__BINDINGS__1__...` etc.
