### ISSUE TITLE
Allow Virtual Folder as explicit home directory for user

### ISSUE THREAD

**Issue by shrink** [drakkan/sftpgo#783]
At the moment, it's possible to implicitly use a directory as the home directory for multiple users by entering the same directory configuration information for each user, however, because it's implicit rather than explicit, it means any configuration change on the directory must be ported to each user individually. For example, if the shared home directory is a Google Cloud Storage Filesystem Bucket, and we are switching to a new `Bucket` or changing the `Key Prefix`, we must set the new value for each user.

I think the solution would be to add an additional "Virtual Folder" Filesystem option when creating a user, which allows for the selection of a Virtual Folder as the home directory for the user. I've taken a look around the code and I think this is viable, but I'm unsure if there's a reason this option isn't already supported -- maybe there are technical reasons that I haven't identified, or it could just be that there hasn't been a need for it before!

If this solution is acceptable, then I am happy to contribute a Pull Request in the coming days with the addition, but I wanted to check beforehand if there's any considerations I've missed.

Thanks,

---

notes:

My initial attempt to achieve this was to add a Virtual Folder to the user, and set the mount path to `.` or `/` or an empty string but these options did not work, so my conclusion based on that behaviour is that there is no explicit support for a Virtual Folder as a user's home directory.

The use-case for sharing a home directory is that we have a Virtual Folder for each entity (i.e: each `partner`) but there is no direct relationship between a `partner` and a `user`. That is, a `partner` could have zero, one or many users (e.g: `employee-1` `employee-2` `api` etc.) so we are first creating a directory for the partner (e.g: a directory for `Walmart`) and then create individual users with access to that directory. Although we could give each user their own home directory, and then mount the partner directory as a Virtual Folder at a dedicated path (e.g: `/partner`) it would be confusing for users ("do I put my files in the root directory or the `partner` directory?") and require that any partner systems hardcode the path to use.

**Comment by drakkan** [comment]
Hi,

first of all thanks for your support, much appreciated. I understand your use case and I'm glad to try to help you.

Sharing the same home directory among multiple users is not a common use case and doing so will make the quota calculation incorrect (but maybe you don't need to manage the quota in SFTPGo for your use case). 

Maybe we could allow `/` as a valid path for virtual folders, that way quota checking will work too.

I'll try this approach over the weekend, I suspect some edge cases might raise as the current code assumes that `/` cannot be a virtual folder.

**Comment by shrink** [comment]
Thank you very much for getting back so quickly. I hadn't considered quotas: you're correct that they're not a concern for us in this instance, but could be for others. The ability to mount a Virtual Folder to `/` would be a great solution too: I had assumed that wasn't viable because it could create conflicts with the contents of other mounted Virtual Folders (i.e: if a Virtual Folder is mounted to `/` and a Virtual Folder is mounted to `/example` with the Virtual Folder `/` containing a directory called `example`) but if it's possible then it would be a great solution for us too. I guess an option to prevent conflicts might be to simply restrict a user to _either_ one `/` mounted Virtual Folder, or _many_ non-`/` mounted Virtual Folders.

**Comment by drakkan** [comment]
Nested virtual folders are already supported, we just check not to define multiple virtual folders that point to the same virtual path. For the local filesystem SFTPGo does not allow virtual folders with overlapping mapped paths (this will make calculating the quota very difficult), for cloud backends this check is very difficult to do and the user is free to overlay the mapped paths (if he does the quota update will be wrong). 

I did the modifications required to allow to mount a virtual folder to `/`, it seems to work fine with few changes but I have to do accurate tests for the edge cases. The only bad thing is that you need to define a local filesystem anyway and it will be hidden from the mounted virtual folder. I'll think about it a little more but it might be acceptable

**Comment by drakkan** [comment]
It should work now, please let me know if you find any issues. This feature need to stay in the development branch for a bit, it will be included in v2.3.0. You can test using one of the latest edge based docker images or you can download a package for your OS/arch from the [actions](https://github.com/drakkan/sftpgo/actions) page

**Comment by shrink** [comment]
I've just tested it out and it works perfectly: thank you very much for the fast turnaround, much appreciated :)

**Comment by drakkan** [comment]
This can also be done using [groups](https://github.com/drakkan/sftpgo/blob/main/docs/groups.md) now. 

The featured introduced here is still useful and will remain

**Comment by shrink** [comment]
@drakkan that's a great feature, we'll definitely check that out: I think Groups would work very well for our use-case and actually make some other aspects of how we're using SFTPGo easier. Thank you!

**Comment by drakkan** [comment]
@shrink thanks to you, if all the companies that use SFTPGo made a small recurring donation like you do, I would have much more time to work on the project
