### ISSUE TITLE
SftpGo sending Upload action on transfer error

### ISSUE THREAD

**Issue by derekbking** [drakkan/sftpgo#786]
Hi,

We are seeing some intermittent issues with FTP file uploads. It seems somehow a closed connection is being used during uploads. When this happens it seems Sftpgo will reject the upload which seems okay to do in the case. The problem is that we still get an upload completed event sent to our API for a file that failed to upload. The client will retry the upload and send us another upload completed event once the file successfully uploads.

`{"level":"error","time":"2022-04-04T20:14:05.174","sender":"FTP","connection_id":"FTP_0_14","message":"stat error for path \"/S2-Internal-FTP-04.04.2022.03.10.25.PM.-05.test0391\": stat /RPS703/FLWHII/Landing/ENDIE14/1/S2-Internal-FTP-04.04.2022.03.10.25.PM.-05.test0391: no such file or directory"}
{"level":"debug","time":"2022-04-04T20:14:05.298","sender":"RetryableHTTPClient","method":"POST","url":"http://host.docker.internal:40030/api/SftpGo/Action","message":"performing request"}
{"level":"debug","time":"2022-04-04T20:14:05.514","sender":"FTP","message":"notified operation \"pre-upload\" to URL: http://host.docker.internal:40030/api/SftpGo/Action status code: 200, elapsed: 215.989ms err: <nil>"}
{"level":"debug","time":"2022-04-04T20:14:05.521","sender":"FTP","connection_id":"FTP_0_14","message":"transfer added, id: 196, active transfers: 1"}
{"level":"debug","time":"2022-04-04T20:14:05.524","sender":"FTP","connection_id":"FTP_0_14","message":"connection removed, local address \"172.18.0.2:21\", remote address \"172.18.0.1:42968\" close fs error: <nil>, num open connections: 0"}
{"level":"debug","time":"2022-04-04T20:14:05.527","sender":"ftpserverlib","server_id":"FTP_0","clientId":"14","clientIp":"172.18.0.1:42968","message":"Client disconnected"}
{"level":"error","time":"2022-04-04T20:14:05.528","sender":"FTP","connection_id":"FTP_0_14","message":"Unexpected error for transfer, path: \"/RPS703/FLWHII/Landing/ENDIE14/1/S2-Internal-FTP-04.04.2022.03.10.25.PM.-05.test0391\", error: \"read tcp 172.18.0.2:28057->172.18.0.1:56610: use of closed network connection\" bytes sent: 0, bytes received: 0 transfer running since 7 ms"}
{"level":"debug","time":"2022-04-04T20:14:05.529","sender":"ftpserverlib","server_id":"FTP_0","clientId":"15","clientIp":"172.18.0.1:48346","message":"Client connected"}
{"level":"debug","time":"2022-04-04T20:14:05.529","sender":"FTP","connection_id":"FTP_0_15","message":"connection added, local address \"172.18.0.2:21\", remote address \"172.18.0.1:48346\", num open connections: 1"}
{"level":"debug","time":"2022-04-04T20:14:05.547","sender":"FTP","connection_id":"FTP_0_14","message":"uploaded file size 0"}
{"level":"info","time":"2022-04-04T20:14:05.549","sender":"Upload","local_addr":"172.18.0.2:21","remote_addr":"172.18.0.1:42968","elapsed_ms":12,"size_bytes":0,"username":"int-ftp-source-6to6","file_path":"/RPS703/FLWHII/Landing/ENDIE14/1/S2-Internal-FTP-04.04.2022.03.10.25.PM.-05.test0391","connection_id":"FTP_0_14","protocol":"FTP","ftp_mode":"passive"}
{"level":"error","time":"2022-04-04T20:14:05.550","sender":"FTP","connection_id":"FTP_0_14","message":"transfer error: read tcp 172.18.0.2:28057->172.18.0.1:56610: use of closed network connection, path: \"/RPS703/FLWHII/Landing/ENDIE14/1/S2-Internal-FTP-04.04.2022.03.10.25.PM.-05.test0391\""}
{"level":"debug","time":"2022-04-04T20:14:05.551","sender":"FTP","connection_id":"FTP_0_14","message":"transfer removed, id: 196 active transfers: 0"}
{"level":"warn","time":"2022-04-04T20:14:05.552","sender":"ftpserverlib","server_id":"FTP_0","clientId":"14","err":"use of closed network connection","message":"Couldn't flush line"}
{"level":"debug","time":"2022-04-04T20:14:05.551","sender":"RetryableHTTPClient","method":"POST","url":"http://host.docker.internal:40030/api/SftpGo/Action","message":"performing request"}
{"level":"debug","time":"2022-04-04T20:14:05.563","sender":"FTP","message":"notified operation \"upload\" to URL: http://host.docker.internal:40030/api/SftpGo/Action status code: 200, elapsed: 11.702ms err: <nil>"}
{"level":"debug","time":"2022-04-04T20:14:05.618","sender":"dataprovider_sqlite","message":"external auth hook executed, response code: 200"}
{"level":"debug","time":"2022-04-04T20:14:05.619","sender":"dataprovider_sqlite","message":"external auth completed for user \"int-ftp-source-6to6\", elapsed: 68.9249ms"}
{"level":"debug","time":"2022-04-04T20:14:05.783","sender":"common","connection_id":"FTP_0_15","message":"connection swapped, close fs error: <nil>"}
{"level":"info","time":"2022-04-04T20:14:05.784","sender":"FTP","connection_id":"FTP_0_15","message":"User \"int-ftp-source-6to6\" logged in with \"password\" from ip \"172.18.0.1\""}
{"level":"debug","time":"2022-04-04T20:14:05.967","sender":"RetryableHTTPClient","method":"POST","url":"http://host.docker.internal:40030/api/SftpGo/Action","message":"performing request"}
{"level":"debug","time":"2022-04-04T20:14:06.174","sender":"FTP","message":"notified operation \"pre-upload\" to URL: http://host.docker.internal:40030/api/SftpGo/Action status code: 200, elapsed: 207.2078ms err: <nil>"}
{"level":"debug","time":"2022-04-04T20:14:06.189","sender":"FTP","connection_id":"FTP_0_15","message":"transfer added, id: 1, active transfers: 1"}
{"level":"debug","time":"2022-04-04T20:14:06.207","sender":"ftpserverlib","server_id":"FTP_0","clientId":"15","writtenBytes":"1024","message":"Stream copy finished"}
{"level":"debug","time":"2022-04-04T20:14:06.222","sender":"FTP","connection_id":"FTP_0_15","message":"uploaded file size 1024"}
{"level":"info","time":"2022-04-04T20:14:06.223","sender":"Upload","local_addr":"172.18.0.2:21","remote_addr":"172.18.0.1:48346","elapsed_ms":22,"size_bytes":1024,"username":"int-ftp-source-6to6","file_path":"/RPS703/FLWHII/Landing/ENDIE14/1/S2-Internal-FTP-04.04.2022.03.10.25.PM.-05.test0391","connection_id":"FTP_0_15","protocol":"FTP","ftp_mode":"passive"}
{"level":"debug","time":"2022-04-04T20:14:06.224","sender":"FTP","connection_id":"FTP_0_15","message":"transfer removed, id: 1 active transfers: 0"}
{"level":"debug","time":"2022-04-04T20:14:06.224","sender":"RetryableHTTPClient","method":"POST","url":"http://host.docker.internal:40030/api/SftpGo/Action","message":"performing request"}
{"level":"debug","time":"2022-04-04T20:14:06.253","sender":"FTP","message":"notified operation \"upload\" to URL: http://host.docker.internal:40030/api/SftpGo/Action status code: 200, elapsed: 28.5829ms err: <nil>"}`

Thanks!

**Comment by drakkan** [comment]
Hi,

SFTPGo notifies both successfull and failed transfers.

For failed transfers the `status` fields is != 1. Take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/custom-actions.md):

> status, integer. Status for upload, download and ssh_cmd actions. 1 means no error, 2 means a generic error occurred, 3 means quota exceeded error


From the above logs I think a zero bytes file is created and you get a notification with status = 2, can you please confirm? Thanks

**Comment by derekbking** [comment]
Yes, you're exactly right. I feel bad for asking questions that are answered in the docs. I guess I overlooked that property. Thank you for the help.

![image](https://user-images.githubusercontent.com/3951143/162471938-0ae02384-87a2-46b7-87a8-858224a61b63.png)

**Comment by drakkan** [comment]
> Yes, you're exactly right. I feel bad for asking questions that are answered in the docs. I guess I overlooked that property. Thank you for the help.
> 
> ![image](https://user-images.githubusercontent.com/3951143/162471938-0ae02384-87a2-46b7-87a8-858224a61b63.png)

No problem, the docs are not perfect ..., for example is not documented that for status = 3 SFTPGo will try to remove the uploaded file, I'll fix this in an upcoming commit
