### ISSUE TITLE
provide OIDC access token to pre-login hook

### ISSUE THREAD

**Issue by markpash** [drakkan/sftpgo#787]
Hi, I've been using sftpgo for a few weeks now and I'm really happy with it. I've specifically been using the OIDC feature, which seems to work quite well. Thanks for building such a useful piece of software.

I've had to write a few scripts and programs to be able to achieve what I want with dynamic user creation. The way I've had to implement them isn't ideal, so what I'm wondering is if there's a better way to expand on the OIDC capabilities in sftpgo, without needing to add features to sftpgo each time.

The way I propose doing this is to expose the access token to the pre-login hook when using OIDC. I believe this would allow for the hook to fetch more attributes and have more flexibility and capabilities when dynamically creating or modifying the sftpgo user.

This could also be used to drop the `sftpgo_role` code from the codebase and make it a responsibility of the pre-login hook to implement, though this part is just an idea, not part of my main proposal.

I'm also happy to discuss, help build, and test this if you agree with my idea.

**Comment by drakkan** [comment]
Hi,

do you mean the raw JSON payload of the ID Token? I was thinking of something similar, such as a setting to specify the list of ID token fields to pass to the hook. Specifying a list of fields avoids always passing the entire JSON payload.

The `sftpgo_role` field is required internally to distinguish between users and admins.

Let me a few more days to think about this request. Thanks

**Comment by markpash** [comment]
> do you mean the raw JSON payload of the ID Token?
Well, I initially meant to actually pass the access token that is returned by oauth2, which I believe sftpgo gets when authenticating with the OIDC provider. If this were given to the hook, then I believe the hook can also act on behalf of the user, and perform API requests to get more details about the user, or potentially access other resources as that user. Though I'm no expert on this, so I might be making some false assumptions about what is technically possible.

On the other hand, adding fields to the ID token on the IDP side, and then allowing sftpgo to pass those fields to the hook can also work for most use-cases. It would also solve my problems too. So I'm fine with your idea as well.

> Let me a few more days to think about this request. Thanks
I'm in no rush at all, I only need this for personal use, and it's a nice-to-have feature. So please take your time, I don't wish for a feature to end up in a release and then needing to change it later.

**Comment by drakkan** [comment]
I confirm that SFTPGo receives a short lived access token which is updated as needed.

I don't know if sharing this token could be a secuirty risk, I prefer a more controlled solution, I'll allow to pass custom token fields based on a new configuration parameter. I think this should allow for any customization, however until this is included in a release I can still modify these APIs.

**Comment by markpash** [comment]
> I confirm that SFTPGo receives a short lived access token which is updated as needed.
> 
> I don't know if sharing this token could be a secuirty risk, I prefer a more controlled solution, I'll allow to pass custom token fields based on a new configuration parameter. I think this should allow for any customization, however until this is included in a release I can still modify these APIs.

Thanks, I think this is enough for my use-case at least. I'll give this a go when I get the time and share an example pre-login hook script.
