### ISSUE TITLE
Exceeding the maximum number of sessions queue mechanism

### ISSUE THREAD

**Issue by faer615** [drakkan/sftpgo#788]
Hello:
In the process of using sftpgo, I found that when the user max sessions exceeds the upper limit, the task will be discarded after multiple attempts to connect failed.
I think when the user exceeds max sessions, use the queue to wait, instead of discarding the task after retries many times, unless the user abandons the task by himself, can this be set?

**Comment by drakkan** [comment]
Currently a new connection is immediately closed if the maximum number of sessions is exceeded. The client can try again and if one of the active connections is closed the new connection will be allowed.

If we queue the connection server side, we still have to set an upper limit to avoid DoS-style attacks and refuse the new connection if this limit is reached. I don't plan to work on this myself, sorry
