### ISSUE TITLE
User is able to connect with more session than the maximum session.

### ISSUE THREAD

**Issue by Lebvanih** [drakkan/sftpgo#792]
Hello,

Version used: SFTPGo 2.1.0-a09cf5c8-2021-06-16T16:02:16Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable.
Backend: S3 Bucket
Environment: K8S

Our issue:
- One of our customers tend to upload quite big files recently compared to the other. 
- This cause our K8S nodes to have disk pressure. We learned from this: https://github.com/drakkan/sftpgo/discussions/692, that if there is an upload of a 80G file, then we need 80G locally. Our disk is currently 200G so this is filled quite quick..
- As temporary workaround (time for us to swap to dedicated volumes for the temp folder) we tried to reduce the amount of session that user can have. We reduced to 1 and disconnected the user (fully), however, from time to time, it seems that the user can connect twice still (from same IP) and start 2 transfers.

From the logs, they seems to be able to connect twice, then start a transfer on each.:
```{"level":"debug","time":"2022-04-13T11:44:27.404","sender":"osfs","connection_id":"3e528561a3ad9a7a00f680d17666e10d8f6644b595ff7c348b0d43abd0cc2e95","message":"root directory \"/tmp/[redacted]\" for user \"[redacted]\" does not exist, try to create, mkdir error: <nil>"}
{"level":"info","time":"2022-04-13T11:44:27.404","sender":"SSH","connection_id":"3e528561a3ad9a7a00f680d17666e10d8f6644b595ff7c348b0d43abd0cc2e95","message":"User id: 38, logged in with: \"password\", username: \"[redacted]\", home_dir: \"/tmp/[redacted]\" remote addr: \"[redacted]\""}
{"level":"debug","time":"2022-04-13T11:44:27.410","sender":"dataprovider_postgresql","message":"last login updated for user \"[redacted]\""}
{"level":"debug","time":"2022-04-13T11:44:27.414","sender":"common","connection_id":"3e528561a3ad9a7a00f680d17666e10d8f6644b595ff7c348b0d43abd0cc2e95","message":"ssh connection added, num open connections: 1"}
{"level":"info","time":"2022-04-13T11:44:27.440","sender":"SSH","connection_id":"78acf17871dc3743d4eb2ff129b7c38979167eb6f4e1822accdcfd4019393f7f","message":"User id: 38, logged in with: \"password\", username: \"[redacted]\", home_dir: \"/tmp/[redacted]\" remote addr: \"[redacted]\""}
{"level":"debug","time":"2022-04-13T11:44:27.446","sender":"dataprovider_postgresql","message":"last login updated for user \"[redacted]\""}
```
If I manually kill one of the 2 connections, the second one is unable to connect as the max session is reached.
``` 
{"level":"debug","time":"2022-04-13T11:53:57.158","sender":"sftpd","message":"authentication refused for user: \"[redacted]\", too many open sessions: 1/1"}
{"level":"debug","time":"2022-04-13T11:53:57.158","sender":"connection_failed","client_ip":"[redacted]","username":"[redacted]","login_type":"password","protocol":"SSH","error":"too many open sessions: 1"}
{"level":"debug","time":"2022-04-13T11:53:57.189","sender":"sftpd","message":"failed to accept an incoming connection: [ssh: no auth passed yet, Authentication error: could not validate password credentials: too many open sessions: 1]"}
{"level":"debug","time":"2022-04-13T11:53:57.721","sender":"sftpd","message":"authentication refused for user: \"[redacted]\", too many open sessions: 1/1"}
{"level":"debug","time":"2022-04-13T11:53:57.721","sender":"connection_failed","client_ip":"[redacted]","username":"[redacted]","login_type":"password","protocol":"SSH","error":"too many open sessions: 1"}
{"level":"debug","time":"2022-04-13T11:53:57.750","sender":"sftpd","message":"failed to accept an incoming connection: [ssh: no auth passed yet, Authentication error: could not validate password credentials: too many open sessions: 1]"}
{"level":"debug","time":"2022-04-13T11:53:58.169","sender":"sftpd","message":"authentication refused for user: \"[redacted]\", too many open sessions: 1/1"}
{"level":"debug","time":"2022-04-13T11:53:58.169","sender":"connection_failed","client_ip":"[redacted]","username":"[redacted]","login_type":"password","protocol":"SSH","error":"too many open sessions: 1"}
```

I tried to check a bit on the repo to see if this would have been fixed in the latest version, but unless I overlooked, I don't see this issue being in there. I am planning on updating tomorrow the installation (and add a dedicated volume) so if this is fixed in the latest version I assume I will noticed it tomorrow.

To me it seems that there is a race condition that allow two client to connect at the same time if the connection attempt is done in a close enough time interval.

**Comment by drakkan** [comment]
> Hello,
> 
> I am not sure that I understand the second part of your message: `However with the current architecture the count will only work on a per-node basis. If you load balance SFTP connections across multiple nodes, each node will limit the number of sessions to 1` We currently do not loadbalance and only have a single SFTPGO node, and that node allow sometimes 2 clients while the max is at 1.

I mean that the active sessions currently are in memory so are local to the node. 

I confirm that I'm aware that the session count must be fixed even on single node setups

**Comment by Lebvanih** [comment]
Ok, this make me sense now. 

Thank you for confirming. I will check internally how we will address this issue.

**Comment by drakkan** [comment]
you should sponsor a project that you rely on, but this only happens in an ideal world, most of the people here are just looking for a free software and a free step by step support  (I am not referring to you in particular). I also have a demanding job and it is not so easy to find the time to work for others :worried: 

I totally agree with these posts from Filippo Valsorda

https://words.filippo.io/pay-maintainers/
https://words.filippo.io/professional-maintainers/

anyway thanks for using SFTPGo
