### ISSUE TITLE
FTP enable config values

### ISSUE THREAD

**Issue by hareeshrao4839** [drakkan/sftpgo#794]
Hi 

trying to enable ftp(2021) on sftpgo along with sftp2022.

but service not starting or not listening port

"ftpd": {
    "bindings": [
      {
        "port": 2021,
        "address": "",
        "apply_proxy_config": true,
        "tls_mode": 0,
        "force_passive_ip": "",
        "passive_ip_overrides": [],
        "client_auth_type": 0,
        "tls_cipher_suites": [],
        "passive_connections_security": 0,
        "active_connections_security": 0,
        "debug": false
      }

sftp perfectly working , but ftd had issue
correct me am i missing anything here. my intention wants to enable ftp in my local n/w itself.

**Comment by drakkan** [comment]
Hi,

please post your full configuration file and the SFTPGo logs, thanks

**Comment by drakkan** [comment]
Please reopen providing more info if you still have this issue
