### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by mcdappdev** [drakkan/sftpgo#8]
I am trying to Dockerize the app and trying this:

```dockerfile
FROM golang:1.12.7-stretch
RUN mkdir /app 
ADD . /app/ 
WORKDIR /app

RUN apt-get update
RUN apt-get install -yq git-all
RUN go get -u github.com/drakkan/sftpgo
CMD ["sftpgo -config-dir /app"]
```

However, when I run it with:

`docker run -p 8080:8080 sftpgo`

I get: 

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"sftpgo -config-dir /app\": stat sftpgo -config-dir /app: no such file or directory": unknown.`

Any ideas?

**Comment by drakkan** [comment]
Hi,

not tested on docker yet, from the error message it seems you are executing the command `sftpgo -config-dir /app` and not the command `sftpgo` with arguments `-config-dir` and `/app`,

please try:

`CMD ["sftpgo", "-config-dir", "/app"]`

or:

`ENTRYPOINT ["sftpgo", "-config-dir", "/app"]`

thanks

**Comment by mcdappdev** [comment]
This is perfect, thanks!!
