### ISSUE TITLE
error if trailing backslash in config-dir (Windows)

### ISSUE THREAD

**Issue by Germs2004** [drakkan/sftpgo#80]
SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z

In Windows, I'd expect to type paths with backslashes:
`sftpgo.exe service install --config-dir="C:\ProgramData\SFTPGO\"`
but it writes an error to C:\Program Files\SFTPGo\sftpgo.log unless I use forward slashes:
`sftpgo.exe service install --config-dir="C:/ProgramData/SFTPGO/"`

```
{"level":"info","time":"2020-03-01T21:57:32.547","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z, config dir: C:\\ProgramData\\SFTPGO\", config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false"}
{"level":"warn","time":"2020-03-01T21:57:32.550","sender":"config","connection_id":"","message":"error loading configuration file: Config File \"sftpgo\" Not Found in \"[C:\\\\ProgramData\\\\SFTPGO\\\" C:\\\\Program Files\\\\SFTPGo]\". Default configuration will be used: {SFTPD:{Banner:SFTPGo_0.9.5 BindPort:2022 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0022 UploadMode:0 Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd]} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:5432 Username: Password:[redacted] SSLMode:0 ConnectionString: UsersTable:users ManageUsers:1 TrackQuota:1 PoolSize:0 UsersBaseDir: Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} ExternalAuthProgram: ExternalAuthScope:0} HTTPDConfig:{BindPort:8080 BindAddress:127.0.0.1 TemplatesPath:templates StaticFilesPath:static BackupsPath:backups}}"}
{"level":"warn","time":"2020-03-01T21:57:32.551","sender":"sqlite","connection_id":"","message":"sqlite database file does not exists, please be sure to create and initialize a database before starting sftpgo"}
{"level":"error","time":"2020-03-01T21:57:32.551","sender":"service","connection_id":"","message":"error initializing data provider: CreateFile C:\\ProgramData\\SFTPGO\"\\sftpgo.db: The filename, directory name, or volume label syntax is incorrect."}
```

You'll also notice that the log file has way too many slashes in it.  Looks like you're trying to escape characters using slashes, but that ends up printing them incorrectly to the log:
`Config File \"sftpgo\" Not Found in \"[C:\\\\ProgramData\\\\SFTPGO\\\" C:\\\\Program Files\\\\SFTPGo]\".`

**Comment by drakkan** [comment]
> SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z
> 
> In Windows, I'd expect to type paths with backslashes:
> `sftpgo.exe service install --config-dir="C:\ProgramData\SFTPGO\"`
> but it writes an error to C:\Program Files\SFTPGo\sftpgo.log unless I use forward slashes:
> `sftpgo.exe service install --config-dir="C:/ProgramData/SFTPGO/"`
> 

Please help me to reproduce the issue, I just tryed this and I was unable to replicate it:

1) path with backslashs notations seems accepted
2) changing the path using forward slashes does not change the log file location for me, it defaults to `sftpgo.log` so it is relative to the current directory. To set the log file location you have to use `-l` flag, please take a look at the install command used inside the windows setup (it uses backslash pat notation too):

https://github.com/drakkan/sftpgo/blob/master/sftpgo.iss#L65

Are you trying to customize things? This is fine, of course, but please list all the steps so I can reproduce and so fix the issue, thanks

> ```
> {"level":"info","time":"2020-03-01T21:57:32.547","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z, config dir: C:\\ProgramData\\SFTPGO\", config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false"}
> {"level":"warn","time":"2020-03-01T21:57:32.550","sender":"config","connection_id":"","message":"error loading configuration file: Config File \"sftpgo\" Not Found in \"[C:\\\\ProgramData\\\\SFTPGO\\\" C:\\\\Program Files\\\\SFTPGo]\". Default configuration will be used: {SFTPD:{Banner:SFTPGo_0.9.5 BindPort:2022 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0022 UploadMode:0 Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd]} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:5432 Username: Password:[redacted] SSLMode:0 ConnectionString: UsersTable:users ManageUsers:1 TrackQuota:1 PoolSize:0 UsersBaseDir: Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} ExternalAuthProgram: ExternalAuthScope:0} HTTPDConfig:{BindPort:8080 BindAddress:127.0.0.1 TemplatesPath:templates StaticFilesPath:static BackupsPath:backups}}"}
> {"level":"warn","time":"2020-03-01T21:57:32.551","sender":"sqlite","connection_id":"","message":"sqlite database file does not exists, please be sure to create and initialize a database before starting sftpgo"}
> {"level":"error","time":"2020-03-01T21:57:32.551","sender":"service","connection_id":"","message":"error initializing data provider: CreateFile C:\\ProgramData\\SFTPGO\"\\sftpgo.db: The filename, directory name, or volume label syntax is incorrect."}
> ```
> 
> You'll also notice that the log file has way too many slashes in it. Looks like you're trying to escape characters using slashes, but that ends up printing them incorrectly to the log:
> `Config File \"sftpgo\" Not Found in \"[C:\\\\ProgramData\\\\SFTPGO\\\" C:\\\\Program Files\\\\SFTPGo]\".`

the log files are in JSON format, `\` is a special character in JSON and it is escaped, the JSON escape character is `\` so a new backslash is added before each backslash

**Comment by Germs2004** [comment]
Sorry for the lack of info before.  I was typing with one hand, holding my new baby in the other arm :)  I didn't mean that the location of the log file should have changed, I meant that the log file wrote an "error" (about not finding the config file) instead of a happy message whenever I used the "windows" slashes.  If I use the "linux" slashes, the log doesn't write that error (and it successfully finds the config file).

Windows 10 Pro v1909

Here's the approximate steps I did:
1) Install sftpgo using sftpgo_0.9.5_windows_x86_64.exe
2) "C:\Program Files\SFTPGo\sftpgo.exe" service uninstall
3) "C:\Program Files\SFTPGo\sftpgo.exe" service install --config-dir="C:\ProgramData\SFTPGO\"
4) netsh advfirewall firewall add rule name="SFTPGo Service" dir=in action=allow program="C:\Program Files\SFTPGo\sftpgo.exe"
5) create a mostly default config file at "C:\ProgramData\SFTPGO\sftpgo.json"
6) "C:\Program Files\SFTPGo\sftpgo.exe" service start

Now, run `"C:\Program Files\SFTPGo\sftpgo.exe" service status` and see that this says "stopped"

And look at the log file `C:\Program Files\SFTPGo\sftpgo.log`.  Here's the full contents of my log:

```
{"level":"info","time":"2020-03-02T13:18:22.659","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z, config dir: C:\\ProgramData\\SFTPGO\", config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false"}
{"level":"warn","time":"2020-03-02T13:18:22.667","sender":"config","connection_id":"","message":"error loading configuration file: Config File \"sftpgo\" Not Found in \"[C:\\\\ProgramData\\\\SFTPGO\\\" C:\\\\Program Files\\\\SFTPGo]\". Default configuration will be used: {SFTPD:{Banner:SFTPGo_0.9.5 BindPort:2022 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0022 UploadMode:0 Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd]} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:5432 Username: Password:[redacted] SSLMode:0 ConnectionString: UsersTable:users ManageUsers:1 TrackQuota:1 PoolSize:0 UsersBaseDir: Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} ExternalAuthProgram: ExternalAuthScope:0} HTTPDConfig:{BindPort:8080 BindAddress:127.0.0.1 TemplatesPath:templates StaticFilesPath:static BackupsPath:backups}}"}
{"level":"warn","time":"2020-03-02T13:18:22.682","sender":"sqlite","connection_id":"","message":"sqlite database file does not exists, please be sure to create and initialize a database before starting sftpgo"}
{"level":"error","time":"2020-03-02T13:18:22.682","sender":"service","connection_id":"","message":"error initializing data provider: CreateFile C:\\ProgramData\\SFTPGO\"\\sftpgo.db: The filename, directory name, or volume label syntax is incorrect."}
```

Now, uninstall the service and reinstall it using Linux slashes, and start the service again:
`"C:\Program Files\SFTPGo\sftpgo.exe" service install --config-dir="C:/ProgramData/SFTPGO/"`
Here's the log output from that (notice the difference in line 2):

```
{"level":"info","time":"2020-03-02T13:23:40.026","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z, config dir: C:/ProgramData/SFTPGO/, config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false"}
{"level":"debug","time":"2020-03-02T13:23:40.064","sender":"config","connection_id":"","message":"config file used: 'C:\\ProgramData\\SFTPGO\\sftpgo.json', config loaded: {SFTPD:{Banner:Private Server BindPort:2022 BindAddress: IdleTimeout:15 MaxAuthTries:5 Umask:0022 UploadMode:1 Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd]} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:999 Username: Password:[redacted] SSLMode:0 ConnectionString: UsersTable:users ManageUsers:1 TrackQuota:0 PoolSize:0 UsersBaseDir: Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} ExternalAuthProgram: ExternalAuthScope:0} HTTPDConfig:{BindPort:8081 BindAddress: TemplatesPath:templates StaticFilesPath:static BackupsPath:backups}}"}
{"level":"warn","time":"2020-03-02T13:23:40.064","sender":"sqlite","connection_id":"","message":"sqlite database file does not exists, please be sure to create and initialize a database before starting sftpgo"}
{"level":"error","time":"2020-03-02T13:23:40.064","sender":"service","connection_id":"","message":"error initializing data provider: CreateFile C:\\ProgramData\\SFTPGO\\sftpgo.db: The system cannot find the file specified."}

```

RE: the second issue:
Ok, the log is in JSON format.  I don't think I've ever seen a log written in that format before, so I wasn't expecting all the slashes.  Though it makes the paths harder to copy/paste or verify correctness, I guess it's unavoidable since it's JSON.  Thanks for the explanation.

**Comment by drakkan** [comment]
Well this is strange please take a look at the following screen:

![Schermata del 2020-03-02 19-53-37](https://user-images.githubusercontent.com/553263/75707694-a2ea6280-5cbf-11ea-9c0c-ca9dc895cb97.png)

these are the commands you described with a different path, and I have these logs (the database is missing):

```
{"level":"info","time":"2020-03-02T19:50:35.333","sender":"service","connection_id":"","message":"starting SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z, config dir: E:\\sftpgo, config file: sftpgo, log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false"}
{"level":"debug","time":"2020-03-02T19:50:35.337","sender":"config","connection_id":"","message":"config file used: 'E:\\sftpgo\\sftpgo.json', config loaded: {SFTPD:{Banner:SFTPGo_0.9.5 BindPort:2022 BindAddress: IdleTimeout:15 MaxAuthTries:0 Umask:0022 UploadMode:0 Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} Keys:[] IsSCPEnabled:false KexAlgorithms:[] Ciphers:[] MACs:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd]} ProviderConf:{Driver:sqlite Name:sftpgo.db Host: Port:5432 Username: Password:[redacted] SSLMode:0 ConnectionString: UsersTable:users ManageUsers:1 TrackQuota:2 PoolSize:0 UsersBaseDir: Actions:{ExecuteOn:[] Command: HTTPNotificationURL:} ExternalAuthProgram: ExternalAuthScope:0} HTTPDConfig:{BindPort:8080 BindAddress:127.0.0.1 TemplatesPath:templates StaticFilesPath:static BackupsPath:backups}}"}
{"level":"warn","time":"2020-03-02T19:50:35.337","sender":"sqlite","connection_id":"","message":"sqlite database file does not exists, please be sure to create and initialize a database before starting sftpgo"}
{"level":"error","time":"2020-03-02T19:50:35.337","sender":"service","connection_id":"","message":"error initializing data provider: CreateFile E:\\sftpgo\\sftpgo.db: The system cannot find the file specified."}
```

this is on a windows 7 VM (I'll try on Windows 10 as soon as I find some time to install a new virtual machine). 

In the meantime please follow the steps described in the issue #82 to get SFTPGo up and running

**Comment by Germs2004** [comment]
Yes, it is interesting that you get different results.

![image](https://user-images.githubusercontent.com/5519340/75709928-a1a24100-5c91-11ea-8c4c-4233addbdfa3.png)

**Comment by Germs2004** [comment]
Thank you for posting your screenshot.  I found the problem.  I wrote my config-dir with a trailing slash and you did not:

This works:
`--config-dir="C:/ProgramData/SFTPGO/"`
and this works:
`--config-dir="C:\ProgramData\SFTPGO"`
but this does not:
`--config-dir="C:\ProgramData\SFTPGO\"`

So looks like a quick user input validation would solve that by automatically ignoring an unwanted trailing slash.  I have that problem all the time with my programs too.  I personally prefer trailing slashes to denote a folder vs a file, but if you automatically clean up the input, then it won't matter which one a user uses.

**Comment by drakkan** [comment]
Ok I can reproduced now, and sftpgo now clean the user input but please note that `\` is an escape char in windows too, so this command will not work anyway:

`--config-dir="C:\ProgramData\SFTPGO\" -l "...."`

because you are escaping the `"` char after `SFTPGO`, these will work now: 

`--config-dir="C:\ProgramData\SFTPGO\"` with no other flag after the unclosed `"`
`--config-dir=C:\ProgramData\SFTPGO\ -l "C:\ProgramData\sftpgo.log"`
