### ISSUE TITLE
send the link to someone

### ISSUE THREAD

**Issue by wiebereu** [drakkan/sftpgo#800]
I test this software and it looks great. However i didn't find a way to copy a shared link to send it by mail for someone to download. 
If i click on the link of the share it only gives me the option to download the share as a zip of to download it directly. I want to be able to copy just the link to send for someone else to open. 

I test it as a test user, not as admin

**Comment by drakkan** [comment]
Hi,

you can right click on the link URL and copy it

![Schermata del 2022-04-22 09-33-54](https://user-images.githubusercontent.com/553263/164628630-0148b6cd-cc6f-4f36-8006-91a97856caab.png)

**Comment by wiebereu** [comment]
> Hi,
> 
> you can right click on the link URL and copy it
> 
> ![Schermata del 2022-04-22 09-33-54](https://user-images.githubusercontent.com/553263/164628630-0148b6cd-cc6f-4f36-8006-91a97856caab.png)

Thanks! 

Is there a way also to connect to an outside FTP server?

**Comment by drakkan** [comment]
If you mean to use an external FTP server as storage this is not supported

**Comment by wiebereu** [comment]
> If you mean to use an external FTP server as storage this is not supported

No i was meaning connect to an FTP server and download files which are on that server.

**Comment by drakkan** [comment]
> > If you mean to use an external FTP server as storage this is not supported
> 
> No i was meaning connect to an FTP server and download files which are on that server.

No sorry, we support FTP and other protocols as server not as client
