### ISSUE TITLE
About Temp File Storage

### ISSUE THREAD

**Issue by MorpheusZero** [drakkan/sftpgo#801]
First--Do you have a Discord (or something similar) where I can ask community questions or is this the correct place to ask a question about the software?

Next--

I have been evaluating this tool for my company to use and I think it's going to fit all of our needs. We need an SFTP Server that can use GCS as the backend storage medium. Everything seemingly works fine. The one thing I'm having trouble figuring out, and that is causing concern from higher ups during my demo is storage of temporary files and how that works. I can't seem to find that information in the docs (if I overlooked it and you can point me there that would be great!).

Just a pre-req here: I am using the official Docker Image v2.2.2 in my deployment.

1. When I setup a user to have a GCS Connection--it asks me for for my Service Account Credentials JSON file. When I put that information in there, where does it go? I looked in the MySQL DB and I can't find anywhere its storing that info. I can open a bash terminal into the running container but I can't find anywhere my Credentials file is being stored in the filesystem either, so how are you re-using this information with every request later?

2. When I use something like Filezilla to open an SFTP connection and upload a file to my GCS Bucket--is that file going straight to GCS or is it being copied to the filesystem that SFTPGo is running on first and then synced over to GCS? It seems to me like its going straight to GCS, but this is one thing I need to know about for my superiors. I tried uploading a 1GB file to see if while it was uploading I could find it anywhere in the filesystem and I couldnt--then when it was done I checked GCS immediately and it was there, so I imagine its not getting saved to the filesystem at all, but I want to be sure.

Thanks for any help or answers you can provide! I love this tool!

EDIT: After looking at the discussion boards below I learned about some new configuration options--but it looks to be deprecated.
```
prefer_database_credentials, boolean. When true, users' Google Cloud Storage credentials will be written to the data provider instead of disk, though pre-existing credentials on disk will be used as a fallback. When false, they will be written to the directory specified by credentials_path. ⚠️ Deprecation warning: this setting is deprecated and it will be removed in future versions, we'll use true as default and will remove prefer_database_credentials and credentials_path.
```

So according to this--this setting should default to TRUE now and it should exist in my DB somewhere? Where can I find this?

**Comment by drakkan** [comment]
Hi,

I confirm that discussions are the right please for ask questions.

`prefer_database_credentials` is `false` by default in v2.2.x, it is `true` by default in the development version. I probably remove this option before v2.3.0 and `true` will be assumed.
In your case your Google Cloud credentials are in the configured `credentials_path`. If you use the default settings it should be `/var/lib/sftpgo/credentials` within the container.

The local storage requirement was discussed in detail [here](https://github.com/drakkan/sftpgo/discussions/692). The short answer is that there files are not copied locally and then synced, we use an unliked file just to support random access writes without the need to keep the whole file in memory. An unliked file will be always deleted even if SFTPGo crashes

**Comment by MorpheusZero** [comment]
Thanks for your help! I will close this and put any further questions in the discussions board!
