### ISSUE TITLE
`pre_login_hook` not running for ftp protocol

### ISSUE THREAD

**Issue by iwyg** [drakkan/sftpgo#802]
Hi there

Seems like the `pre_login_hook` is not firing when connecting via ftp. sftp works fine. Is this simply not possible, or am I missing something here?

Kind Regards

**Comment by drakkan** [comment]
Hi,

the hook should be called every time a user authenticates, regardless of the protocol, please look at or post the SFTPGo logs

**Comment by iwyg** [comment]
Ok so this is weird. I've checked the logs to confirm there's no pre-login entry when using the ftp protocol.  
I'm also using an auth plugin with passwords only scope. Disabling the plugin or changing the scope to something not containing this scope and the `pre_login_hook` fires when connecting via FTP. 
This is also true when using http (not oidc) login 

OIDC, SSH seem fine though

**Comment by drakkan** [comment]
If you use an auth plugin the pre-login hook is not executed, you can return the user from your plugin

**Comment by iwyg** [comment]
Oh ok, this clarifies this

I guess my confusion is from the fact that pre_login_hook firing when using sftp (because it's initially ignored by the auth plugin scope (1))?

```
sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:24.660","sender":"dataprovider_sqlite","message":"pre-login hook completed, elapsed: 3.9249571s"}
sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:24.675","sender":"dataprovider_sqlite","message":"user \"testuser\" added/updated from pre-login hook response, id: 0"}
sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:24.680","sender":"connection_failed","client_ip":"172.18.0.1","username":"testuser","login_type":"publickey","protocol":"SSH","error":"invalid credentials"}
sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:59.216","sender":"dataprovider_sqlite","message":"plugin auth completed for user \"testuser\", elapsed: 207.4668ms,auth scope: 1"}
sftpgo_1  | {"level":"info","time":"2022-04-22T11:29:59.327","sender":"SSH","connection_id":"9bfb061c1fd47863d028ec411f46216166a5a9139728c91225fb31ed1406842c","message":"User \"testuser\" logged in with \"password\", from ip \"172.18.0.1\", client version \"SSH-2.0-OpenSSH_8.1\""}
sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:59.335","sender":"dataprovider_sqlite","message":"last login updated for user \"testuser\""}
sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:59.336","sender":"common","connection_id":"9bfb061c1fd47863d028ec411f46216166a5a9139728c91225fb31ed1406842c","message":"ssh connection added, num open connections: 1"}
sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:59.339","sender":"SFTP","connection_id":"SFTP_9bfb061c1fd47863d028ec411f46216166a5a9139728c91225fb31ed1406842c_1","message":"connection added, local address \"172.18.0.2:2022\", remote address \"172.18.0.1:58022\", num open connections: 1"}
```

**Comment by drakkan** [comment]
> Oh ok, this clarifies this
> 
> I guess my confusion is from the fact that pre_login_hook firing when using sftp (because it's initially ignored by the auth plugin scope (1))?
> 
> ```
> sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:24.660","sender":"dataprovider_sqlite","message":"pre-login hook completed, elapsed: 3.9249571s"}
> sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:24.675","sender":"dataprovider_sqlite","message":"user \"testuser\" added/updated from pre-login hook response, id: 0"}
> sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:24.680","sender":"connection_failed","client_ip":"172.18.0.1","username":"testuser","login_type":"publickey","protocol":"SSH","error":"invalid credentials"}
> sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:59.216","sender":"dataprovider_sqlite","message":"plugin auth completed for user \"testuser\", elapsed: 207.4668ms,auth scope: 1"}
> sftpgo_1  | {"level":"info","time":"2022-04-22T11:29:59.327","sender":"SSH","connection_id":"9bfb061c1fd47863d028ec411f46216166a5a9139728c91225fb31ed1406842c","message":"User \"testuser\" logged in with \"password\", from ip \"172.18.0.1\", client version \"SSH-2.0-OpenSSH_8.1\""}
> sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:59.335","sender":"dataprovider_sqlite","message":"last login updated for user \"testuser\""}
> sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:59.336","sender":"common","connection_id":"9bfb061c1fd47863d028ec411f46216166a5a9139728c91225fb31ed1406842c","message":"ssh connection added, num open connections: 1"}
> sftpgo_1  | {"level":"debug","time":"2022-04-22T11:29:59.339","sender":"SFTP","connection_id":"SFTP_9bfb061c1fd47863d028ec411f46216166a5a9139728c91225fb31ed1406842c_1","message":"connection added, local address \"172.18.0.2:2022\", remote address \"172.18.0.1:58022\", num open connections: 1"}
> ```

yes this is the reason your ssh client uses public key and then pre logon hook is executed and after failing try password authentication as you can see from the logs

**Comment by iwyg** [comment]
Thanks again for your quick response. This really helped a lot!
