### ISSUE TITLE
Question: hook programs with arguments

### ISSUE THREAD

**Issue by iwyg** [drakkan/sftpgo#808]
Hello. I wonder it it is possible to pass options/arguments to hook programs (similar to the plugin cmd/args definition)?

**Comment by drakkan** [comment]
Hi,

this is not possible, but you can easily create a wrapper. For example you set the post connect hook to `/path/post-connect.sh` and within post-connect.sh you can run your program passing any arguments you want and propagating the env vars you need.

P.S. http based hooks generally perform much better than program hooks, you save the overhead to start an external program

**Comment by iwyg** [comment]
That's what I figured. Thanks!
