### ISSUE TITLE
initprovider missing in Windows build

### ISSUE THREAD

**Issue by Germs2004** [drakkan/sftpgo#81]
SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z

New user, I see this error in the log:
```
{"level":"warn","time":"2020-03-01T21:59:58.969","sender":"sqlite","connection_id":"","message":"sqlite database file does not exists, please be sure to create and initialize a database before starting sftpgo"}
{"level":"error","time":"2020-03-01T21:59:58.969","sender":"service","connection_id":"","message":"error initializing data provider: CreateFile C:\\ProgramData\\SFTPGO\\sftpgo.db: The system cannot find the file specified."}
```

The readme says "_For SQLite provider the database file will be auto created if missing_" so I thought I wouldn't need to run initprovider.  Seeing the error though, I ran initprovider as the readme instructs, but the executable does not recognize initprovider.
```
C:\Program Files\SFTPGo>sftpgo initprovider
Error: unknown command "initprovider" for "sftpgo"
Run 'sftpgo --help' for usage.
unknown command "initprovider" for "sftpgo"

C:\Program Files\SFTPGo>sftpgo --help
Full featured and highly configurable SFTP server

Usage:
  sftpgo [command]

Available Commands:
  help        Help about any command
  portable    Serve a single directory
  serve       Start the SFTP Server
  service     Install, Uninstall, Start, Stop and retrieve status for SFTPGo Windows Service

Flags:
  -h, --help      help for sftpgo
  -v, --version

Use "sftpgo [command] --help" for more information about a command.
```

I can't create the database so I'm stuck for now.

**Comment by drakkan** [comment]
Hi,

thanks for opening this issue and the other ones, I'll try to take a look at them,

`initprovider` was added after 0.9.5 release, anyway the windows installer should create the SQLite database for you. Do you have installed SFTPGo using the installer or in another way? Are you trying to change the database location? thanks

**Comment by laurentmenard** [comment]
Same problem.
On windows, the installer doesn't create the SQLite db.
In Linux, another problem. initprovider is not a command recognize.
As i'll like to use mysql, it seems that i need this command.

**Comment by drakkan** [comment]
@laurentmenard `initprovider` was added after 0.9.5 release and currently is available in Git version only, this is the same on Linux, MacOS and Windows, 

if you are using 0.9.5 you need to create the database yourself and then create the required structure using the appropriate sql scripts:

https://github.com/drakkan/sftpgo/tree/0.9.5/sql

if you are using 0.9.5 tag please take a look to the matching documentation and not at the docs for the current git version:

https://github.com/drakkan/sftpgo/blob/0.9.5/README.md

thanks!

**Comment by Germs2004** [comment]
> `initprovider` was added after 0.9.5 release, anyway the windows installer should create the SQLite database for you. Do you have installed SFTPGo using the installer or in another way? Are you trying to change the database location? thanks

I installed it with the installer (sftpgo_0.9.5_windows_x86_64.exe).

You're right.  I just uninstalled and reinstalled the program, and I do see a sftpgo.db file in the installation folder immediately after installation, before I ran any other commands.  Since I next installed the Windows Service using this command `"C:\Program Files\SFTPGo\sftpgo.exe" service install --config-dir="C:/ProgramData/SFTPGO/"` I was expecting to find the db file (and all the log files) in the ProgramData folder instead, and apparently so is the program since it complained that it couldn't find the db.

Perhaps the best solution is for sftpgo to mention in the log's error message that I should manually move the db file from the install path to that desired config folder.  It would also be best if the sftpgo.log file was written to the config folder (ProgramData in this example).  For security reasons, I believe the Program Files folder should be considered read-only by all programs, and all writes should be to either Program Data, AppData, or somewhere in the user's profile folder.

Thank you for your great response and effort on this program.

**Comment by Germs2004** [comment]
> Same problem.
> On windows, the installer doesn't create the SQLite db.
> In Linux, another problem. initprovider is not a command recognize.
> As i'll like to use mysql, it seems that i need this command.

Hi laurentmenard, you said the Windows installer didn't create your db file.  It did for me, so be sure you're looking in the installation folder: `C:\Program Files\SFTPGo\sftpgo.db`.  Apparently, it lives there by default, so if you want the db to be used somewhere else, you have to manually move it the first time.

**Comment by Germs2004** [comment]
Closing this issue because @drakkan explained that the initprovider feature was added after the 0.9.5 release and a default sftpgo.db file was created automatically for me by the Windows installer.  So it's not necessary to run initprovider if we just copy the default db file.
