### ISSUE TITLE
PTY allocation request failed on channel 0 shell request failed on channel 0

### ISSUE THREAD

**Issue by prabhinmp** [drakkan/sftpgo#810]
getting below error while accessing sftpgo application.
```
PTY allocation request failed on channel 0
shell request failed on channel 0
```

I have deployed the sftpgo application using the helm in the Kubernetes cluster, but always I get the below error while I access the sftp while using the below command.

ssh test@XXXXXX -p 2022

**Comment by drakkan** [comment]
Hi,

you are trying to open an SSH shell, SFTPGo does not support interactive shells (and I don't want to add support for this, we can make anything better than OpenSSH here), please open an SFTP session

```
sftp -P 2022 test@XXXXXX
```
