### ISSUE TITLE
MYSQL transaction deadlock - what is rolled back? 

### ISSUE THREAD

**Issue by n-h-mdla** [drakkan/sftpgo#812]
Hi Drakkan,

We are running a test cluster of 3x sftpgo pods (load balanced traffic) with a MariaDB Galera dataprovider to provide HA. Everything is working well, however with external user testing of multiple concurrent connections, we noticed the following logs:

`sftpgo-0/2022/04/28/sftpgo.stdout.log:{"level":"warn","time":"2022-04-28T20:30:00.103","sender":"dataprovider_mysql","message":"error updating last login for user \"redacted_username\": Error 1213: Deadlock found when trying to get lock; try restarting transaction"}`

This MYSQL error makes sense - the user is logged in multiple times, possibly on different pods and the DB has a lock on updating the last login information. However, the question is - what transaction is rolled back/dropped from SFTPGo? I see [this code](https://github.com/drakkan/sftpgo/blob/main/dataprovider/sqlcommon.go#L1068) but I am no Go expert and am not sure if the `err` function drops the entire transaction (stops the user from logging in) or if only the transaction of updating the last login is rolled back/dropped by the dataprovider.

I have tried to reproduce this error myself by opening 30-40 concurrent connections, but I cannot seem to reproduce, so I only have the logs to go off.

Appreciate any insight you could provide. Thanks!

**Comment by drakkan** [comment]
This is very specific to your installation. I only provide this type of support to project sponsors. You have to figure it out yourself, sorry
