### ISSUE TITLE
Docker: set log level

### ISSUE THREAD

**Issue by joarSv** [drakkan/sftpgo#814]
Hi, great work with sftpgo!

Can you please point me in the right direction on how to set the general sftpgo loglevel? We seem to get a log of debug messages on failing connections, which we don't need. Thanks!

Looking for something like `-e SFTPGO_LOG_LEVEL=error`

**Comment by drakkan** [comment]
Hi,

try `SFTPGO_LOG_VERBOSE=0`, see "Command line options" [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

**Comment by joarSv** [comment]
Thanks @drakkan, it works like a charm.
