### ISSUE TITLE
Embed static and template files

### ISSUE THREAD

**Issue by renard** [drakkan/sftpgo#823]
When build sftpgo requires all static and template files to be shipped along the binary.
It would be nice to use embedded files if templates or static are not found on the system. This would allow to only deploy one binary file.

Following patch provide that functionality. There are 2 drawbacks though:

* Static files must be within the package directory. Maybe creating a static module is a better idea. This however requires a change in the packaging.
* For css and js files are either read from embedded filesystem or local directory.

In addition a `dump-template` and / or `dump-static` commands could be added to dump embedded filesystem locally to allow modification.

```patch
diff --git a/httpd/server.go b/httpd/server.go
index 187edec..4fb9384 100644
--- a/httpd/server.go
+++ b/httpd/server.go
@@ -4,11 +4,14 @@ import (
        "context"
        "crypto/tls"
        "crypto/x509"
+       "embed"
        "errors"
        "fmt"
+       "io/fs"
        "log"
        "net"
        "net/http"
+       "os"
        "strings"
        "time"
 
@@ -34,6 +37,9 @@ import (
 var (
        compressor      = middleware.NewCompressor(5)
        xForwardedProto = http.CanonicalHeaderKey("X-Forwarded-Proto")
+
+       //go:embed static/*
+       httpStatic embed.FS
 )
 
 type httpdServer struct {
@@ -1332,7 +1338,16 @@ func (s *httpdServer) initializeRouter() {
        if s.enableWebAdmin || s.enableWebClient {
                s.router.Group(func(router chi.Router) {
                        router.Use(compressor.Handler)
-                       fileServer(router, webStaticFilesPath, http.Dir(s.staticFilesPath))
+                       // Check is staticFilesPath exists. If not found use embedded
+                       // filesystem for static files.
+                       _, err := os.Stat(s.staticFilesPath)
+                       if err != nil {
+                               // static directory is alway embedded.
+                               fsys, _ := fs.Sub(httpStatic, "static")
+                               fileServer(router, webStaticFilesPath, http.FS(fsys))
+                       } else {
+                               fileServer(router, webStaticFilesPath, http.Dir(s.staticFilesPath))
+                       }
                })
                if s.binding.OIDC.isEnabled() {
                        s.router.Get(webOIDCRedirectPath, s.handleOIDCRedirect)
diff --git a/util/util.go b/util/util.go
index 1357fbf..28ef2d8 100644
--- a/util/util.go
+++ b/util/util.go
@@ -25,6 +25,8 @@ import (
        "strings"
        "time"
 
+       "embed"
+
        "github.com/google/uuid"
        "github.com/lithammer/shortuuid/v3"
        "github.com/rs/xid"
@@ -43,6 +45,9 @@ var (
        xRealIP        = http.CanonicalHeaderKey("X-Real-IP")
        cfConnectingIP = http.CanonicalHeaderKey("CF-Connecting-IP")
        trueClientIP   = http.CanonicalHeaderKey("True-Client-IP")
+
+       //go:embed templates/*
+       templates embed.FS
 )
 
 // IsStringInSlice searches a string in a slice and returns true if the string is found
@@ -323,10 +328,19 @@ func LoadTemplate(base *template.Template, paths ...string) *template.Template {
                if err == nil {
                        t, err = base.ParseFiles(paths...)
                }
+               // If paths are not found, use embedded files
+               if err != nil {
+                       t, err = base.ParseFS(templates, paths...)
+               }
        } else {
                t, err = template.ParseFiles(paths...)
        }
 
+       // If paths are not found, use embedded files
+       if err != nil {
+               t, err = base.ParseFS(templates, paths...)
+       }
+
        if err != nil {
                logger.ErrorToConsole("error loading required template: %v", err)
                logger.Error(logSender, "", "error loading required template: %v", err)
```

Let me know if there is specific reason to not use embedded filesystem.

**Comment by drakkan** [comment]
Hi,

Thank you for your suggestion. Embedfs has been available since Go 1.16, so when I started writing SFTPGo was not available. I've never thought about using embedfs until now, so I would need to do some testing before merging such a feature.

Some SFTPGo users use external CSS files to customize the UI or to add a logo to the login screen. See [here](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L259), from the docs:

> `extra_css`, list of structs. Defines additional CSS files. Each struct has the following fields:
      - `path`, string. Path to the CSS file relative to `static_files_path`. For example, if you create a directory named `extra_css` inside the static dir and put the `my.css` file in it, you must set `/extra_css/my.css` as path.

The extra css files can reference existing or new resources (images or other files) by path.
Will this feature continue to work without rebuilding SFTPGo if we embed the static files? 

Can you also please explain your use case? If you use one of the available SFTPGo packages you don't have to change nothing to configure static files and templates paths. Additionally in v2.3.0 I also added a basic [auto discovery](https://github.com/drakkan/sftpgo/commit/80da2dc722ff50f64a73ee5c1955bfd8de89dc27) feature.
Are you using a custom build/deploy process? If you are on macOS and currently install SFTPGo manually, a homebrew package will be available soon.

Thanks

**Comment by renard** [comment]
I was facing the case when I built the sftpgo binary on one machine and need to deploy on one another. If the template or static files are not found on the new machine, the sftpgo binary refuses to start.

I was then thinking to allow to start even if those files are absent (If not found, the embedded version is served). In other words if the files provided by a package are present they will be used, the built-in version is used otherwise.

I haven't check al the ins and outs of such a change, it is only a quick (and dirty) suggestion (that's why I didn't opened a MR).


My initial goal was to only use a single binary file instead of the binary and static files.

Maybe there is no room fo such feature.

**Comment by drakkan** [comment]
I'm not saying I don't want to add this feature, it might be useful but we need to try not to break current use cases and/or make it configurable with a build tag. I need to find some time to better understand the impact

**Comment by renard** [comment]
No problem. This issue can be flagged as enhancement for further notice.
