### ISSUE TITLE
Setting up pre-made folders

### ISSUE THREAD

**Issue by Husky110** [drakkan/sftpgo#824]
Hi,  
I am not sure if I just didn't find it in the docs or if it's just impossible...
My situation is this:  
I'm setting up the docker-container for sftpgo via a StackScript on Linode (StackScripts are basically glorified bash-scripts). Then I create a volume and run the container with -v /path/to/my/volume:/srv/sftpgo and create some folders in there (like data_in and data_out). Before running the container, I do a chown -R 1000:1000 on the /path/to/my/volume.  
When I run the container and setup my admin user, I would expect to see my data_in and data_out folder already beeing there, but it isn't.   
Am I expecting here something I shouldn't or did I miss a configuration-step somewhere?  

Greetings

**Comment by drakkan** [comment]
Hi,

folders are not created based on the filesystem contents, they can point to a filesystem folder or to cloud storage backend and they are stored within the SFTPGo data provider.

**Comment by Husky110** [comment]
Ah - okay. Thank you!. :)
So if I see this right, what i could do is to setup an instance with an admin-user and pre-set folders which I then mount into my docker-container, whereas I could create the folders which are then used by the pre-set database. Right? :)

**Comment by drakkan** [comment]
yes, you can load initial data to populate your data provider on startup, the simplest way is to configure once your users/folders/admin, save a backup from the web ui and then use this backup as initial data. Take a look at the command line options, [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

**Comment by Husky110** [comment]
Perfect! Thanks for your help! :) :+1:
