### ISSUE TITLE
User impersonation in support of FS ACLs?

### ISSUE THREAD

**Issue by ElPistoler0** [drakkan/sftpgo#827]
Hi drakkan, LOVE your awesome work! Thank you for gifting us with this gem!

I noticed the sFTPGo service runs as LocalSystem in my Windows Server 2019 VM. I am using this LDAP proxy (https://github.com/orware/sftpgo-ldap-http-server) so my AD users can log in. So far everything is working as expected, except for respecting NTFS ACLs on the target directories (Local FS).

I have a folder, "Pictures", which has NTFS ACLs on it to allow access to only users A and B. When I log into sFTPGo as user C, I can still navigate to Pictures and download files (this happens because the server process is running with the highest privileges available). However User C has no access according to the NTFS ACLs.

Is there a way to enable user impersonation, so NTFS and share perms are upheld?

Thanks!

Francisco.

**Comment by drakkan** [comment]
Hi,

it is unlikely that we'll do something like [this](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/msmq/ms707075(v=vs.85)) in SFTPGo. I'm not a Windows expert and I don't know if we can do the same in another way, based on the info in this link we basically should login again.

Even on Linux we don't impersonate system users, SFTPGo has a permission system unrelated to the fs permissions. I don't know if this is applicable to your use case but from the external auth hook you can restrict permissions on a per-directory basis
