### ISSUE TITLE
suggestion: Windows Service restart behavior

### ISSUE THREAD

**Issue by Germs2004** [drakkan/sftpgo#83]
SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z
Windows

When you run `sftpgo.exe service install`, it creates a Windows service with a restart behavior of "always restart".  I suggest you change that default behavior to only restart twice, and then if it fails a third time, let it stay stopped.  The other Issue I created demonstrates a reason for this: it keeps restarting over and over, and crashes every time.  It would be better if it gave up and quit wasting resources.  It's doubtful that a service that crashes twice in a row will be successful the third time, so please don't tell it to restart infinitely, just twice.

![image](https://user-images.githubusercontent.com/5519340/75643292-8c370380-5c0c-11ea-833d-bc4179b0d6b2.png)

**Comment by drakkan** [comment]
Fixed, thanks for the suggestion
