### ISSUE TITLE
Feature: Set safe IP/Network list in env variables

### ISSUE THREAD

**Issue by js-timbirkett** [drakkan/sftpgo#831]
Hi 👋 

I'd like to be able to pass in safe IPs and Networks as a string rather than a file. This would make cloud deployments onto things like Fargate much nicer as I could whitelist the NLB IP range and prevent it from being blocked due to plain old TCP connection healthchecks.

Are there any objections to me opening a PR for this feature?

Thanks!

**Comment by drakkan** [comment]
Hi,

my long term goal is to move safe/block lists and other file based configuration to the data provider (or at least make them configurable). Setting short lists as strings in the config file could be acceptable. Separate files are useful for large lists.

Don't you already need other files? For example SSH host keys or certificates for HTTPS/FTPS

**Comment by drakkan** [comment]
> Hi @drakkan - I let SFTPGo generate host keys, and they're stored on EFS mounted to `/var/lib/sftpgo` so they persistent restarts of the service.
> 

I'm not very familiar with Fargate, but you might as well put your safelist there

> For HTTPS I'm offloading TLS on the NLB as there's not really a simple way to automate certs in the SFTPGo container, maybe a LetsEncrypt integration would be useful for cert automation thinking
> 

I plan to integrate caddycertmagic (or the acme library included in golang/crypto) in the future. I have no definite schedule

> Something that isn't working as I thought it might is enabling security headers:
> 
> ```
> .....
>   'SFTPGO_HTTPD__BINDINGS__0__SECURITY__ENABLED': 'true',
>   'SFTPGO_HTTPD__BINDINGS__0__SECURITY__ALLOWED_HOSTS': `sftp.${props.zone.zoneName}`,
>   'SFTPGO_HTTPD__BINDINGS__0__SECURITY__CONTENT_SECURITY_POLICY': "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';base-uri 'self';form-action 'self'",
>   'SFTPGO_HTTPD__BINDINGS__0__SECURITY__STS_SECONDS': '300',
> .....
> ```
> 
> doesn't seem to produce any headers. But that is a separate issue.
> 

This should work, but please note that you need the development version. The container images available in AWS marketplace should have that support. Using the container images I offer on the marketplace help the project to become sustainable on the long term

> I think that being able to add a skeleton set of allowed/blocked IPs through env variables would be needed as having defender configured before the allow/deny rules causes loadbalancer healthchecks to get blocked, fail, and restart the container.
> 
> Would you be against me raising a PR to add the ability to configure them through configuration directly? Of course, I'll include tests, keep to the patterns in the code base and update docs. :)

If you want to contribute a such feature I'll merge it for now, I suppose these lists will be immutable and alternative to the file based ones

**Comment by js-timbirkett** [comment]
I would use the Marketplace images, sadly the organisation I work with locks Marketplace down. I have started to sponsor you a little bit each month though as SFTPGo seems a very good solution.

I'll take a look at raising a PR for the feature mentioned above and anything else that may (or may not) be useful 😄

**Comment by drakkan** [comment]
Thank you for your sponsorship, I really appreciate that even if your company does not allow you to sponsor the project or buy SFTPGo from the marketplace, you have decided to help SFTPGo with a personal sponsorship. 

I'll find time on the weekend to add this feature, I'm glad to help the people who help the project

**Comment by drakkan** [comment]
done, please let me know if it works as expected. My tests are limited to the test cases
