### ISSUE TITLE
External Authentication POST request Body has "user" field in as quoted/escaped string 

### ISSUE THREAD

**Issue by funcmike** [drakkan/sftpgo#836]
Hello,
First thanks for all Your work on project :)
Just minor question that I want ask.

Why do You send "user" field as quoted string with JSON in HTTP POST Request Body for External Authorization?
This is forcing everyone who wants to parse it to unquote it first then parse as JSON.

Link to line: https://github.com/drakkan/sftpgo/blob/c9bd08cf9ca286a23f9ba1b367a093da7045a4cc/dataprovider/dataprovider.go#L3350

**Comment by drakkan** [comment]
Hi,

I'm aware of this issue but changing it now will break all existing auth hooks

**Comment by drakkan** [comment]
It should work as expected now, I will add a backward incompatibility note when I release v2.3.0
