### ISSUE TITLE
Invalid credentials after using premade backup in deployment-process

### ISSUE THREAD

**Issue by Husky110** [drakkan/sftpgo#838]
Hi again,

This is sort of a continuation of issue #824.
Like stated there I set up an instance of sftpgo, set up the admin-user and some folders and created a json-backupfile. Now when I use said backupfile as startup.json it seems to reimport all the data, but when I try to login with "admin" and "mypw" I get "invalid credentials". Right now I'm using version 2.2.3-dev, which is automaticly installed by using the image drakkan/sftpgo:2.2.x-alpine in docker.
The container gives me the following logs:
`{"level":"warn","time":"2022-05-15T14:53:33.095","sender":"dataprovider_sqlite","message":"error authenticating user \"admin\": not found: sql: no rows in result set"}
{"level":"info","time":"2022-05-15T14:53:27.274","sender":"httpd","local_addr":"172.17.0.2:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"172.17.0.1:41736","request_id":"71060a5ae4d0/YXlmi9XHIV-000003","uri":"http://localhost:9191/web/client/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36","resp_status":200,"resp_size":4847,"elapsed_ms":1}
{"level":"info","time":"2022-05-15T14:51:48.880","sender":"httpd","local_addr":"172.17.0.2:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"172.17.0.1:41732","request_id":"71060a5ae4d0/YXlmi9XHIV-000002","uri":"http://localhost:9191/web/client/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36","resp_status":200,"resp_size":5112,"elapsed_ms":1}
{"level":"info","time":"2022-05-15T14:53:33.095","sender":"httpd","local_addr":"172.17.0.2:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"172.17.0.1:41736","request_id":"71060a5ae4d0/YXlmi9XHIV-000004","uri":"http://localhost:9191/web/client/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36","resp_status":200,"resp_size":5112,"elapsed_ms":1}
{"level":"debug","time":"2022-05-15T14:53:33.095","sender":"connection_failed","client_ip":"172.17.0.1","username":"","login_type":"password","protocol":"HTTP","error":"not found: sql: no rows in result set"}
{"level":"debug","time":"2022-05-15T14:51:48.879","sender":"connection_failed","client_ip":"172.17.0.1","username":"","login_type":"password","protocol":"HTTP","error":"not found: sql: no rows in result set"}
{"level":"warn","time":"2022-05-15T14:51:48.879","sender":"dataprovider_sqlite","message":"error authenticating user \"admin\": not found: sql: no rows in result set"}
{"level":"info","time":"2022-05-15T14:51:40.083","sender":"httpd","local_addr":"172.17.0.2:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"172.17.0.1:41732","request_id":"71060a5ae4d0/YXlmi9XHIV-000001","uri":"http://localhost:9191/web/client/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36","resp_status":200,"resp_size":4847,"elapsed_ms":1}`
Which is a bit odd tho...
I don't know if how I connect might be the issue here... I start the container with -p 127.0.0.1:9191:8080, so I can then use an SSH-Tunnel for the webinterface (calling localhost:9191 while having putty open).
Did I do something wrong here or is this realy a bug?  
I verified that the admin-user was actually set up by the container.
`{"level":"debug","time":"2022-05-15T14:44:17.365","sender":"httpd","message":"adding new admin: {ID:1 Status:1 Username:admin Password:[**redacted**] Email: Permissions:[*] Filters:{AllowList:[] AllowAPIKeyAuth:false TOTPConfig:{Enabled:false ConfigName: Secret:0xc0005d4b10} RecoveryCodes:[]} Description: AdditionalInfo: CreatedAt:1652625163162 UpdatedAt:1652625163162 LastLogin:1652625163163}, dump file: \"/ftp/startup.json\", error: <nil>"}`

**Comment by drakkan** [comment]
Hi,

based on the above logs you imported an admin. Admins can login in the web admin UI and create users. Users can login via SFTP and other supported protocols.

Just a small clarification regarding the docker image versions:

- 2.2.x images match the [2.2.x branch](https://github.com/drakkan/sftpgo/commits/2.2.x), the stable version + bugfixes, currently this is basically the same as v2.2.3
- egde images match the main branch (the development version with all the new features)

**Comment by Husky110** [comment]
Okay - maybe I was a bit unclear.
Yes - I imported an admin and I get the "invalid credentials" when I try to login into the web-interface. That is my problem. :)
Version 2.2.3-dev is what I get when I run this docker-command:
`
docker run -d -p 127.0.0.1:9191:8080 -p 2022:2022 --name sftpgo \
    --restart=always \
    -u 1000:1000 \
    -v myftpvolume:/ftp \
    -v myftpusersvolume:/var/lib/sftpgo \
    -e SFTPGO_LOADDATA_FROM=/ftp/startup.json \
    -e SFTPGO_LOADDATA_CLEAN=1 \
    drakkan/sftpgo:2.2.x-alpine
`

**Comment by drakkan** [comment]
Are you sure you are logging in to the web admin? I think you are trying to login to the webclient UI. In your logs I read

```
http://localhost:9191/web/client/login
```

this is the web client UI, not the web admin UI

**Comment by Husky110** [comment]
Ugh! Yes - this one was on me! Mixed up Client- and Admin-Login.  
Might be too tired. :)  
Thanks anyhow!
