### ISSUE TITLE
ENV vars for branding

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#839]
Having trouble mapping this, it's probably very easy but 

`SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__NAME`

shouldn't that be the case?

**Comment by drakkan** [comment]
Hi,

this looks correct, 

I guess you are not using the development version, the branding was introduced last weekend, it is not included in any tags yet

**Comment by ryjogo** [comment]
Ah yes, i'm using edge.. but getting;

![image](https://user-images.githubusercontent.com/5095277/168568176-d500f3a8-7bc1-4d39-8644-2c1b54fbbcb8.png)

It could be that on the config page a min required version is added?

**Comment by ryjogo** [comment]
logs state it picked up the text too..

```Branding:{WebAdmin:{Name:My SFTP ShortName: LogoPath: LoginImagePath: FaviconPath: DisclaimerName: DisclaimerPath: ExtraCSS:[]}```

**Comment by drakkan** [comment]
name is used as page title, to modify the text on the login page use short_name.

**Comment by ryjogo** [comment]
@drakkan branding works - but a new browser, in private mode - and i still get the token no valid. Same with a different computer..

**Comment by drakkan** [comment]
I cannot reproduce, there is something strange on your side or your instance restarts or you have multiple SFTPGo instances

**Comment by ryjogo** [comment]
hmm strange - 0 restarts: sftpgo:edge1 Pod / Created a few seconds ago / Pod Restarts: 0
and only 1 instance. 

works fine on 2.2.3..

**Comment by drakkan** [comment]
Take a look or post some logs, the only difference in the development version is that we also validate the client IP, a CSRF token can only be used by the client IP it was issued for, in v2.2.3 it is any valid token accepted.

If this is the case you should have a log like this

```
error validating CSRF token IP audience
```

**Comment by ryjogo** [comment]
@drakkan That actually is the case

`{"level":"debug","time":"2022-05-16T12:01:17.446","sender":"httpd","message":"error validating CSRF token IP audience"}`

I'm using ingress as traefik, and also haproxy further up - so i assume it's not using the correct client IP.

**Comment by drakkan** [comment]
So what if in your case the same client is seen with one IP when issuing the GET request to load the login page and with another IP when issuing the POST request to log in?

The log should contain the client IP, if you can also post a wireshark dump I can take a look at the HTTP headers and try to better understand what happens, thanks

**Comment by ryjogo** [comment]
capture sent via mail

**Comment by ryjogo** [comment]
this specific issue is closed, branding works given the ENV vars are correct. I can re-open regarding the CSRF token if needed.
