### ISSUE TITLE
error building with latest go 1.14

### ISSUE THREAD

**Issue by fdefilippo** [drakkan/sftpgo#84]
Hello, there are errors building with latest go 1.14:

# git pull
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 35 (delta 29), reused 35 (delta 29), pack-reused 0
Unpacking objects: 100% (35/35), done.
From https://github.com/drakkan/sftpgo
   7163fde..833b702  master     -> origin/master
Updating 7163fde..833b702

> go build
# github.com/drakkan/sftpgo/sftpd
sftpd/ssh_cmd.go:279:20: undefined: errors.Is
note: module requires Go 1.13

**Comment by drakkan** [comment]
Hi, this error happen for me with Go 1.12, I have Go 1.14 locally (default ArchLinux package) and it works. 

We have both go 1.13 and go 1.14 in Travis:

https://github.com/drakkan/sftpgo/blob/master/.travis.yml

and it builds there too. 

Please provide some more info about the Go version that you are using, thanks

**Comment by fdefilippo** [comment]
sorry I was wrong, I used the system go instead of the last build.
