### ISSUE TITLE
proxy_protocol clarification

### ISSUE THREAD

**Issue by tooptoop4** [drakkan/sftpgo#846]
docs say:

1, enabled. If the upstream IP is not allowed to send a proxy header the header be ignored. **Using this mode does not mean that we can accept connections with and without the proxy header. We always try to read the proxy header and we ignore** it if the upstream IP is not allowed to send a proxy header
2, required. **If the upstream IP is not allowed to send a proxy header the connection will be rejected**

both these sound same to me? as in when set to 1 it will also ignore/reject the connection?

**Comment by drakkan** [comment]
Hi,

if you set proxy_protocol to 1 and we receive a proxy header from an IP not in `proxy_allowed` then the proxy header is ignored and the connection is accepted.
If you set proxy_protocol to 2 and we receive a proxy header from an IP not in `proxy_allowed` then the connection is closed and the client disconnected
