### ISSUE TITLE
allow more than 30 seconds for external auth

### ISSUE THREAD

**Issue by tooptoop4** [drakkan/sftpgo#847]
https://github.com/drakkan/sftpgo/blob/187b9468bdc342ff4bad6a5caa7efc7c87c60e0c/dataprovider/dataprovider.go#L3421

my external auth check sometimes takes 35 seconds, would be great if this 30 second value was configurable

**Comment by drakkan** [comment]
I think it is quite unacceptable to wait 30 or more seconds every time a user logs in.
Please explain your use case better, it's hard to believe an authentication backend takes 35 seconds to authenticate a user.
It is more likely that you are running a slow-to-start script. In this case, an attacker can create a DoS by simply trying a few concurrent logins.
In this case I suggest to use an HTTP based hook.

I could increase this timeout (or you can use your own fork with this change) but I suggest to improve your hook as explained above.

**Comment by tooptoop4** [comment]
it is used for batch jobs that transfer GBs of files, so waiting a minute is ok. the authentication lookup goes to an internal entitlements service that has other dependencies which slow things down
