### ISSUE TITLE
Virtual Folders for SCP Backend

### ISSUE THREAD

**Issue by wiswesser** [drakkan/sftpgo#849]
We've been trying to use Virtual Folders to access files on a Server. Sadly this server does not speak sftp but only scp. And trying to configure it as a sftp backend results in "Unexpected EOF" Errors. Is there a reason scp as a backend is not supported? If not we'd try implementing this ourselves (and obviously pushing back our results). Anything we'd have to keep in mind for this?

Kind Regards,
Caspar Wiswesser

**Comment by drakkan** [comment]
Hi,

scp is a legacy protocol and it implements file transfers only, to add the required features you need to execute several commands over SSH (for example `ls`, `mkdir`, `mv`, `pwd`, etc..).

The above commands work on Linux, let's assume someone wants to use this backend with a server running on Windows ... the commands are not the same.

I'm not sure I'll accept a such pull request. Anyway I'll take a look, SFTPGo uses the AGPLv3 license so you need to publish your changes. Good luck!

**Comment by drakkan** [comment]
> Hi drakkan, thanks for the quick response :) I'll relay your answer to our team and we will take a look. In theory we would only need to connect to linux, so maybe we will implement this using commands over ssh. In any case if we do make changes to the sftpgo code we will of course publish them.

Ok, thanks. I check the SFTPGo forks on regular basis, so if you push your changes I'll see them. Can you confirm that you need to connect to an embedded hw that runs a limited SSH server with no SFTP support? (You could also install SFTPGo there if you have control on this hw :smile: )

**Comment by wiswesser** [comment]
We do indeed need to connect to an quite limited embedded hw that we can't update. It is not decided yet if we need to implement this, or just ignore the older models (In theory we are replacing them, but you know how it goes...). If we do end up implementing this, we'll push it back to a fork.
