### ISSUE TITLE
Relative log-file-path doesn't respect config-dir

### ISSUE THREAD

**Issue by Germs2004** [drakkan/sftpgo#85]
SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z
Windows 10

The readme currently says this:
```
--config-dir string. Location of the config dir. This directory should contain the sftpgo configuration file and **is used as the base dir for files with a relative path**
--log-file-path string. Location for the log file, **default "sftpgo.log"**
```

So when I set config-dir to C:\Program Data\sftpGo\ and leave the log-file-path as the default, I would expect to find the log file at C:\Program Data\sftpGo\sftpgo.log, but the log seems to be written to C:\Program Files\SFTPGo\sftpgo.log instead.

Sorry if I'm misunderstanding something.  I know your reply in https://github.com/drakkan/sftpgo/issues/82 says I could also override the log-file-path setting to get the desired result, but it would be nice if that relative log-file-path respected the absolute path given to config-dir, which is how I interpreted the intent of the readme.

Thank you

**Comment by drakkan** [comment]
You understand correctly what it is written, I need to improve my english! It is a bit late at my timezone I'll see if I can implement what is written without breaking compatibility later, thanks
