### ISSUE TITLE
feature: ntlm/kerberos authentication (for windows clients)

### ISSUE THREAD

**Issue by tooptoop4** [drakkan/sftpgo#850]
would be great if clients on windows server could use this to auth against sftpgo, that way they don't need to supply password or key

https://stackoverflow.com/questions/42816600/windows-system-credentials-in-go-http-ntlm-requests
https://github.com/jcmturner/gokrb5

**Comment by drakkan** [comment]
You can use your own external authentication hook or plugin for this
