### ISSUE TITLE
Supported Kex Algos server differs from sftpfs client

### ISSUE THREAD

**Issue by HLeithner** [drakkan/sftpgo#858]
Hi,

I would like to know where the limitation for the server side kex algorithms coming from https://github.com/drakkan/sftpgo/blob/187b9468bdc342ff4bad6a5caa7efc7c87c60e0c/sftpd/server.go#L57-L63 ?

For example is it possible to add diffie-hellman-group-exchange-sha256 ? It's in the sftpfs client but can't be added to the server side.

thanks

**Comment by drakkan** [comment]
It comes from golang/crypto/ssh. diffie-hellman-group-exchange-sha256 is only supported [client side](https://github.com/golang/crypto/blob/master/ssh/kex.go#L32). SFTPGo uses my golang/crypto/ssh [fork](https://github.com/drakkan/crypto/tree/sftpgo) with more KEXs, MACs and other patches. I don't plan to add server side support for `diffie-hellman-group-exchange-sha256` myself, at least for now, sorry. If you want this support please try opening an upsrtream PR, thanks

**Comment by HLeithner** [comment]
Ok thanks for the info, I think my skill level (crypto and go) doesn't match this task^^

**Comment by johnharper0602** [comment]
Could I just check please, if using v2.3.1 and I add "diffie-hellman-group-exchange-sha256" to the list of KEX, that it still will not use it as it is not catered for in the SFTPgo App?
I have done this...
_const kexAlgorithms = '"curve25519-sha256","curve25519-sha256@libssh.org","ecdh-sha2-nistp256","ecdh-sha2-nistp384","ecdh-sha2-nistp521","diffie-hellman-group14-sha256","**diffie-hellman-group-exchange-sha256**"';  
...
        environment: {
          // See full SFTPGo config here https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md
...
          'SFTPGO_SFTPD__KEX__ALGORITHMS': kexAlgorithms, 
        },_

but connection to the server is not working and is reporting:
_debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha256,ext-info-s_                                                                                          

ie, diffie-hellman-group-exchange-sha256 is not in the list (but ext-info-s is and I didn't specify that)
