### ISSUE TITLE
Suggestion: change the default config-dir for Windows

### ISSUE THREAD

**Issue by Germs2004** [drakkan/sftpgo#86]
SFTPGo 0.9.5-2be3721-2020-01-12T13:56:20Z
Windows 10

A humble suggestion:

In Windows, it's best security practice to avoid letting a program write to its own directory in C:\Program Files\.  Instead, it should write to either AppData or C:\ProgramData\.  My suggestion is to change the default value for config-dir from "." to "%ProgramData%\SFTPGo\" for Windows users, and put all the relevant files there during installation (not overwriting existing files) so that the program is ready to run.

Relevant files that I know of:
sftpgo.json (the default config file)
sftpgo.db
sftpgo.log
templates (folder)
static (folder)

**Comment by drakkan** [comment]
I like this suggestion, I'll take a look at it for the next release, thanks!

**Comment by drakkan** [comment]
Hi,

can you please test the windows setup available at the following link?

https://we.tl/t-l71yYg4NBi

The config dir is now set to `commonappdata`. This setup contains the current Git version can you please test the other enhancements you suggested too? 

In this version the `initprovider` command is available, but an already initialized SQLite database is already installed. `initprovider` is useful if you want to use a different data provider such as `MySQL` or `PostgreSQL`. 

Before installing this version please be sure to remove any previous version and the files you manually copied in "ProgramData", thanks!

**Comment by Germs2004** [comment]
My first though it that this is a major improvement!  I uninstalled the old version, deleted all the old files, and installed your new version.  It automatically put lots of files in my C:\ProgramData\SFTPGo\ folder and it automatically installed and started the Windows Service for me.  I didn't have to run any commands after the installer finished, and I could immediately access the web GUI on port 8080.  Assuming nobody has a port conflict on 8080 or 2022, this is as easy an installation as it could possibly be for a Windows user.


The service recovery settings are fixed now so it will now restart twice and then give up.  Good work.


The service's command by default is: `"C:\Program Files\SFTPGo\sftpgo.exe" service start --config-dir C:\ProgramData\SFTPGo --log-file-path C:\ProgramData\SFTPGo\logs\sftpgo.log`.  That works well, but I recommend you either remove the --log-file-path override so it uses the default value of "sftpgo.log", or change it to a nice relative path like `"C:\Program Files\SFTPGo\sftpgo.exe" service install --config-dir C:\ProgramData\SFTPGo --log-file-path logs\sftpgo.log` which appears to have identical results.


If I uninstall that default service and install it with this command, the service won't run: 
`"C:\Program Files\SFTPGo\sftpgo.exe" service install --config-dir="C:\ProgramData\SFTPGO\"`.  It doesn't appear to write any sftpgo.log file in this case so I can't see any error details.  The Windows Event Viewer still shows the unhelpful message:
```
The SFTPGo service terminated with the following service-specific error: 
Incorrect function.
```
I think it still has a bug with a trailing backslash in --config-dir.


If I uninstall that service and install it with this command (just removed the trailing backslash), the service now runs fine.
`"C:\Program Files\SFTPGo\sftpgo.exe" service install --config-dir="C:\ProgramData\SFTPGO"`.  I noticed that it created the log file in C:\ProgramData\SFTPGo\sftpgo.log, which is perfect because the default value for --log-file-path is working correctly as a relative path now.


I'm a native English speaker and I think your English is great.  I wouldn't have guessed that you weren't a native speaker.  You're doing very well :)

**Comment by Germs2004** [comment]
I also tried using my old sftpgo.db file with your new installer but the service wouldn't start.  It logged an error about a missing schema table.  It would be nice if SFTPGo would detect which version the db currently is, and automatically run any necessary schema update scripts to bring the db to the compatible version.  In effect, any old database should work with a newer program version without the user having to manually run a script.

I like seeing the new features in the web GUI when adding a user account.  You're making great progress with making this SFTP Server into a fully featured program.

**Comment by drakkan** [comment]
> My first though it that this is a major improvement! I uninstalled the old version, deleted all the old files, and installed your new version. It automatically put lots of files in my C:\ProgramData\SFTPGo\ folder and it automatically installed and started the Windows Service for me. I didn't have to run any commands after the installer finished, and I could immediately access the web GUI on port 8080. Assuming nobody has a port conflict on 8080 or 2022, this is as easy an installation as it could possibly be for a Windows user.
> 
> The service recovery settings are fixed now so it will now restart twice and then give up. Good work.
> 
> The service's command by default is: `"C:\Program Files\SFTPGo\sftpgo.exe" service start --config-dir C:\ProgramData\SFTPGo --log-file-path C:\ProgramData\SFTPGo\logs\sftpgo.log`. That works well, but I recommend you either remove the --log-file-path override so it uses the default value of "sftpgo.log", or change it to a nice relative path like `"C:\Program Files\SFTPGo\sftpgo.exe" service install --config-dir C:\ProgramData\SFTPGo --log-file-path logs\sftpgo.log` which appears to have identical results.
> 
> If I uninstall that default service and install it with this command, the service won't run:
> `"C:\Program Files\SFTPGo\sftpgo.exe" service install --config-dir="C:\ProgramData\SFTPGO\"`. It doesn't appear to write any sftpgo.log file in this case so I can't see any error details. The Windows Event Viewer still shows the unhelpful message:
> 

please try the new setup here:

https://we.tl/t-eQQXuINXGo

it contains this change:

https://github.com/drakkan/sftpgo/commit/31d285813e9afe5ef89f911d0b908a8d0f8bcb83


> ```
> The SFTPGo service terminated with the following service-specific error: 
> Incorrect function.
> ```
> 
> I think it still has a bug with a trailing backslash in --config-dir.
> 
> If I uninstall that service and install it with this command (just removed the trailing backslash), the service now runs fine.
> `"C:\Program Files\SFTPGo\sftpgo.exe" service install --config-dir="C:\ProgramData\SFTPGO"`. I noticed that it created the log file in C:\ProgramData\SFTPGo\sftpgo.log, which is perfect because the default value for --log-file-path is working correctly as a relative path now.
> 
> I'm a native English speaker and I think your English is great. I wouldn't have guessed that you weren't a native speaker. You're doing very well :)

**Comment by drakkan** [comment]
> I also tried using my old sftpgo.db file with your new installer but the service wouldn't start. It logged an error about a missing schema table. It would be nice if SFTPGo would detect which version the db currently is, and automatically run any necessary schema update scripts to bring the db to the compatible version. In effect, any old database should work with a newer program version without the user having to manually run a script.
> 
> I like seeing the new features in the web GUI when adding a user account. You're making great progress with making this SFTP Server into a fully featured program.

Support for automatic database migration was added after 0.9.5 release

https://github.com/drakkan/sftpgo/commit/d6fa853a37582bb4caa7394619af9ffca0ee94d1

So if you are upgrading from 0.9.5 release you need to manually apply the required sql script, for sqlite this one:

https://github.com/drakkan/sftpgo/blob/master/sql/sqlite/20200208.sql

After 0.9.6 release this manual step will not be required anymore and the old database will be automatically updated if needed.

Since we have no database versioning in previous releases it is really difficult to automatically find the database version (for example an user could update from 0.9.1 to 0.9.6), this would require database specific logic. 

So there is a small pain for existing users while updating to the new version, while after 0.9.6 release no manual intervention is required for new users.

Another update strategy from 0.9.5 is to backup the users using the `dumpdata` REST API, remove the database so the setup will install a new empty database and then restore the users using the `loaddata` REST API. 

This can be done using, for example, the REST API CLI:

https://github.com/drakkan/sftpgo/blob/master/scripts/README.md#backup-data

**Comment by drakkan** [comment]
This should be fixed, please reopen if you still have problem with trailing /

0.9.6 will be released this weekend.

thanks for you tests and suggestions

**Comment by Germs2004** [comment]
That latest installer fixes the issue with the trailing backslash.

I've never noticed a problem with backslashes before in Windows, but I do see now [several ](https://docs.microsoft.com/en-us/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way)[articles](https://devblogs.microsoft.com/oldnewthing/20100917-00/?p=12833) talking about it.  Apparently, Microsoft made the "CommandLineToArgvW" API have a confusing behavior but they don't want to fix it now because of backwards compatibility.  I think there's a way for programs to manually parse the arguments from the command line, avoiding this problem, but it's understandable if you prefer to just tell users to not use trailing backslashes.

Thanks for all your help.

**Comment by drakkan** [comment]
> That latest installer fixes the issue with the trailing backslash.
> 
> I've never noticed a problem with backslashes before in Windows, but I do see now [several ](https://docs.microsoft.com/en-us/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way)[articles](https://devblogs.microsoft.com/oldnewthing/20100917-00/?p=12833) talking about it. Apparently, Microsoft made the "CommandLineToArgvW" API have a confusing behavior but they don't want to fix it now because of backwards compatibility. I think there's a way for programs to manually parse the arguments from the command line, avoiding this problem, but it's understandable if you prefer to just tell users to not use trailing backslashes.
> 
> Thanks for all your help.

I did what I can, the problem is that the arguments parser (we use [cobra](https://github.com/spf13/cobra) but is the same with any parser I tested) will parse something like this:

 `-c "C:\ProgramData\SFTPGO\" -l sftpgo.log`

as a single argument for the flag `-c` since the `\` escape `"`. So the current trick works only if the sequence `\"` is passed for the last argument

**Comment by drakkan** [comment]
I'm not a Windows expert but this seems the same behaviour for windows programs too, for example

```
ping -S "192.168.1.190\" 127.0.0.1
192.168.1.190" 127.0.0.1 is not a valid address.
```

or 

```

C:\Windows\system32>xcopy.exe "C:\Program Files\SFTPGo\scripts\" "C:\Program Fil
es\SFTPGo\scripts1\"
Invalid path
0 File(s) copied

C:\Windows\system32>xcopy.exe "C:\Program Files\SFTPGo\scripts" "C:\Program File
s\SFTPGo\scripts1\"
C:\Program Files\SFTPGo\scripts\README.pdf
C:\Program Files\SFTPGo\scripts\sftpgo_api_cli.exe
2 File(s) copied
```
