### ISSUE TITLE
Plain FTP in Passive mode (default) fails to retrieve directory.

### ISSUE THREAD

**Issue by CorneliousJD** [drakkan/sftpgo#861]
SFTP works and so does non-passive mode, but I have a scanner that only has passive FTP mode that I am using to scan paperless documents locally on my network, and I cannot for the life of me, get this to properly work.

Both WinSCP and FileZilla report the failure to retrieve directory listing.

![image](https://user-images.githubusercontent.com/724777/171322233-d797f9f5-0435-42ec-bd10-5f929583f1df.png)

My docker-run command is as follows. 

docker run -d 'drakkan/sftpgo'
--name='SFTPGo' 
--net='bridge' 
-e TZ="America/New_York" 
-e HOST_OS="Unraid" 
-e HOST_CONTAINERNAME="SFTPGo" 
-e 'SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP'='10.0.0.10' 
-e 'SFTPGO_FTPD__BINDINGS__0__PORT'='2121' 
-e 'SFTPGO_WEBDAVD__BINDINGS__0__PORT'='10080' 
-p '2221:8080/tcp' 
-p '2121:2121/tcp' 
-p '2022:2022/tcp' 
-p '50000-50100:50000-50100/tcp' 
-p '10080:10080/tcp' 
-v '/mnt/user/appdata/sftpgo/data':'/srv/sftpgo/data':'rw' 
-v '/mnt/user/appdata/sftpgo/backups':'/srv/sftpgo/backups':'rw' 
-v '/mnt/user/appdata/sftpgo/config':'/var/lib/sftpgo':'rw' 
-v '/mnt/user':'/unraid':'rw' 
--user 99:100

**Comment by drakkan** [comment]
Hi,

FTP passive mode works just fine, please make sure that the specified passive IP (`10.0.0.10`) is correct and that traffic to port range 50000-50100 is allowed

**Comment by CorneliousJD** [comment]
> Hi,
> 
> FTP passive mode works just fine, please make sure that the specified passive IP (`10.0.0.10`) is correct and that traffic to port range 50000-50100 is allowed

The specified passive IP should be the device I am connecting from, correct? If so I've tried multiple different IPs there but I only ever encounter the same issues or outright refusal of connection. 

Disabling passive mode works and I can connect, and SFTP works when doing test connections from devices that support it.

50000-510100 is indeed opened and allowed. Is there anything else I can do to troubleshoot this? 
I feel like it's probably something silly that I am missing somewhere but I spent a few hours on this yesterday and just cannot get it to work. It authenticates fine with SFTPGo, but it always fails to retrieve directory listing.

**Comment by drakkan** [comment]
In the above screenshot FileZilla tries to connect to `10.0.0.0` on port `50029` to get the directory listing. So it seems your passive ip is `10.0.0.0` and not `10.0.0.10`, take a look at the SFTPGo logs. Passive IP is the IP the client connects to

**Comment by CorneliousJD** [comment]
> In the above screenshot FileZilla tries to connect to `10.0.0.0` on port `50029` to get the directory listing. So it seems your passive ip is `10.0.0.0` and not `10.0.0.10`, take a look at the SFTPGo logs. Passive IP is the IP the client connects to

thanks, passive is working via FileZilla and WinSCP now -- having issues with my scanner still but that is isolated to one device now at least, I'll continue to troubleshoot that.

Thanks for the information and assistance!

**Comment by drakkan** [comment]
Hi,

maybe your scanner is using some old or less common FTP command that SFTPGo does not support. If you share a network dump or enable the FTP [debug](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L121) and share the SFTPGo logs I can take a look, thanks

**Comment by CorneliousJD** [comment]
> Hi,
> 
> maybe your scanner is using some old or less common FTP command that SFTPGo does not support. If you share a network dump or enable the FTP [debug](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L121) and share the SFTPGo logs I can take a look, thanks

I can do that -- I checked the dock here but don't see it. -- https://github.com/drakkan/sftpgo/blob/main/docker/README.md
How can I enable debug mode via an env variable w/ docker?

**Comment by drakkan** [comment]
> > Hi,
> > maybe your scanner is using some old or less common FTP command that SFTPGo does not support. If you share a network dump or enable the FTP [debug](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L121) and share the SFTPGo logs I can take a look, thanks
> 
> I can do that -- I checked the dock here but don't see it. -- https://github.com/drakkan/sftpgo/blob/main/docker/README.md How can I enable debug mode via an env variable w/ docker?

set the `SFTPGO_FTPD__BINDINGS__0__DEBUG` to `1`. 

Configuring SFTPGo via env vars is explained [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md).

**Comment by CorneliousJD** [comment]
> > > Hi,
> > > maybe your scanner is using some old or less common FTP command that SFTPGo does not support. If you share a network dump or enable the FTP [debug](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L121) and share the SFTPGo logs I can take a look, thanks
> > 
> > 
> > I can do that -- I checked the dock here but don't see it. -- https://github.com/drakkan/sftpgo/blob/main/docker/README.md How can I enable debug mode via an env variable w/ docker?
> 
> set the `SFTPGO_FTPD__BINDINGS__0__DEBUG` env var to `1`.
> 
> Configuring SFTPGo via env vars is explained [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md).

Thank you! Here's the relevant debug log.

```
{"level":"debug","time":"2022-06-02T14:14:54.185","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","clientIp":"10.0.0.202:5618","message":"Client connected"}
{"level":"debug","time":"2022-06-02T14:14:54.185","sender":"FTP","connection_id":"FTP_0_1","message":"connection added, local address \"172.17.0.38:2121\", remote address \"10.0.0.202:5618\", num open connections: 1"}
{"level":"debug","time":"2022-06-02T14:14:54.185","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","line":"220 SFTPGo 2.2.3 ready","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T14:14:54.188","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","line":"USER paperless","message":"Received line"}
{"level":"debug","time":"2022-06-02T14:14:54.188","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","line":"331 OK","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T14:14:54.196","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","line":"PASS READACTED","message":"Received line"}
{"level":"debug","time":"2022-06-02T14:14:54.403","sender":"dataprovider_sqlite","connection_id":"FTP_0_1","message":"create intermediary dir to \"/paperless\", path \"/srv/sftpgo/data/paperless/paperless\", err: <nil>"}
{"level":"debug","time":"2022-06-02T14:14:54.403","sender":"common","connection_id":"FTP_0_1","message":"connection swapped, close fs error: <nil>"}
{"level":"info","time":"2022-06-02T14:14:54.403","sender":"FTP","connection_id":"FTP_0_1","message":"User \"paperless\" logged in with \"password\" from ip \"10.0.0.202\""}
{"level":"debug","time":"2022-06-02T14:14:54.432","sender":"dataprovider_sqlite","message":"last login updated for user \"paperless\""}
{"level":"debug","time":"2022-06-02T14:14:54.432","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","line":"230 Password ok, continue","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T14:14:54.435","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","line":"CWD /paperless/","message":"Received line"}
{"level":"debug","time":"2022-06-02T14:14:54.435","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","line":"250 CD worked on /paperless","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T14:14:54.438","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","line":"QUIT","message":"Received line"}
{"level":"debug","time":"2022-06-02T14:14:54.438","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","line":"221 Goodbye","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T14:14:54.439","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","clean":"true","message":"Client disconnected"}
{"level":"debug","time":"2022-06-02T14:14:54.439","sender":"FTP","connection_id":"FTP_0_1","message":"connection removed, local address \"172.17.0.38:2121\", remote address \"10.0.0.202:5618\" close fs error: <nil>, num open connections: 0"}
{"level":"debug","time":"2022-06-02T14:14:54.439","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","clientIp":"10.0.0.202:5618","message":"Client disconnected"}
{"level":"debug","time":"2022-06-02T14:14:54.439","sender":"ftpserverlib","server_id":"FTP_0","clientId":"1","err":"close tcp 172.17.0.38:2121->10.0.0.202:5618: use of closed network connection","message":"Problem closing control connection"}

```

**Comment by CorneliousJD** [comment]
> Hi,
> 
> there is no upload attempt in the above logs, I see the following FTP commands and all worked:
> 
> * USER
> * PASS
> * CWD /
> * QUIT

Odd, here's a new log to be safe, it logs all this IMMEDIATELY when I hit scan, before the paper is even thru the scanner all the way (before it could even make and attempt to upload the PDF file)

The scanner then beeps w/ an error but it doesn't give me any logging at all, but I've included my setup for my scanner as well here in a screenshot. 

The one things I noticed in the logs are these lines, are they of any concern?

```
"sender":"dataprovider_sqlite","connection_id":"FTP_0_7","message":"create intermediary dir to \"/paperless\", path \"/srv/sftpgo/data/paperless/paperless\", err: <nil>"}
"sender":"common","connection_id":"FTP_0_7","message":"connection swapped, close fs error: <nil>"}
"sender":"FTP","connection_id":"FTP_0_7","message":"connection removed, local address \"172.17.0.38:2121\", remote address \"10.0.0.202:40764\" close fs error: <nil>, num open connections: 0"}
"sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","err":"close tcp 172.17.0.38:2121->10.0.0.202:40764: use of closed network connection","message":"Problem closing control connection"}
```


```
{"level":"debug","time":"2022-06-02T15:04:18.001","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","clientIp":"10.0.0.202:40764","message":"Client connected"}
{"level":"debug","time":"2022-06-02T15:04:18.002","sender":"FTP","connection_id":"FTP_0_7","message":"connection added, local address \"172.17.0.38:2121\", remote address \"10.0.0.202:40764\", num open connections: 1"}
{"level":"debug","time":"2022-06-02T15:04:18.002","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"220 SFTPGo 2.2.3 ready","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T15:04:18.005","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"USER paperless","message":"Received line"}
{"level":"debug","time":"2022-06-02T15:04:18.005","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"331 OK","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T15:04:18.010","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"PASS REDACTED","message":"Received line"}
{"level":"debug","time":"2022-06-02T15:04:18.018","sender":"dataprovider_sqlite","connection_id":"FTP_0_7","message":"create intermediary dir to \"/paperless\", path \"/srv/sftpgo/data/paperless/paperless\", err: <nil>"}
{"level":"debug","time":"2022-06-02T15:04:18.018","sender":"common","connection_id":"FTP_0_7","message":"connection swapped, close fs error: <nil>"}
{"level":"info","time":"2022-06-02T15:04:18.018","sender":"FTP","connection_id":"FTP_0_7","message":"User \"paperless\" logged in with \"password\" from ip \"10.0.0.202\""}
{"level":"debug","time":"2022-06-02T15:04:18.018","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"230 Password ok, continue","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T15:04:18.021","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"CWD /","message":"Received line"}
{"level":"debug","time":"2022-06-02T15:04:18.023","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"250 CD worked on /","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"QUIT","message":"Received line"}
{"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"221 Goodbye","message":"Sending answer"}
{"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","clean":"true","message":"Client disconnected"}
{"level":"debug","time":"2022-06-02T15:04:18.026","sender":"FTP","connection_id":"FTP_0_7","message":"connection removed, local address \"172.17.0.38:2121\", remote address \"10.0.0.202:40764\" close fs error: <nil>, num open connections: 0"}
{"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","clientIp":"10.0.0.202:40764","message":"Client disconnected"}
{"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","err":"close tcp 172.17.0.38:2121->10.0.0.202:40764: use of closed network connection","message":"Problem closing control connection"}
```

![image](https://user-images.githubusercontent.com/724777/171717622-90cdaccf-12ee-49ef-bb61-6c999affed47.png)

**Comment by drakkan** [comment]
> > Hi,
> > there is no upload attempt in the above logs, I see the following FTP commands and all worked:
> > 
> > * USER
> > * PASS
> > * CWD /
> > * QUIT
> 
> Odd, here's a new log to be safe, it logs all this IMMEDIATELY when I hit scan, before the paper is even thru the scanner all the way (before it could even make and attempt to upload the PDF file)
> 
> The scanner then beeps w/ an error but it doesn't give me any logging at all, but I've included my setup for my scanner as well here in a screenshot.
> 
> The one things I noticed in the logs are these lines, are they of any concern?
> 
> ```
> "sender":"dataprovider_sqlite","connection_id":"FTP_0_7","message":"create intermediary dir to \"/paperless\", path \"/srv/sftpgo/data/paperless/paperless\", err: <nil>"}
> "sender":"common","connection_id":"FTP_0_7","message":"connection swapped, close fs error: <nil>"}
> "sender":"FTP","connection_id":"FTP_0_7","message":"connection removed, local address \"172.17.0.38:2121\", remote address \"10.0.0.202:40764\" close fs error: <nil>, num open connections: 0"}
> "sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","err":"close tcp 172.17.0.38:2121->10.0.0.202:40764: use of closed network connection","message":"Problem closing control connection"}
> ```

this happen after the `QUIT` command and means that the scanner closed the connection before the server

> 
> ```
> {"level":"debug","time":"2022-06-02T15:04:18.001","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","clientIp":"10.0.0.202:40764","message":"Client connected"}
> {"level":"debug","time":"2022-06-02T15:04:18.002","sender":"FTP","connection_id":"FTP_0_7","message":"connection added, local address \"172.17.0.38:2121\", remote address \"10.0.0.202:40764\", num open connections: 1"}
> {"level":"debug","time":"2022-06-02T15:04:18.002","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"220 SFTPGo 2.2.3 ready","message":"Sending answer"}
> {"level":"debug","time":"2022-06-02T15:04:18.005","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"USER paperless","message":"Received line"}
> {"level":"debug","time":"2022-06-02T15:04:18.005","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"331 OK","message":"Sending answer"}
> {"level":"debug","time":"2022-06-02T15:04:18.010","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"PASS REDACTED","message":"Received line"}
> {"level":"debug","time":"2022-06-02T15:04:18.018","sender":"dataprovider_sqlite","connection_id":"FTP_0_7","message":"create intermediary dir to \"/paperless\", path \"/srv/sftpgo/data/paperless/paperless\", err: <nil>"}
> {"level":"debug","time":"2022-06-02T15:04:18.018","sender":"common","connection_id":"FTP_0_7","message":"connection swapped, close fs error: <nil>"}
> {"level":"info","time":"2022-06-02T15:04:18.018","sender":"FTP","connection_id":"FTP_0_7","message":"User \"paperless\" logged in with \"password\" from ip \"10.0.0.202\""}
> {"level":"debug","time":"2022-06-02T15:04:18.018","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"230 Password ok, continue","message":"Sending answer"}
> {"level":"debug","time":"2022-06-02T15:04:18.021","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"CWD /","message":"Received line"}
> {"level":"debug","time":"2022-06-02T15:04:18.023","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"250 CD worked on /","message":"Sending answer"}
> {"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"QUIT","message":"Received line"}
> {"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","line":"221 Goodbye","message":"Sending answer"}
> {"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","clean":"true","message":"Client disconnected"}
> {"level":"debug","time":"2022-06-02T15:04:18.026","sender":"FTP","connection_id":"FTP_0_7","message":"connection removed, local address \"172.17.0.38:2121\", remote address \"10.0.0.202:40764\" close fs error: <nil>, num open connections: 0"}
> {"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","clientIp":"10.0.0.202:40764","message":"Client disconnected"}
> {"level":"debug","time":"2022-06-02T15:04:18.026","sender":"ftpserverlib","server_id":"FTP_0","clientId":"7","err":"close tcp 172.17.0.38:2121->10.0.0.202:40764: use of closed network connection","message":"Problem closing control connection"}
> ```
> 

Still no upload attempt, please try to upload a file with FileZilla or WinSCP to understand the difference, you should see commands like `PASV` and `STOR`

> ![image](https://user-images.githubusercontent.com/724777/171717622-90cdaccf-12ee-49ef-bb61-6c999affed47.png)

**Comment by CorneliousJD** [comment]
Hmmm, yes I see that when I do a real upload via filezilla or WinSCP, what is weird is if I use a different FTP server this scanner works fine and scans to the folders without issues, but trying to point it at SFTPGo is where it starts failing and I can't access logs of the scanner to determine anything from that end.

Since debug logs don't really give us anything to go on, I'm not sure where else I can go with this, everything else seems to work except this scanner. 

It's a Brother ADS-1000W - not that I expect anyone to be able to help with that specific model but I figured I'd rather add all the info I can incase someone else is searching for this later.

**Comment by CorneliousJD** [comment]
Holy hell do I feel dumb...

I have it working now - THANK YOU so much for taking the time to troubleshoot with me.

The problem was I was scanning a rather large piece of paper with just a scribble on it for testing, and the scanner deemed it a blank page, and since "skip blank page" was on, it skipped the entire thing, thus scanning nothing. :)

**Comment by drakkan** [comment]
No problem, my guess was that your scanner used `STOU` (which is not currently supported) instead of `STOR`. Glad it works
