### ISSUE TITLE
Downloading a file from the FTP URL with cURL or browser

### ISSUE THREAD

**Issue by RevoltEnergy** [drakkan/sftpgo#862]
Is there a possibility in SFTPGo to download files using the following syntax:
`ftp://[user:password@]host[:port]/path/to/file.ext`?

I have created a user _dummy_ with the password _qwerty_ with the Google Cloud Storage as a Filesystem and I'm able to see the files _A.jpeg_ and _B.jpeg_ of a pointed folder of the bucket when I logged in to my server as a client at `http://xx.xx.xx.xx:8080/web/client/files`. I need to be able to download the image with a cURL by:
`curl "ftp://dummy:qwerty@xx.xx.xx.xx:8080/A.jpeg"` but it is not working...

**Comment by drakkan** [comment]
Hi,

FTP and HTTP are different protocols, you cannot connect to an HTTP endpoint using the FTP protocol. If you want to use FTP you have to enable it and connect to the configured ports.

If `curl` is compiled with `libssh` support as you can see here:

```
curl -V
curl 7.83.1 (x86_64-pc-linux-gnu) libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

something like this should work:

```
curl "sftp://dummy:qwerty@xx.xx.xx.xx:2022/A.jpeg"
```

If you want to download files over HTTP you can use REST API

https://sftpgo.stoplight.io/docs/sftpgo/254371f55e770-download-a-single-file

you need a Bearer token or a API key to authenticate the request

```
