### ISSUE TITLE
TypeError: $.fn.dataTable.render.datetime is not a function. 

### ISSUE THREAD

**Issue by sanderdatema** [drakkan/sftpgo#863]
With the latest update (installed on June 5th 2022) it's not possible to edit any items anymore, because jQuery has an error that was not there before. To be fair, I'm not sure if this error is related to nothing being editable anymore.

![Schermafbeelding 2022-06-05 om 10 39 30](https://user-images.githubusercontent.com/176252/172042640-0ca5f4c4-ff91-4154-857c-348f4b05105a.png)

**Comment by drakkan** [comment]
Hi,

maybe this is a browser cache issue, render.datetime was introduced in datatables v1.12.1. Try CTRL+F5 so your browser is forced to reload the referenced js files

**Comment by sanderdatema** [comment]
My bad, it was indeed a browser cache issue. Thanks for the quick reply!
