### ISSUE TITLE
Defender failed to read IP addresses when httpd is listening to unix socket

### ISSUE THREAD

**Issue by ssesik** [drakkan/sftpgo#867]
Hi,

I am currently experimenting with sftpgo and I found that sftpgo's defender failed to read out ip address when sftpgo is configured to listen to unix socket. An `@` symbol was shown instead of the client ip address. Currently I have only tested it with httpd.
![image](https://user-images.githubusercontent.com/13553965/172516756-3a0296c5-bb7b-4d5d-83f8-eec34670e7a4.png)

A nginx server is configured as a reverse proxy and passes client ip address with  X-Real-IP header.
listening to tcp instead does not exhibit the same problem.

Would this be a software bug or issues with my configuration? Thank you.

My nginx config
`location / {`
`proxy_set_header Host $http_host;`
`proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
`proxy_set_header X-Real-IP $remote_addr;`
`proxy_pass_request_headers on;`
`proxy_connect_timeout 300;`
`proxy_http_version 1.1;`
`proxy_pass http://unix:/var/run/sftpgo.sock;`
`}`

My sftpgo config

`"port": 8558,`
`"address": "/var/run/sftpgo.sock",`
`"enable_web_admin": true,`
`"enable_web_client": true,`
`"enable_https": false,`
`"certificate_file": "",`
`"certificate_key_file": "",`
`"min_tls_version": 12,`
`"client_auth_type": 0,`
`"tls_cipher_suites": [],`
`"proxy_allowed": ["127.0.0.1"],`
`"client_ip_proxy_header": "X-Real-IP",`
`"client_ip_header_depth": 0,`

**Comment by ssesik** [comment]
I am running sftpgo v2.3.0

**Comment by drakkan** [comment]
Hi,

this looks like a bug, I don't have time to take a closer look today. I'll fix it tomorrow, thanks for reporting
