### ISSUE TITLE
Docker env variables

### ISSUE THREAD

**Issue by joarSv** [drakkan/sftpgo#868]
Hi, thanks for the quick support last time.

We are trying to enable the "defender" when running as docker instances in Kubernetes. The following env variables does not seem to activate the defender. Are we missing something? I can't seem to find anything in the docs suggesting we need more than the following set. 

```SFTPGO_LOG_VERBOSE: "false"
  SFTPGO_DEFENDER__ENABLED: "true"
  SFTPGO_DEFENDER__DRIVER: "memory"
  SFTPGO_DEFENDER__BAN_TIME: "45"
```

The admin UI shows status disabled.

**Defender**
Status: "Disabled"

**Comment by drakkan** [comment]
Hi,

docs are [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md). If you need step by step support please consider a [sponsorship](https://github.com/sponsors/drakkan), thanks

**Comment by dropthemic** [comment]
The correct variable is `SFTPGO_COMMON__DEFENDER__ENABLED`
