### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by cosmicbeamer** [drakkan/sftpgo#869]
Hi,

since the last update "Last Login" for user and admin always show "Invalid Date". I am using the official Docker image v2-alpine with Bolt db-driver.

**Comment by drakkan** [comment]
Hi,

in the last update I enabled the locale formatting feature introduced in [datatables v1.12](https://datatables.net/blog/2022-05-13). Which locale are you using in your browser? Also try to refresh the browser cache using CTRL+F5. Thanks

**Comment by cosmicbeamer** [comment]
My browser locale is "en-GB" and I cleared the cache – the error remains. But the problem only occurs in Safari:

````
<tr class="odd">
    <td class="noVis dtr-control sorting_1" tabindex="0">something</td>
    <td>Active</td>
    <td>Invalid Date</td>
    <td>SFTP: 1.2.3.4</td>
</tr>
````

With Edge/Chrome and Firefox everything works as expected.

**Comment by drakkan** [comment]
I think it is this safari specific [issue](https://github.com/mdn/browser-compat-data/issues/15401). It should work if you change this [line](https://github.com/drakkan/sftpgo/blob/main/dataprovider/dataprovider.go#L93) to `iso8601UTCFormat          = "2006-01-02T15:04:05Z"`

**Comment by cosmicbeamer** [comment]
Thanx! Now that I know that it is Safari only, I think I can live with it ;)
