### ISSUE TITLE
sftpgo docker show real IP

### ISSUE THREAD

**Issue by msc-dk** [drakkan/sftpgo#870]
Hi

Sorry for posting this, it is probably a very simple configuration, but I've been at this the entire day now.

I'm trying to get the real IP to show up in sftpgo docker when proxying the sftpgo httpd.

sftpgo IP: 172.16.1.56:8080 (docker network 172.17.0.1) - version 2.3.0
nginx reverse proxy: 172.16.1.56 (docker network 172.17.0.2) - version 2.9.18

when checking access sftpgo logs, I'm seeing the internal docker IP address as the source

Using nginx proxy manager.
I have made a "/" location for the proxy host with the following arguments:
proxy_set_header X-Real-IP  $remote_addr;
proxy_set_header Host $host;
proxy_http_version 1.1;

When setting this location, I'm getting a "400 bad request" message.

trying to set ENV's for the docker to allow proxy & client ip headers... is this correct?

docker run --name bll-sftpgo \
    -e SFTPGO_COMMON__DEFENDER__ENABLED=True \
    -e SFTPGO_COMMON__DEFENDER__BAN_TIME=30 \
    -e SFTPGO_COMMON__DEFENDER__INCREMENT=50 \
    -e SFTPGO_COMMON__DEFENDER__THRESHOLD=5 \
    -e SFTPGO_COMMON__DEFENDER__OBSERVATION_TIME=30 \
    -e SFTPGO_COMMON__DEFENDER__SAFELIST="172.16.0.0/12" \
    -e SFTPGO_HTTPD_BINDINGS__0__PROXY_ALLOWED="172.16.0.0/12" \
    -e SFTPGO_HTTPD_BINDINGS__0__CLIENT_IP_PROXY_HEADER="X-Real-IP" \
    -e SFTPGO_SFTPD__BANNER="" \
    -e SFTPGO_FTPD__BINDINGS__0__PORT=2121 \
    -e SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP="x.x.x.x" \
    -p 8080:8090 \
    -p 2022:2022 \
    -p 2121:2121 \
    --mount type=bind,source=/srv/sftpgo/data/homedata,target=/srv/sftpgo \
    --mount type=bind,source=/srv/sftpgo/data/appdata,target=/var/lib/sftpgo \
    -e SFTPGO_HTTPD__BINDINGS__0__PORT=8090 \
    -d "drakkan/sftpgo:latest"

Hope you can help, thanks!

**Comment by drakkan** [comment]
Hi,

the configuration of SFTPGo, at first glance, seems correct, you can confirm this by reading the logs.

On the NGINX side something like this should work:

```
location / {
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header Host $host;
  proxy_http_version 1.1;
  proxy_pass http://<sftpgoip:port>;
}
```

**Comment by msc-dk** [comment]
> you can confirm this by reading the logs.

Wow, thanks... Can't believe i overlooked that. I was able to verify that the ENV's weren't being passed.
I missed double "_" before BINDINGS in the proxy statements.

`proxy_set_header Host $host;` made the 400 Bad Request appear in nginx proxy manager. 
Nginx proxy manager apparently inserts both `proxy_pass` & `proxy_set_header Host $host` just by filling out the formula, thats why i got errors when typing them in again.

Thanks a bunch
