### ISSUE TITLE
feature: allow user to share their data with other users

### ISSUE THREAD

**Issue by tooptoop4** [drakkan/sftpgo#874]
would be great if user1 could login to UI and configure some of their folders to be readable by user2/user3

this would avoid server admin having to maintain all the permissions centrally

**Comment by drakkan** [comment]
Hi,

shared folders are already supported, you can define them from the admin UI (or from your auth hook response)

**Comment by tooptoop4** [comment]
@drakkan regular users can't make adhoc changes to admin/auth hooks. I am talking about allowing regular users to define the sharing whenever they want

**Comment by drakkan** [comment]
I don't plan to work on this without a sponsorship sorry
