### ISSUE TITLE
Generated openapi does not work with sftpgo

### ISSUE THREAD

**Issue by damienhollis** [drakkan/sftpgo#875]
First, thanks for creating sftpgo, it is a great project and really full featured!

We trying to use the sftpgo REST api by generating a client using `openapi-generator-cl` but the resulting java code does not result in the correct json. We have been investigating for a few days and from what we can tell, the generation is working as expected and the specification is wrong. But we are new to openapi, so there might be something wrong with what we are doing.

We are trying to add a user using the api, i.e. posting to `/users`. The valid json looks like:
```
{
  "username": "test",
  "permissions": {
    "/": [
      "*"
    ],
    "/somedir": [
      "list",
      "download"
    ]
  }
}
```

But the generated json looks like:
```
{
  "username": "test",
  "permissions": [ 
    {
      "/": [
        "*"
      ],
      "/somedir": [
        "list",
        "download"
      ]
    }
  ]
}
```

Which is what we would expect from the following generated java code (so serialization of the java to json seems to be doing what we would expect):
```
  public static final String SERIALIZED_NAME_PERMISSIONS = "permissions";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS)
  private List<Map<String, List<Permission>>> permissions = null;
```
The code was generated using this command:
```
sftpgo-java-api % docker run --rm \
    -v $PWD:/local openapitools/openapi-generator-cli:v6.0.0 generate \
    -i https://raw.githubusercontent.com/drakkan/sftpgo/v2.3.0/openapi/openapi.yaml \
    -g java \
    -o /local/out/java \
```

The problem seems to be the specification. The snippet of the specification looks like this:
```
      permissions:
          type: object
          items:
            $ref: '#/components/schemas/DirPermissions'
          minItems: 1
          example:
            /:
              - '*'
            /somedir:
              - list
              - download
```
We aren't experts in the openapi specification but reading the documentation, we can't see any description of how `items` works with `type: object` - it is only documented to work with `type: array` as far as we can tell. We would expect the specification to be something like:
```
      permissions:
          $ref: '#/components/schemas/DirPermissions'
          example:
            /:
              - '*'
            /somedir:
              - list
              - download

```
Are we doing something wrong or is there a bug in the specification?

**Comment by drakkan** [comment]
Hi,

I have no enough motivations to test the java generator myself but if you try swaggerui it works as expected, the same for [stoplight](https://sftpgo.stoplight.io/docs/sftpgo/1ad2b4e6db533-add-user). So I think the definition is correct

**Comment by damienhollis** [comment]
Hi,

I had looked at the spotlight UI in an attempt to understand if it was a code generation issue or the specification. In the end, I wasn't sure how their example message was generated but came away thinking that the permissions part was coming from the example in your specification (rather than actually reading that part of the specification). I also tried to use swagger to generate the java api and it also generated code that did not work.

It is getting late here but tomorrow I can try to generate a go client and see if it works correctly - I'm not really a go programmer but I should be able to get it running to test it. I'll provide the generated code here if it does not work.

**Comment by drakkan** [comment]
> Hi,
> 
> I had looked at the spotlight UI in an attempt to understand if it was a code generation issue or the specification. In the end, I wasn't sure how their example message was generated but came away thinking that the permissions part was coming from the example in your specification (rather than actually reading that part of the specification).

I don't think so, however if you have SFTPGo installed on localhost you can also try `http://localhost:8080/openapi/swagger-ui/`.  Also swaggerui works fine. Other people used REST API in the past with various generators with no issues

https://github.com/ramnes/sftpgo-client

If you want I spend more time on your issue a [sponsorship](https://github.com/sponsors/drakkan) is appreciated, thanks. But I think this is an issue on your side or in the used generator

> I also tried to use swagger to generate the java api and it also generated code that did not work.
> 
> It is getting late here but tomorrow I can try to generate a go client and see if it works correctly - I'm not really a go programmer but I should be able to get it running to test it. I'll provide the generated code here if it does not work.

**Comment by drakkan** [comment]
Just copy the yaml definition in the [swagger editor](https://editor.swagger.io/?_ga=2.145914291.643913157.1654942051-421606233.1553003034), remove the permission example from the yaml. You can see that the generated user has `"permissions": {}`, so it is not a list but an object as expected.

**Comment by drakkan** [comment]
Hi,

I did more tests and with the linked change the generated java code is now this:

```
@SerializedName("permissions")
 private Map<String, List<Permission>> permissions = null;
```

swagger ui and stoplight still work as before

**Comment by damienhollis** [comment]
Hi @drakkan - thanks so much for turning around that "fix" so quickly - really appreciate it!

The java generated code now works as expected.
