### ISSUE TITLE
can't connect by FTP in docker (SFTP & webdav is OK)

### ISSUE THREAD

**Issue by BladPit** [drakkan/sftpgo#876]
sorry to bother you by this simple issue, I am not good at these technical things.

I install this perfect SFTP server by docker on a unRaid OS (bridge network), then I could work good with SFTP & webdav mode, but I did many work to deal with the FTP connect issue. I can't connect with the server by FTP mode via winscp or other media app (nPlayer).

I checked for several times of my docker parameters and can't find any problems, wish you tell me where I did wrong.

here is the related info for you to help:

**docker run code**:
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='sftpgo' --net='bridge' -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -e 'SFTPGO_FTPD__BINDINGS__0__PORT'='2121' -e 'SFTPGO_WEBDAVD__BINDINGS__0__PORT'='10080' -e 'SFTPGO_HTTPD__BINDINGS__0__PORT'='8090' -e 'PUID'='99' -e 'PGID'='100' -e 'SFTPGO_FTPD__PASSIVE_PORT_RANGE__START'='50000' -e 'SFTPGO_FTPD__PASSIVE_PORT_RANGE__END'='50010' -p '50000-50010:50000-50010/tcp' -p '10080:10080/tcp' -p '8090:8090/tcp' -p '2121:2121/tcp' -p '2022:2022/tcp' -v '/mnt/user/appdata/sftpgo/data':'/srv/sftpgo':'rw' -v '/mnt/user/appdata/sftpgo/config':'/var/lib/sftpgo':'rw' -v '/mnt/user/':'/media':'rw' 'drakkan/sftpgo:edge-alpine'`

**Log of connecting via winscp**:
`{"level":"debug","time":"2022-06-11T21:12:51.500","sender":"ftpserverlib","server_id":"FTP_0","clientId":"49","clientIp":"192.168.2.101:9708","message":"Client connected"}
{"level":"debug","time":"2022-06-11T21:12:51.500","sender":"FTP","connection_id":"FTP_0_49","message":"connection added, local address \"172.17.0.3:2121\", remote address \"192.168.2.101:9708\", num open connections: 1"}
{"level":"debug","time":"2022-06-11T21:12:51.506","sender":"common","connection_id":"FTP_0_49","message":"connection swapped, close fs error: <nil>"}

{"level":"info","time":"2022-06-11T21:12:51.506","sender":"FTP","connection_id":"FTP_0_49","message":"User \"user\" logged in with \"password\" from ip \"192.168.2.101\""}
{"level":"debug","time":"2022-06-11T21:12:51.668","sender":"dataprovider_sqlite","message":"last login updated for user \"user\""}
{"level":"debug","time":"2022-06-11T21:13:06.491","sender":"FTP","connection_id":"FTP_0_49","message":"connection removed, local address \"172.17.0.3:2121\", remote address \"192.168.2.101:9708\" close fs error: <nil>, num open connections: 0"}

{"level":"debug","time":"2022-06-11T21:13:06.491","sender":"ftpserverlib","server_id":"FTP_0","clientId":"49","clientIp":"192.168.2.101:9708","message":"Client disconnected"}
{"level":"warn","time":"2022-06-11T21:13:11.791","sender":"ftpserverlib","server_id":"FTP_0","clientId":"49","error":"accept tcp [::]:50000: i/o timeout","message":"Unable to open transfer"}

{"level":"warn","time":"2022-06-11T21:13:11.791","sender":"ftpserverlib","server_id":"FTP_0","clientId":"49","err":"write tcp 172.17.0.3:2121->192.168.2.101:9708: use of closed network connection","message":"Couldn't flush line"}`

screenshot:
![1](https://user-images.githubusercontent.com/90924194/173189516-77c44da8-74ce-45da-950e-18654ddc076c.png)
![2](https://user-images.githubusercontent.com/90924194/173189520-c60022ad-9e48-473c-8bcd-b399e37ea752.png)

**Comment by BladPit** [comment]
By the way, here is another small puzzle：I can't find the config file (sftpgo.json) in the path /var/lib/sftpgo, here only stored some authentication files. So how could I get the config file and persist it in /var/lib/sftpgo？ （has mapped to host path）

Thanks for your help again.
![3](https://user-images.githubusercontent.com/90924194/173197209-6055b448-1b1f-40d9-84a8-9d094938f6eb.png)

**Comment by drakkan** [comment]
Hi,

try to set a passive IP and ensure that no firewall blocks the configured passive ports.

The default config file is in `/etc/sftpgo/sftpgo.json`, just copy it in `/var/lib/sftpgo` if you want to persist the config file. This is generally not required: you use the default values and override via env vars, but you can also persist it if you prefer

**Comment by BladPit** [comment]
> Hi,
> 
> try to set the passive IP and ensure that no firewall blocks the configured passive ports.
> 
> The default config file is in `/etc/sftpgo/sftpgo.json`, just copy it in `/var/lib/sftpgo` if you want to persist the config file. This is generally not required: you use the default values and override via env vars, but you can also persist it if you prefer

thanks for your reply.

Should I set the passive IP of each client to make them connect the server by FTP? Could I just set passive IP=0.0.0.0 to alow any client to use FTP?

And according to your answer, do I have to set the passive IP to make FTP serve available?

**Comment by BladPit** [comment]
and refer to the config file. If I copy sftpgo.json from `/etc/sftpgo/sftpgo.json` to `/var/lib/sftpgo`, when I restart the container, which config file will take effect?

**Comment by drakkan** [comment]
FTP clients open data connections to the configured passive IP, you cannot set 0.0.0.0, you have to set the server IP that clients can reach. This is for passive FTP, for active FTP is the server that opens a connection to a client port (this generally works only on local networks).

**Comment by drakkan** [comment]
> and refer to the config file. If I copy sftpgo.json from `/etc/sftpgo/sftpgo.json` to `/var/lib/sftpgo`, when I restart the container, which config file will take effect?

the config file in `/var/lib/sftpgo` will take precedence

**Comment by BladPit** [comment]
> FTP clients open data connections to the configured passive IP, you cannot set 0.0.0.0, you have to set the server IP that clients can reach. This is for passive FTP, for active FTP is the server that opens a connection to a client port (this generally works only on local networks).

Got, but should I set the host intranet IP to passive IP? or container IP? sorry I am not so familiar with FTP.
(I have took a test, when I set the host intranet IP to passive IP, it works both in intranet and internet. But I can't be sure it is correct. In my understanding, we will set the FTP server IP & port when we make an FTP connection, why should we set the passive IP in config repeatedly?)

**Comment by BladPit** [comment]
> > and refer to the config file. If I copy sftpgo.json from `/etc/sftpgo/sftpgo.json` to `/var/lib/sftpgo`, when I restart the container, which config file will take effect?
> 
> the config file in `/var/lib/sftpgo` will take precedence

thanks, but I find the config file copied from `/etc/sftpgo/sftpgo.json` is the default one which not including the change by environment variables (set in docker run parameter). So it seems that it is useless to persist it, could you tell me how can I find the updated config file? or there is no updated config file?

**Comment by drakkan** [comment]
> > FTP clients open data connections to the configured passive IP, you cannot set 0.0.0.0, you have to set the server IP that clients can reach. This is for passive FTP, for active FTP is the server that opens a connection to a client port (this generally works only on local networks).
> 
> Got, but should I set the host intranet IP to passive IP? or container IP? sorry I am not so familiar with FTP. (I have took a test, when I set the host intranet IP to passive IP, it works both in intranet and internet. But I can't be sure it is correct. In my understanding, we will set the FTP server IP & port when we make an FTP connection, why should we set the passive IP in config repeatedly?)

You have to set the IP that the FTP clients connect to. Host intranet IP should be OK, but you know your network configuration better then me :smile:

**Comment by drakkan** [comment]
> > > and refer to the config file. If I copy sftpgo.json from `/etc/sftpgo/sftpgo.json` to `/var/lib/sftpgo`, when I restart the container, which config file will take effect?
> > 
> > 
> > the config file in `/var/lib/sftpgo` will take precedence
> 
> thanks, but I find the config file copied from `/etc/sftpgo/sftpgo.json` is the default one which not including the change by environment variables (set in docker run parameter). So it seems that it is useless to persist it, could you tell me how can I find the updated config file? or there is no updated config file?

there is no updated config file. You can manually update the config file, persist it and use your modified config file instead of the env vars

**Comment by BladPit** [comment]
> > > > and refer to the config file. If I copy sftpgo.json from `/etc/sftpgo/sftpgo.json` to `/var/lib/sftpgo`, when I restart the container, which config file will take effect?
> > > 
> > > 
> > > the config file in `/var/lib/sftpgo` will take precedence
> > 
> > 
> > thanks, but I find the config file copied from `/etc/sftpgo/sftpgo.json` is the default one which not including the change by environment variables (set in docker run parameter). So it seems that it is useless to persist it, could you tell me how can I find the updated config file? or there is no updated config file?
> 
> there is no updated config file. You can manually update the config file, persist it and use your modified config file instead of the env vars

Got, looks it is better to set my own configuration via env vars when build the container, persisting config file is really not so necessary as you recommended.

**Comment by BladPit** [comment]
> > > FTP clients open data connections to the configured passive IP, you cannot set 0.0.0.0, you have to set the server IP that clients can reach. This is for passive FTP, for active FTP is the server that opens a connection to a client port (this generally works only on local networks).
> > 
> > 
> > Got, but should I set the host intranet IP to passive IP? or container IP? sorry I am not so familiar with FTP. (I have took a test, when I set the host intranet IP to passive IP, it works both in intranet and internet. But I can't be sure it is correct. In my understanding, we will set the FTP server IP & port when we make an FTP connection, why should we set the passive IP in config repeatedly?)
> 
> You have to set the IP that the FTP clients connect to. Host intranet IP should be OK, but you know your network configuration better then me 😄

what puzzled me is that "we have set the FTP server IP & port  in FTP client GUI or CLI when we tried to make a FTP connection", so we define the passive IP in config may be repeated & useless? After all the Client knew the passive IP (=server IP) at the begaining.

**Comment by drakkan** [comment]
This is how FTP works. The client send the `PASV` command and the server replies with the ip and port to use.
By default SFTPGo uses the IP used for the current connection, but in your case you are using docker and the server ip is `172.17.0.3`, the client cannot connect to this IP so you have to set a passive ip.

**Comment by BladPit** [comment]
> This is how FTP works. The client send the `PASV` command and the server replies with the ip and port to use. By default SFTPGo uses the IP used for the current connection, but in your case you are using docker and the server ip is `172.17.0.3`, the client cannot connect to this IP so you have to set a passive ip.

It is clear by your answer, thanks a lot for your reply. I think this issue could be closed then.

by the way, I took some tests just now. I found that when I make an FTP connection and use a external IP or domain as server IP, it is fine with any configuration of passive IP (even a wrong IP or not setting the passive IP). The issue only comes in the situation that I use a local client connect a local/intranet server IP.

**Comment by drakkan** [comment]
it depens on many things. For example the most modern `EPSV` command does not require that the server sends an IP.
I think SFTPGo has all the bits to work in any case, for example you can also set different passive IPs based on [the client source address](https://github.com/drakkan/sftpgo/blob/v2.3.1/sftpgo.json#L116). FTP is an old protocol and some design choices appear strange nowadays
