### ISSUE TITLE
sftpgo resetprovider does not completely reset dataprovider

### ISSUE THREAD

**Issue by mmetz-isa** [drakkan/sftpgo#877]
Hi,

it seems like the `resetprovider` verb does not delete the `shared_sessions` table from the `sqlite` data provider.  This leads to the following error message when running `initprovider`:

```
2022-06-15T03:22:20.975 INF Initializing provider: "sqlite" config file: "/etc/sftpgo/sftpgo.yaml"
2022-06-15T03:22:20.977 INF creating initial database schema, version 15
2022-06-15T03:22:20.993 INF updating database version: 15 -> 16
2022-06-15T03:22:21.006 INF updating database version: 16 -> 17
2022-06-15T03:22:21.020 INF updating database version: 17 -> 18
2022-06-15T03:22:21.028 INF updating database version: 18 -> 19
2022-06-15T03:22:21.029 ERR Unable to initialize/update the data provider: table "shared_sessions" already exists
```

Manually dropping the `shared_sessions` table via sqlite3 is a sufficient workaround so far.

I have installed the Debian sftpgo package version 2.3.1-1 from the osuosl repository.

sftpgo version:

```
sftpgo --version
SFTPGo 2.3.1-ca4da2f-2022-06-10T17:11:30Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
```

Looking into the code I don't quite get why this is happening. It seems like the DROP TABLE statement is in the code and the binutils strings binary I can also find two instances from the different providers. 

https://github.com/drakkan/sftpgo/blob/v2.3.1/dataprovider/sqlite.go#L39

```
strings -d -t x /usr/bin/sftpgo | grep 'DROP TABLE IF EXISTS "{{shared'
1546fc7 DROP TABLE IF EXISTS "{{shared_sessions}}";
1547df2 DROP TABLE IF EXISTS "{{shared_sessions}}" CASCADE;
```

**Comment by drakkan** [comment]
Hi,

this is fixed [here](https://github.com/drakkan/sftpgo/commit/550158ff4bbfdedf1793b0dc1ea87c19ed62e362), unfortunately I noticed this issue after v2.3.1. It will be included in v2.3.2 once I'll tag it. In the meantime you can download and use the deb/rpm from [here](https://github.com/drakkan/sftpgo/actions/runs/2490115039)

**Comment by mmetz-isa** [comment]
Thanks for the prompt response.

Fortunately with the workaround in place this this is not pressing for me.  I only wanted to point out the bug in case you weren't aware of it.

**Comment by drakkan** [comment]
> Thanks for the prompt response.
> 
> Fortunately with the workaround in place this this is not pressing for me. I only wanted to point out the bug in case you weren't aware of it.

yes, thanks. I will not tag a new release only for this issue. To avoid this happening again in the future I'll add the init/reset/init sequence to the test cases. Thanks for reporting
