### ISSUE TITLE
action,  http_notification_url, path parameter under Windows !

### ISSUE THREAD

**Issue by laurentmenard** [drakkan/sftpgo#88]
Let's me thank you for the quality of your project and the time you spend to help users.

It's really powerfull and let me implement a very good solution for my needs.
Really good.

I face a trouble when a define an action under Windows.
The path parameter doesn't contain the ":" character in the beginning of path.
Sample : Pathof the upload file = c:\temp\wema_user_demo_rgpd_sample.csv
the path parameter sendt in the url contains only c\temp\wema_user_demo_rgpd_sample.csv without the ":" after c

Sorry, it's under Windows !!!

**Comment by laurentmenard** [comment]
Please forget my previous issue (except my thank you), cause the parameters are ok, it's my code which is buggy !!!
Shame on me !

**Comment by drakkan** [comment]
Hi,

thanks for reporting back, I just did a quick test and it worked, I get notifications such as this one:

```
"GET /notify?action=upload&file_size=2008&local_file=true&path=C%3A%5Csftphome1%5CPKGBUILD&username=nicola
```
with the full path url encoded.

**Comment by drakkan** [comment]
Hi,

please note that action notifications via HTTP are POST and not GET anymore after this commit:

https://github.com/drakkan/sftpgo/commit/4759254e107522a177d99fc8184eb0e8b79121f2

I know that this is a backward incompatible change but this way the actions can be extended more easily, sorry for the trouble
