### ISSUE TITLE
s3: region cannot be empty

### ISSUE THREAD

**Issue by yctn** [drakkan/sftpgo#884]
it seems sftpgo is not compatible with backblaze B2 because the region field is required. my s3 provider did not provide a Region to me.

even when i test it with a publicly available ceph cluster it is not working correctly because of the region settings.

Please make it possible to leave the Region field empty.

**Comment by drakkan** [comment]
Hi,

I never tested B2 myself, however from the doc [here](https://www.backblaze.com/b2/docs/s3_compatible_api.html) the region seems required, see for example the section "Endpoints/URLs". You have to use the S3 api not the native b2 protocol. 

Ceph (over S3) was confirmed to work in the past from other users.

**Comment by drakkan** [comment]
I did a quick test using the public b2 test bucket and it works using the following settings

![Schermata del 2022-06-20 18-52-26](https://user-images.githubusercontent.com/553263/174648561-a93288b0-734c-44b9-8d46-462192a28917.png)

In the future I'll evaluate to make the bucket optional. For now set the bucket name to the value you see in the endpoint URL. Thanks
