### ISSUE TITLE
Backup does not save virtual folders set on groups

### ISSUE THREAD

**Issue by Destrocamil** [drakkan/sftpgo#885]
Hello Drakkan,
First, props for the amazing tool, time and effort that you put in this project.
Second, a question/issue:
- the backup option does not save the virtual folders that are set on groups;
I am using version 2.3.0 on docker with nginx and PostgreSQL database.
Any help is appreciated!
Thank you!!

**Comment by drakkan** [comment]
Hi,

thanks for reporting, this issue should be fixed in 2.3.x branch (I'll push the fix to the development version later). Please try a 2.3.x docker tag

**Comment by Destrocamil** [comment]
I will try it later and then give some feedback. Props!
