### ISSUE TITLE
startsubsys root path question

### ISSUE THREAD

**Issue by jscheid** [drakkan/sftpgo#888]
When running the OpenSSH SFTP server as a subsystem (`/usr/libexec/sftp-server`) without any parameters, it serves the whole file system (`/`) by default. The Green End SFTP Server works the same.

`sftpgo startsubsys` instead serves the user home directory. That's ok, but is there a way to make it serve the root? I've tried with `-d /` but It then tries to serve `/username`. I've looked through the config options but can't see anything that would help. Is this possible at all?

**Comment by drakkan** [comment]
Hi,

Take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/howto/openssh-sftp-subsystem.md#change-home-dir-set-virtual-permissions-and-other-sftpgo-specific-features). I don't have time/motivation to test it now, but it should work

**Comment by jscheid** [comment]
Works perfectly, thanks!!
