### ISSUE TITLE
Probably shouldn't advertise `hardlink@openssh.com` extension

### ISSUE THREAD

**Issue by jscheid** [drakkan/sftpgo#889]
Hi, sftpgo advertises the `hardlink@openssh.com` extension. But when I try to use it, I'm getting an "operation unsupported" error back. Perhaps there is a reason for the discrepancy?

**Comment by drakkan** [comment]
SFTPGo only advertises `statvfs@openssh.com`

```
debug2: Server supports extension "statvfs@openssh.com" revision 2
```

maybe you have this issue because you are using SFTPGo as OpenSSH subsystem and in this case is OpenSSH that advertises extensions

**Comment by jscheid** [comment]
```
$ (printf '\x00\x00\x00\x05\x01\0x00\x00\x00\x06' && cat) | sftpgo startsubsys 2>/dev/null | hexdump -C
00000000  00 00 00 5f 02 00 00 00  03 00 00 00 14 68 61 72  |..._.........har|
00000010  64 6c 69 6e 6b 40 6f 70  65 6e 73 73 68 2e 63 6f  |dlink@openssh.co|
00000020  6d 00 00 00 01 31 00 00  00 18 70 6f 73 69 78 2d  |m....1....posix-|
00000030  72 65 6e 61 6d 65 40 6f  70 65 6e 73 73 68 2e 63  |rename@openssh.c|
00000040  6f 6d 00 00 00 01 31 00  00 00 13 73 74 61 74 76  |om....1....statv|
00000050  66 73 40 6f 70 65 6e 73  73 68 2e 63 6f 6d 00 00  |fs@openssh.com..|
^C
$ sftpgo --version
SFTPGo 2.3.1-ca4da2f-2022-06-10T17:11:30Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
$ 
```

**Comment by jscheid** [comment]
Wait, are you saying the command above runs OpenSSH?

**Comment by drakkan** [comment]
> Wait, are you saying the command above runs OpenSSH?

no. SFTPGo is not OpenSSH.

Are you able to reproduce the issue if you run SFTPGo in non subsystem mode? I think in subsystem mode extensions are not set, but in this mode the extensions are probably advertised from OpenSSH. I'll do some tests the next week or when I have some free time

**Comment by jscheid** [comment]
If it doesn't run OpenSSH, how can OpenSSH be involved? Like you can see in my example, I'm running sftpgo directly.

I'll try running in non-subsystem mode next.

**Comment by drakkan** [comment]
> If it doesn't run OpenSSH, how can OpenSSH be involved? Like you can see in my example, I'm running sftpgo directly.
> 
> I'll try running in non-subsystem mode next.

because you connect to OpenSSH and not to SFTPGo and probably OpenSSH does not ask for extensions to the sftp subsystem (I'm not sure). However setting the supported extensions in subsystem mode is just a one line change. I'm not sure this will fix your issue

**Comment by drakkan** [comment]
Now you have this

```
(printf '\x00\x00\x00\x05\x01\0x00\x00\x00\x06' && cat) | ./sftpgo startsubsys 2>/dev/null | hexdump -C
00000000  00 00 00 21 02 00 00 00  03 00 00 00 13 73 74 61  |...!.........sta|
00000010  74 76 66 73 40 6f 70 65  6e 73 73 68 2e 63 6f 6d  |tvfs@openssh.com|
```

**Comment by jscheid** [comment]
Awesome, thanks!
