### ISSUE TITLE
`realpath` doesn't seem to work on symlink

### ISSUE THREAD

**Issue by jscheid** [drakkan/sftpgo#890]
I'm trying to use `SSH_FXP_REALPATH` on a simple symlink:

```
$ ls -ld /tmp/work/fixtures/symlink
lrwxrwxrwx 1 user group 30 Jun 25 13:46 /tmp/work/fixtures/symlink -> /tmp/work/fixtures/link-target
$ cat /etc/debian_version 
11.3
$
```

I'm calling it with the full path (`/tmp/work/fixtures/symlink`). I'd expect it to return `/tmp/work/fixtures/link-target` but it returns just `/tmp/work/fixtures/symlink`.

Is there anything I can try to help debug this? I can't see anything related in the logs, is there a way to increase verbosity?

**Comment by drakkan** [comment]
Take a look [here](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-6.11). I think you have to use [SSH_FXP_READLINK](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-6.10) to resolve symlinks

**Comment by jscheid** [comment]
OpenSSH, Proftpd and Green End all resolve symlinks with realpath. And I'm pretty sure your code is trying to as well? 

https://github.com/drakkan/sftpgo/blob/9a6b1a13157da14c1cd2076ede8743272f535157/vfs/sftpfs.go#L631

**Comment by drakkan** [comment]
please share a reproducer, thanks

**Comment by drakkan** [comment]
> OpenSSH, Proftpd and Green End all resolve symlinks with realpath. And I'm pretty sure your code is trying to as well?
> 
> https://github.com/drakkan/sftpgo/blob/9a6b1a13157da14c1cd2076ede8743272f535157/vfs/sftpfs.go#L631

this code is completly unrelated. SFTPFs is used if you use another SFTP server as storage backend

**Comment by jscheid** [comment]
Here you go: https://gist.github.com/jscheid/822b044ba9eed701a951540a49547f28

**Comment by drakkan** [comment]
I know that SFTPGo does not resolve symlinks with `SSH_FXP_REALPATH`. I checked the openssh [code](https://github.com/openssh/openssh-portable/blob/master/sftp-realpath.c#L58) and I verified that symlinks are resolved as you report.

OpenSSH resolves symlink and does not fail if the symlink target does not exist. I will fix this issue with low priority. The V3 specs does not say anything about symlinks, so the SFTPGo implementation does not violate them (we just convert the path to absolute)

**Comment by jscheid** [comment]
You're right that the spec isn't very clear here at all. I think the intention was always for this to mimic [POSIX realpath](https://pubs.opengroup.org/onlinepubs/009696799/functions/realpath.html) though, which does mandate to resolve symlinks, so I agree it would be good to fix at some point. Do take your time, I don't need this at the moment, I just noticed it and thought I'd flag it.

**Comment by drakkan** [comment]
> You're right that the spec isn't very clear here at all. I think the intention was always for this to mimic [POSIX realpath](https://pubs.opengroup.org/onlinepubs/009696799/functions/realpath.html) though, which does mandate to resolve symlinks, so I agree it would be good to fix at some point. Do take your time, I don't need this at the moment, I just noticed it and thought I'd flag it.

v6 specs have more [details](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13#section-8.9). 

I hadn't noticed this OpenSSH behavior until now. I can also simplify our sftpfs implementation (other SFTP servers used as storage backend) now that I know that realpath is supposed to resolve symlinks. 

I'll try to fix this issue with low priority. I don't think it creates any real issue to common SFTP clients. Thanks for reporting

**Comment by drakkan** [comment]
This (untested) patch should fix the issue or it should be a good starting point

[0001-WIP-realpath.zip](https://github.com/drakkan/sftpgo/files/9114712/0001-WIP-realpath.zip)

but we should be able to return an error if the path resolves outside the user home dir or if there is another error and this is not currently possible. Some changes to pkg/sftp are required
