### ISSUE TITLE
Offer Option to use HPN-SSH

### ISSUE THREAD

**Issue by gotjoshua** [drakkan/sftpgo#892]
HPN17v0 is up to date with OpenSSH 8.9. 
[HPN-SSH](https://www.psc.edu/hpn-ssh-home/)

These patches seem to be included in  9.0_p1  https://repology.org/project/openssh/information

Would you consider to include it in your images?

**Comment by drakkan** [comment]
Hi,

SFTPGo is not related to OpenSSH, it uses the Go crypto stack. So we cannot apply these patches.  AES-GCM and CHACHA20 are quite optimized. AES-CTR could be improved, some patches are available upstream but are not yet included in any stable Go version

https://github.com/golang/go/issues/20967

Do you have performance issues?

**Comment by drakkan** [comment]
and HPN patches are not merged in OpenSSH. There is a separate [repo](https://github.com/rapier1/openssh-portable)

**Comment by gotjoshua** [comment]
thanks for the quick reply!  

> Do you have performance issues?

 i have yet to do speed comparisons, but have read many posts that openssh is notoriously slow for sftp.

I will see if i can set up some head to head speed tests and report back if i find anything interesting.

**Comment by drakkan** [comment]
> thanks for the quick reply!
> 
> > Do you have performance issues?
> 
> i have yet to do speed comparisons, but have read many posts that openssh is notoriously slow for sftp.
> 
> I will see if i can set up some head to head speed tests and report back if i find anything interesting.

Another used did a performance comparison with OpenSSH in the past. You can find it [here](https://github.com/drakkan/sftpgo/blob/main/docs/performance.md).

HPN-SSH also supports `NONE` as encryption method. In this mode it will perform better for sure, but you have no security. I expect performance similar to plain FTP in this mode

**Comment by drakkan** [comment]
HPN patches are for OpenSSH, we use a different crypto stack, we cannot apply them here, sorry
