### ISSUE TITLE
Upgrade from v2.2.3 to 2.3.1

### ISSUE THREAD

**Issue by selimfek** [drakkan/sftpgo#893]
Hello Drakkan, 

I created a new environment with the same data and while migrating I got this error. 

<img width="1181" alt="Capture d’écran 2022-06-27 à 15 35 44" src="https://user-images.githubusercontent.com/102149609/175960217-89fdad41-9a12-4dfc-89a5-14fc33ee33ff.png">

_Originally posted by @selimfek in https://github.com/drakkan/sftpgo/issues/871#issuecomment-1167394551_

**Comment by selimfek** [comment]
column upload_data_transfer exists in the users table. I don't understand why I got this error

there is a screenshot from the table users : 
<img width="982" alt="Capture d’écran 2022-06-27 à 17 50 10" src="https://user-images.githubusercontent.com/102149609/175981477-a64fc27a-b2eb-4e83-90f7-a7206b20a364.png">

**Comment by drakkan** [comment]
Hi,

the logs refer to migration 18. The missing column should be created in migration 16, take a look [here](https://github.com/drakkan/sftpgo/blob/2.3.x/dataprovider/mysql.go#L89). Are you able to reproduce using standard mysql?

**Comment by drakkan** [comment]
@sagikazarmark if I remember corretly you use SFTPGo with MySQL, do you have the same issue? Thanks

**Comment by drakkan** [comment]
> column upload_data_transfer exists in the users table. I don't understand why I got this error
> 
> there is a screenshot from the table users : <img alt="Capture d’écran 2022-06-27 à 17 50 10" width="982" src="https://user-images.githubusercontent.com/102149609/175981477-a64fc27a-b2eb-4e83-90f7-a7206b20a364.png">

maybe you MySQL compatible database does not apply schema changes immediately (or there is a custom command to do so)

**Comment by drakkan** [comment]
Please provide more info or a reproducer. I'm not going to test with Amazon RDS for MySQL without a sponsorship. Are you able to reproduce this issue with standard MySQL or MariaDB? Thanks

**Comment by sagikazarmark** [comment]
I'm still running 2.2.3. I'll try to upgrade later this week.

**Comment by selimfek** [comment]
Hello Drakkan,

Sorry for the late. Finally it works. 

You have just to change the name of the colomun from users_mappings to users_groups_mappings and also the database version manually. 

Now the v2.3.1 works fine and also the data inside the database is okay ! You can close issue.

**Comment by drakkan** [comment]
It is no clear to me how the issue happen. In migration v17 we create the [users_groups_mapping](https://github.com/drakkan/sftpgo/blob/2.3.x/dataprovider/mysql.go#L129) table and we rename `folders_mapping` to [users_folders_mapping](https://github.com/drakkan/sftpgo/blob/2.3.x/dataprovider/mysql.go#L134). It should work automatically.

This migration is also tested in the CI. I'll leave the issue open while waiting for feedback from other users
