### ISSUE TITLE
Cannot create initial or additional admins on new installation

### ISSUE THREAD

**Issue by Simon818** [drakkan/sftpgo#894]
I'm running the drakkan/sftpgo:alpine image and seem to be unable to create any persistent admins. On first setup, I can go through the creation process for the first admin account and log in with it. At that point, the credentials I used for the initial admin do not work, and any additional admins I create are not able to log in. However, when I go to the admins list in the web panel, I can see myself and any other admins I create, even though myself and those admins cannot log in. The only reason I'm able to access the web panel at all is because the initial setup causes me to be automatically logged in with that first admin account.

I've verified that I can write to the mapped home and data directories from within the docker image and see the results on the host.

The error in logs is:

> error authenticating user \"simon\": not found: sql: no rows in result set

When I look at logs (using docker-compose log), I can't see anything about user creations at all. I see http logs and when I run initial setup, I see my last login time get updated, but no user creations.

Is there somewhere else I should look for logs of admins being created? If not, I'm pretty stumped.

**Comment by Simon818** [comment]
I think you're right. The first time I set it up, I had a password conflict in Bitwarden so trying to log into both the client and the admin UI failed. From that point onward I basically just forgot it was there. The fact my brain is capable of doing all this troubleshooting while missing the obvious is fascinating, hilarious or obnoxious, depending on who you are. I'm going to redeploy this later today but I expect all is well now; thanks for such a great project and infinite patience.

**Comment by drakkan** [comment]
No problem, let me know if it works now. 
I'm used to people just asking without giving anything in return. I am happy to see that there is someone who appreciates my work and donates something (no matter the amount) even before actually using SFTPGo
