### ISSUE TITLE
Renaming big files result in error with S3 backend

### ISSUE THREAD

**Issue by maximethebault** [drakkan/sftpgo#898]
Hi,

After uploading big files with SFTP backed with S3, renaming fails with:
```
S3: CopyObject, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Put "<file>?x-id=CopyObject": net/http: timeout awaiting response headers
```

With a 100MB file, this error doesn't happen.
With a 1GB, this error does happen.
Which tells me it has something to do with MultipartUpload.

Note: I was initially testing SFTPGo with an older version (most likely branch 2.1.x) and it didn't happen. This issue seems to be coming from more recent versions.

Let me know if I can help investigate!

**Comment by drakkan** [comment]
I did a quick test with a local MinIO instance and I cannot reproduce. 
Testing with real S3 will cost money and you are not sponsoring the project. I can't help sorry.

The now unsupported, v2.1.x uses the same code and the same timeout, the only difference is that in v2.1.x we used AWS SDK v1 while in v2.3.x we use AWS SDKv2. I think you will have the same error with v2.1.x too.

Please debug the issue yourself and send a PR. Thanks

**Comment by maximethebault** [comment]
Fair enough, will do!

**Comment by maximethebault** [comment]
Turns out I'm hitting this timeout:
https://github.com/drakkan/sftpgo/blob/main/vfs/s3fs.go#L948

This is expected as a rename on S3 is a copy + delete, and the copy can take a long time, especially for big files.
I'm hitting the timeout in a context of a singlepart copy (my file is below 5GB, at around 1GB).

I think the best approach would be to set the threshold for multipart copy much lower (or make it configurable), as it can greatly improve response time over a single part copy.
In the context of a SFTP-server, very long rename is most likely not expected and could be triggering client-side timeout (e.g. with a popular SFTP-client waiting for the rename command to complete: "connection timed out after 20 seconds of inactivity")

It's also probably a good idea to increase ResponseHeaderTimeout to something like 10 seconds, as a 500MB copy (which is the default part size in the case of a MPU) takes close to 5 seconds. We'd be safer with more margin.

Let me know what you think and I'll make a PR!

**Comment by drakkan** [comment]
Good catch. Maybe we could completely remove the response header timeout. There is a context timeout for each request. 
I also added the response header timeout to return a response faster in case of an error but maybe that's not a good idea. This explains why it worked in v2.1.x, we had no response header timeout in that version

**Comment by maximethebault** [comment]
The only case where I think the response header timetout could be useful in addition to the context timeout is when you have poor connectivity with AWS and would like to fail fast and let the AWS SDK retry the request - because the response header timeout will cause 2 additional internal retries in the AWS SDK. In this case the retries are transparent to the user and he will get a success if the retry succeeds.

But not sure this happens in practice, so I'm going to go your route and remove that response header timeout.

**Comment by maximethebault** [comment]
PR submitted

There would be room for improvement: a MultipartCopy initiated from the S3 web console is much faster than this because they set part size to 16MB and run all the parts in parallel, but this is my first time dealing with Go and I don't feel like I'm up to the task... yet!

BTW, as a first-timer, I'm amazed at how easy I could compile and run a Go project in local. I think this has much to do with the terrific job you're doing at maintaining this project. Kudos to you! I'll definitely try to get you a sponsoreship once this runs smoothly in production :) Thanks!

**Comment by drakkan** [comment]
> PR submitted
> 
> There would be room for improvement: a MultipartCopy initiated from the S3 web console is much faster than this because they set part size to 16MB and run all the parts in parallel, but this is my first time dealing with Go and I don't feel like I'm up to the task... yet!
> 

I'm working on a major  new feature. I can take a look once this development is done (about 2-3 weeks), it shouldn't be difficult.
Does the S3 console upload 5 parts in parallel or more?

> BTW, as a first-timer, I'm amazed at how easy I could compile and run a Go project in local. I think this has much to do with the terrific job you're doing at maintaining this project. Kudos to you! I'll definitely try to get you a sponsoreship once this runs smoothly in production :) Thanks!

Thank you. I dedicate a lot of my time to SFTPGo, this can't go on forever if sponsorships don't increase. I understand that it is often difficult to obtain sponsorships especially from large companies for bureaucracy, etc. but if everyone donated a small amount there would be no problems with the sustainability of the project.

I honestly would not like to release SFTPGo with a dual license and include some features only in the proprietary version, but if things continue like this I will be forced to.

**Comment by maximethebault** [comment]
> > PR submitted
> > There would be room for improvement: a MultipartCopy initiated from the S3 web console is much faster than this because they set part size to 16MB and run all the parts in parallel, but this is my first time dealing with Go and I don't feel like I'm up to the task... yet!
> 
> I'm working on a major new feature. I can take a look at parallel copy once this development is done (about 2-3 weeks), it shouldn't be difficult. Does the S3 console upload 5 parts in parallel or more?

Seems like it's doing 20 parts in parallel.


> > BTW, as a first-timer, I'm amazed at how easy I could compile and run a Go project in local. I think this has much to do with the terrific job you're doing at maintaining this project. Kudos to you! I'll definitely try to get you a sponsoreship once this runs smoothly in production :) Thanks!
> 
> Thank you. I dedicate a lot of my time to SFTPGo, this can't go on forever if sponsorships don't increase. I understand that it is often difficult to obtain sponsorships especially from large companies for bureaucracy, etc. but if everyone donated a small amount there would be no problems with the sustainability of the project.
> 
> I honestly would not like to release SFTPGo with a dual license and include some features only in the proprietary version, but if things continue like this I will be forced to.

100% on par with you. Will do!

**Comment by drakkan** [comment]
Hi,

the following patch add support for parallel multipart copy

[0001-S3-add-parallel-multipart-copy.zip](https://github.com/drakkan/sftpgo/files/9019182/0001-S3-add-parallel-multipart-copy.zip)

can you please confirm that it improves renaming performance? Thanks

**Comment by drakkan** [comment]
> Renaming performance is indeed greatly improved
> 
> With the same test file (1GB), before and after patch: 15s -> 4s

before v2.3.x multipart copy was not supported. Can you confirm that multipart copy outperforms a single copy object call? Just set the limit to something more than 1 GB for this test, thanks

**Comment by maximethebault** [comment]
Some benchmark:

100MB
singlepart: 2s
parallelized multipart: 3s

340MB
singlepart: 5s
parallelized multipart: 3s

700MB
singlepart: 7s
parallelized multipart: 3s

1GB
singlepart: 15s
non parallelized multipart: 15s
parallelized multipart: 4s


500MB looks OK
