### ISSUE TITLE
Any clients ?

### ISSUE THREAD

**Issue by gedw99** [drakkan/sftpgo#9]
A golang cli client ?
Can build a GUI client on top of the cli client too I think.

Let me know what's lacking .. :)

**Comment by drakkan** [comment]
Hi,

If you mean a cli or web client that manage sftpgo users and connections using the REST API then the answer is yes, I'll probably start developing it after finalizing the server features and releasing the first "stable" version.

An SFTP client like filezilla o winscp is out of scope of this project, there are free and features complete SFTP client already and I don't think another one could be useful or have more features than the existing ones, sorry

**Comment by drakkan** [comment]
Please reopen if you want to provide additional info, thanks!

**Comment by gedw99** [comment]
I was actually thinking of the SFTP Client.
I can develop it.

DO you think that some of the code can be shared between the Client and the Server ?

**Comment by drakkan** [comment]
I think not much code could be shared, I use an sftp client in test cases,

https://github.com/drakkan/sftpgo/blob/master/sftpd/sftpd_test.go#L1206

see sftpUploadFile and sftpDownloadFile some lines below too.

As said this is a server implementation, a client is out of scope, sorry. 

Thanks anyway for your suggestion
