### ISSUE TITLE
WebDAV upload fails sometimes with http2 enabled

### ISSUE THREAD

**Issue by ssesik** [drakkan/sftpgo#900]
Hi,

I am using `rclone copy` to copy a large amount of small files to the webdav server and some error has popped up.

`2022-07-01 13:12:17 ERROR : cache/07b420744932390239acb099c270dd5aee45-251768-906-jpg: Failed to copy: Put "https://dav.example.com/files/server/cache/07b420744932390239acb099c270dd5aee45-251768-906-jpg": http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error`

This error only happened to some of the files being uploaded.

manually adding --disable-http2 to rclone and the problem goes away.

I suspect this is a SFTPGo problem because I wasn't able to mount webdav to Nextcloud.

I am running sftpgo v2.3.1 with an http2 enabled nginx reverse proxy.

**Comment by ssesik** [comment]
https://github.com/stripe/stripe-go/issues/710

maybe similar?

**Comment by drakkan** [comment]
Hi,

from what I understand from your description http/2 is enabled in nginx and not in SFTPGo. Can you confirm?

Can you reproduce this issue connecting directly to SFTPGo? If so, some logs would be useful.

Regarding your Nextcloud issue please take a look at the logs to understand what is happening. Thanks

**Comment by drakkan** [comment]
> Hi,
> 
> I am using `rclone copy` to copy a large amount of small files to the webdav server and some error has popped up.
> 
> `2022-07-01 13:12:17 ERROR : cache/07b420744932390239acb099c270dd5aee45-251768-906-jpg: Failed to copy: Put "https://dav.example.com/files/server/cache/07b420744932390239acb099c270dd5aee45-251768-906-jpg": http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error`
> 

This looks like it needs to be defined on the client side (rclone in your case). The stripe bug you referenced seems to do an http client request

> This error only happened to some of the files being uploaded.
> 
> manually adding --disable-http2 to rclone and the problem goes away.
> 
> I suspect this is a SFTPGo problem because I wasn't able to mount webdav to Nextcloud.
> 
> I am running sftpgo v2.3.1 with an http2 enabled nginx reverse proxy.

**Comment by ssesik** [comment]
> from what I understand from your description http/2 is enabled in nginx and not in SFTPGo. Can you confirm?

Yes, if there is an option to enable it in sftpgo please tell me.

> Can you reproduce this issue connecting directly to SFTPGo? If so, some logs would be useful.

No. Although I have to manually change https://github.com/drakkan/sftpgo/blob/118744a8600358b63b133179c9a66c1702c69ad0/webdavd/server.go#L66
to `NextProtos:               []string{"h2", "http/1.1"},` in order make http2 work.

> Regarding your Nextcloud issue please take a look at the logs to understand what is happening. Thanks

It works when SFTPGo is listening on TCP but not on unix socket. The server just return 502 Bad Gateway.

Nextcloud log
`[no app in context] Warning: OCP\Files\StorageNotAvailableException: Sabre\HTTP\ClientHttpException: Bad Gateway at <<closure>>`

 `0. /var/www/nextcloud/lib/private/Files/Storage/DAV.php line 288
    OC\Files\Storage\DAV->convertException()`
 `1. /var/www/nextcloud/lib/private/Files/Storage/DAV.php line 585
    OC\Files\Storage\DAV->propfind()`
 `2. /var/www/nextcloud/lib/private/Files/Storage/Common.php line 459
    OC\Files\Storage\DAV->stat()`
 `3. /var/www/nextcloud/apps/files_external/lib/MountConfig.php line 131
    OC\Files\Storage\Common->test()`
 `4. /var/www/nextcloud/apps/files_external/lib/Controller/StoragesController.php line 288
    OCA\Files_External\MountConfig::getBackendStatus("*** sensitive parameters replaced ***")`
 `5. /var/www/nextcloud/apps/files_external/lib/Controller/UserGlobalStoragesController.php line 126
    OCA\Files_External\Controller\StoragesController->updateStorageStatus("*** sensitive parameters replaced ***")`
 `6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Files_External\Controller\UserGlobalStoragesController->show()`
 `7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()`
 `8. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()`
 `9. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()`
`10. /var/www/nextcloud/lib/base.php line 1023
    OC\Route\Router->match()`
`11. /var/www/nextcloud/index.php line 36
    OC::handleRequest()`

`GET /index.php/apps/files_external/userglobalstorages/6?testOnly=false
from 123.123.123.123 by user at 2022-07-01T14:26:21+00:00`

nginx error.log
`2022/07/01 17:18:40 [error] 6409#6409: *800 writev() failed (32: Broken pipe) while sending request to upstream, client: 207.90.192.159, server: dav.cloudethan.net, request: "PROPFIND / HTTP/2.0", upstream: "http://unix:/srv/sftpgo/webdav.sock:/", host: "dav.cloudethan.net"`

sftpgo log
`{"level":"info","time":"2022-07-02T07:41:08.510","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli20","uri":"http://dav.example.com/backuppdf","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.512","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli2g","uri":"http://dav.example.com/sync","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.514","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli30","uri":"http://dav.example.com/files","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.516","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli3g","uri":"http://dav.example.com/Music","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.519","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli40","uri":"http://dav.example.com/archive","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.731","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":209,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli4g","uri":"http://dav.example.com/2022-05-26_11-04-07.mkv","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.734","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli50","uri":"http://dav.example.com/Readme.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.736","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli5g","uri":"http://dav.example.com/todo.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.738","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli60","uri":"http://dav.example.com/AF_GPS.zip","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.740","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli6g","uri":"http://dav.example.com/server","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"info","time":"2022-07-02T07:41:08.741","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli70","uri":"http://dav.example.com/crypt","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`
`{"level":"error","time":"2022-07-02T07:41:08.753","sender":"DAV","connection_id":"DAV_cavvd541qtpf31koli7g","message":"stat error for path \"/說明.md\": stat /var/data/ethan/files/說明.md: no such file or directory"}`
`{"level":"info","time":"2022-07-02T07:41:08.753","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli7g","resp_status":404,"uri":"http://dav.example.com/%E8%AA%AA%E6%98%8E.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)","error":"file does not exist"}`
`{"level":"error","time":"2022-07-02T07:41:08.756","sender":"DAV","connection_id":"DAV_cavvd541qtpf31koli80","message":"stat error for path \"/README.md\": stat /var/data/ethan/files/README.md: no such file or directory"}`
`{"level":"info","time":"2022-07-02T07:41:08.756","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli80","resp_status":404,"uri":"http://dav.example.com/README.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)","error":"file does not exist"}`
`{"level":"info","time":"2022-07-02T07:41:08.758","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli8g","uri":"http://dav.example.com/Readme.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`

**Comment by ssesik** [comment]
After some more investigation, the original issue was mitigated by increasing `keepalive_requests` in nginx.
https://github.com/golang/go/issues/25009
https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_requests

I don't know if they are really related, but it works for me.

**Comment by drakkan** [comment]
> > from what I understand from your description http/2 is enabled in nginx and not in SFTPGo. Can you confirm?
> 
> Yes, if there is an option to enable it in sftpgo please tell me.
> 

Ok, so this looks like a client-side bug that could be fixed with something like the stripe patch you posted above. It seems unrelated to SFTPGo

> > Can you reproduce this issue connecting directly to SFTPGo? If so, some logs would be useful.
> 
> No. Although I have to manually change
> 
> https://github.com/drakkan/sftpgo/blob/118744a8600358b63b133179c9a66c1702c69ad0/webdavd/server.go#L66
> 
> 
> to `NextProtos: []string{"h2", "http/1.1"},` in order make http2 work.

I'm following [MinIO](https://github.com/minio/minio/pull/11523) here. It is extensively tested. SFTPGo prefers http/1.1

> > Regarding your Nextcloud issue please take a look at the logs to understand what is happening. Thanks
> 
> It works when SFTPGo is listening on TCP but not on unix socket. The server just return 502 Bad Gateway.
> 
> Nextcloud log `[no app in context] Warning: OCP\Files\StorageNotAvailableException: Sabre\HTTP\ClientHttpException: Bad Gateway at <<closure>>`
> 
> `0. /var/www/nextcloud/lib/private/Files/Storage/DAV.php line 288 OC\Files\Storage\DAV->convertException()` `1. /var/www/nextcloud/lib/private/Files/Storage/DAV.php line 585 OC\Files\Storage\DAV->propfind()` `2. /var/www/nextcloud/lib/private/Files/Storage/Common.php line 459 OC\Files\Storage\DAV->stat()` `3. /var/www/nextcloud/apps/files_external/lib/MountConfig.php line 131 OC\Files\Storage\Common->test()` `4. /var/www/nextcloud/apps/files_external/lib/Controller/StoragesController.php line 288 OCA\Files_External\MountConfig::getBackendStatus("*** sensitive parameters replaced ***")` `5. /var/www/nextcloud/apps/files_external/lib/Controller/UserGlobalStoragesController.php line 126 OCA\Files_External\Controller\StoragesController->updateStorageStatus("*** sensitive parameters replaced ***")` `6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225 OCA\Files_External\Controller\UserGlobalStoragesController->show()` `7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133 OC\AppFramework\Http\Dispatcher->executeController()` `8. /var/www/nextcloud/lib/private/AppFramework/App.php line 172 OC\AppFramework\Http\Dispatcher->dispatch()` `9. /var/www/nextcloud/lib/private/Route/Router.php line 298 OC\AppFramework\App::main()` `10. /var/www/nextcloud/lib/base.php line 1023 OC\Route\Router->match()` `11. /var/www/nextcloud/index.php line 36 OC::handleRequest()`
> 
> `GET /index.php/apps/files_external/userglobalstorages/6?testOnly=false from 123.123.123.123 by user at 2022-07-01T14:26:21+00:00`
> 
> nginx error.log `2022/07/01 17:18:40 [error] 6409#6409: *800 writev() failed (32: Broken pipe) while sending request to upstream, client: 207.90.192.159, server: dav.example.com, request: "PROPFIND / HTTP/2.0", upstream: "http://unix:/srv/sftpgo/webdav.sock:/", host: "dav.example.com"`
> 
> sftpgo log `{"level":"info","time":"2022-07-02T07:41:08.510","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli20","uri":"http://dav.example.com/backuppdf","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.512","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli2g","uri":"http://dav.example.com/sync","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.514","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli30","uri":"http://dav.example.com/files","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.516","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli3g","uri":"http://dav.example.com/Music","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.519","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli40","uri":"http://dav.example.com/archive","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.731","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":209,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli4g","uri":"http://dav.example.com/2022-05-26_11-04-07.mkv","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.734","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli50","uri":"http://dav.example.com/Readme.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.736","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli5g","uri":"http://dav.example.com/todo.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.738","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli60","uri":"http://dav.example.com/AF_GPS.zip","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.740","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli6g","uri":"http://dav.example.com/server","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"info","time":"2022-07-02T07:41:08.741","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli70","uri":"http://dav.example.com/crypt","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}` `{"level":"error","time":"2022-07-02T07:41:08.753","sender":"DAV","connection_id":"DAV_cavvd541qtpf31koli7g","message":"stat error for path \"/說明.md\": stat /var/data/ethan/files/說明.md: no such file or directory"}` `{"level":"info","time":"2022-07-02T07:41:08.753","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli7g","resp_status":404,"uri":"http://dav.example.com/%E8%AA%AA%E6%98%8E.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)","error":"file does not exist"}` `{"level":"error","time":"2022-07-02T07:41:08.756","sender":"DAV","connection_id":"DAV_cavvd541qtpf31koli80","message":"stat error for path \"/README.md\": stat /var/data/ethan/files/README.md: no such file or directory"}` `{"level":"info","time":"2022-07-02T07:41:08.756","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli80","resp_status":404,"uri":"http://dav.example.com/README.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)","error":"file does not exist"}` `{"level":"info","time":"2022-07-02T07:41:08.758","sender":"webdavd","content_length":"469","depth":"0","elapsed_ms":0,"method":"PROPFIND","proto":"HTTP/1.1","remote_addr":"123.123.123.123","request_id":"cavvd541qtpf31koli8g","uri":"http://dav.example.com/Readme.md","user_agent":"sabre-dav/4.2.1 (http://sabre.io/)"}`

I only see a not found error in these logs. This error should not be fatal. Try comparing these logs to those when SFTPGo listens over TCP to understand the differences. 

I'm not going to install Nextcloud and try to reproduce the issue sorry. I only do this type of debugging for project sponsors

**Comment by drakkan** [comment]
> After some more investigation, the original issue was mitigated by increasing `keepalive_requests` in nginx. [golang/go#25009](https://github.com/golang/go/issues/25009) https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_requests
> 
> I don't know if they are really related, but it works for me.

Ok, but the above bug affects Go http clients. You are running SFTPGo/nginx server side. Try to report the issue to rclone

**Comment by ssesik** [comment]
Thanks anyway, will investigate further.

**Comment by drakkan** [comment]
> Thanks anyway, will investigate further.

Ok thanks. If you find something related to SFTPGo you can report it here or open a new issue
