### ISSUE TITLE
Alternative for remote encrypted folders gocryptfs

### ISSUE THREAD

**Issue by gotjoshua** [drakkan/sftpgo#901]
Any considerations to implement gocryptfs ?

**Comment by drakkan** [comment]
Hi,

SFTPGo already supports Data At Rest Encryption, take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/dare.md). 

If you want to use a fuse-based crypt fs you can just mount your partition and add in SFTPGo users with home directory to a path where the partition is mounted.

If this does not answer to your question please elaborate.

**Comment by drakkan** [comment]
Please reopen providing more info if the above answer is not enough
