### ISSUE TITLE
Need an example  command to load sftp users on a docker platform.

### ISSUE THREAD

**Issue by ashokmarch** [drakkan/sftpgo#902]
I have this from the doc...

--loaddata-from string. Load users and folders from this file. The file must be specified as absolute path and it must contain a backup obtained using the dumpdata REST API or compatible content. The default value is empty or the value of SFTPGO_LOADDATA_FROM environment variable

**Comment by drakkan** [comment]
Take a look [here](https://github.com/drakkan/sftpgo/discussions/375). The dump format is documented in REST API, see [here](https://sftpgo.stoplight.io/docs/sftpgo/0f64b9a4deb77-dump-data). The easiest way to get a dump to load is to create your users in a demo instances and then export them from the maintenance section in the web ui

**Comment by drakkan** [comment]
You should have enough info. For step-by-step support a [donation/sponsorship](https://github.com/drakkan/sftpgo#sponsors) is required
