### ISSUE TITLE
webdav cannot set network drive for windows

### ISSUE THREAD

**Issue by jackadam1981** [drakkan/sftpgo#913]
webdav cannot set network drive for windows

I can use winscp's WebDAV protocol to access

But it cannot be used as a network location in windows

As a network drive for your local computer

**Comment by drakkan** [comment]
It works for me, from the [docs](https://github.com/drakkan/sftpgo/blob/main/docs/webdav.md):

> if you use the native Windows client please check its usage and pay particular attention to the [registry settings](https://docs.microsoft.com/en-us/iis/publish/using-webdav/using-the-webdav-redirector#webdav-redirector-registry-settings). The default file size limit is 50MB and if you don't configure SFTPGo to use HTTPS you have to set BasicAuthLevel to 2

**Comment by jackadam1981** [comment]
Thanks
need to set registry
BasicAuthLevel =2
FileSizeLimitInBytes =ffffffff

max file 4G
