### ISSUE TITLE
Adding video streaming and "media gallery" on Web Client

### ISSUE THREAD

**Issue by lispstudent** [drakkan/sftpgo#914]
At the moment the user cannot stream video content from the browser, or view images in a "gallery" like sequence.

Would you consider adding video streaming and "media gallery" on Web Client, perhaps similar to [filestash](https://github.com/mickael-kerjean/filestash) and [filebrowser](https://github.com/filebrowser/filebrowser)?

Thank you again for `sftpgo`. It a delightful piece of software. It is so well engineering, it is inspiring and gratifying to use. Thanks.

**Comment by drakkan** [comment]
This is not planned for now. Do you want to sponsor this feature? Thanks

**Comment by lispstudent** [comment]
We are a tiny non-profit, no funds even for volunteers. But I will definitely pass this  on. Thank you!

**Comment by drakkan** [comment]
I'm more a backend developer. It is not funny, for me, working at the UI level, sorry

**Comment by lispstudent** [comment]
I fully understand! In case, if in the future you would have time, I am sure those two projects, which are also go-based, would not mind if somebody borrows some idea/code.

Congratulations again on your `sftpgo`. It is a breath of fresh air to use.

**Comment by drakkan** [comment]
> I fully understand! In case, if in the future you would have time, I am sure those two projects, which are also go-based, would not mind if somebody borrows some idea/code.
> 
> Congratulations again on your `sftpgo`. It is a breath of fresh air to use.

I'll try to take a look, but no promises

**Comment by lispstudent** [comment]
Wonderful!

**Comment by lispstudent** [comment]
> I'm more a backend developer. It is not funny, for me, working at the UI level, sorry

To me, the backend is what make `sftpgo` standout, it is so well engineered and covers so many use-cases that cannot be dealt with by other similar solutions.

You could perhaps consider simply adopting one of those two external Web-based SFTP clients, or any other you feel proper for `sftpgo`. Then, only a bridge between the backend accounts and the chosen web client would be needed.

In that way, there would not be need to worry about web client gui.

**Comment by lispstudent** [comment]
> 
[web client: add HTML5 player](https://github.com/drakkan/sftpgo/commit/a0bbcf6ebb5836d4117dcc6b7e4a595414d114b3)

Wonderful! Thank you SO much!

🎉🎉🎉

**Comment by MasterKe2003** [comment]
> > 
> 
> [网页客户端：添加 HTML5 播放器](https://github.com/drakkan/sftpgo/commit/a0bbcf6ebb5836d4117dcc6b7e4a595414d114b3)
> 
> 太棒了！非常感谢！
> 
> 🎉🎉🎉

这个如何使用，我没有看到预览
