### ISSUE TITLE
S3 Backend does not handle wildcard patterns

### ISSUE THREAD

**Issue by valves-ops** [drakkan/sftpgo#915]
### Description
When trying to list files on an FTP directory by providing a wildcard pattern, such as `*.xml`, the pattern is directly passed into S3, which fails to properly handle it returning a 404 error.

For example, when I select the `/IN` directory on my test FTP server and use the `*.xml` pattern to list all XML files, this is the error I get:
```
{"level":"error","time":"2022-07-08T12:13:40.079","sender":"FTP","connection_id":"FTP_0_25","message":"stat error for path \"/IN/*.xml\": operation error S3: HeadObject, https response error StatusCode: 404, RequestID: J2ASDJS078S5S, HostID: 4eS7m3YC5YWXeW7UwtlxTtQA/BdXLASDASHJ*909asd3ipVdU1fItxEFE+qBYpjMM=, api error NotFound: Not Found"}
```

And as can be seen in the screenshot below, the given directory is full of XML files:
![Screen Shot 2022-07-08 at 09 17 22](https://user-images.githubusercontent.com/14910855/177990746-31932d8f-82b5-43dc-95de-03e5424caefa.png)

If I repeat the same process on a user that's configured with the Local Filesystem as the storage backend, I get the XML files as expected, even though the logs report an error as well.

### How to Reproduce

1. Setup a user with the S3 Storage Backend (username: s3_user)
2. Setup a user with the Local Filesystem Storage Backend (username: local_fs_user)
3. Create a folder (for example, DIRECTORY) with files sharing a common extension (for example, `.xml`) for both users
4. Use the Python script below to retrieve a list of the files filtered by the extension
```
import ftplib

ftp = ftplib.FTP_TLS("<ftp_server_host>")
ftp.login("<username>", "<password>")
ftp.prot_p()

ftp.cwd("/DIRECTORY")
files = []
ftp.dir('*.xml', files.append)
print(files)
```
6. Expected Result for `s3_user`
```
>>> ftp.prot_p()
'200 OK'
>>> ftp.cwd("/IN")
files = []'250 CD worked on /IN'
>>> files = []
>>> ftp.dir('*.xml', files.append)
>>> print(files)
[]
```
   Related logs
```
{"level":"error","time":"2022-07-08T12:49:12.025","sender":"FTP","connection_id":"FTP_0_31","message":"stat error for path \"/IN/*.xml\": operation error S3: HeadObject, https response error StatusCode: 404, RequestID: BV8TASDASDM1Q, HostID: 0U92shROATaASDASDASDASDASDASDJiuWprYMCph0r+d7zA=, api error NotFound: Not Found"}
```

8. Expected Result for `local_fs_user`
```
>>> ftp.prot_p()
'200 OK'
>>> ftp.cwd("/IN")
'250 CD worked on /IN'
>>> files = []
>>> ftp.dir('*.xml', files.append)
>>> print(files)
['-rw-r--r-- 1 ftp ftp          371 Jul  7 16:09 actiea____43.xml', '-rw-r--r-- 1 ftp ftp         4587 Jul  7 16:09 acti_____028-058.xml', '-rw-r--r-- 1 ftp ftp         4859 Jul  7 16:09 actie____975.xml']
```
   Related logs (it messages a failure, but it does return the files properly filtered)
```
{"level":"error","time":"2022-07-08T12:41:16.701","sender":"FTP","connection_id":"FTP_0_28","message":"stat error for path \"/IN/*.xml\": stat /srv/sftpgo/data/local_fs_test/IN/*.xml: no such file or directory"}
{"level":"debug","time":"2022-07-08T12:41:16.701","sender":"FTP","connection_id":"FTP_0_28","message":"error listing directory: open /srv/sftpgo/data/local_fs_test/IN/*.xml: no such file or directory"}
```

**Comment by drakkan** [comment]
Hi,

do you want to send a patch or [sponsor](https://github.com/sponsors/drakkan) this debug/improvement? Thanks

**Comment by valves-ops** [comment]
Hey @drakkan,

Sorry for the late response, I was discussing internally with my company whether they were open to sponsoring or allowing me the time to contribute with a patch, but it seems you've already done it yourself. From what I've understood, now it is capable of handling wildcards on the last path level for virtual FS such as S3 buckets, is that correct?

**Comment by valves-ops** [comment]
@drakkan could you please explain the changes associated with this issue intended to do? If they did not handle wildcards for the S3 bucket, were they targeted at addressing the error that happens when using wildcards on the local FS?

I read through the PR but I'm not familiar enough with the SFTPGo codebase to properly understand it.

**Comment by drakkan** [comment]
@valves-ops until recently I have provided free and quick support to everyone, I'm sorry but that's not the case anymore. I support project sponsors/donors, they ensure that the project will stay alive.

This answer is very irritating to me:

> Sorry for the late response, I was discussing internally with my company whether they were open to sponsoring or allowing me the time to contribute with a patch, but it seems you've already done it yourself

Please take a look [here](https://words.filippo.io/pay-maintainers/) and read more than one time the paragraph "Pay for maintenance" to be sure to understand it.

Good luck for your project.
