### ISSUE TITLE
Feature Request: File extension upload restrictions

### ISSUE THREAD

**Issue by smidley** [drakkan/sftpgo#916]
It would be great if there was a way to have a list of file extensions that could be restricted from file uploads.

**Comment by drakkan** [comment]
This is supported
![Schermata del 2022-07-09 09-47-01](https://user-images.githubusercontent.com/553263/178096872-2996a83f-2300-4e1c-bb72-31a6f49be603.png)

and you can also use a pre-upload hook for this
