### ISSUE TITLE
Creating folders via API fails sporadically

### ISSUE THREAD

**Issue by fitted-dan** [drakkan/sftpgo#920]
Hello @drakkan!
I'm trying to automate the creation of users by making use of the SFTPGo API. Currently I have a method that calls `POST /api/v2/users` to create a user and right after that I call `POST /api/v2/user/dirs?path=${folder}&mkdir_parents=true` to create a folder inside the new user's home. 

For the second call I'm impersonating the newly created user by setting the `X-SFTPGO-API-KEY` header with the value of the api key + user name: `the_api_key.username`.

For the backend storage I'm using google cloud with a configuration similar to:
```
{
   provider: 2,
   gcsconfig: {
      bucket: this.defaultBucket,
      automatic_credentials: 1,
      key_prefix: `${type}/${username}/sftpgo`
   }
}
```

Now, the problem that I'm facing is that SFTPGo is sporadically failing to create the folder in the second step and all I see in the logs are errors similar to this one:

```
error creating dir: "brand/testuser/sftpgo/inventory.partial" error: open /srv/sftpgo/data/testuser/pipefile3411217826: no such file or directory
```
I was running SFTPGo v2.2.2 when I started noticing this errors, so I upgraded to v2.3.1, but unfortunately I keep getting the error in the newest version.

Do you know what could be causing this error?

Thanks in advance!

**Comment by drakkan** [comment]
Hi,

please share more details about your SFTPGo usage. Do you have multiple instances connected to a single database with a load balancer? Do you have an error log [here](https://github.com/drakkan/sftpgo/blob/main/vfs/osfs.go#L230)?

**Comment by fitted-dan** [comment]
Hi! Thanks for the quick response!

We run on Kubernetes, and there are two SFTPGo containers. Our backend database is Postgres on Cloud SQL, so there are also some cloud sql proxy containers to allow us to connect to Cloud SQL and as I mentioned before our storage backend is Google Cloud Storage.

Because of our setup we had to configure `session affinity` on our gcp load balancer to fix the login issues that we were experiencing when using the web admin / client. We also have `SFTPGO_DATA_PROVIDER__IS_SHARED` set to 1 and after upgrading to version v2.3.1 (from version v2.2.2) we disabled `SFTPGO_HTTPD__TOKEN_VALIDATION` because we were getting the `form token is not valid` error.

I checked the [link](https://github.com/drakkan/sftpgo/blob/main/vfs/osfs.go#L230) you provided and I have seen that error in our logs but that's not the error that is generated when the SFTPGo fails to create a folder, all we get are errors similar to:

```
error creating dir: "brand/testuser/sftpgo/inventory.full" error: open /srv/sftpgo/data/testuser/pipefile3498311392: no such file or directory
```
Now, by looking in the SFTPGo repo, it seems that this error might be generated [here](https://github.com/drakkan/sftpgo/blob/1d9a8cae87d2e5755105819ed1448bca2dc22136/common/connection.go#L340)

For now our "band-aid" fix was to retry the folder creation before giving up... I initially set it to re-try up to 3 times, however from time to time it was failing so for now I set it to retry up to 5 times, but from our testing I was able to observe that only very few had to be retried up to 4 times.

**Comment by drakkan** [comment]
Please confirm that the reported issue is fixed in the above commit. Update docker images (edge variants) will be available as soon as the [CI](https://github.com/drakkan/sftpgo/actions/runs/2654571688) ends

**Comment by drakkan** [comment]
> Hi! Thanks for the quick response!
> 
> We run on Kubernetes, and there are two SFTPGo containers. Our backend database is Postgres on Cloud SQL, so there are also some cloud sql proxy containers to allow us to connect to Cloud SQL and as I mentioned before our storage backend is Google Cloud Storage.
> 
> Because of our setup we had to configure `session affinity` on our gcp load balancer to fix the login issues that we were experiencing when using the web admin / client. We also have `SFTPGO_DATA_PROVIDER__IS_SHARED` set to 1 and after upgrading to version v2.3.1 (from version v2.2.2) we disabled `SFTPGO_HTTPD__TOKEN_VALIDATION` because we were getting the `form token is not valid` error.
> 

This is a security risk. You should configure your proxy headers/setting appropriately. In your setup a token can be used from any IP address and not only from the one it was issued for

> I checked the [link](https://github.com/drakkan/sftpgo/blob/main/vfs/osfs.go#L230) you provided and I have seen that error in our logs but that's not the error that is generated when the SFTPGo fails to create a folder, all we get are errors similar to:
> 
> ```
> error creating dir: "brand/testuser/sftpgo/inventory.full" error: open /srv/sftpgo/data/testuser/pipefile3498311392: no such file or directory
> ```
> 
> Now, by looking in the SFTPGo repo, it seems that this error might be generated [here](https://github.com/drakkan/sftpgo/blob/1d9a8cae87d2e5755105819ed1448bca2dc22136/common/connection.go#L340)
> 
> For now our "band-aid" fix was to retry the folder creation before giving up... I initially set it to re-try up to 3 times, however from time to time it was failing so for now I set it to retry up to 5 times, but from our testing I was able to observe that only very few had to be retried up to 4 times.

**Comment by fitted-dan** [comment]
> Please confirm that the reported issue is fixed in the above commit. Update docker images (edge variants) will be available as soon as the [CI](https://github.com/drakkan/sftpgo/actions/runs/2654571688) ends

Wow, you are quick! I'll let you know...
Thank you!

**Comment by fitted-dan** [comment]
> > Hi! Thanks for the quick response!
> > We run on Kubernetes, and there are two SFTPGo containers. Our backend database is Postgres on Cloud SQL, so there are also some cloud sql proxy containers to allow us to connect to Cloud SQL and as I mentioned before our storage backend is Google Cloud Storage.
> > Because of our setup we had to configure `session affinity` on our gcp load balancer to fix the login issues that we were experiencing when using the web admin / client. We also have `SFTPGO_DATA_PROVIDER__IS_SHARED` set to 1 and after upgrading to version v2.3.1 (from version v2.2.2) we disabled `SFTPGO_HTTPD__TOKEN_VALIDATION` because we were getting the `form token is not valid` error.
> 
> This is a security risk. You should configure your proxy headers/setting appropriately. In your setup a token can be used from any IP address and not only from the one it was issued for
> 
> > I checked the [link](https://github.com/drakkan/sftpgo/blob/main/vfs/osfs.go#L230) you provided and I have seen that error in our logs but that's not the error that is generated when the SFTPGo fails to create a folder, all we get are errors similar to:
> > ```
> > error creating dir: "brand/testuser/sftpgo/inventory.full" error: open /srv/sftpgo/data/testuser/pipefile3498311392: no such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now, by looking in the SFTPGo repo, it seems that this error might be generated [here](https://github.com/drakkan/sftpgo/blob/1d9a8cae87d2e5755105819ed1448bca2dc22136/common/connection.go#L340)
> > For now our "band-aid" fix was to retry the folder creation before giving up... I initially set it to re-try up to 3 times, however from time to time it was failing so for now I set it to retry up to 5 times, but from our testing I was able to observe that only very few had to be retried up to 4 times.

Yes! You are right, we need to fix it but it was the only solution to allow us to continue testing.

Thanks again!!!
