### ISSUE TITLE
Support for setstat 

### ISSUE THREAD

**Issue by readl1** [drakkan/sftpgo#922]
We have a user of sftpgo who is trying to change permissions on a file after writing data (chmod 666) but is getting an error for set stat. It breaks their automated workflow if this functionality is not support are we able to not throw an error and continue on? 

I think the error is similar to this:

https://docs.aws.amazon.com/transfer/latest/userguide/transfer-file.html#avoid-set-stat

**Comment by drakkan** [comment]
Hi,

this is supported, just read the docs or consider a [donation/sponsorship](https://github.com/drakkan/sftpgo#sponsors) if you want step-by-step support
