### ISSUE TITLE
Pressing edit does nothing

### ISSUE THREAD

**Issue by NHOrus** [drakkan/sftpgo#93]
Version SFTPGo 0.9.6-4fe51f7-2020-03-07T14:40:07Z, windows

Pressing EDIT after selecting already created user does nothing.

**Comment by drakkan** [comment]
Hi, which browser are you using? I just tested in chrome and it works as expected

**Comment by NHOrus** [comment]
Weird, I used it in Chrome. dev tools show no network activity
Maybe error on installation?

**Comment by drakkan** [comment]
If you can see the users list then the installation should be ok. You can also check if the windows service is running.

Is this an update from a previous version or a first installation? Are you using windows 7 or 10?

**Comment by NHOrus** [comment]
It's first installation, Windows Server 2012R2 (so Win 7)

Windows service is running.

And after I restarted the service edit function began to work as expected.

Thank you for support, have a nice day!

**Comment by drakkan** [comment]
well this is strange, 

I mainly work on Linux and I have a Windows 7 and a Windows 10 VM to build the setup and to do basic tests, please let me know if you find Windows specific issues, thanks!
