### ISSUE TITLE
sftp connection_failed

### ISSUE THREAD

**Issue by abe520** [drakkan/sftpgo#930]
VLC(Android app) failed to connect  via SFTP in 2.3.x-alpine.The same config is ok in v2.2.2-alpine.
```
docker log: error setting max procs: open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory

{"level":"debug","time":"2022-07-21T14:56:23.247","sender":"connection_failed","client_ip":"192.168.1.2","username":"","login_type":"no_auth_tryed","protocol":"SSH","error":"ssh: no common algorithm for key exchange; client offered: [diffie-hellman-group-exchange-sha256 diffie-hellman-group-exchange-sha1 diffie-hellman-group14-sha1 diffie-hellman-group1-sha1], server offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha256 ext-info-s]"}
{"level":"debug","time":"2022-07-21T14:56:23.260","sender":"sftpd","message":"failed to accept an incoming connection: ssh: no common algorithm for key exchange; client offered: [diffie-hellman-group-exchange-sha256 diffie-hellman-group-exchange-sha1 diffie-hellman-group14-sha1 diffie-hellman-group1-sha1], server offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha256 ext-info-s]"}
```

**Comment by drakkan** [comment]
Hi,

In v2.3.x sha1 based KEXs are disabled by default for security reasons, your VLC client seems to not support anything better so you can enable them in your config [file](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L86). Take a look [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md) for the supported values (expand the "Configuration file" section and search for `kex_algorithms`)

**Comment by abe520** [comment]
I used ed25519.how to get new one(Generating by command or website)

**Comment by drakkan** [comment]
> I used ed25519.how to get new one(Generating by command or website)

I don't understand sorry. It seems you are confusing host keys with kex_algorithms. You don't have to generate anything. You have to simply change the SFTPGo configuration file as explained above and restart the service to apply the changes
