### ISSUE TITLE
No easy way to access effective user properties in custom actions

### ISSUE THREAD

**Issue by mmetz-isa** [drakkan/sftpgo#931]
Hello,

I'm currently implementing a custom provider hook (the executable kind) to make a set of directories on creating users.  Those users are all members of a primary group `suppliers`, which has set the home directory to `/srv/sftpgo/data/suppliers/%username%`.  The [groups documentation](/drakkan/sftpgo/blob/main/docs/groups.md) states:

> home dir, if set for the group will replace the one defined for the user. The %username% placeholder is replaced with the username

However, when recieving the user object within the hook the environment variable `SFTPGO_PROVIDER_OBJECT` contains the default path, in this context `/srv/sftpgo/data/%username%`.

Now I see several ways to work around this:
* Hard code the group home directory.
* Query the group home directory via the sftpgo API and do the substitution by hand.
* Create the directories via the sftpgo API.

However, I'm wondering if the passed user object in the context of the provider hooks should contain the effective properties (with group inheritance applied) instead.

**Comment by drakkan** [comment]
> Hello,
> 
> I'm currently implementing a custom provider hook (the executable kind) to make a set of directories on creating users. Those users are all members of a primary group `suppliers`, which has set the home directory to `/srv/sftpgo/data/suppliers/%username%`. The [groups documentation](/drakkan/sftpgo/blob/main/docs/groups.md) states:
> 
> > home dir, if set for the group will replace the one defined for the user. The %username% placeholder is replaced with the username
> 
> However, when recieving the user object within the hook the environment variable `SFTPGO_PROVIDER_OBJECT` contains the default path, in this context `/srv/sftpgo/data/%username%`.
> 
> Now I see several ways to work around this:
> 
> * Hard code the group home directory.
> * Query the group home directory via the sftpgo API and do the substitution by hand.
> * Create the directories via the sftpgo API.
> 
> However, I'm wondering if the passed user object in the context of the provider hooks should contain the effective properties (with group inheritance applied) instead.

The external auth hook returns an empty string or the updated user. If the group inheritance is applied it is very hard to return a modified user

**Comment by mmetz-isa** [comment]
I'm not following you.  Is the external auth hook called on [provider events](/drakkan/sftpgo/blob/main/docs/custom-actions.md)?  I was under the assumption provider events are only created and the documentation even states so:

> Actions will not be fired for internal updates, such as the last login or the user quota fields, or after external authentication.

**Comment by drakkan** [comment]
> The program must write, on its standard output:
a valid SFTPGo user serialized as JSON if the authentication succeeds. The user will be added/updated within the defined data provider
an empty string, or no response at all, if authentication succeeds and the existing SFTPGo user does not need to be updated. Please note that in versions 2.0.x and earlier an empty response was interpreted as an authentication error
a user with an empty username if the authentication fails

the user you return will update the data provider (even if actions does not fire)

However these requests are outside the community based support. If you want to discuss this please consider a sponsorship

**Comment by mmetz-isa** [comment]
For clarification:

> the user you return will update the data provider (even if actions does not fire)

There is no external authentication involved.  The users are created via API and UI and I wanted to use the provider event hooks to ensure the presense of the directories.

> However these requests are outside the community based support. If you want to discuss this please consider a sponsorship

Sure thing. I will suggest a sponsoership internally.

**Comment by drakkan** [comment]
> For clarification:
> 
> > the user you return will update the data provider (even if actions does not fire)
> 
> There is no external authentication involved. The users are created via API and UI and I wanted to use the provider event hooks to ensure the presense of the directories.

sorry, I read quickly and was convinced you were using the external authentication. The provider event is generally used for auditing purpose I think it must contain the modified object. In this case probably the best approach, for now, is to query the group using the API and do the substitution by hand. In the future I could add a new API to return the user with with group inheritance applied, but you need to call this API in any case
 
> 
> > However these requests are outside the community based support. If you want to discuss this please consider a sponsorship
> 
> Sure thing. I will suggest a sponsorship internally.

This is important, the project will die in the long run if I don't get enough sponsorships/donations and you will be forced to pay for a similar proprietary solution

**Comment by drakkan** [comment]
a smart way to do this would be with the new [EventManager](https://github.com/drakkan/sftpgo/blob/main/docs/eventmanager.md) added in the main branch. So no external hook would be required anymore. It is something that I would like to add in the future but I don't have a definite plan. Let's see if it is so useful that someone wants to sponsor it
