### ISSUE TITLE
sftpgo initprovider bails out when creating higher number of user accounts.

### ISSUE THREAD

**Issue by mmetz-isa** [drakkan/sftpgo#932]
Hello,

sftpgo version: SFTPGo 2.3.1-ca4da2f-2022-06-10T17:11:30Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable
uname -a: Linux <some server name> 1 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux
os release: Debian GNU/Linux 11 (bullseye)

when bulk importing users to a sqlite backed data provider with the following command line:

```
sudo -u sftpgo sftpgo initprovider --config-dir /etc/sftpgo --loaddata-from /tmp/vsftpd-users --loaddata-clean --loaddata-mode 0
```

the command bails out with the following message:

```
2022-07-22T16:13:17.462 INF Initializing provider: "sqlite" config file: "/etc/sftpgo/sftpgo.yaml"
2022-07-22T16:13:17.464 INF the data provider is up to date
2022-07-22T16:13:33.445 ERR Cannot load initial data: unable to restore users from file "/tmp/vsftpd-users": unable to restore user "<user name redacte>": unable to open database file: too many open files
```

With that only a subset of the passed users or none at all are created within the backend.

The file /tmp/vsftpd-users contains 1271 user definitions, with the following fields populated:
* status
* username
* password
* description
* email
* additional_info
* groups
* permissions

The problem seems to occur when missing users are created, updating existing users didn't trigger the message.

As a workaround I splitted up the user list into chunks of 100 users, which loads fine so far.

Loading the full /tmp/vsftpd-users as described via the Web Admin UI in the 'add and update' mode seems also work without errors.

I guess the default ulimit on open file handles of 1024 plays  a part into this.

**Comment by drakkan** [comment]
Strange, I have a pureftpd file with 1821 users

```
cat pureftpd.passwd | wc -l
1821
```

no issues and the open file descriptors is very low while importing. 

```
time ./sftpgo initprovider --loaddata-from /tmp/users.json --loaddata-mode 0
2022-07-22T17:22:13.223 INF Initializing provider: "sqlite" config file: "/tmp/sftpgo/sftpgo.json"
2022-07-22T17:22:13.224 INF the data provider is up to date
2022-07-22T17:22:14.112 INF data loaded from file "/tmp/users.json" mode: 0

real	0m0,916s
user	0m0,996s
sys	0m0,255s
```

In my test case I have no groups, maybe the issue is there. Can you please share your reproducer with usernames/emails, other private info redacted?

If you import from the web UI, can you report the open file descriptors before and after the import? thanks

**Comment by drakkan** [comment]
I think you have a hook defined and so 1271 actions are executed concurrently in your case
