### ISSUE TITLE
When creating a user it still requires filesystem config even when assigning to primary group

### ISSUE THREAD

**Issue by alaughlin** [drakkan/sftpgo#933]
Apologies if I am not understanding how this works, but I am noticing that I create a group with S3 as the filesystem, and then attempt to create a user and choose the group as their primary group, WebAdmin still requires me to completely fill out the filesystem config for the user anyways.

Based on the docs it seems to imply that it should be inheriting the filesystem config from the group, is that not the case?

**Comment by drakkan** [comment]
Hi,

yes the filesystem is inherited from the group. Just leave the storage for the user to local and the home dir blank. SFTPGo will only compliants if you are on Windows and/or you don't have a [users_base_dir](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L197) set (by default it is set in Linux packages and Docker images).

If SFTPGo validates the merged settings and after user creation you change the group settings, we would have to validate all users in that group before saving the new group settings (think about groups with 100 or more users, it would take a long time) or leave some users that may not work. So a user must be valid even without the inherited settings. Hope it is more clear now

**Comment by alaughlin** [comment]
Hi! Still running into issues 😞 

I'm on Mac OS 12.5 and have this in my config under `"data_provider"`
`"users_base_dir": "/usr/local/var/sftpgo/data"`

Here's what my group config looks like:
![Screen Shot 2022-07-22 at 12 08 24](https://user-images.githubusercontent.com/5217745/180480772-555714c5-52d5-4ade-94fc-382b3ded407f.png)

And here's the error I get attempting to create a user and assign them to the group:
![Screen Shot 2022-07-22 at 12 14 28](https://user-images.githubusercontent.com/5217745/180480891-db7052f3-1e4d-4ffb-b1d9-8aa1ba5a3eae.png)

**Comment by drakkan** [comment]
Strange, if you installed SFTPGo from homebrew you should have this

![Schermata del 2022-07-22 18-21-57](https://user-images.githubusercontent.com/553263/180482260-3a688455-b7da-41e9-a2db-37533d4edabb.png)

note the "Leave blank for an appropriate default". If you added the users_base_dir manually please ensure to restart the SFTPGo service

**Comment by alaughlin** [comment]
I did install SFTPGo from homebrew, just a few hours ago. I actually did not add `users_base_dir`, it was already set in the default config file provided by the formula. Maybe something is off there?

**Comment by drakkan** [comment]
and are you running sftpgo as a service or manually. If manually please post the command you used. Maybe there is something wrong in the brew formula.

**Comment by alaughlin** [comment]
I'm running it manually right now, like so:
`sftpgo serve`

`sftpgo` is symlinked to `/usr/local/Cellar/sftpgo/2.3.1/bin/sftpgo`

Let me know if you need anything else!

**Comment by drakkan** [comment]
ah ok, so you are not using the config file you posted above, please try:

```
sftpgo serve -l "" --config-file /usr/local/etc/sftpgo/sftpgo.json
```

the sftpgo.db will be created in the current directory. Your user must be able to write to `/usr/local/var/sftpgo/data` or just change the data location to a directory you can write to in the config file.

Or simply start sftpgo as service (this is how I test the formula)

```
sudo brew services start sftpgo
```

**Comment by alaughlin** [comment]
Ok, I started it as a service and that lets me create the user, so thank you! But I am confused, as it now seems to use my local disk as the storage, when I need it to use the S3 bucket as I defined in the group. Am I not understanding something here?

**Comment by alaughlin** [comment]
^ Ignore my last comment. I see that this is virtual and that it is actually uploading the files to S3. Thanks so much for the help!

**Comment by drakkan** [comment]
> ^ Ignore my last comment. I see that this is virtual and that it is actually uploading the files to S3. Thanks so much for the help!

Yes, if you remove the group membership you will use the local directory
