### ISSUE TITLE
Allow no passwords for users

### ISSUE THREAD

**Issue by optix2000** [drakkan/sftpgo#935]
Allow blank passwords to be used. Right now you can _set_ a blank password for a user, but it can never be used as there's a hard-coded blank password check.

Blank passwords would be good for guest/anonymous uses to have read-only access.

This currently cannot be worked around with check password hooks as this hard-coded check runs before any hooks.

https://github.com/drakkan/sftpgo/blob/1470018054736d6770303d90e36e72b1e26767de/dataprovider/dataprovider.go#L2769-L2770

**Comment by drakkan** [comment]
You can set an empty passwords because you can authenticate using certificates, public keys etc. But we don't allow to authenticate with empty passwords by purpose. 
I'm not a big fan of anonymous users, they are common for legacy FTP server (a password is required and generally any password is accepted). For SFTP there is a specific authentication method that does not require credentials (it is not supported in SFTPGo and I don't plan to support it).

However you can configure a web share with no credentials or accept any credentials in your external auth hook, see [here](https://github.com/drakkan/sftpgo/issues/373#issuecomment-820428107).

Please better explain your use case, do you want anonymous FTP users? Or do you want to allow login with no passwords for SFTP, HTTP etc.? Are you migrating from another system with this feature?

**Comment by optix2000** [comment]
This is primarily for WebDAV and FTP, where anonymous/no auth is allowed for read-only.

WebDAV (IIS, nginx, Apache) also allows no-auth for certain verbs (eg PROPFIND, GET) when configured that way. See https://live.sysinternals.com
For example FTP servers (PureFTPd, vsftpd) will allow anonymous users with no password when that setting is enabled.

> they are common for legacy FTP server (a password is required and generally any password is accepted)

PureFTPd does not prompt for a password at all when the username is "anonymous". You can see an example of this with ftp://ftp.gnu.org.

```
 % ftp ftp.gnu.org
Trying 209.51.188.20:21 ...
Connected to ftp.gnu.org.
220 GNU FTP server ready.
Name (ftp.gnu.org:optix2000): anonymous
<snipped banner>
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp>
```

This is not intended for SFTP/HTTP, where auth is almost always expected, but for protocols where auth is optional, and many use-cases and clients expect it to be optional.

The specific use-case is allowing anonymous/guest access to FTP and WebDAV.
Allowing blank passwords satisfies the ftp anonymous user problem, by creating a user called "anonymous" with no password.
Separately allowing read-only WebDAV with no login at all would be nice (have a setting to enable auth selectively for certain verbs).

**Comment by drakkan** [comment]
> This is primarily for WebDAV and FTP, where anonymous/no auth is allowed for read-only.
> 
> WebDAV (IIS, nginx, Apache) also allows no-auth for certain verbs (eg PROPFIND, GET) when configured that way. See https://live.sysinternals.com FTP servers (PureFTPd, vsftpd) will allow anonymous users with no password when that setting is enabled.
> 
> > they are common for legacy FTP server (a password is required and generally any password is accepted)
> 
> PureFTPd does not prompt for a password at all when the username is "anonymous". You can see an example of this with ftp://ftp.gnu.org.
> 
> ```
>  % ftp ftp.gnu.org
> Trying 209.51.188.20:21 ...
> Connected to ftp.gnu.org.
> 220 GNU FTP server ready.
> Name (ftp.gnu.org:optix2000): anonymous
> <snipped banner>
> 230 Login successful.
> Remote system type is UNIX.
> Using binary mode to transfer files.
> ftp>
> ```
> 

Other FTP implementation just accept any password (including an empty one), take a look here

```
ftp ftp.redhat.com
Connected to ftp.redhat.com.
220 Red Hat FTP server ready. All transfers are logged. (FTP) [no EPSV]
Name (ftp.redhat.com:nicola): anonymous
331 Please specify the password.
Password: 
230 Login successful.
```

This way, in SFTPGo, we can avoid to execute a database query when we receive the `USER` (to check if the anonymous flag is set) and another one when we receive the `PASS` command. I prefer this way.

This is a feature that I would like to add in the future but I have no definite plan for now

> This is not intended for SFTP/HTTP, where auth is almost always expected, but for protocols where auth is optional, and many use-cases and clients expect it to be optional.
> 
> The specific use-case is allowing anonymous/guest access to FTP and WebDAV. Allowing blank passwords satisfies the ftp anonymous user problem, by creating a user called "anonymous" with no password. Separately allowing read-only WebDAV with no login at all would be nice (have a setting to enable auth selectively for certain verbs).

**Comment by optix2000** [comment]
Thanks!
