### ISSUE TITLE
Auto-reload certificates

### ISSUE THREAD

**Issue by optix2000** [drakkan/sftpgo#936]
Would be nice if sftpgo could monitor and auto-reload certificates (possibly using something like [fsnotify](https://github.com/fsnotify/fsnotify)). This is useful when certificates are managed out-of-band (eg [cert-manager](https://cert-manager.io)) and saves some time setting up hooks to SIGHUP the process.

**Comment by drakkan** [comment]
Not sure, this will add complexity and therefore maintenance burden and probably other configurations and verifications eg. when the certificates are managed internally, the check is useless and mixed cases must also be managed.
In any case I would prefer to avoid fsnotity or the like, a simple check of the last modification time once or twice a day should suffice.

I think I'll add this feature if the request comes from a project sponsor, so the sponsorship will cover the maintenance cost
