### ISSUE TITLE
Can't Add SSH Keys to OIDC User

### ISSUE THREAD

**Issue by themooer1** [drakkan/sftpgo#942]
When a user logs in through OIDC they cannot edit their profile to add SSH keys.  The user was manually created.

Login with OIDC:
<img width="225" alt="Screen Shot 2022-07-31 at 11 39 20 PM" src="https://user-images.githubusercontent.com/8960671/182067827-198d7a15-694a-4344-abd6-5ff157952bc1.png">

Same user, manual login with a password set in the SFTPGo admin panel:
<img width="225" alt="Screen Shot 2022-07-31 at 11 44 08 PM" src="https://user-images.githubusercontent.com/8960671/182068163-ec7850ca-f8a6-4c62-a143-162966c6f8a7.png">

`pre_login_hook.sh`:
```
#! /bin/sh

export PATH=/var/lib/sftpgo/hooks:$PATH

if [ "$SFTPGO_LOGIND_PROTOCOL" == "OIDC" ]; then
    echo "$SFTPGO_LOGIND_USER" | jq  --compact-output '.+{"home_dir": ("/srv/sftpgo/"+.username),"permissions": {"/": ["*"]},"status":1}' # Create a new user
fi


echo "" # Do not create a user
```

**Comment by drakkan** [comment]
Hi,

thanks for your small sponsorship. 

The user profile page is disabled for users logging in via OIDC. This was initially done to avoid they can set a password and bypass the OIDC login, but now we can disable the login form so this must be changed, and you are right, they must be able to change their SSH keys anyway
