### ISSUE TITLE
Stat Error

### ISSUE THREAD

**Issue by JoeAtThru** [drakkan/sftpgo#945]
![image](https://user-images.githubusercontent.com/66972511/182721519-6d2aa781-804d-400a-a761-5341ee2a904d.png)
Hi there.

I was trying to investigate some 'errors' I've found in the logs (attached). These appears quite often during both FTP and SFTP uploads. 

I am aware of slowness/latency in the SMB device that is being used as the user's mount path that could be causing these stat errors. Hopefully there are some ways to minimize the impacts of this slowness.

I think this is the line that we are seeing (for FTP/SFTP), but not sure how to keep investigating from here. Thanks
https://github.com/drakkan/sftpgo/blob/71fff28d29806a8508b0bb544c9a2eb5cf0c8b94/internal/common/connection.go#L625

Thanks!

**Comment by drakkan** [comment]
Hi,

some SFTP/FTP clients issue a `stat` command before uploading a file to determine if they should resume an upload.
After the stat error, do you see an upload for the same filename in your logs? If so, you can safely ignore the stat error.

The error is "a no such file" error, so another possibility is that another process/client delete/remove the file at the same time

**Comment by JoeAtThru** [comment]
I think that's it. Thank you!
