### ISSUE TITLE
Can't create users from the interface

### ISSUE THREAD

**Issue by larnoux** [drakkan/sftpgo#947]
Hi,

I updated from 2.2 to 2.3 and I cannot create users anymore from the interface, the buttons are missing.
- I am starting with a fresh state, using the memory driver
- Running in Kubernetes from the official image
- Reverting to 2.2 puts the buttons back
- Imports are working and create users, but same issue regarding creation from the interface.
Am I missing something obvious?

**Comment by drakkan** [comment]
Hi,

please try to invalidate your browser cache, see #863 and #911

**Comment by larnoux** [comment]
How did I fail to find those!
Thanks a lot for the quick answer.
