### ISSUE TITLE
chinese language translate

### ISSUE THREAD

**Issue by iplaywind** [drakkan/sftpgo#949]
dear sir.
is there any plan to add language of chinese?
thansk.

**Comment by drakkan** [comment]
Hi,

this is a feature I would like to add in the future, but setting up and maintaining a proper translation system requires a fair amount of work, a [sponsorship](https://github.com/sponsors/drakkan) is required. Thank you

**Comment by Justsenger** [comment]
> Hi,
> 
> this is a feature I would like to add in the future, but setting up and maintaining a proper translation system requires a fair amount of work, a [sponsorship](https://github.com/sponsors/drakkan) is required. Thank you

I'm glad to help if i can.I mean some translation tasks.

**Comment by drakkan** [comment]
The new WebClient supports localizations as a test feature. Not sure if this will be included in v2.6.0, see more details in the post related to the new webclient
