### ISSUE TITLE
Default permissions of sqlite database too permissive?

### ISSUE THREAD

**Issue by coolbho3k** [drakkan/sftpgo#954]
The default permissions on `/var/lib/sftpgo/sftpgo.db` on my machine is `644` (`-rw-r--r--`).

Is it OK for everyone on the whole machine to be able to read the database? I know passwords are hashed, but maybe it's worth setting it to `600` by default instead so only the `sftpgo` user can read the file.

**Comment by drakkan** [comment]
Hi,

have you tried reading the database file with a user other than sftpgo? It should not work because the permissions on `/var/lib/sftpgo` is 750. The database file is just created with the default umask

**Comment by coolbho3k** [comment]
You're right! I was browsing around as sftpgo, and didn't consider the directory permissions.

**Comment by coolbho3k** [comment]
Going to close the issue. I verified that I can't read the db file as another user.
