### ISSUE TITLE
upgrade from 2.2.0 to 2.3.3 - database too old

### ISSUE THREAD

**Issue by psuter80** [drakkan/sftpgo#955]
hi
i upgraded my sftpgo installation on ubuntu using the ppa from version 2.2.0 to 2.3.3 
after that upgrade, sftpgo won't start anymore. it fails with these error messages in the syslog: 

```Aug 18 17:19:44 planb sftpgo[538149]: {"level":"error","time":"2022-08-18T17:19:44.549","sender":"dataprovider_sqlite","message":"database version 14 is too old, please see the upgrading docs"}
Aug 18 17:19:44 planb sftpgo[538149]: {"level":"error","time":"2022-08-18T17:19:44.549","sender":"dataprovider_sqlite","message":"database migration error: database version 14 is too old, please see the upgrading docs"}
Aug 18 17:19:44 planb sftpgo[538149]: {"level":"error","time":"2022-08-18T17:19:44.549","sender":"service","message":"error initializing data provider: database version 14 is too old, please see the upgrading docs"}
Aug 18 17:19:44 planb systemd[1]: sftpgo.service: Main process exited, code=exited, status=1/FAILURE
```

and `sftpgo initprovider` basically says the same: 
```# sftpgo initprovider
2022-08-18T17:23:16.498 INF Initializing provider: "sqlite" config file: "/etc/sftpgo/sftpgo.json"
2022-08-18T17:23:16.499 ERR database version 14 is too old, please see the upgrading docs
2022-08-18T17:23:16.499 ERR Unable to initialize/update the data provider: database version 14 is too old, please see the upgrading 
``` 

to fix this I downloaded the binary package for version 2.2.2 and ran initprovider with it. this upgraded the database from 14 to 15 and resolved the issue. 

the documentation on your main page says, that upgrades are supported "from the previous release branch to the current one" and lists these examples: 

from 1.2.x to 2.0.x
from 2.0.x to 2.1.x and so on.

so I would assume that upgrading from 2.2.0 to 2.3.3 should be okay given the description above.

i guess we can agree, that a package should not brake due to a normal apt upgrade. so here are a few proposals / requests how to resolve this or turn this at least into a smaller issue: 

- update the documentation with more accurate examples that make it understandable, what I did wrong here ;) 
- prevent apt from updating in a too large step (don't know if the dpkg package format supports something like that to be honest)
- make sftpgo capable to upgrade from some more versions back than just the last one
- produce a more helpful error message. the problem here is, that the user has no idea what sftpgo version relates to version 14 and 15 of the database. the error message could either say tell us which intermediate sftpgo version would cover the next step, so the user would at least know which version to look for, or it could reference to a documentation that has a table that clearly lists which versions can't be jumped over.

and please understand, that his is me complaining on a high level, i love this tool, thank you for sharing it with us.

**Comment by drakkan** [comment]
Hi,

I understand your complaint and I am sorry for the inconvenience. I will try to improve backward compatibility in the future, but please understand that this is a lot of testing and therefore time-consuming. At the moment, in the time that I can dedicate to the project, I am focusing on new features. Much depends on the sponsorships I will receive. Using SFTPGo and not donating even $ 5/month doesn't help much :smile: 
If all users behaved like this SFTPGo has no future, I don't use it in production myself.

In the upgrading doc you can read:

> It is recommended to always install the latest available minor version, ie do not install 1.2.0 if 1.2.2 is available.

**Comment by psuter80** [comment]
hi 
thanks for your quick reply. i didn't mean to actually complain.. maybe the word choice was wrong when i stated i was "complainig on a high level" .. this is something we would say in my native language to say that it's not a big deal and basically not of any importance or urgance.. maybe this saying does not exist in that way in other languages.. so i apologize if i gave you the impression i felt i could actually complain about something i am using for free or give you shit aobut it.. that was not my intent.. in contrary, i wanted to post this here to help other users who may run into the same issue and i wanted to make a few suggestions how this could be solved easily (especially my last point, of improving the error message, telling the user which version to use to do the next intermediate step, that something that does not add a lot of complexity and does not need special testing, only a list of version numbers which would cover the next migration step on the database schema side. 
i wanted to help to improve your software, that's all. 
in any case, i will mark this issue as closed as i found (and published here) a solution to the issue at hand (which was a problem in upgrading from one specific version to another) 

cheers
Pascal

**Comment by drakkan** [comment]
> hi thanks for your quick reply. i didn't mean to actually complain.. maybe the word choice was wrong when i stated i was "complainig on a high level" .. this is something we would say in my native language to say that it's not a big deal and basically not of any importance or urgance.. maybe this saying does not exist in that way in other languages.. so i apologize if i gave you the impression i felt i could actually complain about something i am using for free or give you shit aobut it.. that was not my intent.. in contrary, i wanted to post this here to help other users who may run into the same issue and i wanted to make a few suggestions how this could be solved easily (especially my last point, of improving the error message, telling the user which version to use to do the next intermediate step, that something that does not add a lot of complexity and does not need special testing, only a list of version numbers which would cover the next migration step on the database schema side. i wanted to help to improve your software, that's all. in any case, i will mark this issue as closed as i found (and published here) a solution to the issue at hand (which was a problem in upgrading from one specific version to another)
> 
> cheers Pascal

No problem, I know this isn't very user friendly but my time is limited and I prefer to add new features for now. I hope I can spend more time on the project in the future.

As for the message I will try to add something better, the problem here is that when I tagged v2.2.0 I didn't know I would add a new database migration in v2.2.2
