### ISSUE TITLE
Web UI problem after update

### ISSUE THREAD

**Issue by 0sorkon** [drakkan/sftpgo#957]
Hello! 
After update from 2.2.2 -> 2.3.3 row with buttons was disappear from web admin UI . 
First screenshot below - from test server, second - from production, both v2.3.3 and from admin user with full rights.
https://i.imgur.com/RUCM1cq.png
https://imgst.in/ih/chrome_Jb474kDpqi.jpg

**Comment by drakkan** [comment]
See these related issues #863, #911, #947

**Comment by 0sorkon** [comment]
yes, my fault, it is a browser cache, ctrl+f5 was fix this. Close
