### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by everserve** [drakkan/sftpgo#96]
I can't find it in the docs and the description sounded hopeful, but is it possible to use sftpgo for SSH commands? I'm looking to use composer in a chrooted or jailed environment.
I got sftpgo to work for file transfers with mysql as provider and pub keys as auth but getting "Request Failed" when I try to ssh into it.

Thanks!

**Comment by drakkan** [comment]
Hi,

sftpgo is aimed to file transfers, only some ssh commands are available, please take a look at `enabled_ssh_commands` [here](https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md) for the full list.

If you need commands useful for file transfers I could consider to add them but no shell login is planned

**Comment by everserve** [comment]
Hi @drakkan tahnks for getting back so quickly.
I saw that and assumed (wishfully) I could add my own commands.
So adding libraries for instance to %h/jail or something wouldn't work? Too bad, really loved your work on this app. As a dev I was happy with json config and the rest api.

Back to reading the docs on jailkit ;(

Cheers

**Comment by drakkan** [comment]
I could also allow arbitrary commands but not shell access, can you please better explain what do you need with a step by step example? Thanks

**Comment by everserve** [comment]
I'm a web developer with my own dedicated box and need to add jailed shell access to others.
Typically [composer](https://getcomposer.org/doc/), [nodejs](https://nodejs.org/en/) (both dependency managers) and php need to be executed from the command line.

[Jailkit](https://olivier.sessink.nl/jailkit/) is an option and I found a few other ways but the setup requires copying all the libraries to be inside the user chrooted directory (obviously) and that sounds like maintenance hell.

I thought sftpgo would be able to provide a jailed shell but I now understand it better.

Hope that clarifies it, if not let me know. And if it's possible to support a limited shell, that would be great!

Thanks for your time, I can tell you did a great job on this!

**Comment by drakkan** [comment]
No sorry a jailed shell is not planned, at least for now.

SFTPGo is an SFTP server that support some SSH commands useful for file transfers (rsync,scp ecc..), so you can use it if you want to share files, not for providing generic shell access

**Comment by sergiz** [comment]
What about archive/extract commands, are those in the plans? It would be very useful when transfering a large amount of files.

**Comment by drakkan** [comment]
Hi, which commands do you like to use? tar?

**Comment by sergiz** [comment]
Yeah mostly tar. However, zip/unzip would be a nice too.

**Comment by drakkan** [comment]
OK, I'll evaluate to add these commands. 

Generally speaking adding a new system command is really easy but we have to check that it does not leak the real file paths. A system command interacts with the filesystem directly and it is not aware about virtual folders and  files extensions filters, quota management is problematic ecc.. To be able to handle these things we have to reimplement the system command ourself (for example for scp we don't use the system command) and this require a lot more effort and testing.

**Comment by sergiz** [comment]
Great, thanks! 

Yeah, I understand it's a pretty complicated thing, but I hope you manage to find a secure way for that.
