### ISSUE TITLE
External Auth Question

### ISSUE THREAD

**Issue by zorkleplex** [drakkan/sftpgo#961]
Good Morning!

  Firstly - awesome work!  

  I wanted to see if you could help point me in the right direction.  I have an external auth hook which is processing authentications.  Per documentation 

> If authentication succeeds the HTTP response code must be 200 and the response body can be:

>a valid SFTPGo user serialized as JSON. The user will be added/updated within the defined data provider

>empty, the existing SFTPGo user does not need to be updated. Please note that in versions 2.0.x and earlier an empty response was interpreted as an authentication error

 I am running a container with version 

>drakkan/sftpgo:v2.3.3
 
 I like the pattern of returning only status codes with an empty body.  So I am returning a 200 for happy users and an appropriate HTTP Status Code when things go sideways.  Indeed I am seeing the log statements ( for a good authentication ) 

>{"level":"debug","time":"2022-08-23T10:25:19.042","sender":"dataprovider_postgresql","message":"external auth hook executed, response code: 200"}
{"level":"debug","time":"2022-08-23T10:25:19.042","sender":"dataprovider_postgresql","message":"external auth completed for user \"simple\", elapsed: 173.234ms"}
{"level":"debug","time":"2022-08-23T10:25:19.042","sender":"dataprovider_postgresql","message":"empty response from external hook, no modification requested for user \"simple\" id: 3"}

The next log message I see is 

>{"level":"debug","time":"2022-08-23T10:25:19.113","sender":"connection_failed","client_ip":"172.25.0.1","username":"simple","login_type":"password","protocol":"SSH","error":"invalid credentials"}

This is from an SFTP terminal command line execution like 

>sftp simple@localhost   

If I change my external auth to return a JSON user object along with the status code of 200 I do not get an error and the external auth hook works as expected.  I was hoping though to leverage the scheme of not updating the user upon login.  

More than likely I have misinterpreted the documentation and/or missed a step in my configuration.  Is there a setting that would enforce an additional credential check?  I couldn't interpret one from the source.

Thank you!

**Comment by drakkan** [comment]
> Good Morning!
> 

Hi

> Firstly - awesome work!
> 
> I wanted to see if you could help point me in the right direction. I have an external auth hook which is processing authentications. Per documentation
> 
> > If authentication succeeds the HTTP response code must be 200 and the response body can be:
> 
> > a valid SFTPGo user serialized as JSON. The user will be added/updated within the defined data provider
> 
> > empty, the existing SFTPGo user does not need to be updated. Please note that in versions 2.0.x and earlier an empty response was interpreted as an authentication error
> 
> I am running a container with version
> 
> > drakkan/sftpgo:v2.3.3
> 
> I like the pattern of returning only status codes with an empty body. So I am returning a 200 for happy users and an appropriate HTTP Status Code when things go sideways. Indeed I am seeing the log statements ( for a good authentication )
> 
> > {"level":"debug","time":"2022-08-23T10:25:19.042","sender":"dataprovider_postgresql","message":"external auth hook executed, response code: 200"}
> > {"level":"debug","time":"2022-08-23T10:25:19.042","sender":"dataprovider_postgresql","message":"external auth completed for user "simple", elapsed: 173.234ms"}
> > {"level":"debug","time":"2022-08-23T10:25:19.042","sender":"dataprovider_postgresql","message":"empty response from external hook, no modification requested for user "simple" id: 3"}
> 
> The next log message I see is
> 
> > {"level":"debug","time":"2022-08-23T10:25:19.113","sender":"connection_failed","client_ip":"172.25.0.1","username":"simple","login_type":"password","protocol":"SSH","error":"invalid credentials"}
> 

I think the password used in the previous login and stored in the SFTPGo data provider does not match the current one. If you don't change the user, the stored credentials must match with the current ones.

> This is from an SFTP terminal command line execution like
> 
> > sftp simple@localhost
> 
> If I change my external auth to return a JSON user object along with the status code of 200 I do not get an error and the external auth hook works as expected. I was hoping though to leverage the scheme of not updating the user upon login.
> 
> More than likely I have misinterpreted the documentation and/or missed a step in my configuration. Is there a setting that would enforce an additional credential check? I couldn't interpret one from the source.
> 
> Thank you!

**Comment by tooptoop4** [comment]
does that mean password rotations in external auth won't work? since data provider expects the very first password to not change?

**Comment by zorkleplex** [comment]
Ok - my intent was to rely on external auth only so I wouldn't have to keep a 'secret' in two places.

Thank You!

**Comment by tooptoop4** [comment]
@zorkleplex maybe if u return a json body it will update the pw in data provider? not sure

**Comment by zorkleplex** [comment]
It does and works if do return a JSON body, I was trying to think of a suggested update to the documentation about this.  In essence, if you return an empty body then the password within SFTPGO and the password in the external authentication service must be in sync...

**Comment by drakkan** [comment]
@zorkleplex, I'll update the docs this weekend, thanks for noticing. 
An alternative strategy that might suit your use case is to always return a user from your hook and enable external authentication cache on the SFTPGo side. From the docs:

> You can instruct SFTPGo to cache the external user by setting an external_auth_cache_time in user object returned by your hook. The external_auth_cache_time defines the cache time in seconds.

**Comment by zorkleplex** [comment]
Very cool and thank you for pointing me in the right direction.  Excellent project!
