### ISSUE TITLE
Can't figure out if configuration is applied

### ISSUE THREAD

**Issue by volvoplz** [drakkan/sftpgo#963]
I have "Access denied" issues overtime because of sftpgo defender/rate limiter mechanisms. I'm trying to use env variables to disable both these mechanisms but I can't figure out if my configuration is even applied. The behavior doesn't change at all, and the logs are no help.

Is there  any way, in the admin UI or on an endpoint, to see the current configuration values that are actually applied?

**Comment by drakkan** [comment]
The loaded configuration is logged at startup. Just read your logs

**Comment by drakkan** [comment]
No time/motivation sorry. I just added the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by drakkan** [comment]
closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
