### ISSUE TITLE
web_root not applied after oidc auth

### ISSUE THREAD

**Issue by pfpulux** [drakkan/sftpgo#966]
If via the config a `"web_root": "/sftp/"`is applied the normal login works like expected behind a nginx server with:

```
        location /sftp/ {
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $http_host;
            proxy_pass http://127.0.0.1:8080/sftp/;
        }
```
but after auth via `Login with OpenID` in login the static-files will not searched under /sftp/static/... It request from /static/...

The Auth is configured from the `docs` and worked as expected after the `web_root` is set to `/`.

**Comment by drakkan** [comment]
closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
