### ISSUE TITLE
build issue with alpine dockerfile

### ISSUE THREAD

**Issue by metronlab-it** [drakkan/sftpgo#97]
Hi there,

I'm trying to run a docker build using the alpine Dockerfile from docker/sftpgo/alpine/ and it's giving me build errors:

```
package github.com/nathanaelle/password: code in directory /go/src/github.com/nathanaelle/password expects import "github.com/nathanaelle/password/v2"
The command '/bin/sh -c apk add --no-cache git gcc g++ ca-certificates   && go get -d github.com/drakkan/sftpgo' returned a non-zero code: 1
```
Am running the build as `git clone https://github.com/drakkan/sftpgo.git &&   cd sftpgo &&   sudo docker build -t sftpgo docker/sftpgo/alpine/`. This seems to be a recent problem as it was working a while ago (last week maybe?), but I cleaned the build cache since and now it's broken.

**Comment by drakkan** [comment]
Hi, 

I think the issue is related to the recent nathanaelle/password v2 update, 

please clean the cache again and rebuild using the latest version, it should work now.

Please let me know if the issue is fixed, thanks!

**Comment by metronlab-it** [comment]
Yup, that works now, thanks!
