### ISSUE TITLE
Admin authorization with LDAP/AD

### ISSUE THREAD

**Issue by Jacuo** [drakkan/sftpgo#972]
Is there any way to accomplish Admin authorization with LDAP/AD ? As I understand external_auth work only with "common" users ?

**Comment by drakkan** [comment]
Just read the [docs](https://github.com/drakkan/sftpgo/blob/main/docs/external-auth.md) until the end.

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by Jacuo** [comment]
In docs there is nothing about this feature. But docs are not covering every ascpect of this software. I didn`t want to step by step help, but simple answer yes/no.  Eh.

**Comment by drakkan** [comment]
sorry I misread your question. External auth only works for users, not admins
