### ISSUE TITLE
Use IAM roles for Amazon EC2

### ISSUE THREAD

**Issue by valdemarpereira-vonage** [drakkan/sftpgo#974]
Hi,
I am trying to use sftpgo with an S3 backend for storage using  IAM role as credentials.

So far I have hit a block as I cannot make it work. Even though I'm using IAM roles I'm getting a error message saying that `non-empty Access Key (AKID) must be provided in the credential`.

Here is the full log message:

`{
   "level":"debug",
   "time":"2022-09-06T11:00:54.150",
   "sender":"SFTP",
   "connection_id":"SFTP_a7cac43eab460143a87b7b0722bb2518bc8c5f7562714bcbbcdf6e4b8946cfee_1",
   "message":"error listing directory: operation error S3: ListObjectsV2, https response error StatusCode: 400, RequestID: 1RD5NRJ9Z8NZVTB4, HostID: CtCRNBsWKpjc8FVqs6YrgRcgjnlxVSZnGYziC2MZLpJ/rmyuLhd+t53e2anSoGFd5fKk3QtXM4g=, api error AuthorizationHeaderMalformed: The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential."
}`

Here is the UI for a user using S3 as the filesystem with IAM Role
![sftpgo](https://user-images.githubusercontent.com/66251676/188623031-43e7d37b-3115-46d6-8dad-3bc2b05c839b.jpg)

Thank you in advance for any help

**Comment by drakkan** [comment]
closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy).

This question was asked recently just check the closed issues, thanks
