### ISSUE TITLE
failed to test sftpgo on minio or digital ocean spaces (s3)

### ISSUE THREAD

**Issue by amitm02** [drakkan/sftpgo#98]
1) I've been trying to test sftp first on local minio.
I've failed as the default minio is without SSL. it would be great to have to option to configure S3 without SSL (for dev).

2) next I've tried to run it against spaces in DigitalOcean. I've received 
`{... "message":"error listing directory: RequestError: send request failed\ncaused by: Get \"**********": x509: certificate signed by unknown authority"}`

I'm unsure if its an issue with DigitalOcean of sftpgo, but never the less, it fails to work by following the documentation instructions of sftpgo.

UPDATE:
Found [this](https://github.com/drakkan/sftpgo/pull/71).
I've managed to upload to DigitalOcean spaces. I do think a better docs is need about uncommenting that relevant line in the Dockerfile

**Comment by drakkan** [comment]
> 1. I've been trying to test sftp first on local minio.
>    I've failed as the default minio is without SSL. it would be great to have to option to configure S3 without SSL (for dev).

I mainly developed the S3 backend against minio on localhost (I use `http://127.0.0.1:9000/` as endpoint) so it works for me, can you please share your error logs? 

> 2. next I've tried to run it against spaces in DigitalOcean. I've received
>    `{... "message":"error listing directory: RequestError: send request failed\ncaused by: Get \"**********": x509: certificate signed by unknown authority"}`
> 
> I'm unsure if its an issue with DigitalOcean of sftpgo, but never the less, it fails to work by following the documentation instructions of sftpgo.
> 
> UPDATE:
> Found [this](https://github.com/drakkan/sftpgo/pull/71).
> I've managed to upload to DigitalOcean spaces. I do think a better docs is need about uncommenting that relevant line in the Dockerfile

You are right docs can be improved, are you interested to send a pull request? thanks

**Comment by amitm02** [comment]
I'm not a go developer (we mainly use nodesjs) so I won't be able to help in active development.
We are looking very seriously to use this (amazing) project in out platform. So I'll be able to share any bugs or insight we may discover.
E.g I think you can safely put in the docs that the system supports "DigitalOcean spaces".
any recommendation how to go about testing sftpgo with local minio?

**Comment by drakkan** [comment]
> I'm not a go developer (we mainly use nodesjs) so I won't be able to help with active development.
> We are looking very seriously to use this (amazing) project in our platform. So I'll be able to share any bugs or insight we may discover.
> E.g I think you can safely put in the docs that the system supports "DigitalOcean spaces".
> any recommendation how to go about testing sftpgo with local minio?
> 
> Update:
> using http is not strictly for dev mode. if minio is used within a private cluster, e.g k8s, many times it is deployed without SSL
> 
> > I mainly developed the S3 backend against minio on localhost (I use http://127.0.0.1:9000/ as endpoint) so it works for me, can you please share your error logs?
> 
> {"level":"debug","time":"2020-03-22T13:55:57.877","sender":"sftpd","connection_id":"17ed0e897b916fd691384b4c78b64903f5313409ffcd699e4cd0c8278e2c88ad","message":"requested list file for dir: "/""}
> {"level":"warn","time":"2020-03-22T13:55:58.189","sender":"sftpd","connection_id":"17ed0e897b916fd691384b4c78b64903f5313409ffcd699e4cd0c8278e2c88ad","message":"error listing directory: RequestError: send request failed\ncaused by: Get "[https://127.0.0.1:9000/ttt?delimiter=%2F&list-type=2&prefix=\](https://127.0.0.1:9000/ttt?delimiter=%2F&list-type=2&prefix=%5C)": dial tcp 127.0.0.1:9000: connect: connection refused"}

it seems that minio is not running on port 9000

**Comment by amitm02** [comment]
I have 
```
s3config:{
"bucket":"ttt",
"region":"local",
"access_key": "admin",
"access_secret":"$aes$82c8e004d7dfb8cd86cb3cc62976e7ce$ab9a3c4742154ef24de6440d3c458cb11d908dcad0284ed9fedb88398ad2f37777b8f32d",
"endpoint":"http://127.0.0.1:9000"
}
```
I'm running minio via:
```
version: '3.5'
services:
  minio:
    image: minio/minio
    command: server /data
    environment: 
      MINIO_ACCESS_KEY: "admin" 
      MINIO_SECRET_KEY: "password"
    ports:
      - 9000:9000
```

**Comment by drakkan** [comment]
Hi,

regarding the docs is adding something like this in s3.md clear enough?

"""
Most S3 backends requires HTTPS connections so if you are running SFTPGo as docker image please be sure to uncomment the line that install `ca-certificates`, inside your `Dockerfile`, to be able to properly verify certificate authorities. 
"""

Regarding minio, this log:

```
dial tcp 127.0.0.1:9000: connect: connection refused
```

indicates that SFTPGo container is unable to connect on port 9000, 

can you please run a command like this `curl "http://127.0.0.1:9000"` from the sftpgo container? thanks

**Comment by amitm02** [comment]
please ignore the "connect: connection refused" issue. I trying to access my computer 127.0.0.1 from within sftpgo container, which is stupid
