### ISSUE TITLE
How should i pass json key file in gcsconfig-credentials-payload

### ISSUE THREAD

**Issue by deepakdeshekar** [drakkan/sftpgo#984]
Hi, i want to create sftpGo user via postman API . In gcsconfig credential payload, what should I pass? 
The payload data type is a string and I have JSON key . 

 "gcsconfig": {
            "bucket": "xxx",
            "credentials": {
                "status": "Plain",
                "**payload**":  "",
                "key" :

**Comment by drakkan** [comment]
As string. Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by deepakdeshekar** [comment]
Hi @drakkan, 
I have to stringify the JSON key and passed in payload, the user has been created but getting the below issue 

`Failed to get directory listing: Unable to get directory contents`
