### ISSUE TITLE
Defender would work even if enabled config is turned false

### ISSUE THREAD

**Issue by silent-lad** [drakkan/sftpgo#985]
I recently encountered this when I turned of the defender by its enabled flag and it was still enabled. 
Basically the check to enable defender is 
`Config.defender == nil` https://github.com/drakkan/sftpgo/blob/58311ab4e40310480fef946e3e03fe74a72e10a0/internal/common/common.go#L252

Whereas it should be `Config.defender == nil | | Config.defender.enabled == false`

**Comment by drakkan** [comment]
You are wrong `Config.defender` is `nil` if the defender is not enabled.

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
