### ISSUE TITLE
 error loading required template: open templates\common\sftpgo.css

### ISSUE THREAD

**Issue by igitur** [drakkan/sftpgo#986]
Hi,

I install sftpgo on Windows 10 64b via [scoop package manager](https://scoop.sh). I'm not sure whether that's relevant.

sftpgo fails to run when I don't launch it from the installation directory. e.g.:

```
 C:\temp〉sftpgo.exe serve
2022-09-13T18:00:26.590 INF telemetry server not started, disabled in config file
2022-09-13T18:00:26.596 INF No host keys configured and "id_rsa" does not exist; try to create a new host key
2022-09-13T18:00:26.622 ERR error loading required template: open templates\common\sftpgo.css: The system cannot find the path specified.
panic: open templates\common\sftpgo.css: The system cannot find the path specified.

goroutine 132 [running]:
github.com/drakkan/sftpgo/v2/util.LoadTemplate(0xc000054080?, {0xc0003aa1d8?, 0x7ff64cd4070b?, 0xf?})
        github.com/drakkan/sftpgo/v2/util/util.go:351 +0x16e
github.com/drakkan/sftpgo/v2/httpd.loadAdminTemplates({0xc0004de530, 0x9})
        github.com/drakkan/sftpgo/v2/httpd/webadmin.go:416 +0x30cc
github.com/drakkan/sftpgo/v2/httpd.(*Conf).Initialize(0xc0000efce0, {0x7ff64cff014a, 0x1}, 0x0?)
        github.com/drakkan/sftpgo/v2/httpd/httpd.go:810 +0xd6a
github.com/drakkan/sftpgo/v2/service.(*Service).startServices.func2()
        github.com/drakkan/sftpgo/v2/service/service.go:226 +0x10e
created by github.com/drakkan/sftpgo/v2/service.(*Service).startServices
        github.com/drakkan/sftpgo/v2/service/service.go:224 +0x45b
```

If I launch it from the installation directory (which is actually a symlinked dir), ot works:
```
D:\scoop\apps\sftpgo\2.3.4〉sftpgo.exe serve
2022-09-13T18:05:49.653 INF telemetry server not started, disabled in config file
```

This is probably a very small thing, but it's just a bit weird to me. I would expect sftpgo to run correctly regardless of the startup directory. Hopefully this is an easy fix?

**Comment by drakkan** [comment]
I have never used the scoop package manager, something like this should work from any directory:

```
sftpgo.exe serve -c D:\scoop\apps\sftpgo\2.3.4
```

**Comment by igitur** [comment]
> I have never used the scoop package manager, something like this should work from any directory:
> 
> ```
> sftpgo.exe serve -c D:\scoop\apps\sftpgo\2.3.4
> ```

Yes, this does work, thanks. But for convenience, can that parameter not be made optional? I'll even attempt a PR if you agree with the principle.

**Comment by drakkan** [comment]
This is Windows specific. On Linux SFTPGo already works from any directory (using the default config) because static files are automatically installed/searched in well know locations (`/usr/share/sftpgo`). 

There are several ways to set the config dir, for example the package manager could set an env var when it installs SFTPGo. It is also possibile to set additional search paths for static files at build time and, in the current development version, you can also build SFTPGo with static files embedded in the binary.

**Comment by drakkan** [comment]
Feel free to provide a PR with a better error message, thanks

**Comment by zmyxpt** [comment]
For scoop user, ```scoop prefix <software_name>``` return install directory of the software.
So just use this command instead:
```sftpgo serve -c $(scoop prefix sftpgo)```
