### ISSUE TITLE
feature: add file only webUI

### ISSUE THREAD

**Issue by tooptoop4** [drakkan/sftpgo#988]
right now the webUI has many options like adding sftpkey, changing password, adding shares..etc would be great to have config that makes the webUI only have simple file interaction buttons enabled...ie upload/rename file

**Comment by drakkan** [comment]
This is already supported, you can configure the WebClient UI so a user can only upload/rename and view its profile
![Schermata del 2022-09-15 19-57-46](https://user-images.githubusercontent.com/553263/190476676-41498087-46f4-41ef-98d5-04f8a5ca729b.png)


![Schermata del 2022-09-15 19-58-08](https://user-images.githubusercontent.com/553263/190476709-9889191b-2a73-4b10-aaa2-2dca31ac1b24.png)

**Comment by tooptoop4** [comment]
anyone know how?

**Comment by tooptoop4** [comment]
found out how by inspecting the response of user/ route of the api

solution is then to change external_auth json to return this within the response json:
`,"filters":{"tls_username":"None","hooks": {"external_auth_disabled":false,"pre_login_disabled":false,"check_password_disabled":false},"web_client":["publickey-change-disabled","mfa-disabled","password-change-disabled","api-key-auth-change-disabled","info-change-disabled","shares-disabled","password-reset-disabled","shares-without-password-disabled"],"totp_config":{"secret":{}}}`
