### ISSUE TITLE
Webhook on upload: no file size

### ISSUE THREAD

**Issue by zlodes** [drakkan/sftpgo#991]
Hi!

Sometimes upload event goes without file_size property.
Previous time it was, but now there is no file_size key in json object.

Used SFTP for uploading and S3-connected folder as destination.
Are there any conditions to include file_size to the webhook request? 

```json
{
  "action": "upload",
  "username": "username was there",
  "path": "limits/20220909_183449.lim",
  "virtual_path": "/limits/20220909_183449.lim",
  "fs_provider": 1,
  "bucket": "bucket name was there",
  "endpoint": "S3 endpoint was there",
  "status": 1,
  "protocol": "SFTP",
  "ip": "IP WAS THERE",
  "session_id": "SFTP_31c605ed49df8553504a3d2012695915bee02de992e9f7737c490984c8582162_1",
  "timestamp": 1663309501931101400
}
```

**Comment by drakkan** [comment]
This is documented, closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
