### ISSUE TITLE
Cannot install on Fedora CoreOS

### ISSUE THREAD

**Issue by Darkflicker** [drakkan/sftpgo#992]
Hi,

I added the YUM repo and encountered an error when I tried to install sftpgo by running 'rpm-ostree install sftpgo'.

error: Importing RPMs: Importing package 'sftpgo' : Analyzing /srv/sftpgo: Unsupported path; see https://github.com/projectatomic/rpm-ostree/issues/233

![Screenshot_20220916_203159](https://user-images.githubusercontent.com/26320874/190673211-6465b644-360c-49be-a627-83a948d99abc.png)

Great software btw.

**Comment by drakkan** [comment]
Hi,

I am not familiar with CoreOS, maybe the problem is related to the empty `/srv/sftpgo` directory contained in the RPM
