### ISSUE TITLE
FTPS and Subdirectories of the FTP location

### ISSUE THREAD

**Issue by j-lanham** [drakkan/sftpgo#993]
I have an SFTPGO FTPS site that I'm trying to put into production to replace an old filezilla server.  For some reason, it allows it to write to the subdirectories under the FTP home directory for the user, but when they try to read from it, it ignores the subdirectory of the associated physical directory on download.

Here's a log entry for an upload.  As you can see it references the subdirectory when writing the file.

**{"level":"info","time":"2022-09-16T10:45:50.479","sender":"Upload","local_addr":"99.99.99:21","remote_addr":"99.99.99.99:40456","elapsed_ms":518,"size_bytes":13184,"username":"XXXXFTP","file_path":"C:\\inetpub\\ftproot\\LocalUser\\XXXX\\outbound\\file_name.json","connection_id":"FTP_0_41","protocol":"FTP","ftp_mode":"passive"}**

Here's a download request.   The file named is actually in a subdirectory of the path called inbound.

**{"level":"error","time":"2022-09-16T11:00:34.744","sender":"FTP","connection_id":"FTP_0_42","message":"could not open file \"C:\\\\inetpub\\\\ftproot\\\\LocalUser\\\\XXXX\\\\filename.txt\" for reading: open C:\\inetpub\\ftproot\\LocalUser\\XXXX\\filename.txt: The system cannot find the file specified."}**

I've gone through and reverified the file permissions and other stuff like that.  Could it be that they are changing to the subdirectory and trying to download the file based on current directory?  If so, is the system not keeping the current directory location for the user to use to download the file from?  This is the correct root directory for the account.

**Comment by drakkan** [comment]
Hi,

I'm not sure. Keeping the current directory location should work. FTP is a very strange protocol, please try enabling the [debug mode](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L121) to better understand what is happening. Thanks

**Comment by j-lanham** [comment]
Actually, I just got through stopping SFTPGO and restarting the Filezilla Server to at least capture the command set they're using to establish a successful connection and download/rename command set that they're going through and I will upload it here.  I was also going to walk through the steps with a local connection, although I don't know if I can issue raw commands.  I will post the successful command sequence as well as turn on debug mode and wait for the unsuccessful one and I will dig through it to see what's going on.

According to the filezilla logs, the following is the command they are using to download the file.
(000002)9/16/2022 12:00:39 PM - XXXXX (99.99.99.99)> RETR inbound/filename.txt

 Once they attempt to download the file through SFTPGO and I can get a debug log from the attempt I'll know more.

It's **not** the change directory thing.  I was making an assumption.

**Comment by j-lanham** [comment]
Okay, I think I know what's going on.  

"line":"PBSZ 0","message":"Received line"}
"line":"200 Whatever","message":"Sending answer"}
"line":"PROT P","message":"Received line"}
"line":"200 OK","message":"Sending answer"}
"line":"TYPE A","message":"Received line"}
"line":"200 Type set to ASCII","message":"Sending answer"}
"line":"PASV","message":"Received line"}
"line":"227 Entering Passive Mode (99,999,99,9999,999,999)","message":"Sending answer"}
**"line":"NLST inbound","message":"Received line"}**
"line":"150 Using transfer connection","message":"Sending answer"}
"remoteAddr":"99.99.99.9999:99999","localAddr":"99.99.99.98:99998","message":"Transfer connection opened"}
"message":"Transfer connection closed"}
"line":"226 Closing transfer connection","message":"Sending answer"}
"line":"TYPE I","message":"Received line"}
"line":"200 Type set to binary","message":"Sending answer"}
"line":"PASV","message":"Received line"}
"line":"227 Entering Passive Mode (99,999,99,999,999,99)","message":"Sending answer"}
**"line":"RETR filename.txt","message":"Received line"}**
"message":"could not open file \"C:\\\\inetpub\\\\ftproot\\\\LocalUser\\\\XXXX\\\\filename.txt\" for reading: open C:\\inetpub\\ftproot\\LocalUser\\XXXX\\filename.txt: The system cannot find the file specified."}

As you can see from the highlighted lines, they are issuing an NLST inbound command and getting a file list back, but the RETR does not have /inbound in front of it, but it does in the FileZilla logs.  That makes me assume NLST has the folder as part of the file name in FileZilla but doesn't on the SFTPGO side.  I don't know the actual differences because I don't have a command line client that connect through FTPS to issue the commands and see the results manually.

### Filezilla Logs
PBSZ 0
200 PBSZ=0
PROT P
200 Protection level set to P
TYPE A
200 Type set to A
PASV
227 Entering Passive Mode (99,999,99,999,199,119)
**NLST inbound**
150 Opening data channel for directory listing of "/inbound"
TLS connection for data connection established
226 Successfully transferred "/inbound"
TYPE I
200 Type set to I
PASV
227 Entering Passive Mode (99,999,99,999,198,7)
**RETR inbound/filename.txt**
150 Opening data channel for file download from server of "/inbound/filename.txt"
TLS connection for data connection established
226 Successfully transferred "/inbound/filename.txt"
TYPE A
200 Type set to A
PASV
227 Entering Passive Mode (99,999,99,999,196,34)
RETR inbound/filename.txt
150 Opening data channel for file download from server of "/inbound/filename.txt"
TLS connection for data connection established
226 Successfully transferred "/inbound/filename.txt"
RNFR inbound/filename.txt
350 File exists, ready for destination name.
RNTO processed/filename.txt
250 file renamed successfully
disconnected.

**Comment by drakkan** [comment]
Fixed in v2.3.5, thanks for the useful debugging information

**Comment by j-lanham** [comment]
Thanks so much, Nico.

Jeff
