### ISSUE TITLE
Event hook does not trigger when a file larger than 1 MB is uploaded.

### ISSUE THREAD

**Issue by codecrack3** [drakkan/sftpgo#997]
Hello, I set up a file upload event trigger action. It worked while the file size was less than 1 MB, but if the file size is greater than 1 MB, the event is not triggered. Help me find a solution to this problem, please.

note: only winscp not working, scp is working properly

**Comment by drakkan** [comment]
take a look at your logs. I guess WinSCP loads files with a filepart extension and renames them after the upload is complete.

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)
